/// Tutte le stringhe di interfaccia italiane (onboarding, lobby, giochi,
/// errori...). L'app le legge tramite `AppTexts`.
class ContentItApp {
  const ContentItApp._();

  static const Map<String, String> ui = {
    'app.tagline': 'Il party game per chi ha\nun telefono a testa.',
    'common.retry': 'Riprova',
    'common.cancel': 'Annulla',
    'common.continue': 'CONTINUA',
    'common.back_home': 'TORNA ALLA HOME',
    'common.loading': 'Un attimo…',
    'common.you': 'tu',
    'onboarding.slide1.title': 'La serata prende\nuna piega inaspettata',
    'onboarding.slide1.body':
        'Ognuno col suo telefono, tutti nella stessa stanza. Joyo collega gli schermi, voi create il caos.',
    'onboarding.slide2.title': 'Codice alla mano,\nsi entra nel vivo',
    'onboarding.slide2.body':
        'Apri la stanza, urla il codice e guarda gli amici fiondarsi dentro in pochi secondi.',
    'onboarding.slide3.title': 'Sei giochi per\nnon annoiarsi mai',
    'onboarding.slide3.body':
        'Vota i tuoi amici, inventa balle colossali o sfida la sorte con la bottiglia. Velocità massima.',
    'onboarding.slide4.title': 'Decidi tu\nquanto osare',
    'onboarding.slide4.body':
        'Modalità Normale per scaldarsi, Mix per movimentare la serata, Hot per quando cadono le maschere.',
    'onboarding.language': 'In che lingua giocate?',
    'onboarding.start': 'INIZIA',
    'onboarding.skip': 'Salta',
    'home.create': 'CREA STANZA',
    'home.join': 'UNISCITI CON UN CODICE',
    'home.games': 'I giochi',
    'home.connection_failed': 'Connessione a Joyo non riuscita.',
    'home.language': 'Lingua',
    'join.title_create': 'Crea stanza',
    'join.title_join': 'Unisciti',
    'join.name_question': 'Come ti chiami?',
    'join.name_hint': 'Il tuo nome',
    'join.color': 'Il tuo colore',
    'join.code': 'Codice della stanza',
    'join.cta_create': 'CREA LA STANZA',
    'join.cta_join': 'ENTRA',
    'join.error_name': 'Scrivi il tuo nome.',
    'join.error_code': 'Il codice è di 6 caratteri.',
    'error.room_not_found': 'Nessuna stanza con questo codice.',
    'error.room_full': 'La stanza è piena: massimo 10 giocatori.',
    'error.room_finished': 'Questa partita è già finita.',
    'error.connection': 'Connessione persa. Riapri l\'app e riprova.',
    'lobby.title': 'Lobby',
    'lobby.code_label': 'CODICE STANZA',
    'lobby.code_hint': 'Dillo ad alta voce · tocca per copiare',
    'lobby.code_copied': 'Codice copiato',
    'lobby.players': 'Giocatori',
    'lobby.you': 'tu',
    'lobby.host_badge': 'HOST',
    'lobby.pick_game': 'SCEGLI IL GIOCO',
    'lobby.waiting_host': 'L\'host sta scegliendo il gioco…',
    'lobby.which_game': 'A cosa giochiamo?',
    'lobby.remove_player': 'Rimuovere {name}?',
    'lobby.remove_player_body':
        'Usalo se qualcuno ha chiuso l\'app senza uscire. Potrà sempre rientrare con il codice.',
    'lobby.remove': 'Rimuovi',
    'lobby.exit_host_title': 'Chiudere la stanza?',
    'lobby.exit_host_body':
        'La stanza si chiude per tutti: gli altri giocatori tornano alla home.',
    'lobby.exit_title': 'Uscire dalla stanza?',
    'lobby.exit_body': 'Gli altri giocatori ti vedranno uscire.',
    'lobby.stay': 'Resta',
    'lobby.close': 'Chiudi',
    'lobby.leave': 'Esci',
    'lobby.exit_failed': 'Uscita non riuscita: {detail}',
    'lobby.room_closed': 'La stanza è stata chiusa dall\'host.',
    'lobby.reconnecting': 'Riconnessione…',
    'lobby.entering': 'Entro nella stanza…',
    'mode.title': 'Modalità',
    'mode.normale': 'Normale',
    'mode.mix': 'Mix',
    'mode.hot': 'Hot',
    'mode.normale.desc':
        'Perfetta per rompere il ghiaccio senza troppi traumi.',
    'mode.mix.desc': 'I giochi ruotano e il ritmo incalza. Tenetevi forte.',
    'mode.hot.desc': 'Senza freni. Da giocare solo se siete pronti a tutto.',
    'settings.rounds': 'Round per partita',
    'game.round_of': 'Round {n} di {total}',
    'game.preparing': 'Preparo il round…',
    'game.create_failed': 'Non riesco a creare il round: {detail}',
    'game.close_failed': 'Non riesco a chiudere il round: {detail}',
    'game.vote_failed': 'Risposta non registrata: {detail}',
    'game.next_round': 'PROSSIMO ROUND',
    'game.see_podium': 'VEDI IL PODIO',
    'game.waiting_next': 'L\'host sta per lanciare il prossimo round…',
    'game.finished': 'La partita è finita',
    'game.answered': 'Hanno risposto {n} su {total}',
    'game.back_to_lobby': 'TORNA ALLA LOBBY',
    'game.lobby_short': 'LOBBY',
    'game.host_only': 'L\'host può far ripartire il gioco dalla lobby.',
    'game.coming_soon': 'In arrivo',
    'podium.title': 'Fine partita',
    'podium.winner': 'Vince {name}',
    'podium.no_scores':
        'Questo gioco non assegna punti: nessuna classifica, solo la partita.',
    'podium.points': '{n} punti',
    'podium.points_one': '{n} punto',
    'preferisci.name': 'Preferisci',
    'preferisci.tagline': 'Scelte atroci: chi la pensa come te?',
    'preferisci.prompt': 'Preferisci…',
    'preferisci.or': 'oppure',
    'preferisci.split': 'Il gruppo si è diviso così',
    'preferisci.no_votes': 'Non ha risposto nessuno',
    'non_ho_mai.name': 'Non ho mai',
    'non_ho_mai.tagline': 'Il confessionale è aperto. Confessa e sopravvivi.',
    'non_ho_mai.prompt': 'Non ho mai…',
    'non_ho_mai.done': 'L\'HO FATTO',
    'non_ho_mai.never': 'MAI',
    'non_ho_mai.anonymous':
        'Nessuno vedrà cosa hai risposto: si vede solo il conteggio.',
    'non_ho_mai.nobody': 'Nessuno l\'ha fatto',
    'non_ho_mai.count': '{n} su {total}',
    'non_ho_mai.guess_who': 'Ora tocca a voi capire chi',
    'chi.name': 'Chi lo potrebbe fare',
    'chi.tagline': 'Il gioco dove si punta il dito (letteralmente).',
    'chi.decided': 'Il gruppo ha deciso',
    'chi.tie': 'Pari merito',
    'chi.no_votes': 'Nessun voto',
    'obbligo.name': 'Obbligo o Verità',
    'obbligo.tagline': 'La bottiglia decide, tu sudi. Zero scuse.',
    'obbligo.spinning': 'La bottiglia gira…',
    'obbligo.your_turn': 'Tocca a te',
    'obbligo.turn_of': 'Tocca a {name}',
    'obbligo.choosing': 'Sta scegliendo…',
    'obbligo.dare': 'OBBLIGO',
    'obbligo.truth': 'VERITÀ',
    'obbligo.no_choice': '{name} non ha scelto in tempo',
    'obbligo.when_done': 'Quando ha finito, l\'host lancia il prossimo giro',
    'bluff.name': 'Bluff Story',
    'bluff.tagline': 'Mentire è un\'arte. Riesci a non farti beccare?',
    'bluff.writing': '{name} sta scrivendo\nun fatto vero su di sé',
    'bluff.your_turn_body':
        'Scrivi un fatto vero su di te. Il gioco ci metterà in mezzo due bugie: gli altri dovranno indovinare qual è il tuo.',
    'bluff.hint': 'Scrivi qui…',
    'bluff.send': 'MANDA LA TUA VERITÀ',
    'bluff.too_short': 'Scrivi qualcosa di un po\' più lungo.',
    'bluff.which_true': 'Qual è la verità di {name}?',
    'bluff.in_play': 'La tua storia è in gioco',
    'bluff.dont_tell': 'Non lasciarti scappare qual è quella vera.',
    'bluff.your_truth': 'la tua verità',
    'bluff.true_label': 'vera',
    'bluff.truth_of': 'La verità di {name}',
    'bluff.nobody_guessed': 'Nessuno ha indovinato: {name} vi ha fregati tutti',
    'bluff.guessed': '{n} hanno indovinato',
    'bluff.guessed_one': '{n} ha indovinato',
    'bluff.scoring':
        '+2 a chi ha indovinato · +1 a {name} per ogni bluff riuscito',
    'bluff.ai_working': 'Sto inventando due bugie…',
    'bluff.ai_working_sub': 'su misura per la storia di {name}',
    'impostore.name': 'Impostore',
    'impostore.tagline': 'Un intruso tra noi. Trovalo prima che sia tardi.',
    'impostore.only_you': 'Solo tu vedi questo',
    'impostore.you_are': 'Sei l\'impostore',
    'impostore.you_are_body':
        'Non conosci la parola. Ascolta, improvvisa e non farti scoprire: se indovini la parola alla fine recuperi punti.',
    'impostore.the_word': 'La parola è',
    'impostore.one_doesnt': 'Uno di voi non la conosce.',
    'impostore.round_of_words': 'Giro di parole',
    'impostore.round_of_words_body':
        'A turno, ognuno dice una sola parola legata al segreto.\nTroppo precisa e l\'impostore capisce, troppo vaga e sembrate voi l\'impostore.',
    'impostore.your_word': 'La tua parola: {word}',
    'impostore.to_vote': 'PASSA AL VOTO',
    'impostore.who': 'Chi è l\'impostore?',
    'impostore.guess_hint': 'La parola segreta era…',
    'impostore.guess_body':
        'Sei l\'impostore: prova a indovinare la parola. Se ti scoprono ma la azzecchi, recuperi punti.',
    'impostore.confirm': 'CONFERMA',
    'impostore.vote_registered': 'Voto registrato',
    'impostore.caught': 'Impostore smascherato',
    'impostore.escaped': 'L\'impostore l\'ha fatta franca',
    'impostore.word_was': 'La parola era',
    'impostore.guessed_it': 'Ha indovinato: "{guess}" · +3 punti',
    'impostore.said': 'Aveva detto: "{guess}"',
    'impostore.points_caught': '+2 a chi ha votato l\'impostore',
    'impostore.points_escaped': '+5 all\'impostore',
    'impostore.votes': '{n} voti',
    'impostore.votes_one': '{n} voto',
    'premium.title': 'Contenuti su misura',
    'premium.body':
        'In "Chi lo potrebbe fare" e "Bluff Story" le frasi vengono scritte sul vostro gruppo invece che pescate da un elenco.',
    'premium.active': 'AI attiva in questa stanza',
    'premium.active_body': 'Domande e bugie generate sul vostro gruppo',
    'premium.unlock': 'SBLOCCA',
    'premium.watch_ad': 'ANNUNCIO',
    'premium.host_only': 'Può sbloccarla l\'host.',
    'premium.credits': '{n} crediti',
    'premium.unlocked': 'AI sbloccata per questa stanza',
    'premium.ad_reward': 'Hai guadagnato un contenuto AI',
    'premium.ad_incomplete': 'Annuncio non completato.',
    'premium.no_store':
        'Acquisti non disponibili qui: servono Google Play o App Store.',
    'premium.ads_mobile_only': 'Gli annunci funzionano solo su telefono.',
  };
}
