class ContentItApp {
  const ContentItApp._();

  static const Map<String, String> ui = {
    'app.tagline': 'Il party game dove\ntutti sono connessi.',
    'common.retry': 'RIPROVA',
    'common.cancel': 'ANNULLA',
    'common.continue': 'CONTINUA',
    'common.back_home': 'TORNA ALLA HOME',
    'common.loading': 'Un attimo…',
    'common.you': 'tu',

    'onboarding.slide1.title': 'La serata sta per\ncambiare ritmo',
    'onboarding.slide1.body':
        'Ognuno usa il proprio telefono, ma si gioca tutti insieme. Joyo mette tutto in comune e voi fate il resto.',

    'onboarding.slide2.title': 'Un codice e siete dentro',
    'onboarding.slide2.body':
        'Crea una stanza, condividi il codice e fai entrare gli amici. In pochi secondi siete pronti.',

    'onboarding.slide3.title': 'Sei giochi.\nInfinite possibilità.',
    'onboarding.slide3.body':
        'Preferisci, Non ho mai, Chi lo potrebbe fare, Obbligo o Verità, Bluff Story e Impostore. Scegli il vostro gioco e iniziate.',

    'onboarding.slide4.title': 'Scegli tu\nil livello di gioco',
    'onboarding.slide4.body':
        'Normale per iniziare, Mix per cambiare ritmo, Hot per quando volete rendere la serata più interessante.',

    'onboarding.language': 'In che lingua giocate?',
    'onboarding.start': 'INIZIA',
    'onboarding.skip': 'SALTA',

    'home.create': 'CREA STANZA',
    'home.join': 'ENTRA CON UN CODICE',
    'home.games': 'I giochi',
    'home.connection_failed': 'Impossibile connettersi a Joyo.',
    'home.language': 'Lingua',

    'join.title_create': 'Crea una stanza',
    'join.title_join': 'Entra nella stanza',
    'join.name_question': 'Come ti chiami?',
    'join.name_hint': 'Inserisci il tuo nome',
    'join.color': 'Scegli il tuo colore',
    'join.avatar': 'Scegli il tuo avatar',
    'join.error_avatar': 'Scegli un avatar.',
    'join.code': 'Codice della stanza',
    'join.cta_create': 'CREA LA STANZA',
    'join.cta_join': 'ENTRA',
    'join.error_name': 'Inserisci il tuo nome.',
    'join.error_code': 'Il codice deve contenere 6 caratteri.',

    'error.room_not_found': 'Non troviamo nessuna stanza con questo codice.',
    'error.room_full': 'La stanza è piena. Massimo 10 giocatori.',
    'error.room_finished': 'Questa partita è già terminata.',
    'error.connection':
        'Connessione persa. Controlla la connessione e riprova.',

    'lobby.title': 'Lobby',
    'lobby.code_label': 'CODICE STANZA',
    'lobby.code_hint': 'Condividilo con gli amici · tocca per copiarlo',
    'lobby.code_copied': 'Codice copiato',
    'lobby.players': 'Giocatori',
    'lobby.you': 'tu',
    'lobby.host_badge': 'HOST',
    'lobby.pick_game': 'SCEGLI IL GIOCO',
    'lobby.waiting_host': 'L\'host sta scegliendo il gioco…',
    'lobby.which_game': 'A cosa giochiamo?',
    'lobby.remove_player': 'Rimuovere {name}?',
    'lobby.remove_player_body':
        'Usalo se qualcuno ha chiuso l\'app senza uscire. Potrà rientrare con lo stesso codice.',
    'lobby.remove': 'RIMUOVI',
    'lobby.exit_host_title': 'Chiudere la stanza?',
    'lobby.exit_host_body':
        'La stanza verrà chiusa per tutti e gli altri giocatori torneranno alla home.',
    'lobby.exit_title': 'Uscire dalla stanza?',
    'lobby.exit_body':
        'Stai per lasciare la stanza. Gli altri giocatori lo vedranno.',
    'lobby.stay': 'RESTA',
    'lobby.close': 'CHIUDI',
    'lobby.leave': 'ESCI',
    'lobby.exit_failed': 'Impossibile uscire: {detail}',
    'lobby.room_closed': 'L\'host ha chiuso la stanza.',
    'lobby.reconnecting': 'Riconnessione…',
    'lobby.entering': 'Ingresso nella stanza…',

    'mode.title': 'Modalità',
    'mode.normale': 'Normale',
    'mode.mix': 'Mix',
    'mode.hot': 'Hot',
    'mode.normale.desc': 'Le regole base. Il modo più semplice per iniziare.',
    'mode.mix.desc': 'Più varietà, più ritmo e qualche sorpresa in più.',
    'mode.hot.desc': 'Più diretto, più personale. Solo se siete pronti.',

    'settings.rounds': 'Round per partita',
    'game.round_of': 'Round {n} di {total}',
    'game.preparing': 'Preparo il round…',
    'game.create_failed': 'Impossibile creare il round: {detail}',
    'game.close_failed': 'Impossibile chiudere il round: {detail}',
    'game.vote_failed': 'Risposta non registrata: {detail}',
    'game.next_round': 'PROSSIMO ROUND',
    'game.see_podium': 'VEDI IL PODIO',
    'game.waiting_next': 'L\'host sta per avviare il prossimo round…',
    'game.finished': 'Partita finita',
    'game.answered': 'Hanno risposto {n} su {total}',
    'game.back_to_lobby': 'TORNA ALLA LOBBY',
    'game.lobby_short': 'LOBBY',
    'game.host_only': 'Solo l\'host può riavviare il gioco dalla lobby.',
    'game.coming_soon': 'Presto disponibile',

    'podium.title': 'Fine partita',
    'podium.winner': 'Vince {name}',
    'podium.no_scores':
        'Questo gioco non assegna punti. Qui conta solo giocare.',
    'podium.points': '{n} punti',
    'podium.points_one': '{n} punto',

    'preferisci.name': 'Preferisci',
    'preferisci.tagline': 'Due scelte. Una risposta. Quale scegli?',
    'preferisci.prompt': 'Preferisci…',
    'preferisci.or': 'oppure',
    'preferisci.split': 'Il gruppo ha scelto così',
    'preferisci.no_votes': 'Nessuno ha risposto',

    'non_ho_mai.name': 'Non ho mai',
    'non_ho_mai.tagline': 'È successo o no? Adesso lo scopriamo.',
    'non_ho_mai.prompt': 'Non ho mai…',
    'non_ho_mai.done': 'L\'HO FATTO',
    'non_ho_mai.never': 'MAI',
    'non_ho_mai.anonymous': 'Le risposte sono anonime. Si vede solo il totale.',
    'non_ho_mai.nobody': 'Nessuno l\'ha fatto',
    'non_ho_mai.count': '{n} su {total}',
    'non_ho_mai.guess_who': 'Ora provate a capire chi è stato',

    'chi.name': 'Chi lo potrebbe fare',
    'chi.tagline': 'Una domanda. Un nome. Tocca a voi decidere.',
    'chi.decided': 'Il gruppo ha deciso',
    'chi.tie': 'Pareggio',
    'chi.no_votes': 'Nessun voto',

    'obbligo.name': 'Obbligo o Verità',
    'obbligo.tagline': 'La scelta non è più nelle tue mani.',
    'obbligo.spinning': 'La bottiglia gira…',
    'obbligo.your_turn': 'Tocca a te',
    'obbligo.turn_of': 'Tocca a {name}',
    'obbligo.choosing': 'Sta scegliendo…',
    'obbligo.dare': 'OBBLIGO',
    'obbligo.truth': 'VERITÀ',
    'obbligo.no_choice': '{name} non ha scelto in tempo',
    'obbligo.when_done':
        'Quando ha finito, l\'host può avviare il prossimo giro',

    'bluff.name': 'Bluff Story',
    'bluff.tagline': 'Una verità. Due bugie. Riuscirai a bluffare?',
    'bluff.writing': '{name} sta scrivendo\nuna verità su di sé',
    'bluff.your_turn_body':
        'Scrivi una verità su di te. Noi aggiungeremo due bugie. Gli altri dovranno capire qual è quella vera.',
    'bluff.hint': 'Scrivi la tua verità…',
    'bluff.send': 'INVIA LA TUA VERITÀ',
    'bluff.too_short': 'Scrivi almeno 30 caratteri.',
    'bluff.which_true': 'Qual è la verità di {name}?',
    'bluff.in_play': 'La tua storia è in gioco',
    'bluff.dont_tell': 'Non far capire agli altri qual è quella vera.',
    'bluff.your_truth': 'la tua verità',
    'bluff.true_label': 'vera',
    'bluff.truth_of': 'La verità di {name}',
    'bluff.nobody_guessed':
        'Nessuno ha indovinato. {name} vi ha fregati tutti.',
    'bluff.guessed': '{n} hanno indovinato',
    'bluff.guessed_one': '{n} ha indovinato',
    'bluff.scoring': '+2 a chi indovina · +1 a {name} per ogni bluff riuscito',
    'bluff.multilang_title': 'Lingue diverse al tavolo',
    'bluff.multilang_body':
        'Nel gruppo si gioca in lingue diverse: le bugie escono tradotte, ma '
        'la frase vera resta nella lingua di chi la scrive e può farsi '
        'riconoscere subito.',
    'bluff.ai_working': 'Preparo due bugie…',
    'bluff.ai_working_sub': 'pensate per la storia di {name}',

    'impostore.name': 'Impostore',
    'impostore.tagline': 'Uno di voi sta giocando con informazioni diverse.',
    'impostore.only_you': 'Solo tu puoi vederlo',
    'impostore.you_are': 'Sei l\'impostore',
    'impostore.you_are_body':
        'Non conosci la parola. Ascolta gli altri, improvvisa e non farti scoprire. Se vieni smascherato ma indovini la parola, recuperi punti.',
    'impostore.the_word': 'La parola segreta è',
    'impostore.one_doesnt': 'Uno di voi non conosce la parola.',
    'impostore.round_of_words': 'Giro di parole',
    'impostore.round_of_words_body':
        'A turno, ognuno dice una sola parola legata al segreto.\nTroppo precisa e aiuti l\'impostore. Troppo vaga e sembrerai tu l\'impostore.',
    'impostore.your_word': 'La tua parola: {word}',
    'impostore.to_vote': 'VAI AL VOTO',
    'impostore.who': 'Chi è l\'impostore?',
    'impostore.guess_hint': 'La parola segreta era…',
    'impostore.guess_body':
        'Sei l\'impostore. Prova a indovinare la parola: se ti scoprono ma la indovini, recuperi punti.',
    'impostore.confirm': 'CONFERMA',
    'impostore.vote_registered': 'Voto registrato',
    'impostore.caught': 'Impostore scoperto',
    'impostore.escaped': 'L\'impostore è scappato',
    'impostore.word_was': 'La parola era',
    'impostore.guessed_it': 'Ha indovinato: "{guess}" · +3 punti',
    'impostore.said': 'Aveva detto: "{guess}"',
    'impostore.points_caught': '+2 a chi ha votato per l\'impostore',
    'impostore.points_escaped': '+5 all\'impostore',
    'impostore.votes': '{n} voti',
    'impostore.votes_one': '{n} voto',

    'premium.title': 'Contenuti personalizzati',
    'premium.body':
        'In "Chi lo potrebbe fare" e "Bluff Story", l\'AI crea contenuti pensati per il vostro gruppo invece di usare frasi predefinite.',
    'premium.active': 'AI attiva in questa stanza',
    'premium.active_body': 'Contenuti generati per il vostro gruppo',
    'premium.unlock': 'SBLOCCA',
    'premium.watch_ad': 'GUARDA ANNUNCIO',
    'premium.host_only': 'Solo l\'host può sbloccarla.',
    'premium.credits': '{n} crediti',
    'premium.unlocked': 'AI sbloccata per questa stanza',
    'premium.ad_reward': 'Hai ottenuto un contenuto AI',
    'premium.ad_incomplete': 'Annuncio non completato.',
    'premium.no_store':
        'Gli acquisti non sono disponibili qui. Usa Google Play o App Store.',
    'premium.ads_mobile_only': 'Gli annunci sono disponibili solo su telefono.',

    'shop.badge': 'Premium',
    'shop.title': 'Sblocca Mix e Hot',
    'shop.body':
        'Mix e Hot sono modalità premium. Guarda 3 annunci per sbloccarle per una partita.',
    'shop.progress': '{n}/3 annunci',
    'shop.watch': 'GUARDA UN ANNUNCIO',
    'shop.unlocked': 'Mix e Hot sbloccate per una partita',
    'shop.host_only': 'Solo l\'host può sbloccarle.',
    'shop.go_premium': 'Oppure passa a Premium',
    'shop.page_title': 'Shop',
    'shop.free_title': 'Sblocca con gli annunci',
    'shop.in_room_only': 'Disponibile in una stanza, come host.',
    'shop.games': '{n} partite premium pronte',
    'endgame.promo': 'Vuoi più scintille e meno pubblicità?',
    'endgame.shop_cta': 'SCOPRI PREMIUM',

    'paywall.title': 'Passa a Premium',
    'paywall.no_ads_name': 'Niente pubblicità',
    'paywall.no_ads_desc': 'Gioca senza annunci.',
    'paywall.premium_name': 'Premium',
    'paywall.premium_desc':
        'Mix, Hot, partite più lunghe e niente pubblicità.',
    'paywall.per_month': '/mese',
    'paywall.active': 'Attivo',
    'paywall.subscribe': 'ABBONATI',
    'paywall.restore': 'Ripristina acquisti',
    'paywall.restored': 'Abbonamento ripristinato',
    'paywall.nothing_restored': 'Nessun abbonamento da ripristinare',
  };
}
