/// Pool "Bluff Story" in italiano: affermazioni in prima persona,
/// plausibili, usate come bugie/verità nel gioco del bluff.
class ContentItBluff {
  const ContentItBluff._();

  static const List<String> bluffFakes = [
  'Ho dormito dodici ore di fila in un aeroporto aspettando una coincidenza.',
  'Ho imparato a nuotare solo a diciotto anni perché avevo paura dell\'acqua.',
  'Ho perso un volo intercontinentale per essermi addormentato al gate.',
  'Da piccolo mi sono perso in un centro commerciale per più di un\'ora.',
  'Ho vinto una gara di ballo liscio alle medie con mia cugina.',
  'Sono finito per sbaglio in una foto di matrimonio di perfetti sconosciuti.',
  'Ho lavorato una settimana come cameriere e sono stato licenziato subito.',
  'Ho cucinato per venti persone senza aver mai acceso un fornello prima.',
  'Sono apparso in televisione per tre secondi durante un servizio del TG.',
  'Ho incontrato un attore famosissimo al reparto surgelati del supermercato.',
  'Ho fatto l\'autostop per cinquanta chilometri in un paese straniero.',
  'Ho dormito in macchina durante un temporale fortissimo in montagna.',
  'Ho preso il treno sbagliato e sono finito dall\'altra parte d\'Italia.',
  'Ho passato un capodanno intero in ospedale per accompagnare un amico.',
  'Sono caduto da un albero molto alto da bambino senza farmi un graffio.',
  'Mi sono rotto un braccio giocando a nascondino dentro casa.',
  'Ho fatto un tatuaggio impulsivo e me ne sono pentito il giorno dopo.',
  'Mi sono tagliato i capelli da solo e ho dovuto rasarmi a zero.',
  'Ho tinto i capelli di verde fluo per onorare una scommessa persa.',
  'Ho cantato al karaoke davanti a cento persone che mi fischiavano.',
  'Ho suonato la chitarra in una band metal per meno di due mesi.',
  'Ho scritto una canzone d\'amore che non ho mai fatto sentire a nessuno.',
  'Ho tenuto un diario segreto per cinque anni di fila senza saltare un giorno.',
  'Ho letto un libro di seicento pagine interamente in una sola notte.',
  'Ho visto lo stesso film al cinema per tre volte nella stessa settimana.',
  'Ho imparato a memoria un intero monologo di tre minuti di un film.',
  'Ho recitato in uno spettacolo scolastico e ho inventato tutte le battute.',
  'Ho cantato in un coro polifonico per un anno intero.',
  'Ho imparato una lingua straniera solo guardando serie TV in lingua originale.',
  'Ho fatto un esame universitario senza aver studiato e ho preso trenta.',
  'Ho copiato a un compito importante e il professore mi ha scoperto.',
  'Ho saltato una settimana intera di scuola senza che i miei lo sapessero.',
  'Sono stato l\'ultimo a scoprire una notizia enorme che riguardava la mia famiglia.',
  'Ho scoperto di avere un cugino di secondo grado che vive in America.',
  'Ho vissuto in tre città diverse nell'arco di soli due anni.',
  'Ho fatto un trasloco intero da solo usando una macchina piccolissima.',
  'Ho vissuto un mese intero in una casa senza televisione né internet.',
  'Ho passato un\'estate intera senza usare i social network.',
  'Ho cancellato tutti i miei profili social per tre mesi consecutivi.',
  'Ho perso il mio telefono nuovo in mare mentre facevo un video.',
  'Ho lasciato il portafoglio pieno su un treno e me lo hanno restituito.',
  'Ho trovato cinquanta euro per strada e li ho consegnati alla polizia.',
  'Ho vinto venti euro con un gratta e vinci comprato per caso.',
  'Ho comprato un biglietto della lotteria e l\'ho perso prima dell\'estrazione.',
  'Ho pagato la cena a un tavolo di sconosciuti per errore del cameriere.',
  'Ho ordinato lo stesso identico piatto ogni giorno per un mese.',
  'Ho mangiato solo pizza a pranzo e cena per sette giorni di fila.',
  'Ho provato a diventare vegano e ho resistito solo due settimane.',
  'Ho cucinato una torta che è risultata così dura da essere immangiabile.',
  'Ho bruciato completamente una pentola dimenticandola sul fuoco acceso.',
  'Ho fatto scattare l\'allarme antincendio dell\'hotel cucinando in camera.',
  'Ho rotto il forno di casa proprio il giorno prima di una cena importante.',
  'Ho montato un mobile enorme e alla fine mi sono avanzati dieci pezzi.',
  'Ho dipinto la mia camera di un colore che ho iniziato a odiare subito.',
  'Ho dormito su un materasso gonfiabile per terra per sei mesi.',
  'Ho vissuto con un coinquilino con cui non ho mai parlato in un anno.',
  'Ho adottato un cane d\'impulso mentre ero in vacanza all\'estero.',
  'Ho dato un nome proprio a ogni singola pianta che ho in casa.',
  'Ho fatto morire tutte le piante grasse che mi hanno regalato negli anni.',
  'Ho salvato un gattino che era rimasto bloccato su un ramo altissimo.',
  'Ho avuto una paura tremenda di un cane grande quanto un gatto.',
  'Ho corso una mezza maratona senza aver fatto nemmeno un giorno di allenamento.',
  'Mi sono iscritto in una palestra costosa e ci sono andato solo tre volte.',
  'Ho giocato a calcio in una squadra ufficiale per una sola partita.',
  'Ho provato a sciare per la prima volta a trent\'anni e sono caduto subito.',
  'Ho provato il paracadutismo una volta e ho giurato di non farlo mai più.',
  'Ho fatto un\'immersione subacquea e sono andato nel panico a dieci metri.',
  'Ho scalato una piccola montagna indossando delle scarpe non adatte.',
  'Ho dormito in tenda sotto un temporale fortissimo per due notti di fila.',
  'Ho fatto un viaggio da solo all\'estero senza dirlo a nessuno.',
  'Ho prenotato un volo aereo per il giorno sbagliato e non sono partito.',
  'Ho passato un\'intera notte in stazione aspettando il primo treno utile.',
  'Ho conosciuto il mio migliore amico mentre eravamo in fila al supermercato.',
  'Ho ritrovato un vecchio compagno di classe per caso mentre ero a Londra.',
  'Ho mantenuto un\'amicizia importante per anni comunicando solo via chat.',
  'Ho scritto una lettera d\'amore lunghissima che non ho mai spedito.',
  'Ho ricevuto una lettera anonima che mi ha cambiato completamente la giornata.',
  'Ho chiamato il numero sbagliato e sono rimasto a parlare per dieci minuti.',
  'Ho risposto a una chiamata di lavoro importante mentre ero nudo in spiaggia.',
  'Ho lavorato ininterrottamente durante tutte le vacanze di Natale.',
  'Ho dato le dimissioni dal mio vecchio lavoro senza avere un piano B.',
  'Ho rifiutato un\'offerta di lavoro con uno stipendio molto più alto.',
  'Ho fatto un colloquio di lavoro in una lingua che parlavo malissimo.',
  'Ho preso una decisione fondamentale per la mia vita lanciando una moneta.',
  'Ho dormito profondamente durante una riunione di lavoro molto importante.',
  'Ho mandato una mail confidenziale a tutta l\'azienda per un errore tecnico.',
  'Ho chiamato il mio nuovo capo con il nome del mio ex per sbaglio.',
  'Ho lavorato con un collega per mesi senza mai sapere il suo cognome.',
  'Ho fatto finta di conoscere benissimo una persona che mi salutava per strada.',
  'Ho salutato con entusiasmo uno sconosciuto pensando fosse un mio caro amico.',
  'Ho riconosciuto una persona solo dalla voce dopo dieci anni che non la sentivo.',
  'Ho dimenticato il compleanno di mia madre e me ne sono ricordato dopo una settimana.',
  'Ho organizzato una festa a sorpresa che è stata scoperta il giorno prima.',
  'Ho tenuto un segreto molto importante per più di cinque anni di fila.',
  'Ho raccontato ai miei una bugia che è durata per un anno intero.',
  'Ho confessato una mia colpa solo perché non riuscivo più a dormirci la notte.',
  'Ho pianto disperatamente guardando una pubblicità di cuccioli in TV.',
  'Ho riso a crepapelle durante un funerale e non riuscivo a fermarmi.',
  'Mi sono addormentato al cinema durante l\'anteprima di un film che adoravo.',
  'Ho applaudito da solo e con entusiasmo alla fine di un film al cinema.',
  'Ho cantato a squarciagola in macchina credendo di essere completamente solo.',
  'Ho ballato in ascensore insieme a uno sconosciuto che mi guardava.',
  'Ho fatto amicizia con il mio vicino di casa solo dopo tre anni che vivevamo lì.',
  'Ho perso tutte le chiavi di casa proprio il giorno del mio trasloco.',
  'Sono rimasto chiuso fuori casa sul pianerottolo mentre ero in pigiama.',
  'Sono rimasto bloccato in un ascensore vecchio per più di venti minuti.',
  'Ho preso per errore una scala mobile molto lunga nel verso sbagliato.',
  'Ho sbagliato il bagno in un ristorante elegante e sono entrato in quello opposto.',
  'Sono entrato per errore in una riunione di lavoro e sono rimasto lì dieci minuti.',
  'Ho parlato al telefono ad alta voce su un treno senza accorgermi del volume.',
  'Ho mandato un messaggio d\'amore proprio alla persona di cui stavo parlando male.',
  'Ho fatto uno screenshot di una chat e l\'ho mandato per errore al destinatario.',
  'Ho messo "mi piace" per sbaglio a una foto di dieci anni fa di un mio ex.',
  'Ho scritto un commento molto cattivo e l\'ho cancellato dopo un secondo.',
  'Ho creato un profilo social falso che non ho mai avuto il coraggio di usare.',
  'Ho guardato un\'intera serie TV di tre stagioni in un solo weekend.',
  'Ho finito un videogioco difficilissimo in una sola notte.',
  'Ho giocato ossessivamente allo stesso gioco online per cinque anni.',
  'Ho vinto un torneo di carte in famiglia barando spudoratamente.',
  'Ho perso una scommessa assurda e ho dovuto tingermi i capelli di blu.',
  'Ho fatto una scommessa stupida che mi è costata una cena per otto persone.',
  'Ho mangiato un peperoncino piccantissimo solo per vincere una sfida.',
  'Ho bevuto tre caffè doppi in un\'ora e non ho chiuso occhio tutta la notte.',
  'Ho passato una notte intera in bianco per un\'ansia che poi si è rivelata inutile.',
  'Ho fatto un sogno così realistico da crederci fermamente appena sveglio.',
  'Ho parlato nel sonno rivelando un segreto che doveva restare tale.',
  'Ho camminato nel sonno per tutta casa quando ero un bambino.',
  'Mi sono svegliato in un posto diverso della casa da quello in cui mi ero addormentato.',
  'Ho dormito profondamente su una panchina in un parco pubblico di pomeriggio.',
  'Ho passato un\'intera giornata senza rivolgere la parola a nessuno.',
  'Ho parlato fitto con uno sconosciuto per due ore durante un viaggio in treno.',
  'Ho restituito un portafoglio pieno di soldi che avevo trovato per strada.',
  'Ho vinto un premio a una lotteria di beneficenza e non l\'ho mai ritirato.',
  'Ho mangiato la stessa identica cosa a pranzo per trenta giorni consecutivi.',
  'Ho finto di parlare una lingua straniera per non farmi riconoscere durante una vacanza.',
  'Ho dovuto chiedere aiuto ai vicini perché non trovavo più il mio gatto.',
  'Ho finto di avere problemi di linea per chiudere una chiamata di lavoro noiosa.',
  'Sono uscito dal cinema a metà film perché mi ero annoiato a morte.',
  'Ho portato a spasso per dieci minuti il cane di un vicino pensando che fosse il mio.',
  'Ho salutato con grandissimo entusiasmo una persona che non conoscevo affatto.',
  'Ho seguito un tour turistico della mia città fingendomi un turista straniero.',
  'Ho mandato gli auguri di compleanno alla persona sbagliata per due anni di fila.',
  'Ho vinto una discussione accesa citando una statistica totalmente inventata.',
  'Ho tenuto l\'ombrello aperto per dieci minuti dopo che il sole era già uscito.',
  'Ho fatto una figuraccia epica a un colloquio e mi hanno assunto lo stesso.',
  'Ho tenuto una pianta finta in soggiorno per anni innaffiandola regolarmente.',
  'Ho perso le chiavi della macchina e le ho ritrovate dopo un mese nel freezer.',
  'Ho detto "buon appetito" al cameriere che mi stava portando il piatto.',
  'Ho corso dietro a un autobus per duecento metri e sono riuscito a prenderlo.',
  'Ho dimenticato dove avevo parcheggiato l\'auto e ho girato a vuoto per un\'ora.',
  ];
}