import '../content_tone.dart';

/// Contenuti del gioco "Obbligo o Verità" in italiano: obblighi e verità,
/// entrambi raggruppati per tono (normal/mix/hot).
class ContentItObbligoOVerita {
  const ContentItObbligoOVerita._();

  static const Map<String, List<String>> obblighi = {
    ContentTone.normal: [
      'Imita il modo di camminare della persona alla tua destra.',
      'Canta il ritornello dell\'ultima canzone che hai ascoltato.',
      'Parla in rima fino al tuo prossimo turno.',
      'Fai il verso di tre animali e falli indovinare.',
      'Balla dieci secondi senza musica.',
      'Racconta una barzelletta: se nessuno ride, ripetila più forte.',
      'Imita il tuo personaggio preferito di una serie.',
      'Fai una posa da statua e resta immobile per trenta secondi.',
      'Parla come un telecronista sportivo per un minuto.',
      'Mostra l\'ultima foto che hai scattato.',
      'Mostra la tua schermata home senza aprire nulla.',
      'Fai vedere l\'emoji che usi di più e spiega perché proprio quella.',
      'Fai vedere quante sveglie hai impostato.',
      'Chiedi all\'assistente vocale del telefono una domanda assurda scelta dal gruppo.',
      'Manda un messaggio vocale cantato a un tuo contatto a caso.',
      'Chiama un amico e cantagli tanti auguri anche se non è il suo compleanno.',
      'Fai un complimento sincero a ogni persona presente.',
      'Descrivi la persona alla tua sinistra usando solo tre parole.',
      'Inventa un rap di venti secondi sulla persona alla tua sinistra.',
      'Imita l\'insegnante che ricordi peggio.',
      'Fai finta di essere un venditore e vendici questo tavolo.',
      'Presenta il meteo di domani come in televisione.',
      'Parla con accento straniero fino al prossimo giro.',
      'Racconta la trama di un film senza dire il titolo, gli altri indovinano.',
      'Fai un discorso di ringraziamento come se avessi vinto un premio.',
      'Improvvisa una pubblicità per il tuo oggetto più vicino.',
      'Fai vedere come balli quando sei solo in casa.',
      'Canta al posto di parlare per i prossimi due minuti.',
      'Cammina con un libro in equilibrio sulla testa.',
      'Metti i vestiti al contrario per due round.',
      'Fatti fare una nuova pettinatura da chi sta alla tua destra.',
      'Fai un disegno del gruppo in trenta secondi.',
      'Scrivi il tuo nome con la mano sbagliata e mostralo.',
      'Disegna il ritratto di un presente a occhi chiusi e poi regalaglielo.',
      'Recita l\'alfabeto al contrario più veloce che puoi.',
      'Conta fino a venti saltando i multipli di tre.',
      'Di\' tre parole al contrario, partendo dall\'ultima.',
      'Racconta una storia inventata di trenta secondi che inizi con "Ieri notte…".',
      'Racconta la tua giornata come se fosse un film horror.',
      'Descrivi il tuo lavoro o la tua giornata tipo come farebbe un bambino.',
      'Fai finta di essere un robot per un minuto.',
      'Rispondi solo con domande fino al prossimo turno.',
      'Non puoi dire "sì" né "no" fino al tuo prossimo turno.',
      'Parla di te in terza persona fino al tuo prossimo turno.',
      'Ridi il più forte possibile senza motivo.',
      'Resta serissimo per trenta secondi mentre gli altri provano a farti ridere.',
      'Fai venti secondi di plank mentre gli altri contano.',
      'Fai cinque flessioni contate dal gruppo.',
      'Corri sul posto fino alla fine del turno.',
      'Fai dieci squat dicendo il nome di un presente a ogni piegamento.',
      'Mangia qualcosa scelto dalla persona alla tua sinistra.',
      'Assaggia due cose insieme che non stanno bene insieme.',
      'Fai una recensione da critico stellato dell\'ultima cosa che hai mangiato oggi.',
      'Prepara un drink analcolico e fallo assaggiare a qualcuno.',
      'Fai un brindisi improvvisato in onore del gruppo.',
      'Racconta il tuo ricordo più bello con una persona presente.',
      'Racconta come hai conosciuto chi ti sta di fronte.',
      'Di\' cosa invidi (in senso buono) a ogni persona presente.',
      'Fai una previsione sul futuro di una persona presente.',
      'Assegna un soprannome a ognuno e spiegalo.',
      'Rispondi solo a un nuovo soprannome scelto dal gruppo fino a fine partita.',
      'Scegli chi del gruppo porteresti su un\'isola deserta e perché.',
      'Racconta la cosa più costosa che hai comprato inutilmente.',
      'Confessa una tua abitudine strana.',
      'Racconta una tua paura ridicola.',
      'Fai finta di avere paura di un oggetto della stanza.',
      'Racconta un tuo talento inutile e dimostralo.',
      'Mostra il tuo miglior "trucco di magia" improvvisato.',
      'Fai un origami con quello che trovi in un minuto.',
      'Costruisci una torre con tre oggetti della stanza.',
      'Trova tre oggetti gialli in casa in trenta secondi.',
      'Scambia una cosa che indossi con chi ti sta a destra.',
      'Fai un selfie con la faccia più brutta che riesci a fare.',
      'Fatti una foto imitando la posa di chi sta alla tua sinistra.',
      'Fai un video di dieci secondi come se fossi un influencer.',
      'Registra un messaggio motivazionale per il gruppo.',
      'Leggi l\'oroscopo di oggi con voce drammatica.',
      'Inventa un oroscopo per la persona alla tua destra.',
      'Descrivi come sarà la tua vita tra dieci anni, senza pensarci troppo.',
      'Dichiara il tuo amore eterno a un oggetto della stanza: il divano conta.',
      'Recita una scena d\'addio strappalacrime con un cuscino.',
      'Di\' quale canzone conosci a memoria e cantane un pezzo.',
      'Fai il karaoke di dieci secondi senza musica.',
      'Fischia una canzone e falla indovinare.',
      'Fai un beatbox di cinque secondi.',
      'Imita il suono di tre strumenti diversi.',
      'Fai finta di suonare la chitarra come a un concerto.',
      'Balla come se fossi in discoteca da solo.',
      'Insegna al gruppo un passo di ballo.',
      'Fai una foto di gruppo dando tu le indicazioni.',
      'Scegli la colonna sonora della serata e spiega perché.',
      'Racconta la cosa più bella che ti è successa questa settimana.',
      'Di\' una cosa che vorresti imparare e perché non hai iniziato.',
      'Fai un elenco di tre cose per cui sei grato adesso.',
      'Manda un messaggio carino a una persona a cui non scrivi da tempo.',
      'Chiama tua madre o un parente e digli che gli vuoi bene.',
      'Manda "Buongiorno!" con tre emoji a caso nella chat di famiglia.',
      'Lascia che il gruppo scelga il tuo prossimo obbligo del turno seguente.',
      'Sfila come un modello da una parte all\'altra della stanza, giravolta compresa.',
      'Comportati come un T-Rex con le braccia corte fino al tuo prossimo turno.',
      'Usa un telecomando o una spazzola come microfono ogni volta che parli, per un giro.',
      'Fai il cameriere: prendi con aria serissima le ordinazioni immaginarie di tutti.',
      'Mima un film senza parlare finché il gruppo non lo indovina.',
      'Imita un personaggio famoso scelto dal gruppo finché qualcuno non indovina chi è.',
      'Fai un complimento a ogni presente saltellando su una gamba sola.',
      'Prova a leccarti il gomito con impegno totale per dieci secondi.',
      'Racconta una favola della buonanotte in trenta secondi facendo tutte le voci.',
      'Parla per un minuto di un argomento scelto dal gruppo come se fossi il massimo esperto.',
      'Ripeti tre volte di fila uno scioglilingua scelto dal gruppo senza sbagliare.',
      'Descrivi quello che fa la persona di fronte come farebbe un documentario sulla natura.',
      'Fai cinque espressioni a comando: felice, arrabbiato, sorpreso, innamorato, sospettoso.',
      'Balla un lento romantico con una scopa o un cuscino.',
      'Presenta un telegiornale con tre notizie assurde sui presenti.',
      'Fai l\'eco: ripeti l\'ultima parola di chi parla fino al tuo prossimo turno.',
      'Parla sussurrando fino al tuo prossimo turno, qualunque cosa succeda.',
      'Tieni un sorriso gigante stampato in faccia per tre minuti, qualunque cosa succeda.',
      'Inventa un inno del gruppo sull\'aria di una canzone famosa e cantalo.',
      'Fatti mettere in posa dal gruppo come una statua e resta così per una foto.',
      'Fai una scenata drammatica da telenovela perché è finito un biscotto.',
      'Prova a far ridere la persona più seria del gruppo in trenta secondi, senza toccarla.',
      'Impila su di te più cuscini che puoi e resta in equilibrio per dieci secondi.',
      'Inventa una lingua e "traduci" quello che dice la persona alla tua destra.',
      'Fai finta di essere bloccato in una scatola invisibile finché qualcuno non ti "libera".',
      'Racconta come si è formato questo gruppo in stile documentario storico.',
      'Dai del "Lei" a tutti fino al tuo prossimo turno, con estrema formalità.',
      'Fai un tutorial di cucina immaginario con gli oggetti che hai davanti.',
      'Muoviti al rallentatore fino alla fine del turno, replay compresi.',
      'Saluta in cinque lingue diverse, inventando quelle che non conosci.',
      'Imita un animale finché qualcuno non indovina quale.',
      'Rispondi cantando a tutto quello che ti viene detto fino al tuo turno.',
      'Fai dieci saltelli sul posto gridando il tuo nome.',
      'Inventa un motto per il gruppo e ripetilo ad alta voce.',
      'Fai il telecronista della stanza per trenta secondi.',
      'Inventa una pubblicità per l\'oggetto alla tua destra.',
      'Parla solo bisbigliando fino al tuo prossimo turno.',
      'Resta immobile come una statua mentre gli altri provano a farti ridere.',
      'Fai la lip-sync di una canzone a scelta del gruppo per quindici secondi.',
      'Imita un personaggio famoso scelto dal gruppo.',
      'Racconta la trama di un film famoso in esattamente dieci parole.',
      'Recita i giorni della settimana al contrario il più veloce possibile.',
      'Fingi di vincere un Oscar e ringrazia i presenti uno per uno.',
      'Cammina come un robot fino alla porta e ritorno.',
      'Inventa un soprannome simpatico per ognuno dei presenti.',
      'Canta "Tanti auguri" come se fosse una canzone rock.',
      'Fai cinque facce diverse in cinque secondi.',
      'Tieni un cuscino in equilibrio sulla testa per un giro intero.',
      'Descrivi la tua giornata usando solo suoni.',
      'Fai una previsione del tempo inventata con la massima serietà.',
      'Ordina una pizza immaginaria in modo epico e drammatico.',
      'Applaudi ogni frase detta dagli altri fino al tuo turno.',
    ],
    ContentTone.mix: [
      'Fai un massaggio sensuale all\'interno della coscia di una persona consenziente per trenta secondi.',
      'Sussurra all\'orecchio della persona alla tua destra la tua fantasia più sporca.',
      'Bacia il collo di una persona consenziente e soffia delicatamente sulla pelle.',
      'Fatti scegliere un indumento da togliere da una persona consenziente.',
      'Simula un orgasmo per quindici secondi, con audio e gesti, davanti a tutti.',
      'Togli tre capi d\'abbigliamento (accessori esclusi) e resta così per il resto della partita.',
      'Lecca il lobo dell\'orecchio della persona alla tua sinistra (se consenziente).',
      'Togli un accessorio o uno strato nel modo più provocante e lento possibile.',
      'Fatti bendare e indovina tre persone del gruppo baciando loro solo la mano o il braccio.',
      'Mima la tua posizione preferita con un cuscino in modo estremamente realistico.',
      'Appoggia la testa in grembo a una persona consenziente e restaci per tre round.',
      'Manda una foto di nudo (o una foto molto provocante) a chi vuoi tu e mostra la notifica d\'invio al gruppo.',
      'Fai una lap dance di trenta secondi a una persona consenziente scelta dal gruppo.',
      'Balla un lento sensuale, corpo a corpo, con una persona consenziente per un minuto.',
      'Traccia con la lingua il profilo del collo della persona alla tua sinistra (se consenziente).',
      'Tieni la mano della persona più attraente della stanza infilandola sotto la sua maglia (se consenziente).',
      'Guarda negli occhi la persona che trovi più attraente per trenta secondi mentre ti mordi il labbro.',
      'Mostra al gruppo la faccia che fai nel momento dell\'orgasmo: tieni la posa per cinque secondi.',
      'Bacia lentamente il petto o la spalla di una persona consenziente a tua scelta.',
      'Fai il verso di come reagisci quando ti fanno sesso orale, con l\'audio.',
      'Recita il tuo repertorio da sexting ad alta voce, con tono estremamente serio.',
      'Detta al gruppo il messaggio di seduzione più spinto che manderesti alla tua crush adesso.',
      'Descrivi ad alta voce come porteresti a letto la persona alla tua sinistra, passo per passo.',
      'Insegna al gruppo la tua mossa preferita per eccitare qualcuno in meno di un minuto.',
      'Spiega passo per passo la tua notte ideale: dai preliminari alla colazione.',
      'Fai una pubblicità di trenta secondi di te stesso come amante, citando le tue doti migliori.',
      'Racconta la tua notte migliore includendo dettagli su posizioni e sensazioni.',
      'Descrivi il tuo bacio perfetto e dallo subito a una persona consenziente (se ci sta).',
      'Di\' ad alta voce la frase più sporca che ti abbiano mai sussurrato a letto.',
      'Sussurra "ti voglio ora" con la voce più calda che hai all\'orecchio di tre persone diverse.',
      'Manda un messaggio hot all\'ultima persona con cui sei stato e mostra la risposta.',
      'Fai la tua imitazione di come flirti quando sei ubriaco e vuoi solo concludere.',
      'Mostra al rallentatore come usi la lingua durante un bacio: il gruppo vota la tecnica.',
      'Manda "Sto pensando a noi due a letto." a un contatto scelto dal gruppo.',
      'Leggi ad alta voce la chat più piccante che hai nel telefono, senza censurare nulla.',
      'Mostra la foto più audace che hai scattato o ricevuto negli ultimi mesi.',
      'Fai vedere al gruppo la tua cronologia in incognito degli ultimi due giorni.',
      'Scrivi "Voglio farlo con te" alla persona che ti piace e mostra lo screenshot.',
      'Manda un vocale di seduzione di dieci secondi a un ex scelto dal gruppo.',
      'Racconta fino a dove ti sei spinto nel luogo più pubblico in cui sei mai stato.',
      'Descrivi le tre cose che ti eccitano di più a letto, senza giri di parole.',
      'Racconta il tuo risveglio più imbarazzante dopo una notte di sesso folle.',
      'Confessa qual è il fetish che non hai ancora avuto il coraggio di provare.',
      'Di\' il nome della persona presente con cui avresti più probabilità di finire a letto stasera.',
      'Fai la classifica dei presenti basandoti solo sulla loro potenziale abilità a letto.',
      'Assegna a ogni presente un "voto di attrazione" da 1 a 10, guardandoli negli occhi.',
      'Di\' quale coppia di questa stanza farebbe scintille a letto e perché.',
      'Scegli chi del gruppo vorresti vedere nudo in questo momento.',
      'Fai a una persona del gruppo il complimento più spinto che ti viene in mente sul suo corpo.',
      'Proponi un "gioco di ruolo" veloce alla persona alla tua destra e recita la prima battuta.',
      'Attraversa la stanza come se fossi in uno strip-club, fermati davanti a qualcuno e facci un cenno.',
      'Lascia che il gruppo scriva un messaggio audace dal tuo telefono e lo mandi a chi vuole.',
      'Togli due capi o accessori a scelta, il più lentamente possibile, mentre il gruppo canta una canzone sexy.',
      'Dai una sculacciata decisa, con il suo consenso, alla persona scelta dal gruppo.',
      'Riproduci per dieci secondi i suoni che fai a letto nel momento del piacere massimo.',
      'Bacia lentamente il collo di una persona consenziente partendo dall\'orecchio e scendendo.',
      'Mima, restando vestito, la tua posizione preferita per dieci secondi, con impegno totale.',
      'Di\' ad alta voce il nome della persona in questa stanza che baceresti subito.',
      'Fai un massaggio di un minuto alla schiena di una persona consenziente, infilando le mani sotto i vestiti (se è d\'accordo).',
      'Sussurra all\'orecchio di chi hai a destra cosa le faresti se foste soli in questa stanza.',
      'Fai tre giri di sguardi intensi con la persona che trovi più sexy senza mai ridere.',
      'Descrivi la biancheria intima che indossi stasera nei minimi dettagli.',
      'Balla mezzo minuto di reggaeton strusciandoti (con consenso) contro una persona del gruppo.',
      'Fatti mettere un cubetto di ghiaccio nei pantaloni e resisti un minuto senza urlare.',
      'Sussurra il nome del tuo sex toy preferito all\'orecchio di qualcuno come se fosse una preghiera.',
      'Descrivi come ti tocchi quando sei da solo e vuoi finire in fretta.',
      'Spiega la differenza tra un bacio normale e un bacio "da letto", con esempi teorici.',
      'Mima "sto scrivendo alla mia crush per portarla a casa" con tutte le fasi del panico e del successo.',
      'Mostra la tua posa migliore da "voglio scopare" e spiegane la strategia.',
      'Racconta il complimento più sporco che hai mai ricevuto e chi te l\'ha fatto.',
      'Ripeti "voglio di più" con cinque intenzioni diverse: il gruppo deve indovinare quella giusta.',
      'Fai il gesto più erotico possibile usando solo un cubetto di ghiaccio.',
      'Insegna al gruppo come si fa un succhiotto perfetto senza lasciare troppo segno.',
      'Rivela quale profumo ti fa venire voglia di spogliare qualcuno all\'istante.',
      'Balla un lento di venti secondi con un presente, sussurrandogli cose spinte.',
      'Rifai la faccia di quando vieni: il gruppo vota l\'intensità.',
      'Componi un messaggio di "buongiorno dopo il sesso" che farebbe impazzire chiunque.',
      'Scegli chi del gruppo vorresti come "amico di letto" per un mese intero.',
      'Mordi con delicatezza la spalla di una persona consenziente e lasciala con la voglia di più.',
      'Percorri con un dito la schiena nuda di una persona consenziente partendo dalla nuca fino alla vita.',
      'Fai scivolare un cubetto di ghiaccio lungo il collo di una persona consenziente con la bocca.',
      'Sciogli i capelli e falli ricadere addosso a una persona consenziente mentre le sussurri qualcosa.',
      'Mordicchia le dita di una persona consenziente una a una, guardandola negli occhi.',
      'Balla accovacciandoti lentamente davanti a una persona consenziente scelta dal gruppo.',
      'Sfiora le labbra della persona più attraente con le tue senza mai baciarla, per dieci secondi.',
      'Fatti scrivere sul corpo, con un dito, una parola sporca da una persona consenziente e indovinala.',
      'Poggia la fronte su quella della persona che trovi più sexy e respirate insieme per venti secondi.',
      'Accarezza la nuca di una persona consenziente mentre le reciti la frase più calda che conosci.',
      'Bacia il polso di tre persone consenzienti diverse fingendo ogni volta più desiderio.',
      'Fai un lento massaggio alle spalle di chi hai a destra sussurrando quanto ti piace la sua pelle.',
      'Passa la lingua sul bordo di un bicchiere in modo provocante mentre fissi la tua crush.',
      'Mordi il tuo labbro inferiore e mantieni lo sguardo con la persona più attraente per un round intero.',
      'Sfila lentamente la cintura o un lacetto e usalo per legare (con consenso) i polsi di qualcuno per un minuto.',
      'Fatti guidare la mano da una persona consenziente ovunque voglia sopra i vestiti, per dieci secondi.',
      'Recita una frase da film erotico con la voce più roca che riesci a fare, davanti a tutti.',
      'Simula un bacio appassionato con il dorso della tua mano, il più realistico possibile.',
      'Descrivi al gruppo, guardando una persona consenziente, cosa faresti alle sue labbra se poteste.',
      'Sussurra un conto alla rovescia da cinque a uno all\'orecchio di qualcuno come se stesse per succedere qualcosa.',
      'Struscia lentamente la guancia contro quella di una persona consenziente come farebbe un gatto in calore.',
      'Mordi l\'aria vicino al collo di una persona consenziente senza toccarla, facendola rabbrividire.',
      'Traccia un cuore con la lingua sul palmo aperto di una persona consenziente.',
      'Balla mezzo minuto muovendo solo i fianchi, il più sensualmente possibile, davanti al gruppo.',
      'Appoggia le tue mani sui fianchi di una persona consenziente e guidala in un lento per venti secondi.',
      'Fatti soffiare sul collo da una persona consenziente e reagisci come se ti stesse facendo impazzire.',
      'Sussurra "chiudi gli occhi" a una persona consenziente e falle indovinare dove la sfiorerai.',
      'Descrivi ad alta voce il tuo risveglio ideale accanto alla persona alla tua destra.',
      'Fai finta di spogliarti con lo sguardo la persona più attraente della stanza, in silenzio, per dieci secondi.',
      'Bacia sulla guancia una persona consenziente scendendo pericolosamente vicino alle labbra.',
      'Mostra come baceresti qualcuno sotto la pioggia usando il gruppo come pubblico e un cuscino come partner.',
      'Racconta la volta in cui hai desiderato di più qualcuno senza poterlo avere.',
      'Passa una fragola (o un dito) sulle labbra di una persona consenziente e falla assaggiare.',
      'Fatti disegnare con un dito una linea dal collo alla mano da una persona consenziente e trattieni il respiro.',
      'Ripeti "vieni qui" con tre toni diversi finché il gruppo non decide quale è il più seducente.',
      'Fai un provino da protagonista di un film per adulti recitando la scena d\'apertura, vestito.',
      'Descrivi il posto esatto in cui vorresti essere baciato adesso e lascia che qualcuno provi (con consenso).',
      'Mima con le mani la silhouette della persona che trovi più sexy mentre la guardi negli occhi.',
      'Sussurra all\'orecchio di chi hai a sinistra il momento della giornata in cui pensi di più al sesso.',
      'Fatti mordere gentilmente l\'orecchio da una persona consenziente e non ridere per dieci secondi.',
      'Balla appoggiato di schiena a una persona consenziente, guidando i suoi movimenti coi fianchi.',
      'Racconta, guardandola, cosa ti attrae fisicamente della persona alla tua destra, dettaglio per dettaglio.',
      'Reggi lo sguardo di una persona consenziente mentre le baci lentamente il dorso della mano risalendo verso il polso.',
      'Fai il gesto di toglierti la maglia il più lentamente possibile, fermandoti a metà tra le proteste del gruppo.',
      'Sussurra una promessa piccante all\'orecchio della tua crush come se fosse un segreto di stato.',
      'Descrivi la scena di seduzione perfetta e assegna a un presente il ruolo del protagonista.',
      'Bacia con trasporto il tuo stesso avambraccio mostrando al gruppo esattamente come baci di solito.',
      'Fatti versare (o versa) qualche goccia d\'acqua sul collo e lasciala scivolare senza asciugarla per un round.',
      'Guarda una persona consenziente e mimale con le labbra, senza voce, tre parole che vorresti dirle a letto.',
      'Fai una camminata da modello su una passerella immaginaria fermandoti a mandare un bacio alla tua crush.',
      'Accarezza lentamente il braccio di chi hai accanto raccontando il tuo sogno erotico più recente.',
      'Metti una canzone lenta e invita a ballare la persona che desideri di più, corpo contro corpo.',
      'Fatti chiudere gli occhi e riconosci tre persone consenzienti solo dal profumo della loro pelle.',
      'Sussurra "sei tutto quello che voglio stasera" alla persona alla tua destra come se lo pensassi davvero.',
      'Descrivi cosa faresti a una persona consenziente se aveste solo cinque minuti in una stanza chiusa.',
      'Mordi delicatamente la spalla di un cuscino simulando come lasci un succhiotto a un partner.',
      'Reggi il mento di una persona consenziente e avvicina il viso al suo fino a un soffio dalle labbra.',
      'Recita una dichiarazione di puro desiderio alla persona più sexy della stanza, in ginocchio.',
      'Fai scorrere lentamente le tue mani lungo i tuoi fianchi mentre fissi la tua crush come in un video musicale.',
      'Sussurra il tuo momento preferito dei preliminari all\'orecchio di una persona consenziente.',
      'Fatti scegliere una parte del corpo da una persona consenziente e falle un complimento bollente su quella.',
      'Balla un tango improvvisato con una persona consenziente, finendo in una posa a pochi centimetri dal suo viso.',
      'Descrivi come sedurresti qualcuno usando solo la voce, e dimostralo su un presente per dieci secondi.',
      'Fatti scrivere sul collo con un dito il nome di chi ti attrae e fai indovinare al gruppo la persona.',
      'Racconta la fantasia che ti verrebbe voglia di realizzare proprio con qualcuno di questa stanza.',
      'Mostra al gruppo come ti muovi sopra un partner, usando un cuscino, per dieci secondi.',
      'Sussurra alla persona più attraente cosa noti per prima di lei ogni volta che entra in una stanza.',
      'Passa un dito sulle tue labbra lentamente mentre reggi lo sguardo della persona che desideri.',
      'Fatti dettare dal gruppo tre parole sporche e usale in una frase seducente rivolta alla tua crush.',
      'Bacia lentamente le nocche di una persona consenziente risalendo con lo sguardo fino ai suoi occhi.',
      'Descrivi il profumo del corpo che preferisci su un partner e annusa (con consenso) il collo di qualcuno per verificarlo.',
      'Fatti sussurrare all\'orecchio da una persona consenziente la sua fantasia e reagisci solo con lo sguardo.',
    ],
    ContentTone.hot: [
      'Dai un bacio con la lingua alla persona alla tua destra, se consenziente.',
      'Fatti togliere un indumento con i denti da una persona consenziente.',
      'Mima la tua posizione preferita su una persona consenziente per trenta secondi.',
      'Descrivi ad alta voce come porteresti a letto la persona di fronte a te.',
      'Mostra la faccia che fai quando raggiungi l\'orgasmo.',
      'Lecca il collo della persona alla tua sinistra fino a farla rabbrividire, se consenziente.',
      'Fai un succhiotto ben visibile sulla spalla di una persona consenziente.',
      'Siediti a cavalcioni su una persona consenziente e resta lì per un intero round.',
      'Simula un orgasmo rumoroso e realistico per venti secondi davanti a tutti.',
      'Sussurra all\'orecchio della persona di fronte la cosa più sporca che le faresti.',
      'Fai una lap dance di un minuto a una persona consenziente scelta dal gruppo.',
      'Mordicchia il lobo dell\'orecchio della persona alla tua destra, se consenziente.',
      'Passa un cubetto di ghiaccio dalla tua bocca a quella di una persona consenziente.',
      'Mostra al gruppo come muovi i fianchi durante il sesso, in piedi.',
      'Lecca via una goccia di bevanda dal collo di una persona consenziente.',
      'Togliti un capo di abbigliamento e restaci per i prossimi tre round.',
      'Mostra in che posizione dormi, sdraiandoti a terra.',
      'Bacia il punto del corpo che preferisci di una persona consenziente.',
      'Mima un rapporto orale su una banana o un altro oggetto per quindici secondi.',
      'Balla un lento corpo a corpo con una persona consenziente, mani libere.',
      'Descrivi con dovizia di dettagli l\'ultima volta che ti sei masturbato.',
      'Fai capire con i gesti quanto è dotato o dotata il tuo ex più memorabile.',
      'Metti la mano sulla coscia di una persona consenziente e lasciala lì un round.',
      'Imita i versi che fai a letto quando stai per venire.',
      'Lecca il dito di una persona consenziente nel modo più provocante possibile.',
      'Spogliati fino a restare in intimo e cambia posto con chi hai davanti.',
      'Fai vedere quanto sai essere sensuale togliendoti lentamente i calzini o le scarpe.',
      'Mordi delicatamente il collo di una persona consenziente lasciando il segno dei denti.',
      'Mostra il movimento di lingua che useresti in un bacio alla francese, su una mano.',
      'Sculaccia una persona consenziente e fatti sculacciare a tua volta.',
      'Descrivi la fantasia sessuale che ti fa eccitare di più, senza censure.',
      'Simula di cavalcare qualcuno stando seduto su una sedia per venti secondi.',
      'Fai un massaggio sensuale alla schiena di una persona consenziente per un minuto.',
      'Mostra come baci appassionatamente usando il dorso della tua mano.',
      'Metti a nudo la spalla e fatti baciare lì da una persona consenziente.',
      'Racconta a voce alta il sogno erotico più spinto che ricordi.',
      'Mima la posizione del missionario nell\'aria per dieci secondi, con espressione.',
      'Sussurra un gemito nell\'orecchio della persona alla tua destra, se consenziente.',
      'Fatti legare i polsi con una sciarpa da una persona consenziente per un round.',
      'Descrivi cosa ti eccita di più nel corpo della persona di fronte a te.',
      'Fai vedere come toglieresti il reggiseno con una mano sola, a occhi chiusi.',
      'Lecca la panna o lo zucchero da un dito di una persona consenziente.',
      'Mostra il tuo miglior primo piano di sguardo seducente, tenendolo dieci secondi.',
      'Simula un pompino a un cetriolo con la massima serietà per quindici secondi.',
      'Fatti soffiare sul collo da una persona consenziente e reagisci come faresti a letto.',
      'Descrivi la volta in cui hai avuto l\'orgasmo più intenso della tua vita.',
      'Balla la pole dance usando una sedia come palo per trenta secondi.',
      'Metti le labbra a un centimetro da quelle di chi hai davanti senza baciarlo, per dieci secondi.',
      'Fai un gemito crescente che finisce in un urlo, come un vero climax.',
      'Passa la lingua sul tuo labbro superiore fissando la persona che ti attrae di più qui.',
      'Togliti l\'intimo sotto i vestiti e mostralo al gruppo.',
      'Fatti mordere il collo da una persona consenziente per cinque secondi.',
      'Descrivi il tuo sex toy preferito e come lo usi.',
      'Mima di spogliare con lo sguardo ogni persona presente, uno alla volta.',
      'Fai una danza del ventre lenta e provocante per venti secondi.',
      'Lecca lentamente un dito e infilalo in bocca, guardando chi hai di fronte.',
      'Sussurra a una persona consenziente in che posizione la vorresti.',
      'Metti la testa in grembo a una persona consenziente per un round intero.',
      'Mostra come muovi la lingua quando fai sesso orale, su un ghiacciolo o su un cucchiaio.',
      'Fatti massaggiare le cosce da una persona consenziente per trenta secondi.',
      'Descrivi il punto del tuo corpo che ti fa impazzire quando viene toccato.',
      'Simula un amplesso appassionato con un cuscino per venti secondi.',
      'Bacia la mano di una persona consenziente risalendo fino al gomito.',
      'Fai vedere quanto sai essere sfacciato mimando uno spogliarello di dieci secondi.',
      'Sussurra all\'orecchio del gruppo, uno per uno, quanto li trovi arrapanti.',
      'Fatti coprire gli occhi e indovina chi ti bacia la guancia tra le persone consenzienti.',
      'Descrivi come ti piace essere toccato durante i preliminari.',
      'Mima la posizione della pecorina nell\'aria per dieci secondi, con convinzione.',
      'Lecca il collo del bicchiere in modo osceno mentre tutti guardano.',
      'Fai un twerk sfrenato di trenta secondi davanti al gruppo.',
      'Metti la mano di una persona consenziente sul tuo fianco e guidala mentre balli.',
      'Racconta la cosa più audace che hai fatto a letto per fare colpo.',
      'Simula di allacciare le gambe intorno a qualcuno usando l\'aria, restando in piedi.',
      'Fatti sfiorare la nuca da una persona consenziente e mostra come reagisci.',
      'Descrivi in dettaglio il rapporto sessuale che vorresti avere stasera.',
      'Fai il verso più erotico che sai fare guardando negli occhi chi ti attrae.',
      'Bacia il polso di una persona consenziente e sali lentamente con le labbra.',
      'Mostra come inarcheresti la schiena all\'apice del piacere.',
      'Sussurra tre parole sconce all\'orecchio della persona alla tua sinistra, se consenziente.',
      'Fatti mordere un dito da una persona consenziente in modo provocante.',
      'Descrivi la parte del corpo di una persona presente che ti fa più effetto.',
      'Simula un orgasmo lento sfiorandoti solo il collo e il viso.',
      'Fai una mossa di seduzione con lo sguardo e le labbra verso chi ti piace di più.',
      'Togliti la maglietta o slacciala e resta così per due round, se te la senti.',
      'Lecca il sale dalla mano di una persona consenziente prima di un cicchetto.',
      'Metti le mani sui fianchi di una persona consenziente e falla ballare con te.',
      'Descrivi la cosa più sporca che ti hanno mai sussurrato a letto.',
      'Mima di leccare qualcosa di molto intimo su un frutto per dieci secondi.',
      'Fatti stringere da dietro da una persona consenziente e resta così un round.',
      'Fai vedere come ti muovi quando sei sopra durante il sesso, su una sedia.',
      'Sussurra all\'orecchio di chi hai davanti il tuo desiderio più proibito.',
      'Bacia lentamente il collo di una persona consenziente contando fino a dieci.',
      'Mostra il tuo repertorio di gemiti in tre intensità diverse.',
      'Fatti soffiare piano sull\'orecchio da una persona consenziente e reagisci.',
      'Descrivi come useresti le mani su chi hai di fronte, se potessi.',
      'Simula un ballo di seduzione togliendoti lentamente una cintura o un accessorio.',
      'Lecca via lo zucchero dalle labbra di una persona consenziente, se accetta.',
      'Fai la tua migliore imitazione di come chiami il nome di qualcuno a letto.',
      'Metti la fronte contro quella di chi hai davanti e respira forte per dieci secondi.',
      'Descrivi la fantasia a tre che faresti e con chi la faresti.',
      'Mima uno spogliarello completo restando vestito, in trenta secondi.',
      'Fatti graffiare piano la schiena da una persona consenziente sopra i vestiti.',
      'Mostra come ancheggi entrando in una stanza per far girare la testa a tutti.',
      'Sussurra a una persona consenziente cosa le faresti se fossimo soli.',
      'Bacia l\'interno del polso di chi hai di fronte tenendo lo sguardo fisso.',
      'Descrivi il rumore che ti eccita di più durante il sesso.',
      'Simula un amplesso in piedi appoggiandoti al muro per quindici secondi.',
      'Fai capire con le mani la misura del sesso più impressionante che hai avuto.',
      'Lecca il dito indice e sfiora le tue labbra guardando chi ti attrae di più.',
      'Fatti tirare piano i capelli da una persona consenziente e mostra come reagisci.',
      'Descrivi il posto più assurdo dove ti piacerebbe fare sesso.',
      'Mima la posizione del 69 con un cuscino per dieci secondi.',
      'Fai una carezza sensuale sul viso di una persona consenziente scendendo al collo.',
      'Sussurra un elenco di tre cose che faresti a chi hai davanti stanotte.',
      'Mostra come balli attaccato a qualcuno in discoteca, usando una persona consenziente.',
      'Fatti dare un bacio a stampo sul collo da una persona consenziente.',
      'Descrivi la cosa più eccitante che ti è capitata in un luogo pubblico.',
      'Simula di gemere il nome della persona più sexy della stanza.',
      'Lecca la parte esterna della mano di chi hai di fronte in modo lento.',
      'Fai vedere come ti spogli quando vuoi sedurre qualcuno, con calma.',
      'Metti una mano tra i capelli di una persona consenziente e avvicina il viso.',
      'Descrivi cosa faresti con le labbra a chi ti attrae di più in questa stanza.',
      'Mima di essere ammanettato al letto per dieci secondi, con espressione.',
      'Fatti accarezzare la schiena scoperta da una persona consenziente, se accetta.',
      'Fai un gemito soffocato come se stessi trattenendoti in un posto pubblico.',
      'Sussurra all\'orecchio di chi hai a destra qual è il tuo feticcio, se consenziente.',
      'Bacia il collo di un cuscino come se fosse la persona che desideri di più.',
      'Descrivi la cosa più selvaggia che vorresti provare almeno una volta.',
      'Simula di essere sculacciato reagendo con un gemito, per dieci secondi.',
      'Lecca lentamente un lecca-lecca o un ghiacciolo fissando chi ti piace.',
      'Fai vedere come ti inarchi quando qualcuno ti bacia il punto giusto.',
      'Metti le labbra sulla spalla di una persona consenziente e sali fino all\'orecchio.',
      'Descrivi il preliminare che non ti stanca mai e ti manda in estasi.',
      'Mima un rapporto appassionato contro una porta per quindici secondi.',
      'Fatti mordere piano il labbro inferiore da una persona consenziente.',
      'Fai la tua faccia più provocante mentre ti passi le mani sul corpo.',
      'Sussurra a chi hai davanti quanto lo desideri, usando parole esplicite.',
      'Bacia le dita di una persona consenziente una a una in modo sensuale.',
      'Descrivi la posizione in cui raggiungi l\'orgasmo più facilmente.',
      'Simula un ballo erotico strofinandoti lentamente contro una sedia.',
      'Lecca via una goccia immaginaria dal petto o dal collo di chi hai davanti, se consenziente.',
      'Fai vedere come ti muovi sotto le lenzuola quando fai l\'amore.',
      'Metti la mano sul cuore di una persona consenziente e scendi piano verso l\'addome.',
      'Descrivi l\'orgasmo più lungo che tu abbia mai avuto e come è successo.',
      'Mima di succhiare un dito in modo osceno per dieci secondi guardando il gruppo.',
      'Fatti stringere forte da una persona consenziente e sussurrale un gemito.',
      'Fai la tua espressione da climax mentre inarchi la schiena, per cinque secondi.',
      'Sussurra all\'orecchio di ognuno cosa ti piacerebbe fargli, in un giro completo.',
      'Fai vedere come reagisci quando ti mordicchiano il collo, con voce e brividi.',
      'Mima il tuo momento di piacere più intenso, con voce e movimenti, per dieci secondi.',
    ],
  };

  static const Map<String, List<String>> verita = {
    ContentTone.normal: [
      'Qual è la cosa più imbarazzante che hai fatto in pubblico?',
      'Qual è stata la tua bugia più grossa da bambino?',
      'Qual è il tuo guilty pleasure musicale?',
      'Quale film ti ha fatto piangere di più?',
      'Qual è la cosa più stupida per cui hai litigato?',
      'Qual è il tuo peggior difetto secondo te?',
      'Quale difetto ti attribuiscono gli amici e tu non riconosci per niente?',
      'Qual è la cosa più costosa che hai rotto?',
      'Hai mai finto di stare male per evitare qualcosa?',
      'Qual è la scusa che usi più spesso?',
      'Cosa fai quando sei solo e nessuno ti vede?',
      'Qual è la tua abitudine più strana?',
      'Quanto tempo passi davvero sul telefono ogni giorno?',
      'Qual è l\'app che apri più spesso senza motivo?',
      'Qual è stata la tua ultima ricerca su internet, quella vera?',
      'Qual è la foto più vecchia che hai nel telefono?',
      'Chi è l\'ultima persona a cui hai scritto?',
      'Qual è il messaggio più imbarazzante che hai mandato?',
      'Hai mai mandato un messaggio alla persona sbagliata? Cosa diceva?',
      'Qual è la cosa più bella che ti ha detto qualcuno?',
      'Qual è il complimento più strano che tu abbia mai ricevuto?',
      'Chi è la persona più importante della tua vita?',
      'Chi chiameresti se avessi un problema serio alle tre di notte?',
      'Qual è la cosa che apprezzi di più in un amico?',
      'Qual è stato il momento più bello di quest\'anno?',
      'Qual è stato il momento più difficile di quest\'anno?',
      'Di cosa hai più paura per il futuro?',
      'Qual è il tuo sogno che non hai ancora detto a nessuno?',
      'Cosa faresti se domani non dovessi più lavorare?',
      'Se potessi cambiare una decisione, quale sarebbe?',
      'Qual è la cosa di cui vai più fiero?',
      'Qual è il complimento che vorresti ricevere?',
      'Cosa ti mette di buon umore in cinque minuti?',
      'Qual è la cosa che ti fa arrabbiare più in fretta?',
      'Qual è la mania da cui non riesci a liberarti?',
      'Sei più ordinato o disordinato di quanto ammetti?',
      'Quando è stata l\'ultima volta che hai riso fino alle lacrime?',
      'Qual è la cosa più coraggiosa che hai fatto?',
      'Cosa non faresti mai per soldi?',
      'Per quanti soldi ti faresti tagliare i capelli a zero?',
      'Qual è il tuo talento nascosto?',
      'Qual è una cosa che tutti sanno fare tranne te?',
      'Qual è la cosa più difficile che hai imparato?',
      'Che voto daresti alla tua vita adesso, da 1 a 10?',
      'Cosa ti manca per arrivare a un 10 pieno?',
      'Qual è il posto più bello in cui sei stato?',
      'Dove vorresti vivere se potessi scegliere?',
      'Qual è il viaggio che rifaresti domani?',
      'Qual è la vacanza peggiore che hai fatto?',
      'Hai mai perso un volo o un treno? Com\'è finita?',
      'Qual è la cosa più strana che hai mangiato?',
      'Qual è il piatto che sai cucinare meglio?',
      'Qual è il tuo cibo di conforto?',
      'Mangeresti lo stesso piatto per un mese per mille euro?',
      'Qual è la cosa più inutile che hai comprato?',
      'Quanto tempo ci metti davvero a prepararti?',
      'Qual è il vestito che non butti anche se dovresti?',
      'Qual è la moda che hai seguito e ora rinneghi?',
      'Che taglio di capelli rimpiangi?',
      'Faresti un tatuaggio? Dove e cosa?',
      'Qual è la cosa che hai fatto solo per far contento qualcun altro?',
      'Hai mai finto di aver capito qualcosa per non fare brutta figura?',
      'Qual è l\'argomento su cui bluffi di più?',
      'Qual è il libro che dici di aver letto ma non hai finito?',
      'Qual è la serie che hai abbandonato a metà?',
      'Qual è il personaggio che ti somiglia di più?',
      'Se fossi un animale, quale saresti e perché?',
      'Se dovessi cambiare nome, quale sceglieresti?',
      'Qual è il soprannome che odiavi da piccolo?',
      'Qual è la cosa più noiosa che hai fatto per lavoro?',
      'Qual è il collega o compagno di classe che non sopportavi e perché?',
      'Qual è la cosa che rimandi da più tempo?',
      'A che ora vai davvero a dormire?',
      'Quante volte spegni la sveglia prima di alzarti?',
      'Qual è il tuo posto preferito in casa?',
      'Cosa salveresti se dovessi scappare da casa in un minuto?',
      'Qual è l\'oggetto a cui sei più affezionato?',
      'Qual è il regalo più bello che hai ricevuto?',
      'Qual è il regalo più brutto che hai mai ricevuto?',
      'Hai mai riciclato un regalo?',
      'Qual è la promessa di inizio anno che non hai mai mantenuto?',
      'Quale abitudine vorresti eliminare?',
      'Quale abitudine vorresti iniziare?',
      'Chi del gruppo chiameresti per un consiglio serio?',
      'Chi del gruppo ti fa ridere di più?',
      'Cosa hai imparato dalle persone presenti stasera?',
      'Cosa vorresti che il gruppo sapesse di te?',
      'Qual è la domanda che speravi non uscisse stasera?',
      'C\'è qualcosa che hai sempre voluto chiedere a qualcuno qui?',
      'Se dovessi descrivere questa serata con una parola, quale?',
      'Qual è la cosa più imbarazzante che ti è successa a scuola?',
      'Qual è il sogno notturno più assurdo che ricordi?',
      'Qual è la bugia bianca che dici più spesso?',
      'Quale cibo fingi di apprezzare per pura educazione?',
      'Se avessi un superpotere per un giorno, cosa faresti per prima cosa?',
      'Quale persona famosa vorresti a cena e cosa le chiederesti?',
      'Qual è la cosa più divertente che sia successa a una tua riunione di famiglia?',
      'Se potessi scambiarti la vita con qualcuno per un giorno, chi sceglieresti?',
      'Qual è la canzone che canti sempre sbagliando le parole?',
      'Qual è la cosa più strana che hai fatto per noia?',
      'Ti è mai scappato da ridere in un momento in cui era vietatissimo? Racconta.',
      'Qual è la figuraccia che oggi ti fa ridere ma sul momento ti ha distrutto?',
      'Qual è l\'oggetto più strano che tieni in camera?',
      'Qual è la cosa più infantile che fai ancora oggi?',
      'Se la tua vita fosse un film, quale attore ti interpreterebbe?',
      'Qual è stata la tua peggiore idea "geniale"?',
      'Hai mai cantato allo specchio usando la spazzola come microfono?',
      'Qual è la parola che sbagli sempre a pronunciare?',
      'Qual è il tuo record più assurdo, qualunque cosa valga come record?',
      'Cosa faresti per primo se vincessi un milione domani mattina?',
      'Qual è l\'app più inutile che hai scaricato e mai usato?',
      'Ti sei mai addormentato in un posto assurdo? Dove?',
      'Qual è la cosa che cerchi su internet perché ti vergogni di non saperla?',
      'Qual è il piatto che hai rovinato nel modo più spettacolare?',
      'Qual è la regola di casa tua che credevi normale e invece era stranissima?',
      'Quale personaggio dei cartoni ti faceva paura da bambino?',
      'Qual è la cosa più assurda a cui credevi da bambino?',
      'Hai mai risposto al saluto di qualcuno che salutava un\'altra persona?',
      'Qual è la notifica che ti mette più ansia?',
      'Qual è la canzone che ti fa partire i ricordi ogni volta?',
      'Se potessi teletrasportarti ovunque per un giorno, dove andresti?',
      'Quale mestiere sognavi di fare da bambino?',
      'Qual è la cosa che tutti amano e tu proprio no?',
      'Quale programma trash guardi e difenderesti a spada tratta?',
      'Hai mai parlato con il tuo animale o con le piante come se capissero tutto?',
      'Qual è la cosa che sai fare peggio ma continui a fare con entusiasmo?',
      'Qual è il messaggio più bello che conservi nel telefono?',
      'Qual è la teoria strampalata a cui un po\' credi anche se sai che è assurda?',
      'Qual è il tuo piano di sopravvivenza in caso di apocalisse zombie?',
      'Preferiresti saper volare o leggere nel pensiero, e perché?',
      'Qual è la scusa più creativa che hai usato per un ritardo?',
      'Cosa facevi da bambino che vorresti fosse socialmente accettabile anche oggi?',
      'Chi del gruppo sopravvivrebbe più a lungo su un\'isola deserta secondo te?',
      'Qual è la parola italiana che trovi più buffa?',
      'Qual è il suono o rumore che proprio non sopporti?',
      'Qual è la cosa più carina che hai fatto in segreto per qualcuno?',
      'Hai mai vinto qualcosa a un concorso o a una lotteria? Cosa?',
      'Qual è il gusto di gelato che secondo te andrebbe vietato per legge?',
      'Qual è il film che tutti adorano e tu non sei mai riuscito a finire?',
      'Qual è il cibo che fingi di non amare ma mangeresti di nascosto?',
      'Qual è la canzone che canti solo quando sei sicuro che nessuno ti senta?',
      'Qual è la cosa più assurda che fai quando sei sicuro che nessuno ti guardi?',
      'Qual è il tuo talento più inutile?',
      'Qual è la paura più irrazionale che hai?',
      'Qual è il regalo peggiore che hai mai riciclato?',
      'Cosa c\'è di più imbarazzante nella tua cronologia di YouTube?',
      'Qual è la scusa che usi più spesso per andartene da una festa?',
      'Qual è il cartone animato che guarderesti ancora adesso senza vergogna?',
      'Se potessi scambiare il tuo lavoro con quello di uno dei presenti per un giorno, chi sceglieresti?',
      'Qual è il complimento che ti fa più piacere ricevere?',
    ],
    ContentTone.mix: [
  'Com'è stata la tua prima volta? Età, luogo, posizione e voto da 1 a 10.',
  'Con quante persone sei stato a letto? Di\' il numero esatto, senza arrotondare.',
  'Qual è il posto più assurdo o rischioso in cui l\'hai fatto?',
  'Hai mai fatto sesso anale? Ti è piaciuto? Sii onesto.',
  'Sei mai andato a letto con qualcuno il giorno stesso in cui l\'hai conosciuto? Quante volte?',
  'Qual è stato il tuo one night stand più folle e dove è successo?',
  'Hai mai fatto sesso con un amico e poi fatto finta di niente? Chi era?',
  'Hai mai fatto sexting con più di tre persone contemporaneamente?',
  'Qual è il messaggio più sporco che hai mai inviato o ricevuto? Citalo.',
  'Hai mai mandato o ricevuto un video hard di te stesso? Lo faresti ancora?',
  'Hai mai ricevuto una foto audace non richiesta? Qual è stata la tua reazione vera?',
  'Qual è la tua fantasia erotica più estrema che non hai mai detto a nessuno?',
  'Hai mai fatto una cosa a tre? Se no, con chi di questo gruppo la faresti?',
  'C\'è una persona in questa stanza con cui passeresti volentieri la notte? Un nome.',
  'Preferiresti un orgasmo pazzesco di tre minuti o un\'ora di coccole perfette?',
  'Chi è stato il miglior amante della tua vita e perché? Cosa faceva di speciale?',
  'Hai mai baciato due persone diverse nella stessa ora? Dove eravate?',
  'Ti sei mai pentito amaramente di essere andato a letto con qualcuno mentre lo stavi facendo?',
  'Ti sei mai svegliato accanto a qualcuno e sei scappato dalla finestra o di nascosto?',
  'Cosa conta di più a letto: la tecnica, le dimensioni o l\'intesa mentale?',
  'A letto sei più dominante o sottomesso? Fai un esempio di cosa ti piace fare.',
  'Luci accese, specchi e video, oppure buio totale? Motiva la scelta.',
  'Qual è il complimento più eccitante che ti hanno fatto durante il sesso?',
  'Hai mai finto un orgasmo per far finire prima il rapporto? Quante volte?',
  'Qual è la cosa più imbarazzante che ti sia mai successa mentre lo facevi?',
  'Sei mai stato beccato dai tuoi genitori o da un estraneo mentre eri in azione?',
  'Hai mai fatto finta di dormire per evitare di farlo? Perché non ne avevi voglia?',
  'Hai mai raccontato bugie sulle tue prestazioni per fare colpo sugli amici?',
  'Qual è stata la tua maratona di sesso più lunga? Quante volte in un giorno?',
  'C\'è qualcuno in questo gruppo che ti ha mai fatto eccitare anche solo parlando?',
  'Cosa guardi per primo in una persona che ti fa pensare "voglio andarci a letto"?',
  'Qual è il capo di abbigliamento che trovi più sexy in assoluto? E quello che ti spegne?',
  'Ti consideri bravo a letto? Qual è il tuo punto di forza imbattibile?',
  'Cosa vorresti imparare a fare meglio a letto? Hai mai guardato tutorial?',
  'Qual è la frase di rimorchio più sfacciata che hai usato e ha funzionato?',
  'Hai mai flirtato con il partner di un amico stretto? Fin dove sei arrivato?',
  'Hai mai dato un numero falso a qualcuno dopo averci limonato? Perché?',
  'Qual è la cosa più audace che hai fatto in un luogo pubblico affollato?',
  'Hai mai avuto un flirt estivo che è finito con un video o foto hot?',
  'Qual è stata la massima differenza d\'età che hai avuto in una storia di sesso?',
  'Hai mai baciato qualcuno di questa stanza senza che gli altri lo sapessero?',
  'Chi di noi baceresti subito se si spegnesse la luce per un minuto?',
  'Chi di noi secondo te è il più "selvaggio" a letto, guardandolo ora?',
  'Hai mai usato un\'app di incontri solo per sesso occasionale? Quanti match finiti a letto?',
  'Qual è la chat più compromettente che hai nel telefono in questo momento?',
  'Hai mai scritto a un ex alle tre di notte solo perché avevi voglia di farlo?',
  'Qual è la cosa che ti manca di più a letto del tuo ultimo partner?',
  'Hai mai avuto una storia segreta con una persona impegnata? Com\'è finita?',
  'Sei mai stato "l\'altro" o "l\'altra" consapevolmente? Ti sei sentito in colpa?',
  'Qual è il tuo "kink" più strano o inconfessabile?',
  'Sopra o sotto? Davanti o dietro? Rispondi velocemente, senza pensarci.',
  'Hai mai provato dolore a letto e hai scoperto che ti piaceva?',
  'Hai mai fatto sesso in un ufficio o sul posto di lavoro?',
  'Ti sei mai toccato pensando a una persona presente in questa stanza?',
  'Qual è la parte del tuo corpo che riceve più complimenti a letto?',
  'Hai mai ballato uno strip-tease per qualcuno? Com\'è andata?',
  'Qual è la cosa più sporca che hai mai detto a qualcuno mentre lo facevate?',
  'Se potessi scegliere una persona famosa per una notte di solo sesso, chi sarebbe?',
  'Hai mai fatto sesso in un mare, piscina o vasca idromassaggio pubblica?',
  'Qual è l\'ora del giorno in cui ti senti più eccitato di solito?',
  'Cosa indossi di solito per dormire quando sei con qualcuno che vuoi provocare?',
  'Hai mai fatto sesso con i calzini addosso? Il gruppo ti giudica se dici sì.',
  'Qual è la posizione che trovi più faticosa ma che ti dà più piacere?',
  'Hai mai provato il sesso tantrico o sessioni lunghissime? Racconta.',
  'Hai mai usato cibo o ghiaccio durante i preliminari? Com\'è finita?',
  'Qual è il segnale inequivocabile che mandi quando vuoi farlo subito?',
  'Chi di noi porteresti in una stanza privata adesso, se potessi?',
  'Qual è la prima cosa che ti fa capire che una persona ti desidera davvero?',
  'Hai mai baciato qualcuno del tuo stesso sesso? Ti è piaciuto o è rimasta curiosità?',
  'Qual è il gesto apparentemente innocente che ti eccita più di qualsiasi altro?',
  'Preferisci sedurre o farti sedurre? Fai un esempio concreto della tua ultima conquista.',
  'Qual è la cosa più coraggiosa che hai chiesto a letto e come è stata accolta?',
  'Hai mai avuto un sogno erotico su una persona presente in questa stanza?',
  'Qual è la parte del corpo di un partner che ti fa perdere completamente la testa?',
  'Quanto dura per te la notte perfetta e quante volte vorresti farlo?',
  'Hai mai usato un sex toy in coppia? Se no, ti piacerebbe provarci?',
  'Qual è la bugia più grande che hai raccontato per andare a letto con qualcuno?',
  'Hai mai avuto una cotta segreta per un amico del tuo partner?',
  'Qual è il posto della tua casa in cui ti piace di più farlo, a parte il letto?',
  'Hai mai fatto sesso al primo appuntamento? Ti sei pentito o rifatto?',
  'Qual è la frase che ti fa cadere ai piedi di qualcuno all\'istante?',
  'Preferisci un massaggio erotico lentissimo o passare subito al sodo?',
  'Qual è la cosa più audace che hai indossato per far impazzire qualcuno?',
  'Hai mai spiato o ascoltato per sbaglio due persone che lo facevano? Racconta.',
  'Qual è il tuo record di durata dei preliminari e ne vorresti di più o di meno?',
  'Se dovessi descrivere il tuo stile a letto con una sola parola, quale sarebbe?',
  'Hai mai avuto un incontro segreto in un bagno pubblico o in una macchina?',
  'Qual è stata la volta in cui hai desiderato qualcuno che non potevi avere?',
  'Ti sei mai innamorato di qualcuno solo per come baciava?',
  'Qual è la cosa che nessuno immaginerebbe mai su di te a letto?',
  'Hai mai mandato un messaggio hot alla persona sbagliata? Com\'è finita?',
  'Chi di questa stanza, secondo te, è il più bravo a flirtare senza farsi notare?',
  'Qual è il tuo limite assoluto a letto, la cosa che non faresti mai?',
  'Hai mai baciato qualcuno solo per far ingelosire un\'altra persona?',
  'Qual è la parte di te che vorresti che qualcuno baciasse più spesso?',
  'Hai mai avuto una relazione basata solo sul sesso? Quanto è durata?',
  'Qual è la fantasia che condividi con il tuo partner ma non hai mai realizzato?',
  'Ti eccita di più la voce, lo sguardo o le mani di una persona?',
  'Hai mai finto di non essere interessato a qualcuno che invece desideravi tantissimo?',
  'Qual è stata la seduzione più lunga prima di finire finalmente a letto con qualcuno?',
  'Hai mai fatto sesso ascoltando una canzone specifica? Quale?',
  'Qual è il complimento fisico che ti fa sentire immediatamente desiderabile?',
  'Hai mai avuto un colpo di fulmine puramente fisico? Con chi e come è andata?',
  'Preferisci baci lenti e profondi o mordaci e frenetici?',
  'Qual è la cosa più piccante che ti hanno sussurrato mentre lo facevate?',
  'Hai mai desiderato due persone contemporaneamente? Come hai gestito la cosa?',
  'Qual è il tuo profumo, tuo o altrui, che associ al sesso migliore che hai fatto?',
  'Hai mai flirtato spudoratamente con qualcuno davanti al tuo partner?',
  'Qual è la posizione che vorresti provare ma non hai mai avuto il coraggio di proporre?',
  'Hai mai avuto un\'esperienza a più di due? Se no, la faresti e con chi qui?',
  'Cosa ti fa passare la voglia all\'istante mentre stai per farlo?',
  'Qual è la cosa più sexy che una persona possa fare completamente vestita?',
  'Hai mai avuto un flirt con qualcuno di molto più grande o più giovane di te?',
  'Qual è il tuo segnale segreto per far capire a qualcuno che lo vuoi, stasera?',
  'Ti sei mai eccitato in un momento totalmente inappropriato? Dove eri?',
  'Qual è la cosa che ti rende un amante indimenticabile, secondo chi è stato con te?',
  'Hai mai continuato a pensare a un ex mentre eri a letto con un altro?',
  'Qual è la parola più sporca che ti piace sentirti dire all\'orecchio?',
  'Hai mai baciato qualcuno sotto l\'effetto dell\'adrenalina, tipo dopo un pericolo?',
  'Preferisci il sesso programmato e curato o quello improvviso e travolgente?',
  'Qual è la volta in cui hai rischiato di più di essere scoperto in azione?',
  'Hai mai scritto o ricevuto una lettera o un messaggio erotico che conservi ancora?',
  'Chi di questa stanza baceresti, chi porteresti a letto e chi eviteresti? Sii onesto.',
  'Qual è il tuo pensiero più sporco quando vedi qualcuno che ti piace tantissimo?',
  'Hai mai avuto un\'avventura in vacanza che non hai mai raccontato a nessuno?',
  'Qual è il gioco di ruolo che ti piacerebbe provare almeno una volta nella vita?',
  'Ti sei mai svegliato eccitato accanto a un amico? Cos\'hai fatto?',
  'Qual è la cosa più imbarazzante che hai cercato online sul sesso?',
  'Hai mai avuto paura di deludere qualcuno a letto? Come è andata poi?',
  'Qual è il momento in cui ti sei sentito più desiderato in assoluto?',
  'Preferisci fare l\'amore al buio o guardare tutto negli occhi del partner?',
  'Hai mai baciato più di una persona nella stessa serata? Quante?',
  'Qual è la cosa più folle che faresti per una notte con la persona che desideri?',
  'Ti è mai capitato di dover trattenere i gemiti per non farti sentire? Dove?',
  'Qual è la tua zona erogena segreta che pochi hanno scoperto?',
  'Hai mai iniziato tu, senza esitare, con una persona appena conosciuta?',
  'Qual è la cosa che ti fa sentire più sicuro di te quando sei nudo?',
  'Hai mai avuto una relazione a distanza sostenuta solo da videochiamate hot?',
  'Qual è il ricordo erotico che riaffiora più spesso quando sei solo?',
  'Se il partner dei tuoi sogni ti chiedesse una sola cosa a letto, cosa vorresti che fosse?',
  'Hai mai fatto sesso di riappacificazione dopo un litigio furioso? Era migliore?',
  'Qual è la persona con cui l\'intesa a letto è stata più forte e perché?',
  'Hai mai provato a resistere a una tentazione e poi ceduto miseramente? Con chi?',
  'Qual è la parte del corpo del tuo partner ideale che guardi per prima?',
  'Ti eccita di più essere guardato o guardare mentre lo fai?',
  'Hai mai fatto un patto "amici con benefici" che è finito male? Racconta.',
  'Qual è la cosa più romantica e la più sporca che vorresti nella stessa notte?',
  'Chi di questa stanza pensi ci stia provando con te in questo momento?',
  'Qual è la domanda più intima che vorresti fare a una persona presente stasera?',
  'Qual è la cosa che ti ecciterebbe fare proprio adesso, se il gioco lo permettesse?',
  ],
  ContentTone.hot: [
  'Hai mai legato o ti sei fatto legare durante il sesso?',
  'Hai mai assaggiato lo sperma o l\'eiaculazione del partner?',
  'Ti piacerebbe fare una cosa a tre? Con chi dei presenti?',
  'Qual è il posto più rischioso in cui l\'hai fatto?',
  'Quante volte al giorno ti masturbi, in media?',
  'Qual è la posizione sessuale che ti fa raggiungere l\'orgasmo più in fretta?',
  'Hai mai finto un orgasmo? Con quante persone?',
  'Qual è la cosa più sporca che ti hanno sussurrato a letto?',
  'Hai mai fatto sesso orale in un luogo pubblico?',
  'Con chi dei presenti faresti sesso senza pensarci due volte?',
  'Qual è il tuo sex toy preferito e quanto spesso lo usi?',
  'Hai mai avuto un orgasmo solo grazie al sesso orale?',
  'Ti eccita di più dare o ricevere sesso orale?',
  'Hai mai mandato un video intimo a qualcuno?',
  'Qual è la fantasia sessuale che non hai mai confessato a nessuno?',
  'Hai mai fatto sesso con più di una persona nella stessa notte?',
  'Qual è la parte del corpo che ti fa perdere la testa quando viene toccata?',
  'Hai mai provato il bondage o l\'idea ti eccita?',
  'Quanto è durato il rapporto sessuale più lungo che hai avuto?',
  'Hai mai fatto sesso al primo appuntamento?',
  'Qual è la cosa più kinky che hai fatto a letto?',
  'Hai mai baciato una persona del tuo stesso sesso?',
  'Ti sei mai masturbato pensando a qualcuno dei presenti?',
  'Qual è il numero di partner che hai avuto finora?',
  'Hai mai avuto un rapporto anale? Ti è piaciuto?',
  'Qual è la tua zona erogena più segreta?',
  'Hai mai usato manette o costrizioni durante il sesso?',
  'Quanto tempo impieghi di solito a raggiungere l\'orgasmo?',
  'Hai mai fatto sesso in auto? Dove eravate parcheggiati?',
  'Chi dei presenti immagini sia il migliore a letto?',
  'Hai mai provato lo spanking, dandolo o ricevendolo?',
  'Qual è la cosa più audace che hai fatto per far eccitare un partner?',
  'Hai mai fatto sesso mentre altri erano nella stanza accanto?',
  'Ti piace il sesso al buio o con la luce accesa?',
  'Hai mai avuto un rapporto con qualcuno molto più grande o più giovane di te?',
  'Qual è il tuo feticcio più particolare?',
  'Hai mai fatto sesso in acqua, in piscina o al mare?',
  'Quante volte a settimana vorresti fare sesso, idealmente?',
  'Hai mai provato il sesso bendato?',
  'Con chi dei tuoi ex rifaresti sesso anche solo per una notte?',
  'Qual è la posizione che non sopporti a letto?',
  'Hai mai avuto un orgasmo multiplo?',
  'Hai mai leccato o baciato una parte del corpo poco convenzionale del partner?',
  'Qual è il pensiero più sporco che hai avuto oggi?',
  'Hai mai fatto sesso con qualcuno di cui non ricordavi il nome?',
  'Ti eccita l\'idea di essere guardato mentre fai sesso?',
  'Hai mai usato cibo durante i preliminari? Cosa?',
  'Qual è la fantasia che vorresti realizzare con una delle persone presenti?',
  'Hai mai fatto sesso in casa dei genitori di qualcuno?',
  'Quanto conta per te l\'aspetto fisico di un partner, da uno a dieci?',
  'Hai mai provato dolore consensuale durante il sesso e ti è piaciuto?',
  'Qual è la cosa più strana che ti ha eccitato?',
  'Hai mai avuto un rapporto con due persone contemporaneamente?',
  'Ti masturbi più al mattino o alla sera?',
  'Hai mai fatto sesso telefonico o in videochiamata?',
  'Qual è il posto sul tuo corpo dove vorresti essere baciato più spesso?',
  'Hai mai simulato una scena porno con un partner?',
  'Con chi dei presenti scambieresti volentieri un bacio con la lingua?',
  'Hai mai avuto una storia solo per il sesso?',
  'Qual è stato il tuo orgasmo più imbarazzante da spiegare?',
  'Hai mai indossato lingerie o intimo particolare per sedurre qualcuno?',
  'Ti piace parlare sporco durante il sesso o ti mette a disagio?',
  'Hai mai fatto sesso in un bagno pubblico?',
  'Quanti minuti durano di solito i tuoi preliminari?',
  'Hai mai provato il sesso tantrico o lento e prolungato?',
  'Qual è la cosa più sfacciata che hai chiesto a letto?',
  'Hai mai fatto sesso con un collega o un capo?',
  'Ti eccita di più il sesso passionale o quello dolce?',
  'Hai mai avuto un incontro organizzato solo online per il sesso?',
  'Qual è la parte del tuo corpo di cui vai più fiero a letto?',
  'Hai mai fatto sesso all\'aria aperta, in un bosco o in un parco?',
  'Con chi dei presenti flirteresti se fossi single stasera?',
  'Hai mai provato più di un orgasmo nello stesso rapporto?',
  'Qual è la cosa più proibita che vorresti provare almeno una volta?',
  'Hai mai fatto sesso con qualcuno molto più esperto di te?',
  'Ti piace essere dominato o preferisci avere il controllo?',
  'Hai mai avuto un rapporto in una doccia o in una vasca?',
  'Qual è il tuo record di rapporti in una sola giornata?',
  'Hai mai baciato due persone nella stessa serata?',
  'Qual è la posizione in cui ti senti più sexy?',
  'Hai mai fatto sesso mentre eri al telefono con qualcun altro?',
  'Ti sei mai eccitato in un momento totalmente inopportuno?',
  'Hai mai fatto sesso con la persona sbagliata e te ne sei pentito?',
  'Qual è la cosa più intima che hai confessato solo a un partner?',
  'Hai mai provato il sesso con l\'uso di un vibratore condiviso?',
  'Con chi dei presenti pensi di avere più affinità sessuale?',
  'Hai mai fatto sesso su un tavolo o un ripiano della cucina?',
  'Ti piace guardare video hot da solo o in coppia?',
  'Hai mai avuto un rapporto in ascensore o in un luogo insolito?',
  'Qual è il complimento più eccitante che ti hanno fatto sul corpo?',
  'Hai mai provato il gioco di ruolo a letto? Quale scenario?',
  'Quante posizioni diverse riesci a fare in un solo rapporto?',
  'Hai mai avuto un orgasmo solo con la stimolazione del collo o delle orecchie?',
  'Qual è la cosa che ti fa venire voglia di sesso all\'istante?',
  'Hai mai fatto sesso in tenda o in campeggio?',
  'Ti sei mai innamorato di qualcuno solo per com\'era a letto?',
  'Hai mai usato oli o creme durante il sesso o i massaggi?',
  'Qual è la persona presente con cui non hai mai flirtato ma ci hai pensato?',
  'Hai mai fatto sesso senza dire una parola per tutto il tempo?',
  'Ti eccita di più baciare il collo o le labbra?',
  'Hai mai fatto sesso in un hotel a ore?',
  'Qual è la cosa più sfrenata che ti ha proposto un partner?',
  'Hai mai provato a essere legato mani e piedi?',
  'Con chi dei presenti condivideresti volentieri una notte di passione?',
  'Hai mai avuto un rapporto interrotto sul più bello? Da chi?',
  'Ti piace fare sesso con la musica o in silenzio totale?',
  'Hai mai leccato del cibo dal corpo di un partner?',
  'Qual è la fantasia che ti fa raggiungere l\'orgasmo più velocemente?',
  'Hai mai fatto sesso con qualcuno appena conosciuto in vacanza?',
  'Quanto sei rumoroso a letto, da uno a dieci?',
  'Hai mai provato una sculacciata come parte del gioco erotico?',
  'Qual è la cosa che ti fa impazzire nei preliminari?',
  'Hai mai fatto sesso in un luogo dove potevate essere scoperti?',
  'Ti sei mai masturbato in un posto pubblico?',
  'Hai mai desiderato l\'attuale o l\'ex partner di un amico presente?',
  'Qual è il momento più eccitante che ricordi con un partner?',
  'Hai mai provato il sesso con gli occhi bendati e le mani legate?',
  'Con quale persona famosa faresti sesso senza esitazione?',
  'Hai mai fatto sesso più di tre volte in una notte?',
  'Ti piace di più il sesso mattutino o quello notturno?',
  'Hai mai baciato qualcuno solo per scommessa e poi ti è piaciuto?',
  'Qual è la cosa più erotica che hai scritto in un messaggio?',
  'Hai mai fatto sesso in casa di amici durante una festa?',
  'Qual è il tuo punto debole quando qualcuno vuole sedurti?',
  'Hai mai provato a fare sesso con un accessorio o un giocattolo nuovo?',
  'Con chi dei presenti ti immagini una notte da ricordare?',
  'Hai mai fatto sesso in un luogo di lavoro?',
  'Ti eccita di più il contatto visivo o le parole durante il sesso?',
  'Hai mai avuto un rapporto così intenso da restare senza forze?',
  'Qual è la cosa più sporca che hai fatto per soddisfare un partner?',
  'Hai mai fatto sesso su una spiaggia di notte?',
  'Ti piace essere morso durante il sesso?',
  'Hai mai avuto un orgasmo troppo forte da farti quasi imbarazzare?',
  'Qual è la parte del corpo del partner che baci per prima?',
  'Hai mai provato a fare sesso davanti a uno specchio?',
  'Con chi dei presenti condivideresti il tuo segreto più erotico?',
  'Hai mai fatto sesso con qualcuno che avevi giurato di evitare?',
  'Ti piace prendere l\'iniziativa o essere sedotto?',
  'Hai mai avuto una fantasia su una persona con cui non dovresti?',
  'Qual è la cosa più audace che indosseresti solo per una notte speciale?',
  'Hai mai fatto sesso mentre pioveva, fuori o vicino a una finestra aperta?',
  'Ti sei mai eccitato guardando qualcuno spogliarsi senza che lo sapesse?',
  'Hai mai provato più partner nella stessa settimana?',
  'Qual è il gesto che ti fa capire subito che vuoi qualcuno a letto?',
  'Hai mai fatto sesso e riso per qualcosa di imbarazzante successo?',
  'Con chi dei presenti faresti volentieri un gioco di seduzione?',
  'Hai mai fatto sesso pensando a una persona diversa da quella con cui eri?',
  'Qual è la cosa più eccitante che qualcuno ti ha detto di volerti fare?',
  'Hai mai avuto un rapporto così silenzioso da dover trattenere ogni gemito?',
  'Qual è il desiderio sessuale più segreto che non hai mai detto a nessuno qui?',
  ],
};
}