import '../content_tone.dart';

/// Pool gratuito di "Chi lo potrebbe fare": 152 domande sul gruppo.
class ChiLoPotrebbeFarePool {
  const ChiLoPotrebbeFarePool._();

  static const List<({String text, String tone})> entries =
      <({String text, String tone})>[
        // ---------------------------------------------------------- soft
        (text: 'Chi si perderebbe in una città che conosce da anni?', tone: ContentTone.soft),
        (text: 'Chi arriverebbe in ritardo al proprio matrimonio?', tone: ContentTone.soft),
        (text: 'Chi diventerebbe famoso per sbaglio?', tone: ContentTone.soft),
        (text: 'Chi sopravvivrebbe più a lungo su un\'isola deserta?', tone: ContentTone.soft),
        (text: 'Chi passerebbe un weekend intero senza uscire di casa?', tone: ContentTone.soft),
        (text: 'Chi attaccherebbe bottone con uno sconosciuto in ascensore?', tone: ContentTone.soft),
        (text: 'Chi dimenticherebbe il proprio anniversario?', tone: ContentTone.soft),
        (text: 'Chi litigherebbe con il navigatore?', tone: ContentTone.soft),
        (text: 'Chi comprerebbe qualcosa online alle tre di notte?', tone: ContentTone.soft),
        (text: 'Chi mangerebbe pizza per sette giorni di fila?', tone: ContentTone.soft),
        (text: 'Chi si addormenterebbe al cinema?', tone: ContentTone.soft),
        (text: 'Chi canterebbe al karaoke senza esitare?', tone: ContentTone.soft),
        (text: 'Chi ballerebbe per primo a una festa?', tone: ContentTone.soft),
        (text: 'Chi resterebbe seduto tutta la sera senza ballare?', tone: ContentTone.soft),
        (text: 'Chi organizzerebbe la vacanza di tutto il gruppo?', tone: ContentTone.soft),
        (text: 'Chi perderebbe il passaporto in aeroporto?', tone: ContentTone.soft),
        (text: 'Chi porterebbe tre valigie per due giorni?', tone: ContentTone.soft),
        (text: 'Chi partirebbe domani con lo zaino e basta?', tone: ContentTone.soft),
        (text: 'Chi si trasferirebbe all\'estero senza pensarci?', tone: ContentTone.soft),
        (text: 'Chi tornerebbe a vivere con i genitori senza problemi?', tone: ContentTone.soft),
        (text: 'Chi adotterebbe dieci gatti?', tone: ContentTone.soft),
        (text: 'Chi parlerebbe al proprio cane come a una persona?', tone: ContentTone.soft),
        (text: 'Chi dimenticherebbe di innaffiare le piante fino a farle morire?', tone: ContentTone.soft),
        (text: 'Chi terrebbe il frigo sempre vuoto?', tone: ContentTone.soft),
        (text: 'Chi cucinerebbe per venti persone senza motivo?', tone: ContentTone.soft),
        (text: 'Chi brucerebbe l\'acqua della pasta?', tone: ContentTone.soft),
        (text: 'Chi mangerebbe il dolce prima del primo?', tone: ContentTone.soft),
        (text: 'Chi ordinerebbe sempre la stessa cosa al ristorante?', tone: ContentTone.soft),
        (text: 'Chi assaggerebbe qualsiasi cosa, anche la più strana?', tone: ContentTone.soft),
        (text: 'Chi rimanderebbe indietro un piatto al ristorante?', tone: ContentTone.soft),
        (text: 'Chi lascerebbe la mancia più generosa?', tone: ContentTone.soft),
        (text: 'Chi dimenticherebbe il portafoglio proprio quando tocca a lui pagare?', tone: ContentTone.soft),
        (text: 'Chi terrebbe lo scontrino di ogni caffè?', tone: ContentTone.soft),
        (text: 'Chi spenderebbe tutto lo stipendio in una settimana?', tone: ContentTone.soft),
        (text: 'Chi diventerebbe milionario per un\'idea assurda?', tone: ContentTone.soft),
        (text: 'Chi investirebbe in qualcosa senza capirci niente?', tone: ContentTone.soft),
        (text: 'Chi vincerebbe alla lotteria e non lo direbbe a nessuno?', tone: ContentTone.soft),
        (text: 'Chi presterebbe soldi senza chiederli indietro?', tone: ContentTone.soft),
        (text: 'Chi contratterebbe il prezzo anche al supermercato?', tone: ContentTone.soft),
        (text: 'Chi comprerebbe un attrezzo da palestra e non lo userebbe mai?', tone: ContentTone.soft),
        (text: 'Chi si iscriverebbe in palestra a gennaio e mollerebbe a febbraio?', tone: ContentTone.soft),
        (text: 'Chi correrebbe una maratona senza allenarsi?', tone: ContentTone.soft),
        (text: 'Chi si farebbe male facendo una cosa banale?', tone: ContentTone.soft),
        (text: 'Chi andrebbe al pronto soccorso per un\'unghia rotta?', tone: ContentTone.soft),
        (text: 'Chi non andrebbe dal medico nemmeno con 39 di febbre?', tone: ContentTone.soft),
        (text: 'Chi cercherebbe i sintomi su internet e si convincerebbe di stare morendo?', tone: ContentTone.soft),
        (text: 'Chi dormirebbe fino alle due del pomeriggio?', tone: ContentTone.soft),
        (text: 'Chi si sveglierebbe alle cinque per vedere l\'alba?', tone: ContentTone.soft),
        (text: 'Chi metterebbe dieci sveglie e le spegnerebbe tutte?', tone: ContentTone.soft),
        (text: 'Chi arriverebbe con un\'ora di anticipo ovunque?', tone: ContentTone.soft),
        (text: 'Chi manderebbe messaggi vocali di sette minuti?', tone: ContentTone.soft),
        (text: 'Chi risponderebbe solo con emoji?', tone: ContentTone.soft),
        (text: 'Chi lascerebbe i messaggi in sospeso per giorni?', tone: ContentTone.soft),
        (text: 'Chi chiamerebbe invece di scrivere?', tone: ContentTone.soft),
        (text: 'Chi avrebbe il telefono sempre all\'1% di batteria?', tone: ContentTone.soft),
        (text: 'Chi farebbe cento foto per pubblicarne una?', tone: ContentTone.soft),
        (text: 'Chi non pubblicherebbe mai niente sui social?', tone: ContentTone.soft),
        (text: 'Chi commenterebbe ogni singolo post degli amici?', tone: ContentTone.soft),
        (text: 'Chi si dimenticherebbe di rispondere a un invito importante?', tone: ContentTone.soft),
        (text: 'Chi direbbe di sì a tutto e poi si pentirebbe?', tone: ContentTone.soft),
        (text: 'Chi cancellerebbe un piano all\'ultimo minuto?', tone: ContentTone.soft),
        (text: 'Chi sarebbe l\'ultimo ad andarsene da una festa?', tone: ContentTone.soft),
        (text: 'Chi se ne andrebbe senza salutare nessuno?', tone: ContentTone.soft),
        (text: 'Chi porterebbe a casa gli avanzi del buffet?', tone: ContentTone.soft),
        (text: 'Chi litigherebbe per l\'ultimo pezzo di torta?', tone: ContentTone.soft),
        (text: 'Chi si offrirebbe di fare da autista tutta la sera?', tone: ContentTone.soft),
        (text: 'Chi guiderebbe cantando a squarciagola?', tone: ContentTone.soft),
        (text: 'Chi si perderebbe pur avendo il navigatore acceso?', tone: ContentTone.soft),
        (text: 'Chi prenderebbe una multa per divieto di sosta lo stesso giorno due volte?', tone: ContentTone.soft),
        (text: 'Chi darebbe un nome alla propria macchina?', tone: ContentTone.soft),
        (text: 'Chi terrebbe la macchina immacolata?', tone: ContentTone.soft),
        (text: 'Chi avrebbe la camera in disordine perenne?', tone: ContentTone.soft),
        (text: 'Chi pulirebbe casa alle due di notte?', tone: ContentTone.soft),
        (text: 'Chi comprerebbe un mobile e non riuscirebbe a montarlo?', tone: ContentTone.soft),
        (text: 'Chi riparerebbe qualsiasi cosa con lo scotch?', tone: ContentTone.soft),
        (text: 'Chi chiamerebbe un tecnico per cambiare una lampadina?', tone: ContentTone.soft),
        (text: 'Chi guarderebbe un tutorial e si sentirebbe un esperto?', tone: ContentTone.soft),
        (text: 'Chi finirebbe una serie in una notte sola?', tone: ContentTone.soft),
        (text: 'Chi spoilerebbe il finale senza accorgersene?', tone: ContentTone.soft),
        (text: 'Chi piangerebbe per una pubblicità?', tone: ContentTone.soft),
        (text: 'Chi riderebbe nel momento meno opportuno?', tone: ContentTone.soft),
        (text: 'Chi resterebbe serio anche davanti alla battuta migliore?', tone: ContentTone.soft),
        (text: 'Chi racconterebbe la stessa storia per la decima volta?', tone: ContentTone.soft),
        (text: 'Chi interromperebbe sempre gli altri?', tone: ContentTone.soft),
        (text: 'Chi ascolterebbe tutti senza mai parlare di sé?', tone: ContentTone.soft),
        (text: 'Chi darebbe consigli non richiesti?', tone: ContentTone.soft),
        (text: 'Chi organizzerebbe una sorpresa perfetta?', tone: ContentTone.soft),
        (text: 'Chi rovinerebbe una sorpresa parlando troppo?', tone: ContentTone.soft),
        (text: 'Chi ricorderebbe i compleanni di tutti?', tone: ContentTone.soft),
        (text: 'Chi farebbe il regalo comprato all\'ultimo minuto?', tone: ContentTone.soft),
        (text: 'Chi impacchetterebbe un regalo in modo disastroso?', tone: ContentTone.soft),
        (text: 'Chi terrebbe le decorazioni di Natale fino a marzo?', tone: ContentTone.soft),
        (text: 'Chi si commuoverebbe al matrimonio di un amico?', tone: ContentTone.soft),
        (text: 'Chi farebbe il discorso più lungo a una cena?', tone: ContentTone.soft),
        (text: 'Chi imparerebbe una lingua nuova per hobby?', tone: ContentTone.soft),
        (text: 'Chi si iscriverebbe a un corso e non ci andrebbe mai?', tone: ContentTone.soft),
        (text: 'Chi vincerebbe una gara di mangiatori di hot dog?', tone: ContentTone.soft),
        (text: 'Chi diventerebbe vegetariano da un giorno all\'altro?', tone: ContentTone.soft),
        (text: 'Chi scriverebbe un libro sulla propria vita?', tone: ContentTone.soft),
        (text: 'Chi aprirebbe un canale e lo abbandonerebbe dopo tre video?', tone: ContentTone.soft),
        (text: 'Chi si candiderebbe a un reality?', tone: ContentTone.soft),
        // ------------------------------------------------------ piccante
        (text: 'Chi manderebbe un messaggio a un ex alle tre di notte?', tone: ContentTone.piccante),
        (text: 'Chi tornerebbe con un ex per la terza volta?', tone: ContentTone.piccante),
        (text: 'Chi si innamorerebbe in vacanza nel giro di due giorni?', tone: ContentTone.piccante),
        (text: 'Chi direbbe "ti amo" per primo?', tone: ContentTone.piccante),
        (text: 'Chi lascerebbe qualcuno con un messaggio?', tone: ContentTone.piccante),
        (text: 'Chi flirterebbe con il cameriere davanti a tutti?', tone: ContentTone.piccante),
        (text: 'Chi userebbe la stessa battuta di rimorchio da dieci anni?', tone: ContentTone.piccante),
        (text: 'Chi avrebbe più chat aperte contemporaneamente?', tone: ContentTone.piccante),
        (text: 'Chi controllerebbe il telefono del partner?', tone: ContentTone.piccante),
        (text: 'Chi nasconderebbe una relazione a tutto il gruppo?', tone: ContentTone.piccante),
        (text: 'Chi bacerebbe qualcuno per una scommessa?', tone: ContentTone.piccante),
        (text: 'Chi si dichiarerebbe davanti a tutti?', tone: ContentTone.piccante),
        (text: 'Chi ghosterebbe qualcuno senza spiegazioni?', tone: ContentTone.piccante),
        (text: 'Chi risponderebbe a una storia solo per farsi notare?', tone: ContentTone.piccante),
        (text: 'Chi guarderebbe il profilo di un ex ogni settimana?', tone: ContentTone.piccante),
        (text: 'Chi metterebbe like a una foto di tre anni fa per sbaglio?', tone: ContentTone.piccante),
        (text: 'Chi racconterebbe un segreto dopo due bicchieri?', tone: ContentTone.piccante),
        (text: 'Chi direbbe una bugia guardandoti negli occhi?', tone: ContentTone.piccante),
        (text: 'Chi finirebbe a cantare sul tavolo di un locale?', tone: ContentTone.piccante),
        (text: 'Chi si addormenterebbe alla propria festa di compleanno?', tone: ContentTone.piccante),
        (text: 'Chi dimenticherebbe un\'intera serata?', tone: ContentTone.piccante),
        (text: 'Chi manderebbe messaggi di cui si pentirebbe la mattina dopo?', tone: ContentTone.piccante),
        (text: 'Chi chiamerebbe un amico per farsi salvare da un appuntamento?', tone: ContentTone.piccante),
        (text: 'Chi mentirebbe sulla propria età a un appuntamento?', tone: ContentTone.piccante),
        (text: 'Chi userebbe una foto profilo di dieci anni fa?', tone: ContentTone.piccante),
        (text: 'Chi si presenterebbe a un primo appuntamento in ritardo di un\'ora?', tone: ContentTone.piccante),
        (text: 'Chi parlerebbe dell\'ex durante un primo appuntamento?', tone: ContentTone.piccante),
        (text: 'Chi si farebbe un tatuaggio d\'impulso in vacanza?', tone: ContentTone.piccante),
        (text: 'Chi ballerebbe sul bancone dopo il terzo drink?', tone: ContentTone.piccante),
        (text: 'Chi si tufferebbe in piscina vestito?', tone: ContentTone.piccante),
        (text: 'Chi farebbe il bagno senza costume?', tone: ContentTone.piccante),
        (text: 'Chi convincerebbe tutti a fare una cosa che non volevano fare?', tone: ContentTone.piccante),
        (text: 'Chi ruberebbe un bicchiere da un locale come souvenir?', tone: ContentTone.piccante),
        (text: 'Chi finirebbe a discutere con un buttafuori?', tone: ContentTone.piccante),
        (text: 'Chi rimarrebbe chiuso in un bagno di un locale?', tone: ContentTone.piccante),
        (text: 'Chi passerebbe la notte in bianco per una discussione?', tone: ContentTone.piccante),
        (text: 'Chi urlerebbe in mezzo alla strada per farsi sentire?', tone: ContentTone.piccante),
        (text: 'Chi litigherebbe con un amico per una sciocchezza?', tone: ContentTone.piccante),
        (text: 'Chi terrebbe il broncio per una settimana?', tone: ContentTone.piccante),
        (text: 'Chi chiederebbe scusa per primo?', tone: ContentTone.piccante),
        (text: 'Chi origlierebbe una conversazione privata?', tone: ContentTone.piccante),
        (text: 'Chi leggerebbe i messaggi sullo schermo di un altro?', tone: ContentTone.piccante),
        (text: 'Chi condividerebbe lo screenshot di una chat privata?', tone: ContentTone.piccante),
        (text: 'Chi creerebbe un profilo falso per curiosare?', tone: ContentTone.piccante),
        (text: 'Chi direbbe di essere a casa mentre è fuori?', tone: ContentTone.piccante),
        (text: 'Chi darebbe buca senza avvisare?', tone: ContentTone.piccante),
        (text: 'Chi fingerebbe di stare male per saltare un impegno?', tone: ContentTone.piccante),
        (text: 'Chi finirebbe a piangere in bagno a una festa?', tone: ContentTone.piccante),
        (text: 'Chi bacerebbe qualcuno di questo gruppo, se non fosse un gioco?', tone: ContentTone.cattivo),
        (text: 'Chi ha già mentito almeno una volta stasera?', tone: ContentTone.cattivo),
        (text: 'Chi sta pensando a qualcuno proprio adesso?', tone: ContentTone.cattivo),
      ];

  static int get length => entries.length;
}
