/// Obbligo o Verità — tono soft: si può giocare con chiunque, anche in
/// famiglia. 100 obblighi + 100 verità.
class ObbligoOVeritaSoft {
  const ObbligoOVeritaSoft._();

  static const List<String> obblighi = <String>[
    'Imita il modo di camminare della persona alla tua destra.',
    'Canta il ritornello dell\'ultima canzone che hai ascoltato.',
    'Parla in rima fino al tuo prossimo turno.',
    'Fai il verso di tre animali e falli indovinare.',
    'Balla dieci secondi senza musica.',
    'Racconta una barzelletta: se nessuno ride, ripetila più forte.',
    'Imita il tuo personaggio preferito di una serie.',
    'Fai una posa da statua e resta immobile per trenta secondi.',
    'Parla come un telecronista sportivo per un minuto.',
    'Mostra l\'ultima foto che hai scattato.',
    'Mostra la tua schermata home senza aprire nulla.',
    'Leggi ad alta voce l\'ultima nota che hai salvato nel telefono.',
    'Fai vedere quante sveglie hai impostato.',
    'Di\' il nome dell\'ultima canzone che hai messo in ripetizione.',
    'Manda un messaggio vocale cantato a un tuo contatto a caso.',
    'Chiama un amico e cantagli tanti auguri anche se non è il suo compleanno.',
    'Fai un complimento sincero a ogni persona presente.',
    'Descrivi la persona alla tua sinistra usando solo tre parole.',
    'Racconta la cosa più imbarazzante che ti è successa a scuola.',
    'Imita l\'insegnante che ricordi peggio.',
    'Fai finta di essere un venditore e vendici questo tavolo.',
    'Presenta il meteo di domani come in televisione.',
    'Parla con accento straniero fino al prossimo giro.',
    'Racconta la trama di un film senza dire il titolo, gli altri indovinano.',
    'Fai un discorso di ringraziamento come se avessi vinto un premio.',
    'Improvvisa una pubblicità per il tuo oggetto più vicino.',
    'Fai vedere come balli quando sei solo in casa.',
    'Canta al posto di parlare per i prossimi due minuti.',
    'Cammina con un libro in equilibrio sulla testa.',
    'Fai dieci saltelli contando ad alta voce in un\'altra lingua.',
    'Tieni gli occhi chiusi fino alla fine del turno.',
    'Metti i vestiti al contrario per due round.',
    'Fatti fare una nuova pettinatura da chi sta alla tua destra.',
    'Fai un disegno del gruppo in trenta secondi.',
    'Scrivi il tuo nome con la mano sbagliata e mostralo.',
    'Fai lo spelling del tuo cognome al contrario.',
    'Recita l\'alfabeto al contrario più veloce che puoi.',
    'Conta fino a venti saltando i multipli di tre.',
    'Racconta una storia inventata di trenta secondi che inizi con "Ieri notte…".',
    'Racconta la tua giornata come se fosse un film horror.',
    'Descrivi il tuo lavoro o la tua giornata tipo come farebbe un bambino.',
    'Fai finta di essere un robot per un minuto.',
    'Rispondi solo con domande fino al prossimo turno.',
    'Non puoi dire "sì" né "no" fino al tuo prossimo turno.',
    'Chiama qualcuno per nome sbagliato per tutto il round.',
    'Ridi il più forte possibile senza motivo.',
    'Prova a fare la ruota, o spiega perché non ci riesci.',
    'Fai venti secondi di plank mentre gli altri contano.',
    'Fai cinque flessioni contate dal gruppo.',
    'Corri sul posto fino alla fine del turno.',
    'Bevi un bicchiere d\'acqua tutto d\'un fiato.',
    'Mangia qualcosa scelto dalla persona alla tua sinistra.',
    'Assaggia due cose insieme che non stanno bene insieme.',
    'Descrivi il sapore di una cosa che stai mangiando come un critico.',
    'Prepara un drink analcolico e fallo assaggiare a qualcuno.',
    'Fai un brindisi improvvisato in onore del gruppo.',
    'Racconta il tuo ricordo più bello con una persona presente.',
    'Racconta come hai conosciuto chi ti sta di fronte.',
    'Di\' cosa invidi (in senso buono) a ogni persona presente.',
    'Fai una previsione sul futuro di una persona presente.',
    'Assegna un soprannome a ognuno e spiegalo.',
    'Scegli chi del gruppo porteresti su un\'isola deserta e perché.',
    'Racconta la cosa più costosa che hai comprato inutilmente.',
    'Confessa una tua abitudine strana.',
    'Racconta una tua paura ridicola.',
    'Fai finta di avere paura di un oggetto della stanza.',
    'Racconta un tuo talento inutile e dimostralo.',
    'Mostra il tuo miglior "trucco di magia" improvvisato.',
    'Fai un origami con quello che trovi in un minuto.',
    'Costruisci una torre con tre oggetti della stanza.',
    'Trova tre oggetti gialli in casa in trenta secondi.',
    'Scambia una cosa che indossi con chi ti sta a destra.',
    'Fai un selfie con la faccia più brutta che riesci a fare.',
    'Fatti una foto imitando la posa di chi sta alla tua sinistra.',
    'Fai un video di dieci secondi come se fossi un influencer.',
    'Registra un messaggio motivazionale per il gruppo.',
    'Leggi l\'oroscopo di oggi con voce drammatica.',
    'Inventa un oroscopo per la persona alla tua destra.',
    'Descrivi come sarà la tua vita tra dieci anni, senza pensarci troppo.',
    'Racconta il sogno più assurdo che ricordi.',
    'Racconta la bugia più innocente che dici più spesso.',
    'Confessa quale cibo fingi di apprezzare.',
    'Di\' quale canzone conosci a memoria e cantane un pezzo.',
    'Fai il karaoke di dieci secondi senza musica.',
    'Fischia una canzone e falla indovinare.',
    'Fai un beatbox di cinque secondi.',
    'Imita il suono di tre strumenti diversi.',
    'Fai finta di suonare la chitarra come a un concerto.',
    'Balla come se fossi in discoteca da solo.',
    'Insegna al gruppo un passo di ballo.',
    'Fai fare al gruppo un riscaldamento di dieci secondi.',
    'Guida il gruppo in un applauso ritmato.',
    'Fai una foto di gruppo dando tu le indicazioni.',
    'Scegli la colonna sonora della serata e spiega perché.',
    'Racconta la cosa più bella che ti è successa questa settimana.',
    'Di\' una cosa che vorresti imparare e perché non hai iniziato.',
    'Fai un elenco di tre cose per cui sei grato adesso.',
    'Manda un messaggio carino a una persona a cui non scrivi da tempo.',
    'Chiama tua madre o un parente e digli che gli vuoi bene.',
    'Scrivi in chat di gruppo una frase decisa dagli altri (niente di offensivo).',
    'Lascia che il gruppo scelga il tuo prossimo obbligo del turno seguente.',
  ];

  static const List<String> verita = <String>[
    'Qual è la cosa più imbarazzante che hai fatto in pubblico?',
    'Qual è stata la tua bugia più grossa da bambino?',
    'Qual è il tuo piacere colpevole musicale?',
    'Quale film ti ha fatto piangere di più?',
    'Qual è la cosa più stupida per cui hai litigato?',
    'Qual è il tuo peggior difetto secondo te?',
    'E secondo i tuoi amici qual è?',
    'Qual è la cosa più costosa che hai rotto?',
    'Hai mai finto di stare male per evitare qualcosa?',
    'Qual è la scusa che usi più spesso?',
    'Cosa fai quando sei solo e nessuno ti vede?',
    'Qual è la tua abitudine più strana?',
    'Quanto tempo passi davvero sul telefono ogni giorno?',
    'Qual è l\'app che apri più spesso senza motivo?',
    'Qual è l\'ultima cosa che hai cercato su internet?',
    'Qual è la foto più vecchia che hai nel telefono?',
    'Chi è l\'ultima persona a cui hai scritto?',
    'Qual è il messaggio più imbarazzante che hai mandato?',
    'Hai mai mandato un messaggio alla persona sbagliata? Cosa diceva?',
    'Qual è la cosa più bella che ti ha detto qualcuno?',
    'Qual è il complimento che ricordi ancora?',
    'Chi è la persona più importante della tua vita?',
    'Chi chiameresti se avessi un problema serio alle tre di notte?',
    'Qual è la cosa che apprezzi di più in un amico?',
    'Qual è stato il momento più bello di quest\'anno?',
    'E il peggiore?',
    'Di cosa hai più paura per il futuro?',
    'Qual è il tuo sogno che non hai ancora detto a nessuno?',
    'Cosa faresti se domani non dovessi più lavorare?',
    'Se potessi cambiare una decisione, quale sarebbe?',
    'Qual è la cosa di cui vai più fiero?',
    'Qual è il complimento che vorresti ricevere?',
    'Cosa ti mette di buon umore in cinque minuti?',
    'Qual è la cosa che ti fa arrabbiare più in fretta?',
    'Qual è la tua manie da cui non riesci a liberarti?',
    'Sei più ordinato o disordinato di quanto ammetti?',
    'Quando è stata l\'ultima volta che hai pianto?',
    'Quando è stata l\'ultima volta che hai riso fino alle lacrime?',
    'Qual è la cosa più coraggiosa che hai fatto?',
    'Cosa non faresti mai per soldi?',
    'Quanto ti costerebbe farti tagliare i capelli a zero?',
    'Qual è il tuo talento nascosto?',
    'Qual è una cosa che tutti sanno fare tranne te?',
    'Qual è la cosa più difficile che hai imparato?',
    'Che voto daresti alla tua vita adesso, da 1 a 10?',
    'Cosa ti manca per farlo diventare 10?',
    'Qual è il posto più bello in cui sei stato?',
    'Dove vorresti vivere se potessi scegliere?',
    'Qual è il viaggio che rifaresti domani?',
    'Qual è la vacanza peggiore che hai fatto?',
    'Hai mai perso un volo o un treno? Come è finita?',
    'Qual è la cosa più strana che hai mangiato?',
    'Qual è il piatto che sai cucinare meglio?',
    'Qual è il tuo cibo di conforto?',
    'Mangeresti lo stesso piatto per un mese per mille euro?',
    'Qual è la cosa più inutile che hai comprato?',
    'Quanto tempo ci metti davvero a prepararti?',
    'Ti guardi allo specchio più di quanto ammetti?',
    'Qual è il vestito che non butti anche se dovresti?',
    'Qual è la moda che hai seguito e ora rinneghi?',
    'Che taglio di capelli rimpiangi?',
    'Faresti un tatuaggio? Dove e cosa?',
    'Qual è la cosa che hai fatto solo per far contento qualcun altro?',
    'Hai mai finto di aver capito qualcosa per non fare brutta figura?',
    'Qual è l\'argomento su cui bluffi di più?',
    'Qual è il libro che dici di aver letto ma non hai finito?',
    'Qual è la serie che hai abbandonato a metà?',
    'Quante volte hai rivisto il tuo film preferito?',
    'Qual è il personaggio che ti somiglia di più?',
    'Se fossi un animale, quale saresti e perché?',
    'Se dovessi cambiare nome, quale sceglieresti?',
    'Qual è il soprannome che odiavi da piccolo?',
    'Qual è stato il tuo primo lavoro?',
    'Qual è la cosa più noiosa che hai fatto per lavoro?',
    'Qual è il collega che non sopportavi e perché?',
    'Se il capo non ti sentisse, cosa gli diresti?',
    'Qual è la cosa che rimandi da più tempo?',
    'A che ora vai davvero a dormire?',
    'Quante volte spegni la sveglia prima di alzarti?',
    'Qual è la cosa che fai appena sveglio?',
    'Hai un rituale prima di dormire?',
    'Qual è il tuo posto preferito in casa?',
    'Cosa salveresti se dovessi scappare da casa in un minuto?',
    'Qual è l\'oggetto a cui sei più affezionato?',
    'Da chi lo hai avuto?',
    'Qual è il regalo più bello che hai ricevuto?',
    'E il regalo peggiore?',
    'Hai mai riciclato un regalo?',
    'Qual è la festa che ti piace di meno?',
    'Come passi di solito il capodanno?',
    'Qual è la promessa di inizio anno che non hai mai mantenuto?',
    'Quale abitudine vorresti eliminare?',
    'Quale abitudine vorresti iniziare?',
    'Chi del gruppo chiameresti per un consiglio serio?',
    'Chi del gruppo ti fa ridere di più?',
    'Cosa hai imparato dalle persone presenti stasera?',
    'Cosa vorresti che il gruppo sapesse di te?',
    'Qual è la domanda che speravi non uscisse stasera?',
    'C\'è qualcosa che hai sempre voluto chiedere a qualcuno qui?',
    'Se dovessi descrivere questa serata con una parola, quale?',
  ];
}
