/// Obbligo o Verità — tono piccante: seduzione diretta e senza giri di parole.
/// Obblighi fisici e di flirt (sempre con partner consenzienti), verità che
/// nominano apertamente notti, fantasie e vita di letto, mai graficamente
/// esplicite. Oltre un centinaio di obblighi e altrettante verità.
class ObbligoOVeritaPiccante {
  const ObbligoOVeritaPiccante._();

  static const List<String> obblighi = <String>[
    'Fai un massaggio alle spalle di trenta secondi a una persona consenziente a tua scelta: lei deve dare un voto ad alta voce.',
    'Sussurra all\'orecchio della persona alla tua destra la frase più audace che ti viene in mente.',
    'Bacia la mano di ogni persona del gruppo guardandola negli occhi, come un seduttore d\'altri tempi.',
    'Dai un bacio sulla guancia, il più vicino possibile all\'orecchio, a una persona consenziente scelta dal gruppo.',
    'Fai una lap dance scherzosa di quindici secondi a una persona consenziente scelta dal gruppo.',
    'Balla un lento sensuale, guancia a guancia, con una persona consenziente per trenta secondi.',
    'Traccia con un dito il profilo del viso della persona alla tua sinistra (se ci sta), in silenzio totale.',
    'Tieni la mano della persona più attraente della stanza fino al tuo prossimo turno, senza spiegare la scelta.',
    'Fatti bendare e riconosci tre persone del gruppo toccando solo mani e braccia.',
    'Fatti bendare e lasciati imboccare qualcosa da una persona scelta dal gruppo.',
    'Appoggia la testa sulle gambe di una persona consenziente e restaci per un round intero.',
    'Abbraccia da dietro una persona consenziente e sussurrale "mi sei mancato" con la voce più calda che hai.',
    'Guarda negli occhi la persona che trovi più attraente per venti secondi senza parlare: il gruppo commenta.',
    'Soffia delicatamente sul collo della persona consenziente alla tua destra, poi torna a sederti come se niente fosse.',
    'Fai l\'occhiolino più provocante che hai a ogni persona del gruppo, una alla volta, senza ridere.',
    'Morditi lentamente il labbro guardando la persona di fronte finché uno dei due cede e ride.',
    'Togli un accessorio o uno strato (scarpe, calze, camicia sopra la maglietta: scegli tu) nel modo più sensuale possibile.',
    'Rifai la scena più sensuale di un film che conosci, usando una persona consenziente come partner di scena.',
    'Balla per venti secondi come se stessi cercando di sedurre tutta la stanza contemporaneamente.',
    'Fai il verso di come reagisci quando ti fanno un massaggio perfetto, con l\'audio.',
    'Recita il tuo repertorio da sexting ad alta voce, come se fosse una poesia. Inventa se serve, ma poco.',
    'Detta al gruppo, parola per parola, il messaggio di seduzione perfetto per conquistare la tua crush.',
    'Descrivi ad alta voce come sedurresti la persona alla tua sinistra, passo per passo, guardandola.',
    'Insegna al gruppo la tua mossa firmata per passare dal divano alla camera da letto.',
    'Spiega passo per passo come trasformi un appuntamento in una notte insieme, dall\'aperitivo alla porta di casa.',
    'Fai una pubblicità di trenta secondi di te stesso come amante, senza falsa modestia.',
    'Racconta la tua notte migliore come se fosse il trailer di un film: niente nomi, ma il clima deve arrivare.',
    'Descrivi il tuo bacio perfetto nei dettagli mentre guardi la persona di fronte, senza staccare gli occhi.',
    'Di\' ad alta voce la frase esatta che useresti per invitare qualcuno a passare la notte da te.',
    'Sussurra "buonanotte" con la tua voce più sensuale all\'orecchio di tre persone diverse.',
    'Interpreta la scena: ti svegli accanto alla tua crush. Mostra la faccia, la prima frase e la mossa successiva.',
    'Fai la tua imitazione di come flirti dopo il terzo drink, con dedizione totale.',
    'Manda un bacio al rallentatore alla persona di fronte, mantenendo il contatto visivo dall\'inizio alla fine.',
    'Mostra al rallentatore come baci, con l\'aria come partner: il gruppo dà un voto da 1 a 10.',
    'Manda "Che fai più tardi?" alla persona con cui hai flirtato più di recente e mostra la risposta quando arriva.',
    'Manda "Sto pensando a cose che non posso scrivere qui." a un contatto scelto da te.',
    'Manda un\'emoji di fuoco all\'ultima persona con cui hai flirtato e mostra la risposta.',
    'Leggi ad alta voce il messaggio più audace nella chat con la tua ultima fiamma.',
    'Mostra la conversazione più piccante che sei disposto a far vedere al gruppo.',
    'Leggi ad alta voce l\'ultimo messaggio che hai mandato dopo mezzanotte, con il tono con cui l\'hai pensato.',
    'Fai vedere la foto di te stesso in cui ti trovi più irresistibile.',
    'Scrivi "Ho pensato a te tutta la sera." alla persona che ti piace e mostra la risposta quando arriva.',
    'Fai leggere al gruppo la tua bio da app di incontri, o creane una adesso senza censure.',
    'Manda un vocale di dieci secondi con la tua voce più sensuale a un contatto scelto dal gruppo (niente offese).',
    'Registra un vocale leggendo la lista della spesa come se fosse un audio proibito.',
    'Racconta fino a dove ti sei spinto nel primo appuntamento più riuscito della tua vita.',
    'Racconta la tua notte più folle in trenta secondi: puoi saltare i dettagli, non i fatti.',
    'Confessa la fantasia più confessabile che hai e incassa i commenti del gruppo senza difenderti.',
    'Elenca tre cose che ti fanno perdere la testa a letto, in ordine crescente di imbarazzo.',
    'Racconta il tuo risveglio più imbarazzante a casa di qualcun altro.',
    'Racconta come è iniziata la tua ultima avventura, fermando il racconto sulla porta della camera.',
    'Di\' ad alta voce il posto più assurdo dove l\'hai fatto: solo il posto, niente storia.',
    'Racconta la volta in cui sei stato beccato nel momento sbagliato.',
    'Racconta la tua peggior figura in un momento di intimità, senza fare nomi.',
    'Confessa l\'orario più assurdo in cui hai mandato (o ricevuto) un "sei sveglio?".',
    'Rivela il tuo record: quanto poco tempo è passato tra "piacere, come ti chiami" e il resto.',
    'Mima la tua reazione quando ricevi una foto audace che non ti aspettavi.',
    'Di\' quale canzone metteresti come colonna sonora di una notte importante e difendi la scelta.',
    'Descrivi il tuo "dopo": sei da abbraccio, da silenzio, da frigo o da fuga?',
    'Di\' chi del gruppo ha lo sguardo più pericoloso e cosa ti aspetteresti da una sua serata.',
    'Scegli la persona del gruppo con cui condivideresti la tenda in campeggio e spiega il criterio, tutto il criterio.',
    'Fai la classifica dei presenti per "carisma da fine serata", dal primo all\'ultimo, e difendila.',
    'Assegna a ogni presente un livello di pericolosità sentimentale da 1 a 10, a voce alta.',
    'Di\' quale coppia potenziale di questa stanza funzionerebbe a meraviglia e quale sarebbe un disastro.',
    'Scegli chi del gruppo sopravviverebbe meglio a una storia con te e chiedigli scusa in anticipo.',
    'Fai a una persona del gruppo, guardandola negli occhi, il complimento più audace che puoi permetterti.',
    'Rivolgi la tua migliore frase di rimorchio alla persona scelta dal gruppo, che deve rispondere a tono.',
    'Recita una dichiarazione infuocata alla persona di fronte come se fosse l\'ultima notte sulla Terra.',
    'Proponi un finto appuntamento alla persona alla tua destra: dove la porteresti e come vorresti che finisse la serata.',
    'Guarda ogni persona del gruppo e dille solo "sì", "no" o "forse", senza mai spiegare la domanda.',
    'Tieni un cubetto di ghiaccio in bocca mentre dici la frase più seducente che conosci.',
    'Avvicina piano il viso a quello della persona di fronte (se ci sta) e fermati a un centimetro: il primo che ride perde il turno.',
    'Balla una canzone scelta dal gruppo come se fossi nel video musicale, versione vietata ai minori ma ballabile.',
    'Attraversa la stanza come su una passerella, fermati davanti alla persona più attraente e dille "ci vediamo dopo".',
    'Fatti dare un voto da 1 a 10 sul tuo sguardo seducente da ogni persona del gruppo.',
    'Lascia un segno di rossetto (o disegna un cuoricino con una penna) sulla guancia di una persona consenziente.',
    'Gioco dello specchio: la persona di fronte fa mosse di seduzione e tu le ripeti identiche, per venti secondi.',
    'Siediti sulle ginocchia di una persona consenziente per tutto il prossimo round.',
    'Fatti massaggiare la testa da una persona scelta dal gruppo e commenta ad alta voce come se fossi al ristorante.',
    'Appoggia la fronte a quella della persona di fronte e sostenete lo sguardo per dieci secondi: chi ride paga pegno doppio.',
    'Scambia un indumento o un accessorio con la persona alla tua sinistra fino a fine partita.',
    'Fai tre flessioni dicendo a ogni flessione il nome di una persona con cui usciresti.',
    'Di\' l\'alfabeto con la tua voce più sensuale finché qualcuno ti implora di smettere (succederà presto).',
    'Mangia o bevi qualcosa che c\'è sul tavolo nel modo più provocante possibile.',
    'Bevi un sorso guardando negli occhi la persona più attraente della stanza, senza staccare lo sguardo.',
    'Componi sul momento due frasi di una canzone dedicata alla tua ultima notte memorabile.',
    'Racconta la scusa più creativa che hai usato per restare a dormire da qualcuno.',
    'Racconta la scusa più creativa che hai usato per NON restare a dormire da qualcuno.',
    'Confessa il rituale segreto che hai prima di un appuntamento che promette bene.',
    'Mima la tua routine di preparazione a una notte importante, senza saltare passaggi.',
    'Di\' quale superpotere sceglieresti per la tua vita amorosa e come lo useresti già stasera.',
    'Racconta la cosa più audace che hai fatto in vacanza e che a casa non rifaresti mai.',
    'Di\' la cosa più sfacciata che ti hanno detto in discoteca o per strada, e cosa hai risposto.',
    'Rileggi ad alta voce, con voce da film, il messaggio più sdolcinato che hai mai inviato.',
    'Racconta il tuo one night stand più memorabile: il gruppo può fare tre domande, tu puoi passarne una sola.',
    'Descrivi la tua serata perfetta che finisce a colazione, senza saltare la notte in mezzo.',
    'Di\' tre posti dove ti piacerebbe farlo almeno una volta nella vita: il gruppo commenta ogni voce.',
    'Confessa se stasera c\'è qualcuno, qui o fuori, a cui stai pensando in un modo non esattamente innocente.',
    'Recita un finto annuncio: "Cercasi complice per notti insonni", descrivendo i requisiti veri.',
    'Fai un brindisi ad alta voce "alla mia prossima notte indimenticabile" e reggi gli sguardi del gruppo.',
    'Chiama la tua vecchia fiamma preferita e dille "ripensavo a noi", reggendo dieci secondi di silenzio.',
    'Manda "Ripensavo a quella notte…" a una persona con cui sei davvero stato e mostra la risposta.',
    'Scrivi alla tua crush "Ho una cosa da dirti, ma solo di persona." e mostra la risposta quando arriva.',
    'Lascia che il gruppo scriva un messaggio audace (niente offese) e mandalo a un contatto scelto da te.',
    'Di\' senza filtri qual è la prima cosa che guardi in una persona che ti attrae, e ammetti da quanto lo fai.',
    'Descrivi il bacio perfetto del primo appuntamento e dimostralo sul dorso della tua mano, con impegno totale.',
    'Fai la faccia esatta che fai quando capisci che la serata sta per finire molto bene.',
    'Togli due capi o accessori a scelta, il più lentamente possibile, sulla colonna sonora scelta dal gruppo.',
    'Dai una sculacciata scherzosa, con il suo consenso, alla persona scelta dal gruppo.',
    'Riproduci per cinque secondi i suoni che fai a letto, versione senza vergogna.',
    'Mostra la faccia che fai nel momento migliore di tutti: tre secondi, faccia seria, il gruppo vota.',
    'Racconta il tuo ultimo sogno erotico, o inventane uno così credibile che nessuno capisca la differenza.',
    'Bacia lentamente il collo di una persona consenziente scelta da te.',
    'Mima da vestito, per cinque secondi e con la massima serietà, la tua posizione preferita.',
    'Di\' ad alta voce, guardando il soffitto, il nome della persona con cui rifaresti la tua notte migliore.',
    'Fai un massaggio di trenta secondi alla schiena di una persona consenziente: si ferma solo quando lo dice lei.',
    'Sussurra all\'orecchio della persona scelta dal gruppo perché la mattina dopo servirebbe una colazione abbondante.',
    'Fai tre giri di sguardi intensi con la persona di fronte senza mai ridere.',
    'Descrivi la persona più attraente che hai visto questa settimana, nei dettagli.',
    'Manda "Mi fai perdere la testa." a un contatto scelto da te e mostra la risposta.',
    'Fai un complimento sul fisico, elegante ma sincero, a ogni persona consenziente del gruppo.',
    'Balla mezzo minuto di reggaeton come se nessuno ti guardasse. Ti guardiamo tutti.',
    'Fatti mettere un cubetto di ghiaccio sul collo senza cambiare espressione.',
    'Attraversa la stanza come se fossi appena uscito dalla doccia con l\'asciugamano.',
    'Recita la scena "ci siamo appena notati da lontano in un locale" con la persona scelta dal gruppo.',
    'Sussurra il tuo drink preferito all\'orecchio di qualcuno come se fosse un segreto di stato.',
    'Descrivi come ti vestiresti per una notte che deve andare assolutamente bene.',
    'Spiega la differenza tra un bacio di saluto e un bacio vero, con esempi teorici dettagliati.',
    'Interpreta "il risveglio accanto a qualcuno": prima versione film romantico, poi versione realtà.',
    'Racconta il momento esatto in cui hai capito di piacere a qualcuno.',
    'Fai la tua camminata più sicura attraverso la stanza e concludi con uno sguardo.',
    'Fatti dare un tema dal gruppo e improvvisa venti secondi di discorso seducente.',
    'Leggi un menu immaginario con voce da spot di profumo.',
    'Mima "sto scrivendo alla mia crush" con tutte le fasi del panico.',
    'Di\' tre modi infallibili per farti notare da qualcuno senza parlare.',
    'Mostra la tua posa migliore da foto profilo e spiegane la strategia.',
    'Concedi alla persona alla tua destra tre domande sulla tua vita sentimentale: devi risponderne almeno due.',
    'Racconta il complimento più bello che hai mai fatto e a chi.',
    'Ripeti "che serata interessante" con cinque intenzioni diverse: il gruppo deve indovinarle.',
    'Fai il gesto più romantico possibile usando solo un oggetto della stanza.',
    'Organizza sul momento un appuntamento perfetto per due persone del gruppo.',
    'Insegna al gruppo come si esce con dignità da un flirt fallito.',
    'Rivela quale canzone ti fa venire in mente una persona precisa, e balla otto secondi.',
    'Di\' quale profumo ti fa girare la testa e a chi dei presenti lo assoceresti.',
    'Balla un lento di dieci secondi con un cuscino, con trasporto autentico.',
    'Descrivi al gruppo la tua idea di colazione del giorno dopo perfetta.',
    'Rifai la faccia di quando ricevi un messaggio dalla persona giusta al momento giusto.',
    'Componi un messaggio di buongiorno che scioglierebbe chiunque e leggilo ad alta voce.',
    'Scegli chi del gruppo interpreterebbe la tua crush in un film e dirigilo in una scena di due battute.',
    'Chiudi gli occhi e descrivi il tuo appuntamento ideale mentre il gruppo aggiunge imprevisti.',
  ];

  static const List<String> verita = <String>[
    'Qual è stata la tua prima volta: età, luogo e voto da 1 a 10.',
    'Con quante persone hai passato la notte? Puoi rispondere con un intervallo, ma un intervallo onesto.',
    'Qual è il posto più assurdo in cui l\'hai fatto?',
    'Qual è il posto in cui vorresti farlo almeno una volta nella vita?',
    'Sei mai andato a letto con qualcuno il giorno stesso in cui l\'hai conosciuto?',
    'Qual è stato il tuo one night stand più memorabile?',
    'E quello che vorresti cancellare dalla memoria?',
    'Hai mai passato la notte con un amico e fatto finta di niente il giorno dopo?',
    'Hai mai fatto sexting? Con quante persone diverse?',
    'Qual è il messaggio più audace che hai mai scritto? Puoi parafrasare, ma poco.',
    'Hai mai mandato una tua foto audace? Ti fidi ancora di chi l\'ha ricevuta?',
    'Hai mai ricevuto una foto audace non richiesta? Cosa hai risposto?',
    'Qual è la tua fantasia più confessabile?',
    'E quella che confesseresti solo dopo mezzanotte?',
    'Una cosa a tre: ci hai mai pensato seriamente? Sì o no.',
    'C\'è una persona con cui rifaresti volentieri tutto da capo, anche solo per una notte?',
    'Meglio una notte indimenticabile senza seguito o dieci appuntamenti perfetti senza notte?',
    'Qual è la cosa che ti fa perdere la testa in un bacio?',
    'Chi è stato il tuo miglior bacio? E il peggiore?',
    'Hai mai baciato due persone nella stessa serata?',
    'Hai mai baciato qualcuno per scommessa? Ne è valsa la pena?',
    'Hai mai baciato qualcuno e te ne sei pentito mentre lo stavi ancora facendo?',
    'Ti sei mai svegliato accanto a qualcuno chiedendoti come fosse successo?',
    'Sei mai scappato da casa di qualcuno prima che si svegliasse?',
    'Sei mai stato tu quello da cui sono scappati? Quando l\'hai capito?',
    'Qual è il tuo record di tempo tra il primo sguardo e il primo bacio?',
    'Cosa conta di più a letto secondo te: intesa, fantasia o allenamento?',
    'A letto sei più tradizionalista o sperimentatore? Una parola sola.',
    'Luci accese o spente? Difendi la risposta.',
    'Sei più da mattina, da pomeriggio o da notte fonda? Sii specifico.',
    'Musica sì o musica no? E quale?',
    'Qual è il complimento più bello che ti hanno fatto a letto? Puoi parafrasare.',
    'Hai mai finto di divertirti per gentilezza? Quante volte, a occhio?',
    'Hai mai riso nel momento meno opportuno? Racconta.',
    'Qual è la cosa più imbarazzante che ti è successa in un momento intimo?',
    'Sei mai stato interrotto sul più bello? Da cosa o da chi?',
    'Ti sei mai rivestito di corsa perché stava arrivando qualcuno?',
    'Hai mai fatto finta di dormire per evitare un momento di intimità?',
    'Hai mai esagerato i dettagli di una notte raccontandola agli amici?',
    'Hai mai avuto una storia solo fisica? Quanto è durata?',
    'La tua storia solo fisica è finita perché è finita l\'attrazione o perché uno dei due si è innamorato?',
    'Hai mai avuto un "amico speciale" di cui il gruppo non ha mai saputo niente?',
    'C\'è qualcuno che ti attrae e che gli altri troverebbero improbabile?',
    'Cosa noti per prima cosa in una persona che ti attrae? Sii onesto, non diplomatico.',
    'Qual è il gesto innocente che trovi irresistibile in una persona?',
    'Qual è il capo di abbigliamento o il dettaglio che ti fa girare la testa?',
    'Ti consideri bravo a letto? Voto da 1 a 10, senza falsa modestia.',
    'Cosa miglioreresti di te come amante?',
    'Qual è la tua arma di seduzione principale? Il gruppo può chiederti di dimostrarla.',
    'Qual è la frase di rimorchio che su di te funzionerebbe davvero?',
    'Hai mai usato una frase di rimorchio trovata su internet? Com\'è andata?',
    'Hai mai flirtato per ottenere un favore? Ha funzionato?',
    'Hai mai flirtato con due persone nella stessa serata? Si sono accorte l\'una dell\'altra?',
    'Hai mai dato un numero falso? A chi e perché?',
    'Hai mai chiesto un numero e poi non scritto mai? Perché?',
    'Qual è la cosa più audace che hai fatto per attirare l\'attenzione di qualcuno?',
    'Qual è la cosa più audace che hai fatto in un locale pubblico?',
    'Qual è la cosa più audace che hai fatto su un mezzo di trasporto?',
    'Hai mai avuto un flirt in vacanza? Fin dove è arrivato?',
    'Hai mai frequentato qualcuno con una differenza d\'età che ha fatto discutere? Quanti anni?',
    'Hai mai avuto una cotta per il partner di un amico? Hai mai fatto qualcosa a riguardo?',
    'Hai mai baciato qualcuno di questa stanza? Il silenzio vale come un sì.',
    'Hai mai pensato a una persona presente in un modo non esattamente innocente? Sì o no.',
    'Chi è la persona più attraente di questa stanza? Il partner, se presente, non vale.',
    'Se dovessi fingere un fidanzamento di un mese con qualcuno del gruppo, chi reggerebbe meglio la parte?',
    'Chi del gruppo ha secondo te la vita amorosa più movimentata di quello che racconta?',
    'Chi del gruppo avrebbe più successo su un\'app di incontri per avventure di una notte?',
    'Hai mai usato un\'app di incontri? Racconta il match migliore e il peggiore.',
    'Qual è la bugia più grossa che hai letto (o scritto) su un profilo?',
    'Hai mai riconosciuto qualcuno che conosci su un\'app di incontri? Cosa hai fatto?',
    'Hai mai chattato fino all\'alba con qualcuno di nascosto da tutti?',
    'Qual è la notifica che ti ha fatto battere il cuore più forte ultimamente?',
    'Hai mai riletto una conversazione intera per decifrare cosa intendeva davvero una persona?',
    'Hai mai scritto, cancellato e riscritto un messaggio per più di dieci minuti? A chi?',
    'Qual è il messaggio che rimpiangi di più: uno che hai mandato o uno che non hai mai mandato?',
    'Hai mai mandato un messaggio audace alla persona sbagliata? Cosa diceva?',
    'Hai mai scritto a un ex dopo mezzanotte? Com\'è finita?',
    'Sei mai tornato da un ex solo per una notte? Rifaresti?',
    'Provi ancora attrazione per un tuo ex? Quale, se hai il coraggio?',
    'Qual è la cosa che ti manca di più della tua ultima storia, tra quelle che non si dicono a cena?',
    'Perché è finita davvero la tua ultima storia?',
    'Hai mai avuto una storia segreta? Chi lo sapeva?',
    'Sei mai stato il segreto di qualcuno? Quando l\'hai scoperto?',
    'Hai mai avuto una storia con un collega o un compagno di corso? Chi lo sapeva?',
    'Qual è stato il tuo colpo di fulmine più forte? Che fine ha fatto?',
    'Il tuo "tipo ideale" corrisponde davvero alle persone che frequenti?',
    'Cosa sceglieresti tra un anno senza baci e un anno senza telefono?',
    'Qual è la cosa più folle che hai fatto per una notte con qualcuno?',
    'Qual è la scusa più assurda che hai inventato per rivedere qualcuno?',
    'Ti sei mai vestito apposta per farti notare da una persona precisa? Ha funzionato?',
    'Hai mai fatto una deviazione lunghissima solo per passare "per caso" da qualcuno?',
    'Qual è il tuo peggior due di picche? Come hai reagito?',
    'Il tuo miglior due di picche dato: sei stato elegante o brutale?',
    'Hai mai detto "ti amo" senza pensarlo? In quale momento?',
    'Te l\'hanno mai detto in un momento decisamente sbagliato? Quale?',
    'Qual è la cosa che non rifaresti mai più a un primo appuntamento?',
    'Com\'è il tuo primo appuntamento perfetto: come inizia e, soprattutto, come finisce?',
    'Al primo appuntamento chi deve fare la prima mossa? Tu l\'hai mai fatta?',
    'Qual è il momento esatto in cui capisci che la serata finirà bene?',
    'Qual è il segnale che ti fa capire che è meglio chiamare un taxi e andare a casa da solo?',
    'Hai mai passato una notte intera solo a parlare quando era chiaro che poteva succedere altro? Rimpianti?',
    'Qual è la cosa che vorresti avere più coraggio di chiedere a un partner?',
    'Qual è la cosa più romantica e la più audace che hai fatto nella stessa serata?',
    'Racconta la volta in cui un flirt è andato molto meglio del previsto, fino a dove te la senti.',
    'Qual è il sogno a occhi aperti che fai più spesso su una persona reale? Niente nomi, tutti i dettagli confessabili.',
    'Se la tua vita amorosa fosse un film, che titolo avrebbe e che divieto d\'età?',
    'Cosa sei felice che tua madre non sappia della tua vita privata?',
    'Qual è la domanda di questo gioco a cui speravi di non dover mai rispondere? Ora rispondi.',
    'Hai mai finto un orgasmo? Quante volte, a occhio?',
    'Qual è la tua posizione preferita? La risposta vera, non un voto di banalità.',
    'Sopra o sotto? Motiva la risposta.',
    'Sei rumoroso o silenzioso? C\'è qualcuno che potrebbe confermarlo?',
    'Dove ti piace essere baciato, oltre alla bocca?',
    'Qual è la tua zona più sensibile? Nominala o indicala, scegli tu.',
    'Cosa indossi per dormire quando non dormi da solo?',
    'Hai mai dormito nudo a casa di qualcun altro la prima notte?',
    'Preliminari lunghi o dritti al punto? Sii onesto, non elegante.',
    'Quanto è durata la tua maratona più lunga? Arrotonda pure, ma non per eccesso.',
    'Ti sei mai eccitato nel momento più sbagliato possibile? Dove eri?',
    'Hai mai comprato biancheria pensando a una persona precisa? L\'ha mai vista?',
    'Hai mai avuto un sogno erotico su un amico? Riesci ancora a guardarlo allo stesso modo?',
    'Luci, specchi o buio totale: cosa ti mette più a tuo agio?',
    'Qual è il complimento che vorresti sentirti dire a letto e che nessuno ti ha mai fatto?',
    'Cosa rende un bacio indimenticabile per te: tecnica, momento o persona? Porta un esempio vero.',
    'Qual è il bacio che ricordi più spesso?',
    'Chi ti ha insegnato, di fatto, a baciare?',
    'Qual è la cosa più audace che hai fatto mentre altri erano nella stanza, ignari?',
    'Preferisci conquistare o essere conquistato? Esempi concreti.',
    'Qual è il momento della giornata in cui ti senti irresistibile?',
    'Qual è la parte del tuo corpo che ti piace di più?',
    'E quella che riceve più complimenti?',
    'Ti sei mai guardato allo specchio dopo una bella notte e fatto l\'occhiolino?',
    'Qual è la cosa più bella che ti hanno sussurrato all\'orecchio?',
    'Hai mai ballato un lento pensando "eccoci"?',
    'Qual è stato il tuo flirt estivo più memorabile?',
    'Dove flirti di più: palestra, lavoro o mezzi pubblici?',
    'Per flirtare: vocali o messaggi scritti? Perché?',
    'Qual è la tua ora preferita per un primo bacio?',
    'Cosa ti fa capire che un abbraccio non è solo un abbraccio?',
    'Qual è il gesto che ti fa capire che qualcuno ci sta provando con te?',
    'Come capisci che stai per essere baciato? Racconta l\'ultima volta.',
    'Qual è il tuo record di messaggi in un giorno con una sola persona?',
    'Chi è stata la tua cotta più lunga mai confessata?',
    'Qual è la cosa che fai solo quando sei preso davvero?',
    'Ti piace di più la conquista o la conferma?',
    'Qual è la frase che ti ha fatto capitolare?',
    'Sei mai uscito con due persone nello stesso weekend?',
    'Qual è l\'appuntamento che rifaresti identico domani sera?',
    'Chi del gruppo bacerebbe meglio secondo te, a istinto?',
    'Qual è la parte migliore: prima, durante o dopo il bacio?',
  ];
}
