/// Obbligo o Verità — tono piccante: qualche domanda imbarazzante, niente di
/// esplicito. 100 obblighi + 100 verità.
class ObbligoOVeritaPiccante {
  const ObbligoOVeritaPiccante._();

  static const List<String> obblighi = <String>[
    'Leggi ad alta voce l\'ultimo messaggio che hai mandato.',
    'Leggi l\'ultimo messaggio ricevuto senza dire da chi.',
    'Mostra l\'ultima persona a cui hai scritto.',
    'Fai vedere il tuo ultimo messaggio inviato a un ex, se esiste.',
    'Manda un messaggio a caso a un contatto: "Devo dirti una cosa…" e non spiegare per cinque minuti.',
    'Chiama il terzo contatto della rubrica e chiedi come sta.',
    'Fai vedere le ultime tre foto della galleria.',
    'Fai vedere quali sono i tuoi ultimi tre profili visitati sui social.',
    'Metti mi piace all\'ultima foto della persona alla tua destra.',
    'Fai una storia con la faccia peggiore che riesci a fare.',
    'Scrivi in chat di gruppo una frase scelta dagli altri.',
    'Cambia il tuo nome nella chat di gruppo per un\'ora, lo scelgono gli altri.',
    'Metti come stato una frase decisa dal gruppo per dieci minuti.',
    'Fai leggere a qualcuno la tua playlist più imbarazzante.',
    'Canta la canzone d\'amore che ti imbarazza di più.',
    'Dedica una canzone a qualcuno del gruppo, cantandola.',
    'Fai una dichiarazione d\'amore finta a una persona a caso della stanza.',
    'Guarda negli occhi la persona di fronte per trenta secondi senza ridere.',
    'Fai un complimento imbarazzante a chi ti sta a sinistra.',
    'Di\' a ogni persona presente cosa cambieresti di lei, con gentilezza.',
    'Racconta la tua peggior figuraccia con qualcuno che ti piaceva.',
    'Racconta il tuo peggior primo appuntamento.',
    'Imita come flirti quando ci provi.',
    'Mostra come balleresti per conquistare qualcuno.',
    'Fai la tua migliore battuta di rimorchio a chi ti sta di fronte.',
    'Fai finta di chiedere il numero alla persona alla tua destra.',
    'Scegli chi del gruppo porteresti a un appuntamento e spiega perché.',
    'Ordina le persone della stanza per chi ti somiglia di più.',
    'Di\' chi del gruppo ti fa più paura quando si arrabbia.',
    'Racconta un segreto che non hai mai detto a nessuno qui dentro.',
    'Confessa una cosa che hai fatto e che nessuno di noi sa.',
    'Racconta la peggiore bugia che hai detto a un partner.',
    'Racconta la cosa più gelosa che hai fatto.',
    'Racconta la tua reazione peggiore a un due di picche.',
    'Imita il tuo ex mentre litiga (senza fare nomi).',
    'Imita come ti comporti quando sei geloso.',
    'Fai vedere la foto più imbarazzante che hai nel telefono.',
    'Fai vedere il tuo selfie più vecchio.',
    'Racconta cosa hai fatto l\'ultima volta che hai bevuto troppo.',
    'Fai il verso di come ridi quando qualcuno ti piace.',
    'Manda un vocale imbarazzante al gruppo, scelto da noi.',
    'Fatti scrivere un messaggio da un\'altra persona e mandalo davvero (niente offese).',
    'Lascia il telefono a chi ti sta a destra per un minuto: può guardare solo la galleria.',
    'Racconta la cosa più assurda che hai fatto per farti notare.',
    'Mostra il tuo miglior sguardo ammiccante.',
    'Balla in modo sensuale per dieci secondi senza ridere.',
    'Fai un massaggio alle spalle di dieci secondi a chi ti sta a sinistra.',
    'Siediti sulle ginocchia di qualcuno per un round intero.',
    'Tieni la mano di chi ti sta a destra fino al prossimo giro.',
    'Fai un abbraccio di venti secondi a chi sceglie il gruppo.',
    'Sussurra qualcosa all\'orecchio della persona di fronte: nessun altro deve sentire.',
    'Racconta a tutti quello che hai appena sussurrato.',
    'Scegli due persone del gruppo che secondo te starebbero bene insieme.',
    'Di\' a chi del gruppo affideresti il tuo telefono sbloccato.',
    'Di\' chi del gruppo NON lascerai mai avvicinare al tuo telefono.',
    'Fai una classifica dei presenti per ordine di simpatia (e difendila).',
    'Racconta la cosa che ti ha imbarazzato di più in questa serata.',
    'Fai finta di essere ubriaco per un minuto.',
    'Racconta cosa faresti se ti innamorassi di un amico.',
    'Imita la persona alla tua destra finché non indovina che è lei.',
    'Fai la parodia di uno del gruppo, gli altri devono indovinare chi è.',
    'Racconta il pettegolezzo più innocuo che conosci.',
    'Di\' qual è la cosa più cattiva che hai pensato stasera.',
    'Confessa una cosa per cui dovresti scusarti con qualcuno qui.',
    'Chiedi scusa davvero a quella persona.',
    'Fai una promessa al gruppo e mantienila per tutta la serata.',
    'Rivela quanto tempo hai passato oggi sui social.',
    'Fai vedere lo screen time del telefono.',
    'Fai vedere i tuoi acquisti online dell\'ultimo mese.',
    'Racconta la cosa più stupida che hai comprato di notte.',
    'Manda un messaggio ai tuoi dicendo che hai una notizia da dare.',
    'Fatti fare tre domande a raffica e rispondi senza pensarci.',
    'Rispondi con sincerità totale alle prossime due domande di chiunque.',
    'Racconta cosa pensavi davvero la prima volta che hai visto chi ti sta di fronte.',
    'Di\' una cosa che invidi a una persona presente.',
    'Di\' la cosa che ti rende più insicuro, se te la senti.',
    'Confessa se hai mai finto di essere d\'accordo per quieto vivere.',
    'Racconta l\'ultima volta che hai mentito a un amico.',
    'Racconta l\'ultima volta che hai mentito a te stesso.',
    'Fai il tuo miglior sguardo da "ti ho scoperto" a ogni persona.',
    'Scegli chi del gruppo secondo te ha più segreti.',
    'Fai una domanda scomoda alla persona che vuoi.',
    'Rispondi tu alla stessa domanda che hai appena fatto.',
    'Rivela il nome che daresti a tuo figlio.',
    'Racconta com\'è finita la tua storia più importante.',
    'Racconta cosa hai imparato dalla relazione peggiore che hai avuto.',
    'Di\' una cosa che non perdoneresti mai.',
    'Di\' una cosa che perdoneresti sempre.',
    'Racconta il tuo appuntamento più romantico.',
    'Descrivi il tuo tipo ideale mentre tutti indovinano chi è.',
    'Fai un discorso serio di trenta secondi su quanto ti piace il tuo cibo preferito.',
    'Prometti di rispondere "sì" alla prossima domanda, qualunque sia (niente di pericoloso).',
    'Balla il lento con una persona scelta dal gruppo.',
    'Fai vedere come baci l\'aria.',
    'Racconta la cosa più sfacciata che ti ha detto uno sconosciuto.',
    'Racconta la cosa più sfacciata che hai detto tu.',
    'Manda un messaggio al tuo ex compagno di scuola preferito.',
    'Scrivi a una persona che non senti da un anno.',
    'Racconta cosa cercheresti su di te se fossi un\'altra persona.',
    'Fai un brindisi imbarazzante in onore di chi ti sta a destra.',
  ];

  static const List<String> verita = <String>[
    'Ti è mai piaciuto qualcuno di questo gruppo?',
    'Chi è stata la tua cotta più imbarazzante?',
    'Qual è stato il tuo primo bacio e con chi?',
    'Quanti anni avevi al primo bacio?',
    'Qual è la cosa più romantica che hai fatto?',
    'E la più romantica che hanno fatto per te?',
    'Hai mai baciato due persone nella stessa serata?',
    'Hai mai finto di essere single?',
    'Hai mai mentito a un partner? Su cosa?',
    'Hai mai controllato il telefono di un partner?',
    'Cosa cercavi?',
    'Hai mai letto i messaggi di un amico di nascosto?',
    'Hai mai scritto a un ex di notte?',
    'Hai mai risposto a un ex sapendo che avresti fatto danni?',
    'Sei mai tornato con un ex?',
    'Rifaresti la stessa scelta?',
    'Qual è il messaggio che rimpiangi di più?',
    'Hai mai ghostato qualcuno?',
    'Ti hanno mai ghostato? Come hai reagito?',
    'Qual è la scusa peggiore che hai usato per non uscire?',
    'Hai mai dato buca a un appuntamento?',
    'Qual è la cosa peggiore che hai detto per chiudere una storia?',
    'Hai mai chiuso una storia con un messaggio?',
    'Qual è il tuo record di durata di una relazione?',
    'E quello più breve?',
    'Hai mai avuto una storia segreta?',
    'Chi lo sapeva?',
    'Hai mai fatto finta di dormire per evitare una conversazione?',
    'Hai mai fatto finta di divertirti a una festa?',
    'Qual è stata la peggior serata della tua vita?',
    'Qual è la cosa più imbarazzante che hai fatto da ubriaco?',
    'Qualcuno ha video di quella sera?',
    'Hai mai perso pezzi di una serata?',
    'Qual è la cosa che non ricordi ma ti hanno raccontato?',
    'Hai mai baciato qualcuno per scommessa?',
    'Hai mai usato un\'app di incontri?',
    'Com\'è andato l\'incontro peggiore?',
    'Qual è la bugia più grossa detta su un profilo?',
    'Quanto è vecchia la tua foto profilo?',
    'Hai mai spiato il profilo del nuovo partner del tuo ex?',
    'Fino a che anno sei arrivato scrollando?',
    'Hai mai messo like per sbaglio a una foto vecchissima?',
    'Cosa hai fatto dopo?',
    'Hai mai creato un profilo falso?',
    'Hai mai finto una cotta per far ingelosire qualcuno?',
    'Hai mai flirtato per ottenere un favore?',
    'Ha funzionato?',
    'Chi del gruppo ti sembra il più bugiardo?',
    'Chi del gruppo ti sembra il più sincero?',
    'Chi del gruppo chiameresti per un segreto?',
    'Chi del gruppo NON chiameresti mai per un segreto?',
    'Qual è il segreto più grosso che hai tenuto per un amico?',
    'Hai mai rivelato un segreto che non dovevi?',
    'Hai mai origliato una conversazione su di te?',
    'Cosa hai sentito?',
    'Hai mai fatto finta di non sapere una cosa che sapevi benissimo?',
    'Hai mai riso di qualcuno alle spalle?',
    'Ti sei mai pentito di una cosa detta in un gruppo?',
    'Qual è la cosa più cattiva che hai pensato di qualcuno qui?',
    'Qual è la cosa più bella che hai pensato di qualcuno qui?',
    'Chi del gruppo secondo te ha più fortuna in amore?',
    'Chi del gruppo si sposerà per primo?',
    'Chi non si sposerà mai?',
    'Chi ti chiamerebbe alle quattro di notte per un dramma?',
    'Con chi del gruppo non convivresti mai?',
    'Con chi del gruppo faresti un viaggio di un mese?',
    'A chi del gruppo presteresti mille euro?',
    'A chi non li presteresti?',
    'Qual è la cosa più imbarazzante che hai nel telefono?',
    'Quanto ti costerebbe farci vedere la tua galleria?',
    'Qual è la ricerca più imbarazzante nella tua cronologia?',
    'Qual è la playlist che non faresti mai vedere?',
    'Qual è il video che riguardi di nascosto?',
    'Qual è la cosa che fai solo quando sei solo in casa?',
    'Canti davvero sotto la doccia?',
    'Hai mai parlato da solo credendo che nessuno sentisse?',
    'Qualcuno ti ha sentito?',
    'Hai mai finto di ridere per non offendere?',
    'Hai mai finto di apprezzare un regalo orribile?',
    'Dove è finito quel regalo?',
    'Qual è la cosa che rimpiangi di non aver detto?',
    'A chi la diresti adesso?',
    'C\'è qualcuno che non hai mai smesso di pensare?',
    'Hai mai amato qualcuno che non lo sapeva?',
    'Glielo diresti oggi?',
    'Qual è la cosa più folle che faresti per amore?',
    'Cosa non faresti mai per amore?',
    'Hai mai scelto una persona sbagliata sapendolo?',
    'Perché?',
    'Qual è la cosa che ti fa scappare da una relazione?',
    'Qual è il difetto che non sopporti in un partner?',
    'Qual è il tuo difetto peggiore in una relazione?',
    'Sei più geloso o più possessivo?',
    'Hai mai fatto una scenata di gelosia?',
    'Com\'è finita?',
    'Qual è il consiglio d\'amore peggiore che hai ricevuto?',
    'Lo hai seguito?',
    'Cosa vorresti che ti chiedessero stasera?',
    'C\'è una domanda a cui hai risposto con una bugia stasera?',
    'Vuoi correggerla adesso?',
  ];
}
