/// Obbligo o Verità — tono cattivo: domande scomode e obblighi imbarazzanti,
/// da giocare solo tra amici stretti. 100 obblighi + 100 verità.
///
/// "Cattivo" qui significa senza filtri sul piano sociale, non pericoloso:
/// niente di illegale, niente che spinga a bere, niente di sessualmente
/// esplicito e niente che umili qualcuno che non sta giocando.
class ObbligoOVeritaCattivo {
  const ObbligoOVeritaCattivo._();

  static const List<String> obblighi = <String>[
    'Di\' a ogni persona presente la prima cosa che hai pensato di lei quando l\'hai conosciuta.',
    'Fai una classifica onesta dei presenti dal più al meno affidabile.',
    'Di\' chi del gruppo secondo te mente più spesso, guardandolo in faccia.',
    'Di\' a chi ti sta di fronte una cosa che ti irrita di lui.',
    'Di\' a chi ti sta a destra la cosa che apprezzi meno del suo carattere.',
    'Racconta il pettegolezzo più grosso che sai su qualcuno presente.',
    'Rivela una cosa che ti hanno detto in confidenza (scegli tu quanto grave).',
    'Leggi ad alta voce l\'ultima conversazione con la persona che nomini tu.',
    'Fai vedere l\'ultima chat con il tuo migliore amico.',
    'Fai leggere al gruppo gli ultimi tre messaggi che hai ricevuto.',
    'Dai il telefono sbloccato a chi ti sta a sinistra per trenta secondi.',
    'Fatti aprire una chat a caso da un\'altra persona e leggila ad alta voce.',
    'Manda un messaggio scelto dal gruppo alla persona scelta dal gruppo.',
    'Chiama il tuo ex e digli una frase decisa dagli altri (niente di offensivo).',
    'Scrivi a una persona che ti piace o ti piaceva: "Ho pensato a te oggi".',
    'Manda un vocale al gruppo dicendo cosa pensi davvero di questa serata.',
    'Cambia la foto profilo con una scelta dagli altri per un\'ora.',
    'Metti come stato una frase scelta dal gruppo per un\'ora.',
    'Pubblica la tua foto peggiore e lasciala su per dieci minuti.',
    'Fai vedere lo screen time e leggi le tre app più usate.',
    'Fai vedere la cronologia degli ultimi acquisti.',
    'Fai vedere l\'ultima cosa che hai cercato su internet.',
    'Fai vedere le tue ultime tre ricerche di immagini.',
    'Leggi ad alta voce l\'ultima nota nel telefono, qualunque sia.',
    'Fai vedere quante persone hai bloccato.',
    'Di\' il nome dell\'ultima persona che hai stalkerato sui social.',
    'Racconta la cosa peggiore che hai fatto a un amico.',
    'Racconta la cosa peggiore che hai fatto a un partner.',
    'Confessa una cosa per cui non ti sei mai scusato.',
    'Scusati adesso, davanti a tutti, con chi devi.',
    'Racconta il tuo tradimento peggiore, di qualsiasi tipo.',
    'Racconta la bugia più grossa che hai detto in questo gruppo.',
    'Racconta una cosa che hai detto di qualcuno presente alle sue spalle.',
    'Di\' chi del gruppo ti ha deluso di più.',
    'Di\' chi del gruppo ti ha sorpreso in positivo.',
    'Fai una critica sincera a ognuno, una alla volta.',
    'Accetta le critiche di tutti senza rispondere.',
    'Fatti dire da ognuno un tuo difetto e ringrazia.',
    'Fai finta di litigare con chi ti sta a destra per un minuto, senza ridere.',
    'Imita il difetto peggiore di una persona presente finché non indovina.',
    'Fai la parodia di come parla chi ti sta di fronte.',
    'Imita come si comporta il gruppo quando beve troppo.',
    'Racconta cosa pensi davvero del lavoro di chi ti sta a sinistra.',
    'Di\' quanto guadagni, oppure salta il turno perdendo il prossimo.',
    'Di\' quanti soldi hai sul conto, arrotondati alle centinaia.',
    'Racconta la spesa più stupida della tua vita e quanto ti è costata.',
    'Confessa un debito che non hai ancora ripagato.',
    'Di\' a chi devi ancora dei soldi in questa stanza.',
    'Confessa se hai mai preso qualcosa che non era tuo.',
    'Racconta la cosa più disonesta che hai fatto al lavoro.',
    'Racconta come hai fatto a farti perdonare l\'ultima volta.',
    'Racconta la figura peggiore della tua vita, per intero.',
    'Racconta la cosa che ti fa ancora arrossire dopo anni.',
    'Racconta un tuo fallimento senza usare scuse.',
    'Elenca tre cose che invidi a persone di questa stanza.',
    'Di\' chi del gruppo vorresti essere per un giorno e perché.',
    'Di\' chi del gruppo non vorresti essere mai.',
    'Fai una previsione cattiva ma realistica sul futuro di ognuno.',
    'Di\' quale amicizia di questo gruppo secondo te non durerà.',
    'Di\' chi si è comportato peggio in questa serata.',
    'Fai il verso a come reagisci quando ti offendi.',
    'Racconta l\'ultima volta che hai pianto e perché.',
    'Racconta di cosa ti vergogni di più.',
    'Di\' la cosa che non hai mai detto a tuo padre o tua madre.',
    'Di\' cosa non hai mai avuto il coraggio di dire al tuo capo.',
    'Registra un vocale con quella frase (non mandarlo).',
    'Ora decidi se mandarlo davvero.',
    'Racconta la cosa che rimpiangi di più.',
    'Racconta cosa faresti diversamente se tornassi indietro di cinque anni.',
    'Di\' a chi devi delle scuse da anni.',
    'Scrivi a quella persona adesso.',
    'Racconta il tuo pensiero peggiore su questa serata.',
    'Fai vedere l\'ultima foto in cui esci male e non hai cancellato.',
    'Fatti truccare o pettinare dal gruppo e resta così per due round.',
    'Indossa una cosa scelta dal gruppo fino alla fine della partita.',
    'Lascia che il gruppo scriva una parola sul tuo braccio con una penna.',
    'Fatti fare una foto ridicola e usala come profilo per un\'ora.',
    'Balla per un minuto intero mentre tutti ti guardano in silenzio.',
    'Canta una canzone stonando apposta davanti a tutti.',
    'Fai un discorso di trenta secondi elogiando chi ti sta meno simpatico.',
    'Fai i complimenti alla persona con cui hai litigato di più.',
    'Racconta la cosa più bella di chi ti sta antipatico.',
    'Guarda negli occhi chi ti sta di fronte per un minuto in silenzio.',
    'Racconta cosa hai pensato durante quel minuto.',
    'Rispondi con sincerità assoluta alle prossime tre domande.',
    'Fatti fare tre domande dal gruppo e non puoi passare.',
    'Rispondi alla domanda che ti fa più paura fra quelle di stasera.',
    'Di\' una cosa che nessuno in questa stanza sa di te.',
    'Di\' se hai mai pensato di allontanarti da questo gruppo.',
    'Di\' cosa ti tiene qui.',
    'Racconta una volta in cui hai fatto piangere qualcuno.',
    'Racconta una volta in cui qualcuno ti ha fatto piangere.',
    'Di\' se hai mai finto un\'amicizia per convenienza.',
    'Di\' quale amicizia hai lasciato andare e perché.',
    'Confessa un\'invidia che provi ancora oggi.',
    'Confessa una cosa di cui ti senti in colpa.',
    'Di\' la cosa peggiore che hai pensato di te stesso.',
    'Di\' la cosa migliore che hai pensato di te stesso.',
    'Chiudi la partita dicendo una verità che nessuno si aspetta.',
    'Di\' a ognuno una cosa che non gli hai mai detto in faccia.',
  ];

  static const List<String> verita = <String>[
    'Chi di noi non inviteresti al tuo matrimonio?',
    'Chi di noi ti sta meno simpatico oggi?',
    'Chi di noi hai giudicato male all\'inizio?',
    'Chi di noi hai criticato alle spalle?',
    'Cosa avevi detto?',
    'Chi di noi secondo te parla male degli altri?',
    'Chi di noi non chiameresti mai per un favore?',
    'Chi di noi ti ha deluso di più?',
    'Chi di noi consideri davvero un amico e chi solo una conoscenza?',
    'Chi di noi sparirebbe dalla tua vita senza che te ne accorgessi?',
    'Chi di noi ti manca quando non c\'è?',
    'Hai mai finto un\'amicizia per interesse?',
    'Hai mai tradito la fiducia di qualcuno presente?',
    'Hai mai letto messaggi non tuoi?',
    'Cosa hai scoperto?',
    'Hai mai rivelato un segreto per farti bello?',
    'Hai mai mentito in questo gruppo su una cosa importante?',
    'Su cosa?',
    'Qual è la bugia che stai raccontando ancora oggi?',
    'Qual è la verità che stai evitando di dire a qualcuno?',
    'A chi devi delle scuse da più tempo?',
    'Perché non le hai ancora fatte?',
    'Hai mai fatto del male a qualcuno di proposito?',
    'Te ne sei pentito davvero?',
    'Qual è la cosa peggiore che hai fatto a un ex?',
    'Qual è la cosa peggiore che ti hanno fatto?',
    'Hai mai tradito qualcuno?',
    'Lo rifaresti?',
    'Hai mai perdonato un tradimento?',
    'Hai mai fatto finta di perdonare senza perdonare?',
    'Sei ancora arrabbiato con qualcuno di noi?',
    'Per cosa?',
    'C\'è una persona che non vorresti mai rivedere?',
    'Cosa ha fatto?',
    'Hai mai desiderato del male a qualcuno?',
    'Hai mai gioito della sfortuna di qualcuno?',
    'Di chi?',
    'Qual è la cosa più egoista che hai fatto?',
    'Qual è la cosa più vigliacca che hai fatto?',
    'Hai mai lasciato che qualcun altro pagasse per un tuo errore?',
    'Hai mai mentito a un colloquio?',
    'Hai mai preso qualcosa dal lavoro?',
    'Hai mai finto di lavorare per un\'intera giornata?',
    'Quanto tempo perdi davvero in una giornata di lavoro?',
    'Quanto guadagni?',
    'Ti sembra giusto?',
    'Chi di noi pensi guadagni più di te?',
    'Hai mai giudicato qualcuno per i soldi che ha?',
    'Hai mai chiesto soldi senza restituirli?',
    'A chi devi ancora dei soldi?',
    'Qual è la cosa più imbarazzante nella tua cronologia?',
    'Cosa cancelleresti dal telefono prima di darcelo?',
    'C\'è qualcosa nel tuo telefono che rovinerebbe un\'amicizia qui?',
    'Chi di noi non deve mai vedere la tua galleria?',
    'Hai mai fatto uno screenshot di una chat per farlo girare?',
    'A chi lo hai mandato?',
    'Hai mai parlato male di me con un\'altra persona di questo gruppo?',
    'Hai mai riso di una disgrazia di un amico?',
    'Hai mai finto di essere dispiaciuto?',
    'Qual è l\'emozione che fingi più spesso?',
    'Quando è stata l\'ultima volta che sei stato davvero sincero?',
    'Con chi non sei mai sincero?',
    'Qual è la parte di te che nascondi meglio?',
    'Cosa penseresti di te se fossi un\'altra persona?',
    'Qual è la critica che ti ha ferito di più?',
    'Aveva ragione?',
    'Qual è il tuo più grande fallimento?',
    'Di chi è la colpa, onestamente?',
    'Cosa invidi di più a chi ti sta di fronte?',
    'Cosa ti fa sentire inferiore?',
    'Con chi ti confronti sempre?',
    'Qual è la cosa che rimandi perché hai paura?',
    'Di cosa hai davvero paura?',
    'Qual è la cosa che non hai mai detto ai tuoi?',
    'Cosa penserebbero se lo sapessero?',
    'C\'è una scelta della tua vita che rifaresti diversamente?',
    'Quanto ti pesa oggi?',
    'Hai mai pensato di mollare tutto e sparire?',
    'Cosa te lo ha impedito?',
    'C\'è qualcuno che ami e non lo sa?',
    'Perché non gliel\'hai detto?',
    'C\'è qualcuno in questa stanza che hai amato?',
    'Lo ami ancora?',
    'Hai mai desiderato la persona di un amico?',
    'Hai mai fatto qualcosa a riguardo?',
    'Hai mai baciato qualcuno di questa stanza?',
    'Ci pensi ancora?',
    'Chi di noi bacieresti se non ci fossero conseguenze?',
    'Chi di noi eviteresti in ogni caso?',
    'Cosa non ci hai mai detto di quella storia?',
    'Qual è la versione dei fatti che ci hai raccontato meglio di com\'è andata?',
    'Cosa vorresti che nessuno ti chiedesse mai?',
    'Perché?',
    'Qual è la domanda a cui hai risposto con una bugia stasera?',
    'Vuoi rispondere di nuovo, questa volta davvero?',
    'Cosa ti porti a casa da questa serata?',
    'C\'è qualcuno a cui devi dire grazie qui dentro?',
    'Diglielo adesso.',
    'Cosa non dirai mai a nessuno di noi?',
    'Se stasera dovessi tagliare fuori una persona da questo gruppo, chi sarebbe?',
  ];
}
