/// Obbligo o Verità — tono cattivo: il mazzo più sfacciato e provocatorio.
/// Verità senza filtri su sesso, attrazioni e segreti, obblighi fisici e
/// imbarazzanti.
class ObbligoOVeritaCattivo {
  const ObbligoOVeritaCattivo._();

  static const List<String> obblighi = <String>[
    'Dai un bacio con la lingua alla persona alla tua destra, se consenziente.',
    'Fatti togliere un indumento con i denti da una persona consenziente.',
    'Mima la tua posizione preferita su una persona consenziente per trenta secondi.',
    'Descrivi ad alta voce come porteresti a letto la persona di fronte a te.',
    'Mostra la faccia che fai quando raggiungi l\'orgasmo.',
    'Lecca il collo della persona alla tua sinistra fino a farla rabbrividire, se consenziente.',
    'Fai un succhiotto ben visibile sulla spalla di una persona consenziente.',
    'Siediti a cavalcioni su una persona consenziente e resta lì per un intero round.',
    'Simula un orgasmo rumoroso e realistico per venti secondi davanti a tutti.',
    'Sussurra all\'orecchio della persona di fronte la cosa più sporca che le faresti.',
    'Fai una lap dance di un minuto a una persona consenziente scelta dal gruppo.',
    'Mordicchia il lobo dell\'orecchio della persona alla tua destra, se consenziente.',
    'Passa un cubetto di ghiaccio dalla tua bocca a quella di una persona consenziente.',
    'Mostra al gruppo come muovi i fianchi durante il sesso, in piedi.',
    'Lecca via una goccia di bevanda dal collo di una persona consenziente.',
    'Togliti un capo di abbigliamento e restaci per i prossimi tre round.',
    'Fai vedere in che posizione dormi nuda o nudo, mettendoti a terra.',
    'Bacia il punto del corpo che preferisci di una persona consenziente.',
    'Mima un rapporto orale su una banana o un altro oggetto per quindici secondi.',
    'Balla un lento corpo a corpo con una persona consenziente, mani libere.',
    'Descrivi con dovizia di dettagli l\'ultima volta che ti sei masturbato.',
    'Fai capire con i gesti quanto è dotato o dotata il tuo ex più memorabile.',
    'Metti la mano sulla coscia di una persona consenziente e lasciala lì un round.',
    'Imita i versi che fai a letto quando stai per venire.',
    'Lecca il dito di una persona consenziente in modo il più provocante possibile.',
    'Spogliati fino a restare in intimo e cambia posto con chi hai davanti.',
    'Fai vedere quanto sai essere sensuale togliendoti lentamente i calzini o le scarpe.',
    'Mordi delicatamente il collo di una persona consenziente lasciando il segno dei denti.',
    'Mostra il movimento di lingua che useresti in un bacio alla francese, su una mano.',
    'Sculaccia una persona consenziente e fatti sculacciare a tua volta.',
    'Descrivi la fantasia sessuale che ti fa eccitare di più, senza censure.',
    'Simula di cavalcare qualcuno stando seduto su una sedia per venti secondi.',
    'Fai un massaggio sensuale alla schiena di una persona consenziente per un minuto.',
    'Mostra come baci appassionatamente usando il dorso della tua mano.',
    'Metti a nudo la spalla e fatti baciare lì da una persona consenziente.',
    'Racconta a voce alta il sogno erotico più spinto che ricordi.',
    'Mima la posizione del missionario nell\'aria per dieci secondi, con espressione.',
    'Sussurra un gemito nell\'orecchio della persona alla tua destra, se consenziente.',
    'Fatti legare i polsi con una sciarpa da una persona consenziente per un round.',
    'Descrivi cosa ti eccita di più nel corpo della persona di fronte a te.',
    'Fai vedere come toglieresti il reggiseno con una mano sola, a occhi chiusi.',
    'Lecca la panna o lo zucchero da un dito di una persona consenziente.',
    'Mostra il tuo miglior primo piano di sguardo seducente, tenendolo dieci secondi.',
    'Simula un pompino a un cetriolo con la massima serietà per quindici secondi.',
    'Fatti soffiare sul collo da una persona consenziente e reagisci come faresti a letto.',
    'Descrivi la volta in cui hai avuto l\'orgasmo più intenso della tua vita.',
    'Balla la pole dance usando una sedia come palo per trenta secondi.',
    'Metti le labbra a un centimetro da quelle di chi hai davanti senza baciarlo, per dieci secondi.',
    'Fai un gemito crescente che finisce in un urlo, come un vero climax.',
    'Passa la lingua sul tuo labbro superiore fissando la persona che ti attrae di più qui.',
    'Togliti l\'intimo sotto i vestiti e mostralo al gruppo.',
    'Fatti mordere il collo da una persona consenziente per cinque secondi.',
    'Descrivi il tuo sex toy preferito e come lo usi.',
    'Mima di spogliare con lo sguardo ogni persona presente, uno alla volta.',
    'Fai una danza del ventre lenta e provocante per venti secondi.',
    'Lecca lentamente un dito e infilalo in bocca guardando chi hai di fronte.',
    'Sussurra a una persona consenziente in che posizione la vorresti.',
    'Metti la testa in grembo a una persona consenziente per un round intero.',
    'Mostra come muovi la lingua quando fai sesso orale, su un ghiacciolo o cucchiaio.',
    'Fatti massaggiare le cosce da una persona consenziente per trenta secondi.',
    'Descrivi il punto del tuo corpo che ti fa impazzire quando viene toccato.',
    'Simula un amplesso appassionato con un cuscino per venti secondi.',
    'Bacia la mano di una persona consenziente risalendo fino al gomito.',
    'Fai vedere quanto sai essere sfacciato mimando uno spogliarello di dieci secondi.',
    'Sussurra all\'orecchio del gruppo, uno per uno, quanto li trovi arrapanti.',
    'Fatti coprire gli occhi e indovina chi ti bacia la guancia tra i consenzienti.',
    'Descrivi come ti piace essere toccato durante i preliminari.',
    'Mima la posizione della pecorina nell\'aria per dieci secondi, con convinzione.',
    'Lecca il collo del bicchiere in modo osceno mentre tutti guardano.',
    'Fai un twerk sfrenato di trenta secondi davanti al gruppo.',
    'Metti la mano di una persona consenziente sul tuo fianco e guidala mentre balli.',
    'Racconta la cosa più audace che hai fatto a letto per fare colpo.',
    'Simula di allacciare le gambe intorno a qualcuno usando l\'aria, restando in piedi.',
    'Fatti sfiorare la nuca da una persona consenziente e mostra come reagisci.',
    'Descrivi in dettaglio il rapporto sessuale che vorresti avere stasera.',
    'Fai il verso più erotico che sai fare guardando negli occhi chi ti attrae.',
    'Bacia il polso di una persona consenziente e sali lentamente con le labbra.',
    'Mostra come inarcheresti la schiena all\'apice del piacere.',
    'Sussurra tre parole sconce all\'orecchio della persona alla tua sinistra, se consenziente.',
    'Fatti mordere un dito da una persona consenziente in modo provocante.',
    'Descrivi la parte del corpo di una persona presente che ti fa più effetto.',
    'Simula un orgasmo lento sfiorandoti solo il collo e il viso.',
    'Fai una mossa di seduzione con lo sguardo e le labbra verso chi ti piace di più.',
    'Togliti la maglietta o slacciala e resta così per due round, se te la senti.',
    'Lecca il sale dalla mano di una persona consenziente prima di un cicchetto.',
    'Metti le mani sui fianchi di una persona consenziente e falla ballare con te.',
    'Descrivi la cosa più sporca che ti hanno mai sussurrato a letto.',
    'Mima di leccare qualcosa di molto intimo su un frutto per dieci secondi.',
    'Fatti stringere da dietro da una persona consenziente e resta così un round.',
    'Fai vedere come ti muovi quando sei sopra durante il sesso, su una sedia.',
    'Sussurra all\'orecchio di chi hai davanti il tuo desiderio più proibito.',
    'Bacia lentamente il collo di una persona consenziente contando fino a dieci.',
    'Mostra il tuo repertorio di gemiti in tre intensità diverse.',
    'Fatti soffiare piano sull\'orecchio da una persona consenziente e reagisci.',
    'Descrivi come useresti le mani su chi hai di fronte, se potessi.',
    'Simula un ballo di seduzione togliendoti lentamente una cintura o un accessorio.',
    'Lecca via lo zucchero dalle labbra di una persona consenziente, se accetta.',
    'Fai la tua migliore imitazione di come chiami il nome di qualcuno a letto.',
    'Metti la fronte contro quella di chi hai davanti e respira forte per dieci secondi.',
    'Descrivi la fantasia a tre che faresti e con chi la faresti.',
    'Mima uno spogliarello completo restando vestito, in trenta secondi.',
    'Fatti graffiare piano la schiena da una persona consenziente sopra i vestiti.',
    'Mostra come ancheggi entrando in una stanza per far girare la testa a tutti.',
    'Sussurra a una persona consenziente cosa le faresti se fossimo soli.',
    'Bacia l\'interno del polso di chi hai di fronte tenendo lo sguardo fisso.',
    'Descrivi il rumore che ti eccita di più durante il sesso.',
    'Simula un amplesso in piedi appoggiandoti al muro per quindici secondi.',
    'Fai capire con le mani la misura del sesso più impressionante che hai avuto.',
    'Lecca il dito indice e sfiora le tue labbra guardando chi ti attrae di più.',
    'Fatti tirare piano i capelli da una persona consenziente e mostra come reagisci.',
    'Descrivi il posto più assurdo dove ti piacerebbe fare sesso.',
    'Mima la posizione del 69 con un cuscino per dieci secondi.',
    'Fai una carezza sensuale sul viso di una persona consenziente scendendo al collo.',
    'Sussurra un elenco di tre cose che faresti a chi hai davanti stanotte.',
    'Mostra come balli attaccato a qualcuno in discoteca, usando una persona consenziente.',
    'Fatti dare un bacio a stampo sul collo da una persona consenziente.',
    'Descrivi la cosa più eccitante che ti è capitata in un luogo pubblico.',
    'Simula di gemere il nome della persona più sexy della stanza.',
    'Lecca la parte esterna della mano di chi hai di fronte in modo lento.',
    'Fai vedere come ti spogli quando vuoi sedurre qualcuno, con calma.',
    'Metti una mano tra i capelli di una persona consenziente e avvicina il viso.',
    'Descrivi cosa faresti con le labbra a chi ti attrae di più in questa stanza.',
    'Mima di essere ammanettato al letto per dieci secondi, con espressione.',
    'Fatti accarezzare la schiena scoperta da una persona consenziente, se accetta.',
    'Fai un gemito soffocato come se stessi trattenendoti in un posto pubblico.',
    'Sussurra all\'orecchio di chi hai a destra qual è il tuo feticcio, se consenziente.',
    'Bacia il collo di un cuscino come se fosse la persona che desideri di più.',
    'Descrivi la cosa più selvaggia che vorresti provare almeno una volta.',
    'Simula di essere sculacciato reagendo con un gemito, per dieci secondi.',
    'Lecca lentamente un lecca-lecca o un ghiacciolo fissando chi ti piace.',
    'Fai vedere come ti inarchi quando qualcuno ti bacia il punto giusto.',
    'Metti le labbra sulla spalla di una persona consenziente e sali fino all\'orecchio.',
    'Descrivi il preliminare che non ti stanca mai e ti manda in estasi.',
    'Mima un rapporto appassionato contro una porta per quindici secondi.',
    'Fatti mordere piano il labbro inferiore da una persona consenziente.',
    'Fai la tua faccia più provocante mentre ti passi le mani sul corpo.',
    'Sussurra a chi hai davanti quanto lo desideri, usando parole esplicite.',
    'Bacia le dita di una persona consenziente una a una in modo sensuale.',
    'Descrivi la posizione in cui raggiungi l\'orgasmo più facilmente.',
    'Simula un ballo erotico strofinandoti lentamente contro una sedia.',
    'Lecca via una goccia immaginaria dal petto o dal collo di chi hai davanti, se consenziente.',
    'Fai vedere come ti muovi sotto le lenzuola quando fai l\'amore.',
    'Metti la mano sul cuore di una persona consenziente e scendi piano verso l\'addome.',
    'Descrivi l\'orgasmo più lungo che tu abbia mai avuto e come è successo.',
    'Mima di succhiare un dito in modo osceno per dieci secondi guardando il gruppo.',
    'Fatti stringere forte da una persona consenziente e sussurrale un gemito.',
    'Fai la tua espressione da climax mentre inarchi la schiena, per cinque secondi.',
    'Sussurra all\'orecchio di ognuno cosa ti piacerebbe fargli, in un giro completo.',
    'Fai vedere come reagisci quando ti mordicchiano il collo, con voce e brividi.',
    'Ultima: mima il tuo momento di piacere più intenso, con voce e movimenti, per dieci secondi.',
  ];

  static const List<String> verita = <String>[
    'Hai mai legato o ti sei fatto legare durante il sesso?',
    'Hai mai assaggiato lo sperma o l\'eiaculazione del partner?',
    'Ti piacerebbe fare una cosa a tre? Con chi dei presenti?',
    'Qual è il posto più rischioso in cui l\'hai fatto?',
    'Quante volte al giorno ti masturbi, in media?',
    'Qual è la posizione sessuale che ti fa raggiungere l\'orgasmo più in fretta?',
    'Hai mai finto un orgasmo? Con quante persone?',
    'Qual è la cosa più sporca che ti hanno sussurrato a letto?',
    'Hai mai fatto sesso orale in un luogo pubblico?',
    'Con chi dei presenti faresti sesso senza pensarci due volte?',
    'Qual è il tuo sex toy preferito e ogni quanto lo usi?',
    'Hai mai avuto un orgasmo solo grazie al sesso orale?',
    'Ti eccita di più dare o ricevere sesso orale?',
    'Hai mai mandato un video intimo a qualcuno?',
    'Qual è la fantasia sessuale che non hai mai confessato a nessuno?',
    'Hai mai fatto sesso con più di una persona nella stessa notte?',
    'Qual è la parte del corpo che ti fa perdere la testa quando viene toccata?',
    'Hai mai provato il bondage o l\'idea ti eccita?',
    'Quanto è durato il tuo rapporto sessuale più lungo?',
    'Hai mai fatto sesso al primo appuntamento?',
    'Qual è la cosa più kinky che hai fatto a letto?',
    'Hai mai baciato una persona del tuo stesso sesso?',
    'Ti sei mai masturbato pensando a qualcuno dei presenti?',
    'Qual è il numero di partner che hai avuto finora?',
    'Hai mai avuto un rapporto anale? Ti è piaciuto?',
    'Qual è la tua zona erogena più segreta?',
    'Hai mai usato manette o costrizioni durante il sesso?',
    'Quanto tempo impieghi di solito a raggiungere l\'orgasmo?',
    'Hai mai fatto sesso in auto? Dove eravate parcheggiati?',
    'Chi dei presenti immagini sia il migliore a letto?',
    'Hai mai provato uno spanking, dandolo o ricevendolo?',
    'Qual è la cosa più audace che hai fatto per far eccitare un partner?',
    'Hai mai fatto sesso mentre altri erano nella stanza accanto?',
    'Ti piace il sesso al buio o con la luce accesa?',
    'Hai mai avuto un rapporto con qualcuno molto più grande o più giovane di te?',
    'Qual è il tuo feticcio più particolare?',
    'Hai mai fatto sesso in acqua, in piscina o al mare?',
    'Quante volte a settimana vorresti fare sesso, idealmente?',
    'Hai mai provato il sesso bendato?',
    'Con chi dei tuoi ex rifaresti sesso anche solo per una notte?',
    'Qual è la posizione che non sopporti a letto?',
    'Hai mai avuto un orgasmo multiplo?',
    'Hai mai leccato o baciato una parte del corpo poco convenzionale del partner?',
    'Qual è il pensiero più sporco che hai avuto oggi?',
    'Hai mai fatto sesso con qualcuno di cui non ricordavi il nome?',
    'Ti eccita l\'idea di essere guardato mentre fai sesso?',
    'Hai mai usato cibo durante i preliminari? Cosa?',
    'Qual è la fantasia che vorresti realizzare con una delle persone presenti?',
    'Hai mai fatto sesso in casa dei genitori di qualcuno?',
    'Quanto conta per te la dote fisica di un partner, da uno a dieci?',
    'Hai mai provato dolore consensuale durante il sesso e ti è piaciuto?',
    'Qual è la cosa più strana che ti ha eccitato?',
    'Hai mai avuto un rapporto con due persone contemporaneamente?',
    'Ti masturbi più al mattino o alla sera?',
    'Hai mai fatto sesso telefonico o in videochiamata?',
    'Qual è il posto sul tuo corpo dove vorresti essere baciato più spesso?',
    'Hai mai simulato una scena porno con un partner?',
    'Con chi dei presenti scambieresti volentieri un bacio con la lingua?',
    'Hai mai avuto una storia solo per il sesso?',
    'Qual è stato il tuo orgasmo più imbarazzante da spiegare?',
    'Hai mai indossato lingerie o intimo particolare per sedurre qualcuno?',
    'Ti piace parlare sporco durante il sesso o ti mette a disagio?',
    'Hai mai fatto sesso in un bagno pubblico?',
    'Quanti minuti durano di solito i tuoi preliminari?',
    'Hai mai provato il sesso tantrico o lento e prolungato?',
    'Qual è la cosa più sfacciata che hai chiesto a letto?',
    'Hai mai fatto sesso con un collega o un capo?',
    'Ti eccita di più il sesso passionale o quello dolce?',
    'Hai mai avuto un incontro organizzato solo online per il sesso?',
    'Qual è la parte del tuo corpo di cui vai più fiero a letto?',
    'Hai mai fatto sesso all\'aria aperta, in un bosco o in un parco?',
    'Con chi dei presenti flirteresti se fossi single stasera?',
    'Hai mai provato più di un orgasmo nello stesso rapporto?',
    'Qual è la cosa più proibita che vorresti provare almeno una volta?',
    'Hai mai fatto sesso con qualcuno molto più esperto di te?',
    'Ti piace essere dominato o preferisci avere il controllo?',
    'Hai mai avuto un rapporto in una doccia o in una vasca?',
    'Qual è il tuo record di rapporti in una sola giornata?',
    'Hai mai baciato due persone nella stessa serata?',
    'Qual è la posizione in cui ti senti più sexy?',
    'Hai mai fatto sesso mentre eri al telefono con qualcun altro?',
    'Ti sei mai eccitato in un momento totalmente inopportuno?',
    'Hai mai fatto sesso con la persona sbagliata e te ne sei pentito?',
    'Qual è la cosa più intima che hai confessato solo a un partner?',
    'Hai mai provato il sesso con l\'uso di un vibratore condiviso?',
    'Con chi dei presenti pensi di avere più affinità sessuale?',
    'Hai mai fatto sesso su un tavolo o un ripiano della cucina?',
    'Ti piace guardare video hot da solo o in coppia?',
    'Hai mai avuto un rapporto in ascensore o in un luogo insolito?',
    'Qual è il complimento più eccitante che ti hanno fatto sul corpo?',
    'Hai mai provato il gioco di ruolo a letto? Quale scenario?',
    'Quante posizioni diverse riesci a fare in un solo rapporto?',
    'Hai mai avuto un orgasmo solo con la stimolazione del collo o delle orecchie?',
    'Qual è la cosa che ti fa venire voglia di sesso all\'istante?',
    'Hai mai fatto sesso in tenda o in campeggio?',
    'Ti sei mai innamorato di qualcuno solo per com\'era a letto?',
    'Hai mai usato oli o creme durante il sesso o i massaggi?',
    'Qual è la persona presente con cui non hai mai flirtato ma ci hai pensato?',
    'Hai mai fatto sesso senza dire una parola per tutto il tempo?',
    'Ti eccita di più baciare il collo o le labbra?',
    'Hai mai fatto sesso in un hotel a ore?',
    'Qual è la cosa più sfrenata che ti ha proposto un partner?',
    'Hai mai provato a essere legato mani e piedi?',
    'Con chi dei presenti condivideresti volentieri una notte di passione?',
    'Hai mai avuto un rapporto interrotto sul più bello? Da chi?',
    'Ti piace fare sesso con la musica o in silenzio totale?',
    'Hai mai leccato del cibo dal corpo di un partner?',
    'Qual è la fantasia che ti fa raggiungere l\'orgasmo più velocemente?',
    'Hai mai fatto sesso con qualcuno appena conosciuto in vacanza?',
    'Quanto sei rumoroso a letto, da uno a dieci?',
    'Hai mai provato una sculacciata come parte del gioco erotico?',
    'Qual è la cosa che ti fa impazzire nei preliminari?',
    'Hai mai fatto sesso in un luogo dove potevate essere scoperti?',
    'Ti sei mai masturbato in un posto pubblico?',
    'Hai mai desiderato l\'attuale o l\'ex partner di un amico presente?',
    'Qual è il momento più eccitante che ricordi con un partner?',
    'Hai mai provato il sesso con gli occhi bendati e le mani legate?',
    'Con quale persona famosa faresti sesso senza esitazione?',
    'Hai mai fatto sesso più di tre volte in una notte?',
    'Ti piace di più il sesso mattutino o quello notturno?',
    'Hai mai baciato qualcuno solo per scommessa e poi ti è piaciuto?',
    'Qual è la cosa più erotica che hai scritto in un messaggio?',
    'Hai mai fatto sesso in casa di amici durante una festa?',
    'Qual è il tuo punto debole quando qualcuno vuole sedurti?',
    'Hai mai provato il sesso con un accessorio o un giocattolo nuovo?',
    'Con chi dei presenti ti immagini una notte da ricordare?',
    'Hai mai fatto sesso in un luogo di lavoro?',
    'Ti eccita di più il contatto visivo o le parole durante il sesso?',
    'Hai mai avuto un rapporto così intenso da restare senza forze?',
    'Qual è la cosa più sporca che hai fatto per soddisfare un partner?',
    'Hai mai fatto sesso su una spiaggia di notte?',
    'Ti piace essere morso durante il sesso?',
    'Hai mai avuto un orgasmo troppo forte da farti quasi imbarazzare?',
    'Qual è la parte del corpo del partner che baci per prima?',
    'Hai mai provato a fare sesso davanti a uno specchio?',
    'Con chi dei presenti condivideresti il tuo segreto più erotico?',
    'Hai mai fatto sesso con qualcuno che avevi giurato di evitare?',
    'Ti piace prendere l\'iniziativa o essere sedotto?',
    'Hai mai avuto una fantasia su una persona con cui non dovresti?',
    'Qual è la cosa più audace che indosseresti solo per una notte speciale?',
    'Hai mai fatto sesso mentre pioveva, fuori o vicino a una finestra aperta?',
    'Ti sei mai eccitato guardando qualcuno spogliarsi senza che lo sapesse?',
    'Hai mai provato più partner nella stessa settimana?',
    'Qual è il gesto che ti fa capire subito che vuoi qualcuno a letto?',
    'Hai mai fatto sesso e riso per qualcosa di imbarazzante successo?',
    'Con chi dei presenti faresti volentieri un gioco di seduzione?',
    'Hai mai fatto sesso pensando a una persona diversa da quella con cui eri?',
    'Qual è la cosa più eccitante che qualcuno ti ha detto di volerti fare?',
    'Hai mai avuto un rapporto tanto silenzioso da trattenere ogni gemito?',
    'Ultima: qual è il desiderio sessuale più segreto che non hai mai detto a nessuno qui?',
  ];
}
