/// Obbligo o Verità — tono soft: si può giocare con chiunque, anche in
/// famiglia. Oltre un centinaio di obblighi e altrettante verità: siparietti
/// da salotto e domande che tirano fuori storie, senza mai mettere in
/// imbarazzo davvero.
class ObbligoOVeritaSoft {
  const ObbligoOVeritaSoft._();

  static const List<String> obblighi = <String>[
    'Imita il modo di camminare della persona alla tua destra.',
    'Canta il ritornello dell\'ultima canzone che hai ascoltato.',
    'Parla in rima fino al tuo prossimo turno.',
    'Fai il verso di tre animali e falli indovinare.',
    'Balla dieci secondi senza musica.',
    'Racconta una barzelletta: se nessuno ride, ripetila più forte.',
    'Imita il tuo personaggio preferito di una serie.',
    'Fai una posa da statua e resta immobile per trenta secondi.',
    'Parla come un telecronista sportivo per un minuto.',
    'Mostra l\'ultima foto che hai scattato.',
    'Mostra la tua schermata home senza aprire nulla.',
    'Fai vedere l\'emoji che usi di più e spiega perché proprio quella.',
    'Fai vedere quante sveglie hai impostato.',
    'Chiedi all\'assistente vocale del telefono una domanda assurda scelta dal gruppo.',
    'Manda un messaggio vocale cantato a un tuo contatto a caso.',
    'Chiama un amico e cantagli tanti auguri anche se non è il suo compleanno.',
    'Fai un complimento sincero a ogni persona presente.',
    'Descrivi la persona alla tua sinistra usando solo tre parole.',
    'Inventa un rap di venti secondi sulla persona alla tua sinistra.',
    'Imita l\'insegnante che ricordi peggio.',
    'Fai finta di essere un venditore e vendici questo tavolo.',
    'Presenta il meteo di domani come in televisione.',
    'Parla con accento straniero fino al prossimo giro.',
    'Racconta la trama di un film senza dire il titolo, gli altri indovinano.',
    'Fai un discorso di ringraziamento come se avessi vinto un premio.',
    'Improvvisa una pubblicità per il tuo oggetto più vicino.',
    'Fai vedere come balli quando sei solo in casa.',
    'Canta al posto di parlare per i prossimi due minuti.',
    'Cammina con un libro in equilibrio sulla testa.',
    'Metti i vestiti al contrario per due round.',
    'Fatti fare una nuova pettinatura da chi sta alla tua destra.',
    'Fai un disegno del gruppo in trenta secondi.',
    'Scrivi il tuo nome con la mano sbagliata e mostralo.',
    'Disegna il ritratto di un presente a occhi chiusi e poi regalaglielo.',
    'Recita l\'alfabeto al contrario più veloce che puoi.',
    'Conta fino a venti saltando i multipli di tre.',
    'Di\' tre parole al contrario, partendo dall\'ultima lettera.',
    'Racconta una storia inventata di trenta secondi che inizi con "Ieri notte…".',
    'Racconta la tua giornata come se fosse un film horror.',
    'Descrivi il tuo lavoro o la tua giornata tipo come farebbe un bambino.',
    'Fai finta di essere un robot per un minuto.',
    'Rispondi solo con domande fino al prossimo turno.',
    'Non puoi dire "sì" né "no" fino al tuo prossimo turno.',
    'Parla di te in terza persona fino al tuo prossimo turno.',
    'Ridi il più forte possibile senza motivo.',
    'Resta serissimo per trenta secondi mentre gli altri provano a farti ridere.',
    'Fai venti secondi di plank mentre gli altri contano.',
    'Fai cinque flessioni contate dal gruppo.',
    'Corri sul posto fino alla fine del turno.',
    'Fai dieci squat dicendo il nome di un presente a ogni piegamento.',
    'Mangia qualcosa scelto dalla persona alla tua sinistra.',
    'Assaggia due cose insieme che non stanno bene insieme.',
    'Fai una recensione da critico stellato dell\'ultima cosa che hai mangiato oggi.',
    'Prepara un drink analcolico e fallo assaggiare a qualcuno.',
    'Fai un brindisi improvvisato in onore del gruppo.',
    'Racconta il tuo ricordo più bello con una persona presente.',
    'Racconta come hai conosciuto chi ti sta di fronte.',
    'Di\' cosa invidi (in senso buono) a ogni persona presente.',
    'Fai una previsione sul futuro di una persona presente.',
    'Assegna un soprannome a ognuno e spiegalo.',
    'Rispondi solo a un nuovo soprannome scelto dal gruppo fino a fine partita.',
    'Scegli chi del gruppo porteresti su un\'isola deserta e perché.',
    'Racconta la cosa più costosa che hai comprato inutilmente.',
    'Confessa una tua abitudine strana.',
    'Racconta una tua paura ridicola.',
    'Fai finta di avere paura di un oggetto della stanza.',
    'Racconta un tuo talento inutile e dimostralo.',
    'Mostra il tuo miglior "trucco di magia" improvvisato.',
    'Fai un origami con quello che trovi in un minuto.',
    'Costruisci una torre con tre oggetti della stanza.',
    'Trova tre oggetti gialli in casa in trenta secondi.',
    'Scambia una cosa che indossi con chi ti sta a destra.',
    'Fai un selfie con la faccia più brutta che riesci a fare.',
    'Fatti una foto imitando la posa di chi sta alla tua sinistra.',
    'Fai un video di dieci secondi come se fossi un influencer.',
    'Registra un messaggio motivazionale per il gruppo.',
    'Leggi l\'oroscopo di oggi con voce drammatica.',
    'Inventa un oroscopo per la persona alla tua destra.',
    'Descrivi come sarà la tua vita tra dieci anni, senza pensarci troppo.',
    'Dichiara il tuo amore eterno a un oggetto della stanza: il divano conta.',
    'Recita una scena d\'addio strappalacrime con un cuscino.',
    'Di\' quale canzone conosci a memoria e cantane un pezzo.',
    'Fai il karaoke di dieci secondi senza musica.',
    'Fischia una canzone e falla indovinare.',
    'Fai un beatbox di cinque secondi.',
    'Imita il suono di tre strumenti diversi.',
    'Fai finta di suonare la chitarra come a un concerto.',
    'Balla come se fossi in discoteca da solo.',
    'Insegna al gruppo un passo di ballo.',
    'Fai una foto di gruppo dando tu le indicazioni.',
    'Scegli la colonna sonora della serata e spiega perché.',
    'Racconta la cosa più bella che ti è successa questa settimana.',
    'Di\' una cosa che vorresti imparare e perché non hai iniziato.',
    'Fai un elenco di tre cose per cui sei grato adesso.',
    'Manda un messaggio carino a una persona a cui non scrivi da tempo.',
    'Chiama tua madre o un parente e digli che gli vuoi bene.',
    'Manda "Buongiorno!" con tre emoji a caso nella chat di famiglia.',
    'Lascia che il gruppo scelga il tuo prossimo obbligo del turno seguente.',
    'Sfila come un modello da una parte all\'altra della stanza, giravolta compresa.',
    'Comportati come un T-Rex con le braccia corte fino al tuo prossimo turno.',
    'Usa un telecomando o una spazzola come microfono ogni volta che parli, per un giro.',
    'Fai il cameriere: prendi con aria serissima le ordinazioni immaginarie di tutti.',
    'Mima un film senza parlare finché il gruppo non lo indovina.',
    'Imita un personaggio famoso scelto dal gruppo finché qualcuno non indovina chi è.',
    'Fai un complimento a ogni presente saltellando su una gamba sola.',
    'Prova a leccarti il gomito con impegno totale per dieci secondi.',
    'Racconta una favola della buonanotte in trenta secondi facendo tutte le voci.',
    'Parla per un minuto di un argomento scelto dal gruppo come se fossi il massimo esperto.',
    'Ripeti tre volte di fila uno scioglilingua scelto dal gruppo senza sbagliare.',
    'Descrivi quello che fa la persona di fronte come farebbe un documentario sulla natura.',
    'Fai cinque espressioni a comando: felice, arrabbiato, sorpreso, innamorato, sospettoso.',
    'Balla un lento romantico con una scopa o un cuscino.',
    'Presenta un telegiornale con tre notizie assurde sui presenti.',
    'Fai l\'eco: ripeti l\'ultima parola di chi parla fino al tuo prossimo turno.',
    'Parla sussurrando fino al tuo prossimo turno, qualunque cosa succeda.',
    'Tieni un sorriso gigante stampato in faccia per tre minuti, qualunque cosa succeda.',
    'Inventa un inno del gruppo sull\'aria di una canzone famosa e cantalo.',
    'Fatti mettere in posa dal gruppo come una statua e resta così per una foto.',
    'Fai una scenata drammatica da telenovela perché è finito un biscotto.',
    'Prova a far ridere la persona più seria del gruppo in trenta secondi, senza toccarla.',
    'Impila su di te più cuscini che puoi e resta in equilibrio per dieci secondi.',
    'Inventa una lingua e "traduci" quello che dice la persona alla tua destra.',
    'Fai finta di essere bloccato in una scatola invisibile finché qualcuno non ti "libera".',
    'Racconta come si è formato questo gruppo in stile documentario storico.',
    'Da\' del "lei" a tutti fino al tuo prossimo turno, con estrema formalità.',
    'Fai un tutorial di cucina immaginario con gli oggetti che hai davanti.',
    'Muoviti al rallentatore fino alla fine del turno, replay compresi.',
    'Saluta in cinque lingue diverse, inventando quelle che non conosci.',
    'Imita un animale finché qualcuno non indovina quale.',
    'Rispondi cantando a tutto quello che ti viene detto fino al tuo turno.',
    'Fai dieci saltelli sul posto gridando il tuo nome.',
    'Racconta una barzelletta: se nessuno ride, riprova con un\'altra.',
    'Fai il telecronista della stanza per trenta secondi.',
    'Inventa una pubblicità per l\'oggetto alla tua destra.',
    'Parla con un accento straniero fino al prossimo giro.',
    'Resta immobile come una statua mentre gli altri provano a farti ridere.',
    'Balla senza musica per quindici secondi.',
    'Fai il verso di tre animali scelti dal gruppo.',
    'Racconta la trama di un film famoso in esattamente dieci parole.',
    'Di\' l\'alfabeto al contrario il più veloce possibile.',
    'Fingi di vincere un Oscar e ringrazia i presenti uno per uno.',
    'Cammina come un robot fino alla porta e ritorno.',
    'Inventa un soprannome simpatico per ognuno dei presenti.',
    'Canta "Tanti auguri" come se fosse una canzone rock.',
    'Fai cinque facce diverse in cinque secondi.',
    'Tieni un cuscino in equilibrio sulla testa per un giro intero.',
    'Descrivi la tua giornata usando solo suoni.',
    'Fai una previsione del tempo inventata con la massima serietà.',
    'Ordina una pizza immaginaria in modo epico e drammatico.',
    'Applaudi ogni frase detta dagli altri fino al tuo turno.',
  ];

  static const List<String> verita = <String>[
    'Qual è la cosa più imbarazzante che hai fatto in pubblico?',
    'Qual è stata la tua bugia più grossa da bambino?',
    'Qual è il tuo piacere colpevole musicale?',
    'Quale film ti ha fatto piangere di più?',
    'Qual è la cosa più stupida per cui hai litigato?',
    'Qual è il tuo peggior difetto secondo te?',
    'Quale difetto ti attribuiscono gli amici e tu non riconosci per niente?',
    'Qual è la cosa più costosa che hai rotto?',
    'Hai mai finto di stare male per evitare qualcosa?',
    'Qual è la scusa che usi più spesso?',
    'Cosa fai quando sei solo e nessuno ti vede?',
    'Qual è la tua abitudine più strana?',
    'Quanto tempo passi davvero sul telefono ogni giorno?',
    'Qual è l\'app che apri più spesso senza motivo?',
    'Qual è stata la tua ultima ricerca su internet, quella vera?',
    'Qual è la foto più vecchia che hai nel telefono?',
    'Chi è l\'ultima persona a cui hai scritto?',
    'Qual è il messaggio più imbarazzante che hai mandato?',
    'Hai mai mandato un messaggio alla persona sbagliata? Cosa diceva?',
    'Qual è la cosa più bella che ti ha detto qualcuno?',
    'Qual è il complimento più strano che tu abbia mai ricevuto?',
    'Chi è la persona più importante della tua vita?',
    'Chi chiameresti se avessi un problema serio alle tre di notte?',
    'Qual è la cosa che apprezzi di più in un amico?',
    'Qual è stato il momento più bello di quest\'anno?',
    'Qual è stato il momento più difficile di quest\'anno?',
    'Di cosa hai più paura per il futuro?',
    'Qual è il tuo sogno che non hai ancora detto a nessuno?',
    'Cosa faresti se domani non dovessi più lavorare?',
    'Se potessi cambiare una decisione, quale sarebbe?',
    'Qual è la cosa di cui vai più fiero?',
    'Qual è il complimento che vorresti ricevere?',
    'Cosa ti mette di buon umore in cinque minuti?',
    'Qual è la cosa che ti fa arrabbiare più in fretta?',
    'Qual è la mania da cui non riesci a liberarti?',
    'Sei più ordinato o disordinato di quanto ammetti?',
    'Quando è stata l\'ultima volta che hai riso fino alle lacrime?',
    'Qual è la cosa più coraggiosa che hai fatto?',
    'Cosa non faresti mai per soldi?',
    'Quanto ti costerebbe farti tagliare i capelli a zero?',
    'Qual è il tuo talento nascosto?',
    'Qual è una cosa che tutti sanno fare tranne te?',
    'Qual è la cosa più difficile che hai imparato?',
    'Che voto daresti alla tua vita adesso, da 1 a 10?',
    'Cosa ti manca per arrivare a un 10 pieno?',
    'Qual è il posto più bello in cui sei stato?',
    'Dove vorresti vivere se potessi scegliere?',
    'Qual è il viaggio che rifaresti domani?',
    'Qual è la vacanza peggiore che hai fatto?',
    'Hai mai perso un volo o un treno? Come è finita?',
    'Qual è la cosa più strana che hai mangiato?',
    'Qual è il piatto che sai cucinare meglio?',
    'Qual è il tuo cibo di conforto?',
    'Mangeresti lo stesso piatto per un mese per mille euro?',
    'Qual è la cosa più inutile che hai comprato?',
    'Quanto tempo ci metti davvero a prepararti?',
    'Qual è il vestito che non butti anche se dovresti?',
    'Qual è la moda che hai seguito e ora rinneghi?',
    'Che taglio di capelli rimpiangi?',
    'Faresti un tatuaggio? Dove e cosa?',
    'Qual è la cosa che hai fatto solo per far contento qualcun altro?',
    'Hai mai finto di aver capito qualcosa per non fare brutta figura?',
    'Qual è l\'argomento su cui bluffi di più?',
    'Qual è il libro che dici di aver letto ma non hai finito?',
    'Qual è la serie che hai abbandonato a metà?',
    'Qual è il personaggio che ti somiglia di più?',
    'Se fossi un animale, quale saresti e perché?',
    'Se dovessi cambiare nome, quale sceglieresti?',
    'Qual è il soprannome che odiavi da piccolo?',
    'Qual è la cosa più noiosa che hai fatto per lavoro?',
    'Qual è il collega o compagno di classe che non sopportavi e perché?',
    'Qual è la cosa che rimandi da più tempo?',
    'A che ora vai davvero a dormire?',
    'Quante volte spegni la sveglia prima di alzarti?',
    'Qual è il tuo posto preferito in casa?',
    'Cosa salveresti se dovessi scappare da casa in un minuto?',
    'Qual è l\'oggetto a cui sei più affezionato?',
    'Qual è il regalo più bello che hai ricevuto?',
    'Qual è il regalo più brutto che hai mai ricevuto?',
    'Hai mai riciclato un regalo?',
    'Qual è la promessa di inizio anno che non hai mai mantenuto?',
    'Quale abitudine vorresti eliminare?',
    'Quale abitudine vorresti iniziare?',
    'Chi del gruppo chiameresti per un consiglio serio?',
    'Chi del gruppo ti fa ridere di più?',
    'Cosa hai imparato dalle persone presenti stasera?',
    'Cosa vorresti che il gruppo sapesse di te?',
    'Qual è la domanda che speravi non uscisse stasera?',
    'C\'è qualcosa che hai sempre voluto chiedere a qualcuno qui?',
    'Se dovessi descrivere questa serata con una parola, quale?',
    'Qual è la cosa più imbarazzante che ti è successa a scuola?',
    'Qual è il sogno notturno più assurdo che ricordi?',
    'Qual è la bugia bianca che dici più spesso?',
    'Quale cibo fingi di apprezzare per pura educazione?',
    'Se avessi un superpotere per un giorno, cosa faresti per prima cosa?',
    'Quale persona famosa vorresti a cena e cosa le chiederesti?',
    'Qual è la cosa più divertente successa a una tua riunione di famiglia?',
    'Se potessi scambiarti la vita con qualcuno per un giorno, chi sceglieresti?',
    'Qual è la canzone che canti sempre sbagliando le parole?',
    'Qual è la cosa più strana che hai fatto per noia?',
    'Ti è mai scappato da ridere in un momento in cui era vietatissimo? Racconta.',
    'Qual è la figuraccia che oggi ti fa ridere ma sul momento ti ha distrutto?',
    'Qual è l\'oggetto più strano che tieni in camera?',
    'Qual è la cosa più infantile che fai ancora oggi?',
    'Se la tua vita fosse un film, quale attore ti interpreterebbe?',
    'Qual è stata la tua peggiore idea "geniale"?',
    'Hai mai cantato allo specchio usando la spazzola come microfono?',
    'Qual è la parola che sbagli sempre a pronunciare?',
    'Qual è il tuo record più assurdo, qualsiasi cosa conti come record?',
    'Cosa faresti per primo se vincessi un milione domani mattina?',
    'Qual è l\'app più inutile che hai scaricato e mai usato?',
    'Ti sei mai addormentato in un posto assurdo? Dove?',
    'Qual è la cosa che cerchi su internet perché ti vergogni di non saperla?',
    'Qual è il piatto che hai rovinato nel modo più spettacolare?',
    'Qual è la regola di casa tua che credevi normale e invece era stranissima?',
    'Quale personaggio dei cartoni ti faceva paura da bambino?',
    'Qual è la cosa più assurda a cui credevi da bambino?',
    'Hai mai risposto al saluto di qualcuno che salutava un\'altra persona?',
    'Qual è la notifica che ti mette più ansia?',
    'Qual è la canzone che ti fa partire i ricordi ogni volta?',
    'Se potessi teletrasportarti ovunque per un giorno, dove andresti?',
    'Quale mestiere sognavi di fare da bambino?',
    'Qual è la cosa che tutti amano e tu proprio no?',
    'Quale programma trash guardi e difenderesti a spada tratta?',
    'Hai mai parlato con il tuo animale o con le piante come se capissero tutto?',
    'Qual è la cosa che sai fare peggio ma continui a fare con entusiasmo?',
    'Qual è il messaggio più bello che conservi nel telefono?',
    'Qual è la teoria strampalata a cui un po\' credi anche se sai che è assurda?',
    'Qual è il tuo piano di sopravvivenza in caso di apocalisse zombie?',
    'Preferiresti saper volare o leggere nel pensiero, e perché?',
    'Qual è la scusa più creativa che hai usato per un ritardo?',
    'Cosa facevi da bambino che vorresti fosse socialmente accettabile anche oggi?',
    'Chi del gruppo sopravvivrebbe più a lungo su un\'isola deserta secondo te?',
    'Qual è la parola italiana che trovi più buffa?',
    'Qual è il suono o rumore che proprio non sopporti?',
    'Qual è la cosa più carina che hai fatto in segreto per qualcuno?',
    'Hai mai vinto qualcosa a un concorso o a una lotteria? Cosa?',
    'Qual è il gusto di gelato che secondo te andrebbe vietato per legge?',
    'Qual è il film che tutti adorano e tu non sei mai riuscito a finire?',
    'Qual è il cibo che fingi di non amare ma mangeresti di nascosto?',
    'Qual è la canzone che canti solo quando sei sicuro che nessuno ti senta?',
    'Qual è l\'abitudine più strana che hai quando sei in casa da solo?',
    'Qual è il tuo talento più inutile?',
    'Qual è la paura più irrazionale che hai?',
    'Qual è il regalo peggiore che tu abbia mai riciclato?',
    'Cosa c\'è di più imbarazzante nella tua cronologia di YouTube?',
    'Qual è la scusa che usi più spesso per andartene da una festa?',
    'Qual è il cartone animato che guarderesti ancora adesso senza vergogna?',
    'Se potessi scambiare vita con uno dei presenti per un giorno, chi sceglieresti?',
    'Qual è il complimento che ti fa più piacere ricevere?',
  ];
}
