/// Obbligo o Verità — tono piccante: seduzione diretta e senza giri di parole.
/// Obblighi fisici e di flirt (sempre con partner consenzienti), verità che
/// nominano apertamente notti, fantasie e vita di letto.
class ObbligoOVeritaPiccante {
  const ObbligoOVeritaPiccante._();

  static const List<String> obblighi = <String>[
    'Fai un massaggio sensuale all\'interno coscia di una persona consenziente per trenta secondi.',
    'Sussurra all\'orecchio della persona alla tua destra la tua fantasia più sporca.',
    'Bacia il collo di una persona consenziente e soffia delicatamente sulla pelle.',
    'Fatti togliere un indumento da una persona consenziente usando solo i denti.',
    'Simula un orgasmo per quindici secondi, con audio e gesti, davanti a tutti.',
    'Leva tre capi d\'abbigliamento (accessori esclusi) e resta così per il resto della partita.',
    'Lecca il lobo dell\'orecchio della persona alla tua sinistra (se consenziente).',
    'Togli un accessorio o uno strato nel modo più provocante e lento possibile.',
    'Fatti bendare e indovina tre persone del gruppo baciando loro solo la mano o il braccio.',
    'Mima la tua posizione preferita con un cuscino in modo estremamente realistico.',
    'Appoggia la testa in grembo a una persona consenziente e restaci per tre round.',
    'Manda un nude (o una foto molto provocante) a chi vuoi tu e mostra la notifica d\'invio al gruppo.',
    'Fai una lap dance di trenta secondi a una persona consenziente scelta dal gruppo.',
    'Balla un lento sensuale, corpo a corpo, con una persona consenziente per un minuto.',
    'Traccia con la lingua il profilo del collo della persona alla tua sinistra (se consenziente).',
    'Tieni la mano della persona più attraente della stanza infilandola sotto la sua maglia (se consenziente).',
    'Guarda negli occhi la persona che trovi più attraente per trenta secondi mentre ti mordi il labbro.',
    'Mostra al gruppo la faccia che fai nel momento dell\'orgasmo: tieni la posa per cinque secondi.',
    'Bacia lentamente il petto o la spalla di una persona consenziente a tua scelta.',
    'Fai il verso di come reagisci quando ti fanno sesso orale, con l\'audio.',
    'Recita il tuo repertorio da sexting ad alta voce, con tono estremamente serio.',
    'Detta al gruppo il messaggio di seduzione più spinto che manderesti alla tua crush adesso.',
    'Descrivi ad alta voce come porteresti a letto la persona alla tua sinistra, passo dopo passo.',
    'Insegna al gruppo la tua mossa preferita per eccitare qualcuno in meno di un minuto.',
    'Spiega passo per passo la tua notte ideale: dai preliminari alla colazione.',
    'Fai una pubblicità di trenta secondi di te stesso come amante, citando le tue doti migliori.',
    'Racconta la tua notte migliore includendo dettagli su posizioni e sensazioni.',
    'Descrivi il tuo bacio perfetto e dallo subito a una persona consenziente (se ci sta).',
    'Di\' ad alta voce la frase più sporca che ti abbiano mai sussurrato a letto.',
    'Sussurra "ti voglio ora" con la voce più calda che hai all\'orecchio di tre persone diverse.',
    'Manda un messaggio hot all\'ultima persona con cui sei stato e mostra la risposta.',
    'Fai la tua imitazione di come flirti quando sei ubriaco e vuoi solo concludere.',
    'Mostra al rallentatore come usi la lingua durante un bacio: il gruppo vota la tecnica.',
    'Manda "Sto pensando a noi due a letto." a un contatto scelto dal gruppo.',
    'Leggi ad alta voce la chat più piccante che hai nel telefono, senza censurare nulla.',
    'Mostra la foto più audace che hai scattato o ricevuto negli ultimi mesi.',
    'Fai vedere al gruppo la tua cronologia in incognito degli ultimi due giorni.',
    'Scrivi "Voglio farlo con te" alla persona che ti piace e mostra lo screenshot.',
    'Manda un vocale di seduzione di dieci secondi a un ex scelto dal gruppo.',
    'Racconta fino a dove ti sei spinto nel luogo più pubblico in cui sei mai stato.',
    'Descrivi le tre cose che ti eccitano di più a letto, senza giri di parole.',
    'Racconta il tuo risveglio più imbarazzante dopo una notte di sesso folle.',
    'Confessa qual è il fetish che non hai ancora avuto il coraggio di provare.',
    'Di\' il nome della persona presente con cui avresti più probabilità di finire a letto stasera.',
    'Fai la classifica dei presenti basandoti solo sulla loro potenziale abilità a letto.',
    'Assegna a ogni presente un "voto di attrazione" da 1 a 10, guardandoli negli occhi.',
    'Di\' quale coppia di questa stanza farebbe scintille a letto e perché.',
    'Scegli chi del gruppo vorresti vedere nudo in questo momento.',
    'Fai a una persona del gruppo il complimento più spinto che ti viene in mente sul suo corpo.',
    'Proponi un "gioco di ruolo" veloce alla persona alla tua destra e recita la prima battuta.',
    'Attraversa la stanza come se fossi in uno strip-club, fermati davanti a qualcuno e facci un cenno.',
    'Lascia che il gruppo scriva un messaggio audace dal tuo telefono e lo mandi a chi vuole.',
    'Togli due capi o accessori a scelta, il più lentamente possibile, mentre il gruppo canta una canzone sexy.',
    'Dai una sculacciata decisa, con il suo consenso, alla persona scelta dal gruppo.',
    'Riproduci per dieci secondi i suoni che fai a letto nel momento del piacere massimo.',
    'Bacia lentamente il collo di una persona consenziente partendo dall\'orecchio e scendendo.',
    'Mima da vestito la tua posizione preferita per dieci secondi, con impegno totale.',
    'Di\' ad alta voce il nome della persona in questa stanza che baceresti subito.',
    'Fai un massaggio di un minuto alla schiena di una persona consenziente, infilando le mani sotto i vestiti (se ci sta).',
    'Sussurra all\'orecchio di chi hai a destra cosa le faresti se foste soli in questa stanza.',
    'Fai tre giri di sguardi intensi con la persona che trovi più sexy senza mai ridere.',
    'Descrivi la biancheria intima che indossi stasera nei minimi dettagli.',
    'Balla mezzo minuto di reggaeton strusciandoti (con consenso) contro una persona del gruppo.',
    'Fatti mettere un cubetto di ghiaccio nei pantaloni e resisti un minuto senza urlare.',
    'Sussurra il nome del tuo sex toy preferito all\'orecchio di qualcuno come se fosse una preghiera.',
    'Descrivi come ti tocchi quando sei da solo e vuoi finire in fretta.',
    'Spiega la differenza tra un bacio normale e un bacio "da letto", con esempi teorici.',
    'Mima "sto scrivendo alla mia crush per portarla a casa" con tutte le fasi del panico e del successo.',
    'Mostra la tua posa migliore da "voglio scopare" e spiegane la strategia.',
    'Racconta il complimento più sporco che hai mai ricevuto e chi te l\'ha fatto.',
    'Ripeti "voglio di più" con cinque intenzioni diverse: il gruppo deve indovinare quella giusta.',
    'Fai il gesto più erotico possibile usando solo un cubetto di ghiaccio.',
    'Insegna al gruppo come si fa un succhiotto perfetto senza lasciare troppo segno.',
    'Rivela quale profumo ti fa venire voglia di spogliare qualcuno all\'istante.',
    'Balla un lento di venti secondi con un presente, sussurrandogli cose spinte.',
    'Rifai la faccia di quando vieni: il gruppo vota l\'intensità.',
    'Componi un messaggio di "buongiorno dopo il sesso" che farebbe impazzire chiunque.',
    'Scegli chi del gruppo vorresti come "amico di letto" per un mese intero.',
    'Mordi con delicatezza la spalla di una persona consenziente e lasciala con la voglia di di più.',
    'Percorri con un dito la schiena nuda di una persona consenziente partendo dalla nuca fino alla vita.',
    'Fai scivolare un cubetto di ghiaccio lungo il collo di una persona consenziente con la bocca.',
    'Sciogli i capelli e falli ricadere addosso a una persona consenziente mentre le sussurri qualcosa.',
    'Mordicchia le dita di una persona consenziente una a una, guardandola negli occhi.',
    'Balla accovacciandoti lentamente davanti a una persona consenziente scelta dal gruppo.',
    'Sfiora le labbra della persona più attraente con le tue senza mai baciarla, per dieci secondi.',
    'Fatti scrivere sul corpo, con un dito, una parola sporca da una persona consenziente e indovinala.',
    'Poggia la fronte su quella della persona che trovi più sexy e respirate insieme per venti secondi.',
    'Accarezza la nuca di una persona consenziente mentre le reciti la frase più calda che conosci.',
    'Bacia il polso di tre persone consenzienti diverse fingendo ogni volta più desiderio.',
    'Fai un lento massaggio alle spalle di chi hai a destra sussurrando quanto ti piace la sua pelle.',
    'Passa la lingua sul bordo di un bicchiere in modo provocante mentre fissi la tua crush.',
    'Mordi il tuo labbro inferiore e mantieni lo sguardo con la persona più attraente per un round intero.',
    'Sfila lentamente la cintura o un lacetto e usalo per legare (con consenso) i polsi di qualcuno per un minuto.',
    'Fatti guidare la mano da una persona consenziente ovunque voglia sopra i vestiti, per dieci secondi.',
    'Recita una frase da film erotico con la voce più roca che riesci a fare, davanti a tutti.',
    'Simula un bacio appassionato con il dorso della tua mano, il più realistico possibile.',
    'Descrivi al gruppo, guardando una persona consenziente, cosa faresti alle sue labbra se poteste.',
    'Sussurra un conto alla rovescia da cinque a uno all\'orecchio di qualcuno come se stesse per succedere qualcosa.',
    'Struscia lentamente la guancia contro quella di una persona consenziente come farebbe un gatto in calore.',
    'Mordi l\'aria vicino al collo di una persona consenziente senza toccarla, facendola rabbrividire.',
    'Traccia un cuore con la lingua sul palmo aperto di una persona consenziente.',
    'Balla mezzo minuto muovendo solo i fianchi, il più sensualmente possibile, davanti al gruppo.',
    'Appoggia le tue mani sui fianchi di una persona consenziente e guidala in un lento per venti secondi.',
    'Fatti soffiare sul collo da una persona consenziente e reagisci come se ti stesse facendo impazzire.',
    'Sussurra "chiudi gli occhi" a una persona consenziente e falle indovinare dove la sfiorerai.',
    'Descrivi ad alta voce il tuo risveglio ideale accanto alla persona alla tua destra.',
    'Fai finta di spogliarti con lo sguardo la persona più attraente della stanza, in silenzio, per dieci secondi.',
    'Bacia sulla guancia una persona consenziente scendendo pericolosamente vicino alle labbra.',
    'Mostra come baceresti qualcuno sotto la pioggia usando il gruppo come pubblico e un cuscino come partner.',
    'Racconta la volta in cui hai desiderato di più qualcuno senza poterlo avere.',
    'Passa una fragola (o un dito) sulle labbra di una persona consenziente e falla assaggiare.',
    'Fatti disegnare con un dito una linea dal collo alla mano da una persona consenziente e trattieni il respiro.',
    'Ripeti "vieni qui" con tre toni diversi finché il gruppo non decide quale è il più seducente.',
    'Fai un provino da protagonista di un film per adulti recitando la scena d\'apertura, vestito.',
    'Descrivi il posto esatto in cui vorresti essere baciato adesso e lascia che qualcuno provi (con consenso).',
    'Mima con le mani la silhouette della persona che trovi più sexy mentre la guardi negli occhi.',
    'Sussurra all\'orecchio di chi hai a sinistra il momento della giornata in cui pensi di più al sesso.',
    'Fatti mordere gentilmente l\'orecchio da una persona consenziente e non ridere per dieci secondi.',
    'Balla appoggiato di schiena a una persona consenziente, guidando i suoi movimenti coi fianchi.',
    'Racconta, guardandola, cosa ti attrae fisicamente della persona alla tua destra, dettaglio per dettaglio.',
    'Reggi lo sguardo di una persona consenziente mentre le baci lentamente il dorso della mano risalendo verso il polso.',
    'Fai il gesto di toglierti la maglia il più lentamente possibile, fermandoti a metà tra le proteste del gruppo.',
    'Sussurra una promessa piccante all\'orecchio della tua crush come se fosse un segreto di stato.',
    'Descrivi la scena di seduzione perfetta e assegna a un presente il ruolo del protagonista.',
    'Bacia con trasporto il tuo stesso avambraccio mostrando al gruppo esattamente come baci di solito.',
    'Fatti versare (o versa) qualche goccia d\'acqua sul collo e lasciala scivolare senza asciugarla per un round.',
    'Guarda una persona consenziente e mimale con le labbra, senza voce, tre parole che vorresti dirle a letto.',
    'Fai una camminata da modello su una passerella immaginaria fermandoti a mandare un bacio alla tua crush.',
    'Accarezza lentamente il braccio di chi hai accanto raccontando il tuo sogno erotico più recente.',
    'Metti una canzone lenta e invita a ballare la persona che desideri di più, corpo contro corpo.',
    'Fatti chiudere gli occhi e riconosci tre persone consenzienti solo dal profumo della loro pelle.',
    'Sussurra "sei tutto quello che voglio stasera" alla persona alla tua destra come se lo pensassi davvero.',
    'Descrivi cosa faresti a una persona consenziente se aveste solo cinque minuti in una stanza chiusa.',
    'Mordi delicatamente la spalla di un cuscino simulando come lasci un succhiotto a un partner.',
    'Reggi il mento di una persona consenziente e avvicina il viso al suo fino a un soffio dalle labbra.',
    'Recita una dichiarazione di puro desiderio alla persona più sexy della stanza, in ginocchio.',
    'Fai scorrere lentamente le tue mani lungo i tuoi fianchi mentre fissi la tua crush come in un video musicale.',
    'Sussurra il tuo momento preferito dei preliminari all\'orecchio di una persona consenziente.',
    'Fatti scegliere una parte del corpo da una persona consenziente e falle un complimento bollente su quella.',
    'Balla un tango improvvisato con una persona consenziente finendo in una posa vicinissima ai suoi occhi.',
    'Descrivi come sedurresti qualcuno usando solo la voce, e dimostralo su un presente per dieci secondi.',
    'Fatti scrivere sul collo con un dito il nome di chi ti attrae e fai indovinare al gruppo la persona.',
    'Racconta la fantasia che ti verrebbe voglia di realizzare proprio con qualcuno di questa stanza.',
    'Mostra al gruppo come ti muovi sopra un partner, usando un cuscino, per dieci secondi.',
    'Sussurra alla persona più attraente cosa noti per prima di lei ogni volta che entra in una stanza.',
    'Passa un dito sulle tue labbra lentamente mentre reggi lo sguardo della persona che desideri.',
    'Fatti dettare dal gruppo tre parole sporche e usale in una frase seducente rivolta alla tua crush.',
    'Bacia lentamente le nocche di una persona consenziente risalendo con lo sguardo fino ai suoi occhi.',
    'Descrivi il tuo profumo del corpo preferito su un partner e annusa (con consenso) il collo di qualcuno per verificarlo.',
    'Fatti sussurrare all\'orecchio da una persona consenziente la sua fantasia e reagisci solo con lo sguardo.',
  ];

  static const List<String> verita = <String>[
    'Qual è stata la tua prima volta: età, luogo, posizione e voto da 1 a 10.',
    'Con quante persone sei stato a letto? Di\' il numero esatto, niente arrotondamenti.',
    'Qual è il posto più assurdo o rischioso in cui l\'hai fatto?',
    'Hai mai fatto sesso anale? Ti è piaciuto? Sii onesto.',
    'Sei mai andato a letto con qualcuno il giorno stesso in cui l\'hai conosciuto? Quante volte?',
    'Qual è stato il tuo one night stand più folle e dove è successo?',
    'Hai mai fatto sesso con un amico e poi fatto finta di niente? Chi era?',
    'Hai mai fatto sexting con più di tre persone contemporaneamente?',
    'Qual è il messaggio più sporco che hai mai inviato o ricevuto? Citalo.',
    'Hai mai mandato o ricevuto un video hard di te stesso? Lo faresti ancora?',
    'Hai mai ricevuto una foto audace non richiesta? Qual è stata la tua reazione vera?',
    'Qual è la tua fantasia erotica più estrema che non hai mai detto a nessuno?',
    'Una cosa a tre: l\'hai fatta? Se no, con chi di questo gruppo la faresti?',
    'C\'è una persona in questa stanza con cui passeresti volentieri la notte? Un nome.',
    'Meglio un orgasmo pazzesco di tre minuti o un\'ora di coccole perfette?',
    'Chi è stato il miglior amante della tua vita e perché? Cosa faceva di speciale?',
    'Hai mai baciato due persone diverse nella stessa ora? Dove eravate?',
    'Ti sei mai pentito amaramente di essere andato a letto con qualcuno mentre lo stavi facendo?',
    'Ti sei mai svegliato accanto a qualcuno e sei scappato dalla finestra o di nascosto?',
    'Cosa conta di più a letto: la tecnica, le dimensioni o l\'intesa mentale?',
    'A letto sei più dominante o sottomesso? Fai un esempio di cosa ti piace fare.',
    'Luci accese, specchi e video o buio totale? Motiva la scelta.',
    'Qual è il complimento più eccitante che ti hanno fatto durante il sesso?',
    'Hai mai finto un orgasmo per far finire prima il rapporto? Quante volte?',
    'Qual è la cosa più imbarazzante che ti sia mai successa mentre lo facevi?',
    'Sei mai stato beccato dai tuoi genitori o da un estraneo mentre eri in azione?',
    'Hai mai fatto finta di dormire per evitare di farlo? Perché non ne avevi voglia?',
    'Hai mai raccontato bugie sulle tue prestazioni per fare colpo sugli amici?',
    'Qual è stata la tua maratona di sesso più lunga? Quante volte in un giorno?',
    'C\'è qualcuno in questo gruppo che ti ha mai fatto eccitare anche solo parlando?',
    'Cosa guardi per primo in una persona che ti fa pensare "voglio andarci a letto"?',
    'Qual è il capo di abbigliamento che trovi più sexy in assoluto? E quello che ti spegne?',
    'Ti consideri bravo a letto? Qual è il tuo punto di forza imbattibile?',
    'Cosa vorresti imparare a fare meglio a letto? Hai mai guardato tutorial?',
    'Qual è la frase di rimorchio più sfacciata che hai usato e ha funzionato?',
    'Hai mai flirtato con il partner di un amico stretto? Fin dove sei arrivato?',
    'Hai mai dato un numero falso a qualcuno dopo averci limonato? Perché?',
    'Qual è la cosa più audace che hai fatto in un luogo pubblico affollato?',
    'Hai mai avuto un flirt estivo che è finito con un video o foto hot?',
    'Qual è la differenza d\'età massima che hai avuto in una storia di sesso?',
    'Hai mai baciato qualcuno di questa stanza senza che gli altri lo sapessero?',
    'Chi di noi baceresti subito se si spegnesse la luce per un minuto?',
    'Chi di noi secondo te è il più "selvaggio" a letto, guardandolo ora?',
    'Hai mai usato un\'app di incontri solo per sesso occasionale? Quanti match finiti a letto?',
    'Qual è la chat più compromettente che hai nel telefono in questo momento?',
    'Hai mai scritto a un ex alle tre di notte solo perché avevi voglia di farlo?',
    'Qual è la cosa che ti manca di più a letto del tuo ultimo partner?',
    'Hai mai avuto una storia segreta con una persona impegnata? Com\'è finita?',
    'Sei mai stato "l\'altro" o "l\'altra" consapevolmente? Ti sentivi in colpa?',
    'Qual è il tuo "kink" più strano o inconfessabile?',
    'Sopra o sotto? Davanti o dietro? Rispondi veloce senza pensare.',
    'Hai mai provato dolore a letto e hai scoperto che ti piaceva?',
    'Hai mai fatto sesso in un ufficio o sul posto di lavoro?',
    'Ti sei mai toccato pensando a una persona presente in questa stanza?',
    'Qual è la parte del tuo corpo che riceve più complimenti a letto?',
    'Hai mai ballato uno strip-tease per qualcuno? Com\'è andata?',
    'Qual è la cosa più sporca che hai mai detto a qualcuno mentre lo facevate?',
    'Se potessi scegliere una persona famosa per una notte di solo sesso, chi sarebbe?',
    'Hai mai fatto sesso in un mare, piscina o vasca idromassaggio pubblica?',
    'Qual è l\'ora del giorno in cui ti senti più eccitato di solito?',
    'Cosa indossi di solito per dormire quando sei con qualcuno che vuoi provocare?',
    'Hai mai fatto sesso con i calzini addosso? Il gruppo ti giudica se dici sì.',
    'Qual è la posizione che trovi più faticosa ma che ti dà più piacere?',
    'Hai mai provato il sesso tantrico o sessioni lunghissime? Racconta.',
    'Hai mai usato cibo o ghiaccio durante i preliminari? Com\'è finita?',
    'Qual è il segnale inequivocabile che mandi quando vuoi farlo subito?',
    'Chi di noi porteresti in una stanza privata adesso, se potessi?',
    'Qual è la prima cosa che ti fa capire che una persona ti desidera davvero?',
    'Hai mai baciato qualcuno del tuo stesso sesso? Ti è piaciuto o è rimasta curiosità?',
    'Qual è il gesto apparentemente innocente che ti eccita più di qualsiasi altro?',
    'Preferisci sedurre o farti sedurre? Fai un esempio concreto della tua ultima conquista.',
    'Qual è la cosa più coraggiosa che hai chiesto a letto e come è stata accolta?',
    'Hai mai avuto un sogno erotico su una persona presente in questa stanza?',
    'Qual è la parte del corpo di un partner che ti fa perdere completamente la testa?',
    'Quanto dura per te la notte perfetta e quante volte vorresti farlo?',
    'Hai mai usato un sex toy in coppia? Se no, ti piacerebbe provarci?',
    'Qual è la bugia più grande che hai raccontato per andare a letto con qualcuno?',
    'Hai mai avuto una cotta segreta per un amico del tuo partner?',
    'Qual è il posto della tua casa in cui ti piace di più farlo, a parte il letto?',
    'Hai mai fatto sesso al primo appuntamento? Ti sei pentito o rifatto?',
    'Qual è la frase che ti fa cadere ai piedi di qualcuno all\'istante?',
    'Preferisci un massaggio erotico lentissimo o passare subito al sodo?',
    'Qual è la cosa più audace che hai indossato per far impazzire qualcuno?',
    'Hai mai spiato o ascoltato per sbaglio due persone che lo facevano? Racconta.',
    'Qual è il tuo record di durata dei preliminari e ne vorresti di più o di meno?',
    'Se dovessi descrivere il tuo stile a letto con una sola parola, quale sarebbe?',
    'Hai mai avuto un incontro segreto in un bagno pubblico o in una macchina?',
    'Qual è stata la volta in cui hai desiderato qualcuno che non potevi avere?',
    'Ti sei mai innamorato di qualcuno solo per come baciava?',
    'Qual è la cosa che nessuno immaginerebbe mai su di te a letto?',
    'Hai mai mandato un messaggio hot alla persona sbagliata? Com\'è finita?',
    'Chi di questa stanza, secondo te, è il più bravo a flirtare senza farsi notare?',
    'Qual è il tuo limite assoluto a letto, la cosa che non faresti mai?',
    'Hai mai baciato qualcuno solo per far ingelosire un\'altra persona?',
    'Qual è la parte di te che vorresti che qualcuno baciasse più spesso?',
    'Hai mai avuto una relazione basata solo sul sesso? Quanto è durata?',
    'Qual è la fantasia che condividi con il tuo partner ma non hai mai realizzato?',
    'Ti eccita di più la voce, lo sguardo o le mani di una persona?',
    'Hai mai finto di non essere interessato a qualcuno che invece desideravi tantissimo?',
    'Qual è stata la seduzione più lunga prima di finire finalmente a letto con qualcuno?',
    'Hai mai fatto sesso ascoltando una canzone specifica? Quale?',
    'Qual è il complimento fisico che ti fa sentire immediatamente desiderabile?',
    'Hai mai avuto un colpo di fulmine puramente fisico? Con chi e come è andata?',
    'Preferisci baci lenti e profondi o mordaci e frenetici?',
    'Qual è la cosa più piccante che ti hanno sussurrato mentre lo facevate?',
    'Hai mai desiderato due persone contemporaneamente? Come hai gestito la cosa?',
    'Qual è il tuo profumo, tuo o altrui, che associ al sesso migliore che hai fatto?',
    'Hai mai flirtato spudoratamente con qualcuno davanti al tuo partner?',
    'Qual è la posizione che vorresti provare ma non hai mai avuto il coraggio di proporre?',
    'Hai mai avuto un\'esperienza a più di due? Se no, la faresti e con chi qui?',
    'Cosa ti fa passare la voglia all\'istante mentre stai per farlo?',
    'Qual è la cosa più sexy che una persona possa fare completamente vestita?',
    'Hai mai avuto un flirt con qualcuno di molto più grande o più giovane di te?',
    'Qual è il tuo segnale segreto per far capire a qualcuno che lo vuoi, stasera?',
    'Ti sei mai eccitato in un momento totalmente inappropriato? Dove eri?',
    'Qual è la cosa che ti rende un amante indimenticabile, secondo chi è stato con te?',
    'Hai mai continuato a pensare a un ex mentre eri a letto con un altro?',
    'Qual è la parola più sporca che ti piace sentirti dire all\'orecchio?',
    'Hai mai baciato qualcuno sotto l\'effetto dell\'adrenalina, tipo dopo un pericolo?',
    'Preferisci il sesso programmato e curato o quello improvviso e travolgente?',
    'Qual è la volta in cui hai rischiato di più di essere scoperto in azione?',
    'Hai mai scritto o ricevuto una lettera o un messaggio erotico che conservi ancora?',
    'Chi di questa stanza baceresti, chi porteresti a letto e chi eviteresti? Sii onesto.',
    'Qual è il tuo pensiero più sporco quando vedi qualcuno che ti piace tantissimo?',
    'Hai mai avuto un\'avventura in vacanza che non hai mai raccontato a nessuno?',
    'Qual è il gioco di ruolo che ti piacerebbe provare almeno una volta nella vita?',
    'Ti sei mai svegliato eccitato accanto a un amico? Cos\'hai fatto?',
    'Qual è la cosa più imbarazzante che hai cercato online sul sesso?',
    'Hai mai avuto paura di deludere qualcuno a letto? Come è andata poi?',
    'Qual è il momento in cui ti sei sentito più desiderato in assoluto?',
    'Preferisci fare l\'amore al buio o guardare tutto negli occhi del partner?',
    'Hai mai baciato più di una persona nella stessa serata? Quante?',
    'Qual è la cosa più folle che faresti per una notte con la persona che desideri?',
    'Ti è mai capitato di dover trattenere i gemiti per non farti sentire? Dove?',
    'Qual è la tua zona erogena segreta che pochi hanno scoperto?',
    'Hai mai iniziato tu, senza esitare, con una persona appena conosciuta?',
    'Qual è la cosa che ti fa sentire più sicuro di te quando sei nudo?',
    'Hai mai avuto una relazione a distanza sostenuta solo da videochiamate hot?',
    'Qual è il ricordo erotico che riaffiora più spesso quando sei solo?',
    'Se il partner dei tuoi sogni ti chiedesse una sola cosa a letto, cosa vorresti fosse?',
    'Hai mai fatto sesso di riappacificazione dopo un litigio furioso? Era migliore?',
    'Qual è la persona con cui l\'intesa a letto è stata più forte e perché?',
    'Hai mai provato a resistere a una tentazione e poi ceduto miseramente? Con chi?',
    'Qual è la parte del corpo del tuo partner ideale che guardi per prima?',
    'Ti eccita di più essere guardato o guardare mentre lo fai?',
    'Hai mai fatto un patto "amici con benefici" che è finito male? Racconta.',
    'Qual è la cosa più romantica e la più sporca che vorresti nella stessa notte?',
    'Chi di questa stanza pensi ci stia provando con te in questo momento?',
    'Qual è la domanda più intima che vorresti fare a una persona presente stasera?',
    'Qual è la cosa che ti ecciterebbe fare proprio adesso, se il gioco lo permettesse?',
  ];
}
