/// Obbligo o Verità — tono cattivo: il mazzo più sfacciato e provocatorio.
/// Verità senza filtri su sesso, attrazioni e segreti, obblighi fisici e
/// imbarazzanti.
class ObbligoOVeritaCattivo {
  const ObbligoOVeritaCattivo._();

  static const List<String> obblighi = <String>[
    'Di\' ad alta voce con chi dei presenti andresti a letto stasera stessa se fossi single.',
    'Fai la classifica dei presenti dal più sexy al meno attraente, senza pietà.',
    'Di\' chi in questa stanza ha l\'odore più eccitante secondo te, dopo averli annusati.',
    'Lecca il collo della persona alla tua destra fino a lasciarlo bagnato (se consenziente).',
    'Fai un succhiotto visibile sul collo o sulla spalla di una persona consenziente.',
    'Togliti i pantaloni o la gonna e resta in mutande per i prossimi tre round.',
    'Fatti bendare e indovina chi ti sta baciando sul collo tra i presenti consenzienti.',
    'Descrivi nei minimi dettagli l\'ultima volta che ti sei dato piacere da solo.',
    'Di\' chi tra i presenti scoperesti meglio e spiega il motivo tecnico.',
    'Assegna a ogni presente la sua "specialità" da camera da letto basandoti solo sulla faccia.',
    'Togli un capo di abbigliamento a una persona consenziente usando solo i denti.',
    'Fai una lap dance di un minuto a una persona consenziente scelta dal gruppo: niente sconti.',
    'Siediti a cavalcioni sulla persona scelta dal gruppo per un intero round.',
    'Sussurra la cosa più sporca che vorresti fare a chi hai di fronte.',
    'Balla un lento corpo a corpo con la persona scelta dal gruppo, con le mani dove preferisci.',
    'Tieni un cubetto di ghiaccio in bocca e passalo (con la bocca) a una persona consenziente.',
    'Mostra al gruppo l\'ultimo sexting che hai inviato, parola per parola.',
    'Manda "Voglio scoparti" all\'ultima persona con cui sei stato e mostra la risposta.',
    'Chiama un tuo ex e digli "mi manchi a letto", reggendo trenta secondi di chiamata.',
    'Apri la galleria e mostra la foto più "proibita" che hai, o paga un pegno pesantissimo.',
    'Manda un vocale di trenta secondi in cui simuli un orgasmo a un contatto scelto dal gruppo.',
    'Racconta la tua peggior figura a letto, includendo fluidi o rumori imbarazzanti.',
    'Confessa una bugia sessuale che hai detto a un partner e che non hai mai ammesso.',
    'Di\' l\'età della tua prima volta e descrivi quanto è stata deludente o fantastica nei dettagli.',
    'Dai il tuo telefono sbloccato a chi hai a sinistra: può guardare quello che vuole per un minuto.',
    'Leggi ad alta voce i messaggi della chat che il gruppo sceglie, senza saltare nulla.',
    'Di\' chi dei presenti ti ha fatto eccitare stasera e perché.',
    'Confessa se hai mai desiderato il partner di uno dei presenti e cosa avresti voluto fargli.',
    'Racconta la cosa più cattiva o sfacciata che hai fatto per portarti qualcuno a letto.',
    'Fatti fare tre domande "proibite" dal gruppo e rispondi con sincerità assoluta.',
    'Imita come scoperesti se fossi un pornoattore, con gesti e rumori, per dieci secondi.',
    'Lecca un goccio di drink dal corpo di una persona consenziente scelta da te.',
    'Fai vedere la tua biancheria intima a tutto il gruppo, sfilando i pantaloni o alzando la gonna.',
    'Manda un messaggio hot scelto dal gruppo a un tuo collega di lavoro.',
    'Di\' a ogni persona presente cosa le faresti a letto se non ci fossero regole.',
    'Rivela quale posizione preferisci e mimala sul pavimento per dieci secondi.',
    'Confessa se possiedi sex toys e descrivi come usi il tuo preferito.',
    'Racconta la volta che hai fatto sesso in un posto pubblico rischiando l\'arresto.',
    'Mostra la faccia che fai quando ricevi sesso orale: tieni la posa per dieci secondi.',
    'Chiama la persona con cui l\'hai fatto l\'ultima volta e chiedile un voto onesto.',
    'Descrivi l\'odore e il sapore della tua ultima notte di passione.',
    'Di\' quale dei presenti porteresti in un club per scambisti e perché.',
    'Fatti mettere della panna o del cibo su una parte del corpo e lascia che una persona consenziente lo lecchi.',
    'Racconta la walk of shame più squallida della tua vita: orario, luogo e condizioni fisiche.',
    'Di\' chi tra i presenti ha le mani che vorresti sentire addosso in questo momento.',
    'Confessa se hai mai tradito e descrivi come ti sentivi mentre lo facevi.',
    'Scegli due persone del gruppo che dovrebbero fare una cosa a tre con te stasera.',
    'Fai una previsione spietata sulla vita sessuale di ogni presente per il prossimo anno.',
    'Rivela chi del gruppo secondo te è il più finto a letto e perché.',
    'Racconta il tradimento peggiore che hai fatto: il gruppo decide se sei un mostro o no.',
    'Confessa se hai mai baciato qualcuno qui presente e hai sperato che succedesse altro.',
    'Togliti la maglietta o il top e resta così fino alla fine della partita.',
    'Mima da vestito come ti piace essere preso da dietro, con la massima serietà.',
    'Riproduci il suono esatto che fai nel momento in cui vieni, a volume alto.',
    'Dai una sculacciata forte, con consenso, a chi trovi più attraente qui dentro.',
    'Descrivi il tuo sogno erotico più malato con protagonista un presente (senza dire il nome subito).',
    'Ammetti l\'ultima volta che ti sei toccato guardando le foto di qualcuno in questa stanza.',
    'Di\' quale dei presenti secondo te ha il membro o il seno più bello, basandoti sull\'istinto.',
    'Racconta la scena del tuo risveglio più degradante a casa di uno sconosciuto.',
    'Mostra sul tuo corpo dove ti piace essere leccato di più.',
    'Di\' quante persone hai avuto in una sola settimana al tuo massimo.',
    'Confessa il messaggio più degradante che hai mai inviato per sesso.',
    'Racconta la volta che hai detto "ti amo" solo per riuscire a spogliarli.',
    'Di\' chi dei presenti ti ha deluso di più stasera con le sue risposte.',
    'Bacia sulla bocca, con lingua, una persona consenziente scelta dal gruppo.',
    'Fai un massaggio di due minuti a una persona consenziente infilando le mani nelle mutande (se ci sta).',
    'Confessa se hai mai fatto sesso nel letto di un amico mentre lui non c\'era.',
    'Racconta la volta che hai fatto sesso con qualcuno che odiavi profondamente.',
    'Di\' chi tra i presenti bacia peggio secondo te, anche se non l\'hai mai provato.',
    'Fatti bendare e lascia che il gruppo ti tocchi dove vuole per trenta secondi: devi stare fermo.',
    'Rivela se hai mai provato attrazione per un tuo parente (non stretto).',
    'Descrivi nei dettagli l\'ultima cosa che hai espulso o ingoiato a letto.',
    'Racconta la tua esperienza più estrema: orgie, scambi di coppia o bondage pesante.',
    'Di\' chi in questa stanza porteresti in bagno adesso per cinque minuti di fuoco.',
  ];

  static const List<String> verita = <String>[
    'Con quante persone sei stato davvero a letto? Di\' il numero e non mentire.',
    'Hai mai fatto sesso con qualcuno di questa stanza? Di\' il nome o bevi il doppio.',
    'Con chi di noi passeresti la notte se fossi costretto a scegliere adesso?',
    'Hai mai pensato a uno di noi mentre ti toccavi da solo? Chi?',
    'Chi di noi baceresti con la lingua se non ci fossero conseguenze? Solo un nome.',
    'Hai mai desiderato il partner di uno dei presenti? Hai mai provato a farci qualcosa?',
    'Qual è la fantasia sessuale più sporca che hai e che non hai mai confessato?',
    'Hai mai fatto sesso anale? Ti piace essere quello che dà o quello che riceve?',
    'La persona migliore con cui sei mai stato a letto: cosa faceva che gli altri non sanno fare?',
    'E la peggiore: descrivi il disastro nei minimi dettagli.',
    'Sei mai andato a letto con due o più persone nello stesso giorno? Racconta la giornata.',
    'Con quante persone sei stato senza nemmeno sapere come si chiamavano?',
    'Qual è il posto più assurdo o illegale in cui hai fatto sesso?',
    'Vi hanno mai beccato mentre lo facevate? Chi era e cosa ha visto esattamente?',
    'Hai mai fatto sexting mentre eri a cena con la tua famiglia o il tuo partner?',
    'Hai mai mandato foto del tuo membro o del tuo seno a sconosciuti? Ti è piaciuto?',
    'Hai mai fatto sesso riprendendoti con un video? Il video esiste ancora?',
    'Hai mai ricevuto o fatto proposte per una cosa a tre? Com\'è finita?',
    'Una cosa a tre: la faresti stasera con due persone di questo gruppo? Quali?',
    'Hai mai finto un orgasmo in modo clamoroso? Perché l\'hai fatto?',
    'Ti hanno mai detto in faccia che a letto eri una delusione? Come hai reagito?',
    'Qual è il complimento più volgare che ti hanno fatto a letto e che ti ha eccitato?',
    'Qual è la tua più grande paura o insicurezza quando sei nudo davanti a qualcuno?',
    'Sceglieresti un anno senza sesso o un anno senza internet? Sii onesto.',
    'Quanto tempo è passato davvero dalla tua ultima volta? Giorni, ore o minuti?',
    'Qual è il tuo record di orgasmi in una sola notte? Rispondi col numero.',
    'Il tuo "one night stand" più squallido: descrivi il luogo e la persona.',
    'Sei mai scappato da casa di qualcuno nudo o vestito male dopo averlo fatto?',
    'Qual è il messaggio più spinto e volgare che hai ricevuto ultimamente? Leggilo.',
    'Qual è la cosa più estrema che hai fatto con qualcuno conosciuto da meno di un\'ora?',
    'Hai mai tradito il tuo partner attuale o passato? Descrivi come hai fatto a non farti beccare.',
    'Sei mai stato "l\'amante" di qualcuno sapendo che aveva figli o famiglia?',
    'Qual è la bugia più schifosa che hai detto per andare a letto con qualcuno?',
    'Hai mai usato il letto dei tuoi genitori o di un amico per fare sesso?',
    'Cosa c\'è nel tuo comodino o sotto il letto che ti farebbe vergognare da morire?',
    'Qual è l\'ultima cosa che hai cercato su un sito porno? Sii specifico sul genere.',
    'Qual è il tuo "kink" più inconfessabile e perché ti eccita così tanto?',
    'Ingoiare o sputare? Davanti o dietro? Sopra o sotto? Rispondi a raffica.',
    'Hai mai provato attrazione fisica per un tuo amico e gliel\'hai confessato a letto?',
    'Hai mai detto il nome di un ex mentre eri a letto con un altro? Com\'è finita?',
    'Qual è la cosa più assurda che hai fatto subito dopo aver finito? Scappare o mangiare?',
    'Chi di noi consideri il più "facile" da portare a letto basandoti sulla serata?',
    'Chi di noi secondo te ha la vita sessuale più noiosa e piatta?',
    'Hai mai tradito la fiducia di qualcuno qui presente per un motivo di sesso?',
    'Hai mai letto i messaggi privati di uno dei presenti? Cosa hai scoperto di piccante?',
    'C\'è qualcosa nel tuo telefono che, se uscisse ora, distruggerebbe un\'amicizia qui?',
    'Chi di noi non vorresti mai vedere nudo, nemmeno per un milione di euro?',
    'Se potessi spiare uno di noi in camera da letto per una notte, chi sceglieresti?',
    'Hai mai fatto uno screenshot di una foto hot di qualcuno e l\'hai mostrata ad altri?',
    'Cosa pensi che diremo della tua abilità a letto appena te ne andrai?',
    'Qual è la verità che stai nascondendo a tutti noi stasera?',
    'C\'è qualcuno in questa stanza che odi segretamente perché ha avuto successo con chi volevi tu?',
    'Hai mai desiderato la persona di un tuo migliore amico? Hai provato a rubargliela?',
    'Qual è la cosa più egoista e cattiva che hai fatto a letto?',
    'Chi di noi ha mentito di più stasera secondo te, e su quale domanda?',
    'Hai mai finto un orgasmo con qualcuno che conosciamo tutti?',
    'Possiedi sex toys? Quanti ne hai e qual è il tuo preferito da usare in due?',
    'Ti sei mai toccato pensando a qualcuno di noi stasera? Di\' solo sì o no.',
    'Quante volte a settimana ti dai piacere da solo? Di\' la verità.',
    'Il sesso migliore della tua vita: descrivi le posizioni e cosa lo ha reso unico.',
    'Hai mai fatto sesso con più di una persona nello stesso giorno? Racconta.',
    'Hai mai fatto foto o video "hard" senza che l\'altra persona lo sapesse?',
    'Sesso al primo appuntamento: qual è la tua percentuale di successo?',
    'Qual è il "fetish" che ti vergogni di più ad ammettere?',
    'Hai mai fatto sesso sapendo che qualcuno vi stava guardando o sentendo?',
    'Qual è il tempo record tra il "ciao" e il letto? Ore o minuti?',
    'Chi di noi porteresti in un motel adesso se non ci fossero conseguenze?',
    'Hai mai fatto sesso anale ricevendo? Ti è piaciuto davvero?',
    'Qual è la cosa che hai fatto una volta, hai detto "che schifo" e poi hai rifatto?',
    'Chi è la persona più "sbagliata" con cui sei stato? Ex di amici, parenti alla lontana?',
    'Cosa faresti stanotte se fossi sicuro che nessuno di noi lo saprà mai?',
    'Ultima: stanotte dormi da solo o hai già scritto a qualcuno per non farlo?',
  ];
}
