import '../content_tone.dart';

/// Coppie di "Preferisci" in spagnolo: parità completa col mazzo italiano.
class PreferisciPoolEs {
  const PreferisciPoolEs._();

  static const List<({String a, String b})> pairs = <({String a, String b})>[
    (a: 'Saber cómo morirás', b: 'Saber cuándo'),
    (a: 'Una verdad incómoda', b: 'Una mentira cómoda'),
    (a: 'Más dinero', b: 'Más tiempo libre'),
    (a: 'Ser famoso', b: 'Ser invisible para la gente'),
    (a: 'Viajar al pasado', b: 'Viajar al futuro'),
    (a: 'Saber volar', b: 'Ser invisible'),
    (a: 'Leer la mente', b: 'Predecir el futuro'),
    (a: 'Nunca más redes sociales', b: 'Nunca más películas'),
    (a: 'Perder el móvil', b: 'Perder las llaves de casa'),
    (a: 'Siempre 5 minutos antes', b: 'Siempre 10 minutos tarde'),
    (a: 'Jefe simpático pero inútil', b: 'Jefe borde pero brillante'),
    (a: 'Sueldo alto y trabajo aburrido', b: 'Sueldo bajo y trabajo que amas'),
    (a: 'Boda con 200 invitados', b: 'Boda de dos'),
    (a: 'Una semana sin salir', b: 'Salir todas las noches'),
    (a: 'Dormir 10 horas', b: 'Dormir 5 y estar genial'),
    (a: 'Repetir las vacaciones perfectas', b: 'Probar un sitio nuevo'),
    (a: 'Mirar la cuenta cada día', b: 'No mirarla nunca'),
    (a: 'Superpoder inútil pero divertido', b: 'Superpoder útil pero aburrido'),
    (a: 'Releer siempre el mismo libro', b: 'No acabar ninguno nunca'),
    (a: 'Vida sin música', b: 'Vida sin cine'),
    (a: 'Saber siempre la verdad', b: 'Vivir feliz en la ilusión'),
    (a: 'Un año sabático', b: 'Jubilarte un año antes'),
    (a: 'Hablar todos los idiomas', b: 'Tocar todos los instrumentos'),
    (a: 'No sentir nunca vergüenza', b: 'No sentir nunca miedo'),
    (a: 'Revivir tu mejor día', b: 'Borrar el peor'),
    (a: 'Vivir juntos al mes', b: 'Vivir juntos tras años'),
    (a: 'Hijos pronto', b: 'Hijos tarde'),
    (a: 'Viaje planeado al detalle', b: 'Salir a la aventura'),
    (a: 'Una temporada en una noche', b: 'Un episodio por semana'),
    (a: 'Batería siempre al 1%', b: 'Internet lentísimo'),
    (a: 'Ropa siempre algo mojada', b: 'Piedra en el zapato para siempre'),
    (a: 'Decir siempre lo que piensas', b: 'No poder hablar nunca más'),
    (a: 'Sin calefacción en invierno', b: 'Sin aire en verano'),
    (a: 'Hipo de por vida', b: 'Estornudar cada dos minutos'),
    (a: 'Tu plato favorito en cada comida', b: 'Nunca más tu plato favorito'),
    (a: 'No necesitar dormir nunca', b: 'No necesitar comer nunca'),
    (a: 'Rico pero sin amigos', b: 'Sin blanca pero muy querido'),
    (a: 'Nunca más alquiler', b: 'Sueldo el doble'),
    (a: 'El más simpático de la sala', b: 'El más listo de la sala'),
    (a: 'Memoria fotográfica', b: 'Olvidar cada ridículo'),
    (a: 'Nunca más colas', b: 'Nunca más atascos'),
    (a: 'Cejas rapadas un año', b: 'Pelo verde flúor un año'),
    (a: 'Perder el olfato', b: 'Perder el gusto'),
    (a: 'Voz de dibujo animado', b: 'Risa que avergüenza a todos'),
    (a: 'Historial visible para tus padres', b: 'Chats leídos por tu jefe'),
    (a: 'Eructar al final de cada frase', b: 'Reírte como una cabra'),
    (a: 'Usar el cepillo de un desconocido', b: 'Beber de su vaso ya usado'),
    (a: 'Manos siempre sudadas', b: 'Labios siempre agrietados'),
    (a: 'Salir con tu ex', b: 'Con el ex de tu mejor amigo'),
    (a: 'Pedos ruidosos pero sin olor', b: 'Silenciosos pero mortales'),
    (a: 'Olvidar quién eres', b: 'Que todos te olviden'),
    (a: 'Perder todo tu dinero', b: 'Perder todos tus recuerdos'),
    (a: 'Pareja rica pero aburrida', b: 'Pareja pobre pero divertida'),
    (
      a: 'Una hora en el ascensor con tu ex',
      b: 'Una hora en el ascensor con tu jefe',
    ),
    (a: 'Cumpleaños olvidado por todos', b: 'Fiesta sorpresa incómoda'),
    (a: 'Tu secreto contado a todos', b: 'Saber los secretos de todos'),
    (a: 'Famoso pero odiado', b: 'Anónimo pero querido'),
    (a: 'No volver a reír', b: 'No volver a llorar'),
    (a: 'Volver al instituto un año', b: 'Repetir la selectividad cada año'),
    (a: 'Vivir en una peli de terror', b: 'Vivir en un musical'),
    (a: 'Pies en lugar de manos', b: 'Manos en lugar de pies'),
    (
      a: 'Un pato del tamaño de un caballo',
      b: 'Cien caballos del tamaño de un pato',
    ),
    (a: 'Vivir bajo el agua', b: 'Vivir en el espacio'),
    (
      a: 'Perseguido por un caracol asesino',
      b: 'Un payaso que te mira cada noche',
    ),
    (a: 'Hablar con los animales', b: 'Controlar el tiempo'),
    (a: 'Bailar en cuanto suena la música', b: 'Llorar cuando alguien se ríe'),
    (a: 'Cada mañana en un país distinto', b: 'No salir nunca de tu ciudad'),
    (a: 'Vivir en un videojuego', b: 'Vivir en un dibujo animado'),
    (a: 'Botón de pausa para la vida', b: 'Botón de rebobinar para la vida'),
    (a: 'Teletransporte sin zapatos', b: 'Volar a paso de tortuga'),
    (a: 'Vivir 1000 años', b: 'Diez vidas de 100 años'),
    (a: 'Lluvia de tacos', b: 'Nieve de helado'),
    (a: 'Rey del mundo un día', b: 'Persona normal para siempre'),
    (a: 'Saberlo todo sin sentir nada', b: 'Sentir todo sin entender nada'),
    (a: 'Borrar un arrepentimiento', b: 'Garantizarte un éxito futuro'),
    (a: 'Siempre con hambre', b: 'Siempre con sueño'),
    (
      a: 'Cola que se mueve si eres feliz',
      b: 'Orejas que caen si estás triste',
    ),
    (a: 'Renunciar al café para siempre', b: 'Renunciar al chocolate'),
    (a: 'Nariz que crece al mentir', b: 'Pelo que cambia con el ánimo'),
    (
      a: 'Encontrar el amor de tu vida',
      b: 'Encontrar el trabajo de tus sueños',
    ),
    (a: 'Riquísimo pero siempre triste', b: 'Sin un euro pero feliz'),
    (a: 'Un millón ahora', b: '3.000 euros al mes de por vida'),
    (a: 'Salvar a tu perro', b: 'Salvar a un desconocido'),
    (a: 'No poder mentir nunca', b: 'Creerte cualquier mentira'),
    (a: 'Tener razón siempre pero solo', b: 'Equivocarte pero acompañado'),
    (a: 'Genio incomprendido', b: 'Simplón feliz'),
    (a: 'El mismo look cada día', b: 'No repetir look nunca'),
    (a: 'Cantar todo lo que dices', b: 'Andar solo hacia atrás'),
    (a: 'Wifi gratis en todas partes', b: 'Vuelos gratis de por vida'),
    (a: 'Comer solo comida hirviendo', b: 'Solo comida helada'),
    (a: 'Nunca más pizza', b: 'Nunca más pasta'),
    (a: 'Nunca más cañas', b: 'Nunca más comida a domicilio'),
    (a: 'Vida larga llena de reproches', b: 'Vida corta sin arrepentimientos'),
    (a: 'Amar sin ser correspondido', b: 'Que te ame quien no amas'),
    (a: 'Tu pareja te lee la mente', b: 'Tú le lees la mente'),
    (a: 'Pareja elegida por tus amigos', b: 'Pareja elegida por un algoritmo'),
    (a: 'Saber siempre quién te miente', b: 'Que nunca te pillen mintiendo'),
    (a: 'Revivir tus 18 años para siempre', b: 'Saltar directo a los 40'),
    (a: 'Dormir siempre en casa ajena', b: 'Tener siempre invitados en casa'),
    (
      a: 'Tu grupo favorito pero tú solo',
      b: 'Festival con amigos y música que odias',
    ),
    (
      a: 'Karaoke desafinando ante todos',
      b: 'Bailar solo en la pista una hora',
    ),
    (a: 'Perder todas las fotos del móvil', b: 'Perder todos los chats'),
    (a: 'Estornudar confeti', b: 'Eructar pompas de jabón'),
    (a: 'Tener cuatro brazos', b: 'Tener cuatro piernas'),
    (a: 'Medir dos veinte', b: 'Medir uno veinte'),
    (a: 'Vivir sin verano', b: 'Vivir sin invierno'),
    (a: 'Salvar a cinco desconocidos', b: 'Salvar a tu mejor amigo'),
    (a: 'Un millón y nunca más móvil', b: 'Cero dinero pero con móvil'),
    (
      a: 'Trabajo ideal en el extranjero',
      b: 'Trabajo aburrido cerca de amigos',
    ),
    (a: 'Tener 25 años para siempre', b: 'Envejecer con tus amigos'),
    (a: 'Casa ideal en medio de la nada', b: 'Estudio en pleno centro'),
    (
      a: 'Saber qué dicen de ti a tus espaldas',
      b: 'Vivir tranquilo sin saberlo',
    ),
    (a: 'Cada comida hecha por un chef', b: 'Chófer personal de por vida'),
    (
      a: 'Narrar en voz alta todo lo que haces',
      b: 'Oír la voz narradora de tu vida',
    ),
    (a: 'Pisar Legos cada mañana', b: 'Ducha helada cada mañana'),
    (a: 'Un mosquito cada noche', b: 'Una mosca en cada plato'),
    (a: 'Autocorrector loco de por vida', b: 'Nunca más emojis'),
    (
      a: 'Llamadas solo en manos libres',
      b: 'Pantalla siempre visible para todos',
    ),
    (a: 'Tu perro habla pero te critica', b: 'Tu espejo te halaga en falso'),
    (a: 'Un millón solo para ti', b: 'Cien mil por cabeza para el grupo'),
    (a: 'Que siempre te infravaloren', b: 'Que siempre te sobrevaloren'),
    (a: 'Redescubrir tu serie favorita', b: 'Ver antes cada final'),
    (a: 'Hablar solo a gritos', b: 'Hablar solo susurrando'),
    (a: 'Reírte siempre en momentos serios', b: 'Llorar con cada comedia'),
    (a: 'Comer siempre con las manos', b: 'Comer todo con cucharilla'),
    (a: 'Tus sueños proyectados a tus amigos', b: 'Tus amigos leen tu diario'),
    (a: 'El único soltero del grupo', b: 'El primero del grupo en casarte'),
    (a: 'Nacer en los 80', b: 'Nacer en 2050'),
    (a: 'Restaurantes gratis pero solo', b: 'Pagar siempre pero acompañado'),
    (a: 'Viral por un ridículo épico', b: 'Nunca más de 10 likes'),
    (a: 'Beber solo agua para siempre', b: 'Nunca más agua, solo refrescos'),
    (a: 'Un solo género musical de por vida', b: 'Una sola app en el móvil'),
    (a: 'De esmoquin en la playa', b: 'En bañador en una boda'),
    (a: 'Cocinar como un chef con estrella', b: 'Casa que se limpia sola'),
    (a: 'Vuelo largo junto a un charlatán', b: 'Vuelo largo junto a un bebé'),
    (a: 'Desayuno salado para siempre', b: 'Cena dulce para siempre'),
    (a: 'Vivir sin espejos', b: 'Vivir sin relojes'),
    (a: 'Revivir el mismo lunes', b: 'Saltarte todos los viernes'),
    (a: 'Hablar con las plantas', b: 'Entender a los bebés'),
    (a: 'Ganar siempre a las cartas', b: 'Encontrar siempre aparcamiento'),
    (a: 'Verano de 40 grados sin playa', b: 'Invierno helado sin nieve'),
    (a: 'Solo pelis mal dobladas', b: 'Solo pelis con subtítulos desfasados'),
    (a: 'Café gratis de por vida', b: 'Helado gratis de por vida'),
    (a: 'Mudarte cada año', b: 'La misma casa para siempre'),
    (a: 'Tono de móvil vergonzoso siempre', b: 'Fondo de pantalla vergonzoso'),
    (a: 'Ser un meme famoso', b: 'Tener un doble famoso'),
    (
      a: 'Bailar la macarena al saludar',
      b: 'Saludar a todos con una reverencia',
    ),
    (a: 'Nocilla sin pan', b: 'Pan sin Nocilla'),
    (a: 'Fin de semana infinito con lluvia', b: 'Solo lunes pero siempre sol'),
    (a: 'Un solo plato pero perfecto', b: 'Cocinarlo todo regular'),
  ];

  /// Dilemmi da modalità Hot: parità completa col mazzo italiano.
  static const List<({String a, String b, String tone})> hot =
      <({String a, String b, String tone})>[
        (
          a: 'Salir desnudo un minuto',
          b: 'Besar a alguien de este grupo',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Pasar la noche con alguien del grupo',
          b: 'Una noche con un viejo profe tuyo',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Enseñar tu galería al grupo',
          b: 'Que lean tus chats en voz alta',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Un año sin sexo',
          b: 'Un año sin salir de noche',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Decir tu body count al grupo',
          b: 'Enseñar tu última búsqueda',
          tone: ContentTone.piccante,
        ),
        (a: 'Amor sin sexo', b: 'Sexo sin amor', tone: ContentTone.piccante),
        (
          a: 'Pareja guapa pero pésima en la cama',
          b: 'Pareja normal pero fenomenal',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Una noche con tu ex',
          b: 'Una noche con un desconocido',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Pillar a tus padres',
          b: 'Que te pillen tus padres',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Decir a todos quién te gusta ahora',
          b: 'No volver a hablar nunca con quien te gusta',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Besar con los ojos cerrados a alguien del grupo',
          b: 'Besar a tu ex delante de todos',
          tone: ContentTone.piccante,
        ),
        (
          a: 'No poder besar nunca más',
          b: 'No poder abrazar nunca más',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Saber con quién te engañaría tu pareja',
          b: 'No saberlo jamás',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Solo citas a ciegas durante un año',
          b: 'Solo salidas elegidas por tu madre',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Volver a ver en vídeo tu primer beso',
          b: 'Que lo vea todo el grupo',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Gemir cada vez que te sientas',
          b: 'Gritar el nombre de tu ex en cada brindis',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Mandar un nude a tu ex por error',
          b: 'Mandarlo al grupo de la familia',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Sexting con tu jefe por error',
          b: 'Llamar a tu pareja con el nombre de tu ex',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Una noche con una celebridad',
          b: 'Un mes de sexo con tu ex',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Hacer sexo solo a oscuras totales',
          b: 'Solo con la luz siempre encendida',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Decir tu fantasía más rara',
          b: 'Escuchar la de quien tienes a la derecha',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Amigos de cama con tu mejor amigo',
          b: 'Nunca más sexo durante un año',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Un ex que besa de maravilla',
          b: 'Uno nuevo al que enseñárselo todo',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Que te desnuden con la mirada en el bar',
          b: 'No volver a llamar la atención jamás',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Contar tu peor cita',
          b: 'Revivir tu ridículo más caliente',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Dar tú siempre el primer paso',
          b: 'Esperar siempre a que arranque el otro',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Un trío con desconocidos',
          b: 'Un trío con amigos',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Pillar a tu compañero de piso en acción',
          b: 'Que te pille tu compañero de piso',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Decir cuántas veces lo piensas al día',
          b: 'Decir cuándo lo hiciste la última vez',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Pareja supercelosa pero ardiente',
          b: 'Pareja tranquila pero perezosa en la cama',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Besar al primero que entre por la puerta',
          b: 'Besar al último que te escribió',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Noche de pasión sin besos',
          b: 'Besos infinitos y nada más',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Olvidar tu primera vez',
          b: 'Recordarla cada santo día',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Decir el sitio más absurdo donde lo hiciste',
          b: 'Decir el sitio donde te gustaría hacerlo',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Un flirteo con tu entrenador personal',
          b: 'Un flirteo con tu médico',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Solo rollos de una noche durante un año',
          b: 'Solo relaciones serias de por vida',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Volver con tu ex de vez en cuando',
          b: 'Cerrar para siempre pero con arrepentimiento',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Un morreo con quien tienes a la izquierda',
          b: 'Un lento sensual con quien tienes a la derecha',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Dormir desnudo con un amigo',
          b: 'Ducharte en bañador con tu ex',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Recibir un nude no pedido de tu jefe',
          b: 'Mandarle uno a tu jefe por error',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Sexo de escándalo una vez al mes',
          b: 'Sexo mediocre cada día',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Saber qué piensa el otro en la cama',
          b: 'Que oiga cada pensamiento tuyo en la cama',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Un finde con tu amor platónico secreto',
          b: 'Un mes con tu primer amor',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Desayuno en la cama tras la primera noche',
          b: 'Desaparecer antes del amanecer',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Decir tu punto débil en la cama',
          b: 'Imitarlo delante del grupo',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Tatuarte el nombre de tu ex',
          b: 'Gritar su nombre en el momento equivocado',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Match con tu ex en una app',
          b: 'Match con tu jefe en una app',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Tu pareja conoce todas tus fantasías',
          b: 'Tú conoces todas las suyas',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Striptease improvisado ahora mismo',
          b: 'Relato picante de tu verano',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Besar a alguien del grupo a tu elección',
          b: 'Besar a uno elegido por el grupo',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Historia secreta superpasional',
          b: 'Historia oficial pero tibia',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Hacer sexo solo en verano',
          b: 'Hacer sexo solo en invierno',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Olvidar todas tus noches locas',
          b: 'Recordar hasta las que querrías olvidar',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Audio caliente mandado a la persona equivocada',
          b: 'Recibir uno de tu jefe',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Enseñar los mensajes con tu ex',
          b: 'Enseñar las fotos con tu ex',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Amor a primera vista esta noche',
          b: 'Aventura de una noche esta noche',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Decir el nombre de tu crush al grupo',
          b: 'Hacer que lo adivine el grupo',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Bailar un lento con tu ex esta noche',
          b: 'Karaoke romántico con alguien del grupo',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Tirarle la caña a un desconocido ahora',
          b: 'Dar tu número al primero que lo pida',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Un masaje de alguien del grupo',
          b: 'Hacérselo tú a alguien del grupo',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Prohibido flirtear durante un año',
          b: 'Obligado a flirtear con cualquiera',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Una noche con tu ídolo musical',
          b: 'Un finde con tu actor favorito',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Confesar un sueño caliente sobre un presente',
          b: 'Que un presente lo confiese sobre ti',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Silencio total en la cama',
          b: 'Narración completa en la cama',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Un culo de escándalo',
          b: 'Un escote de aplauso',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Tu ex se vuelve famosísimo',
          b: 'Tu ex se vuelve tu jefe',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Decir qué te excita más',
          b: 'Decir qué te corta el rollo al instante',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Un lío de verano nunca confesado',
          b: 'Un amor a distancia infinito',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Dos presentes te tiran la caña',
          b: 'Tirarles la caña tú a dos presentes a la vez',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Ver a tu ex con alguien más guapo que tú',
          b: 'Que te vea con alguien peor que él',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Besos con mordisco',
          b: 'Besos de piquito para siempre',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Dormir abrazados sin sexo',
          b: 'Sexo sin dormir nunca juntos',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Hacer sexo con la música a tope',
          b: 'Con el telediario de fondo',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Revelar tu número de ex',
          b: 'Revelar quién fue el mejor',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Tirarle la caña al camarero esta noche',
          b: 'Dejarle el número en el recibo',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Primera vez torpe pero tierna',
          b: 'Perfecta pero con la persona equivocada',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Un tatuaje donde decida el grupo',
          b: 'Un piercing donde decida el grupo',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Un beso de 30 segundos con un presente',
          b: 'Diez besos rápidos con diez desconocidos',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Saber quién del grupo sueña contigo de noche',
          b: 'Saber quién no te besaría jamás',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Sexo en tienda en un camping lleno',
          b: 'En un hotel con paredes de papel',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Unas vacaciones solo para solteros',
          b: 'Unas vacaciones solo para parejas',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Sexo anal cada vez',
          b: 'Nunca más sexo durante un año',
          tone: ContentTone.piccante,
        ),
        (a: 'Ser dominado', b: 'Ser dominante', tone: ContentTone.piccante),
        (
          a: 'Hacer sexo con dos personas a la vez',
          b: 'Prescindir de él seis meses',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Que te graben mientras lo haces',
          b: 'No hacerlo nunca más',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Lamer por todas partes',
          b: 'Que te laman por todas partes',
          tone: ContentTone.piccante,
        ),
        (a: 'Tragar', b: 'Escupir', tone: ContentTone.cattivo),
        (
          a: 'Que te venden y te aten',
          b: 'Ser tú quien venda y ate',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Sexo salvaje con un desconocido',
          b: 'Sexo mediocre con la pareja ideal',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Hacerle tragar a él',
          b: 'Hacer que te lo escupa encima',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Un trío con desconocidos',
          b: 'Con dos amigos íntimos de aquí',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Solo sexo oral durante un año',
          b: 'Nunca más sexo oral',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Recibir siempre el oral',
          b: 'Hacerlo siempre tú',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Un oral que acaba en la boca',
          b: 'Un oral que acaba en la cara',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Lamer hasta el orgasmo',
          b: 'Que te laman hasta el orgasmo',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Una mamada de 30 minutos',
          b: 'Correrte en 30 segundos',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Un trío con dos desconocidos',
          b: 'Ver a tu pareja con otro',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Un trío con dos hombres',
          b: 'Un trío con dos mujeres',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Una orgía de ocho personas',
          b: 'Sexo en solitario durante un año',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Ver a tu pareja follar con otro',
          b: 'Que te miren mientras follas',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Un desconocido te mira correrte',
          b: 'Miras a un desconocido correrse',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Que te aten y te venden',
          b: 'Atar y vendar tú',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Que te fustiguen con suavidad',
          b: 'Fustigar tú a tu pareja',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Sumisa por una noche',
          b: 'Dominatriz por una noche',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Collar y correa puestos a ti',
          b: 'Ponérselos tú a tu pareja',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Azotes hasta dejar marca',
          b: 'Azotar tú hasta dejar marca',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Atada a la cama toda la noche',
          b: 'Atar tú a tu pareja a la cama',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Vendada y a merced de tu pareja',
          b: 'Vendar tú y mandar',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Un vibrador una hora sin parar',
          b: 'Ningún orgasmo durante un mes',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Orgasmo negado durante días',
          b: 'Orgasmos forzados sin parar',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Un plug puesto todo el día',
          b: 'Un vibrador en público',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Probar todos los juguetes de la tienda',
          b: 'Solo manos para siempre',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Un consolador enorme',
          b: 'Un vibrador pequeño pero constante',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Esposas de verdad en las muñecas',
          b: 'Cuerdas de seda por el cuerpo',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Sexo en el baño de un local',
          b: 'Sexo en un callejón a oscuras',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Hacerlo en la playa de noche',
          b: 'Hacerlo en el ascensor',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Sexo en el coche en un aparcamiento',
          b: 'Sexo en una azotea de noche',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Arriesgarte a que os pillen en la oficina',
          b: 'Hacerlo en un probador',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Sexo en un tren en marcha',
          b: 'Sexo bajo una mesa llena de gente',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Un vídeo caliente que circula',
          b: 'Tus chats calientes que circulan',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Tus fotos desnuda en el móvil de él',
          b: 'Un vídeo íntimo tuyo guardado',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Grabaros mientras lo hacéis',
          b: 'Fotografiarte desnuda para él',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Un desnudo enviado por error al jefe',
          b: 'Un desnudo visto por tus amigos',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Hacer sexo delante de una webcam',
          b: 'Hacer sexo con la luz siempre encendida',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Sexo rudo y sin piedad',
          b: 'Sexo lento toda la noche',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Correrte cinco veces seguidas',
          b: 'Un solo orgasmo larguísimo',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Fingir siempre el orgasmo',
          b: 'No correrte nunca más',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Un orgasmo cada hora durante un día',
          b: 'Ningún orgasmo durante un año',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Squirtear delante de él',
          b: 'Verlo correrse sobre tu cuerpo',
          tone: ContentTone.cattivo,
        ),
        (a: 'Sexo anal', b: 'Doble penetración', tone: ContentTone.cattivo),
        (
          a: 'Probar el anal por primera vez',
          b: 'No probarlo nunca',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Ligarte a un desconocido esta noche',
          b: 'Un ex para una última noche',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Una noche con tu mito del cine',
          b: 'Una noche con tu mejor ex',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Sexo con el mejor amigo de él',
          b: 'Sexo con la mejor amiga de ella',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Intercambio de pareja con amigos',
          b: 'Intercambio con perfectos desconocidos',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Besar a todos en una orgía',
          b: 'Elegir a una sola persona',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Un masaje que acaba en la cama',
          b: 'Un lap dance privado',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Striptease delante del grupo',
          b: 'Bailar desnuda en una barra',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Lamer la nata de su cuerpo',
          b: 'Hacerle lamer el chocolate de ti',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Sexo cubiertos de aceite',
          b: 'Sexo bajo la ducha ardiente',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Un fetiche de pies satisfecho',
          b: 'Un fetiche del culo satisfecho',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Que te chupen los dedos de los pies',
          b: 'Chuparle tú los suyos',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Llevar solo lencería en una cena fuera',
          b: 'Sin ropa interior en una cena fuera',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Un corsé apretado toda la noche',
          b: 'Tacones de aguja y nada más',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Sexo con antifaz en la cara',
          b: 'Sexo a oscuras totales',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Decir en voz alta tus fantasías',
          b: 'Cumplir una al azar',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Un juego de rol de profe y alumno',
          b: 'Un juego de rol de jefe y secretaria',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Fingir ser dos desconocidos en un bar',
          b: 'Fingir ser ex que se reencuentran',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Sexo mientras los demás duermen cerca',
          b: 'Sexo gritando sin freno',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Que te digan guarradas al oído',
          b: 'Decírselas tú a él',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Sexting toda la jornada de trabajo',
          b: 'Fotos calientes cada hora',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Una mamada mientras conduce',
          b: 'Un dedeo en el cine',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Seducirlo con la mirada durante una hora',
          b: 'Saltarle encima enseguida',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Cabalgarlo hasta agotarlo',
          b: 'Dejar que te tomen por detrás',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Sexo en tres posturas seguidas',
          b: 'Una hora en la misma postura',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Hacerlo correrse solo con las manos',
          b: 'Solo con la boca',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Una mamada con los ojos vendados',
          b: 'Un polvo con los ojos vendados',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Hielo sobre la piel desnuda',
          b: 'Cera caliente sobre el cuerpo',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Morder hasta dejar marcas',
          b: 'Arañar la espalda a fondo',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Chupetones visibles en el cuello',
          b: 'Marcas de mordiscos en la cara interna del muslo',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Sexo con una sola pareja para siempre',
          b: 'Una pareja distinta cada mes',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Ver a tu pareja desnuda con otro',
          b: 'No saber nunca qué hace',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Un trío planeado al detalle',
          b: 'Un trío totalmente improvisado',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Que te desnude despacio él',
          b: 'Desnudarlo tú con los dientes',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Sexo con él de uniforme',
          b: 'Sexo contigo de uniforme',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Un largo preliminar sin penetración',
          b: 'Penetración directa sin preliminares',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Edging durante una hora',
          b: 'Orgasmo inmediato y listo',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Que te toquen en un local lleno',
          b: 'Tocarlo tú bajo la mesa',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Un dedo extra durante el acto',
          b: 'Una lengua extra durante el acto',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Sexo delante del espejo',
          b: 'Sexo grabado con el móvil',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Llevar un plug en la cena con los suegros',
          b: 'Un vibrador controlado por él',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Vibrador con mando en el metro',
          b: 'Vibrador con mando en el restaurante',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Una sesión larga de azotes',
          b: 'Una sesión larga de bondage',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Suspendida con cuerdas japonesas',
          b: 'Inmovilizada con cinta adhesiva',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Un masaje integral de alguien del grupo',
          b: 'Una ducha junto a alguien del grupo',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Besar al compañero que te gusta hace meses',
          b: 'Que te diga que te corresponde pero tiene pareja',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Sexo lento toda la noche',
          b: 'Sexo rápido y arrollador en un minuto',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Decir en voz alta tu palabra de seguridad',
          b: 'Imitar tu postura favorita',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Flirteo ardiente con el mejor amigo de tu ex',
          b: 'Un flirteo ardiente con el vecino',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Hacer sexo solo en lugares públicos',
          b: 'Hacer sexo solo con la puerta abierta',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Un finde de puro sexo sin hablar',
          b: 'Un finde de solo mimos sin sexo',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Recibir un lap dance de quien tienes a la derecha',
          b: 'Hacerle uno a quien tienes a la izquierda',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Confesar a qué presente cortejarías',
          b: 'Que el grupo te elija un pretendiente',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Probarlo todo en una noche con el desconocido',
          b: 'Guardar castidad un año con el amor verdadero',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Un beso con lengua con tu primer amor',
          b: 'Un abrazo infinito con tu último crush',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Besar por turnos a todos los presentes',
          b: 'Besar a uno solo durante diez minutos',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Decir cuánto duras de media en la cama',
          b: 'Decir tu récord personal',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Un encuentro prohibido con el profe de baile',
          b: 'Un encuentro prohibido con el camarero de abajo',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Seducir a un desconocido en diez minutos',
          b: 'Que te seduzcan sin decir una palabra',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Solo lencería provocativa durante un mes',
          b: 'Solo pijamas deformados durante un año',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Hacer sexo con la misma pareja para siempre',
          b: 'Una pareja distinta cada semana sin amor',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Que te desnude despacio quien tienes delante',
          b: 'Desnudar tú a quien tienes al lado',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Decir la fantasía que nunca has cumplido',
          b: 'Cumplirla esta noche con un presente',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Un beso apasionado bajo la lluvia',
          b: 'Una noche de fuego frente a la chimenea',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Sexo con la persona más guapa jamás vista',
          b: 'Sexo inolvidable con quien de verdad amas',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Que te muerda el cuello quien tienes a la derecha',
          b: 'Morder tú el cuello a quien tienes a la izquierda',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Cuántas veces has pensado en un presente',
          b: 'Que un presente confiese cuántas veces piensa en ti',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Un año de solo aventuras sin mañana',
          b: 'Un año de solo espera por la persona correcta',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Besar a alguien con los ojos vendados y adivinar quién es',
          b: 'Que te besen y que todos adivinen',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Sexo desenfrenado pero sin volver a veros',
          b: 'Espera infinita pero luego para siempre',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Un baile provocativo delante de todo el grupo',
          b: 'Un beso sorpresa elegido por el grupo',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Ducharte junto a tu ex',
          b: 'Bañarte junto a tu crush',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Decir a quién del grupo besarías a oscuras',
          b: 'Decir a quién del grupo no besarías jamás',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Masaje de pies de un desconocido sexy',
          b: 'Un masaje de espalda de tu ex',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Hacer sexo solo con oscuridad y velas',
          b: 'Hacer sexo solo delante del espejo',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Flirteo secreto con tu instructor de natación',
          b: 'Un flirteo secreto con tu tatuador',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Revelar el objeto más atrevido que tienes',
          b: 'Enseñárselo al grupo',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Pasar la noche con tu crush del instituto',
          b: 'Pasar la noche con tu crush de ahora',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Solo besos lentos durante un mes',
          b: 'Solo noches de pasión pero sin besos',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Que te susurren cosas ardientes al oído',
          b: 'Susurrárselas tú a quien tienes al lado',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Decir el mote caliente que le pones a tu pareja',
          b: 'Decir el que tu pareja te pone a ti',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Una noche con quien te rechazó hace años',
          b: 'Una noche con quien te desea desde siempre',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Hacer sexo siempre en la primera cita',
          b: 'Esperar tres meses cada vez',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Besar a quien tienes delante veinte segundos',
          b: 'Abrazar a quien tienes detrás dos minutos',
          tone: ContentTone.piccante,
        ),
        (
          a: 'El sitio más arriesgado donde lo has intentado',
          b: 'La hora más absurda a la que lo hiciste',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Un finde en el balneario solo con alguien del grupo',
          b: 'Un crucero romántico con un desconocido',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Que te lean la mente durante un beso',
          b: 'Leer tú la mente de a quien besas',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Solo citas ardientes pero nunca una segunda',
          b: 'Solo citas dulces pero sin chispa',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Revelar cuántos presentes te parecen atractivos',
          b: 'Que cada uno te diga si te encuentra atractivo',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Hacer sexo escuchando tu canción favorita',
          b: 'Hacerlo en el silencio más absoluto',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Una noche con un modelo pero sin palabras',
          b: 'Una noche con un gracioso pero sin sexo',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Un morreo apasionado con quien tienes a la derecha',
          b: 'Un masaje sensual de quien tienes a la izquierda',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Qué parte del cuerpo te hace perder la cabeza',
          b: 'Hacérselo adivinar al grupo',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Seducir a quien te gusta escribiendo solo emojis',
          b: 'Seducirlo con un único audio embarazoso',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Hacer sexo solo a primera hora de la mañana',
          b: 'Hacer sexo solo de madrugada',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Un beso robado a tu jefe por una apuesta',
          b: 'Un beso robado al mejor amigo de tu pareja',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Confesar tu fantasía con un famoso',
          b: 'Escuchar la de quien tienes delante',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Solo relaciones a distancia pero pasionales',
          b: 'Solo relaciones cercanas pero tibias',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Que te hagan un chupetón bien visible',
          b: 'Hacerle uno tú a quien tienes al lado',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Decir cuántas veces diste el primer paso',
          b: 'Decir cuántas veces te echaste atrás',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Una noche de pasión pero la olvidas',
          b: 'Ninguna noche pero el recuerdo de un beso',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Besar a la persona más tímida del grupo',
          b: 'Besar a la más descarada del grupo',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Jugar un strip poker con los presentes',
          b: 'Jugar a verdad o reto solo picante',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Seducir a alguien solo con la mirada',
          b: 'Seducirlo solo con una frase',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Una cita caliente decidida por tu ex',
          b: 'Una cita caliente decidida por tu madre',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Un mordisco en el pezón',
          b: 'Pinzas en los pezones',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Una venda y sorpresas inesperadas',
          b: 'Saberlo todo de antemano',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Que te humillen con palabras en la cama',
          b: 'Humillarlo tú a él con palabras',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Un amo por una noche',
          b: 'Una esclava por una noche',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Obedecer cada orden durante una hora',
          b: 'Dar tú las órdenes durante una hora',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Sexo con una palabra de seguridad',
          b: 'Sexo sin límites pactados',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Un trío con una escort',
          b: 'Un trío con un amigo',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Que os grabe un tercero presente',
          b: 'Que solo os mire un tercero',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Sexo en un balcón a la vista',
          b: 'Sexo en el jardín de noche',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Un polvo rápido en la cocina',
          b: 'Una maratón en el dormitorio',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Hacerlo en la mesa del salón',
          b: 'Hacerlo contra la pared de la entrada',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Sexo nada más despertar cada mañana',
          b: 'Sexo solo a medianoche cada noche',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Probar el wax play',
          b: 'Probar el temperature play',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Un vibrador mientras él te mira',
          b: 'Sus manos mientras tú te miras',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Masturbarte delante de él',
          b: 'Verlo masturbarse para ti',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Un orgasmo solo con las palabras',
          b: 'Un orgasmo solo con un juguete',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Sexo con el semen en la cara',
          b: 'Sexo con el semen en el cuerpo',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Que acabe dentro de ti',
          b: 'Que acabe fuera',
          tone: ContentTone.cattivo,
        ),
        (a: 'Un creampie', b: 'Un facial', tone: ContentTone.cattivo),
        (
          a: 'Lamerlo después de que se ha corrido',
          b: 'Que te laman después de correrte',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Un acto a plena luz del día',
          b: 'Un acto solo a la luz de las velas',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Sexo con música a todo volumen',
          b: 'Sexo en total silencio',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Atarse las muñecas con la corbata',
          b: 'Atar los tobillos con las medias',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Una venda y auriculares insonorizados',
          b: 'Solo la venda en los ojos',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Dominar por completo durante un día',
          b: 'Someterte por completo durante un día',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Sexo en tienda de campaña',
          b: 'Sexo en la piscina de noche',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Un acto en el asiento trasero',
          b: 'Un acto sobre el capó',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Probar el pegging',
          b: 'Probar el rimming',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Un consolador con arnés para ella',
          b: 'Un anillo vibrador para él',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Que te la metan en la boca hasta el fondo',
          b: 'Metértela tú hasta el fondo',
          tone: ContentTone.cattivo,
        ),
        (a: 'Deep throat', b: 'Face sitting', tone: ContentTone.cattivo),
        (
          a: 'Sentarte en su cara',
          b: 'Hacerlo sentarse en la tuya',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Un sesenta y nueve infinito',
          b: 'Alternarse por turnos',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Sexo con un lubricante que da calor',
          b: 'Sexo con un gel de efecto frío',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Que te venden y adivinar los juguetes',
          b: 'Adivinar sus manos con los ojos vendados',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Un juego de rol de enfermera y paciente',
          b: 'Un juego de rol de policía y detenido',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Fingir ser desconocidos en un hotel',
          b: 'Fingir ser vecinos curiosos',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Sexo con la lencería arrancada del cuerpo',
          b: 'Sexo quedándoos casi vestidos',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Que te arranquen las bragas',
          b: 'Arrancarle los bóxers con los dientes',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Un orgasmo en menos de un minuto',
          b: 'Aguantar veinte minutos',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Contar los orgasmos en voz alta',
          b: 'Quedarte en absoluto silencio',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Un trío con tu crush',
          b: 'Un trío con su crush',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Ver porno juntos e imitarlo',
          b: 'Inventarlo todo sin referencias',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Recrear una escena porno famosa',
          b: 'Rodar vuestro propio vídeo casero',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Sexo con los tacones aún puestos',
          b: 'Sexo completamente desnudos',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Que te hagan llevar un huevo vibrador todo el día',
          b: 'Un plug toda la tarde',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Un masaje erótico completo',
          b: 'Un baño erótico entre dos',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Sexo con aceite perfumado por todas partes',
          b: 'Sexo cubiertos de espuma',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Que otra lo seduzca delante de ti',
          b: 'Seducir tú a otro delante de él',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Un strip poker que acaba en la cama',
          b: 'Un verdad o reto caliente hasta el final',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Besar a una mujer delante de él',
          b: 'Verlo besar a un hombre',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Un primer beso sáfico',
          b: 'Un primer beso gay',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Sexo con dos manos sobre ti',
          b: 'Sexo con dos bocas sobre ti',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Que te aprieten el cuello con suavidad',
          b: 'Apretar tú sus muñecas',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Un choking leve pactado',
          b: 'Un tirón de pelo decidido',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Sexo con el pelo tirado',
          b: 'Sexo con las uñas en la espalda',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Que te tomen por detrás frente al espejo',
          b: 'Tomarlo tú cabalgándolo frente al espejo',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Un orgasmo negado durante tres días',
          b: 'Tres orgasmos en una hora',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Que te miren mientras te desnudas por webcam',
          b: 'Ver a él desnudarse por webcam',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Un vibrador compartido por turnos',
          b: 'Dos juguetes a la vez',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Sexo atada en una silla',
          b: 'Sexo de pie contra la ventana',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Que te muerdan el labio hasta marcarlo',
          b: 'Morderle el cuello con ansia',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Un acto interrumpido y retomado varias veces',
          b: 'Un acto único sin pausas',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Probar la privación sensorial',
          b: 'Probar la sobrecarga sensorial',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Que te hagan cosquillas con los ojos vendados',
          b: 'Hacerle cosquillas tú a él inmovilizado',
          tone: ContentTone.cattivo,
        ),
      ];
}
