/// Coppie di "Preferisci" nelle lingue diverse dall'italiano.
///
/// Non sono traduzioni parola per parola dell'elenco italiano: alcune coppie
/// funzionano solo in un contesto (Ferragosto, carbonara) e sono state
/// sostituite con equivalenti locali.
class PreferisciPoolIntl {
  const PreferisciPoolIntl._();

  static const List<({String a, String b})> en = <({String a, String b})>[
    (a: 'Beach', b: 'Mountains'),
    (a: 'Pizza', b: 'Pasta'),
    (a: 'Dogs', b: 'Cats'),
    (a: 'Summer', b: 'Winter'),
    (a: 'Sweet', b: 'Savoury'),
    (a: 'Coffee', b: 'Tea'),
    (a: 'A film at the cinema', b: 'A series on the sofa'),
    (a: 'Early nights', b: 'Late mornings'),
    (a: 'Living in the city', b: 'Living in the countryside'),
    (a: 'Plane', b: 'Train'),
    (a: 'Netflix', b: 'YouTube'),
    (a: 'A plan for everything', b: 'Making it up as you go'),
    (a: 'Sweet breakfast', b: 'Full English'),
    (a: 'Sushi', b: 'Burgers'),
    (a: 'Dark chocolate', b: 'Milk chocolate'),
    (a: 'Beer', b: 'Wine'),
    (a: 'The gym', b: 'Running outside'),
    (a: 'Headphones on', b: 'Speakers up loud'),
    (a: 'Read the book', b: 'Watch the film'),
    (a: 'One concert', b: 'A whole festival'),
    (a: 'Saturday night out', b: 'Saturday night in'),
    (a: 'Boiling hot shower', b: 'Ice cold shower'),
    (a: 'Up at 6am', b: 'Bed at 3am'),
    (a: 'Cooking from scratch', b: 'Ordering in'),
    (a: 'Window seat', b: 'Aisle seat'),
    (a: 'Pineapple on pizza', b: 'Never in this life'),
    (a: 'Ketchup', b: 'Mayonnaise'),
    (a: 'A whole season tonight', b: 'One episode a week'),
    (a: 'Karaoke', b: 'Dancing'),
    (a: 'Camping', b: 'Hotel'),
    (a: 'Talking', b: 'Listening'),
    (a: 'Voice notes', b: 'Texts'),
    (a: 'An awkward truth', b: 'A comfortable lie'),
    (a: 'More money', b: 'More free time'),
    (a: 'Being famous', b: 'Being invisible'),
    (a: 'Travel to the past', b: 'Travel to the future'),
    (a: 'Fly', b: 'Be invisible'),
    (a: 'Read minds', b: 'See the future'),
    (a: 'No social media ever again', b: 'No films ever again'),
    (a: 'Lose your phone', b: 'Lose your keys'),
    (a: 'Always five minutes early', b: 'Always ten minutes late'),
    (a: 'Work from home', b: 'Work from the office'),
    (a: 'A nice but useless boss', b: 'A brilliant but rude boss'),
    (a: 'Big salary, boring job', b: 'Small salary, job you love'),
    (a: 'Comfy shoes', b: 'Good looking shoes'),
    (a: 'Dressed up', b: 'Dressed down'),
    (a: 'Barbecue with friends', b: 'Dinner at a restaurant'),
    (a: 'Sunrise', b: 'Sunset'),
    (a: 'A tattoo', b: 'A piercing'),
    (a: 'Same haircut forever', b: 'A new look every month'),
    (a: 'Reply straight away', b: 'Reply whenever'),
    (a: 'Old friends', b: 'New people'),
    (a: 'House party', b: 'Club night'),
    (a: 'Watching sport', b: 'Playing sport'),
    (a: 'Knowing how you die', b: 'Knowing when'),
  ];

  static const List<({String a, String b})> es = <({String a, String b})>[
    (a: 'Playa', b: 'Montaña'),
    (a: 'Pizza', b: 'Pasta'),
    (a: 'Perros', b: 'Gatos'),
    (a: 'Verano', b: 'Invierno'),
    (a: 'Dulce', b: 'Salado'),
    (a: 'Café', b: 'Té'),
    (a: 'Peli en el cine', b: 'Serie en el sofá'),
    (a: 'Acostarse pronto', b: 'Levantarse tarde'),
    (a: 'Vivir en la ciudad', b: 'Vivir en el pueblo'),
    (a: 'Avión', b: 'Tren'),
    (a: 'Churros', b: 'Tostada con tomate'),
    (a: 'Netflix', b: 'YouTube'),
    (a: 'Viaje organizado', b: 'Salir a la aventura'),
    (a: 'Sushi', b: 'Hamburguesa'),
    (a: 'Chocolate negro', b: 'Chocolate con leche'),
    (a: 'Cerveza', b: 'Vino'),
    (a: 'Gimnasio', b: 'Correr en la calle'),
    (a: 'Música con cascos', b: 'Música a todo volumen'),
    (a: 'Leer el libro', b: 'Ver la película'),
    (a: 'Concierto', b: 'Festival'),
    (a: 'Sábado de fiesta', b: 'Sábado de manta'),
    (a: 'Ducha ardiendo', b: 'Ducha helada'),
    (a: 'Despertarse a las 6', b: 'Acostarse a las 3'),
    (a: 'Cocinar', b: 'Pedir a domicilio'),
    (a: 'Ventanilla', b: 'Pasillo'),
    (a: 'Piña en la pizza', b: 'Jamás en la vida'),
    (a: 'Kétchup', b: 'Mayonesa'),
    (a: 'Temporada entera de golpe', b: 'Un capítulo por semana'),
    (a: 'Karaoke', b: 'Bailar'),
    (a: 'Camping', b: 'Hotel'),
    (a: 'Hablar', b: 'Escuchar'),
    (a: 'Audios', b: 'Mensajes escritos'),
    (a: 'Una verdad incómoda', b: 'Una mentira cómoda'),
    (a: 'Más dinero', b: 'Más tiempo libre'),
    (a: 'Ser famoso', b: 'Ser invisible'),
    (a: 'Viajar al pasado', b: 'Viajar al futuro'),
    (a: 'Volar', b: 'Ser invisible'),
    (a: 'Leer la mente', b: 'Ver el futuro'),
    (a: 'Nunca más redes', b: 'Nunca más cine'),
    (a: 'Perder el móvil', b: 'Perder las llaves'),
    (a: 'Llegar cinco minutos antes', b: 'Llegar diez tarde'),
    (a: 'Teletrabajo', b: 'Oficina'),
    (a: 'Jefe majo e inútil', b: 'Jefe borde y brillante'),
    (a: 'Sueldazo y trabajo aburrido', b: 'Poco sueldo y trabajo que amas'),
    (a: 'Zapatos cómodos', b: 'Zapatos bonitos'),
    (a: 'Ir elegante', b: 'Ir cómodo'),
    (a: 'Barbacoa con amigos', b: 'Cena en restaurante'),
    (a: 'Amanecer', b: 'Atardecer'),
    (a: 'Tatuaje', b: 'Piercing'),
    (a: 'Siempre el mismo corte', b: 'Cambiar de look cada mes'),
    (a: 'Responder al momento', b: 'Responder cuando te apetece'),
    (a: 'Los amigos de siempre', b: 'Conocer gente nueva'),
    (a: 'Fiesta en casa', b: 'Discoteca'),
    (a: 'Ver deporte', b: 'Hacer deporte'),
    (a: 'Saber cómo mueres', b: 'Saber cuándo'),
  ];

  static const List<({String a, String b})> fr = <({String a, String b})>[
    (a: 'La plage', b: 'La montagne'),
    (a: 'Pizza', b: 'Pâtes'),
    (a: 'Chiens', b: 'Chats'),
    (a: 'Été', b: 'Hiver'),
    (a: 'Sucré', b: 'Salé'),
    (a: 'Café', b: 'Thé'),
    (a: 'Un film au cinéma', b: 'Une série sur le canapé'),
    (a: 'Se coucher tôt', b: 'Se lever tard'),
    (a: 'Vivre en ville', b: 'Vivre à la campagne'),
    (a: 'Avion', b: 'Train'),
    (a: 'Croissant', b: 'Pain au chocolat'),
    (a: 'Netflix', b: 'YouTube'),
    (a: 'Voyage organisé', b: "Partir à l'aventure"),
    (a: 'Sushi', b: 'Burger'),
    (a: 'Chocolat noir', b: 'Chocolat au lait'),
    (a: 'Bière', b: 'Vin'),
    (a: 'La salle de sport', b: 'Courir dehors'),
    (a: 'Musique au casque', b: 'Musique à fond'),
    (a: 'Lire le livre', b: 'Voir le film'),
    (a: 'Un concert', b: 'Un festival'),
    (a: 'Samedi soir dehors', b: 'Samedi soir au calme'),
    (a: 'Douche brûlante', b: 'Douche glacée'),
    (a: 'Debout à 6h', b: 'Couché à 3h'),
    (a: 'Cuisiner', b: 'Se faire livrer'),
    (a: 'Côté hublot', b: 'Côté couloir'),
    (a: 'Ananas sur la pizza', b: 'Jamais de la vie'),
    (a: 'Ketchup', b: 'Mayonnaise'),
    (a: 'Une saison en une nuit', b: 'Un épisode par semaine'),
    (a: 'Karaoké', b: 'Danser'),
    (a: 'Camping', b: 'Hôtel'),
    (a: 'Parler', b: 'Écouter'),
    (a: 'Messages vocaux', b: 'Messages écrits'),
    (a: 'Une vérité gênante', b: 'Un mensonge confortable'),
    (a: "Plus d'argent", b: 'Plus de temps libre'),
    (a: 'Être célèbre', b: 'Être invisible'),
    (a: 'Voyager dans le passé', b: "Voyager dans le futur"),
    (a: 'Voler', b: 'Être invisible'),
    (a: 'Lire dans les pensées', b: "Voir l'avenir"),
    (a: 'Plus jamais de réseaux', b: 'Plus jamais de films'),
    (a: 'Perdre son téléphone', b: 'Perdre ses clés'),
    (a: "Toujours cinq minutes en avance", b: 'Toujours dix en retard'),
    (a: 'Télétravail', b: 'Le bureau'),
    (a: 'Un chef sympa et nul', b: 'Un chef doué et désagréable'),
    (a: 'Gros salaire, boulot ennuyeux', b: 'Petit salaire, boulot passion'),
    (a: 'Chaussures confortables', b: 'Chaussures qui claquent'),
    (a: 'Bien habillé', b: 'À l\'aise'),
    (a: 'Barbecue entre amis', b: 'Dîner au restaurant'),
    (a: 'Le lever du soleil', b: 'Le coucher du soleil'),
    (a: 'Un tatouage', b: 'Un piercing'),
    (a: 'La même coupe à vie', b: 'Changer de tête chaque mois'),
    (a: 'Répondre tout de suite', b: 'Répondre quand ça te chante'),
    (a: 'Les amis de toujours', b: 'Rencontrer du monde'),
    (a: 'Soirée à la maison', b: 'Boîte de nuit'),
    (a: 'Regarder le sport', b: 'Faire du sport'),
    (a: 'Savoir comment tu meurs', b: 'Savoir quand'),
  ];

  static const List<({String a, String b})> de = <({String a, String b})>[
    (a: 'Strand', b: 'Berge'),
    (a: 'Pizza', b: 'Pasta'),
    (a: 'Hunde', b: 'Katzen'),
    (a: 'Sommer', b: 'Winter'),
    (a: 'Süß', b: 'Herzhaft'),
    (a: 'Kaffee', b: 'Tee'),
    (a: 'Film im Kino', b: 'Serie auf dem Sofa'),
    (a: 'Früh ins Bett', b: 'Spät aufstehen'),
    (a: 'In der Stadt wohnen', b: 'Auf dem Land wohnen'),
    (a: 'Flugzeug', b: 'Zug'),
    (a: 'Brötchen', b: 'Croissant'),
    (a: 'Netflix', b: 'YouTube'),
    (a: 'Durchgeplanter Urlaub', b: 'Einfach losfahren'),
    (a: 'Sushi', b: 'Burger'),
    (a: 'Zartbitter', b: 'Vollmilch'),
    (a: 'Bier', b: 'Wein'),
    (a: 'Fitnessstudio', b: 'Draußen laufen'),
    (a: 'Musik über Kopfhörer', b: 'Musik in voller Lautstärke'),
    (a: 'Das Buch lesen', b: 'Den Film schauen'),
    (a: 'Ein Konzert', b: 'Ein Festival'),
    (a: 'Samstagabend raus', b: 'Samstagabend zu Hause'),
    (a: 'Kochend heiße Dusche', b: 'Eiskalte Dusche'),
    (a: 'Um 6 Uhr raus', b: 'Um 3 Uhr ins Bett'),
    (a: 'Selbst kochen', b: 'Essen bestellen'),
    (a: 'Fensterplatz', b: 'Gangplatz'),
    (a: 'Ananas auf Pizza', b: 'Niemals im Leben'),
    (a: 'Ketchup', b: 'Mayo'),
    (a: 'Ganze Staffel am Stück', b: 'Eine Folge pro Woche'),
    (a: 'Karaoke', b: 'Tanzen'),
    (a: 'Zelten', b: 'Hotel'),
    (a: 'Reden', b: 'Zuhören'),
    (a: 'Sprachnachrichten', b: 'Geschriebene Nachrichten'),
    (a: 'Eine unbequeme Wahrheit', b: 'Eine bequeme Lüge'),
    (a: 'Mehr Geld', b: 'Mehr Freizeit'),
    (a: 'Berühmt sein', b: 'Unsichtbar sein'),
    (a: 'In die Vergangenheit reisen', b: 'In die Zukunft reisen'),
    (a: 'Fliegen können', b: 'Unsichtbar sein'),
    (a: 'Gedanken lesen', b: 'Die Zukunft sehen'),
    (a: 'Nie wieder Social Media', b: 'Nie wieder Filme'),
    (a: 'Handy verlieren', b: 'Schlüssel verlieren'),
    (a: 'Immer fünf Minuten früher', b: 'Immer zehn zu spät'),
    (a: 'Homeoffice', b: 'Büro'),
    (a: 'Netter, unfähiger Chef', b: 'Unsympathischer, guter Chef'),
    (a: 'Viel Geld, langweiliger Job', b: 'Wenig Geld, Traumjob'),
    (a: 'Bequeme Schuhe', b: 'Schöne Schuhe'),
    (a: 'Schick angezogen', b: 'Bequem angezogen'),
    (a: 'Grillen mit Freunden', b: 'Essen im Restaurant'),
    (a: 'Sonnenaufgang', b: 'Sonnenuntergang'),
    (a: 'Tattoo', b: 'Piercing'),
    (a: 'Immer derselbe Schnitt', b: 'Jeden Monat neuer Look'),
    (a: 'Sofort antworten', b: 'Antworten, wenn du Lust hast'),
    (a: 'Die alten Freunde', b: 'Neue Leute kennenlernen'),
    (a: 'Hausparty', b: 'Club'),
    (a: 'Sport schauen', b: 'Sport machen'),
    (a: 'Wissen, wie du stirbst', b: 'Wissen, wann'),
  ];
}
