import '../content_tone.dart';

/// Coppie di "Preferisci" in francese: parità completa col mazzo italiano.
class PreferisciPoolFr {
  const PreferisciPoolFr._();

  static const List<({String a, String b})> pairs = <({String a, String b})>[
    (a: 'Savoir comment tu vas mourir', b: 'Savoir quand'),
    (a: 'Une vérité qui dérange', b: 'Un mensonge confortable'),
    (a: 'Plus d\'argent', b: 'Plus de temps libre'),
    (a: 'Être célèbre', b: 'Être invisible aux yeux des gens'),
    (a: 'Voyager dans le passé', b: 'Voyager dans le futur'),
    (a: 'Savoir voler', b: 'Être invisible'),
    (a: 'Lire les pensées', b: 'Prédire l\'avenir'),
    (a: 'Plus jamais de réseaux', b: 'Plus jamais de films'),
    (a: 'Perdre ton téléphone', b: 'Perdre tes clés de maison'),
    (a: 'Toujours 5 minutes en avance', b: 'Toujours 10 minutes en retard'),
    (a: 'Chef sympa mais incompétent', b: 'Chef odieux mais brillant'),
    (a: 'Gros salaire, boulot ennuyeux', b: 'Petit salaire, boulot passion'),
    (a: 'Mariage à 200 invités', b: 'Mariage à deux'),
    (a: 'Une semaine sans sortir', b: 'Sortir tous les soirs'),
    (a: 'Dormir 10 heures', b: 'Dormir 5 heures et être en forme'),
    (a: 'Refaire les vacances parfaites', b: 'Tester un endroit nouveau'),
    (a: 'Regarder ton compte chaque jour', b: 'Ne jamais le regarder'),
    (a: 'Superpouvoir inutile mais drôle', b: 'Superpouvoir utile mais chiant'),
    (a: 'Relire toujours le même livre', b: 'N\'en finir jamais aucun'),
    (a: 'Une vie sans musique', b: 'Une vie sans cinéma'),
    (a: 'Toujours savoir la vérité', b: 'Vivre heureux dans l\'illusion'),
    (a: 'Une année sabbatique', b: 'Partir à la retraite un an plus tôt'),
    (a: 'Parler toutes les langues', b: 'Jouer de tous les instruments'),
    (a: 'Ne jamais être gêné', b: 'Ne jamais avoir peur'),
    (a: 'Revivre ton plus beau jour', b: 'Effacer le pire'),
    (a: 'Vivre ensemble après un mois', b: 'Vivre ensemble après des années'),
    (a: 'Des enfants tôt', b: 'Des enfants tard'),
    (a: 'Vacances planifiées au détail', b: 'Partir à l\'aventure'),
    (a: 'Une saison en une nuit', b: 'Un épisode par semaine'),
    (a: 'Batterie toujours à 1%', b: 'Internet ultra lent'),
    (
      a: 'Vêtements toujours un peu mouillés',
      b: 'Un caillou dans la chaussure à vie',
    ),
    (a: 'Toujours dire ce que tu penses', b: 'Ne plus pouvoir parler'),
    (a: 'Pas de chauffage en hiver', b: 'Pas de clim en été'),
    (a: 'Le hoquet à vie', b: 'Éternuer toutes les deux minutes'),
    (a: 'Ton plat préféré à chaque repas', b: 'Plus jamais ton plat préféré'),
    (a: 'Ne plus avoir besoin de dormir', b: 'Ne plus avoir besoin de manger'),
    (a: 'Riche mais sans amis', b: 'Fauché mais adoré'),
    (a: 'Plus jamais de loyer', b: 'Salaire doublé'),
    (a: 'Le plus drôle de la salle', b: 'Le plus intelligent de la salle'),
    (a: 'Mémoire photographique', b: 'Oublier chaque humiliation'),
    (a: 'Plus jamais de files d\'attente', b: 'Plus jamais d\'embouteillages'),
    (a: 'Sourcils rasés pendant un an', b: 'Cheveux vert fluo pendant un an'),
    (a: 'Perdre l\'odorat', b: 'Perdre le goût'),
    (a: 'Une voix de dessin animé', b: 'Un rire qui gêne tout le monde'),
    (a: 'Historique visible par tes parents', b: 'Messages lus par ton patron'),
    (a: 'Roter à la fin de chaque phrase', b: 'Rire comme une chèvre'),
    (
      a: 'Utiliser la brosse à dents d\'un inconnu',
      b: 'Boire dans son verre déjà utilisé',
    ),
    (a: 'Mains toujours moites', b: 'Lèvres toujours gercées'),
    (a: 'Sortir avec ton ex', b: 'Avec l\'ex de ton meilleur ami'),
    (a: 'Des pets bruyants mais sans odeur', b: 'Silencieux mais mortels'),
    (a: 'Oublier qui tu es', b: 'Être oublié de tous'),
    (a: 'Perdre tout ton argent', b: 'Perdre tous tes souvenirs'),
    (a: 'Partenaire riche mais ennuyeux', b: 'Partenaire fauché mais hilarant'),
    (
      a: 'Une heure en ascenseur avec ton ex',
      b: 'Une heure en ascenseur avec ton chef',
    ),
    (a: 'Anniversaire oublié par tous', b: 'Fête surprise embarrassante'),
    (a: 'Ton secret révélé à tous', b: 'Connaître les secrets de tous'),
    (a: 'Célèbre mais détesté', b: 'Inconnu mais aimé'),
    (a: 'Ne plus jamais rire', b: 'Ne plus jamais pleurer'),
    (a: 'Retourner au lycée un an', b: 'Repasser le bac chaque année'),
    (a: 'Vivre dans un film d\'horreur', b: 'Vivre dans une comédie musicale'),
    (a: 'Des pieds à la place des mains', b: 'Des mains à la place des pieds'),
    (
      a: 'Un canard grand comme un cheval',
      b: 'Cent chevaux grands comme des canards',
    ),
    (a: 'Vivre sous l\'eau', b: 'Vivre dans l\'espace'),
    (
      a: 'Poursuivi à vie par un escargot tueur',
      b: 'Un clown qui te fixe chaque nuit',
    ),
    (a: 'Parler aux animaux', b: 'Contrôler la météo'),
    (a: 'Danser dès que la musique démarre', b: 'Pleurer quand quelqu\'un rit'),
    (
      a: 'Chaque matin dans un autre pays',
      b: 'Ne plus jamais quitter ta ville',
    ),
    (a: 'Vivre dans un jeu vidéo', b: 'Vivre dans un dessin animé'),
    (a: 'Une touche "pause" pour la vie', b: 'Une touche "retour" pour la vie'),
    (a: 'Téléportation mais sans chaussures', b: 'Voler au pas d\'un piéton'),
    (a: 'Vivre 1000 ans', b: 'Dix vies de 100 ans'),
    (a: 'Une pluie de tacos', b: 'Une neige de glace'),
    (a: 'Roi du monde pour un jour', b: 'Personne normale pour toujours'),
    (
      a: 'Tout savoir sans rien ressentir',
      b: 'Tout ressentir sans rien comprendre',
    ),
    (a: 'Effacer un regret', b: 'T\'assurer un succès futur'),
    (a: 'Toujours affamé', b: 'Toujours endormi'),
    (
      a: 'Une queue qui remue quand tu es content',
      b: 'Des oreilles qui tombent si tu es triste',
    ),
    (a: 'Renoncer au café pour toujours', b: 'Renoncer au chocolat'),
    (
      a: 'Un nez qui pousse quand tu mens',
      b: 'Des cheveux qui changent avec l\'humeur',
    ),
    (a: 'Trouver l\'amour de ta vie', b: 'Trouver le job de tes rêves'),
    (a: 'Très riche mais toujours triste', b: 'Fauché mais toujours heureux'),
    (a: 'Un million tout de suite', b: '3 000 euros par mois à vie'),
    (a: 'Sauver ton chien', b: 'Sauver un inconnu'),
    (a: 'Ne jamais pouvoir mentir', b: 'Croire à chaque mensonge'),
    (a: 'Toujours raison mais tout seul', b: 'Avoir tort mais bien accompagné'),
    (a: 'Génie incompris', b: 'Simplet heureux'),
    (a: 'La même tenue chaque jour', b: 'Ne jamais répéter une tenue'),
    (a: 'Chanter tout ce que tu dis', b: 'Marcher seulement à reculons'),
    (a: 'Wifi gratuit partout à vie', b: 'Vols gratuits à vie'),
    (a: 'Manger seulement brûlant', b: 'Manger seulement glacé'),
    (a: 'Plus jamais de pizza', b: 'Plus jamais de pâtes'),
    (a: 'Plus jamais d\'apéros', b: 'Plus jamais de livraison'),
    (a: 'Vie longue pleine de regrets', b: 'Vie courte sans aucun regret'),
    (
      a: 'Aimer sans être aimé en retour',
      b: 'Être aimé de qui tu n\'aimes pas',
    ),
    (a: 'Ton partenaire lit tes pensées', b: 'Tu lis les siennes'),
    (a: 'Partenaire choisi par tes amis', b: 'Partenaire choisi par un algo'),
    (
      a: 'Toujours démasquer les menteurs',
      b: 'Ne jamais être démasqué en mentant',
    ),
    (a: 'Revivre tes 18 ans pour toujours', b: 'Sauter directement à 40 ans'),
    (
      a: 'Dormir toujours chez les autres',
      b: 'Avoir toujours des invités chez toi',
    ),
    (
      a: 'Le concert de ton groupe mais seul',
      b: 'Un festival entre amis, musique nulle',
    ),
    (
      a: 'Un karaoké faux devant tout le monde',
      b: 'Danser seul une heure en piste',
    ),
    (a: 'Perdre toutes tes photos', b: 'Perdre toutes tes conversations'),
    (a: 'Éternuer des confettis', b: 'Roter des bulles de savon'),
    (a: 'Avoir quatre bras', b: 'Avoir quatre jambes'),
    (a: 'Mesurer 2 m 20', b: 'Mesurer 1 m 20'),
    (a: 'Vivre sans été', b: 'Vivre sans hiver'),
    (a: 'Sauver cinq inconnus', b: 'Sauver ton meilleur ami'),
    (
      a: 'Un million mais plus de smartphone',
      b: 'Zéro argent mais ton téléphone',
    ),
    (
      a: 'Le job de tes rêves à l\'étranger',
      b: 'Un job ennuyeux près de tes amis',
    ),
    (a: 'Avoir 25 ans pour toujours', b: 'Vieillir avec tes amis'),
    (a: 'La maison de rêve au milieu de rien', b: 'Un studio en plein centre'),
    (
      a: 'Savoir ce qu\'on dit derrière ton dos',
      b: 'Vivre tranquille sans le savoir',
    ),
    (a: 'Chaque repas cuisiné par un chef', b: 'Un chauffeur perso à vie'),
    (
      a: 'Commenter à voix haute tout ce que tu fais',
      b: 'Entendre la voix qui narre ta vie',
    ),
    (a: 'Marcher sur des Lego chaque matin', b: 'Douche glacée chaque matin'),
    (a: 'Un moustique chaque nuit', b: 'Une mouche à chaque repas'),
    (a: 'Correcteur auto fou à vie', b: 'Plus jamais d\'emojis'),
    (
      a: 'Appels toujours en haut-parleur',
      b: 'Écran toujours visible par tous',
    ),
    (
      a: 'Ton chien parle mais te critique',
      b: 'Ton miroir te flatte faussement',
    ),
    (a: 'Un million pour toi seul', b: 'Cent mille chacun pour le groupe'),
    (a: 'Toujours sous-estimé', b: 'Toujours surestimé'),
    (
      a: 'Redécouvrir ta série préférée',
      b: 'Voir chaque fin en avant-première',
    ),
    (a: 'Parler seulement en criant', b: 'Parler seulement en chuchotant'),
    (a: 'Rire dans les moments sérieux', b: 'Pleurer à chaque comédie'),
    (
      a: 'Manger toujours avec les mains',
      b: 'Tout manger à la petite cuillère',
    ),
    (a: 'Tes rêves projetés à tes amis', b: 'Tes amis lisent ton journal'),
    (a: 'Le seul célibataire du groupe', b: 'Le premier du groupe à te marier'),
    (a: 'Renaître dans les années 80', b: 'Naître en 2050'),
    (
      a: 'Restos gratuits mais toujours seul',
      b: 'Payer toujours mais bien accompagné',
    ),
    (a: 'Viral pour une honte épique', b: 'Jamais plus de 10 likes'),
    (
      a: 'Boire seulement de l\'eau à vie',
      b: 'Plus jamais d\'eau, que du soda',
    ),
    (a: 'Un seul genre musical à vie', b: 'Une seule appli sur ton téléphone'),
    (a: 'En smoking à la plage', b: 'En maillot à un mariage'),
    (a: 'Cuisiner comme un chef étoilé', b: 'Une maison qui se nettoie seule'),
    (a: 'Long vol à côté d\'un bavard', b: 'Long vol à côté d\'un bébé'),
    (a: 'Petit-déj salé pour toujours', b: 'Dîner sucré pour toujours'),
    (a: 'Vivre sans miroirs', b: 'Vivre sans horloges'),
    (a: 'Revivre le même lundi', b: 'Sauter tous les vendredis'),
    (a: 'Parler avec les plantes', b: 'Comprendre les bébés'),
    (a: 'Toujours gagner aux cartes', b: 'Toujours trouver une place'),
    (a: 'Été à 40 degrés sans mer', b: 'Hiver glacial sans neige'),
    (a: 'Que des films mal doublés', b: 'Que des sous-titres décalés'),
    (a: 'Café gratuit à vie', b: 'Glaces gratuites à vie'),
    (a: 'Déménager chaque année', b: 'La même maison pour toujours'),
    (
      a: 'Sonnerie gênante pour toujours',
      b: 'Fond d\'écran gênant pour toujours',
    ),
    (a: 'Être un mème célèbre', b: 'Avoir un sosie célèbre'),
    (
      a: 'Danser la macarena pour dire bonjour',
      b: 'Saluer tout le monde en s\'inclinant',
    ),
    (a: 'Du Nutella sans pain', b: 'Du pain sans Nutella'),
    (
      a: 'Week-end infini mais toujours pluie',
      b: 'Que des lundis mais toujours soleil',
    ),
    (a: 'Un seul plat mais parfait', b: 'Tout cuisiner de façon moyenne'),
  ];

  /// Dilemmi da modalità Hot: parità completa col mazzo italiano.
  static const List<({String a, String b, String tone})> hot =
      <({String a, String b, String tone})>[
        (
          a: 'Sortir tout nu pendant une minute',
          b: 'Embrasser quelqu\'un de ce groupe',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Passer la nuit avec quelqu\'un du groupe',
          b: 'Une nuit avec un de tes anciens profs',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Montrer ta galerie photo au groupe',
          b: 'Faire lire tes messages à voix haute',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Un an sans sexe',
          b: 'Un an sans sortir le soir',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Dire ton body count au groupe',
          b: 'Montrer ta dernière recherche',
          tone: ContentTone.piccante,
        ),
        (
          a: 'L\'amour sans le sexe',
          b: 'Le sexe sans l\'amour',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Partenaire beau mais nul au lit',
          b: 'Partenaire ordinaire mais phénoménal',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Une nuit avec ton ex',
          b: 'Une nuit avec un inconnu',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Surprendre tes parents en pleine action',
          b: 'Te faire surprendre par tes parents',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Dire à tout le monde qui te plaît maintenant',
          b: 'Ne plus jamais parler à celui qui te plaît',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Embrasser les yeux fermés quelqu\'un du groupe',
          b: 'Embrasser ton ex devant tout le monde',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Ne plus jamais pouvoir embrasser',
          b: 'Ne plus jamais pouvoir faire de câlins',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Savoir avec qui ton partenaire te tromperait',
          b: 'Ne jamais le savoir',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Que des rendez-vous à l\'aveugle pendant un an',
          b: 'Que des sorties choisies par ta mère',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Revoir en vidéo ton premier baiser',
          b: 'Que tout le groupe le revoie',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Gémir chaque fois que tu t\'assois',
          b: 'Crier le nom de ton ex à chaque toast',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Envoyer un nude à ton ex par erreur',
          b: 'L\'envoyer dans le groupe familial',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Sexto avec ton patron par erreur',
          b: 'Appeler ton partenaire par le nom de ton ex',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Une nuit avec une célébrité',
          b: 'Un mois de sexe avec ton ex',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Faire l\'amour seulement dans le noir total',
          b: 'Seulement avec la lumière toujours allumée',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Dire ton fantasme le plus bizarre',
          b: 'Entendre celui de la personne à ta droite',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Sex friends avec ton meilleur ami',
          b: 'Plus jamais de sexe pendant un an',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Un ex qui embrasse comme un dieu',
          b: 'Un nouveau à tout apprendre',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Te faire déshabiller du regard au bar',
          b: 'Ne plus jamais être remarqué',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Raconter ton pire rendez-vous',
          b: 'Revivre ta gaffe la plus hot',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Faire toujours le premier pas',
          b: 'Attendre toujours que l\'autre le fasse',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Un plan à trois avec des inconnus',
          b: 'Un plan à trois avec des amis',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Surprendre ton coloc en pleine action',
          b: 'Te faire surprendre par ton coloc',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Dire combien de fois par jour tu y penses',
          b: 'Dire quand tu l\'as fait la dernière fois',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Partenaire super jaloux mais bouillant',
          b: 'Partenaire tranquille mais fainéant au lit',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Embrasser le premier qui passe la porte',
          b: 'Embrasser le dernier qui t\'a écrit',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Nuit de passion sans baisers',
          b: 'Des baisers à l\'infini mais rien d\'autre',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Oublier ta première fois',
          b: 'T\'en souvenir chaque jour',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Dire l\'endroit le plus fou où tu l\'as fait',
          b: 'Dire l\'endroit où tu voudrais le faire',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Un flirt avec ton coach sportif',
          b: 'Un flirt avec ton médecin',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Que des coups d\'un soir pendant un an',
          b: 'Que des relations sérieuses à vie',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Recoucher avec ton ex de temps en temps',
          b: 'Rompre pour toujours mais avec des regrets',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Une galoche avec la personne à ta gauche',
          b: 'Un slow sensuel avec la personne à ta droite',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Dormir nu avec un ami',
          b: 'Prendre une douche en maillot avec ton ex',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Recevoir un nude non désiré de ton patron',
          b: 'En envoyer un à ton patron par erreur',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Du sexe à couper le souffle une fois par mois',
          b: 'Du sexe médiocre tous les jours',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Savoir ce que l\'autre pense au lit',
          b: 'Qu\'il entende chacune de tes pensées au lit',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Un week-end avec ton crush secret',
          b: 'Un mois avec ton premier amour',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Petit-déjeuner au lit après la première nuit',
          b: 'Disparaître avant l\'aube',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Dire ton point faible au lit',
          b: 'Le mimer devant le groupe',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Te tatouer le nom de ton ex',
          b: 'Crier son nom au mauvais moment',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Un match avec ton ex sur une appli',
          b: 'Un match avec ton patron sur une appli',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Ton partenaire connaît chacun de tes fantasmes',
          b: 'Tu connais chacun des siens',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Un strip-tease improvisé maintenant',
          b: 'Un récit coquin de ton été',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Embrasser quelqu\'un du groupe de ton choix',
          b: 'En embrasser un choisi par le groupe',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Une histoire secrète ultra passionnée',
          b: 'Une histoire officielle mais tiède',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Faire l\'amour seulement en été',
          b: 'Faire l\'amour seulement en hiver',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Oublier toutes tes folles nuits',
          b: 'Te souvenir même de celles à oublier',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Un audio hot envoyé à la mauvaise personne',
          b: 'En recevoir un de ton patron',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Faire lire tes messages avec ton ex',
          b: 'Faire voir tes photos avec ton ex',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Coup de foudre ce soir',
          b: 'Aventure d\'un soir ce soir',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Dire le nom de ton crush au groupe',
          b: 'Le faire deviner au groupe',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Danser un slow avec ton ex ce soir',
          b: 'Karaoké romantique avec quelqu\'un du groupe',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Draguer un inconnu maintenant',
          b: 'Donner ton numéro au premier qui le demande',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Un massage par quelqu\'un du groupe',
          b: 'En faire un à quelqu\'un du groupe',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Interdit de flirter pendant un an',
          b: 'Obligé de flirter avec n\'importe qui',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Une nuit avec ton idole de la musique',
          b: 'Un week-end avec ton acteur préféré',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Avouer un rêve hot sur une personne présente',
          b: 'Qu\'une personne présente en avoue un sur toi',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Silence total au lit',
          b: 'Commentaire en direct complet au lit',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Un derrière de rêve',
          b: 'Un décolleté à applaudir',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Ton ex devient super célèbre',
          b: 'Ton ex devient ton patron',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Dire ce qui t\'excite le plus',
          b: 'Dire ce qui te coupe l\'envie tout de suite',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Une aventure d\'été jamais avouée',
          b: 'Un amour à distance sans fin',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Deux personnes présentes te font du gringue',
          b: 'Faire du gringue à deux personnes présentes à la fois',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Voir ton ex avec quelqu\'un de plus beau que toi',
          b: 'Qu\'il te voie avec quelqu\'un de moins bien que lui',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Des baisers avec morsure',
          b: 'Des baisers chastes pour toujours',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Dormir enlacés sans sexe',
          b: 'Du sexe sans jamais dormir ensemble',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Faire l\'amour avec la musique à fond',
          b: 'Avec le journal télévisé en fond sonore',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Révéler ton nombre d\'ex',
          b: 'Révéler qui était le meilleur',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Draguer le serveur ce soir',
          b: 'Lui laisser ton numéro sur l\'addition',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Une première fois gênante mais tendre',
          b: 'Parfaite mais avec la mauvaise personne',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Un tatouage choisi par le groupe',
          b: 'Un piercing choisi par le groupe',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Un baiser de 30 secondes avec une personne présente',
          b: 'Dix baisers rapides avec dix inconnus',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Savoir qui du groupe rêve de toi la nuit',
          b: 'Savoir qui ne t\'embrasserait jamais',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Du sexe sous la tente dans un camping bondé',
          b: 'À l\'hôtel avec des murs en papier',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Des vacances réservées aux célibataires',
          b: 'Des vacances réservées aux couples',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Du sexe anal à chaque fois',
          b: 'Plus jamais de sexe pendant un an',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Être dominé',
          b: 'Être dominant',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Faire l\'amour avec deux personnes en même temps',
          b: 'T\'en passer pendant six mois',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Te faire filmer pendant que tu le fais',
          b: 'Ne plus jamais le faire',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Lécher partout',
          b: 'Être léché partout',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Avaler',
          b: 'Cracher',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Te faire bander les yeux et ligoter',
          b: 'Être celui qui bande les yeux et ligote',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Du sexe sauvage avec un inconnu',
          b: 'Du sexe médiocre avec le partenaire idéal',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Le lui faire avaler',
          b: 'Le lui faire cracher sur toi',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Un plan à trois avec des inconnus',
          b: 'Avec deux amis proches d\'ici',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Que du sexe oral pendant un an',
          b: 'Plus jamais de sexe oral',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Recevoir toujours le sexe oral',
          b: 'Le faire toujours toi',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Un oral qui finit dans la bouche',
          b: 'Un oral qui finit sur le visage',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Lécher jusqu\'à l\'orgasme',
          b: 'Être léchée jusqu\'à l\'orgasme',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Une pipe de 30 minutes',
          b: 'Jouir en 30 secondes',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Un plan à trois avec deux inconnus',
          b: 'Regarder ton partenaire avec un autre',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Un plan à trois avec deux hommes',
          b: 'Un plan à trois avec deux femmes',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Une orgie à huit',
          b: 'Du sexe en solo pendant un an',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Regarder ton partenaire en baiser un autre',
          b: 'Te faire regarder pendant que tu baises',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Un inconnu te regarde jouir',
          b: 'Tu regardes un inconnu jouir',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Te faire ligoter et bander les yeux',
          b: 'Ligoter et bander les yeux toi-même',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Être fouettée doucement',
          b: 'Fouetter toi-même ton partenaire',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Soumise pour une nuit',
          b: 'Dominatrice pour une nuit',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Un collier et une laisse sur toi',
          b: 'Les mettre toi-même à ton partenaire',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Une fessée jusqu\'à laisser la marque',
          b: 'Donner la fessée toi-même jusqu\'à la marque',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Attachée au lit toute la nuit',
          b: 'Attacher toi-même ton partenaire au lit',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Les yeux bandés et à la merci du partenaire',
          b: 'Bander les yeux toi-même et commander',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Un vibromasseur pendant une heure sans s\'arrêter',
          b: 'Aucun orgasme pendant un mois',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Orgasme refusé pendant des jours',
          b: 'Orgasmes forcés à répétition',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Un plug porté toute la journée',
          b: 'Un vibromasseur en public',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Essayer tous les sextoys du magasin',
          b: 'Seulement les mains pour toujours',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Un gode énorme',
          b: 'Un vibromasseur petit mais constant',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'De vraies menottes aux poignets',
          b: 'Des cordes de soie sur le corps',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Du sexe dans les toilettes d\'un bar',
          b: 'Du sexe dans une ruelle sombre',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Le faire sur la plage la nuit',
          b: 'Le faire dans l\'ascenseur',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Du sexe en voiture sur un parking',
          b: 'Du sexe sur un toit la nuit',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Risquer de se faire surprendre au bureau',
          b: 'Le faire dans une cabine d\'essayage',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Du sexe dans un train en marche',
          b: 'Du sexe sous une table bondée',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Une vidéo hot qui circule',
          b: 'Tes chats hot qui circulent',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Tes photos nues sur son téléphone',
          b: 'Une de tes vidéos intimes sauvegardée',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Enregistrer pendant que vous le faites',
          b: 'Te photographier nue pour lui',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Un nude envoyé par erreur au patron',
          b: 'Un nude vu par tes amis',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Faire l\'amour devant une webcam',
          b: 'Faire l\'amour avec la lumière toujours allumée',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Du sexe brutal et sans pitié',
          b: 'Du sexe lent toute la nuit',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Jouir cinq fois de suite',
          b: 'Un seul orgasme très long',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Simuler toujours l\'orgasme',
          b: 'Ne plus jamais jouir',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Un orgasme toutes les heures pendant un jour',
          b: 'Aucun orgasme pendant un an',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Squirter devant lui',
          b: 'Le voir jouir sur ton corps',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Sexe anal',
          b: 'Double pénétration',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Essayer l\'anal pour la première fois',
          b: 'Ne jamais l\'essayer',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Draguer un inconnu ce soir',
          b: 'Un ex pour une dernière nuit',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Une nuit avec ta star de cinéma',
          b: 'Une nuit avec ton meilleur ex',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Du sexe avec le meilleur ami de lui',
          b: 'Du sexe avec la meilleure amie d\'elle',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Échangisme avec des amis',
          b: 'Échangisme avec de parfaits inconnus',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Embrasser tout le monde à une orgie',
          b: 'Ne choisir qu\'une seule personne',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Un massage qui finit au lit',
          b: 'Une lap dance privée',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Un strip-tease devant le groupe',
          b: 'Danser nue autour d\'une barre',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Lécher la crème sur son corps',
          b: 'Lui faire lécher le chocolat sur toi',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Du sexe couverts d\'huile',
          b: 'Du sexe sous la douche brûlante',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Un fétichisme des pieds assouvi',
          b: 'Un fétichisme des fesses assouvi',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Te faire sucer les orteils',
          b: 'Sucer les siens toi-même',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Ne porter que de la lingerie au restaurant',
          b: 'Aucun sous-vêtement au restaurant',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Un corset serré toute la soirée',
          b: 'Des talons aiguilles et rien d\'autre',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Du sexe avec un masque sur le visage',
          b: 'Du sexe dans le noir total',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Dire tes fantasmes à voix haute',
          b: 'En réaliser un au hasard',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Un jeu de rôle prof et élève',
          b: 'Un jeu de rôle patron et secrétaire',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Faire semblant d\'être deux inconnus dans un bar',
          b: 'Faire semblant d\'être des ex qui se retrouvent',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Du sexe pendant que les autres dorment à côté',
          b: 'Du sexe en criant sans retenue',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Te faire dire des cochonneries à l\'oreille',
          b: 'Les lui dire toi-même',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Sexto toute la journée de travail',
          b: 'Des photos hot toutes les heures',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Une pipe pendant qu\'il conduit',
          b: 'Un doigté au cinéma',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Le séduire du regard pendant une heure',
          b: 'Lui sauter dessus tout de suite',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Le chevaucher jusqu\'à l\'épuiser',
          b: 'Te laisser prendre par derrière',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Du sexe en trois positions d\'affilée',
          b: 'Une heure dans la même position',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Le faire jouir seulement avec les mains',
          b: 'Seulement avec la bouche',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Une pipe les yeux bandés',
          b: 'Un rapport les yeux bandés',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'De la glace sur la peau nue',
          b: 'De la cire chaude sur le corps',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Mordre jusqu\'à laisser des marques',
          b: 'Griffer le dos à fond',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Des suçons visibles dans le cou',
          b: 'Des marques de morsures à l\'intérieur des cuisses',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Du sexe avec un seul partenaire pour toujours',
          b: 'Un partenaire différent chaque mois',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Voir ton partenaire nu avec un autre',
          b: 'Ne jamais savoir ce qu\'il fait',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Un trio programmé dans les moindres détails',
          b: 'Un trio totalement improvisé',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Te faire déshabiller lentement par lui',
          b: 'Le déshabiller toi-même avec les dents',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Du sexe avec lui en uniforme',
          b: 'Du sexe avec toi en uniforme',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'De longs préliminaires sans pénétration',
          b: 'Pénétration tout de suite sans préliminaires',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Edging pendant une heure',
          b: 'Orgasme immédiat et terminé',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Te faire toucher dans un bar bondé',
          b: 'Le toucher toi-même sous la table',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Un doigt en plus pendant le rapport',
          b: 'Une langue en plus pendant le rapport',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Du sexe devant le miroir',
          b: 'Du sexe filmé au téléphone',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Porter un plug au dîner chez les beaux-parents',
          b: 'Un vibromasseur commandé par lui',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Vibromasseur télécommandé dans le métro',
          b: 'Vibromasseur télécommandé au restaurant',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Une longue séance de spanking',
          b: 'Une longue séance de bondage',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Suspendue avec des cordes japonaises',
          b: 'Immobilisée avec du ruban adhésif',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Un massage intégral par quelqu\'un du groupe',
          b: 'Une douche avec quelqu\'un du groupe',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Embrasser le collègue qui te plaît depuis des mois',
          b: 'T\'entendre dire qu\'il partage mais qu\'il est en couple',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Du sexe lent toute la nuit',
          b: 'Du sexe rapide et fougueux en une minute',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Dire ton mot de passe à voix haute',
          b: 'Mimer ta position préférée',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Un flirt brûlant avec le meilleur ami de ton ex',
          b: 'Un flirt brûlant avec ton voisin',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Faire l\'amour seulement dans des lieux publics',
          b: 'Faire l\'amour seulement porte ouverte',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Un week-end de sexe pur sans parler',
          b: 'Un week-end de câlins seulement sans sexe',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Recevoir une lap dance de la personne à ta droite',
          b: 'En faire une à la personne à ta gauche',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Avouer à quelle personne présente tu ferais la cour',
          b: 'Te faire choisir un prétendant par le groupe',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Tout essayer en une nuit avec l\'inconnu',
          b: 'Rester chaste un an avec le grand amour',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Un baiser à la française avec ton premier amour',
          b: 'Une étreinte sans fin avec ton dernier crush',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Embrasser toutes les personnes présentes à tour de rôle',
          b: 'N\'en embrasser qu\'une seule pendant dix minutes',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Dire combien de temps tu tiens en moyenne au lit',
          b: 'Dire ton record personnel',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Une rencontre interdite avec ton prof de danse',
          b: 'Une rencontre interdite avec le barman d\'en bas',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Séduire un inconnu en dix minutes',
          b: 'Te faire séduire sans dire un mot',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Que de la lingerie provocante pendant un mois',
          b: 'Que des pyjamas informes pendant un an',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Faire l\'amour avec le même partenaire pour toujours',
          b: 'Un partenaire différent chaque semaine sans amour',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Te faire déshabiller lentement par la personne en face',
          b: 'Déshabiller toi-même la personne à côté',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Dire le fantasme que tu n\'as jamais réalisé',
          b: 'Le réaliser ce soir avec une personne présente',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Un baiser passionné sous la pluie',
          b: 'Une nuit de feu devant la cheminée',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Du sexe avec la plus belle personne jamais vue',
          b: 'Du sexe inoubliable avec celui que tu aimes vraiment',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Te faire mordre le cou par la personne à ta droite',
          b: 'Mordre toi-même le cou de la personne à ta gauche',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Combien de fois tu as pensé à une personne présente',
          b: 'Qu\'une personne présente avoue combien de fois elle pense à toi',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Un an d\'aventures sans lendemain',
          b: 'Un an d\'attente pour la bonne personne',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Embrasser quelqu\'un les yeux bandés et deviner qui c\'est',
          b: 'Te faire embrasser et faire deviner à tous',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Du sexe débridé mais sans jamais se revoir',
          b: 'Une attente infinie mais ensuite pour toujours',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Une danse provocante devant tout le groupe',
          b: 'Un baiser surprise choisi par le groupe',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Prendre une douche avec ton ex',
          b: 'Prendre un bain avec ton crush',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Dire qui du groupe tu embrasserais dans le noir',
          b: 'Dire qui du groupe tu n\'embrasserais jamais',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Un massage des pieds par un inconnu sexy',
          b: 'Un massage du dos par ton ex',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Faire l\'amour seulement dans le noir avec des bougies',
          b: 'Faire l\'amour seulement devant le miroir',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Un flirt secret avec ton maître-nageur',
          b: 'Un flirt secret avec ton tatoueur',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Révéler l\'objet le plus osé que tu possèdes',
          b: 'Le montrer au groupe',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Passer la nuit avec ton crush du lycée',
          b: 'Passer la nuit avec ton crush du moment',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Que des baisers lents pendant un mois',
          b: 'Que des nuits de passion mais aucun baiser',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Te faire murmurer des choses brûlantes à l\'oreille',
          b: 'Les murmurer toi-même à la personne à côté',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Dire le surnom hot que tu donnes à ton partenaire',
          b: 'Dire celui que ton partenaire te donne',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Une nuit avec celui qui t\'a rejeté il y a des années',
          b: 'Une nuit avec celui qui te désire depuis toujours',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Faire l\'amour au premier rendez-vous à chaque fois',
          b: 'Attendre trois mois à chaque fois',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Embrasser la personne en face pendant vingt secondes',
          b: 'Enlacer la personne derrière toi pendant deux minutes',
          tone: ContentTone.piccante,
        ),
        (
          a: 'L\'endroit le plus risqué où tu as tenté ta chance',
          b: 'L\'heure la plus folle où tu l\'as fait',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Un week-end au spa seul avec quelqu\'un du groupe',
          b: 'Une croisière romantique avec un inconnu',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Te faire lire dans les pensées pendant un baiser',
          b: 'Lire toi-même les pensées de celui que tu embrasses',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Que des rendez-vous brûlants mais jamais un deuxième',
          b: 'Que des rendez-vous doux mais sans étincelle',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Révéler combien de personnes présentes tu trouverais attirantes',
          b: 'Te faire dire par chacun s\'il te trouve attirant',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Faire l\'amour en écoutant ta chanson préférée',
          b: 'Le faire dans le silence le plus total',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Une nuit avec un mannequin mais sans un mot',
          b: 'Une nuit avec un boute-en-train mais sans sexe',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Une galoche passionnée avec la personne à ta droite',
          b: 'Un massage sensuel par la personne à ta gauche',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Quelle partie du corps te fait perdre la tête',
          b: 'La faire deviner au groupe',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Séduire celui qui te plaît en n\'écrivant que des emojis',
          b: 'Le séduire avec un seul vocal gênant',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Faire l\'amour seulement tôt le matin',
          b: 'Faire l\'amour seulement tard dans la nuit',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Un baiser volé à ton patron pour un pari',
          b: 'Un baiser volé au meilleur ami de ton partenaire',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Avouer ton fantasme avec une célébrité',
          b: 'Entendre celui de la personne en face',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Que des relations à distance mais passionnées',
          b: 'Que des relations proches mais tièdes',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Te faire faire un suçon bien visible',
          b: 'En faire un toi-même à la personne à côté',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Dire combien de fois tu as fait le premier pas',
          b: 'Dire combien de fois tu t\'es dégonflé',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Une nuit de passion mais tu l\'oublies',
          b: 'Aucune nuit mais le souvenir d\'un baiser',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Embrasser la personne la plus timide du groupe',
          b: 'Embrasser la plus effrontée du groupe',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Faire un strip-poker avec les personnes présentes',
          b: 'Faire un action ou vérité version coquine seulement',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Séduire quelqu\'un seulement avec le regard',
          b: 'Le séduire seulement avec une phrase',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Un rendez-vous hot décidé par ton ex',
          b: 'Un rendez-vous hot décidé par ta mère',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Une morsure sur le téton',
          b: 'Des pinces sur les tétons',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Un bandeau sur les yeux et des surprises à l\'improviste',
          b: 'Tout savoir à l\'avance',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Te faire humilier avec des mots au lit',
          b: 'L\'humilier toi-même avec des mots',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Un maître pour une nuit',
          b: 'Une esclave pour une nuit',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Obéir à chaque ordre pendant une heure',
          b: 'Donner toi-même les ordres pendant une heure',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Du sexe avec un mot de sécurité',
          b: 'Du sexe sans limites convenues',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Un plan à trois avec une escort',
          b: 'Un plan à trois avec un ami',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Se faire filmer par une troisième personne présente',
          b: 'Se faire seulement regarder par un tiers',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Du sexe sur un balcon à la vue de tous',
          b: 'Du sexe dans le jardin la nuit',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Un quickie dans la cuisine',
          b: 'Un marathon dans la chambre',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Le faire sur la table du salon',
          b: 'Le faire contre le mur de l\'entrée',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Du sexe au réveil chaque matin',
          b: 'Du sexe seulement à minuit chaque nuit',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Essayer le wax play',
          b: 'Essayer le temperature play',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Un vibromasseur pendant qu\'il te regarde',
          b: 'Ses mains pendant que tu te regardes',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Te masturber devant lui',
          b: 'Le regarder se masturber pour toi',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Un orgasme seulement avec les mots',
          b: 'Un orgasme seulement avec un jouet',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Du sexe avec le sperme sur le visage',
          b: 'Du sexe avec le sperme sur le corps',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Qu\'il finisse à l\'intérieur',
          b: 'Qu\'il finisse à l\'extérieur',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Un creampie',
          b: 'Un facial',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Le lécher après qu\'il a joui',
          b: 'Te faire lécher après que tu as joui',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Un rapport en pleine lumière du jour',
          b: 'Un rapport seulement à la lueur d\'une bougie',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Du sexe avec la musique à plein volume',
          b: 'Du sexe dans le silence total',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Se faire attacher les poignets avec la cravate',
          b: 'Attacher les chevilles avec les collants',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Un bandeau et un casque antibruit',
          b: 'Seulement le bandeau sur les yeux',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Dominer complètement pendant un jour',
          b: 'Te soumettre complètement pendant un jour',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Du sexe sous la tente au camping',
          b: 'Du sexe dans la piscine la nuit',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Un rapport sur la banquette arrière',
          b: 'Un rapport sur le capot',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Essayer le pegging',
          b: 'Essayer le rimming',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Un gode-ceinture pour elle',
          b: 'Un anneau vibrant pour lui',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Te faire prendre en bouche jusqu\'au fond',
          b: 'Le prendre toi-même jusqu\'au fond',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Deep throat',
          b: 'Face sitting',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'T\'asseoir sur son visage',
          b: 'Le faire asseoir sur le tien',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Un soixante-neuf sans fin',
          b: 'Alterner à tour de rôle',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Du sexe avec un lubrifiant chauffant',
          b: 'Du sexe avec un gel effet froid',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Te faire bander les yeux et deviner les jouets',
          b: 'Deviner ses mains les yeux bandés',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Un jeu de rôle infirmière et patient',
          b: 'Un jeu de rôle policière et arrêté',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Faire semblant d\'être des inconnus à l\'hôtel',
          b: 'Faire semblant d\'être des voisins curieux',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Du sexe avec la lingerie arrachée sur toi',
          b: 'Du sexe en restant presque habillés',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Te faire arracher la culotte',
          b: 'Lui arracher le caleçon avec les dents',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Un orgasme en moins d\'une minute',
          b: 'Résister pendant vingt minutes',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Compter les orgasmes à voix haute',
          b: 'Rester dans le silence absolu',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Un threesome avec ton crush',
          b: 'Un threesome avec son crush',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Regarder un porno ensemble et l\'imiter',
          b: 'Tout inventer sans références',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Recréer une scène porno célèbre',
          b: 'Tourner votre propre vidéo amateur',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Du sexe avec les talons encore aux pieds',
          b: 'Du sexe entièrement nus',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Te faire garder un œuf vibrant toute la journée',
          b: 'Un plug tout l\'après-midi',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Un massage érotique complet',
          b: 'Un bain érotique à deux',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Du sexe avec de l\'huile parfumée partout',
          b: 'Du sexe couverts de mousse',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Le faire séduire par une autre devant toi',
          b: 'Séduire toi-même un autre devant lui',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Un strip-poker qui finit au lit',
          b: 'Un action ou vérité hot jusqu\'au bout',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Embrasser une femme devant lui',
          b: 'Le regarder embrasser un homme',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Un premier baiser saphique',
          b: 'Un premier baiser gay',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Du sexe avec deux mains sur toi',
          b: 'Du sexe avec deux bouches sur toi',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Te faire serrer le cou doucement',
          b: 'Serrer toi-même ses poignets',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Un léger choking convenu',
          b: 'Un hair pulling ferme',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Du sexe avec les cheveux tirés',
          b: 'Du sexe avec les ongles dans le dos',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Te faire prendre par derrière devant le miroir',
          b: 'Le chevaucher toi-même devant le miroir',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Un orgasme refusé pendant trois jours',
          b: 'Trois orgasmes en une heure',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Te faire regarder pendant que tu te déshabilles en webcam',
          b: 'Le regarder se déshabiller en webcam',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Un vibromasseur partagé à tour de rôle',
          b: 'Deux jouets en même temps',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Du sexe sur une chaise, attachée',
          b: 'Du sexe debout contre la fenêtre',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Te faire mordre la lèvre jusqu\'au sang',
          b: 'Lui mordre le cou avec fougue',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Un rapport interrompu et repris plusieurs fois',
          b: 'Un rapport unique sans pauses',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Essayer la privation sensorielle',
          b: 'Essayer la surcharge sensorielle',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Te faire chatouiller les yeux bandés',
          b: 'Le chatouiller toi-même immobilisé',
          tone: ContentTone.cattivo,
        ),
      ];
}
