import '../content_tone.dart';

/// Coppie di "Preferisci" in inglese: parità completa col mazzo italiano.
class PreferisciPoolEn {
  const PreferisciPoolEn._();

  static const List<({String a, String b})> pairs = <({String a, String b})>[
    (a: 'Knowing how you will die', b: 'Knowing when'),
    (a: 'An uncomfortable truth', b: 'A comfortable lie'),
    (a: 'More money', b: 'More free time'),
    (a: 'Being famous', b: 'Being invisible to everyone'),
    (a: 'Travelling to the past', b: 'Travelling to the future'),
    (a: 'Being able to fly', b: 'Being invisible'),
    (a: 'Reading minds', b: 'Seeing the future'),
    (a: 'No more social media', b: 'No more films'),
    (a: 'Losing your phone', b: 'Losing your house keys'),
    (a: 'Always 5 minutes early', b: 'Always 10 minutes late'),
    (a: 'A lovely but useless boss', b: 'An awful but brilliant boss'),
    (
      a: 'A big salary and a boring job',
      b: 'A small salary and a job you love',
    ),
    (a: 'A wedding with 200 guests', b: 'A wedding for two'),
    (a: 'A week without going out', b: 'Going out every single night'),
    (a: 'Sleeping 10 hours', b: 'Sleeping 5 hours and feeling amazing'),
    (a: 'Repeating the perfect holiday', b: 'Trying somewhere new'),
    (a: 'Checking your bank balance daily', b: 'Never looking at it'),
    (a: 'A useless but fun superpower', b: 'A useful but boring superpower'),
    (a: 'Re-reading the same book forever', b: 'Never finishing a single one'),
    (a: 'A life with no music', b: 'A life with no cinema'),
    (a: 'Always knowing the truth', b: 'Living happily in the illusion'),
    (a: 'A sabbatical year', b: 'Retiring one year early'),
    (a: 'Speaking every language', b: 'Playing every instrument'),
    (a: 'Never feeling embarrassment', b: 'Never feeling fear'),
    (a: 'Reliving your best day', b: 'Erasing your worst one'),
    (
      a: 'Moving in together after a month',
      b: 'Moving in together after years',
    ),
    (a: 'Kids early', b: 'Kids late'),
    (
      a: 'A holiday planned down to the minute',
      b: 'Setting off on an adventure',
    ),
    (a: 'A whole season in one night', b: 'One episode a week'),
    (a: 'Battery always on 1%', b: 'Painfully slow internet'),
    (
      a: 'Clothes that are always slightly damp',
      b: 'A pebble in your shoe forever',
    ),
    (a: 'Always saying what you think', b: 'Never speaking again'),
    (a: 'No heating in winter', b: 'No air conditioning in summer'),
    (a: 'Hiccups for life', b: 'Sneezing every two minutes'),
    (
      a: 'Your favourite dish at every meal',
      b: 'Never your favourite dish again',
    ),
    (a: 'Never needing sleep again', b: 'Never needing food again'),
    (a: 'Rich but with no friends', b: 'Broke but adored'),
    (a: 'Never paying rent again', b: 'Double your salary'),
    (
      a: 'The funniest person in the room',
      b: 'The smartest person in the room',
    ),
    (a: 'A photographic memory', b: 'Forgetting every embarrassing moment'),
    (a: 'No more queues', b: 'No more traffic'),
    (a: 'Shaved eyebrows for a year', b: 'Neon green hair for a year'),
    (a: 'Losing your sense of smell', b: 'Losing your sense of taste'),
    (a: 'A cartoon voice', b: 'A laugh that embarrasses everyone'),
    (
      a: 'Your parents seeing your search history',
      b: 'Your boss reading your chats',
    ),
    (a: 'Burping at the end of every sentence', b: 'Laughing like a goat'),
    (a: 'Using a stranger\'s toothbrush', b: 'Drinking from their used glass'),
    (a: 'Permanently sweaty palms', b: 'Permanently chapped lips'),
    (a: 'Dating your ex', b: 'Dating your best friend\'s ex'),
    (a: 'Loud but odourless farts', b: 'Silent but deadly ones'),
    (a: 'Forgetting who you are', b: 'Being forgotten by everyone'),
    (a: 'Losing all your money', b: 'Losing all your memories'),
    (a: 'A rich but boring partner', b: 'A broke but hilarious partner'),
    (
      a: 'An hour in a lift with your ex',
      b: 'An hour in a lift with your boss',
    ),
    (
      a: 'Everyone forgetting your birthday',
      b: 'An embarrassing surprise party',
    ),
    (
      a: 'Your secret revealed to everyone',
      b: 'Knowing everyone else\'s secrets',
    ),
    (a: 'Famous but hated', b: 'Unknown but loved'),
    (a: 'Never laughing again', b: 'Never crying again'),
    (
      a: 'Going back to school for a year',
      b: 'Resitting your final exams every year',
    ),
    (a: 'Living in a horror film', b: 'Living in a musical'),
    (a: 'Feet instead of hands', b: 'Hands instead of feet'),
    (
      a: 'Fighting one duck the size of a horse',
      b: 'A hundred horses the size of ducks',
    ),
    (a: 'Living underwater', b: 'Living in space'),
    (
      a: 'A killer snail chasing you for life',
      b: 'A clown staring at you every night',
    ),
    (a: 'Talking to animals', b: 'Controlling the weather'),
    (a: 'Dancing whenever music plays', b: 'Crying whenever someone laughs'),
    (
      a: 'Every morning in a different country',
      b: 'Never leaving your city again',
    ),
    (a: 'Living in a video game', b: 'Living in a cartoon'),
    (a: 'A "pause" button for life', b: 'A "rewind" button for life'),
    (
      a: 'Teleporting but always losing your shoes',
      b: 'Flying at walking pace',
    ),
    (a: 'Living 1000 years', b: 'Ten lives of 100 years each'),
    (a: 'Raining tacos', b: 'Snowing ice cream'),
    (a: 'King of the world for one day', b: 'An ordinary person forever'),
    (
      a: 'Knowing everything but feeling nothing',
      b: 'Feeling everything but understanding nothing',
    ),
    (a: 'Erasing one regret', b: 'Guaranteeing one future success'),
    (a: 'Always hungry', b: 'Always sleepy'),
    (
      a: 'A tail that wags when you are happy',
      b: 'Ears that droop when you are sad',
    ),
    (a: 'Giving up coffee forever', b: 'Giving up chocolate'),
    (
      a: 'A nose that grows when you lie',
      b: 'Hair that changes colour with your mood',
    ),
    (a: 'Finding the love of your life', b: 'Finding your dream job'),
    (a: 'Filthy rich but always sad', b: 'Broke but always happy'),
    (a: 'A million right now', b: '3,000 euros a month for life'),
    (a: 'Saving your dog', b: 'Saving a stranger'),
    (a: 'Never being able to lie', b: 'Believing every lie'),
    (a: 'Always right but alone', b: 'Wrong but in good company'),
    (a: 'A misunderstood genius', b: 'A happy simpleton'),
    (a: 'The same outfit every day', b: 'Never repeating an outfit'),
    (a: 'Singing everything you say', b: 'Only walking backwards'),
    (a: 'Free Wi-Fi everywhere for life', b: 'Free flights for life'),
    (a: 'Only scalding hot food', b: 'Only freezing cold food'),
    (a: 'Never pizza again', b: 'Never pasta again'),
    (a: 'Never drinks with friends again', b: 'Never takeaway again'),
    (a: 'A long life full of regrets', b: 'A short life with none'),
    (
      a: 'Loving without being loved back',
      b: 'Being loved by someone you do not love',
    ),
    (a: 'Your partner reads your thoughts', b: 'You read theirs'),
    (
      a: 'A partner chosen by your friends',
      b: 'A partner chosen by an algorithm',
    ),
    (
      a: 'Always knowing when someone lies to you',
      b: 'Never getting caught when you lie',
    ),
    (a: 'Being 18 forever', b: 'Skipping straight to 40'),
    (
      a: 'Always sleeping at other people\'s places',
      b: 'Always having guests at yours',
    ),
    (
      a: 'Your favourite band\'s concert all alone',
      b: 'A festival with friends but music you hate',
    ),
    (
      a: 'Singing karaoke off-key in front of everyone',
      b: 'Dancing alone on the dance floor for an hour',
    ),
    (a: 'Losing all the photos on your phone', b: 'Losing all your chats'),
    (a: 'Sneezing confetti', b: 'Burping soap bubbles'),
    (a: 'Having four arms', b: 'Having four legs'),
    (a: 'Being 2 metres 20 tall', b: 'Being 1 metre 20 tall'),
    (a: 'Living without summer', b: 'Living without winter'),
    (a: 'Saving five strangers', b: 'Saving your best friend'),
    (
      a: 'A million but no smartphone ever again',
      b: 'No money but with your phone',
    ),
    (a: 'Your dream job abroad', b: 'A boring job close to your friends'),
    (a: 'Being 25 forever', b: 'Growing old with your friends'),
    (
      a: 'Your dream house in the middle of nowhere',
      b: 'A studio flat right in the centre',
    ),
    (
      a: 'Knowing what they say behind your back',
      b: 'Living peacefully without knowing',
    ),
    (a: 'Every meal cooked by a chef', b: 'A personal driver for life'),
    (
      a: 'Narrating out loud everything you do',
      b: 'Hearing the voice-over of your own life',
    ),
    (a: 'Walking on Lego every morning', b: 'A freezing shower every morning'),
    (
      a: 'A mosquito in your room every night',
      b: 'A fly on your plate at every meal',
    ),
    (a: 'Autocorrect gone mad for life', b: 'No more emojis ever'),
    (
      a: 'Calls only on speakerphone',
      b: 'Your screen always visible to everyone',
    ),
    (
      a: 'Your dog talks but criticises you',
      b: 'Your mirror pays you fake compliments',
    ),
    (a: 'A million just for you', b: 'A hundred thousand each for the group'),
    (a: 'Always underrated', b: 'Always overrated'),
    (
      a: 'Rediscovering your favourite series',
      b: 'Seeing every finale in advance',
    ),
    (a: 'Only speaking by shouting', b: 'Only speaking in a whisper'),
    (a: 'Always laughing at serious moments', b: 'Crying at every comedy'),
    (
      a: 'Always eating with your hands',
      b: 'Eating everything with a teaspoon',
    ),
    (
      a: 'Your dreams projected to your friends',
      b: 'Your friends reading your diary',
    ),
    (
      a: 'The only single one in the group forever',
      b: 'The first in the group to marry',
    ),
    (a: 'Being reborn in the \'80s', b: 'Being born in 2050'),
    (
      a: 'Free restaurants but always alone',
      b: 'Always paying but in good company',
    ),
    (a: 'Going viral for an epic embarrassment', b: 'Never more than 10 likes'),
    (a: 'Only water forever', b: 'Never water again, only fizzy drinks'),
    (a: 'One music genre for life', b: 'One single app on your phone'),
    (a: 'A tuxedo on the beach', b: 'Swimwear at a wedding'),
    (a: 'Cooking like a starred chef', b: 'A house that cleans itself'),
    (
      a: 'A long flight next to a chatterbox',
      b: 'A long flight next to a newborn',
    ),
    (a: 'Savoury breakfast forever', b: 'Sweet dinner forever'),
    (a: 'Living without mirrors', b: 'Living without clocks'),
    (a: 'Reliving the same Monday', b: 'Skipping every Friday'),
    (a: 'Talking to plants', b: 'Understanding babies'),
    (a: 'Always winning at cards', b: 'Always finding a parking space'),
    (a: 'A 40 degree summer with no sea', b: 'A freezing winter with no snow'),
    (
      a: 'Only terribly dubbed films',
      b: 'Only films with out-of-sync subtitles',
    ),
    (a: 'Free coffee for life', b: 'Free ice cream for life'),
    (a: 'Moving house every year', b: 'The same house forever'),
    (
      a: 'An embarrassing ringtone forever',
      b: 'An embarrassing wallpaper forever',
    ),
    (a: 'Being a famous meme', b: 'Having a famous lookalike'),
    (
      a: 'Dancing the macarena at every greeting',
      b: 'Greeting everyone with a bow',
    ),
    (a: 'Chocolate spread without bread', b: 'Bread without chocolate spread'),
    (
      a: 'An endless weekend of constant rain',
      b: 'Only Mondays but always sunny',
    ),
    (
      a: 'One dish cooked to perfection',
      b: 'Cooking everything just about okay',
    ),
  ];

  /// Dilemmi da modalità Hot: parità completa col mazzo italiano.
  static const List<({String a, String b, String tone})>
  hot = <({String a, String b, String tone})>[
    (
      a: 'Walking around naked for a minute',
      b: 'Kissing someone in this group',
      tone: ContentTone.piccante,
    ),
    (
      a: 'A night with someone in the group',
      b: 'A night with an old teacher of yours',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Showing the group your gallery',
      b: 'Having your chats read out loud',
      tone: ContentTone.piccante,
    ),
    (
      a: 'A year without sex',
      b: 'A year without nights out',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Telling the group your body count',
      b: 'Showing your last search',
      tone: ContentTone.piccante,
    ),
    (a: 'Love without sex', b: 'Sex without love', tone: ContentTone.piccante),
    (
      a: 'A gorgeous partner who is awful in bed',
      b: 'An average one who is phenomenal',
      tone: ContentTone.piccante,
    ),
    (
      a: 'A night with your ex',
      b: 'A night with a stranger',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Catching your parents',
      b: 'Being caught by them',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Telling everyone who you fancy right now',
      b: 'Never speaking to them again',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Kissing someone here with your eyes closed',
      b: 'Kissing your ex in front of everyone',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Never kissing again',
      b: 'Never hugging again',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Knowing who your partner would cheat with',
      b: 'Never knowing at all',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Only blind dates for a year',
      b: 'Only dates picked by your mum',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Rewatching your first kiss on video',
      b: 'The whole group rewatching it',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Moaning every time you sit down',
      b: 'Shouting your ex\'s name at every toast',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Sending a nude to your ex by mistake',
      b: 'Sending it to the family group chat',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Sexting your boss by mistake',
      b: 'Calling your partner by your ex\'s name',
      tone: ContentTone.piccante,
    ),
    (
      a: 'One night with a celebrity',
      b: 'A month of sex with your ex',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Sex only in total darkness',
      b: 'Only with the lights full on',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Sharing your weirdest fantasy',
      b: 'Hearing the one from the person on your right',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Friends with benefits with your best friend',
      b: 'No sex at all for a year',
      tone: ContentTone.piccante,
    ),
    (
      a: 'An ex who kisses like a god',
      b: 'Someone new who needs full training',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Being undressed with a look at the bar',
      b: 'Never being noticed again',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Telling us your worst date',
      b: 'Reliving your steamiest embarrassment',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Always making the first move',
      b: 'Always waiting for the other person',
      tone: ContentTone.piccante,
    ),
    (
      a: 'A threesome with strangers',
      b: 'A threesome with friends',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Catching your flatmate in the act',
      b: 'Being caught by your flatmate',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Saying how often you think about it daily',
      b: 'Saying when you last did it',
      tone: ContentTone.piccante,
    ),
    (
      a: 'A super jealous but red-hot partner',
      b: 'A relaxed but lazy one in bed',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Kissing the first person through the door',
      b: 'Kissing the last person who texted you',
      tone: ContentTone.piccante,
    ),
    (
      a: 'A night of passion with no kissing',
      b: 'Endless kissing but nothing else',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Forgetting your first time',
      b: 'Remembering it every single day',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Naming the most absurd place you have done it',
      b: 'Naming the place you would love to',
      tone: ContentTone.piccante,
    ),
    (
      a: 'A fling with your personal trainer',
      b: 'A fling with your doctor',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Only one night stands for a year',
      b: 'Only serious relationships for life',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Hooking up with your ex now and then',
      b: 'Closing the door forever, with regret',
      tone: ContentTone.piccante,
    ),
    (
      a: 'A snog with the person on your left',
      b: 'A sensual slow with the person on your right',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Sleeping naked next to a friend',
      b: 'Showering in swimwear with your ex',
      tone: ContentTone.piccante,
    ),
    (
      a: 'An unsolicited nude from your boss',
      b: 'Sending one to your boss by mistake',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Mind-blowing sex once a month',
      b: 'Mediocre sex every day',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Knowing what they think in bed',
      b: 'Them hearing your every thought in bed',
      tone: ContentTone.piccante,
    ),
    (
      a: 'A weekend with your secret crush',
      b: 'A month with your first love',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Breakfast in bed after the first night',
      b: 'Vanishing before dawn',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Naming your weak spot in bed',
      b: 'Miming it in front of the group',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Tattooing your ex\'s name',
      b: 'Shouting their name at the wrong moment',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Matching with your ex on an app',
      b: 'Matching with your boss on an app',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Your partner knows your every fantasy',
      b: 'You know every one of theirs',
      tone: ContentTone.piccante,
    ),
    (
      a: 'An improvised striptease right now',
      b: 'A spicy tale of your summer',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Kissing someone here of your choosing',
      b: 'Kissing one chosen by the group',
      tone: ContentTone.piccante,
    ),
    (
      a: 'A secret, wildly passionate affair',
      b: 'An official but lukewarm relationship',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Sex only in summer',
      b: 'Sex only in winter',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Forgetting every wild night you have had',
      b: 'Remembering even the ones best forgotten',
      tone: ContentTone.piccante,
    ),
    (
      a: 'A spicy voice note sent to the wrong person',
      b: 'Receiving one from your boss',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Letting us read your chats with your ex',
      b: 'Letting us see your photos with your ex',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Love at first sight tonight',
      b: 'A one night adventure tonight',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Telling the group your crush\'s name',
      b: 'Letting the group guess it',
      tone: ContentTone.piccante,
    ),
    (
      a: 'A slow dance with your ex tonight',
      b: 'Romantic karaoke with someone in the group',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Chatting up a stranger right now',
      b: 'Giving your number to the first who asks',
      tone: ContentTone.piccante,
    ),
    (
      a: 'A massage from someone in the group',
      b: 'Giving one to someone in the group',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Flirting banned for a year',
      b: 'Compulsory flirting with everyone',
      tone: ContentTone.piccante,
    ),
    (
      a: 'A night with your music idol',
      b: 'A weekend with your favourite actor',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Confessing a steamy dream about someone here',
      b: 'Someone here confessing one about you',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Total silence in bed',
      b: 'Full live commentary in bed',
      tone: ContentTone.piccante,
    ),
    (
      a: 'A showstopping behind',
      b: 'A neckline worth applause',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Your ex becomes mega famous',
      b: 'Your ex becomes your boss',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Saying what turns you on most',
      b: 'Saying what kills the mood instantly',
      tone: ContentTone.piccante,
    ),
    (
      a: 'A summer affair never confessed',
      b: 'An endless long-distance love',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Two people here chatting you up',
      b: 'Chatting up two people here at once',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Seeing your ex with someone hotter than you',
      b: 'Them seeing you with someone worse than them',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Kisses with a bite',
      b: 'Closed-lip pecks forever',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Sleeping cuddled up with no sex',
      b: 'Sex without ever sleeping together',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Sex with the music blasting',
      b: 'With the news on in the background',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Revealing your number of exes',
      b: 'Revealing which one was the best',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Chatting up the waiter tonight',
      b: 'Leaving your number on the receipt',
      tone: ContentTone.piccante,
    ),
    (
      a: 'An awkward but sweet first time',
      b: 'A perfect one with the wrong person',
      tone: ContentTone.piccante,
    ),
    (
      a: 'A tattoo where the group decides',
      b: 'A piercing where the group decides',
      tone: ContentTone.piccante,
    ),
    (
      a: 'A 30 second kiss with someone here',
      b: 'Ten quick kisses with ten strangers',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Knowing who here dreams about you at night',
      b: 'Knowing who would never kiss you',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Sex in a tent on a packed campsite',
      b: 'In a hotel with paper-thin walls',
      tone: ContentTone.piccante,
    ),
    (
      a: 'A singles-only holiday',
      b: 'A couples-only holiday',
      tone: ContentTone.piccante,
    ),
    (a: 'Swallow', b: 'Spit', tone: ContentTone.cattivo),
    (
      a: 'Give oral for an hour',
      b: 'Receive oral for an hour',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Only oral for a year',
      b: 'Never receive oral again',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Deepthroat every time',
      b: 'Never go down at all',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'A threesome with two strangers',
      b: 'Watch your partner with someone else',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Be tied up and blindfolded',
      b: 'Tie up and blindfold them',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'A hot video of you leaks',
      b: 'Your hot chats leak',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Ride on top all night',
      b: 'Get pinned down all night',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Loud and vocal in bed',
      b: 'Completely silent in bed',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Sex with the lights on',
      b: 'Sex only in the dark',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Edge them for an hour',
      b: 'Let them finish in a minute',
      tone: ContentTone.cattivo,
    ),
    (a: 'Wear a blindfold', b: 'Wear handcuffs', tone: ContentTone.cattivo),
    (a: 'Rough and fast', b: 'Slow and teasing', tone: ContentTone.cattivo),
    (a: 'Get spanked', b: 'Do the spanking', tone: ContentTone.cattivo),
    (
      a: 'Use a vibrator together',
      b: 'Use handcuffs together',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'A threesome with two women',
      b: 'A threesome with two men',
      tone: ContentTone.cattivo,
    ),
    (a: 'Give a striptease', b: 'Get a lap dance', tone: ContentTone.cattivo),
    (
      a: 'Send a nude first',
      b: 'Wait to receive one',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Morning sex every day',
      b: 'Late-night sex every night',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Sex in a public bathroom',
      b: 'Sex on a balcony at night',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Try anal',
      b: 'Try double penetration with a toy',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Be dominant every time',
      b: 'Be submissive every time',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Talk dirty out loud',
      b: 'Stay completely quiet',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Blindfold your partner',
      b: 'Be blindfolded yourself',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'A quickie in a car',
      b: 'A quickie in an elevator',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Roleplay boss and assistant',
      b: 'Roleplay strangers at a bar',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Get tied to the bed',
      b: 'Tie them to the bed',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Have your hair pulled',
      b: 'Pull their hair',
      tone: ContentTone.cattivo,
    ),
    (a: 'Watch porn together', b: 'Film your own', tone: ContentTone.cattivo),
    (
      a: 'Skinny dip in public',
      b: 'Have sex on a beach at night',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'A week of only oral',
      b: 'A week of only anal',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Wear a collar and leash',
      b: 'Hold the leash',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Record a private sex tape',
      b: 'Never record anything',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Get teased for an hour first',
      b: 'Skip straight to it',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Use ice on their body',
      b: 'Use hot wax on their body',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Be gagged during sex',
      b: 'Gag your partner',
      tone: ContentTone.cattivo,
    ),
    (a: 'Try bondage rope', b: 'Try a spreader bar', tone: ContentTone.cattivo),
    (
      a: 'A one-night stand abroad',
      b: 'Kiss a stranger at home',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Give oral in the shower',
      b: 'Receive oral in the bath',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Sit on their face',
      b: 'Have them sit on yours',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Try a sex swing',
      b: 'Try a spanking bench',
      tone: ContentTone.cattivo,
    ),
    (a: 'Moan their name', b: 'Keep totally silent', tone: ContentTone.cattivo),
    (
      a: 'Send a dirty voice note',
      b: 'Send an explicit photo',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Have sex in a changing room',
      b: 'In a cinema back row',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Be edged all night',
      b: 'Finish fast every time',
      tone: ContentTone.cattivo,
    ),
    (a: 'Try nipple clamps', b: 'Try a paddle', tone: ContentTone.cattivo),
    (
      a: 'A blindfolded taste test on skin',
      b: 'A blindfolded touch game',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Dominate in the bedroom',
      b: 'Submit in the bedroom',
      tone: ContentTone.cattivo,
    ),
    (a: 'Try wax play', b: 'Try ice play', tone: ContentTone.cattivo),
    (
      a: 'Have sex outdoors in daylight',
      b: 'Only after dark',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Wear lingerie all evening',
      b: 'Wear nothing all evening',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Get your partner off first',
      b: 'Finish first yourself',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'A friends-with-benefits deal',
      b: 'A no-strings holiday fling',
      tone: ContentTone.cattivo,
    ),
    (a: 'Try a butt plug', b: 'Try a cock ring', tone: ContentTone.cattivo),
    (
      a: 'Be watched by one stranger',
      b: 'Watch two strangers',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Have sex to loud music',
      b: 'In complete silence',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Try roleplay every time',
      b: 'Keep it real every time',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Get blindfolded and surprised',
      b: 'Blindfold and surprise them',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Try a threesome once',
      b: 'Try swinging once',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Deny their orgasm for a day',
      b: 'Give them three in a row',
      tone: ContentTone.cattivo,
    ),
    (a: 'Have sex on a train', b: 'On a rooftop', tone: ContentTone.cattivo),
    (
      a: 'Wear a remote vibrator in public',
      b: 'Get teased under the table',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Be handcuffed to a chair',
      b: 'Handcuff them to a chair',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Try sensory deprivation',
      b: 'Try overstimulation',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Give a massage that leads to more',
      b: 'Receive one that does',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Say your wildest fantasy out loud',
      b: 'Have them guess it',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Sex in every room in one night',
      b: 'A marathon in one room',
      tone: ContentTone.cattivo,
    ),
    (a: 'Be tied spread-eagle', b: 'Do the tying', tone: ContentTone.cattivo),
    (
      a: 'Try a strap-on',
      b: 'Try a double-ended toy',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Get edged and denied',
      b: 'Get overstimulated',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'A threesome with an ex',
      b: 'A threesome with a stranger',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Have loud makeup sex',
      b: 'Silent angry sex',
      tone: ContentTone.cattivo,
    ),
    (a: 'Try light choking', b: 'Try firm pinning', tone: ContentTone.cattivo),
    (
      a: 'Sext all day at work',
      b: 'Video call at night',
      tone: ContentTone.cattivo,
    ),
    // -------------------------------------------- piccante (extra)
    (
      a: 'One perfect kiss a month',
      b: 'Mediocre kisses every day',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Knowing what your crush thinks of you',
      b: 'Them knowing everything you think',
      tone: ContentTone.piccante,
    ),
    (
      a: 'One unforgettable night with no follow-up',
      b: 'Ten lovely dates with no spark',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Sleeping cuddled up and nothing more',
      b: 'Everything else but no cuddles after',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Revealing your body count to your crush',
      b: 'Showing your last chat with your flame',
      tone: ContentTone.piccante,
    ),
    (
      a: 'A partner brilliant at kissing',
      b: 'A partner brilliant at texting',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Flirting in front of your parents',
      b: 'Flirting in front of your ex',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Getting a daring photo from the wrong person',
      b: 'Sending one to the wrong person yourself',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Being seduced with words',
      b: 'Being seduced with a look',
      tone: ContentTone.piccante,
    ),
    (
      a: 'A weekend of passion with no phone',
      b: 'A week of flirting by chat only',
      tone: ContentTone.piccante,
    ),
    (
      a: 'A first kiss on the first date',
      b: 'A first kiss after a month of waiting',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Always knowing who is watching you in a bar',
      b: 'Never knowing but being watched often',
      tone: ContentTone.piccante,
    ),
    (
      a: 'An ex who texts you every night',
      b: 'A crush who never texts you',
      tone: ContentTone.piccante,
    ),
    (
      a: 'A slow with your crush in front of everyone',
      b: 'A candlelit dinner in total silence',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Letting the group read your crush chat',
      b: 'Calling them right now on speaker',
      tone: ContentTone.piccante,
    ),
    (
      a: 'A perfect massage every evening',
      b: 'Breakfast in bed every morning',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Being the best kiss of someone\'s life',
      b: 'Receiving the best kiss of yours',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Never any first dates again',
      b: 'Only first dates forever',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Always saying "I like you" first',
      b: 'Always waiting to hear it first',
      tone: ContentTone.piccante,
    ),
    (
      a: 'A playlist that starts when you flirt',
      b: 'A voice-over narrating your dates',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Your ex at your wedding',
      b: 'Your mother-in-law on your honeymoon',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Rewatching your first kiss on video',
      b: 'Showing the group your dating profile',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Freezing at every "we need to talk"',
      b: 'Never hearing "we need to talk" again',
      tone: ContentTone.piccante,
    ),
    (
      a: 'A summer fling every summer',
      b: 'A true love every ten years',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Knowing how often they talked about you',
      b: 'Knowing what they said but not who',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Kisses only in the rain',
      b: 'Kisses only in lifts',
      tone: ContentTone.piccante,
    ),
    (
      a: 'A "good morning" from the right person daily',
      b: 'A "goodnight" every evening',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Losing your voice whenever you flirt',
      b: 'Always saying one word too many',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Irresistible only by day',
      b: 'Irresistible only by night',
      tone: ContentTone.piccante,
    ),
    (
      a: 'A blind date arranged by the group',
      b: 'A date organised by your ex',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Dinner with your crush\'s partner',
      b: 'Driving the couple around all evening',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Always knowing when someone lies in love',
      b: 'Never being the first to lie yourself',
      tone: ContentTone.piccante,
    ),
    (
      a: 'A year without kisses',
      b: 'A year without hugs',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Confessing the crush to their face',
      b: 'Confessing it to this whole room right now',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Famous for a love story',
      b: 'Famous for an epic rejection',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Dating someone identical to you',
      b: 'Dating your exact opposite',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Your diary read by your crush',
      b: 'Your search history read by your parents',
      tone: ContentTone.piccante,
    ),
    (
      a: 'One stolen kiss you remember forever',
      b: 'A hundred kisses asked for permission',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Always seeming uninterested',
      b: 'Always seeming far too keen',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Love at first sight once in a lifetime',
      b: 'Constant crushes never returned straight away',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Flowers at the office every week',
      b: 'A romantic voice note every evening',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Flirting brilliantly only in writing',
      b: 'Flirting brilliantly only in person',
      tone: ContentTone.piccante,
    ),
    (
      a: 'A crush on a friend in this group',
      b: 'A crush on a colleague you see daily',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Always knowing if a first date will go well',
      b: 'Getting to redo every first date once',
      tone: ContentTone.piccante,
    ),
    (
      a: 'A romantic date planned to the minute',
      b: 'Total improvisation every time',
      tone: ContentTone.piccante,
    ),
    (
      a: 'A partner who dances beautifully',
      b: 'A partner who cooks beautifully',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Zero jealousy forever',
      b: 'Double the passion but jealousy included',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Being courted by two people at once',
      b: 'Always choosing but never being courted',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Your name in a famous love song',
      b: 'Your face in a viral romantic video',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Only breakfast dates',
      b: 'Only midnight dates',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Holding hands in public always',
      b: 'Affection only in private but intense',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Forgetting all your exes',
      b: 'All your exes forgetting you',
      tone: ContentTone.piccante,
    ),
    (
      a: 'A film-worthy kiss once a year',
      b: 'Ordinary kisses but daily',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Declaring your love in a handwritten letter',
      b: 'Declaring it in a speech in front of everyone',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Knowing the exact day you will fall in love',
      b: 'Knowing only the name but not when',
      tone: ContentTone.piccante,
    ),
    (
      a: 'A touchy but passionate partner',
      b: 'A zen but lukewarm one',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Reliving your first love',
      b: 'Knowing your last one in advance',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Coming across as shy when you flirt',
      b: 'Coming across as brazen when you are shy',
      tone: ContentTone.piccante,
    ),
    (
      a: 'The truth about why each relationship ended',
      b: 'Never knowing but ending in peace',
      tone: ContentTone.piccante,
    ),
    (
      a: 'A perfect date organised by your ex',
      b: 'A total disaster but with the right person',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Everyone fancying you except your crush',
      b: 'Only your crush fancying you and nobody else',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Messages always read instantly',
      b: 'Replies guaranteed within a minute',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Unsending one message a day',
      b: 'Reading every message others delete',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Shameless flirting but only on Tuesdays',
      b: 'Light flirting but every day',
      tone: ContentTone.piccante,
    ),
    (
      a: 'The group picks your next date',
      b: 'The group reads the chat from your last one',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Being kissed without warning',
      b: 'Announcing every kiss ten seconds early',
      tone: ContentTone.piccante,
    ),
    (
      a: 'A legendary single summer',
      b: 'A perfect coupled-up winter',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Your crush sees all your stories',
      b: 'You see everything they look at',
      tone: ContentTone.piccante,
    ),
    (
      a: 'A slow dance with the wrong person',
      b: 'No slow dances ever again',
      tone: ContentTone.piccante,
    ),
    // --------------------------------------------- cattivo (extra)
    (
      a: 'Have sex outdoors and risk it',
      b: 'Stay safe indoors',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Be the only one blindfolded',
      b: 'Both blindfolded',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Wear a ball gag',
      b: 'Wear a blindfold instead',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Try mutual masturbation',
      b: 'Try mutual oral',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Get spanked with a hand',
      b: 'Get spanked with a paddle',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Have sex in a hot tub',
      b: 'In a pool at night',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Roleplay a stranger pickup',
      b: 'Roleplay reunited exes',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Be told exactly what to do',
      b: 'Give all the orders',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Plan a threesome carefully',
      b: 'Let one just happen',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Keep your eyes on them',
      b: 'Keep your eyes closed',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Give a slow tease strip',
      b: 'Get one from them',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Have sex with a mirror watching',
      b: 'With it covered up',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Try temperature play',
      b: 'Try impact play',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Be tied and teased for an hour',
      b: 'Do the teasing',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Have phone sex nightly',
      b: 'Video sex weekly',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Try a blindfold and headphones',
      b: 'Just a blindfold',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Get pinned against a wall',
      b: 'Pin them against a wall',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Have sex right after a fight',
      b: 'Right after a night out',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Wear a chastity device',
      b: 'Hold the key to theirs',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Get woken up for sex',
      b: 'Wake them up for it',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'A threesome with a couple',
      b: 'A threesome with two singles',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Try a new position each time',
      b: 'Perfect one position',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Whisper filth in their ear',
      b: 'Have it whispered to you',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Be spanked till you beg',
      b: 'Spank till they beg',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Try public teasing all date',
      b: 'Private teasing all night',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Get bent over the counter',
      b: 'Bend them over it',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Have sex on the first date',
      b: 'Wait months on purpose',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Wear a vibrator on a dinner date',
      b: 'Wear one at the cinema',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Try being fully submissive',
      b: 'Be fully in control',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Give a hands-free tease',
      b: 'Get a hands-free tease',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Have your fantasy acted out',
      b: 'Act out theirs',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Try a spanking paddle',
      b: 'Try a leather flogger',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Get tied and left waiting',
      b: 'Be the one who waits',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Have sex during a road trip',
      b: 'Have sex at a festival',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Join a threesome with strangers',
      b: 'Watch and not join',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Be blindfolded and fed pleasure',
      b: 'Do the feeding',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Have loud shower sex',
      b: 'Quiet bedroom sex',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Roleplay a fantasy job',
      b: 'Roleplay a fantasy stranger',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Get overstimulated till you shake',
      b: 'Edged till you beg',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Have sex with toys only',
      b: 'With hands only',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Try being watched on webcam',
      b: 'Watch someone on cam',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Get your neck kissed for an hour',
      b: 'Do the kissing',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'A wild one-night stand',
      b: 'A slow-burn affair',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Try a bondage harness',
      b: 'Try a simple silk tie',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Be told no all night then yes',
      b: 'Be told yes all night',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Have sex outdoors under the stars',
      b: 'In a luxury suite',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Have a threesome and stay',
      b: 'Have a threesome and leave',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Give a blindfolded oral tease',
      b: 'Receive one',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Have makeup sex after every row',
      b: 'Never fight at all',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Try a remote toy they control',
      b: 'A remote toy you control',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Get pinned and told to stay still',
      b: 'Do the pinning',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Have sex in a party bathroom',
      b: 'Have sex in a taxi',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Try being gagged and tied',
      b: 'Do the gagging',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Wear nothing under a coat out',
      b: 'Wear lingerie under a suit',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Get edged over a video call',
      b: 'Get teased in person',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Pick your threesome partner',
      b: 'Let them pick yours',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Roleplay with costumes',
      b: 'Roleplay with just accents',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Be denied a week then spoiled',
      b: 'Get a little every day',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Have sex on a balcony at dusk',
      b: 'In a forest clearing',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Try light bondage nightly',
      b: 'Try wild kink weekly',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Get talked through it step by step',
      b: 'Take the lead',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Have shower sex before work',
      b: 'Bath sex after work',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Try a blindfolded guessing game',
      b: 'A tied-up tease game',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Be spanked in roleplay',
      b: 'Do the spanking in roleplay',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Play a safeword surrender game',
      b: 'Play a total control game',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Flash in public on a dare',
      b: 'Strip in private on a dare',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Get overstimulated by a toy',
      b: 'Overstimulated by their hands',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Have the threesome you both crave',
      b: 'Keep it just you two',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'A full night of teasing',
      b: 'A fast night of finishing',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Be tied and blindfolded together',
      b: 'Take turns tying',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Have sex in a moving car',
      b: 'On a still rooftop',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Take a dominant role for a week',
      b: 'A submissive role for a week',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Have your orgasm controlled',
      b: 'Control theirs',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Have loud hotel sex',
      b: 'Silent house sex',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Film a private tape',
      b: 'Take private photos',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Give a striptease to slow music',
      b: 'Get one to fast music',
      tone: ContentTone.cattivo,
    ),
  ];
}
