import '../content_tone.dart';

/// Coppie di "Preferisci" in inglese: parità completa col mazzo italiano.
class PreferisciPoolEn {
  const PreferisciPoolEn._();

  static const List<({String a, String b})> pairs = <({String a, String b})>[
    (a: 'Knowing how you will die', b: 'Knowing when'),
    (a: 'An uncomfortable truth', b: 'A comfortable lie'),
    (a: 'More money', b: 'More free time'),
    (a: 'Being famous', b: 'Being invisible to everyone'),
    (a: 'Travelling to the past', b: 'Travelling to the future'),
    (a: 'Being able to fly', b: 'Being invisible'),
    (a: 'Reading minds', b: 'Seeing the future'),
    (a: 'No more social media', b: 'No more films'),
    (a: 'Losing your phone', b: 'Losing your house keys'),
    (a: 'Always 5 minutes early', b: 'Always 10 minutes late'),
    (a: 'A lovely but useless boss', b: 'An awful but brilliant boss'),
    (
      a: 'A big salary and a boring job',
      b: 'A small salary and a job you love',
    ),
    (a: 'A wedding with 200 guests', b: 'A wedding for two'),
    (a: 'A week without going out', b: 'Going out every single night'),
    (a: 'Sleeping 10 hours', b: 'Sleeping 5 hours and feeling amazing'),
    (a: 'Repeating the perfect holiday', b: 'Trying somewhere new'),
    (a: 'Checking your bank balance daily', b: 'Never looking at it'),
    (a: 'A useless but fun superpower', b: 'A useful but boring superpower'),
    (a: 'Re-reading the same book forever', b: 'Never finishing a single one'),
    (a: 'A life with no music', b: 'A life with no cinema'),
    (a: 'Always knowing the truth', b: 'Living happily in the illusion'),
    (a: 'A sabbatical year', b: 'Retiring one year early'),
    (a: 'Speaking every language', b: 'Playing every instrument'),
    (a: 'Never feeling embarrassment', b: 'Never feeling fear'),
    (a: 'Reliving your best day', b: 'Erasing your worst one'),
    (
      a: 'Moving in together after a month',
      b: 'Moving in together after years',
    ),
    (a: 'Kids early', b: 'Kids late'),
    (
      a: 'A holiday planned down to the minute',
      b: 'Setting off on an adventure',
    ),
    (a: 'A whole season in one night', b: 'One episode a week'),
    (a: 'Battery always on 1%', b: 'Painfully slow internet'),
    (
      a: 'Clothes that are always slightly damp',
      b: 'A pebble in your shoe forever',
    ),
    (a: 'Always saying what you think', b: 'Never speaking again'),
    (a: 'No heating in winter', b: 'No air conditioning in summer'),
    (a: 'Hiccups for life', b: 'Sneezing every two minutes'),
    (
      a: 'Your favourite dish at every meal',
      b: 'Never your favourite dish again',
    ),
    (a: 'Never needing sleep again', b: 'Never needing food again'),
    (a: 'Rich but with no friends', b: 'Broke but adored'),
    (a: 'Never paying rent again', b: 'Double your salary'),
    (
      a: 'The funniest person in the room',
      b: 'The smartest person in the room',
    ),
    (a: 'A photographic memory', b: 'Forgetting every embarrassing moment'),
    (a: 'No more queues', b: 'No more traffic'),
    (a: 'Shaved eyebrows for a year', b: 'Neon green hair for a year'),
    (a: 'Losing your sense of smell', b: 'Losing your sense of taste'),
    (a: 'A cartoon voice', b: 'A laugh that embarrasses everyone'),
    (
      a: 'Your parents seeing your search history',
      b: 'Your boss reading your chats',
    ),
    (a: 'Burping at the end of every sentence', b: 'Laughing like a goat'),
    (a: 'Using a stranger\'s toothbrush', b: 'Drinking from their used glass'),
    (a: 'Permanently sweaty palms', b: 'Permanently chapped lips'),
    (a: 'Dating your ex', b: 'Dating your best friend\'s ex'),
    (a: 'Loud but odourless farts', b: 'Silent but deadly ones'),
    (a: 'Forgetting who you are', b: 'Being forgotten by everyone'),
    (a: 'Losing all your money', b: 'Losing all your memories'),
    (a: 'A rich but boring partner', b: 'A broke but hilarious partner'),
    (
      a: 'An hour in a lift with your ex',
      b: 'An hour in a lift with your boss',
    ),
    (
      a: 'Everyone forgetting your birthday',
      b: 'An embarrassing surprise party',
    ),
    (
      a: 'Your secret revealed to everyone',
      b: 'Knowing everyone else\'s secrets',
    ),
    (a: 'Famous but hated', b: 'Unknown but loved'),
    (a: 'Never laughing again', b: 'Never crying again'),
    (
      a: 'Going back to school for a year',
      b: 'Resitting your final exams every year',
    ),
    (a: 'Living in a horror film', b: 'Living in a musical'),
    (a: 'Feet instead of hands', b: 'Hands instead of feet'),
    (
      a: 'Fighting one duck the size of a horse',
      b: 'A hundred horses the size of ducks',
    ),
    (a: 'Living underwater', b: 'Living in space'),
    (
      a: 'A killer snail chasing you for life',
      b: 'A clown staring at you every night',
    ),
    (a: 'Talking to animals', b: 'Controlling the weather'),
    (a: 'Dancing whenever music plays', b: 'Crying whenever someone laughs'),
    (
      a: 'Every morning in a different country',
      b: 'Never leaving your city again',
    ),
    (a: 'Living in a video game', b: 'Living in a cartoon'),
    (a: 'A "pause" button for life', b: 'A "rewind" button for life'),
    (
      a: 'Teleporting but always losing your shoes',
      b: 'Flying at walking pace',
    ),
    (a: 'Living 1000 years', b: 'Ten lives of 100 years each'),
    (a: 'Raining tacos', b: 'Snowing ice cream'),
    (a: 'King of the world for one day', b: 'An ordinary person forever'),
    (
      a: 'Knowing everything but feeling nothing',
      b: 'Feeling everything but understanding nothing',
    ),
    (a: 'Erasing one regret', b: 'Guaranteeing one future success'),
    (a: 'Always hungry', b: 'Always sleepy'),
    (
      a: 'A tail that wags when you are happy',
      b: 'Ears that droop when you are sad',
    ),
    (a: 'Giving up coffee forever', b: 'Giving up chocolate'),
    (
      a: 'A nose that grows when you lie',
      b: 'Hair that changes colour with your mood',
    ),
    (a: 'Finding the love of your life', b: 'Finding your dream job'),
    (a: 'Filthy rich but always sad', b: 'Broke but always happy'),
    (a: 'A million right now', b: '3,000 euros a month for life'),
    (a: 'Saving your dog', b: 'Saving a stranger'),
    (a: 'Never being able to lie', b: 'Believing every lie'),
    (a: 'Always right but alone', b: 'Wrong but in good company'),
    (a: 'A misunderstood genius', b: 'A happy simpleton'),
    (a: 'The same outfit every day', b: 'Never repeating an outfit'),
    (a: 'Singing everything you say', b: 'Only walking backwards'),
    (a: 'Free Wi-Fi everywhere for life', b: 'Free flights for life'),
    (a: 'Only scalding hot food', b: 'Only freezing cold food'),
    (a: 'Never pizza again', b: 'Never pasta again'),
    (a: 'Never drinks with friends again', b: 'Never takeaway again'),
    (a: 'A long life full of regrets', b: 'A short life with none'),
    (
      a: 'Loving without being loved back',
      b: 'Being loved by someone you do not love',
    ),
    (a: 'Your partner reads your thoughts', b: 'You read theirs'),
    (
      a: 'A partner chosen by your friends',
      b: 'A partner chosen by an algorithm',
    ),
    (
      a: 'Always knowing when someone lies to you',
      b: 'Never getting caught when you lie',
    ),
    (a: 'Being 18 forever', b: 'Skipping straight to 40'),
    (
      a: 'Always sleeping at other people\'s places',
      b: 'Always having guests at yours',
    ),
    (
      a: 'Your favourite band\'s concert all alone',
      b: 'A festival with friends but music you hate',
    ),
    (
      a: 'Singing karaoke off-key in front of everyone',
      b: 'Dancing alone on the dance floor for an hour',
    ),
    (a: 'Losing all the photos on your phone', b: 'Losing all your chats'),
    (a: 'Sneezing confetti', b: 'Burping soap bubbles'),
    (a: 'Having four arms', b: 'Having four legs'),
    (a: 'Being 2 metres 20 tall', b: 'Being 1 metre 20 tall'),
    (a: 'Living without summer', b: 'Living without winter'),
    (a: 'Saving five strangers', b: 'Saving your best friend'),
    (
      a: 'A million but no smartphone ever again',
      b: 'No money but with your phone',
    ),
    (a: 'Your dream job abroad', b: 'A boring job close to your friends'),
    (a: 'Being 25 forever', b: 'Growing old with your friends'),
    (
      a: 'Your dream house in the middle of nowhere',
      b: 'A studio flat right in the centre',
    ),
    (
      a: 'Knowing what they say behind your back',
      b: 'Living peacefully without knowing',
    ),
    (a: 'Every meal cooked by a chef', b: 'A personal driver for life'),
    (
      a: 'Narrating out loud everything you do',
      b: 'Hearing the voice-over of your own life',
    ),
    (a: 'Walking on Lego every morning', b: 'A freezing shower every morning'),
    (
      a: 'A mosquito in your room every night',
      b: 'A fly on your plate at every meal',
    ),
    (a: 'Autocorrect gone mad for life', b: 'No more emojis ever'),
    (
      a: 'Calls only on speakerphone',
      b: 'Your screen always visible to everyone',
    ),
    (
      a: 'Your dog talks but criticises you',
      b: 'Your mirror pays you fake compliments',
    ),
    (a: 'A million just for you', b: 'A hundred thousand each for the group'),
    (a: 'Always underrated', b: 'Always overrated'),
    (
      a: 'Rediscovering your favourite series',
      b: 'Seeing every finale in advance',
    ),
    (a: 'Only speaking by shouting', b: 'Only speaking in a whisper'),
    (a: 'Always laughing at serious moments', b: 'Crying at every comedy'),
    (
      a: 'Always eating with your hands',
      b: 'Eating everything with a teaspoon',
    ),
    (
      a: 'Your dreams projected to your friends',
      b: 'Your friends reading your diary',
    ),
    (
      a: 'The only single one in the group forever',
      b: 'The first in the group to marry',
    ),
    (a: 'Being reborn in the \'80s', b: 'Being born in 2050'),
    (
      a: 'Free restaurants but always alone',
      b: 'Always paying but in good company',
    ),
    (a: 'Going viral for an epic embarrassment', b: 'Never more than 10 likes'),
    (a: 'Only water forever', b: 'Never water again, only fizzy drinks'),
    (a: 'One music genre for life', b: 'One single app on your phone'),
    (a: 'A tuxedo on the beach', b: 'Swimwear at a wedding'),
    (a: 'Cooking like a starred chef', b: 'A house that cleans itself'),
    (
      a: 'A long flight next to a chatterbox',
      b: 'A long flight next to a newborn',
    ),
    (a: 'Savoury breakfast forever', b: 'Sweet dinner forever'),
    (a: 'Living without mirrors', b: 'Living without clocks'),
    (a: 'Reliving the same Monday', b: 'Skipping every Friday'),
    (a: 'Talking to plants', b: 'Understanding babies'),
    (a: 'Always winning at cards', b: 'Always finding a parking space'),
    (a: 'A 40 degree summer with no sea', b: 'A freezing winter with no snow'),
    (
      a: 'Only terribly dubbed films',
      b: 'Only films with out-of-sync subtitles',
    ),
    (a: 'Free coffee for life', b: 'Free ice cream for life'),
    (a: 'Moving house every year', b: 'The same house forever'),
    (
      a: 'An embarrassing ringtone forever',
      b: 'An embarrassing wallpaper forever',
    ),
    (a: 'Being a famous meme', b: 'Having a famous lookalike'),
    (
      a: 'Dancing the macarena at every greeting',
      b: 'Greeting everyone with a bow',
    ),
    (a: 'Chocolate spread without bread', b: 'Bread without chocolate spread'),
    (
      a: 'An endless weekend of constant rain',
      b: 'Only Mondays but always sunny',
    ),
    (
      a: 'One dish cooked to perfection',
      b: 'Cooking everything just about okay',
    ),
  ];

  /// Dilemmi da modalità Hot: parità completa col mazzo italiano.
  static const List<({String a, String b, String tone})>
  hot = <({String a, String b, String tone})>[
    (
      a: 'Walk around naked for a minute',
      b: 'Kiss someone in this group',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Spend the night with someone in the group',
      b: 'A night with an old teacher of yours',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Show the group your photo gallery',
      b: 'Have your chats read out loud',
      tone: ContentTone.piccante,
    ),
    (
      a: 'A year without sex',
      b: 'A year without going out at night',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Tell the group your body count',
      b: 'Show your last search',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Love without sex',
      b: 'Sex without love',
      tone: ContentTone.piccante,
    ),
    (
      a: 'A gorgeous partner but awful in bed',
      b: 'An average partner but phenomenal',
      tone: ContentTone.piccante,
    ),
    (
      a: 'A night with your ex',
      b: 'A night with a stranger',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Catching your parents in the act',
      b: 'Getting caught by your parents',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Tell everyone who you fancy right now',
      b: 'Never speak to your crush again',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Kiss someone in the group with your eyes closed',
      b: 'Kiss your ex in front of everyone',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Never being able to kiss again',
      b: 'Never being able to hug again',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Knowing who your partner would cheat on you with',
      b: 'Never knowing it',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Only blind dates for a year',
      b: 'Only dates chosen by your mother',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Rewatch the video of your first kiss',
      b: 'Have the whole group rewatch it',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Moan every time you sit down',
      b: 'Shout your ex\'s name at every toast',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Send a nude to your ex by mistake',
      b: 'Send it to the family group chat',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Sexting your boss by mistake',
      b: 'Calling your partner by your ex\'s name',
      tone: ContentTone.piccante,
    ),
    (
      a: 'A night with a celebrity',
      b: 'A month of sex with your ex',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Have sex only in total darkness',
      b: 'Only with the light always on',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Tell your weirdest fantasy',
      b: 'Hear the one from the person on your right',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Friends with benefits with your best friend',
      b: 'No more sex for a year',
      tone: ContentTone.piccante,
    ),
    (
      a: 'An ex who kisses like a god',
      b: 'A new one to train from scratch',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Being undressed by someone\'s eyes at the bar',
      b: 'Never being noticed again',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Tell your worst date ever',
      b: 'Relive your hottest embarrassing moment',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Always make the first move',
      b: 'Always wait for the other to start',
      tone: ContentTone.piccante,
    ),
    (
      a: 'A threesome with strangers',
      b: 'A threesome with friends',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Catch your flatmate in action',
      b: 'Get caught by your flatmate',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Say how many times a day you think about it',
      b: 'Say when you last did it',
      tone: ContentTone.piccante,
    ),
    (
      a: 'A super jealous but red-hot partner',
      b: 'A chill partner but lazy in bed',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Kiss the first person through the door',
      b: 'Kiss the last person who texted you',
      tone: ContentTone.piccante,
    ),
    (
      a: 'A night of passion without kissing',
      b: 'Endless kissing but nothing else',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Forget your first time',
      b: 'Remember it every single day',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Say the most absurd place you\'ve done it',
      b: 'Say the place where you\'d like to',
      tone: ContentTone.piccante,
    ),
    (
      a: 'A fling with your personal trainer',
      b: 'A fling with your doctor',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Only one night stands for a year',
      b: 'Only serious relationships for life',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Hook up with your ex now and then',
      b: 'End it forever but with regret',
      tone: ContentTone.piccante,
    ),
    (
      a: 'A make-out with the person on your left',
      b: 'A sensual slow dance with the person on your right',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Sleep naked with a friend',
      b: 'Shower in your swimsuit with your ex',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Receive an unsolicited nude from your boss',
      b: 'Send one to your boss by mistake',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Mind-blowing sex once a month',
      b: 'Mediocre sex every day',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Know what the other thinks in bed',
      b: 'Have them hear your every thought in bed',
      tone: ContentTone.piccante,
    ),
    (
      a: 'A weekend with your secret crush',
      b: 'A month with your first love',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Breakfast in bed after the first night',
      b: 'Disappear before dawn',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Say your weak spot in bed',
      b: 'Mime it in front of the group',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Tattoo your ex\'s name',
      b: 'Shout their name at the wrong moment',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Match with your ex on an app',
      b: 'Match with your boss on an app',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Your partner knows your every fantasy',
      b: 'You know every fantasy of theirs',
      tone: ContentTone.piccante,
    ),
    (
      a: 'An improvised striptease right now',
      b: 'A spicy tale of your summer',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Kiss someone in the group of your choice',
      b: 'Kiss one chosen by the group',
      tone: ContentTone.piccante,
    ),
    (
      a: 'A secret, super passionate relationship',
      b: 'An official but lukewarm relationship',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Have sex only in summer',
      b: 'Have sex only in winter',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Forget every wild night of yours',
      b: 'Remember even the ones best forgotten',
      tone: ContentTone.piccante,
    ),
    (
      a: 'A hot audio sent to the wrong person',
      b: 'Receiving one from your boss',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Show your messages with your ex',
      b: 'Show your photos with your ex',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Love at first sight tonight',
      b: 'A one-night adventure tonight',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Say your crush\'s name to the group',
      b: 'Make the group guess it',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Dance a slow with your ex tonight',
      b: 'Romantic karaoke with someone in the group',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Hit on a stranger right now',
      b: 'Give your number to the first who asks',
      tone: ContentTone.piccante,
    ),
    (
      a: 'A massage from someone in the group',
      b: 'Give one to someone in the group',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Forbidden to flirt for a year',
      b: 'Forced to flirt with everyone',
      tone: ContentTone.piccante,
    ),
    (
      a: 'A night with your music idol',
      b: 'A weekend with your favourite actor',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Confess a hot dream about someone here',
      b: 'Have someone here confess one about you',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Total silence in bed',
      b: 'Full running commentary in bed',
      tone: ContentTone.piccante,
    ),
    (
      a: 'A killer booty',
      b: 'A cleavage worth applause',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Your ex becomes super famous',
      b: 'Your ex becomes your boss',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Say what turns you on the most',
      b: 'Say what turns you off instantly',
      tone: ContentTone.piccante,
    ),
    (
      a: 'A summer affair never confessed',
      b: 'An endless long-distance love',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Two people here are hitting on you',
      b: 'Hitting on two people here at once',
      tone: ContentTone.piccante,
    ),
    (
      a: 'See your ex with someone hotter than you',
      b: 'Have them see you with someone worse than them',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Kisses with a bite',
      b: 'Pecks on the lips forever',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Sleep cuddled up without sex',
      b: 'Sex but never sleeping together',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Have sex with the music blasting',
      b: 'With the news on in the background',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Reveal your number of exes',
      b: 'Reveal who was the best',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Hit on the waiter tonight',
      b: 'Leave him your number on the receipt',
      tone: ContentTone.piccante,
    ),
    (
      a: 'An awkward but sweet first time',
      b: 'Perfect but with the wrong person',
      tone: ContentTone.piccante,
    ),
    (
      a: 'A tattoo where the group decides',
      b: 'A piercing where the group decides',
      tone: ContentTone.piccante,
    ),
    (
      a: 'A 30-second kiss with someone here',
      b: 'Ten quick kisses with ten strangers',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Know who in the group dreams about you at night',
      b: 'Know who would never kiss you',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Sex in a tent on a packed campsite',
      b: 'In a hotel with paper-thin walls',
      tone: ContentTone.piccante,
    ),
    (
      a: 'A singles-only holiday',
      b: 'A couples-only holiday',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Anal sex every time',
      b: 'No more sex for a year',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Being dominated',
      b: 'Being dominant',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Have sex with two people at once',
      b: 'Go without it for six months',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Get filmed while you do it',
      b: 'Never do it again',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Lick everywhere',
      b: 'Be licked everywhere',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Swallow',
      b: 'Spit',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Get blindfolded and tied up',
      b: 'Be the one who blindfolds and ties',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Wild sex with a stranger',
      b: 'Mediocre sex with the ideal partner',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Make him swallow',
      b: 'Make him spit it on you',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'A threesome with strangers',
      b: 'With two close friends from here',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Only oral sex for a year',
      b: 'Never oral sex again',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Always receive oral',
      b: 'Always be the one giving it',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Oral finished in the mouth',
      b: 'Oral finished on the face',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Lick until orgasm',
      b: 'Be licked until orgasm',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'A 30-minute blowjob',
      b: 'Come in 30 seconds',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'A threesome with two strangers',
      b: 'Watch your partner with someone else',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'A threesome with two men',
      b: 'A threesome with two women',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'An eight-person orgy',
      b: 'Solo sex for a year',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Watch your partner fuck someone else',
      b: 'Be watched while you fuck',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'A stranger watches you come',
      b: 'You watch a stranger come',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Get tied up and blindfolded',
      b: 'Tie up and blindfold them',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Be gently whipped',
      b: 'Whip your partner yourself',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Submissive for a night',
      b: 'Dominatrix for a night',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'A collar and leash on you',
      b: 'Put them on your partner',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Spanked until it leaves a mark',
      b: 'Spank until you leave a mark',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Tied to the bed all night',
      b: 'Tie your partner to the bed',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Blindfolded and at your partner\'s mercy',
      b: 'Blindfold them and take charge',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'A vibrator for an hour without stopping',
      b: 'No orgasm for a month',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Orgasm denied for days',
      b: 'Forced orgasms over and over',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'A plug worn all day',
      b: 'A vibrator in public',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Try every sex toy in the shop',
      b: 'Only hands forever',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'A huge dildo',
      b: 'A small but constant vibrator',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Real handcuffs on your wrists',
      b: 'Silk ropes on your body',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Sex in the bathroom of a club',
      b: 'Sex in a dark alley',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Do it on the beach at night',
      b: 'Do it in an elevator',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Sex in a car in a car park',
      b: 'Sex on a rooftop at night',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Risk getting caught at the office',
      b: 'Do it in a fitting room',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Sex on a moving train',
      b: 'Sex under a crowded table',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'A hot video of you goes around',
      b: 'Your hot chats go around',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Your nude photos on his phone',
      b: 'An intimate video of you saved',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Record while you do it',
      b: 'Photograph yourself naked for him',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'A nude sent to your boss by mistake',
      b: 'A nude seen by your friends',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Have sex in front of a webcam',
      b: 'Have sex with the light always on',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Rough and merciless sex',
      b: 'Slow sex all night',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Come five times in a row',
      b: 'One single very long orgasm',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Always fake your orgasm',
      b: 'Never come again',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'An orgasm every hour for a day',
      b: 'No orgasm for a year',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Squirt in front of him',
      b: 'Watch him come on your body',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Anal sex',
      b: 'Double penetration',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Try anal for the first time',
      b: 'Never try it',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Pick up a stranger tonight',
      b: 'An ex for one last night',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'A night with your movie idol',
      b: 'A night with your best ex',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Sex with his best friend',
      b: 'Sex with her best friend',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Partner swap with friends',
      b: 'A swap with total strangers',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Kiss everyone at an orgy',
      b: 'Choose only one person',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'A massage that ends in bed',
      b: 'A private lap dance',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'A striptease in front of the group',
      b: 'Pole dance naked',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Lick the cream off his body',
      b: 'Have him lick the chocolate off you',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Sex covered in oil',
      b: 'Sex under a scalding shower',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'A foot fetish satisfied',
      b: 'A butt fetish satisfied',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Have your toes sucked',
      b: 'Suck his',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Wear only lingerie to dinner out',
      b: 'No underwear to dinner out',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'A tight corset all evening',
      b: 'Stilettos and nothing else',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Sex with a mask on your face',
      b: 'Sex in total darkness',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Say your fantasies out loud',
      b: 'Act out a random one',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'A teacher and student roleplay',
      b: 'A boss and secretary roleplay',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Pretend to be two strangers in a bar',
      b: 'Pretend to be exes reuniting',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Sex while the others sleep nearby',
      b: 'Sex screaming with no restraint',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Have dirty things whispered in your ear',
      b: 'Say them to him yourself',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Sexting all day at work',
      b: 'Hot photos every hour',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'A blowjob while he drives',
      b: 'A fingering at the cinema',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Seduce him with a look for an hour',
      b: 'Jump on him right away',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Ride him until he\'s spent',
      b: 'Let yourself be taken from behind',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Sex in three positions in a row',
      b: 'An hour in the same position',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Make him come with your hands only',
      b: 'Only with your mouth',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'A blindfolded blowjob',
      b: 'Blindfolded sex',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Ice on bare skin',
      b: 'Hot wax on the body',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Bite until it leaves marks',
      b: 'Scratch the back deeply',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Visible hickeys on the neck',
      b: 'Bite marks on the inner thigh',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Sex with one partner forever',
      b: 'A different partner every month',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'See your partner naked with someone else',
      b: 'Never know what they\'re doing',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'A threesome planned in detail',
      b: 'A totally improvised threesome',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Be slowly undressed by him',
      b: 'Undress him with your teeth',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Sex with him in uniform',
      b: 'Sex with you in uniform',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'A long foreplay without penetration',
      b: 'Penetration right away with no foreplay',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Edging for an hour',
      b: 'Immediate orgasm and done',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Get touched in a crowded club',
      b: 'Touch him under the table',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'An extra finger during sex',
      b: 'An extra tongue during sex',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Sex in front of the mirror',
      b: 'Sex filmed on the phone',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Wear a plug at dinner with the in-laws',
      b: 'A vibrator controlled by him',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'A remote-controlled vibrator on the metro',
      b: 'A remote-controlled vibrator at the restaurant',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'A long spanking session',
      b: 'A long bondage session',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Suspended with Japanese ropes',
      b: 'Immobilized with duct tape',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'A full-body massage from someone in the group',
      b: 'A shower together with someone in the group',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Kiss the colleague you\'ve fancied for months',
      b: 'Be told they feel the same but they\'re taken',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Slow sex all night',
      b: 'Fast, overwhelming sex in a minute',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Say your safe word out loud',
      b: 'Mime your favourite position',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Steamy flirt with your ex\'s best friend',
      b: 'A steamy flirt with your neighbour',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Have sex only in public places',
      b: 'Have sex only with the door open',
      tone: ContentTone.piccante,
    ),
    (
      a: 'A weekend of pure sex without talking',
      b: 'A weekend of just cuddles without sex',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Get a lap dance from the person on your right',
      b: 'Give one to the person on your left',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Confess which person here you\'d court',
      b: 'Have the group pick you a suitor',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Try everything in one night with the stranger',
      b: 'Stay chaste for a year with true love',
      tone: ContentTone.piccante,
    ),
    (
      a: 'A French kiss with your first love',
      b: 'An endless hug with your latest crush',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Kiss everyone here in turn',
      b: 'Kiss just one for ten minutes',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Say how long you last in bed on average',
      b: 'Say your personal record',
      tone: ContentTone.piccante,
    ),
    (
      a: 'A forbidden encounter with your dance teacher',
      b: 'A forbidden encounter with the barista downstairs',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Seduce a stranger in ten minutes',
      b: 'Be seduced without saying a word',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Only provocative lingerie for a month',
      b: 'Only baggy pyjamas for a year',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Have sex with the same partner forever',
      b: 'A different partner every week without love',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Be slowly undressed by the person in front of you',
      b: 'Undress the person next to you',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Say the fantasy you\'ve never fulfilled',
      b: 'Fulfil it tonight with someone here',
      tone: ContentTone.piccante,
    ),
    (
      a: 'A passionate kiss in the rain',
      b: 'A night of fire by the fireplace',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Sex with the most beautiful person you\'ve ever seen',
      b: 'Unforgettable sex with someone you truly love',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Have your neck bitten by the person on your right',
      b: 'Bite the neck of the person on your left',
      tone: ContentTone.piccante,
    ),
    (
      a: 'How many times you\'ve thought about someone here',
      b: 'Have someone here confess how often they think of you',
      tone: ContentTone.piccante,
    ),
    (
      a: 'A year of nothing but flings with no tomorrow',
      b: 'A year of just waiting for the right person',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Kiss someone blindfolded and guess who it is',
      b: 'Get kissed and have everyone guess',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Wild sex but never seeing each other again',
      b: 'Endless waiting but then forever',
      tone: ContentTone.piccante,
    ),
    (
      a: 'A provocative dance in front of the whole group',
      b: 'A surprise kiss chosen by the group',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Shower together with your ex',
      b: 'Bathe together with your crush',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Say who in the group you\'d kiss in the dark',
      b: 'Say who in the group you\'d never kiss',
      tone: ContentTone.piccante,
    ),
    (
      a: 'A foot massage from a sexy stranger',
      b: 'A back massage from your ex',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Have sex only by darkness and candlelight',
      b: 'Have sex only in front of the mirror',
      tone: ContentTone.piccante,
    ),
    (
      a: 'A secret flirt with your swimming instructor',
      b: 'A secret flirt with your tattoo artist',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Reveal the most risque object you own',
      b: 'Show it to the group',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Spend the night with your high-school crush',
      b: 'Spend the night with your current crush',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Only slow kisses for a month',
      b: 'Only nights of passion but no kissing',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Have hot things whispered in your ear',
      b: 'Whisper them to the person next to you',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Say the hot nickname you give your partner',
      b: 'Say the one your partner gives you',
      tone: ContentTone.piccante,
    ),
    (
      a: 'A night with someone who rejected you years ago',
      b: 'A night with someone who\'s always wanted you',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Have sex on the first date every time',
      b: 'Wait three months every time',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Kiss the person in front of you for twenty seconds',
      b: 'Hug the person behind you for two minutes',
      tone: ContentTone.piccante,
    ),
    (
      a: 'The riskiest place you\'ve tried it',
      b: 'The most absurd hour you\'ve done it',
      tone: ContentTone.piccante,
    ),
    (
      a: 'A spa weekend alone with someone in the group',
      b: 'A romantic cruise with a stranger',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Have your mind read during a kiss',
      b: 'Read the thoughts of whoever you kiss',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Only steamy dates but never a second one',
      b: 'Only sweet dates but no spark',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Reveal how many people here you\'d find attractive',
      b: 'Have everyone tell you if they find you attractive',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Have sex listening to your favourite song',
      b: 'Do it in total silence',
      tone: ContentTone.piccante,
    ),
    (
      a: 'A night with a model but no words',
      b: 'A night with a funny one but no sex',
      tone: ContentTone.piccante,
    ),
    (
      a: 'A passionate make-out with the person on your right',
      b: 'A sensual massage from the person on your left',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Which body part makes you lose your head',
      b: 'Have the group guess it',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Seduce your crush using only emojis',
      b: 'Seduce them with a single awkward voice note',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Have sex only early in the morning',
      b: 'Have sex only in the dead of night',
      tone: ContentTone.piccante,
    ),
    (
      a: 'A stolen kiss from your boss on a bet',
      b: 'A stolen kiss from your partner\'s best friend',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Confess your fantasy about a celebrity',
      b: 'Hear the one from the person in front of you',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Only long-distance but passionate relationships',
      b: 'Only close but lukewarm relationships',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Get a clearly visible hickey',
      b: 'Give one to the person next to you',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Say how many times you\'ve made the first move',
      b: 'Say how many times you\'ve backed out',
      tone: ContentTone.piccante,
    ),
    (
      a: 'A night of passion but you forget it',
      b: 'No night but the memory of one kiss',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Kiss the shyest person in the group',
      b: 'Kiss the cheekiest one in the group',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Play strip poker with the people here',
      b: 'Play truth or dare, spicy only',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Seduce someone with just a look',
      b: 'Seduce them with just one line',
      tone: ContentTone.piccante,
    ),
    (
      a: 'A hot date decided by your ex',
      b: 'A hot date decided by your mother',
      tone: ContentTone.piccante,
    ),
    (
      a: 'A bite on the nipple',
      b: 'Clamps on the nipples',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'A blindfold and surprises out of nowhere',
      b: 'Knowing everything in advance',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Be verbally humiliated in bed',
      b: 'Verbally humiliate him',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'A master for a night',
      b: 'A slave for a night',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Obey every order for an hour',
      b: 'Give the orders for an hour',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Sex with a safe word',
      b: 'Sex with no agreed limits',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'A threesome with an escort',
      b: 'A threesome with a friend',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Get filmed by a third person present',
      b: 'Just get watched by a third person',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Sex on a balcony in plain view',
      b: 'Sex in the garden at night',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'A quickie in the kitchen',
      b: 'A marathon in the bedroom',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Do it on the dining table',
      b: 'Do it against the hallway wall',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Sex right after waking every morning',
      b: 'Sex only at midnight every night',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Try wax play',
      b: 'Try temperature play',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'A vibrator while he watches you',
      b: 'His hands while you watch yourself',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Masturbate in front of him',
      b: 'Watch him masturbate for you',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'An orgasm from words alone',
      b: 'An orgasm from a toy alone',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Sex with the cum on your face',
      b: 'Sex with the cum on your body',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Have him finish inside',
      b: 'Have him finish outside',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'A creampie',
      b: 'A facial',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Lick him after he comes',
      b: 'Get licked after you come',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Sex in broad daylight',
      b: 'Sex only by candlelight',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Sex with music at full blast',
      b: 'Sex in total silence',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Have your wrists tied with a tie',
      b: 'Tie your ankles with stockings',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'A blindfold and noise-cancelling headphones',
      b: 'Just the blindfold over the eyes',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Dominate completely for a day',
      b: 'Submit completely for a day',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Sex in a tent while camping',
      b: 'Sex in the pool at night',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Sex on the back seat',
      b: 'Sex on the bonnet',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Try pegging',
      b: 'Try rimming',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'A strap-on for her',
      b: 'A vibrating ring for him',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Take it all the way in your mouth',
      b: 'Take him all the way',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Deep throat',
      b: 'Face sitting',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Sit on his face',
      b: 'Have him sit on yours',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'An endless sixty-nine',
      b: 'Take turns',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Sex with a warming lubricant',
      b: 'Sex with a cooling gel',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Get blindfolded and guess the toys',
      b: 'Guess his hands while blindfolded',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'A nurse and patient roleplay',
      b: 'A policewoman and arrested man roleplay',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Pretend to be strangers in a hotel',
      b: 'Pretend to be nosy neighbours',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Sex with the lingerie torn off you',
      b: 'Sex staying almost fully dressed',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Have your panties ripped off',
      b: 'Rip off his boxers with your teeth',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'An orgasm in under a minute',
      b: 'Hold on for twenty minutes',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Count the orgasms out loud',
      b: 'Stay completely silent',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'A threesome with your crush',
      b: 'A threesome with his crush',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Watch porn together and imitate it',
      b: 'Make it all up with no reference',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Recreate a famous porn scene',
      b: 'Shoot your own amateur video',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Sex with the heels still on',
      b: 'Sex completely naked',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Wear a love egg all day',
      b: 'A plug all afternoon',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'A full erotic massage',
      b: 'An erotic bath for two',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Sex with scented oil everywhere',
      b: 'Sex covered in foam',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Have him seduced by another woman in front of you',
      b: 'Seduce another man in front of him',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'A strip poker that ends in bed',
      b: 'A truth or dare, hot all the way',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Kiss a woman in front of him',
      b: 'Watch him kiss a man',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'A first sapphic kiss',
      b: 'A first gay kiss',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Sex with two hands on you',
      b: 'Sex with two mouths on you',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Have your neck gently gripped',
      b: 'Grip his wrists yourself',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'A light agreed choking',
      b: 'A firm hair pulling',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Sex with your hair pulled',
      b: 'Sex with nails down your back',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Get taken from behind in front of the mirror',
      b: 'Take him riding on top in front of the mirror',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'An orgasm denied for three days',
      b: 'Three orgasms in an hour',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Get watched while you strip on webcam',
      b: 'Watch him strip on webcam',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'A vibrator shared in turns',
      b: 'Two toys at the same time',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Sex tied to a chair',
      b: 'Sex standing against the window',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Have your lip bitten till it bleeds',
      b: 'Bite his neck fiercely',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Sex interrupted and resumed several times',
      b: 'One single session with no pauses',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Try sensory deprivation',
      b: 'Try sensory overload',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Get tickled while blindfolded',
      b: 'Tickle him while he\'s pinned down',
      tone: ContentTone.cattivo,
    ),
  ];
}
