import '../content_tone.dart';

/// Coppie di "Preferisci" in tedesco: parità completa col mazzo italiano.
class PreferisciPoolDe {
  const PreferisciPoolDe._();

  static const List<({String a, String b})> pairs = <({String a, String b})>[
    (a: 'Wissen, wie du stirbst', b: 'Wissen, wann'),
    (a: 'Eine unbequeme Wahrheit', b: 'Eine bequeme Lüge'),
    (a: 'Mehr Geld', b: 'Mehr Freizeit'),
    (a: 'Berühmt sein', b: 'Für alle unsichtbar sein'),
    (a: 'In die Vergangenheit reisen', b: 'In die Zukunft reisen'),
    (a: 'Fliegen können', b: 'Unsichtbar sein'),
    (a: 'Gedanken lesen', b: 'Die Zukunft vorhersagen'),
    (a: 'Nie mehr Social Media', b: 'Nie mehr Filme'),
    (a: 'Dein Handy verlieren', b: 'Deine Hausschlüssel verlieren'),
    (a: 'Immer 5 Minuten zu früh', b: 'Immer 10 Minuten zu spät'),
    (a: 'Netter aber unfähiger Chef', b: 'Fieser aber genialer Chef'),
    (a: 'Top Gehalt, langweiliger Job', b: 'Wenig Geld, aber Traumjob'),
    (a: 'Hochzeit mit 200 Gästen', b: 'Hochzeit zu zweit'),
    (a: 'Eine Woche nicht rausgehen', b: 'Jeden Abend ausgehen'),
    (a: 'Zehn Stunden schlafen', b: 'Fünf Stunden und top fit sein'),
    (a: 'Den perfekten Urlaub wiederholen', b: 'Einen neuen Ort ausprobieren'),
    (a: 'Jeden Tag aufs Konto schauen', b: 'Nie draufschauen'),
    (
      a: 'Nutzlose aber witzige Superkraft',
      b: 'Nützliche aber fade Superkraft',
    ),
    (a: 'Immer dasselbe Buch lesen', b: 'Nie eines fertig lesen'),
    (a: 'Leben ohne Musik', b: 'Leben ohne Kino'),
    (a: 'Immer die Wahrheit kennen', b: 'Glücklich in der Illusion leben'),
    (a: 'Ein Sabbatjahr', b: 'Ein Jahr früher in Rente'),
    (a: 'Alle Sprachen sprechen', b: 'Alle Instrumente spielen'),
    (a: 'Nie peinlich berührt sein', b: 'Nie Angst haben'),
    (a: 'Deinen besten Tag neu erleben', b: 'Den schlimmsten löschen'),
    (
      a: 'Nach einem Monat zusammenziehen',
      b: 'Erst nach Jahren zusammenziehen',
    ),
    (a: 'Früh Kinder', b: 'Spät Kinder'),
    (a: 'Urlaub bis ins Detail geplant', b: 'Einfach losfahren'),
    (a: 'Eine Staffel in einer Nacht', b: 'Eine Folge pro Woche'),
    (a: 'Akku immer bei 1%', b: 'Extrem langsames Internet'),
    (a: 'Klamotten immer etwas feucht', b: 'Für immer ein Stein im Schuh'),
    (a: 'Immer sagen, was du denkst', b: 'Nie mehr sprechen können'),
    (a: 'Keine Heizung im Winter', b: 'Keine Klimaanlage im Sommer'),
    (a: 'Für immer Schluckauf', b: 'Alle zwei Minuten niesen'),
    (a: 'Lieblingsessen bei jeder Mahlzeit', b: 'Nie mehr dein Lieblingsessen'),
    (a: 'Nie mehr schlafen müssen', b: 'Nie mehr essen müssen'),
    (a: 'Reich aber ohne Freunde', b: 'Pleite aber sehr beliebt'),
    (a: 'Nie mehr Miete zahlen', b: 'Doppeltes Gehalt'),
    (a: 'Der Lustigste im Raum', b: 'Der Klügste im Raum'),
    (a: 'Fotografisches Gedächtnis', b: 'Jede Blamage vergessen'),
    (a: 'Nie mehr Schlangen', b: 'Nie mehr Staus'),
    (a: 'Ein Jahr rasierte Augenbrauen', b: 'Ein Jahr neongrüne Haare'),
    (a: 'Den Geruchssinn verlieren', b: 'Den Geschmack verlieren'),
    (a: 'Eine Cartoon-Stimme', b: 'Ein Lachen, das alle nervt'),
    (a: 'Verlauf für die Eltern sichtbar', b: 'Chats vom Chef gelesen'),
    (a: 'Nach jedem Satz rülpsen', b: 'Wie eine Ziege lachen'),
    (a: 'Fremde Zahnbürste benutzen', b: 'Aus seinem benutzten Glas trinken'),
    (a: 'Immer feuchte Hände', b: 'Immer spröde Lippen'),
    (a: 'Mit deinem Ex ausgehen', b: 'Mit dem Ex des besten Freundes'),
    (a: 'Laute aber geruchlose Pupse', b: 'Lautlos aber tödlich'),
    (a: 'Vergessen, wer du bist', b: 'Von allen vergessen werden'),
    (a: 'Dein ganzes Geld verlieren', b: 'Alle Erinnerungen verlieren'),
    (a: 'Reicher aber langweiliger Partner', b: 'Armer aber witziger Partner'),
    (
      a: 'Eine Stunde im Aufzug mit dem Ex',
      b: 'Eine Stunde im Aufzug mit dem Chef',
    ),
    (a: 'Geburtstag von allen vergessen', b: 'Peinliche Überraschungsparty'),
    (
      a: 'Dein Geheimnis wird allen verraten',
      b: 'Die Geheimnisse aller kennen',
    ),
    (a: 'Berühmt aber gehasst', b: 'Unbekannt aber geliebt'),
    (a: 'Nie mehr lachen', b: 'Nie mehr weinen'),
    (
      a: 'Ein Jahr zurück in die Schule',
      b: 'Jedes Jahr das Abitur wiederholen',
    ),
    (a: 'Im Horrorfilm leben', b: 'Im Musical leben'),
    (a: 'Füße statt Hände', b: 'Hände statt Füße'),
    (
      a: 'Eine Ente so groß wie ein Pferd',
      b: 'Hundert Pferde so groß wie Enten',
    ),
    (a: 'Unter Wasser leben', b: 'Im Weltraum leben'),
    (
      a: 'Von einer Killerschnecke gejagt',
      b: 'Ein Clown starrt dich nachts an',
    ),
    (a: 'Mit Tieren sprechen', b: 'Das Wetter steuern'),
    (a: 'Tanzen, sobald Musik läuft', b: 'Weinen, wenn jemand lacht'),
    (
      a: 'Jeden Morgen in einem anderen Land',
      b: 'Nie mehr aus deiner Stadt raus',
    ),
    (a: 'In einem Videospiel leben', b: 'In einem Zeichentrickfilm leben'),
    (
      a: 'Eine Pause-Taste für das Leben',
      b: 'Eine Rückspul-Taste für das Leben',
    ),
    (a: 'Teleportieren ohne Schuhe', b: 'Fliegen im Schritttempo'),
    (a: '1000 Jahre leben', b: 'Zehn Leben à 100 Jahre'),
    (a: 'Tacos-Regen', b: 'Eis-Schnee'),
    (a: 'Einen Tag König der Welt', b: 'Für immer ein normaler Mensch'),
    (a: 'Alles wissen ohne Gefühle', b: 'Alles fühlen ohne Verstehen'),
    (a: 'Ein Bedauern löschen', b: 'Einen Erfolg garantiert bekommen'),
    (a: 'Immer hungrig', b: 'Immer müde'),
    (
      a: 'Ein Schwanz, der bei Freude wackelt',
      b: 'Ohren, die bei Trauer hängen',
    ),
    (a: 'Für immer auf Kaffee verzichten', b: 'Auf Schokolade verzichten'),
    (a: 'Nase wächst beim Lügen', b: 'Haare wechseln die Farbe je nach Laune'),
    (a: 'Die Liebe deines Lebens finden', b: 'Den Traumjob finden'),
    (a: 'Superreich aber immer traurig', b: 'Pleite aber immer glücklich'),
    (a: 'Eine Million sofort', b: '3.000 Euro im Monat für immer'),
    (a: 'Deinen Hund retten', b: 'Einen Fremden retten'),
    (a: 'Nie lügen können', b: 'Jede Lüge glauben'),
    (
      a: 'Immer recht haben aber allein',
      b: 'Falsch liegen aber in Gesellschaft',
    ),
    (a: 'Verkanntes Genie', b: 'Glücklicher Einfaltspinsel'),
    (a: 'Jeden Tag dasselbe Outfit', b: 'Nie ein Outfit wiederholen'),
    (a: 'Alles singen, was du sagst', b: 'Nur rückwärts laufen'),
    (a: 'Überall gratis WLAN, für immer', b: 'Für immer gratis fliegen'),
    (a: 'Nur kochend heißes Essen', b: 'Nur eiskaltes Essen'),
    (a: 'Nie mehr Pizza', b: 'Nie mehr Pasta'),
    (a: 'Nie mehr Aperitifs', b: 'Nie mehr Lieferessen'),
    (a: 'Langes Leben voller Reue', b: 'Kurzes Leben ohne Reue'),
    (a: 'Lieben ohne Gegenliebe', b: 'Geliebt werden ohne Liebe'),
    (a: 'Der Partner liest deine Gedanken', b: 'Du liest seine Gedanken'),
    (
      a: 'Partner von Freunden ausgesucht',
      b: 'Partner vom Algorithmus gewählt',
    ),
    (a: 'Immer Lügner erkennen', b: 'Beim Lügen nie erwischt werden'),
    (a: 'Für immer 18 sein', b: 'Direkt auf 40 springen'),
    (a: 'Immer bei anderen schlafen', b: 'Immer Gäste bei dir haben'),
    (
      a: 'Konzert deiner Band aber allein',
      b: 'Festival mit Freunden, Musik grässlich',
    ),
    (a: 'Falsch singendes Karaoke vor allen', b: 'Eine Stunde allein tanzen'),
    (a: 'Alle Handyfotos verlieren', b: 'Alle Chats verlieren'),
    (a: 'Konfetti niesen', b: 'Seifenblasen rülpsen'),
    (a: 'Vier Arme haben', b: 'Vier Beine haben'),
    (a: '2,20 Meter groß sein', b: '1,20 Meter groß sein'),
    (a: 'Leben ohne Sommer', b: 'Leben ohne Winter'),
    (a: 'Fünf Fremde retten', b: 'Deinen besten Freund retten'),
    (a: 'Eine Million ohne Smartphone', b: 'Kein Geld aber mit Handy'),
    (a: 'Traumjob im Ausland', b: 'Fader Job bei den Freunden'),
    (a: 'Für immer 25 sein', b: 'Mit deinen Freunden altern'),
    (a: 'Traumhaus mitten im Nichts', b: 'Einzimmerwohnung im Zentrum'),
    (
      a: 'Wissen, was hinter dem Rücken läuft',
      b: 'Ruhig leben, ohne es zu wissen',
    ),
    (a: 'Jede Mahlzeit von einem Chef', b: 'Ein Privatchauffeur für immer'),
    (
      a: 'Alles laut kommentieren, was du tust',
      b: 'Die Erzählerstimme deines Lebens hören',
    ),
    (a: 'Jeden Morgen auf Lego treten', b: 'Jeden Morgen eiskalt duschen'),
    (a: 'Jede Nacht eine Mücke im Raum', b: 'Bei jeder Mahlzeit eine Fliege'),
    (a: 'Für immer irre Autokorrektur', b: 'Nie mehr Emojis'),
    (a: 'Anrufe nur über Lautsprecher', b: 'Display immer für alle sichtbar'),
    (a: 'Dein Hund spricht und kritisiert', b: 'Dein Spiegel lügt dich schön'),
    (a: 'Eine Million nur für dich', b: 'Hunderttausend pro Person'),
    (a: 'Immer unterschätzt werden', b: 'Immer überschätzt werden'),
    (a: 'Lieblingsserie neu entdecken', b: 'Jedes Finale vorab sehen'),
    (a: 'Nur schreiend sprechen', b: 'Nur flüsternd sprechen'),
    (a: 'In ernsten Momenten lachen', b: 'Bei jeder Komödie weinen'),
    (a: 'Immer mit den Händen essen', b: 'Alles mit dem Teelöffel essen'),
    (a: 'Deine Träume für Freunde sichtbar', b: 'Freunde lesen dein Tagebuch'),
    (a: 'Für immer der einzige Single', b: 'Als Erster in der Gruppe heiraten'),
    (a: 'In den 80ern geboren werden', b: 'Im Jahr 2050 geboren werden'),
    (
      a: 'Gratis essen aber immer allein',
      b: 'Immer zahlen aber in Gesellschaft',
    ),
    (a: 'Viral wegen einer Blamage', b: 'Nie mehr als 10 Likes'),
    (a: 'Für immer nur Wasser trinken', b: 'Nie mehr Wasser, nur Limo'),
    (a: 'Für immer nur ein Musikgenre', b: 'Nur eine App auf dem Handy'),
    (a: 'Im Smoking am Strand', b: 'In Badehose auf einer Hochzeit'),
    (a: 'Wie ein Sternekoch kochen', b: 'Eine Wohnung, die sich selbst putzt'),
    (a: 'Langer Flug neben einem Schwätzer', b: 'Langer Flug neben einem Baby'),
    (a: 'Für immer salziges Frühstück', b: 'Für immer süßes Abendessen'),
    (a: 'Leben ohne Spiegel', b: 'Leben ohne Uhren'),
    (a: 'Denselben Montag neu erleben', b: 'Alle Freitage überspringen'),
    (a: 'Mit Pflanzen sprechen', b: 'Babys verstehen'),
    (a: 'Immer beim Kartenspiel gewinnen', b: 'Immer einen Parkplatz finden'),
    (a: '40 Grad Sommer ohne Meer', b: 'Eiskalter Winter ohne Schnee'),
    (
      a: 'Nur schlecht synchronisierte Filme',
      b: 'Nur Filme mit versetzten Untertiteln',
    ),
    (a: 'Für immer gratis Kaffee', b: 'Für immer gratis Eis'),
    (a: 'Jedes Jahr umziehen', b: 'Für immer dieselbe Wohnung'),
    (
      a: 'Für immer peinlicher Klingelton',
      b: 'Für immer peinlicher Hintergrund',
    ),
    (a: 'Ein berühmtes Meme sein', b: 'Einen berühmten Doppelgänger haben'),
    (a: 'Zur Begrüßung Macarena tanzen', b: 'Alle mit einer Verbeugung grüßen'),
    (a: 'Nutella ohne Brot', b: 'Brot ohne Nutella'),
    (a: 'Endloses Wochenende mit Regen', b: 'Nur Montage aber immer Sonne'),
    (a: 'Nur ein Gericht, aber perfekt', b: 'Alles nur mittelmäßig kochen'),
  ];

  /// Dilemmi da modalità Hot: parità completa col mazzo italiano.
  static const List<({String a, String b, String tone})>
  hot = <({String a, String b, String tone})>[
    (
      a: 'Eine Minute nackt herumlaufen',
      b: 'Jemanden aus dieser Gruppe küssen',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Die Nacht mit jemandem aus der Gruppe verbringen',
      b: 'Eine Nacht mit einem alten Lehrer von dir',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Der Gruppe deine Galerie zeigen',
      b: 'Deine Chats laut vorlesen lassen',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Ein Jahr ohne Sex',
      b: 'Ein Jahr, ohne abends auszugehen',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Der Gruppe deinen Body Count sagen',
      b: 'Deine letzte Suche zeigen',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Liebe ohne Sex',
      b: 'Sex ohne Liebe',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Schöner Partner, aber mies im Bett',
      b: 'Normaler Partner, aber phänomenal',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Eine Nacht mit deinem Ex',
      b: 'Eine Nacht mit einem Fremden',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Deine Eltern erwischen',
      b: 'Von deinen Eltern erwischt werden',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Allen sagen, wen du gerade magst',
      b: 'Nie wieder mit deinem Schwarm sprechen',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Mit geschlossenen Augen jemanden aus der Gruppe küssen',
      b: 'Deinen Ex vor allen küssen',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Nie wieder küssen können',
      b: 'Nie wieder umarmen können',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Wissen, mit wem dein Partner dich betrügen würde',
      b: 'Es nie erfahren',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Ein Jahr lang nur Blind Dates',
      b: 'Nur Dates, die deine Mutter aussucht',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Deinen ersten Kuss auf Video wiedersehen',
      b: 'Dass die ganze Gruppe ihn sieht',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Jedes Mal stöhnen, wenn du dich hinsetzt',
      b: 'Bei jedem Anstoßen den Namen deines Ex rufen',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Aus Versehen ein Nude an den Ex schicken',
      b: 'Es in die Familiengruppe schicken',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Aus Versehen mit dem Chef sexten',
      b: 'Den Partner mit dem Namen des Ex rufen',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Eine Nacht mit einem Star',
      b: 'Ein Monat Sex mit deinem Ex',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Sex nur in völliger Dunkelheit',
      b: 'Nur bei immer eingeschaltetem Licht',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Deine seltsamste Fantasie verraten',
      b: 'Die von dem rechts neben dir hören',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Bettgeschichte mit deinem besten Freund',
      b: 'Ein Jahr lang keinen Sex mehr',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Ein Ex, der göttlich küsst',
      b: 'Ein Neuer, dem du alles beibringen musst',
      tone: ContentTone.piccante,
    ),
    (
      a: 'An der Bar mit Blicken ausgezogen werden',
      b: 'Nie wieder beachtet werden',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Von deinem schlimmsten Date erzählen',
      b: 'Deine heißeste Blamage noch mal erleben',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Immer selbst den ersten Schritt machen',
      b: 'Immer warten, dass der andere anfängt',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Ein Dreier mit Fremden',
      b: 'Ein Dreier mit Freunden',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Deinen Mitbewohner in Aktion erwischen',
      b: 'Von deinem Mitbewohner erwischt werden',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Sagen, wie oft du am Tag daran denkst',
      b: 'Sagen, wann du es zuletzt getan hast',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Extrem eifersüchtiger, aber heißer Partner',
      b: 'Ruhiger, aber fauler Partner im Bett',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Den Ersten küssen, der zur Tür reinkommt',
      b: 'Den Letzten küssen, der dir geschrieben hat',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Eine Nacht voller Leidenschaft ohne Küsse',
      b: 'Endlose Küsse, aber sonst nichts',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Dein erstes Mal vergessen',
      b: 'Dich jeden einzelnen Tag daran erinnern',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Den absurdesten Ort verraten, wo du es getan hast',
      b: 'Den Ort verraten, wo du es tun möchtest',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Ein Flirt mit deinem Personal Trainer',
      b: 'Ein Flirt mit deinem Arzt',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Ein Jahr lang nur One-Night-Stands',
      b: 'Lebenslang nur feste Beziehungen',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Ab und zu wieder was mit dem Ex anfangen',
      b: 'Für immer Schluss, aber mit Reue',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Rummachen mit dem links neben dir',
      b: 'Ein sinnlicher Slow mit dem rechts neben dir',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Nackt neben einem Freund schlafen',
      b: 'Mit dem Ex in Badekleidung duschen',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Ein ungefragtes Nude vom Chef bekommen',
      b: 'Dem Chef aus Versehen eins schicken',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Umwerfender Sex einmal im Monat',
      b: 'Mittelmäßiger Sex jeden Tag',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Wissen, was der andere im Bett denkt',
      b: 'Dass er jeden deiner Gedanken im Bett hört',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Ein Wochenende mit deinem heimlichen Schwarm',
      b: 'Ein Monat mit deiner ersten Liebe',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Frühstück im Bett nach der ersten Nacht',
      b: 'Vor dem Morgengrauen verschwinden',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Deine Schwachstelle im Bett verraten',
      b: 'Sie vor der Gruppe vormachen',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Dir den Namen des Ex tätowieren',
      b: 'Seinen Namen im falschen Moment rufen',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Ein Match mit deinem Ex auf einer App',
      b: 'Ein Match mit deinem Chef auf einer App',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Dein Partner kennt jede deiner Fantasien',
      b: 'Du kennst jede seiner Fantasien',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Sofort ein improvisierter Striptease',
      b: 'Eine pikante Geschichte aus deinem Sommer',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Jemanden aus der Gruppe küssen, den du wählst',
      b: 'Einen küssen, den die Gruppe wählt',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Heimliche, hoch leidenschaftliche Beziehung',
      b: 'Offizielle, aber lauwarme Beziehung',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Sex nur im Sommer',
      b: 'Sex nur im Winter',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Jede deiner wilden Nächte vergessen',
      b: 'Auch die, die man besser vergisst, erinnern',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Heißes Audio an die falsche Person geschickt',
      b: 'Eins von deinem Chef bekommen',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Die Nachrichten mit dem Ex vorlesen lassen',
      b: 'Die Fotos mit dem Ex zeigen',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Heute Abend Liebe auf den ersten Blick',
      b: 'Heute Abend ein One-Night-Abenteuer',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Der Gruppe den Namen deines Schwarms sagen',
      b: 'Die Gruppe ihn erraten lassen',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Heute Abend einen Slow mit deinem Ex tanzen',
      b: 'Romantisches Karaoke mit jemandem aus der Gruppe',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Jetzt einen Fremden anbaggern',
      b: 'Dem Ersten, der fragt, deine Nummer geben',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Eine Massage von jemandem aus der Gruppe',
      b: 'Selbst einem aus der Gruppe eine geben',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Ein Jahr lang Flirtverbot',
      b: 'Flirtpflicht mit jedem',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Eine Nacht mit deinem Musikidol',
      b: 'Ein Wochenende mit deinem Lieblingsschauspieler',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Einen heißen Traum über einen Anwesenden gestehen',
      b: 'Dass ein Anwesender einen über dich gesteht',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Völlige Stille im Bett',
      b: 'Vollständige Live-Reportage im Bett',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Ein umwerfender Hintern',
      b: 'Ein Dekolleté zum Applaudieren',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Dein Ex wird superberühmt',
      b: 'Dein Ex wird dein Chef',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Sagen, was dich am meisten anmacht',
      b: 'Sagen, was dich sofort abtörnt',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Ein nie gestandener Sommerflirt',
      b: 'Eine endlose Fernbeziehung',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Zwei Anwesende machen dir den Hof',
      b: 'Zwei Anwesenden gleichzeitig den Hof machen',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Deinen Ex mit jemandem Schönerem als dir sehen',
      b: 'Dass er dich mit jemandem Schlechterem sieht',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Küsse mit Biss',
      b: 'Für immer nur brave Küsschen',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Umschlungen schlafen ohne Sex',
      b: 'Sex, aber nie zusammen schlafen',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Sex mit Musik auf voller Lautstärke',
      b: 'Mit den Nachrichten im Hintergrund',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Deine Anzahl an Ex-Partnern verraten',
      b: 'Verraten, wer der Beste war',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Heute Abend den Kellner anbaggern',
      b: 'Ihm die Nummer auf den Kassenbon schreiben',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Erstes Mal peinlich, aber süß',
      b: 'Perfekt, aber mit der falschen Person',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Ein Tattoo, über das die Gruppe entscheidet',
      b: 'Ein Piercing, über das die Gruppe entscheidet',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Ein 30-Sekunden-Kuss mit einem Anwesenden',
      b: 'Zehn schnelle Küsse mit zehn Fremden',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Wissen, wer aus der Gruppe nachts von dir träumt',
      b: 'Wissen, wer dich niemals küssen würde',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Sex im Zelt auf einem vollen Campingplatz',
      b: 'Im Hotel mit hauchdünnen Wänden',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Ein Urlaub nur für Singles',
      b: 'Ein Urlaub nur für Paare',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Jedes Mal Analsex',
      b: 'Ein Jahr lang keinen Sex mehr',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Dominiert werden',
      b: 'Dominant sein',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Sex mit zwei Personen gleichzeitig',
      b: 'Sechs Monate darauf verzichten',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Dich beim Sex filmen lassen',
      b: 'Es nie wieder tun',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Überall lecken',
      b: 'Überall geleckt werden',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Schlucken',
      b: 'Ausspucken',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Dich verbinden und fesseln lassen',
      b: 'Selbst verbinden und fesseln',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Wilder Sex mit einem Fremden',
      b: 'Mittelmäßiger Sex mit dem Traumpartner',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Ihn schlucken lassen',
      b: 'Ihn es dir auf den Körper spucken lassen',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Ein Dreier mit Fremden',
      b: 'Mit zwei engen Freunden von hier',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Ein Jahr lang nur Oralsex',
      b: 'Nie wieder Oralsex',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Immer Oralsex bekommen',
      b: 'Ihn immer selbst geben',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Ein Oralsex, der im Mund endet',
      b: 'Ein Oralsex, der im Gesicht endet',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Bis zum Orgasmus lecken',
      b: 'Bis zum Orgasmus geleckt werden',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Ein 30-minütiger Blowjob',
      b: 'In 30 Sekunden kommen',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Dreier mit zwei Fremden',
      b: 'Deinem Partner mit einem anderen zusehen',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Dreier mit zwei Männern',
      b: 'Dreier mit zwei Frauen',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Eine Orgie mit acht Leuten',
      b: 'Ein Jahr lang Sex nur allein',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Deinem Partner beim Ficken mit einem anderen zusehen',
      b: 'Dir beim Ficken zusehen lassen',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Ein Fremder sieht dir beim Kommen zu',
      b: 'Du siehst einem Fremden beim Kommen zu',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Gefesselt und verbunden werden',
      b: 'Selbst fesseln und verbinden',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Sanft ausgepeitscht werden',
      b: 'Selbst den Partner auspeitschen',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Für eine Nacht unterwürfig',
      b: 'Für eine Nacht Domina',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Halsband und Leine an dir',
      b: 'Sie selbst dem Partner anlegen',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Versohlt werden, bis es Spuren hinterlässt',
      b: 'Selbst versohlen, bis es Spuren gibt',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Die ganze Nacht ans Bett gefesselt',
      b: 'Selbst den Partner ans Bett fesseln',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Verbunden und dem Partner ausgeliefert',
      b: 'Selbst verbinden und bestimmen',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Ein Vibrator eine Stunde lang ohne Pause',
      b: 'Einen Monat lang kein Orgasmus',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Tagelang der Orgasmus verweigert',
      b: 'Erzwungene Orgasmen am laufenden Band',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Einen Plug den ganzen Tag tragen',
      b: 'Einen Vibrator in der Öffentlichkeit',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Alle Sextoys im Laden ausprobieren',
      b: 'Für immer nur Hände',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Ein riesiger Dildo',
      b: 'Ein kleiner, aber konstanter Vibrator',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Echte Handschellen an den Handgelenken',
      b: 'Seidenseile am Körper',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Sex auf der Toilette einer Bar',
      b: 'Sex in einer dunklen Gasse',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Es nachts am Strand tun',
      b: 'Es im Aufzug tun',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Sex im Auto auf einem Parkplatz',
      b: 'Sex nachts auf einem Dach',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Riskieren, im Büro erwischt zu werden',
      b: 'Es in einer Umkleidekabine tun',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Sex im fahrenden Zug',
      b: 'Sex unter einem vollen Tisch',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Ein heißes Video von dir macht die Runde',
      b: 'Deine heißen Chats machen die Runde',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Deine Nacktfotos auf seinem Handy',
      b: 'Ein intimes Video von dir gespeichert',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Aufnehmen, während ihr es tut',
      b: 'Dich nackt für ihn fotografieren',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Ein Nacktfoto aus Versehen an den Chef geschickt',
      b: 'Ein Nacktfoto, das deine Freunde gesehen haben',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Sex vor einer Webcam haben',
      b: 'Sex immer bei eingeschaltetem Licht',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Rauer Sex ohne Gnade',
      b: 'Langsamer Sex die ganze Nacht',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Fünfmal hintereinander kommen',
      b: 'Ein einziger, sehr langer Orgasmus',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Den Orgasmus immer vortäuschen',
      b: 'Nie wieder kommen',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Einen Orgasmus jede Stunde, einen Tag lang',
      b: 'Ein Jahr lang kein Orgasmus',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Vor ihm squirten',
      b: 'Ihm zusehen, wie er auf deinen Körper kommt',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Analsex',
      b: 'Doppelte Penetration',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Analsex zum ersten Mal ausprobieren',
      b: 'Ihn nie ausprobieren',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Heute Abend einen Fremden aufreißen',
      b: 'Ein Ex für eine letzte Nacht',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Eine Nacht mit deinem Kino-Idol',
      b: 'Eine Nacht mit deinem besten Ex',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Sex mit seinem besten Freund',
      b: 'Sex mit ihrer besten Freundin',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Partnertausch mit Freunden',
      b: 'Tausch mit völlig Fremden',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Bei einer Orgie alle küssen',
      b: 'Nur eine Person auswählen',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Eine Massage, die im Bett endet',
      b: 'Ein privater Lapdance',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Striptease vor der Gruppe',
      b: 'Nackt an einer Stange tanzen',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Die Sahne von seinem Körper lecken',
      b: 'Ihn die Schokolade von dir lecken lassen',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Sex, mit Öl bedeckt',
      b: 'Sex unter der heißen Dusche',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Ein befriedigter Fußfetisch',
      b: 'Ein befriedigter Po-Fetisch',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Dir die Zehen lutschen lassen',
      b: 'Selbst seine lutschen',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Beim Abendessen auswärts nur Dessous tragen',
      b: 'Beim Abendessen auswärts ohne Unterwäsche',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Ein enges Korsett den ganzen Abend',
      b: 'Stöckelschuhe und sonst nichts',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Sex mit einer Maske im Gesicht',
      b: 'Sex in völliger Dunkelheit',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Deine Fantasien laut aussprechen',
      b: 'Eine zufällige davon umsetzen',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Ein Rollenspiel: Lehrer und Schülerin',
      b: 'Ein Rollenspiel: Chef und Sekretärin',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Euch in einer Bar als Fremde ausgeben',
      b: 'Euch als Ex ausgeben, die sich wiedertreffen',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Sex, während die anderen nebenan schlafen',
      b: 'Sex, laut schreiend, ohne Hemmungen',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Dir schmutzige Dinge ins Ohr sagen lassen',
      b: 'Sie ihm selbst sagen',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Den ganzen Arbeitstag lang sexten',
      b: 'Jede Stunde ein heißes Foto',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Ein Blowjob, während er fährt',
      b: 'Fingern im Kino',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Ihn eine Stunde lang mit Blicken verführen',
      b: 'Sofort über ihn herfallen',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Ihn reiten, bis er erschöpft ist',
      b: 'Dich von hinten nehmen lassen',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Sex in drei Stellungen hintereinander',
      b: 'Eine Stunde in derselben Stellung',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Ihn nur mit den Händen kommen lassen',
      b: 'Nur mit dem Mund',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Ein Blowjob mit verbundenen Augen',
      b: 'Sex mit verbundenen Augen',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Eis auf der nackten Haut',
      b: 'Heißes Wachs auf dem Körper',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Beißen, bis es Spuren hinterlässt',
      b: 'Den Rücken tief zerkratzen',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Sichtbare Knutschflecke am Hals',
      b: 'Bissspuren an der Innenseite der Schenkel',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Für immer Sex mit nur einem Partner',
      b: 'Jeden Monat ein anderer Partner',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Den Partner nackt mit einem anderen sehen',
      b: 'Nie erfahren, was er tut',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Ein bis ins Detail geplanter Dreier',
      b: 'Ein völlig improvisierter Dreier',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Dich langsam von ihm ausziehen lassen',
      b: 'Ihn selbst mit den Zähnen ausziehen',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Sex mit ihm in Uniform',
      b: 'Sex mit dir in Uniform',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Ein langes Vorspiel ohne Penetration',
      b: 'Sofortige Penetration ohne Vorspiel',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Eine Stunde Edging',
      b: 'Sofortiger Orgasmus und fertig',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Dich in einer vollen Bar anfassen lassen',
      b: 'Ihn selbst unter dem Tisch anfassen',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Ein zusätzlicher Finger beim Sex',
      b: 'Eine zusätzliche Zunge beim Sex',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Sex vor dem Spiegel',
      b: 'Sex, mit dem Handy gefilmt',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Einen Plug beim Essen bei den Schwiegereltern tragen',
      b: 'Ein Vibrator, von ihm gesteuert',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Ferngesteuerter Vibrator in der U-Bahn',
      b: 'Ferngesteuerter Vibrator im Restaurant',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Eine lange Spanking-Session',
      b: 'Eine lange Bondage-Session',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Mit japanischen Seilen aufgehängt',
      b: 'Mit Klebeband fixiert',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Eine Ganzkörpermassage von jemandem aus der Gruppe',
      b: 'Eine gemeinsame Dusche mit jemandem aus der Gruppe',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Den Kollegen küssen, den du seit Monaten magst',
      b: 'Hören, dass er es erwidert, aber vergeben ist',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Langsamer Sex die ganze Nacht',
      b: 'Schneller, überwältigender Sex in einer Minute',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Dein Codewort laut aussprechen',
      b: 'Deine Lieblingsstellung vormachen',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Heißer Flirt mit dem besten Freund deines Ex',
      b: 'Ein heißer Flirt mit dem Nachbarn',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Sex nur an öffentlichen Orten',
      b: 'Sex nur bei offener Tür',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Ein Wochenende voller Sex ohne zu reden',
      b: 'Ein Wochenende voller Kuscheln ohne Sex',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Einen Lapdance von dem rechts neben dir bekommen',
      b: 'Einen für den links neben dir machen',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Gestehen, welchem Anwesenden du den Hof machen würdest',
      b: 'Die Gruppe einen Verehrer für dich wählen lassen',
      tone: ContentTone.piccante,
    ),
    (
      a: 'In einer Nacht alles mit dem Fremden ausprobieren',
      b: 'Ein Jahr keusch bleiben mit der wahren Liebe',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Ein Zungenkuss mit deiner ersten Liebe',
      b: 'Eine endlose Umarmung mit deinem letzten Schwarm',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Alle Anwesenden nacheinander küssen',
      b: 'Nur einen zehn Minuten lang küssen',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Sagen, wie lange du im Bett durchschnittlich durchhältst',
      b: 'Deinen persönlichen Rekord verraten',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Ein verbotenes Treffen mit dem Tanzlehrer',
      b: 'Ein verbotenes Treffen mit dem Barista um die Ecke',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Einen Fremden in zehn Minuten verführen',
      b: 'Dich ohne ein Wort verführen lassen',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Einen Monat lang nur aufreizende Dessous',
      b: 'Ein Jahr lang nur ausgeleierte Schlafanzüge',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Für immer Sex mit demselben Partner',
      b: 'Jede Woche ein anderer Partner, ohne Liebe',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Dich langsam von dem vor dir ausziehen lassen',
      b: 'Den neben dir selbst ausziehen',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Die Fantasie verraten, die du nie umgesetzt hast',
      b: 'Sie heute Abend mit einem Anwesenden umsetzen',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Ein leidenschaftlicher Kuss im Regen',
      b: 'Eine feurige Nacht vor dem Kamin',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Sex mit der schönsten Person, die du je gesehen hast',
      b: 'Unvergesslicher Sex mit dem, den du wirklich liebst',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Dich von dem rechts neben dir in den Hals beißen lassen',
      b: 'Den links neben dir selbst in den Hals beißen',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Wie oft du an einen Anwesenden gedacht hast',
      b: 'Ein Anwesender gesteht, wie oft er an dich denkt',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Ein Jahr nur Abenteuer ohne Morgen',
      b: 'Ein Jahr nur Warten auf die richtige Person',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Jemanden mit verbundenen Augen küssen und raten, wer es ist',
      b: 'Dich küssen lassen und alle raten lassen',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Hemmungsloser Sex, aber ihr seht euch nie wieder',
      b: 'Endloses Warten, aber dann für immer',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Ein aufreizender Tanz vor der ganzen Gruppe',
      b: 'Ein Überraschungskuss, von der Gruppe gewählt',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Mit deinem Ex zusammen duschen',
      b: 'Mit deinem Schwarm zusammen baden',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Sagen, wen aus der Gruppe du im Dunkeln küssen würdest',
      b: 'Sagen, wen aus der Gruppe du nie küssen würdest',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Fußmassage von einem heißen Fremden',
      b: 'Eine Rückenmassage von deinem Ex',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Sex nur bei Dunkelheit und Kerzen',
      b: 'Sex nur vor dem Spiegel',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Heimlicher Flirt mit deinem Schwimmlehrer',
      b: 'Ein heimlicher Flirt mit deinem Tätowierer',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Den gewagtesten Gegenstand verraten, den du besitzt',
      b: 'Ihn der Gruppe zeigen',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Die Nacht mit deinem Schwarm aus der Schulzeit verbringen',
      b: 'Die Nacht mit deinem jetzigen Schwarm verbringen',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Einen Monat lang nur langsame Küsse',
      b: 'Nur Nächte voller Leidenschaft, aber keine Küsse',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Dir heiße Dinge ins Ohr flüstern lassen',
      b: 'Sie selbst dem neben dir flüstern',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Den heißen Spitznamen verraten, den du deinem Partner gibst',
      b: 'Den verraten, den dein Partner dir gibt',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Eine Nacht mit dem, der dich vor Jahren abgewiesen hat',
      b: 'Eine Nacht mit dem, der dich schon immer begehrt',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Immer schon beim ersten Date Sex',
      b: 'Jedes Mal drei Monate warten',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Den vor dir zwanzig Sekunden lang küssen',
      b: 'Den hinter dir zwei Minuten lang umarmen',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Der riskanteste Ort, an dem du es versucht hast',
      b: 'Die absurdeste Uhrzeit, zu der du es getan hast',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Ein Wellness-Wochenende allein mit jemandem aus der Gruppe',
      b: 'Eine romantische Kreuzfahrt mit einem Fremden',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Dir während eines Kusses die Gedanken lesen lassen',
      b: 'Selbst die Gedanken dessen lesen, den du küsst',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Nur heiße Dates, aber nie ein zweites',
      b: 'Nur süße Dates, aber ohne Funken',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Verraten, wie viele Anwesende du attraktiv fändest',
      b: 'Jeden sagen lassen, ob er dich attraktiv findet',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Sex zu deinem Lieblingslied',
      b: 'Es in völliger Stille tun',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Eine Nacht mit einem Model, aber ohne Worte',
      b: 'Eine Nacht mit einem Witzbold, aber ohne Sex',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Ein leidenschaftliches Rummachen mit dem rechts neben dir',
      b: 'Eine sinnliche Massage von dem links neben dir',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Welcher Körperteil dir den Kopf verdreht',
      b: 'Die Gruppe ihn erraten lassen',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Deinen Schwarm nur mit Emojis verführen',
      b: 'Ihn mit einer einzigen peinlichen Sprachnachricht verführen',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Sex nur früh am Morgen',
      b: 'Sex nur tief in der Nacht',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Einen Kuss von deinem Chef als Wette stehlen',
      b: 'Einen Kuss vom besten Freund des Partners stehlen',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Deine Fantasie über einen VIP gestehen',
      b: 'Die von dem vor dir hören',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Nur Fernbeziehungen, aber voller Leidenschaft',
      b: 'Nur Beziehungen in der Nähe, aber lauwarm',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Dir einen gut sichtbaren Knutschfleck machen lassen',
      b: 'Selbst einen dem neben dir machen',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Sagen, wie oft du den ersten Schritt gemacht hast',
      b: 'Sagen, wie oft du einen Rückzieher gemacht hast',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Eine Nacht voller Leidenschaft, aber du vergisst sie',
      b: 'Keine Nacht, aber die Erinnerung an einen Kuss',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Die schüchternste Person der Gruppe küssen',
      b: 'Die frechste der Gruppe küssen',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Strip-Poker mit den Anwesenden spielen',
      b: 'Wahrheit oder Pflicht, nur pikant, spielen',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Jemanden nur mit Blicken verführen',
      b: 'Ihn nur mit einem Satz verführen',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Ein heißes Date, ausgewählt von deinem Ex',
      b: 'Ein heißes Date, ausgewählt von deiner Mutter',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Ein Biss in die Brustwarze',
      b: 'Klemmen an den Brustwarzen',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Augenbinde und Überraschungen',
      b: 'Alles im Voraus wissen',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Dich im Bett mit Worten erniedrigen lassen',
      b: 'Ihn selbst mit Worten erniedrigen',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Ein Herr für eine Nacht',
      b: 'Eine Sklavin für eine Nacht',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Eine Stunde lang jedem Befehl gehorchen',
      b: 'Eine Stunde lang selbst die Befehle geben',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Sex mit einem Safeword',
      b: 'Sex ohne vereinbarte Grenzen',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Ein Dreier mit einer Escort',
      b: 'Ein Dreier mit einem Freund',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Sich von einem Dritten filmen lassen',
      b: 'Sich von einem Dritten nur zusehen lassen',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Sex auf einem einsehbaren Balkon',
      b: 'Sex nachts im Garten',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Ein Quickie in der Küche',
      b: 'Ein Marathon im Schlafzimmer',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Es auf dem Wohnzimmertisch tun',
      b: 'Es an der Wand im Flur tun',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Sex direkt nach dem Aufwachen, jeden Morgen',
      b: 'Sex nur um Mitternacht, jede Nacht',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Wax Play ausprobieren',
      b: 'Temperature Play ausprobieren',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Ein Vibrator, während er dir zusieht',
      b: 'Seine Hände, während du dir selbst zusiehst',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Vor ihm masturbieren',
      b: 'Ihm zusehen, wie er für dich masturbiert',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Ein Orgasmus nur durch Worte',
      b: 'Ein Orgasmus nur durch ein Spielzeug',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Sex mit dem Sperma im Gesicht',
      b: 'Sex mit dem Sperma auf dem Körper',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Ihn in dir kommen lassen',
      b: 'Ihn außerhalb kommen lassen',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Ein Creampie',
      b: 'Ein Facial',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Ihn lecken, nachdem er gekommen ist',
      b: 'Dich lecken lassen, nachdem du gekommen bist',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Ein Akt bei vollem Tageslicht',
      b: 'Ein Akt nur bei Kerzenschein',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Sex mit Musik in voller Lautstärke',
      b: 'Sex in völliger Stille',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Sich die Handgelenke mit der Krawatte fesseln lassen',
      b: 'Die Knöchel mit Strümpfen fesseln',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Eine Augenbinde und schalldichte Kopfhörer',
      b: 'Nur die Augenbinde',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Einen Tag lang völlig dominieren',
      b: 'Dich einen Tag lang völlig unterwerfen',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Sex im Zelt beim Camping',
      b: 'Sex nachts im Pool',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Ein Akt auf der Rückbank',
      b: 'Ein Akt auf der Motorhaube',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Pegging ausprobieren',
      b: 'Rimming ausprobieren',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Ein Umschnalldildo für sie',
      b: 'Ein Vibrationsring für ihn',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Dich tief in den Mund nehmen lassen',
      b: 'Ihn selbst tief in den Mund nehmen',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Deep Throat',
      b: 'Face Sitting',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Dich auf sein Gesicht setzen',
      b: 'Ihn sich auf deins setzen lassen',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Ein endloser Sixty-Nine',
      b: 'Sich abwechseln',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Sex mit einem wärmenden Gleitgel',
      b: 'Sex mit einem Gel mit Kälteeffekt',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Dich verbinden lassen und die Spielzeuge erraten',
      b: 'Mit verbundenen Augen seine Hände erraten',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Ein Rollenspiel: Krankenschwester und Patient',
      b: 'Ein Rollenspiel: Polizistin und Verhafteter',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Sich im Hotel als Fremde ausgeben',
      b: 'Sich als neugierige Nachbarn ausgeben',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Sex mit vom Leib gerissenen Dessous',
      b: 'Sex, fast angezogen bleibend',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Dir das Höschen zerreißen lassen',
      b: 'Ihm die Boxershorts mit den Zähnen zerreißen',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Ein Orgasmus in weniger als einer Minute',
      b: 'Zwanzig Minuten durchhalten',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Die Orgasmen laut zählen',
      b: 'Absolut still bleiben',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Ein Dreier mit deinem Schwarm',
      b: 'Ein Dreier mit seinem Schwarm',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Zusammen Pornos schauen und nachahmen',
      b: 'Alles ohne Vorlage erfinden',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Eine berühmte Pornoszene nachstellen',
      b: 'Ein eigenes Amateurvideo drehen',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Sex mit noch angezogenen High Heels',
      b: 'Sex völlig nackt',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Ein Liebeskugel-Ei den ganzen Tag tragen',
      b: 'Ein Plug den ganzen Nachmittag',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Eine komplette erotische Massage',
      b: 'Ein erotisches Bad zu zweit',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Sex mit duftendem Öl überall',
      b: 'Sex, mit Schaum bedeckt',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Ihn vor dir von einer anderen verführen lassen',
      b: 'Selbst einen anderen vor ihm verführen',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Ein Strip-Poker, das im Bett endet',
      b: 'Ein Wahrheit oder Pflicht, heiß bis zum Ende',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Eine Frau vor ihm küssen',
      b: 'Ihm zusehen, wie er einen Mann küsst',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Ein erster lesbischer Kuss',
      b: 'Ein erster schwuler Kuss',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Sex mit zwei Händen auf dir',
      b: 'Sex mit zwei Mündern auf dir',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Dir sanft den Hals umfassen lassen',
      b: 'Selbst seine Handgelenke umfassen',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Ein leichtes, vereinbartes Choking',
      b: 'Ein entschlossenes Hair Pulling',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Sex mit gezogenen Haaren',
      b: 'Sex mit Fingernägeln auf dem Rücken',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Dich vor dem Spiegel von hinten nehmen lassen',
      b: 'Ihn selbst vor dem Spiegel reiten',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Drei Tage lang der Orgasmus verweigert',
      b: 'Drei Orgasmen in einer Stunde',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Sich beim Ausziehen per Webcam beobachten lassen',
      b: 'Ihm per Webcam beim Ausziehen zusehen',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Ein Vibrator, abwechselnd geteilt',
      b: 'Zwei Spielzeuge gleichzeitig',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Sex auf einem Stuhl gefesselt',
      b: 'Sex im Stehen gegen das Fenster',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Dir auf die Lippe beißen lassen, bis sie blutet',
      b: 'Ihm gierig in den Hals beißen',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Ein mehrfach unterbrochener und wieder aufgenommener Akt',
      b: 'Ein einziger Akt ohne Pausen',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Sensory Deprivation ausprobieren',
      b: 'Sensory Overload ausprobieren',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Dich mit verbundenen Augen kitzeln lassen',
      b: 'Ihn selbst kitzeln, während er fixiert ist',
      tone: ContentTone.cattivo,
    ),
  ];
}
