import '../../../core/i18n/app_locale.dart';
import '../content_tone.dart';
import 'preferisci_pool_de.dart';
import 'preferisci_pool_en.dart';
import 'preferisci_pool_es.dart';
import 'preferisci_pool_fr.dart';

/// Pool gratuito di "Preferisci", una lista per lingua.
///
/// L'indice della coppia finisce dentro `rounds.content['i']`, così l'host sa
/// quali sono già uscite e non le ripesca nella stessa partita.
class PreferisciPool {
  const PreferisciPool._();

  /// Coppie nella lingua scelta dal gruppo.
  static List<({String a, String b})> pairs(AppLocale locale) =>
      switch (locale) {
        AppLocale.it => it,
        AppLocale.en => PreferisciPoolEn.pairs,
        AppLocale.es => PreferisciPoolEs.pairs,
        AppLocale.fr => PreferisciPoolFr.pairs,
        AppLocale.de => PreferisciPoolDe.pairs,
      };

  /// Coppie audaci (piccante/cattivo) nella lingua del gruppo.
  static List<({String a, String b, String tone})> _hot(AppLocale locale) =>
      switch (locale) {
        AppLocale.it => hotIt,
        AppLocale.en => PreferisciPoolEn.hot,
        AppLocale.es => PreferisciPoolEs.hot,
        AppLocale.fr => PreferisciPoolFr.hot,
        AppLocale.de => PreferisciPoolDe.hot,
      };

  /// Coppie con il tono, per il filtro della modalità.
  ///
  /// Il mazzo base è tutto soft; in Mix e Hot entrano anche le coppie audaci
  /// di [hotIt] o dell'equivalente nella lingua del gruppo.
  static List<({String a, String b, String tone})> entries(AppLocale locale) =>
      [
        for (final p in pairs(locale)) (a: p.a, b: p.b, tone: ContentTone.soft),
        ..._hot(locale),
      ];

  /// Dilemmi da modalità Hot: diretti su sesso, ex e segreti del gruppo,
  /// mai descrittivi. È il registro dei party game per adulti in commercio.
  static const List<({String a, String b, String tone})> hotIt =
      <({String a, String b, String tone})>[
        (
          a: 'Uscire nudo in giro per un minuto',
          b: 'Baciare una persona di questo gruppo',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Passare la notte con uno del gruppo',
          b: 'Una notte con un tuo vecchio prof',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Mostrare la galleria al gruppo',
          b: 'Far leggere le tue chat ad alta voce',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Un anno senza sesso',
          b: 'Un anno senza uscire la sera',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Dire il tuo body count al gruppo',
          b: 'Mostrare l\'ultima ricerca fatta',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Amore senza sesso',
          b: 'Sesso senza amore',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Partner bello ma pessimo a letto',
          b: 'Partner normale ma fenomenale',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Una notte col tuo ex',
          b: 'Una notte con uno sconosciuto',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Beccare i tuoi genitori',
          b: 'Farti beccare dai tuoi',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Dire a tutti chi ti piace adesso',
          b: 'Non parlare mai più con chi ti piace',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Baciare a occhi chiusi uno del gruppo',
          b: 'Baciare il tuo ex davanti a tutti',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Non poter più baciare',
          b: 'Non poter più abbracciare',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Sapere con chi ti tradirebbe il partner',
          b: 'Non saperlo mai',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Solo appuntamenti al buio per un anno',
          b: 'Solo uscite scelte da tua madre',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Rivedere in video il tuo primo bacio',
          b: 'Che lo riveda tutto il gruppo',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Gemere ogni volta che ti siedi',
          b: 'Urlare il nome del tuo ex ogni brindisi',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Mandare un nude all\'ex per sbaglio',
          b: 'Mandarlo nel gruppo famiglia',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Sexting col capo per errore',
          b: 'Chiamare il partner col nome dell\'ex',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Una notte con una celebrità',
          b: 'Un mese di sesso col tuo ex',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Fare sesso solo al buio totale',
          b: 'Solo con la luce sempre accesa',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Dire la tua fantasia più strana',
          b: 'Sentire quella di chi hai a destra',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Amici di letto col tuo migliore amico',
          b: 'Mai più sesso per un anno',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Un ex che bacia da dio',
          b: 'Uno nuovo tutto da istruire',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Farti spogliare con gli occhi al bar',
          b: 'Non essere mai più notato',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Raccontare il tuo peggior appuntamento',
          b: 'Rivivere la tua figuraccia più hot',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Fare sempre tu la prima mossa',
          b: 'Aspettare sempre che parta l\'altro',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Una cosa a tre con sconosciuti',
          b: 'Una cosa a tre con amici',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Beccare il coinquilino in azione',
          b: 'Farti beccare dal coinquilino',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Dire quante volte ci pensi al giorno',
          b: 'Dire quando l\'hai fatto l\'ultima volta',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Partner super geloso ma bollente',
          b: 'Partner tranquillo ma pigro a letto',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Baciare il primo che entra dalla porta',
          b: 'Baciare l\'ultimo che ti ha scritto',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Notte di passione senza baci',
          b: 'Baci infiniti ma niente altro',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Dimenticare la tua prima volta',
          b: 'Ricordarla ogni singolo giorno',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Dire il posto più assurdo dove l\'hai fatto',
          b: 'Dire il posto dove vorresti farlo',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Un flirt col tuo personal trainer',
          b: 'Un flirt col tuo medico',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Solo one night stand per un anno',
          b: 'Solo relazioni serie a vita',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Rifarti con l\'ex ogni tanto',
          b: 'Chiudere per sempre ma con rimpianto',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Un limone con chi hai a sinistra',
          b: 'Un lento sensuale con chi hai a destra',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Dormire nudo con un amico',
          b: 'Fare la doccia in costume con l\'ex',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Ricevere un nude non richiesto dal capo',
          b: 'Mandarne uno al capo per sbaglio',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Sesso da urlo una volta al mese',
          b: 'Sesso mediocre ogni giorno',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Sapere cosa pensa l\'altro a letto',
          b: 'Che senta ogni tuo pensiero a letto',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Un weekend con la tua cotta segreta',
          b: 'Un mese col tuo primo amore',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Colazione a letto dopo la prima notte',
          b: 'Sparire prima dell\'alba',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Dire il tuo punto debole a letto',
          b: 'Mimarlo davanti al gruppo',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Tatuarti il nome dell\'ex',
          b: 'Urlare il suo nome al momento sbagliato',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Match col tuo ex su un\'app',
          b: 'Match col tuo capo su un\'app',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Il partner sa ogni tua fantasia',
          b: 'Tu sai ogni sua fantasia',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Spogliarello improvvisato ora',
          b: 'Racconto piccante della tua estate',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Baciare uno del gruppo a scelta tua',
          b: 'Baciarne uno scelto dal gruppo',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Storia segreta super passionale',
          b: 'Storia ufficiale ma tiepida',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Fare sesso solo d\'estate',
          b: 'Fare sesso solo d\'inverno',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Scordare ogni tua notte brava',
          b: 'Ricordare pure quelle da dimenticare',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Audio hot mandato alla persona sbagliata',
          b: 'Riceverne uno dal tuo capo',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Far leggere i messaggi con l\'ex',
          b: 'Far vedere le foto con l\'ex',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Amore a prima vista stasera',
          b: 'Avventura di una notte stasera',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Dire il nome della tua cotta al gruppo',
          b: 'Farla indovinare al gruppo',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Ballare un lento col tuo ex stasera',
          b: 'Karaoke romantico con uno del gruppo',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Provarci con uno sconosciuto ora',
          b: 'Dare il numero al primo che lo chiede',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Un massaggio da uno del gruppo',
          b: 'Farlo tu a uno del gruppo',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Vietato flirtare per un anno',
          b: 'Obbligo di flirtare con chiunque',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Una notte col tuo idolo musicale',
          b: 'Un weekend col tuo attore preferito',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Confessare un sogno hot su un presente',
          b: 'Che un presente lo confessi su di te',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Silenzio totale a letto',
          b: 'Telecronaca completa a letto',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Un lato B da urlo',
          b: 'Un décolleté da applausi',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Il tuo ex diventa famosissimo',
          b: 'Il tuo ex diventa il tuo capo',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Dire cosa ti eccita di più',
          b: 'Dire cosa ti spegne subito',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Una tresca estiva mai confessata',
          b: 'Un amore a distanza infinito',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Due presenti ti fanno il filo',
          b: 'Fare il filo a due presenti insieme',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Vedere l\'ex con uno più bello di te',
          b: 'Che ti veda con uno peggio di lui',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Baci col morso',
          b: 'Baci a stampo per sempre',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Dormire abbracciati senza sesso',
          b: 'Sesso senza mai dormire insieme',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Fare sesso con la musica a palla',
          b: 'Col telegiornale in sottofondo',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Rivelare il tuo numero di ex',
          b: 'Rivelare chi era il migliore',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Provarci col cameriere stasera',
          b: 'Lasciargli il numero sullo scontrino',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Prima volta imbarazzante ma dolce',
          b: 'Perfetta ma con la persona sbagliata',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Un tatuaggio dove decide il gruppo',
          b: 'Un piercing dove decide il gruppo',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Un bacio di 30 secondi con un presente',
          b: 'Dieci baci veloci con dieci sconosciuti',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Sapere chi del gruppo ti sogna di notte',
          b: 'Sapere chi non ti bacerebbe mai',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Sesso in tenda in campeggio pieno',
          b: 'In hotel con pareti di carta',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Una vacanza solo per single',
          b: 'Una vacanza solo per coppie',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Tradire senza mai essere scoperto',
          b: 'Essere tradito senza saperlo mai',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Una storia col partner di un amico',
          b: 'Il tuo partner col tuo migliore amico',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Che escano le tue foto peggiori',
          b: 'Che escano le tue chat peggiori',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Sentire cosa dice il gruppo di te',
          b: 'Che il gruppo senta cosa dici tu',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Confessare il tuo peggior segreto ora',
          b: 'Che lo sveli il tuo migliore amico',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Sesso con l\'ex del tuo migliore amico',
          b: 'Dirgli che ci hai già pensato',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Sapere tutto dei presenti',
          b: 'Che i presenti sappiano tutto di te',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Un ex che torna sempre',
          b: 'Mai più notizie di nessun ex',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Fare coppia fissa con uno del gruppo',
          b: 'Non poter più vedere il gruppo',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Scoprire un tradimento del passato',
          b: 'Confessarne uno tuo adesso',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Leggere il diario segreto del partner',
          b: 'Che lui legga tutte le tue chat',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Sapere chi del gruppo parla male di te',
          b: 'Sapere chi ti ha mentito di più',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Un ex che spunta al primo appuntamento',
          b: 'Un partner che nomina sempre l\'ex',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Tradire in un sogno e confessarlo',
          b: 'Sognare l\'ex ogni notte e tacere',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Sapere il vero body count del partner',
          b: 'Che lui scopra il tuo vero',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Baciare l\'ex del tuo migliore amico',
          b: 'Che lui baci il tuo ex',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Una notte col partner di un collega',
          b: 'Che tutti pensino che l\'hai fatto',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Scoprire che l\'ex ti tradiva sempre',
          b: 'Scoprire che ti ha sempre amato',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Vendicarti di un ex e pentirtene',
          b: 'Perdonarlo e pentirtene di più',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Il gruppo legge la tua ultima chat hot',
          b: 'Il gruppo vede le tue foto private',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Confessare a chi hai fatto ghosting',
          b: 'Chiamare ora chi ti ha ghostato',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Essere lasciato con un vocale',
          b: 'Lasciare qualcuno al suo compleanno',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Rubare il partner a qualcuno',
          b: 'Fartelo rubare e riprendertelo',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Sapere ogni bugia detta dal partner',
          b: 'Che il partner sappia ogni tua bugia',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Dire al gruppo il tuo peggior tradimento',
          b: 'Dire il segreto peggiore di un amico',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Flirtare col partner del tuo capo',
          b: 'Che il tuo capo flirti col tuo',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Un amico che ci prova col tuo partner',
          b: 'Un partner che ci prova col tuo amico',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Trovare un regalo dell\'ex a casa sua',
          b: 'Trovare chat con l\'ex nel suo telefono',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Cancellare per sempre un tuo segreto',
          b: 'Scoprire quello che ti nascondono',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Dire con chi del gruppo non usciresti',
          b: 'Sentire chi non uscirebbe mai con te',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Un ex a cui devi ancora dei soldi',
          b: 'Un ex che ti deve ancora delle scuse',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Ammettere di aver stalkerato l\'ex',
          b: 'Mostrare la cronologia dei suoi profili',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Sesso di nascosto a casa dei suoceri',
          b: 'Beccati da loro al momento peggiore',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Il tuo migliore amico ti odia',
          b: 'Il tuo amico ama il tuo partner',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Tradimento di una notte confessato',
          b: 'Storia parallela mai scoperta',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Rispondere nudo a tre domande',
          b: 'Rispondere vestito a trenta',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Sapere la data della fine della coppia',
          b: 'Sapere il motivo ma non la data',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Un rivale in amore più bello',
          b: 'Un rivale più simpatico',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Dire subito se il partner bacia male',
          b: 'Sposarlo senza dirglielo mai',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'L\'ex che ti scrive alle 3 di notte',
          b: 'Scrivergli tu e negare per sempre',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Partner ancora amico di tutti i suoi ex',
          b: 'Partner che ti vieta di vedere i tuoi',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Scoprire un profilo segreto del partner',
          b: 'Che lui trovi il tuo',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Amare due persone insieme',
          b: 'Essere l\'amante e non saperlo',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Dire chi dei presenti bacia peggio',
          b: 'Farti dare un voto da ogni presente',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Sabotare le nozze del tuo ex',
          b: 'Fare il testimone alle sue nozze',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Una lista pubblica dei tuoi flirt',
          b: 'Una lista di chi ti ha rifiutato',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Perdere l\'amico per dirgli la verità',
          b: 'Tenertelo mentendogli a vita',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Il tuo nemico sa il tuo segreto',
          b: 'Tua suocera sa tutto di te',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Scambiare il partner per una settimana',
          b: 'Vivere da single per un anno',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Il gruppo vota il tuo peggior difetto',
          b: 'Sentirli elencare tutti i tuoi flirt',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Tradire e confessarlo dopo dieci anni',
          b: 'Scoprirlo dopo dieci anni',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Un weekend con i tuoi suoceri',
          b: 'Un weekend con l\'ex del partner',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Sapere quanti ti hanno detto di no',
          b: 'Sapere chi si è pentito del sì',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Vuotare il sacco su un amore segreto',
          b: 'Che il gruppo indaghi per un\'ora',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Leggere ad alta voce l\'ultimo messaggio',
          b: 'Chiamare l\'ultimo numero in rubrica',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Rovinare una coppia dicendo la verità',
          b: 'Salvarla con una bugia enorme',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Il tuo ex parla di te in un podcast',
          b: 'Il gruppo racconta le tue notti peggiori',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Essere il piano B di qualcuno',
          b: 'Avere un piano B e farti beccare',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Il partner controlla il tuo telefono',
          b: 'Non poter mai guardare il suo',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Dire l\'ultima bugia detta a un presente',
          b: 'Ogni presente ne dice una su di te',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Uscire col gemello del tuo ex',
          b: 'Con qualcuno identico al tuo capo',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Sapere cosa dicono i tuoi ex di te',
          b: 'Riunirli tutti a una cena',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Tradire per vendetta e dirlo',
          b: 'Incassare e tramare in silenzio',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Baciare qualcuno per una scommessa',
          b: 'Scoprire di essere stato una scommessa',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Un matrimonio riparatore tra un mese',
          b: 'Dieci anni di fidanzamento senza nozze',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Spiare la serata dell\'ex dai social',
          b: 'Bloccarlo e morire di curiosità',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Confessare il flirt più squallido',
          b: 'Che lo racconti chi era presente',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Il gruppo sa chi ti piace qui dentro',
          b: 'Lo sa solo la persona sbagliata',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Scoprire una doppia vita del partner',
          b: 'Riuscire a nascondere la tua',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Rompere una coppia di amici parlando',
          b: 'Vederli infelici e stare zitto',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Il gruppo ti sceglie il partner',
          b: 'Il gruppo sceglie chi devi lasciare',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Dire il vero motivo del tuo ultimo addio',
          b: 'Sentire la versione del tuo ex',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Una notte con due ex insieme',
          b: 'Una notte con l\'ex e il suo nuovo amore',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Essere geloso e avere ragione',
          b: 'Fidarti ed essere tradito',
          tone: ContentTone.cattivo,
        ),
        // -------------------------------------------- piccante (extra)
        (a: 'Un bacio perfetto al mese', b: 'Baci mediocri ogni giorno', tone: ContentTone.piccante),
        (a: 'Sapere cosa pensa di te la tua crush', b: 'Farle sapere tutto quello che pensi tu', tone: ContentTone.piccante),
        (a: 'Una notte indimenticabile senza seguito', b: 'Dieci appuntamenti carini senza scintilla', tone: ContentTone.piccante),
        (a: 'Dormire abbracciati e basta', b: 'Tutto il resto ma niente coccole dopo', tone: ContentTone.piccante),
        (a: 'Rivelare il tuo body count alla tua crush', b: 'Mostrare l\'ultima chat con la tua fiamma', tone: ContentTone.piccante),
        (a: 'Partner bravissimo a baciare', b: 'Partner bravissimo a scrivere messaggi', tone: ContentTone.piccante),
        (a: 'Flirtare davanti ai tuoi genitori', b: 'Flirtare davanti al tuo ex', tone: ContentTone.piccante),
        (a: 'Ricevere una foto audace dalla persona sbagliata', b: 'Mandarla tu alla persona sbagliata', tone: ContentTone.piccante),
        (a: 'Essere sedotto a parole', b: 'Essere sedotto con lo sguardo', tone: ContentTone.piccante),
        (a: 'Weekend di passione senza telefono', b: 'Settimana di flirt solo via chat', tone: ContentTone.piccante),
        (a: 'Primo bacio al primo appuntamento', b: 'Primo bacio dopo un mese di attesa', tone: ContentTone.piccante),
        (a: 'Sapere sempre chi ti guarda in un locale', b: 'Non saperlo mai ma essere guardato spesso', tone: ContentTone.piccante),
        (a: 'Un ex che ti scrive ogni notte', b: 'Una crush che non ti scrive mai', tone: ContentTone.piccante),
        (a: 'Un lento con la tua crush davanti a tutti', b: 'Cena a lume di candela ma in silenzio totale', tone: ContentTone.piccante),
        (a: 'Far leggere la chat con la crush al gruppo', b: 'Chiamarla adesso in vivavoce', tone: ContentTone.piccante),
        (a: 'Un massaggio perfetto ogni sera', b: 'Colazione a letto ogni mattina', tone: ContentTone.piccante),
        (a: 'Essere il bacio migliore della vita di qualcuno', b: 'Ricevere tu il bacio migliore della tua vita', tone: ContentTone.piccante),
        (a: 'Mai più primi appuntamenti', b: 'Solo primi appuntamenti per sempre', tone: ContentTone.piccante),
        (a: 'Dire "mi piaci" sempre per primo', b: 'Aspettare sempre che lo dicano a te', tone: ContentTone.piccante),
        (a: 'Una playlist che parte da sola quando flirti', b: 'Una voce narrante che commenta i tuoi appuntamenti', tone: ContentTone.piccante),
        (a: 'Il tuo ex al tuo matrimonio', b: 'Tua suocera in luna di miele', tone: ContentTone.piccante),
        (a: 'Rivedere il tuo primo bacio in video', b: 'Mostrare al gruppo il tuo profilo di incontri', tone: ContentTone.piccante),
        (a: 'Gelo a ogni "dobbiamo parlare"', b: 'Non sentirti mai dire "dobbiamo parlare"', tone: ContentTone.piccante),
        (a: 'Un flirt estivo ogni estate', b: 'Un amore vero ogni dieci anni', tone: ContentTone.piccante),
        (a: 'Sapere quante volte hanno parlato di te', b: 'Sapere cosa hanno detto ma non chi', tone: ContentTone.piccante),
        (a: 'Baci solo sotto la pioggia', b: 'Baci solo in ascensore', tone: ContentTone.piccante),
        (a: 'Un "buongiorno" ogni mattina dalla persona giusta', b: 'Una "buonanotte" ogni sera', tone: ContentTone.piccante),
        (a: 'Perdere la voce quando flirti', b: 'Dire sempre una parola di troppo', tone: ContentTone.piccante),
        (a: 'Essere irresistibile solo di giorno', b: 'Essere irresistibile solo di notte', tone: ContentTone.piccante),
        (a: 'Un appuntamento al buio scelto dal gruppo', b: 'Un appuntamento organizzato dal tuo ex', tone: ContentTone.piccante),
        (a: 'Cenare con il partner della tua crush', b: 'Fare da autista alla coppia tutta la sera', tone: ContentTone.piccante),
        (a: 'Sapere sempre quando mentono in amore', b: 'Non mentire mai tu per primo', tone: ContentTone.piccante),
        (a: 'Un anno senza baci', b: 'Un anno senza abbracci', tone: ContentTone.piccante),
        (a: 'Confessare la cotta al diretto interessato', b: 'Confessarla a tutta questa stanza adesso', tone: ContentTone.piccante),
        (a: 'Essere famoso per una storia d\'amore', b: 'Essere famoso per un due di picche epico', tone: ContentTone.piccante),
        (a: 'Uscire con qualcuno identico a te', b: 'Uscire con il tuo esatto opposto', tone: ContentTone.piccante),
        (a: 'Il tuo diario letto dalla crush', b: 'La tua cronologia letta dai tuoi', tone: ContentTone.piccante),
        (a: 'Un bacio rubato che ricordi per sempre', b: 'Cento baci chiesti con il permesso', tone: ContentTone.piccante),
        (a: 'Sembrare sempre disinteressato', b: 'Sembrare sempre troppo interessato', tone: ContentTone.piccante),
        (a: 'Amore a prima vista una sola volta nella vita', b: 'Colpi di fulmine continui mai ricambiati subito', tone: ContentTone.piccante),
        (a: 'Fiori in ufficio ogni settimana', b: 'Un vocale romantico ogni sera', tone: ContentTone.piccante),
        (a: 'Flirtare benissimo solo per iscritto', b: 'Flirtare benissimo solo dal vivo', tone: ContentTone.piccante),
        (a: 'Una cotta per un amico di questo gruppo', b: 'Una cotta per un collega che vedi ogni giorno', tone: ContentTone.piccante),
        (a: 'Sapere sempre se il primo appuntamento andrà bene', b: 'Poter rifare ogni primo appuntamento una volta', tone: ContentTone.piccante),
        (a: 'Uscita romantica pianificata al minuto', b: 'Improvvisazione totale ogni volta', tone: ContentTone.piccante),
        (a: 'Un partner che balla benissimo', b: 'Un partner che cucina benissimo', tone: ContentTone.piccante),
        (a: 'Gelosia zero per sempre', b: 'Passione doppia ma gelosia inclusa', tone: ContentTone.piccante),
        (a: 'Essere corteggiato da due persone insieme', b: 'Scegliere sempre tu ma senza mai essere corteggiato', tone: ContentTone.piccante),
        (a: 'Il tuo nome in una canzone d\'amore famosa', b: 'Il tuo volto in un video virale romantico', tone: ContentTone.piccante),
        (a: 'Solo appuntamenti a colazione', b: 'Solo appuntamenti a mezzanotte', tone: ContentTone.piccante),
        (a: 'Mano nella mano in pubblico sempre', b: 'Effusioni solo in privato ma intense', tone: ContentTone.piccante),
        (a: 'Dimenticare tutti i tuoi ex', b: 'Che tutti i tuoi ex dimentichino te', tone: ContentTone.piccante),
        (a: 'Un bacio da film una volta l\'anno', b: 'Baci normali ma quotidiani', tone: ContentTone.piccante),
        (a: 'Dichiararti con una lettera scritta a mano', b: 'Dichiararti con un discorso davanti a tutti', tone: ContentTone.piccante),
        (a: 'Sapere il giorno esatto in cui ti innamorerai', b: 'Sapere solo il nome ma non quando', tone: ContentTone.piccante),
        (a: 'Un partner permaloso ma passionale', b: 'Un partner zen ma tiepido', tone: ContentTone.piccante),
        (a: 'Rivivere il tuo primo amore', b: 'Conoscere in anticipo l\'ultimo', tone: ContentTone.piccante),
        (a: 'Passare per timido quando flirti', b: 'Passare per sfacciato quando sei timido', tone: ContentTone.piccante),
        (a: 'La verità sul perché è finita ogni tua storia', b: 'Non saperlo mai ma chiudere in pace', tone: ContentTone.piccante),
        (a: 'Un appuntamento perfetto organizzato dal tuo ex', b: 'Un disastro totale ma con la persona giusta', tone: ContentTone.piccante),
        (a: 'Piacere a tutti tranne che alla tua crush', b: 'Piacere solo alla tua crush e a nessun altro', tone: ContentTone.piccante),
        (a: 'Messaggi letti sempre subito', b: 'Risposte garantite entro un minuto', tone: ContentTone.piccante),
        (a: 'Poter ritirare un messaggio al giorno', b: 'Poter rileggere ogni messaggio cancellato dagli altri', tone: ContentTone.piccante),
        (a: 'Flirt spudorato ma solo il martedì', b: 'Flirt leggero ma tutti i giorni', tone: ContentTone.piccante),
        (a: 'Il gruppo sceglie il tuo prossimo appuntamento', b: 'Il gruppo legge la chat del tuo ultimo', tone: ContentTone.piccante),
        (a: 'Essere baciato senza preavviso dalla persona giusta', b: 'Annunciare ogni bacio dieci secondi prima', tone: ContentTone.piccante),
        (a: 'Un\'estate da single leggendaria', b: 'Un inverno in coppia perfetto', tone: ContentTone.piccante),
        (a: 'La tua crush vede tutte le tue storie', b: 'Tu vedi tutto quello che guarda lei', tone: ContentTone.piccante),
        (a: 'Un lento con la persona sbagliata davanti a quella giusta', b: 'Nessun lento mai più', tone: ContentTone.piccante),
        // --------------------------------------------- cattivo (extra)
        (a: 'Sesso solo al buio per sempre', b: 'Solo con la luce accesa per sempre', tone: ContentTone.cattivo),
        (a: 'Una sola posizione a vita', b: 'Tutte le posizioni tranne la tua preferita', tone: ContentTone.cattivo),
        (a: 'Dire la tua fantasia più spinta al gruppo', b: 'Mostrare la cronologia in incognito', tone: ContentTone.cattivo),
        (a: 'Un anno di castità', b: 'Un anno senza telefono', tone: ContentTone.cattivo),
        (a: 'Farti sentire dai vicini', b: 'Sentire i vicini ogni notte', tone: ContentTone.cattivo),
        (a: 'Solo sesso mattutino', b: 'Solo notti fonde', tone: ContentTone.cattivo),
        (a: 'Perfetto a letto ma pessimo a parole', b: 'Poeta meraviglioso ma disastro a letto', tone: ContentTone.cattivo),
        (a: 'Dire ogni tuo numero, body count incluso', b: 'Consegnare il telefono sbloccato per un\'ora', tone: ContentTone.cattivo),
        (a: 'Rivedere la tua prima volta in video', b: 'Raccontarla adesso nei dettagli decenti', tone: ContentTone.cattivo),
        (a: 'Iniziare sempre tu, per contratto', b: 'Aspettare sempre, anche per mesi', tone: ContentTone.cattivo),
        (a: 'Sesso senza mai baci', b: 'Baci senza mai altro', tone: ContentTone.cattivo),
        (a: 'Una notte con l\'ex peggiore', b: 'Sei mesi senza nessuno', tone: ContentTone.cattivo),
        (a: 'Il gruppo sente i tuoi vocali delle tre di notte', b: 'Il gruppo legge il tuo ultimo sexting', tone: ContentTone.cattivo),
        (a: 'Beccato dai tuoi nel momento peggiore', b: 'Beccare i tuoi nel momento peggiore', tone: ContentTone.cattivo),
        (a: 'Dimenticare le tue notti migliori', b: 'Ricordarle tutte ma non poterle mai raccontare', tone: ContentTone.cattivo),
        (a: 'Provare un fetish assegnato dal gruppo', b: 'Confessare adesso il tuo', tone: ContentTone.cattivo),
        (a: 'Solo avventure di una notte per sempre', b: 'Solo relazioni serissime dal primo giorno', tone: ContentTone.cattivo),
        (a: 'Una storia segreta per sempre segreta', b: 'Tutto pubblico dal primo giorno', tone: ContentTone.cattivo),
        (a: 'Un amico di letto che si innamora sempre', b: 'Innamorarti sempre tu degli amici di letto', tone: ContentTone.cattivo),
        (a: 'Dire ad alta voce chi dei presenti ti attrae', b: 'Che i presenti votino chi attrai tu', tone: ContentTone.cattivo),
        (a: 'Il cassetto dei segreti trovato da tua madre', b: 'Trovato dal tuo capo', tone: ContentTone.cattivo),
        (a: 'Sesso solo in casa tua per sempre', b: 'Mai più in casa tua', tone: ContentTone.cattivo),
        (a: 'Doccia in due sempre obbligatoria', b: 'Mai più docce in due', tone: ContentTone.cattivo),
        (a: 'Dormire sempre nudo ovunque', b: 'Sempre vestito da capo a piedi, anche in luna di miele', tone: ContentTone.cattivo),
        (a: 'Un tatuaggio con il nome di ogni ex', b: 'Un elenco pubblico online dei tuoi ex', tone: ContentTone.cattivo),
        (a: 'Fare sempre troppo rumore', b: 'Silenzio assoluto obbligatorio per sempre', tone: ContentTone.cattivo),
        (a: 'Il tuo ex fa da referenza a ogni tuo nuovo partner', b: 'Nessuna referenza ma tanti sospetti', tone: ContentTone.cattivo),
        (a: 'Sapere quante volte hanno finto con te', b: 'Vivere sereno nel dubbio', tone: ContentTone.cattivo),
        (a: 'Sesso da dieci una volta al mese', b: 'Da sei ogni giorno', tone: ContentTone.cattivo),
        (a: 'Sempre troppo veloce', b: 'Sempre troppo lungo', tone: ContentTone.cattivo),
        (a: 'La tua playlist hot parte in ufficio', b: 'Il tuo ultimo messaggio hot letto a una cena di famiglia', tone: ContentTone.cattivo),
        (a: 'Una notte con la tua celebrity crush ma lo sanno tutti', b: 'Segreto totale ma nessuno ti crederà mai', tone: ContentTone.cattivo),
        (a: 'Solo posti pubblici rischiosi', b: 'Solo il tuo letto per sempre', tone: ContentTone.cattivo),
        (a: 'Confessare il posto più assurdo dove l\'hai fatto', b: 'Farlo indovinare al gruppo con le domande', tone: ContentTone.cattivo),
        (a: 'Mai più preliminari', b: 'Solo preliminari', tone: ContentTone.cattivo),
        (a: 'Ogni appuntamento finisce a letto', b: 'Nessuno ci finisce mai al primo', tone: ContentTone.cattivo),
        (a: 'Sapere il voto che ti danno gli ex', b: 'Dare tu i voti pubblicamente', tone: ContentTone.cattivo),
        (a: 'Un weekend senza limiti ma senza poterlo raccontare', b: 'Una serata normale ma raccontabile per anni', tone: ContentTone.cattivo),
        (a: 'Il tuo momento più imbarazzante raccontato da chi c\'era', b: 'Raccontarlo tu ma per intero', tone: ContentTone.cattivo),
        (a: 'Perdere per sempre la tua posizione preferita', b: 'Doverla spiegare adesso al gruppo', tone: ContentTone.cattivo),
        (a: 'Solo sesso programmato in agenda', b: 'Solo improvviso nei momenti peggiori', tone: ContentTone.cattivo),
        (a: 'Dire ogni volta "è stato il migliore"', b: 'Non poter mai commentare', tone: ContentTone.cattivo),
        (a: 'Un mese senza toccare il partner', b: 'Un mese senza parlargli', tone: ContentTone.cattivo),
        (a: 'Che si sappia sempre quando l\'hai fatto', b: 'Che nessuno ti creda mai', tone: ContentTone.cattivo),
        (a: 'Vestiti strappati ogni volta, a tue spese', b: 'Piegare sempre tutto prima, con calma', tone: ContentTone.cattivo),
        (a: 'L\'ex nella stanza accanto ogni notte', b: 'L\'ex nel tuo gruppo di amici per sempre', tone: ContentTone.cattivo),
        (a: 'Raccontare il tuo sogno erotico più assurdo', b: 'Che il protagonista lo scelga il gruppo', tone: ContentTone.cattivo),
        (a: 'Mai più sesso in vacanza', b: 'Solo sesso in vacanza', tone: ContentTone.cattivo),
        (a: 'Perdere il conto delle tue notti', b: 'Un contatore pubblico sempre aggiornato', tone: ContentTone.cattivo),
        (a: 'Sedurre sempre con la stessa identica frase', b: 'Mai più parlare durante la seduzione', tone: ContentTone.cattivo),
        (a: 'I vicini sanno sempre quando sei in compagnia', b: 'Il tuo gruppo riceve una notifica', tone: ContentTone.cattivo),
        (a: 'Colazione ogni volta con la famiglia dell\'altro', b: 'Uscire sempre dalla finestra', tone: ContentTone.cattivo),
        (a: 'Sesso solo con musica trap', b: 'Solo con musica classica a tutto volume', tone: ContentTone.cattivo),
        (a: 'Dormire sempre lì, obbligatorio', b: 'Non poter mai restare a dormire', tone: ContentTone.cattivo),
        (a: 'Il primo pensiero del mattino detto ad alta voce', b: 'L\'ultimo pensiero della notte pubblicato', tone: ContentTone.cattivo),
        (a: 'Mai più baci sul collo', b: 'Solo baci sul collo', tone: ContentTone.cattivo),
        (a: 'Bravissimo ma dimentichi tutto ogni volta', b: 'Ricordi tutto ma sei mediocre', tone: ContentTone.cattivo),
        (a: 'La verità vera su com\'è andata, sempre', b: 'Complimenti garantiti ma mai sinceri', tone: ContentTone.cattivo),
        (a: 'Rifare per sempre la tua notte migliore', b: 'Una notte nuova ma a sorpresa totale', tone: ContentTone.cattivo),
        (a: 'Sesso solo dopo tre appuntamenti esatti', b: 'Solo al primo o mai più', tone: ContentTone.cattivo),
        (a: 'Tutti sanno il tuo fetish', b: 'Non poterlo mai più praticare', tone: ContentTone.cattivo),
        (a: 'Un anno da single con ricordi vividissimi', b: 'In coppia ma con amnesia delle notti', tone: ContentTone.cattivo),
        (a: 'Spogliarello obbligatorio a ogni festa', b: 'Mai più spogliarsi con la luce accesa', tone: ContentTone.cattivo),
        (a: 'Dirlo sempre quando provi attrazione', b: 'Non poterlo mai far capire', tone: ContentTone.cattivo),
        (a: 'Il gruppo sceglie con chi flirti stasera', b: 'Il gruppo guarda come flirti di solito', tone: ContentTone.cattivo),
        (a: 'Mai più la mattina', b: 'Mai più la notte', tone: ContentTone.cattivo),
        (a: 'Solo hotel a ore', b: 'Solo casa dei tuoi', tone: ContentTone.cattivo),
        (a: 'Sesso fantastico ma solo d\'estate', b: 'Mediocre ma tutto l\'anno', tone: ContentTone.cattivo),
        (a: 'Sapere cosa pensa davvero durante', b: 'Che sappia ogni cosa che pensi tu', tone: ContentTone.cattivo),
        (a: 'Il tuo tipo lo sceglie il gruppo per un anno', b: 'Lo sceglie il tuo ex', tone: ContentTone.cattivo),
        (a: 'Ogni appuntamento commentato in cuffia dal gruppo', b: 'Sempre da solo senza consigli', tone: ContentTone.cattivo),
        (a: 'Una notte da raccontare per dieci anni', b: 'Dieci notti da dimenticare subito', tone: ContentTone.cattivo),
        (a: 'Il tuo prossimo partner è in questa stanza', b: 'Non sarà mai nessuno dei presenti', tone: ContentTone.cattivo),
        (a: 'Confessare adesso la cosa più spinta che hai fatto', b: 'La racconta il tuo migliore amico al posto tuo', tone: ContentTone.cattivo),
        (a: 'Un weekend di passione con zero conversazione', b: 'Un weekend di conversazione perfetta e basta', tone: ContentTone.cattivo),
        (a: 'Che ogni tuo ex dica la sua versione di voi', b: 'Non poter mai raccontare la tua', tone: ContentTone.cattivo),
      ];

  static const List<({String a, String b})> it = <({String a, String b})>[
    (a: 'Sapere come morirai', b: 'Sapere quando'),
    (a: 'Una verità scomoda', b: 'Una bugia comoda'),
    (a: 'Più soldi', b: 'Più tempo libero'),
    (a: 'Essere famoso', b: 'Essere invisibile alla gente'),
    (a: 'Viaggiare nel passato', b: 'Viaggiare nel futuro'),
    (a: 'Saper volare', b: 'Essere invisibile'),
    (a: 'Leggere nel pensiero', b: 'Prevedere il futuro'),
    (a: 'Mai più social', b: 'Mai più film'),
    (a: 'Perdere il telefono', b: 'Perdere le chiavi di casa'),
    (a: 'Sempre 5 minuti in anticipo', b: 'Sempre 10 minuti in ritardo'),
    (a: 'Capo simpatico ma incapace', b: 'Capo antipatico ma bravo'),
    (
      a: 'Stipendio alto e lavoro noioso',
      b: 'Stipendio basso e lavoro che ami',
    ),
    (a: 'Matrimonio con 200 invitati', b: 'Matrimonio in due'),
    (a: 'Una settimana senza uscire', b: 'Uscire tutte le sere'),
    (a: 'Dormire 10 ore', b: 'Dormire 5 ore e stare benissimo'),
    (a: 'Rifare la vacanza perfetta', b: 'Provare un posto nuovo'),
    (a: 'Controllare il conto ogni giorno', b: 'Non guardarlo mai'),
    (a: 'Superpotere inutile ma divertente', b: 'Superpotere utile ma noioso'),
    (a: 'Rileggere sempre lo stesso libro', b: 'Non finirne mai uno'),
    (a: 'Vita senza musica', b: 'Vita senza cinema'),
    (a: 'Sapere sempre la verità', b: 'Vivere felice nell\'illusione'),
    (a: 'Un anno sabbatico', b: 'Andare in pensione un anno prima'),
    (a: 'Parlare tutte le lingue', b: 'Suonare tutti gli strumenti'),
    (a: 'Non provare mai imbarazzo', b: 'Non provare mai paura'),
    (a: 'Rivivere il tuo giorno migliore', b: 'Cancellare il peggiore'),
    (a: 'Convivere dopo un mese', b: 'Convivere dopo anni'),
    (a: 'Figli presto', b: 'Figli tardi'),
    (a: 'Vacanza organizzata nei minimi dettagli', b: 'Partire all\'avventura'),
    (a: 'Una stagione tutta in una notte', b: 'Un episodio a settimana'),
    (a: 'Batteria sempre all\'1%', b: 'Internet lentissimo'),
    (
      a: 'Vestiti sempre un po\' bagnati',
      b: 'Sassolino nella scarpa per sempre',
    ),
    (a: 'Dire sempre ciò che pensi', b: 'Non poter più parlare'),
    (
      a: 'Niente riscaldamento d\'inverno',
      b: 'Niente aria condizionata d\'estate',
    ),
    (a: 'Singhiozzo a vita', b: 'Starnutire ogni due minuti'),
    (a: 'Piatto preferito a ogni pasto', b: 'Mai più il tuo piatto preferito'),
    (a: 'Mai più bisogno di dormire', b: 'Mai più bisogno di mangiare'),
    (a: 'Ricco ma senza amici', b: 'Squattrinato ma amatissimo'),
    (a: 'Niente più affitto a vita', b: 'Stipendio raddoppiato'),
    (a: 'Il più simpatico della stanza', b: 'Il più intelligente della stanza'),
    (a: 'Memoria fotografica', b: 'Dimenticare ogni figuraccia'),
    (a: 'Mai più code', b: 'Mai più traffico'),
    (a: 'Sopracciglia rasate per un anno', b: 'Capelli verde fluo per un anno'),
    (a: 'Perdere l\'olfatto', b: 'Perdere il gusto'),
    (a: 'Voce da cartone animato', b: 'Risata che imbarazza tutti'),
    (a: 'Cronologia visibile ai genitori', b: 'Chat lette dal tuo capo'),
    (a: 'Ruttare alla fine di ogni frase', b: 'Ridere come una capra'),
    (
      a: 'Usare lo spazzolino di uno sconosciuto',
      b: 'Bere dal suo bicchiere già usato',
    ),
    (a: 'Palmi sempre sudati', b: 'Labbra sempre screpolate'),
    (a: 'Uscire con il tuo ex', b: 'Con l\'ex del tuo migliore amico'),
    (a: 'Puzzette rumorose ma inodori', b: 'Silenziose ma micidiali'),
    (a: 'Dimenticare chi sei', b: 'Essere dimenticato da tutti'),
    (a: 'Perdere tutti i soldi', b: 'Perdere tutti i ricordi'),
    (a: 'Partner ricco ma noioso', b: 'Partner squattrinato ma esilarante'),
    (a: 'Un\'ora in ascensore col tuo ex', b: 'Un\'ora in ascensore col capo'),
    (a: 'Compleanno dimenticato da tutti', b: 'Festa a sorpresa imbarazzante'),
    (a: 'Il tuo segreto svelato a tutti', b: 'Sapere i segreti di tutti'),
    (a: 'Famoso ma odiato', b: 'Sconosciuto ma amato'),
    (a: 'Non ridere mai più', b: 'Non piangere mai più'),
    (
      a: 'Tornare alle superiori per un anno',
      b: 'Rifare l\'esame di maturità ogni anno',
    ),
    (a: 'Vivere in un film horror', b: 'Vivere in un musical'),
    (a: 'Piedi al posto delle mani', b: 'Mani al posto dei piedi'),
    (
      a: 'Sfidare un\'anatra grande come un cavallo',
      b: 'Cento cavalli grandi come anatre',
    ),
    (a: 'Vivere sott\'acqua', b: 'Vivere nello spazio'),
    (
      a: 'Inseguito a vita da una lumaca killer',
      b: 'Un clown che ti fissa ogni notte',
    ),
    (a: 'Parlare con gli animali', b: 'Controllare il meteo'),
    (a: 'Ballare appena parte la musica', b: 'Piangere quando qualcuno ride'),
    (
      a: 'Ogni mattina in un paese diverso',
      b: 'Mai più uscire dalla tua città',
    ),
    (a: 'Vivere in un videogioco', b: 'Vivere in un cartone animato'),
    (a: 'Tasto "pausa" per la vita', b: 'Tasto "riavvolgi" per la vita'),
    (a: 'Teletrasporto ma perdi sempre le scarpe', b: 'Volare a passo d\'uomo'),
    (a: 'Vivere 1000 anni', b: 'Dieci vite da 100 anni'),
    (a: 'Pioggia di tacos', b: 'Neve di gelato'),
    (a: 'Re del mondo per un giorno', b: 'Persona normale per sempre'),
    (
      a: 'Sapere tutto ma non provare emozioni',
      b: 'Provare tutto ma non capire niente',
    ),
    (a: 'Cancellare un rimpianto', b: 'Garantirti un successo futuro'),
    (a: 'Sempre affamato', b: 'Sempre assonnato'),
    (
      a: 'Coda che scodinzola quando sei felice',
      b: 'Orecchie che si abbassano se sei triste',
    ),
    (a: 'Rinunciare al caffè per sempre', b: 'Rinunciare al cioccolato'),
    (
      a: 'Naso che cresce quando menti',
      b: 'Capelli che cambiano colore con l\'umore',
    ),
    (a: 'Trovare l\'amore della vita', b: 'Trovare il lavoro dei sogni'),
    (a: 'Ricchissimo ma sempre triste', b: 'Al verde ma sempre felice'),
    (a: 'Un milione subito', b: '3.000 euro al mese a vita'),
    (a: 'Salvare il tuo cane', b: 'Salvare uno sconosciuto'),
    (a: 'Non poter mai mentire', b: 'Credere a ogni bugia'),
    (a: 'Avere sempre ragione ma da solo', b: 'Sbagliare ma in compagnia'),
    (a: 'Genio incompreso', b: 'Sempliciotto felice'),
    (a: 'Stesso outfit ogni giorno', b: 'Mai ripetere un outfit'),
    (a: 'Cantare tutto ciò che dici', b: 'Camminare solo all\'indietro'),
    (a: 'Wi-Fi gratis ovunque a vita', b: 'Voli gratis a vita'),
    (a: 'Mangiare solo cibo bollente', b: 'Solo cibo ghiacciato'),
    (a: 'Mai più pizza', b: 'Mai più pasta'),
    (a: 'Mai più aperitivi', b: 'Mai più cibo a domicilio'),
    (a: 'Vita lunga piena di rimpianti', b: 'Vita breve senza rimpianti'),
    (a: 'Amare senza essere ricambiato', b: 'Essere amato da chi non ami'),
    (a: 'Il partner legge i tuoi pensieri', b: 'Tu leggi i suoi'),
    (a: 'Partner scelto dai tuoi amici', b: 'Partner scelto da un algoritmo'),
    (a: 'Capire sempre chi ti mente', b: 'Non farti mai beccare quando menti'),
    (a: 'Rivivere per sempre i tuoi 18 anni', b: 'Saltare direttamente ai 40'),
    (a: 'Dormire sempre a casa di altri', b: 'Avere sempre ospiti a casa tua'),
    (
      a: 'Concerto della tua band preferita da solo',
      b: 'Festival con amici ma musica che odi',
    ),
    (
      a: 'Fare karaoke stonando davanti a tutti',
      b: 'Ballare da solo in pista per un\'ora',
    ),
    (a: 'Perdere tutte le foto del telefono', b: 'Perdere tutte le chat'),
    (a: 'Starnutire coriandoli', b: 'Ruttare bolle di sapone'),
    (a: 'Avere quattro braccia', b: 'Avere quattro gambe'),
    (a: 'Essere alto 2 metri e 20', b: 'Essere alto un metro e 20'),
    (a: 'Vivere senza estate', b: 'Vivere senza inverno'),
    (a: 'Salvare cinque sconosciuti', b: 'Salvare il tuo migliore amico'),
    (a: 'Un milione ma mai più smartphone', b: 'Zero soldi ma col telefono'),
    (a: 'Lavoro dei sogni all\'estero', b: 'Lavoro noioso vicino agli amici'),
    (a: 'Avere 25 anni per sempre', b: 'Invecchiare con i tuoi amici'),
    (a: 'Casa dei sogni in mezzo al nulla', b: 'Monolocale in pieno centro'),
    (
      a: 'Sapere cosa dicono di te alle spalle',
      b: 'Vivere sereno senza saperlo',
    ),
    (a: 'Ogni pasto cucinato da uno chef', b: 'Autista personale a vita'),
    (
      a: 'Commentare ad alta voce tutto ciò che fai',
      b: 'Sentire la voce narrante della tua vita',
    ),
    (a: 'Camminare sui Lego ogni mattina', b: 'Doccia gelata ogni mattina'),
    (a: 'Zanzara in camera ogni notte', b: 'Mosca sul piatto a ogni pasto'),
    (a: 'Autocorrettore impazzito a vita', b: 'Mai più emoji'),
    (a: 'Chiamate solo in vivavoce', b: 'Schermo sempre visibile a tutti'),
    (
      a: 'Il tuo cane parla ma ti critica',
      b: 'Il tuo specchio ti fa complimenti falsi',
    ),
    (a: 'Un milione solo per te', b: 'Centomila a testa per il gruppo'),
    (a: 'Essere sempre sottovalutato', b: 'Essere sempre sopravvalutato'),
    (
      a: 'Riscoprire da zero la tua serie preferita',
      b: 'Vedere in anteprima ogni finale',
    ),
    (a: 'Parlare solo urlando', b: 'Parlare solo sussurrando'),
    (a: 'Ridere sempre nei momenti seri', b: 'Piangere a ogni film comico'),
    (a: 'Mangiare sempre con le mani', b: 'Mangiare tutto col cucchiaino'),
    (
      a: 'I tuoi sogni proiettati agli amici',
      b: 'Gli amici leggono il tuo diario',
    ),
    (a: 'Unico single del gruppo per sempre', b: 'Primo del gruppo a sposarti'),
    (a: 'Rinascere negli anni \'80', b: 'Nascere nel 2050'),
    (
      a: 'Ristoranti gratis ma sempre da solo',
      b: 'Pagare sempre ma in compagnia',
    ),
    (a: 'Virale per una figuraccia epica', b: 'Mai più di 10 like'),
    (a: 'Bere solo acqua per sempre', b: 'Mai più acqua, solo bibite'),
    (a: 'Un solo genere musicale a vita', b: 'Una sola app sul telefono'),
    (a: 'In smoking in spiaggia', b: 'In costume a un matrimonio'),
    (a: 'Cucinare da chef stellato', b: 'Casa che si pulisce da sola'),
    (
      a: 'Volo lungo accanto a un chiacchierone',
      b: 'Volo lungo accanto a un neonato',
    ),
    (a: 'Colazione salata per sempre', b: 'Cena dolce per sempre'),
    (a: 'Vivere senza specchi', b: 'Vivere senza orologi'),
    (a: 'Rivivere lo stesso lunedì', b: 'Saltare tutti i venerdì'),
    (a: 'Parlare con le piante', b: 'Capire i neonati'),
    (a: 'Vincere sempre a carte', b: 'Trovare sempre parcheggio'),
    (a: 'Estate di 40 gradi senza mare', b: 'Inverno gelido senza neve'),
    (a: 'Solo film doppiati malissimo', b: 'Solo film coi sottotitoli sfasati'),
    (a: 'Caffè gratis a vita', b: 'Gelato gratis a vita'),
    (a: 'Trasloco ogni anno', b: 'Stessa casa per sempre'),
    (
      a: 'Suoneria imbarazzante per sempre',
      b: 'Sfondo imbarazzante per sempre',
    ),
    (a: 'Essere un meme famoso', b: 'Avere un sosia famoso'),
    (
      a: 'Ballare la macarena a ogni saluto',
      b: 'Salutare tutti con l\'inchino',
    ),
    (a: 'Nutella senza pane', b: 'Pane senza Nutella'),
    (a: 'Weekend infinito ma sempre pioggia', b: 'Solo lunedì ma sempre sole'),
    (
      a: 'Un solo piatto ma cucinato perfetto',
      b: 'Cucinare tutto in modo mediocre',
    ),
    (a: 'Viaggio su Marte senza ritorno', b: 'Mai più lasciare l\'Italia'),
    (a: 'Dormire ogni notte in tenda', b: 'Dormire ogni notte sul divano'),
    (a: 'Un maggiordomo robot', b: 'Un cuoco robot'),
    (a: 'Mai più ascensori', b: 'Mai più scale mobili'),
    (a: 'Sapere ogni gossip di Hollywood', b: 'Sapere ogni finale di serie tv'),
    (a: 'Solo cibo piccante per un anno', b: 'Mai più sale'),
    (a: 'Vivere senza musica', b: 'Vivere senza film'),
    (a: 'Sempre cinque minuti in ritardo', b: 'Sempre un\'ora in anticipo'),
    (a: 'Ballare benissimo una sola canzone', b: 'Ballare così così qualsiasi canzone'),
    (a: 'Estate eterna', b: 'Inverno eterno'),
    (a: 'Mai più fritto', b: 'Mai più dolci'),
    (a: 'Leggere il pensiero dei cani', b: 'Parlare con i gatti'),
    (a: 'Azzeccare sempre la fila più veloce', b: 'Azzeccare sempre l\'ascensore giusto'),
    (a: 'Casa in montagna', b: 'Casa al mare'),
    (
      a: 'Rivivere lo stesso giorno perfetto',
      b: 'Un giorno nuovo ma imprevedibile',
    ),
    (a: 'Wi-Fi lento per sempre', b: 'Batteria sempre al dieci per cento'),
    (
      a: 'Essere invisibile un\'ora al giorno',
      b: 'Volare dieci minuti al giorno',
    ),
    (a: 'Solo docce fredde', b: 'Solo treni regionali'),
    (a: 'Cucinare per dieci ogni sera', b: 'Lavare i piatti di dieci ogni sera'),
    (
      a: 'Zaino pesante ma con tutto il necessario',
      b: 'Zaino leggero ma mai la cosa giusta',
    ),
    (
      a: 'Foto sempre venute male ma ricordi perfetti',
      b: 'Foto perfette ma ricordi confusi',
    ),
    (a: 'Un karaoke obbligatorio a settimana', b: 'Un discorso in pubblico al mese'),
    (a: 'Un maggiordomo umano imbarazzante', b: 'Un robot che ti giudica in silenzio'),
  ];
}
