import '../content_tone.dart';

/// Coppie di "Preferisci" in francese: parità completa col mazzo italiano.
class PreferisciPoolFr {
  const PreferisciPoolFr._();

  static const List<({String a, String b})> pairs = <({String a, String b})>[
    (a: 'Savoir comment tu vas mourir', b: 'Savoir quand'),
    (a: 'Une vérité qui dérange', b: 'Un mensonge confortable'),
    (a: 'Plus d\'argent', b: 'Plus de temps libre'),
    (a: 'Être célèbre', b: 'Être invisible aux yeux des gens'),
    (a: 'Voyager dans le passé', b: 'Voyager dans le futur'),
    (a: 'Savoir voler', b: 'Être invisible'),
    (a: 'Lire les pensées', b: 'Prédire l\'avenir'),
    (a: 'Plus jamais de réseaux', b: 'Plus jamais de films'),
    (a: 'Perdre ton téléphone', b: 'Perdre tes clés de maison'),
    (a: 'Toujours 5 minutes en avance', b: 'Toujours 10 minutes en retard'),
    (a: 'Chef sympa mais incompétent', b: 'Chef odieux mais brillant'),
    (a: 'Gros salaire, boulot ennuyeux', b: 'Petit salaire, boulot passion'),
    (a: 'Mariage à 200 invités', b: 'Mariage à deux'),
    (a: 'Une semaine sans sortir', b: 'Sortir tous les soirs'),
    (a: 'Dormir 10 heures', b: 'Dormir 5 heures et être en forme'),
    (a: 'Refaire les vacances parfaites', b: 'Tester un endroit nouveau'),
    (a: 'Regarder ton compte chaque jour', b: 'Ne jamais le regarder'),
    (a: 'Superpouvoir inutile mais drôle', b: 'Superpouvoir utile mais chiant'),
    (a: 'Relire toujours le même livre', b: 'N\'en finir jamais aucun'),
    (a: 'Une vie sans musique', b: 'Une vie sans cinéma'),
    (a: 'Toujours savoir la vérité', b: 'Vivre heureux dans l\'illusion'),
    (a: 'Une année sabbatique', b: 'Partir à la retraite un an plus tôt'),
    (a: 'Parler toutes les langues', b: 'Jouer de tous les instruments'),
    (a: 'Ne jamais être gêné', b: 'Ne jamais avoir peur'),
    (a: 'Revivre ton plus beau jour', b: 'Effacer le pire'),
    (a: 'Vivre ensemble après un mois', b: 'Vivre ensemble après des années'),
    (a: 'Des enfants tôt', b: 'Des enfants tard'),
    (a: 'Vacances planifiées au détail', b: 'Partir à l\'aventure'),
    (a: 'Une saison en une nuit', b: 'Un épisode par semaine'),
    (a: 'Batterie toujours à 1%', b: 'Internet ultra lent'),
    (
      a: 'Vêtements toujours un peu mouillés',
      b: 'Un caillou dans la chaussure à vie',
    ),
    (a: 'Toujours dire ce que tu penses', b: 'Ne plus pouvoir parler'),
    (a: 'Pas de chauffage en hiver', b: 'Pas de clim en été'),
    (a: 'Le hoquet à vie', b: 'Éternuer toutes les deux minutes'),
    (a: 'Ton plat préféré à chaque repas', b: 'Plus jamais ton plat préféré'),
    (a: 'Ne plus avoir besoin de dormir', b: 'Ne plus avoir besoin de manger'),
    (a: 'Riche mais sans amis', b: 'Fauché mais adoré'),
    (a: 'Plus jamais de loyer', b: 'Salaire doublé'),
    (a: 'Le plus drôle de la salle', b: 'Le plus intelligent de la salle'),
    (a: 'Mémoire photographique', b: 'Oublier chaque humiliation'),
    (a: 'Plus jamais de files d\'attente', b: 'Plus jamais d\'embouteillages'),
    (a: 'Sourcils rasés pendant un an', b: 'Cheveux vert fluo pendant un an'),
    (a: 'Perdre l\'odorat', b: 'Perdre le goût'),
    (a: 'Une voix de dessin animé', b: 'Un rire qui gêne tout le monde'),
    (a: 'Historique visible par tes parents', b: 'Messages lus par ton patron'),
    (a: 'Roter à la fin de chaque phrase', b: 'Rire comme une chèvre'),
    (
      a: 'Utiliser la brosse à dents d\'un inconnu',
      b: 'Boire dans son verre déjà utilisé',
    ),
    (a: 'Mains toujours moites', b: 'Lèvres toujours gercées'),
    (a: 'Sortir avec ton ex', b: 'Avec l\'ex de ton meilleur ami'),
    (a: 'Des pets bruyants mais sans odeur', b: 'Silencieux mais mortels'),
    (a: 'Oublier qui tu es', b: 'Être oublié de tous'),
    (a: 'Perdre tout ton argent', b: 'Perdre tous tes souvenirs'),
    (a: 'Partenaire riche mais ennuyeux', b: 'Partenaire fauché mais hilarant'),
    (
      a: 'Une heure en ascenseur avec ton ex',
      b: 'Une heure en ascenseur avec ton chef',
    ),
    (a: 'Anniversaire oublié par tous', b: 'Fête surprise embarrassante'),
    (a: 'Ton secret révélé à tous', b: 'Connaître les secrets de tous'),
    (a: 'Célèbre mais détesté', b: 'Inconnu mais aimé'),
    (a: 'Ne plus jamais rire', b: 'Ne plus jamais pleurer'),
    (a: 'Retourner au lycée un an', b: 'Repasser le bac chaque année'),
    (a: 'Vivre dans un film d\'horreur', b: 'Vivre dans une comédie musicale'),
    (a: 'Des pieds à la place des mains', b: 'Des mains à la place des pieds'),
    (
      a: 'Un canard grand comme un cheval',
      b: 'Cent chevaux grands comme des canards',
    ),
    (a: 'Vivre sous l\'eau', b: 'Vivre dans l\'espace'),
    (
      a: 'Poursuivi à vie par un escargot tueur',
      b: 'Un clown qui te fixe chaque nuit',
    ),
    (a: 'Parler aux animaux', b: 'Contrôler la météo'),
    (a: 'Danser dès que la musique démarre', b: 'Pleurer quand quelqu\'un rit'),
    (
      a: 'Chaque matin dans un autre pays',
      b: 'Ne plus jamais quitter ta ville',
    ),
    (a: 'Vivre dans un jeu vidéo', b: 'Vivre dans un dessin animé'),
    (a: 'Une touche "pause" pour la vie', b: 'Une touche "retour" pour la vie'),
    (a: 'Téléportation mais sans chaussures', b: 'Voler au pas d\'un piéton'),
    (a: 'Vivre 1000 ans', b: 'Dix vies de 100 ans'),
    (a: 'Une pluie de tacos', b: 'Une neige de glace'),
    (a: 'Roi du monde pour un jour', b: 'Personne normale pour toujours'),
    (
      a: 'Tout savoir sans rien ressentir',
      b: 'Tout ressentir sans rien comprendre',
    ),
    (a: 'Effacer un regret', b: 'T\'assurer un succès futur'),
    (a: 'Toujours affamé', b: 'Toujours endormi'),
    (
      a: 'Une queue qui remue quand tu es content',
      b: 'Des oreilles qui tombent si tu es triste',
    ),
    (a: 'Renoncer au café pour toujours', b: 'Renoncer au chocolat'),
    (
      a: 'Un nez qui pousse quand tu mens',
      b: 'Des cheveux qui changent avec l\'humeur',
    ),
    (a: 'Trouver l\'amour de ta vie', b: 'Trouver le job de tes rêves'),
    (a: 'Très riche mais toujours triste', b: 'Fauché mais toujours heureux'),
    (a: 'Un million tout de suite', b: '3 000 euros par mois à vie'),
    (a: 'Sauver ton chien', b: 'Sauver un inconnu'),
    (a: 'Ne jamais pouvoir mentir', b: 'Croire à chaque mensonge'),
    (a: 'Toujours raison mais tout seul', b: 'Avoir tort mais bien accompagné'),
    (a: 'Génie incompris', b: 'Simplet heureux'),
    (a: 'La même tenue chaque jour', b: 'Ne jamais répéter une tenue'),
    (a: 'Chanter tout ce que tu dis', b: 'Marcher seulement à reculons'),
    (a: 'Wifi gratuit partout à vie', b: 'Vols gratuits à vie'),
    (a: 'Manger seulement brûlant', b: 'Manger seulement glacé'),
    (a: 'Plus jamais de pizza', b: 'Plus jamais de pâtes'),
    (a: 'Plus jamais d\'apéros', b: 'Plus jamais de livraison'),
    (a: 'Vie longue pleine de regrets', b: 'Vie courte sans aucun regret'),
    (
      a: 'Aimer sans être aimé en retour',
      b: 'Être aimé de qui tu n\'aimes pas',
    ),
    (a: 'Ton partenaire lit tes pensées', b: 'Tu lis les siennes'),
    (a: 'Partenaire choisi par tes amis', b: 'Partenaire choisi par un algo'),
    (
      a: 'Toujours démasquer les menteurs',
      b: 'Ne jamais être démasqué en mentant',
    ),
    (a: 'Revivre tes 18 ans pour toujours', b: 'Sauter directement à 40 ans'),
    (
      a: 'Dormir toujours chez les autres',
      b: 'Avoir toujours des invités chez toi',
    ),
    (
      a: 'Le concert de ton groupe mais seul',
      b: 'Un festival entre amis, musique nulle',
    ),
    (
      a: 'Un karaoké faux devant tout le monde',
      b: 'Danser seul une heure en piste',
    ),
    (a: 'Perdre toutes tes photos', b: 'Perdre toutes tes conversations'),
    (a: 'Éternuer des confettis', b: 'Roter des bulles de savon'),
    (a: 'Avoir quatre bras', b: 'Avoir quatre jambes'),
    (a: 'Mesurer 2 m 20', b: 'Mesurer 1 m 20'),
    (a: 'Vivre sans été', b: 'Vivre sans hiver'),
    (a: 'Sauver cinq inconnus', b: 'Sauver ton meilleur ami'),
    (
      a: 'Un million mais plus de smartphone',
      b: 'Zéro argent mais ton téléphone',
    ),
    (
      a: 'Le job de tes rêves à l\'étranger',
      b: 'Un job ennuyeux près de tes amis',
    ),
    (a: 'Avoir 25 ans pour toujours', b: 'Vieillir avec tes amis'),
    (a: 'La maison de rêve au milieu de rien', b: 'Un studio en plein centre'),
    (
      a: 'Savoir ce qu\'on dit derrière ton dos',
      b: 'Vivre tranquille sans le savoir',
    ),
    (a: 'Chaque repas cuisiné par un chef', b: 'Un chauffeur perso à vie'),
    (
      a: 'Commenter à voix haute tout ce que tu fais',
      b: 'Entendre la voix qui narre ta vie',
    ),
    (a: 'Marcher sur des Lego chaque matin', b: 'Douche glacée chaque matin'),
    (a: 'Un moustique chaque nuit', b: 'Une mouche à chaque repas'),
    (a: 'Correcteur auto fou à vie', b: 'Plus jamais d\'emojis'),
    (
      a: 'Appels toujours en haut-parleur',
      b: 'Écran toujours visible par tous',
    ),
    (
      a: 'Ton chien parle mais te critique',
      b: 'Ton miroir te flatte faussement',
    ),
    (a: 'Un million pour toi seul', b: 'Cent mille chacun pour le groupe'),
    (a: 'Toujours sous-estimé', b: 'Toujours surestimé'),
    (
      a: 'Redécouvrir ta série préférée',
      b: 'Voir chaque fin en avant-première',
    ),
    (a: 'Parler seulement en criant', b: 'Parler seulement en chuchotant'),
    (a: 'Rire dans les moments sérieux', b: 'Pleurer à chaque comédie'),
    (
      a: 'Manger toujours avec les mains',
      b: 'Tout manger à la petite cuillère',
    ),
    (a: 'Tes rêves projetés à tes amis', b: 'Tes amis lisent ton journal'),
    (a: 'Le seul célibataire du groupe', b: 'Le premier du groupe à te marier'),
    (a: 'Renaître dans les années 80', b: 'Naître en 2050'),
    (
      a: 'Restos gratuits mais toujours seul',
      b: 'Payer toujours mais bien accompagné',
    ),
    (a: 'Viral pour une honte épique', b: 'Jamais plus de 10 likes'),
    (
      a: 'Boire seulement de l\'eau à vie',
      b: 'Plus jamais d\'eau, que du soda',
    ),
    (a: 'Un seul genre musical à vie', b: 'Une seule appli sur ton téléphone'),
    (a: 'En smoking à la plage', b: 'En maillot à un mariage'),
    (a: 'Cuisiner comme un chef étoilé', b: 'Une maison qui se nettoie seule'),
    (a: 'Long vol à côté d\'un bavard', b: 'Long vol à côté d\'un bébé'),
    (a: 'Petit-déj salé pour toujours', b: 'Dîner sucré pour toujours'),
    (a: 'Vivre sans miroirs', b: 'Vivre sans horloges'),
    (a: 'Revivre le même lundi', b: 'Sauter tous les vendredis'),
    (a: 'Parler avec les plantes', b: 'Comprendre les bébés'),
    (a: 'Toujours gagner aux cartes', b: 'Toujours trouver une place'),
    (a: 'Été à 40 degrés sans mer', b: 'Hiver glacial sans neige'),
    (a: 'Que des films mal doublés', b: 'Que des sous-titres décalés'),
    (a: 'Café gratuit à vie', b: 'Glaces gratuites à vie'),
    (a: 'Déménager chaque année', b: 'La même maison pour toujours'),
    (
      a: 'Sonnerie gênante pour toujours',
      b: 'Fond d\'écran gênant pour toujours',
    ),
    (a: 'Être un mème célèbre', b: 'Avoir un sosie célèbre'),
    (
      a: 'Danser la macarena pour dire bonjour',
      b: 'Saluer tout le monde en s\'inclinant',
    ),
    (a: 'Du Nutella sans pain', b: 'Du pain sans Nutella'),
    (
      a: 'Week-end infini mais toujours pluie',
      b: 'Que des lundis mais toujours soleil',
    ),
    (a: 'Un seul plat mais parfait', b: 'Tout cuisiner de façon moyenne'),
  ];

  /// Dilemmi da modalità Hot: parità completa col mazzo italiano.
  static const List<({String a, String b, String tone})> hot =
      <({String a, String b, String tone})>[
        (
          a: 'Sortir tout nu pendant une minute',
          b: 'Embrasser quelqu\'un de ce groupe',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Passer la nuit avec un du groupe',
          b: 'Une nuit avec un ancien prof',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Montrer ta galerie au groupe',
          b: 'Faire lire tes messages tout haut',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Un an sans sexe',
          b: 'Un an sans sortir le soir',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Dire ton body count au groupe',
          b: 'Montrer ta dernière recherche',
          tone: ContentTone.piccante,
        ),
        (
          a: 'L\'amour sans le sexe',
          b: 'Le sexe sans l\'amour',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Partenaire beau mais nul au lit',
          b: 'Partenaire normal mais génial',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Une nuit avec ton ex',
          b: 'Une nuit avec un inconnu',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Surprendre tes parents',
          b: 'Être surpris par tes parents',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Dire à tous qui te plaît',
          b: 'Ne plus jamais lui parler',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Embrasser un du groupe les yeux fermés',
          b: 'Embrasser ton ex devant tous',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Ne plus pouvoir embrasser',
          b: 'Ne plus pouvoir faire de câlins',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Savoir avec qui on te tromperait',
          b: 'Ne jamais le savoir',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Que des rendez-vous à l\'aveugle un an',
          b: 'Que des dates choisies par ta mère',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Revoir ton premier baiser en vidéo',
          b: 'Que tout le groupe le revoie',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Gémir chaque fois que tu t\'assois',
          b: 'Crier le nom de ton ex à chaque toast',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Envoyer un nude à ton ex par erreur',
          b: 'L\'envoyer au groupe famille',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Sexto au patron par erreur',
          b: 'Appeler ton partenaire du nom de ton ex',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Une nuit avec une célébrité',
          b: 'Un mois de sexe avec ton ex',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Du sexe seulement dans le noir',
          b: 'Seulement avec la lumière allumée',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Dire ton fantasme le plus bizarre',
          b: 'Entendre celui de ta droite',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Sex friend avec ton meilleur ami',
          b: 'Plus de sexe pendant un an',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Un ex qui embrasse divinement',
          b: 'Un nouveau à tout apprendre',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Être déshabillé du regard au bar',
          b: 'Ne plus jamais être remarqué',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Raconter ton pire rendez-vous',
          b: 'Revivre ta honte la plus hot',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Faire toujours le premier pas',
          b: 'Attendre toujours l\'autre',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Un plan à trois avec des inconnus',
          b: 'Un plan à trois avec des amis',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Surprendre ton coloc en action',
          b: 'Être surpris par ton coloc',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Dire combien de fois tu y penses par jour',
          b: 'Dire quand c\'était la dernière fois',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Partenaire très jaloux mais brûlant',
          b: 'Partenaire calme mais paresseux',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Embrasser le premier qui entre',
          b: 'Embrasser le dernier qui t\'a écrit',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Nuit de passion sans baisers',
          b: 'Baisers infinis et rien d\'autre',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Oublier ta première fois',
          b: 'T\'en souvenir chaque jour',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Dire l\'endroit le plus fou où tu l\'as fait',
          b: 'Dire où tu aimerais le faire',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Un flirt avec ton coach sportif',
          b: 'Un flirt avec ton médecin',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Que des coups d\'un soir un an',
          b: 'Que des histoires sérieuses à vie',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Recoucher avec ton ex parfois',
          b: 'Arrêter à jamais mais le regretter',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Un patin avec celui de gauche',
          b: 'Un slow sensuel avec celui de droite',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Dormir nu avec un ami',
          b: 'Te doucher en maillot avec ton ex',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Recevoir un nude de ton patron',
          b: 'Lui en envoyer un par erreur',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Du sexe de dingue une fois par mois',
          b: 'Du sexe moyen tous les jours',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Savoir ce que l\'autre pense au lit',
          b: 'Qu\'il entende chacune de tes pensées',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Un week-end avec ton crush secret',
          b: 'Un mois avec ton premier amour',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Petit-déj au lit après la première nuit',
          b: 'Disparaître avant l\'aube',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Dire ton point faible au lit',
          b: 'Le mimer devant le groupe',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Te tatouer le nom de ton ex',
          b: 'Crier son nom au mauvais moment',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Un match avec ton ex sur une appli',
          b: 'Un match avec ton chef sur une appli',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Ton partenaire connaît tous tes fantasmes',
          b: 'Tu connais tous les siens',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Un strip-tease improvisé maintenant',
          b: 'Un récit très chaud de ton été',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Embrasser un du groupe à ton choix',
          b: 'En embrasser un choisi par le groupe',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Histoire secrète très passionnée',
          b: 'Histoire officielle mais tiède',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Du sexe seulement en été',
          b: 'Du sexe seulement en hiver',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Oublier toutes tes folles nuits',
          b: 'Te souvenir même des pires',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Audio hot envoyé au mauvais numéro',
          b: 'En recevoir un de ton patron',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Faire lire tes messages avec ton ex',
          b: 'Montrer tes photos avec ton ex',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Coup de foudre ce soir',
          b: 'Aventure d\'un soir ce soir',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Dire le nom de ton crush au groupe',
          b: 'Le faire deviner au groupe',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Un slow avec ton ex ce soir',
          b: 'Un karaoké romantique avec un du groupe',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Draguer un inconnu maintenant',
          b: 'Donner ton numéro au premier venu',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Un massage par un du groupe',
          b: 'En faire un à un du groupe',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Interdit de flirter pendant un an',
          b: 'Obligé de flirter avec tous',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Une nuit avec ton idole musicale',
          b: 'Un week-end avec ton acteur préféré',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Avouer un rêve chaud sur un présent',
          b: 'Qu\'un présent l\'avoue sur toi',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Silence total au lit',
          b: 'Commentaire complet au lit',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Un fessier de rêve',
          b: 'Un décolleté à applaudir',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Ton ex devient très célèbre',
          b: 'Ton ex devient ton patron',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Dire ce qui t\'excite le plus',
          b: 'Dire ce qui te coupe l\'envie',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Une aventure d\'été jamais avouée',
          b: 'Un amour à distance infini',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Deux présents te draguent',
          b: 'Draguer deux présents à la fois',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Voir ton ex avec plus beau que toi',
          b: 'Qu\'il te voie avec moins bien',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Des baisers avec morsure',
          b: 'Des bisous sages pour toujours',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Dormir enlacés sans sexe',
          b: 'Du sexe sans jamais dormir ensemble',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Du sexe avec la musique à fond',
          b: 'Avec le journal télé en fond',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Révéler ton nombre d\'ex',
          b: 'Révéler qui était le meilleur',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Draguer le serveur ce soir',
          b: 'Laisser ton numéro sur le ticket',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Première fois gênante mais tendre',
          b: 'Parfaite mais avec la mauvaise personne',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Un tatouage où le groupe décide',
          b: 'Un piercing où le groupe décide',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Un baiser de 30 secondes avec un présent',
          b: 'Dix baisers rapides avec dix inconnus',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Savoir qui du groupe rêve de toi',
          b: 'Savoir qui ne t\'embrasserait jamais',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Du sexe sous tente au camping plein',
          b: 'À l\'hôtel avec des murs en papier',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Des vacances que pour célibataires',
          b: 'Des vacances que pour couples',
          tone: ContentTone.piccante,
        ),
        (a: 'Avaler', b: 'Recracher', tone: ContentTone.cattivo),
        (
          a: 'Un plan à trois avec deux inconnus',
          b: 'Regarder ton/ta partenaire avec un autre',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Que du sexe oral pendant un an',
          b: 'Plus jamais de sexe oral',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Dominer toute la nuit',
          b: 'Être soumis toute la nuit',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Être attaché au lit',
          b: 'Attacher ton/ta partenaire',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Un orgasme retardé pendant une heure',
          b: 'Finir en trente secondes',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Du sexe anal',
          b: 'Que de la sodomie avec un jouet',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Porter un plug toute la journée',
          b: 'Porter des menottes toute la soirée',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Faire l\'amour dans un parc la nuit',
          b: 'Le faire dans les toilettes d\'un bar',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Un gode-ceinture sur ton/ta partenaire',
          b: 'Le/la laisser en mettre un sur toi',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Te faire bander les yeux tout le temps',
          b: 'Bander les yeux de l\'autre',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Une fessée jusqu\'à rougir',
          b: 'Griffer le dos jusqu\'au sang',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Un jeu de rôle infirmière coquine',
          b: 'Un jeu de rôle patron et secrétaire',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Du sexe filmé et gardé',
          b: 'Une photo nue envoyée par erreur',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Une partouze à cinq',
          b: 'Un vis-à-vis avec un autre couple',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Te masturber devant ton/ta partenaire',
          b: 'Le/la regarder se masturber',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Recevoir un massage érotique complet',
          b: 'Le donner sans avoir le droit d\'y toucher',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Jouir sans jamais toucher les parties',
          b: 'Toucher sans jamais jouir',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Un rendez-vous dans un club échangiste',
          b: 'Une soirée dans un donjon BDSM',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Faire l\'amour au réveil chaque matin',
          b: 'Une nuit sauvage une fois par mois',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Des préliminaires d\'une heure',
          b: 'Aller droit au but en cinq minutes',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Goûter à la douche dorée',
          b: 'Goûter au wax play à la bougie',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Un collier et une laisse au lit',
          b: 'Un bâillon-boule toute la scène',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Dire tes fantasmes les plus sales',
          b: 'Réaliser un fantasme du groupe',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Sexe sur la table de la cuisine',
          b: 'Sexe contre la vitre du salon',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Te faire lécher partout sans bouger',
          b: 'Lécher partout sans qu\'on te touche',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Un strip-tease intégral pour le groupe',
          b: 'Une lap dance privée pour un inconnu',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Sextoter avec un(e) ex tout un soir',
          b: 'Un appel vidéo hot avec un inconnu',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Un vibromasseur télécommandé en public',
          b: 'Des boules de geisha au restaurant',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Faire l\'amour dans un avion',
          b: 'Le faire dans un ascenseur bondé',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Un suçon bien visible dans le cou',
          b: 'Des marques de corde aux poignets',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Que ton/ta partenaire choisisse ta tenue sexy',
          b: 'Choisir la sienne toute la semaine',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Un orgasme forcé jusqu\'à supplier',
          b: 'Interdit de jouir de toute la nuit',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Sexe à trois avec un(e) ami(e) commun(e)',
          b: 'Sexe à trois avec deux inconnus',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Te faire dominer par une inconnue',
          b: 'Dominer un inconnu sur commande',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Une nuit dans une chambre à miroirs',
          b: 'Une nuit dans une pièce insonorisée',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Porter des sous-vêtements comestibles',
          b: 'Manger sur le corps de l\'autre',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Faire l\'amour sans jamais s\'embrasser',
          b: 'Que s\'embrasser pendant une heure',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Recevoir une fellation surprise',
          b: 'Faire un cunnilingus surprise',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Une orgie entre amis proches',
          b: 'Un club libertin avec des inconnus',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Te faire chevaucher jusqu\'à l\'épuisement',
          b: 'Chevaucher jusqu\'à ne plus tenir',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Du sexe rude avec des mots crus',
          b: 'Du sexe lent et silencieux',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Un plan cul régulier sans sentiments',
          b: 'Une nuit passionnée sans lendemain',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Te laisser tondre le pubis par l\'autre',
          b: 'Tondre celui de ton/ta partenaire',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Sexe dans une cabine d\'essayage',
          b: 'Sexe sur la banquette arrière',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Un test de nouveaux sextoys chaque semaine',
          b: 'Une nouvelle position imposée chaque nuit',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Te faire déshabiller très lentement',
          b: 'Déshabiller l\'autre avec les dents',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Une soirée où tu obéis à tout',
          b: 'Une soirée où tu commandes tout',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Faire l\'amour éclairé par des bougies',
          b: 'Le faire dans le noir complet',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Que ton/ta partenaire lise ton journal intime coquin',
          b: 'Qu\'il/elle écoute tes gémissements enregistrés',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Un doigté prolongé sans pénétration',
          b: 'Une pénétration sans préliminaires',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Te faire mordiller les tétons',
          b: 'Te faire tirer les cheveux',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Un rendez-vous nudiste sur la plage',
          b: 'Un sauna mixte entièrement nu',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Sexe pendant un orage sur le balcon',
          b: 'Sexe sous la pluie dans le jardin',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Te faire fouetter avec une cravache',
          b: 'Te faire caresser avec une plume',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Une nuit avec deux partenaires à la fois',
          b: 'Deux nuits séparées avec deux personnes',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Du sexe où tu ne peux pas faire un bruit',
          b: 'Du sexe où tu cries sans retenue',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Te faire embrasser le corps entier',
          b: 'Embrasser chaque centimètre de l\'autre',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Un fantasme d\'inconnu croisé dans un bar',
          b: 'Un fantasme de retrouvailles avec un ex',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Te faire ligoter façon shibari',
          b: 'Ligoter ton/ta partenaire au lit',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Faire l\'amour trois fois de suite',
          b: 'Une seule fois mais pendant deux heures',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Un jeu de rôle prof et élève majeur',
          b: 'Un jeu de rôle inconnus dans un train',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Te laisser mettre une note en direct',
          b: 'Noter la performance de l\'autre à voix haute',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Une gorge profonde sans les mains',
          b: 'Un cunnilingus les mains attachées',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Sexe devant un miroir en te regardant',
          b: 'Sexe filmé et regardé ensemble après',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Te faire réveiller par une caresse coquine',
          b: 'Réveiller l\'autre avec ta bouche',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Une partie fine masquée entre amis',
          b: 'Une soirée swing avec des voisins',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Interdit de porter des sous-vêtements un jour',
          b: 'Interdit de te toucher pendant une semaine',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Te faire asperger de champagne au lit',
          b: 'Asperger l\'autre de chocolat fondu',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Un plan à quatre bien organisé',
          b: 'Un plan spontané avec des inconnus',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Faire l\'amour dans la voiture au feu rouge',
          b: 'Le faire dans le vestiaire de la salle',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Recevoir des ordres sexy par oreillette',
          b: 'Donner des ordres à l\'autre à distance',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Te faire chatouiller jusqu\'à supplier',
          b: 'Te faire caresser jusqu\'à trembler',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Une nuit entière de sexe tantrique',
          b: 'Un quickie brûlant dans la cuisine',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Un baiser parfait par mois',
          b: 'Des baisers moyens chaque jour',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Savoir ce que ton crush pense de toi',
          b: 'Qu\'il sache tout ce que tu penses',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Une nuit inoubliable sans suite',
          b: 'Dix dates mignonnes sans étincelle',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Dormir enlacés et rien de plus',
          b: 'Tout le reste mais aucun câlin après',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Dire ton body count à ton crush',
          b: 'Montrer ton dernier chat brûlant',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Partenaire qui embrasse très bien',
          b: 'Partenaire qui écrit très bien',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Flirter devant tes parents',
          b: 'Flirter devant ton ex',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Recevoir une photo osée par erreur',
          b: 'En envoyer une au mauvais contact',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Être séduit par les mots',
          b: 'Être séduit par le regard',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Week-end de passion sans téléphone',
          b: 'Semaine de flirt seulement par chat',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Premier baiser au premier rendez-vous',
          b: 'Premier baiser après un mois d\'attente',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Savoir qui te regarde dans un bar',
          b: 'L\'ignorer mais être très regardé',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Un ex qui t\'écrit chaque nuit',
          b: 'Un crush qui ne t\'écrit jamais',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Un slow avec ton crush devant tous',
          b: 'Dîner aux chandelles en silence',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Faire lire ton chat avec ton crush',
          b: 'L\'appeler tout de suite en haut-parleur',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Un massage parfait chaque soir',
          b: 'Petit-déj au lit chaque matin',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Être le meilleur baiser de quelqu\'un',
          b: 'Recevoir le meilleur baiser de ta vie',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Plus jamais de premiers rendez-vous',
          b: 'Que des premiers rendez-vous à vie',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Dire "tu me plais" toujours en premier',
          b: 'Attendre toujours qu\'on te le dise',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Une playlist qui démarre si tu flirtes',
          b: 'Une voix qui commente tes dates',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Ton ex à ton mariage',
          b: 'Ta belle-mère en lune de miel',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Revoir ton premier baiser filmé',
          b: 'Montrer ton profil de rencontres',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Un froid à chaque "il faut qu\'on parle"',
          b: 'Ne jamais l\'entendre de ta vie',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Un flirt d\'été chaque été',
          b: 'Un vrai amour tous les dix ans',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Savoir combien de fois on a parlé de toi',
          b: 'Savoir ce qu\'on a dit mais pas qui',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Des baisers que sous la pluie',
          b: 'Des baisers que dans l\'ascenseur',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Un "bonjour" de la bonne personne',
          b: 'Une "bonne nuit" chaque soir',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Perdre ta voix quand tu flirtes',
          b: 'Toujours dire un mot de trop',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Être irrésistible que le jour',
          b: 'Être irrésistible que la nuit',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Un date à l\'aveugle choisi par le groupe',
          b: 'Un date organisé par ton ex',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Dîner avec le conjoint de ton crush',
          b: 'Leur servir de chauffeur toute la soirée',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Repérer les mensonges en amour',
          b: 'Ne jamais mentir le premier',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Un an sans baisers',
          b: 'Un an sans câlins',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Avouer ton crush à la personne',
          b: 'L\'avouer à toute la salle maintenant',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Célèbre pour une histoire d\'amour',
          b: 'Célèbre pour un râteau épique',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Sortir avec ton sosie',
          b: 'Sortir avec ton exact opposé',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Ton journal lu par ton crush',
          b: 'Ton historique lu par tes parents',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Un baiser volé inoubliable',
          b: 'Cent baisers demandés poliment',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Paraître toujours indifférent',
          b: 'Paraître toujours trop intéressé',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Un coup de foudre une seule fois',
          b: 'Des coups de foudre jamais rendus',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Des fleurs au bureau chaque semaine',
          b: 'Un vocal romantique chaque soir',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Très bien flirter que par écrit',
          b: 'Très bien flirter qu\'en vrai',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Un crush pour un ami de ce groupe',
          b: 'Un crush pour un collègue de bureau',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Savoir si le premier date ira bien',
          b: 'Pouvoir refaire chaque premier date',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Un date romantique planifié à la minute',
          b: 'Improvisation totale chaque fois',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Un partenaire qui danse très bien',
          b: 'Un partenaire qui cuisine très bien',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Zéro jalousie pour toujours',
          b: 'Double passion mais jalousie incluse',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Être courtisé par deux personnes',
          b: 'Choisir toi mais sans être courtisé',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Ton nom dans une chanson d\'amour',
          b: 'Ton visage dans une vidéo romantique',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Que des dates au petit-déjeuner',
          b: 'Que des dates à minuit',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Main dans la main en public toujours',
          b: 'Des câlins qu\'en privé mais intenses',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Oublier tous tes ex',
          b: 'Que tous tes ex t\'oublient',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Un baiser de film une fois par an',
          b: 'Des baisers normaux mais quotidiens',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Te déclarer avec une lettre à la main',
          b: 'Te déclarer devant tout le monde',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Savoir le jour où tu tomberas amoureux',
          b: 'Savoir juste le nom mais pas quand',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Partenaire susceptible mais passionné',
          b: 'Partenaire zen mais tiède',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Revivre ton premier amour',
          b: 'Connaître d\'avance le dernier',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Passer pour timide en flirtant',
          b: 'Passer pour effronté alors que non',
          tone: ContentTone.piccante,
        ),
        (
          a: 'La vraie raison de chaque rupture',
          b: 'Ne jamais le savoir mais finir en paix',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Un date parfait organisé par ton ex',
          b: 'Un désastre avec la bonne personne',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Plaire à tous sauf à ton crush',
          b: 'Plaire qu\'à ton crush et à personne',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Messages toujours lus tout de suite',
          b: 'Réponse garantie en une minute',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Retirer un message par jour',
          b: 'Relire les messages supprimés',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Flirt éhonté mais que le mardi',
          b: 'Flirt léger mais tous les jours',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Le groupe choisit ton prochain date',
          b: 'Le groupe lit le chat du dernier',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Être embrassé sans prévenir',
          b: 'Annoncer chaque baiser dix secondes avant',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Un été de célibataire légendaire',
          b: 'Un hiver en couple parfait',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Ton crush voit toutes tes stories',
          b: 'Tu vois tout ce qu\'il regarde',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Un slow avec la mauvaise personne',
          b: 'Plus jamais un seul slow',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Te faire lécher les orteils',
          b: 'Lécher le corps entier de l\'autre',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Un sextape que vous regardez ensemble',
          b: 'Des photos coquines imprimées et cachées',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Te faire dominer par ton/ta partenaire déguisé',
          b: 'Le/la dominer en costume de patron',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Du sexe où tu gardes les yeux fermés',
          b: 'Du sexe où tu ne quittes pas son regard',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Une séance de spanking sur commande',
          b: 'Une séance de cire chaude sur le dos',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Faire l\'amour dans une piscine publique la nuit',
          b: 'Le faire dans un jacuzzi partagé',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Un(e) partenaire qui te murmure des saletés',
          b: 'Un(e) partenaire totalement silencieux',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Te faire attacher les mains au dos',
          b: 'Attacher les jambes de l\'autre écartées',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Une pipe pendant qu\'il/elle conduit',
          b: 'Un doigté sous la table au restaurant',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Un trio avec ton/ta meilleur(e) ami(e)',
          b: 'Un trio avec un couple d\'inconnus',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Te faire prendre en levrette contre le mur',
          b: 'Te faire chevaucher sur le canapé',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Du sexe où tu dois quémander chaque geste',
          b: 'Du sexe où tu contrôles chaque geste',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Te faire mettre un plug pendant le dîner',
          b: 'Mettre des pinces à tétons à l\'autre',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Faire l\'amour au sommet d\'une randonnée',
          b: 'Le faire sur le toit d\'un immeuble',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Une nuit BDSM en tant que soumis',
          b: 'Une nuit BDSM en tant que maître',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Te faire couvrir de morsures légères',
          b: 'Couvrir l\'autre de baisers mouillés',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Un plan cul avec un(e) collègue',
          b: 'Un plan cul avec un(e) ex récent(e)',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Recevoir une double stimulation avec deux jouets',
          b: 'Une pénétration lente et prolongée',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Te faire déguster les yeux bandés',
          b: 'Deviner ce que l\'autre te fait subir',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Un jeu de vérité qui finit tout nus',
          b: 'Un strip-poker qui dégénère',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Te faire prendre sous la douche brûlante',
          b: 'Te faire prendre sur le carrelage froid',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Une soirée où tu portes un collier de soumis',
          b: 'Une soirée où tu tiens la laisse',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Du sexe avec des glaçons sur la peau',
          b: 'Du sexe avec de la cire chaude',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Te faire éventer les fesses en public discret',
          b: 'Te faire pincer les fesses sous la table',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Un massage nu à quatre mains',
          b: 'Un massage nu par un(e) inconnu(e)',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Faire l\'amour dans une bibliothèque déserte',
          b: 'Le faire dans un musée après la fermeture',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Te faire supplier pour jouir',
          b: 'Supplier l\'autre de te laisser jouir',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Un(e) partenaire qui te filme en action',
          b: 'Un(e) partenaire qui te photographie nu(e)',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Une orgie thème années 70',
          b: 'Une soirée fétichiste en cuir et latex',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Te faire prendre à quatre pattes',
          b: 'Prendre l\'autre à quatre pattes',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Du sexe brutal contre le lavabo',
          b: 'Du sexe tendre dans un bain moussant',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Te faire mettre une laisse et ramper',
          b: 'Faire ramper ton/ta partenaire vers toi',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Un premier plan à trois cette semaine',
          b: 'Un premier bondage complet ce soir',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Recevoir un lap dance très rapproché',
          b: 'Faire un lap dance sur les genoux de l\'autre',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Te faire teaser sans jamais te toucher',
          b: 'Toucher partout sans satisfaire l\'autre',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Une nuit avec un(e) inconnu(e) rencontré(e) en ligne',
          b: 'Une nuit à trois avec un vieux fantasme',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Te faire prendre en public dans le noir',
          b: 'Te faire prendre à la maison portes ouvertes',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Du sexe où tu portes un masque',
          b: 'Du sexe où l\'autre porte un masque',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Te faire enduire d\'huile chaude partout',
          b: 'Enduire l\'autre et le/la masser longuement',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Un sextoy inséré toute la soirée mondaine',
          b: 'Des menottes cachées sous les manches',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Faire l\'amour au bord d\'une falaise',
          b: 'Le faire dans une tente en camping bondé',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Te faire fouetter légèrement les cuisses',
          b: 'Fouetter légèrement le dos de l\'autre',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Une double pénétration avec un jouet',
          b: 'Une pénétration surprise par derrière',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Te faire commander par SMS toute la journée',
          b: 'Commander l\'autre par SMS toute la journée',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Un jeu de rôle cambrioleur et propriétaire',
          b: 'Un jeu de rôle patron sévère et employé',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Te faire lécher jusqu\'à trois orgasmes',
          b: 'Un seul orgasme mais dévastateur',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Du sexe où tu gardes tes talons hauts',
          b: 'Du sexe où tu gardes ton uniforme',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Te faire attacher au dossier d\'une chaise',
          b: 'Attacher l\'autre au montant du lit',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Une pipe surprise sous le bureau',
          b: 'Un doigté surprise dans le taxi',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Un trio filmé pour vous deux seulement',
          b: 'Un trio spontané jamais reparlé après',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Te faire prendre pendant que tu télétravailles',
          b: 'Te faire prendre juste avant de sortir',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Du sexe avec des mots sales à l\'oreille',
          b: 'Du sexe avec des ordres murmurés',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Te faire poser des pinces à tétons',
          b: 'Poser des pinces sur ton/ta partenaire',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Faire l\'amour dans une grange à la campagne',
          b: 'Le faire sur la plage à minuit',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Une nuit où tu es totalement soumis(e)',
          b: 'Une nuit où tu domines sans limite',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Te faire couvrir de suçons cachés',
          b: 'Couvrir l\'autre de suçons visibles',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Un plan cul avec un(e) voisin(e) sexy',
          b: 'Un plan cul avec un(e) inconnu(e) en boîte',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Recevoir un édging pendant une heure',
          b: 'Un orgasme multiple sans pause',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Te faire bander les yeux et deviner les jouets',
          b: 'Bander les yeux de l\'autre et le/la surprendre',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Une soirée nue à jouer à des jeux coquins',
          b: 'Une soirée à réaliser des gages sexy',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Te faire prendre sur la machine à laver',
          b: 'Te faire prendre sur le plan de travail',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Du sexe où tu dois rester immobile',
          b: 'Du sexe où tu te déchaînes',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Te faire mettre un bâillon-boule',
          b: 'Bâillonner ton/ta partenaire au lit',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Un premier club échangiste ce week-end',
          b: 'Un premier donjon BDSM ce week-end',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Recevoir un massage du périnée',
          b: 'Donner un massage prostatique',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Te faire teaser au bord de l\'orgasme dix fois',
          b: 'Jouir sans qu\'on te laisse récupérer',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Une nuit avec deux inconnu(e)s d\'un soir',
          b: 'Une nuit à te faire regarder par un couple',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Te faire prendre en cuissarde et corset',
          b: 'Te faire prendre en simple chemise ouverte',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Du sexe où tu portes un bandeau et un collier',
          b: 'Du sexe où tu tiens la cravache',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Te faire suspendre dans un harnais',
          b: 'Suspendre l\'autre dans une balançoire coquine',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Une fellation en levrette simultanée à trois',
          b: 'Un cunnilingus pendant qu\'on te caresse',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Te faire dicter chaque geste au lit',
          b: 'Dicter chaque geste de ton/ta partenaire',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Un jeu de rôle masseur et cliente',
          b: 'Un jeu de rôle auto-stoppeur et conducteur',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Te faire prendre trois fois avant midi',
          b: 'Te faire teaser trois jours sans final',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Te faire prendre en pleine sieste',
          b: 'Te faire réveiller par un gode-ceinture',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Une nuit entière menotté au radiateur',
          b: 'Une nuit entière à mener la danse',
          tone: ContentTone.cattivo,
        ),
      ];
}
