import '../content_tone.dart';

/// Coppie di "Preferisci" in spagnolo: parità completa col mazzo italiano.
class PreferisciPoolEs {
  const PreferisciPoolEs._();

  static const List<({String a, String b})> pairs = <({String a, String b})>[
    (a: 'Saber cómo morirás', b: 'Saber cuándo'),
    (a: 'Una verdad incómoda', b: 'Una mentira cómoda'),
    (a: 'Más dinero', b: 'Más tiempo libre'),
    (a: 'Ser famoso', b: 'Ser invisible para la gente'),
    (a: 'Viajar al pasado', b: 'Viajar al futuro'),
    (a: 'Saber volar', b: 'Ser invisible'),
    (a: 'Leer la mente', b: 'Predecir el futuro'),
    (a: 'Nunca más redes sociales', b: 'Nunca más películas'),
    (a: 'Perder el móvil', b: 'Perder las llaves de casa'),
    (a: 'Siempre 5 minutos antes', b: 'Siempre 10 minutos tarde'),
    (a: 'Jefe simpático pero inútil', b: 'Jefe borde pero brillante'),
    (a: 'Sueldo alto y trabajo aburrido', b: 'Sueldo bajo y trabajo que amas'),
    (a: 'Boda con 200 invitados', b: 'Boda de dos'),
    (a: 'Una semana sin salir', b: 'Salir todas las noches'),
    (a: 'Dormir 10 horas', b: 'Dormir 5 y estar genial'),
    (a: 'Repetir las vacaciones perfectas', b: 'Probar un sitio nuevo'),
    (a: 'Mirar la cuenta cada día', b: 'No mirarla nunca'),
    (a: 'Superpoder inútil pero divertido', b: 'Superpoder útil pero aburrido'),
    (a: 'Releer siempre el mismo libro', b: 'No acabar ninguno nunca'),
    (a: 'Vida sin música', b: 'Vida sin cine'),
    (a: 'Saber siempre la verdad', b: 'Vivir feliz en la ilusión'),
    (a: 'Un año sabático', b: 'Jubilarte un año antes'),
    (a: 'Hablar todos los idiomas', b: 'Tocar todos los instrumentos'),
    (a: 'No sentir nunca vergüenza', b: 'No sentir nunca miedo'),
    (a: 'Revivir tu mejor día', b: 'Borrar el peor'),
    (a: 'Vivir juntos al mes', b: 'Vivir juntos tras años'),
    (a: 'Hijos pronto', b: 'Hijos tarde'),
    (a: 'Viaje planeado al detalle', b: 'Salir a la aventura'),
    (a: 'Una temporada en una noche', b: 'Un episodio por semana'),
    (a: 'Batería siempre al 1%', b: 'Internet lentísimo'),
    (a: 'Ropa siempre algo mojada', b: 'Piedra en el zapato para siempre'),
    (a: 'Decir siempre lo que piensas', b: 'No poder hablar nunca más'),
    (a: 'Sin calefacción en invierno', b: 'Sin aire en verano'),
    (a: 'Hipo de por vida', b: 'Estornudar cada dos minutos'),
    (a: 'Tu plato favorito en cada comida', b: 'Nunca más tu plato favorito'),
    (a: 'No necesitar dormir nunca', b: 'No necesitar comer nunca'),
    (a: 'Rico pero sin amigos', b: 'Sin blanca pero muy querido'),
    (a: 'Nunca más alquiler', b: 'Sueldo el doble'),
    (a: 'El más simpático de la sala', b: 'El más listo de la sala'),
    (a: 'Memoria fotográfica', b: 'Olvidar cada ridículo'),
    (a: 'Nunca más colas', b: 'Nunca más atascos'),
    (a: 'Cejas rapadas un año', b: 'Pelo verde flúor un año'),
    (a: 'Perder el olfato', b: 'Perder el gusto'),
    (a: 'Voz de dibujo animado', b: 'Risa que avergüenza a todos'),
    (a: 'Historial visible para tus padres', b: 'Chats leídos por tu jefe'),
    (a: 'Eructar al final de cada frase', b: 'Reírte como una cabra'),
    (a: 'Usar el cepillo de un desconocido', b: 'Beber de su vaso ya usado'),
    (a: 'Manos siempre sudadas', b: 'Labios siempre agrietados'),
    (a: 'Salir con tu ex', b: 'Con el ex de tu mejor amigo'),
    (a: 'Pedos ruidosos pero sin olor', b: 'Silenciosos pero mortales'),
    (a: 'Olvidar quién eres', b: 'Que todos te olviden'),
    (a: 'Perder todo tu dinero', b: 'Perder todos tus recuerdos'),
    (a: 'Pareja rica pero aburrida', b: 'Pareja pobre pero divertida'),
    (
      a: 'Una hora en el ascensor con tu ex',
      b: 'Una hora en el ascensor con tu jefe',
    ),
    (a: 'Cumpleaños olvidado por todos', b: 'Fiesta sorpresa incómoda'),
    (a: 'Tu secreto contado a todos', b: 'Saber los secretos de todos'),
    (a: 'Famoso pero odiado', b: 'Anónimo pero querido'),
    (a: 'No volver a reír', b: 'No volver a llorar'),
    (a: 'Volver al instituto un año', b: 'Repetir la selectividad cada año'),
    (a: 'Vivir en una peli de terror', b: 'Vivir en un musical'),
    (a: 'Pies en lugar de manos', b: 'Manos en lugar de pies'),
    (
      a: 'Un pato del tamaño de un caballo',
      b: 'Cien caballos del tamaño de un pato',
    ),
    (a: 'Vivir bajo el agua', b: 'Vivir en el espacio'),
    (
      a: 'Perseguido por un caracol asesino',
      b: 'Un payaso que te mira cada noche',
    ),
    (a: 'Hablar con los animales', b: 'Controlar el tiempo'),
    (a: 'Bailar en cuanto suena la música', b: 'Llorar cuando alguien se ríe'),
    (a: 'Cada mañana en un país distinto', b: 'No salir nunca de tu ciudad'),
    (a: 'Vivir en un videojuego', b: 'Vivir en un dibujo animado'),
    (a: 'Botón de pausa para la vida', b: 'Botón de rebobinar para la vida'),
    (a: 'Teletransporte sin zapatos', b: 'Volar a paso de tortuga'),
    (a: 'Vivir 1000 años', b: 'Diez vidas de 100 años'),
    (a: 'Lluvia de tacos', b: 'Nieve de helado'),
    (a: 'Rey del mundo un día', b: 'Persona normal para siempre'),
    (a: 'Saberlo todo sin sentir nada', b: 'Sentir todo sin entender nada'),
    (a: 'Borrar un arrepentimiento', b: 'Garantizarte un éxito futuro'),
    (a: 'Siempre con hambre', b: 'Siempre con sueño'),
    (
      a: 'Cola que se mueve si eres feliz',
      b: 'Orejas que caen si estás triste',
    ),
    (a: 'Renunciar al café para siempre', b: 'Renunciar al chocolate'),
    (a: 'Nariz que crece al mentir', b: 'Pelo que cambia con el ánimo'),
    (
      a: 'Encontrar el amor de tu vida',
      b: 'Encontrar el trabajo de tus sueños',
    ),
    (a: 'Riquísimo pero siempre triste', b: 'Sin un euro pero feliz'),
    (a: 'Un millón ahora', b: '3.000 euros al mes de por vida'),
    (a: 'Salvar a tu perro', b: 'Salvar a un desconocido'),
    (a: 'No poder mentir nunca', b: 'Creerte cualquier mentira'),
    (a: 'Tener razón siempre pero solo', b: 'Equivocarte pero acompañado'),
    (a: 'Genio incomprendido', b: 'Simplón feliz'),
    (a: 'El mismo look cada día', b: 'No repetir look nunca'),
    (a: 'Cantar todo lo que dices', b: 'Andar solo hacia atrás'),
    (a: 'Wifi gratis en todas partes', b: 'Vuelos gratis de por vida'),
    (a: 'Comer solo comida hirviendo', b: 'Solo comida helada'),
    (a: 'Nunca más pizza', b: 'Nunca más pasta'),
    (a: 'Nunca más cañas', b: 'Nunca más comida a domicilio'),
    (a: 'Vida larga llena de reproches', b: 'Vida corta sin arrepentimientos'),
    (a: 'Amar sin ser correspondido', b: 'Que te ame quien no amas'),
    (a: 'Tu pareja te lee la mente', b: 'Tú le lees la mente'),
    (a: 'Pareja elegida por tus amigos', b: 'Pareja elegida por un algoritmo'),
    (a: 'Saber siempre quién te miente', b: 'Que nunca te pillen mintiendo'),
    (a: 'Revivir tus 18 años para siempre', b: 'Saltar directo a los 40'),
    (a: 'Dormir siempre en casa ajena', b: 'Tener siempre invitados en casa'),
    (
      a: 'Tu grupo favorito pero tú solo',
      b: 'Festival con amigos y música que odias',
    ),
    (
      a: 'Karaoke desafinando ante todos',
      b: 'Bailar solo en la pista una hora',
    ),
    (a: 'Perder todas las fotos del móvil', b: 'Perder todos los chats'),
    (a: 'Estornudar confeti', b: 'Eructar pompas de jabón'),
    (a: 'Tener cuatro brazos', b: 'Tener cuatro piernas'),
    (a: 'Medir dos veinte', b: 'Medir uno veinte'),
    (a: 'Vivir sin verano', b: 'Vivir sin invierno'),
    (a: 'Salvar a cinco desconocidos', b: 'Salvar a tu mejor amigo'),
    (a: 'Un millón y nunca más móvil', b: 'Cero dinero pero con móvil'),
    (
      a: 'Trabajo ideal en el extranjero',
      b: 'Trabajo aburrido cerca de amigos',
    ),
    (a: 'Tener 25 años para siempre', b: 'Envejecer con tus amigos'),
    (a: 'Casa ideal en medio de la nada', b: 'Estudio en pleno centro'),
    (
      a: 'Saber qué dicen de ti a tus espaldas',
      b: 'Vivir tranquilo sin saberlo',
    ),
    (a: 'Cada comida hecha por un chef', b: 'Chófer personal de por vida'),
    (
      a: 'Narrar en voz alta todo lo que haces',
      b: 'Oír la voz narradora de tu vida',
    ),
    (a: 'Pisar Legos cada mañana', b: 'Ducha helada cada mañana'),
    (a: 'Un mosquito cada noche', b: 'Una mosca en cada plato'),
    (a: 'Autocorrector loco de por vida', b: 'Nunca más emojis'),
    (
      a: 'Llamadas solo en manos libres',
      b: 'Pantalla siempre visible para todos',
    ),
    (a: 'Tu perro habla pero te critica', b: 'Tu espejo te halaga en falso'),
    (a: 'Un millón solo para ti', b: 'Cien mil por cabeza para el grupo'),
    (a: 'Que siempre te infravaloren', b: 'Que siempre te sobrevaloren'),
    (a: 'Redescubrir tu serie favorita', b: 'Ver antes cada final'),
    (a: 'Hablar solo a gritos', b: 'Hablar solo susurrando'),
    (a: 'Reírte siempre en momentos serios', b: 'Llorar con cada comedia'),
    (a: 'Comer siempre con las manos', b: 'Comer todo con cucharilla'),
    (a: 'Tus sueños proyectados a tus amigos', b: 'Tus amigos leen tu diario'),
    (a: 'El único soltero del grupo', b: 'El primero del grupo en casarte'),
    (a: 'Nacer en los 80', b: 'Nacer en 2050'),
    (a: 'Restaurantes gratis pero solo', b: 'Pagar siempre pero acompañado'),
    (a: 'Viral por un ridículo épico', b: 'Nunca más de 10 likes'),
    (a: 'Beber solo agua para siempre', b: 'Nunca más agua, solo refrescos'),
    (a: 'Un solo género musical de por vida', b: 'Una sola app en el móvil'),
    (a: 'De esmoquin en la playa', b: 'En bañador en una boda'),
    (a: 'Cocinar como un chef con estrella', b: 'Casa que se limpia sola'),
    (a: 'Vuelo largo junto a un charlatán', b: 'Vuelo largo junto a un bebé'),
    (a: 'Desayuno salado para siempre', b: 'Cena dulce para siempre'),
    (a: 'Vivir sin espejos', b: 'Vivir sin relojes'),
    (a: 'Revivir el mismo lunes', b: 'Saltarte todos los viernes'),
    (a: 'Hablar con las plantas', b: 'Entender a los bebés'),
    (a: 'Ganar siempre a las cartas', b: 'Encontrar siempre aparcamiento'),
    (a: 'Verano de 40 grados sin playa', b: 'Invierno helado sin nieve'),
    (a: 'Solo pelis mal dobladas', b: 'Solo pelis con subtítulos desfasados'),
    (a: 'Café gratis de por vida', b: 'Helado gratis de por vida'),
    (a: 'Mudarte cada año', b: 'La misma casa para siempre'),
    (a: 'Tono de móvil vergonzoso siempre', b: 'Fondo de pantalla vergonzoso'),
    (a: 'Ser un meme famoso', b: 'Tener un doble famoso'),
    (
      a: 'Bailar la macarena al saludar',
      b: 'Saludar a todos con una reverencia',
    ),
    (a: 'Nocilla sin pan', b: 'Pan sin Nocilla'),
    (a: 'Fin de semana infinito con lluvia', b: 'Solo lunes pero siempre sol'),
    (a: 'Un solo plato pero perfecto', b: 'Cocinarlo todo regular'),
    (a: 'Viaje a Marte sin retorno', b: 'No salir nunca más de España'),
    (a: 'Dormir cada noche en una tienda', b: 'Dormir cada noche en el sofá'),
    (a: 'Un mayordomo robot', b: 'Un cocinero robot'),
    (a: 'Nunca más ascensores', b: 'Nunca más escaleras mecánicas'),
    (a: 'Saber todo el gossip de Hollywood', b: 'Saber el final de cada serie'),
    (a: 'Solo comida picante un año', b: 'Nunca más sal'),
    (a: 'Vivir sin música', b: 'Vivir sin pelis'),
    (a: 'Siempre cinco minutos tarde', b: 'Siempre una hora antes'),
    (
      a: 'Bailar genial una sola canción',
      b: 'Bailar regular cualquier canción',
    ),
    (a: 'Verano eterno', b: 'Invierno eterno'),
    (a: 'Nunca más frituras', b: 'Nunca más dulces'),
    (a: 'Leer la mente de los perros', b: 'Hablar con los gatos'),
    (
      a: 'Acertar siempre la cola rápida',
      b: 'Acertar siempre el ascensor bueno',
    ),
    (a: 'Casa en la montaña', b: 'Casa en la playa'),
    (a: 'Revivir el mismo día perfecto', b: 'Un día nuevo e imprevisible'),
    (a: 'Wifi lento para siempre', b: 'Batería siempre al diez por ciento'),
    (a: 'Ser invisible una hora al día', b: 'Volar diez minutos al día'),
    (a: 'Solo duchas frías', b: 'Solo trenes de cercanías'),
    (
      a: 'Cocinar para diez cada noche',
      b: 'Lavar los platos de diez cada noche',
    ),
    (
      a: 'Mochila pesada pero completa',
      b: 'Mochila ligera sin lo que necesitas',
    ),
    (
      a: 'Fotos malas y recuerdos perfectos',
      b: 'Fotos perfectas y recuerdos borrosos',
    ),
    (
      a: 'Un karaoke obligatorio por semana',
      b: 'Un discurso en público al mes',
    ),
    (a: 'Un mayordomo humano incómodo', b: 'Un robot que te juzga en silencio'),
  ];

  /// Dilemmi da modalità Hot: parità completa col mazzo italiano.
  static const List<({String a, String b, String tone})> hot =
      <({String a, String b, String tone})>[
        (
          a: 'Salir desnudo un minuto',
          b: 'Besar a alguien de este grupo',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Pasar la noche con alguien del grupo',
          b: 'Una noche con un profe del insti',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Mostrar tu galería al grupo',
          b: 'Que lean tus chats en voz alta',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Un año sin sexo',
          b: 'Un año sin salir de noche',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Decir tu body count al grupo',
          b: 'Mostrar tu última búsqueda',
          tone: ContentTone.piccante,
        ),
        (a: 'Amor sin sexo', b: 'Sexo sin amor', tone: ContentTone.piccante),
        (
          a: 'Pareja guapa pero mala en la cama',
          b: 'Pareja normal pero espectacular',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Una noche con tu ex',
          b: 'Una noche con un desconocido',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Pillar a tus padres',
          b: 'Que te pillen tus padres',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Decir a todos quién te gusta',
          b: 'No hablarle nunca más',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Besar a uno del grupo con los ojos cerrados',
          b: 'Besar a tu ex delante de todos',
          tone: ContentTone.piccante,
        ),
        (
          a: 'No poder besar más',
          b: 'No poder abrazar más',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Saber con quién te engañaría tu pareja',
          b: 'No saberlo nunca',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Solo citas a ciegas un año',
          b: 'Solo citas elegidas por tu madre',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Ver en vídeo tu primer beso',
          b: 'Que lo vea todo el grupo',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Gemir cada vez que te sientas',
          b: 'Gritar el nombre de tu ex al brindar',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Mandar un desnudo a tu ex sin querer',
          b: 'Mandarlo al grupo de la familia',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Sexting con tu jefe por error',
          b: 'Llamar a tu pareja como a tu ex',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Una noche con un famoso',
          b: 'Un mes de sexo con tu ex',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Sexo solo a oscuras totales',
          b: 'Solo con la luz siempre encendida',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Decir tu fantasía más rara',
          b: 'Oír la del que tienes a la derecha',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Amigos de cama con tu mejor amigo',
          b: 'Nunca más sexo durante un año',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Un ex que besa de maravilla',
          b: 'Uno nuevo al que enseñar todo',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Que te desnuden con la mirada en el bar',
          b: 'No volver a llamar la atención',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Contar tu peor cita',
          b: 'Revivir tu ridículo más caliente',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Dar tú siempre el primer paso',
          b: 'Esperar siempre al otro',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Un trío con desconocidos',
          b: 'Un trío con amigos',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Pillar a tu compañero de piso',
          b: 'Que él te pille a ti',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Decir cuántas veces lo piensas al día',
          b: 'Decir cuándo fue la última vez',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Pareja celosísima pero ardiente',
          b: 'Pareja tranquila pero perezosa',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Besar al primero que entre por la puerta',
          b: 'Besar al último que te escribió',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Noche de pasión sin besos',
          b: 'Besos infinitos y nada más',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Olvidar tu primera vez',
          b: 'Recordarla cada día',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Decir el sitio más absurdo donde lo hiciste',
          b: 'Decir dónde te gustaría hacerlo',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Un flirteo con tu entrenador',
          b: 'Un flirteo con tu médico',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Solo rollos de una noche un año',
          b: 'Solo relaciones serias de por vida',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Volver con tu ex de vez en cuando',
          b: 'Cerrar para siempre con pena',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Un morreo con quien tienes a la izquierda',
          b: 'Un lento sensual con quien está a tu derecha',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Dormir desnudo con un amigo',
          b: 'Ducharte en bañador con tu ex',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Recibir un desnudo de tu jefe',
          b: 'Mandarle uno sin querer',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Sexo de escándalo una vez al mes',
          b: 'Sexo mediocre cada día',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Saber qué piensa el otro en la cama',
          b: 'Que oiga cada pensamiento tuyo',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Un finde con tu amor secreto',
          b: 'Un mes con tu primer amor',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Desayuno en la cama tras la primera noche',
          b: 'Desaparecer antes del amanecer',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Decir tu punto débil en la cama',
          b: 'Imitarlo delante del grupo',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Tatuarte el nombre de tu ex',
          b: 'Gritarlo en el peor momento',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Match con tu ex en una app',
          b: 'Match con tu jefe en una app',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Tu pareja sabe todas tus fantasías',
          b: 'Tú sabes todas las suyas',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Striptease improvisado ahora',
          b: 'Relato picante de tu verano',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Besar a uno del grupo a tu elección',
          b: 'Besar al que elija el grupo',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Historia secreta muy pasional',
          b: 'Historia oficial pero tibia',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Sexo solo en verano',
          b: 'Sexo solo en invierno',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Olvidar todas tus noches locas',
          b: 'Recordar también las peores',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Audio caliente a quien no debías',
          b: 'Recibir uno de tu jefe',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Que lean tus mensajes con tu ex',
          b: 'Que vean tus fotos con tu ex',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Amor a primera vista esta noche',
          b: 'Aventura de una noche hoy',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Decir el nombre de tu crush al grupo',
          b: 'Que el grupo lo adivine',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Un lento con tu ex esta noche',
          b: 'Karaoke romántico con uno del grupo',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Tirarle la caña a un desconocido ya',
          b: 'Dar tu número al primero que lo pida',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Un masaje de alguien del grupo',
          b: 'Hacérselo tú a alguien del grupo',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Prohibido flirtear un año',
          b: 'Obligado a flirtear con todos',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Una noche con tu ídolo musical',
          b: 'Un finde con tu actor favorito',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Confesar un sueño caliente con un presente',
          b: 'Que un presente lo confiese de ti',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Silencio total en la cama',
          b: 'Narración completa en la cama',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Un culo de escándalo',
          b: 'Un escote de aplauso',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Tu ex se vuelve famosísimo',
          b: 'Tu ex se vuelve tu jefe',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Decir qué te excita más',
          b: 'Decir qué te corta el rollo',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Un lío de verano nunca confesado',
          b: 'Un amor a distancia infinito',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Dos presentes te tiran la caña',
          b: 'Tirársela tú a dos a la vez',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Ver a tu ex con alguien mejor que tú',
          b: 'Que te vea con alguien peor',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Besos con mordisco',
          b: 'Besos de piquito para siempre',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Dormir abrazados sin sexo',
          b: 'Sexo sin dormir juntos nunca',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Sexo con la música a todo volumen',
          b: 'Con el telediario de fondo',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Revelar tu número de ex',
          b: 'Revelar quién fue el mejor',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Tirarle la caña al camarero hoy',
          b: 'Dejarle tu número en el recibo',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Primera vez torpe pero dulce',
          b: 'Perfecta pero con quien no debías',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Un tatuaje donde decida el grupo',
          b: 'Un piercing donde decida el grupo',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Un beso de 30 segundos con un presente',
          b: 'Diez besos rápidos con diez extraños',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Saber quién del grupo sueña contigo',
          b: 'Saber quién no te besaría nunca',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Sexo en tienda en un camping lleno',
          b: 'En un hotel de paredes de papel',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Vacaciones solo para solteros',
          b: 'Vacaciones solo para parejas',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Engañar sin ser descubierto nunca',
          b: 'Que te engañen y no saberlo',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Un lío con la pareja de un amigo',
          b: 'Tu pareja con tu mejor amigo',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Que salgan tus peores fotos',
          b: 'Que salgan tus peores chats',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Oír qué dice el grupo de ti',
          b: 'Que el grupo oiga qué dices tú',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Confesar tu peor secreto ahora',
          b: 'Que lo revele tu mejor amigo',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Sexo con el ex de tu mejor amigo',
          b: 'Decirle que ya lo pensaste',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Saberlo todo de los presentes',
          b: 'Que ellos lo sepan todo de ti',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Un ex que siempre vuelve',
          b: 'No saber nunca más de tus ex',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Ser pareja fija de uno del grupo',
          b: 'No poder ver más al grupo',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Descubrir una infidelidad pasada',
          b: 'Confesar una tuya ahora',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Leer el diario secreto de tu pareja',
          b: 'Que lea todos tus chats',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Saber quién del grupo habla mal de ti',
          b: 'Saber quién te ha mentido más',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Un ex que aparece en tu primera cita',
          b: 'Una pareja que siempre nombra al ex',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Engañar en un sueño y confesarlo',
          b: 'Soñar con tu ex cada noche y callar',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Saber el body count real de tu pareja',
          b: 'Que descubra el tuyo real',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Besar al ex de tu mejor amigo',
          b: 'Que él bese a tu ex',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Una noche con la pareja de un colega',
          b: 'Que todos crean que lo hiciste',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Descubrir que tu ex te engañaba',
          b: 'Descubrir que siempre te quiso',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Vengarte de un ex y arrepentirte',
          b: 'Perdonarlo y arrepentirte más',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'El grupo lee tu último chat caliente',
          b: 'El grupo ve tus fotos privadas',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Confesar a quién hiciste ghosting',
          b: 'Llamar ya a quien te lo hizo',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Que te dejen con un audio',
          b: 'Dejar a alguien en su cumpleaños',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Robarle la pareja a alguien',
          b: 'Que te la roben y recuperarla',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Saber cada mentira de tu pareja',
          b: 'Que sepa cada mentira tuya',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Contar al grupo tu peor traición',
          b: 'Contar el peor secreto de un amigo',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Flirtear con la pareja de tu jefe',
          b: 'Que tu jefe flirtee con la tuya',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Un amigo que va a por tu pareja',
          b: 'Tu pareja que va a por tu amigo',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Hallar un regalo del ex en su casa',
          b: 'Hallar chats con el ex en su móvil',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Borrar para siempre un secreto tuyo',
          b: 'Descubrir lo que te esconden',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Decir con quién del grupo no saldrías',
          b: 'Oír quién no saldría contigo',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Un ex al que aún debes dinero',
          b: 'Un ex que te debe una disculpa',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Admitir que stalkeaste a tu ex',
          b: 'Mostrar el historial de sus perfiles',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Sexo a escondidas donde tus suegros',
          b: 'Que te pillen en el peor momento',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Tu mejor amigo te odia',
          b: 'Tu amigo ama a tu pareja',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Infidelidad de una noche confesada',
          b: 'Doble vida nunca descubierta',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Responder desnudo a tres preguntas',
          b: 'Responder vestido a treinta',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Saber la fecha del fin de tu pareja',
          b: 'Saber el motivo pero no la fecha',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Un rival en el amor más guapo',
          b: 'Un rival más simpático',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Decir ya si tu pareja besa mal',
          b: 'Casarte sin decírselo nunca',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'El ex que te escribe a las 3',
          b: 'Escribirle tú y negarlo siempre',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Pareja amiga de todos sus ex',
          b: 'Pareja que te prohíbe ver a los tuyos',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Descubrir un perfil secreto suyo',
          b: 'Que encuentre el tuyo',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Amar a dos personas a la vez',
          b: 'Ser el amante y no saberlo',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Decir quién besa peor aquí',
          b: 'Que cada presente te puntúe',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Sabotear la boda de tu ex',
          b: 'Ser testigo en su boda',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Una lista pública de tus flirteos',
          b: 'Una lista de quién te rechazó',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Perder al amigo por decirle la verdad',
          b: 'Conservarlo mintiéndole siempre',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Tu enemigo sabe tu secreto',
          b: 'Tu suegra lo sabe todo de ti',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Intercambiar pareja una semana',
          b: 'Vivir soltero un año',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'El grupo vota tu peor defecto',
          b: 'Oírles enumerar tus flirteos',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Engañar y confesarlo diez años después',
          b: 'Descubrirlo diez años después',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Un finde con tus suegros',
          b: 'Un finde con el ex de tu pareja',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Saber cuántos te dijeron que no',
          b: 'Saber quién se arrepintió del sí',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Contarlo todo de un amor secreto',
          b: 'Que el grupo investigue una hora',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Leer en voz alta tu último mensaje',
          b: 'Llamar al último número marcado',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Romper una pareja diciendo la verdad',
          b: 'Salvarla con una mentira enorme',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Tu ex habla de ti en un podcast',
          b: 'El grupo cuenta tus peores noches',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Ser el plan B de alguien',
          b: 'Tener un plan B y que te pillen',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Tu pareja revisa tu móvil',
          b: 'No poder mirar nunca el suyo',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Decir tu última mentira a un presente',
          b: 'Que cada presente diga una de ti',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Salir con el gemelo de tu ex',
          b: 'Con alguien idéntico a tu jefe',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Saber qué dicen tus ex de ti',
          b: 'Reunirlos todos en una cena',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Engañar por venganza y decirlo',
          b: 'Aguantar y tramar en silencio',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Besar a alguien por una apuesta',
          b: 'Saber que fuiste una apuesta',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Boda de urgencia en un mes',
          b: 'Diez años de novios sin boda',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Espiar la noche de tu ex por redes',
          b: 'Bloquearlo y morir de curiosidad',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Confesar el flirteo más cutre',
          b: 'Que lo cuente quien estaba allí',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'El grupo sabe quién te gusta aquí',
          b: 'Lo sabe solo quien no debía',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Descubrir la doble vida de tu pareja',
          b: 'Lograr esconder la tuya',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Romper una pareja de amigos hablando',
          b: 'Verlos infelices y callarte',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'El grupo elige tu pareja',
          b: 'El grupo elige a quién dejas',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Decir el motivo real de tu último adiós',
          b: 'Oír la versión de tu ex',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Una noche con dos ex a la vez',
          b: 'Una noche con tu ex y su nuevo amor',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Ser celoso y tener razón',
          b: 'Confiar y que te engañen',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Un beso perfecto al mes',
          b: 'Besos mediocres cada día',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Saber qué piensa tu crush de ti',
          b: 'Que sepa todo lo que piensas tú',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Una noche inolvidable sin más',
          b: 'Diez citas monas sin chispa',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Dormir abrazados y nada más',
          b: 'Todo lo demás pero sin mimos',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Decirle tu body count a tu crush',
          b: 'Mostrar tu último chat con tu ligue',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Pareja que besa de maravilla',
          b: 'Pareja que escribe de maravilla',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Flirtear delante de tus padres',
          b: 'Flirtear delante de tu ex',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Recibir una foto atrevida por error',
          b: 'Mandarla tú a quien no debías',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Que te seduzcan con palabras',
          b: 'Que te seduzcan con la mirada',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Finde de pasión sin móvil',
          b: 'Semana de flirteo solo por chat',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Primer beso en la primera cita',
          b: 'Primer beso tras un mes de espera',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Saber siempre quién te mira en un bar',
          b: 'No saberlo pero que te miren mucho',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Un ex que te escribe cada noche',
          b: 'Un crush que nunca te escribe',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Un lento con tu crush ante todos',
          b: 'Cena romántica en silencio total',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Que el grupo lea tu chat con tu crush',
          b: 'Llamarla ahora en manos libres',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Un masaje perfecto cada noche',
          b: 'Desayuno en la cama cada mañana',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Ser el mejor beso de alguien',
          b: 'Recibir el mejor beso de tu vida',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Nunca más primeras citas',
          b: 'Solo primeras citas para siempre',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Decir "me gustas" siempre primero',
          b: 'Esperar siempre a que lo digan',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Una playlist que suena si flirteas',
          b: 'Una voz que narra tus citas',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Tu ex en tu boda',
          b: 'Tu suegra en tu luna de miel',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Volver a ver en vídeo tu primer beso',
          b: 'Mostrar al grupo tu perfil de citas',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Congelarte con cada "tenemos que hablar"',
          b: 'No oírlo nunca en la vida',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Un flirteo de verano cada año',
          b: 'Un amor de verdad cada diez años',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Saber cuántas veces hablaron de ti',
          b: 'Saber qué dijeron pero no quién',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Besos solo bajo la lluvia',
          b: 'Besos solo en el ascensor',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Un "buenos días" de quien te importa',
          b: 'Un "buenas noches" cada noche',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Perder la voz cuando flirteas',
          b: 'Decir siempre una palabra de más',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Ser irresistible solo de día',
          b: 'Ser irresistible solo de noche',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Una cita a ciegas elegida por el grupo',
          b: 'Una cita organizada por tu ex',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Cenar con la pareja de tu crush',
          b: 'Hacerles de chófer toda la noche',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Saber cuándo mienten por amor',
          b: 'No mentir nunca tú primero',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Un año sin besos',
          b: 'Un año sin abrazos',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Confesar tu crush a esa persona',
          b: 'Confesarla a toda esta sala ya',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Ser famoso por una historia de amor',
          b: 'Ser famoso por una calabaza épica',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Salir con alguien idéntico a ti',
          b: 'Salir con tu opuesto exacto',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Tu diario leído por tu crush',
          b: 'Tu historial leído por tus padres',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Un beso robado inolvidable',
          b: 'Cien besos pedidos con permiso',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Parecer siempre desinteresado',
          b: 'Parecer siempre demasiado ansioso',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Amor a primera vista una sola vez',
          b: 'Flechazos que nunca te corresponden',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Flores en la oficina cada semana',
          b: 'Un audio romántico cada noche',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Flirtear genial solo por escrito',
          b: 'Flirtear genial solo en persona',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Un crush por un amigo de este grupo',
          b: 'Un crush por alguien del trabajo',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Saber si la primera cita irá bien',
          b: 'Poder repetir cada primera cita',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Cita romántica planeada al minuto',
          b: 'Improvisación total cada vez',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Una pareja que baila genial',
          b: 'Una pareja que cocina genial',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Cero celos para siempre',
          b: 'Doble pasión pero con celos',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Que dos personas te cortejen',
          b: 'Elegir tú pero sin ser cortejado',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Tu nombre en una canción de amor',
          b: 'Tu cara en un vídeo romántico viral',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Solo citas en el desayuno',
          b: 'Solo citas a medianoche',
          tone: ContentTone.piccante,
        ),
        (
          a: 'De la mano en público siempre',
          b: 'Cariño solo en privado pero intenso',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Olvidar a todos tus ex',
          b: 'Que todos tus ex te olviden',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Un beso de peli una vez al año',
          b: 'Besos normales pero cada día',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Declararte con una carta a mano',
          b: 'Declararte ante todo el mundo',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Saber el día en que te enamorarás',
          b: 'Saber solo el nombre y no cuándo',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Pareja susceptible pero pasional',
          b: 'Pareja zen pero tibia',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Revivir tu primer amor',
          b: 'Conocer de antemano el último',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Pasar por tímido al flirtear',
          b: 'Pasar por descarado siendo tímido',
          tone: ContentTone.piccante,
        ),
        (
          a: 'La verdad de por qué acabó cada amor',
          b: 'No saberlo pero cerrar en paz',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Una cita perfecta organizada por tu ex',
          b: 'Un desastre con la persona ideal',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Gustar a todos menos a tu crush',
          b: 'Gustar solo a tu crush y a nadie más',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Mensajes leídos siempre al momento',
          b: 'Respuesta garantizada en un minuto',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Retirar un mensaje al día',
          b: 'Leer los mensajes borrados por otros',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Flirteo descarado solo los martes',
          b: 'Flirteo suave todos los días',
          tone: ContentTone.piccante,
        ),
        (
          a: 'El grupo elige tu próxima cita',
          b: 'El grupo lee el chat de la última',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Que te bese sin avisar quien te gusta',
          b: 'Anunciar cada beso diez segundos antes',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Un verano de soltero legendario',
          b: 'Un invierno en pareja perfecto',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Tu crush ve todas tus historias',
          b: 'Tú ves todo lo que ella mira',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Un lento con quien no debías',
          b: 'Ningún lento nunca más',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Sexo a oscuras para siempre',
          b: 'Solo con la luz encendida siempre',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Una sola postura de por vida',
          b: 'Todas menos tu favorita',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Decir tu fantasía más fuerte al grupo',
          b: 'Mostrar el historial en incógnito',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Un año de castidad',
          b: 'Un año sin móvil',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Que te oigan los vecinos',
          b: 'Oír a los vecinos cada noche',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Solo sexo por la mañana',
          b: 'Solo de madrugada',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Perfecto en la cama y pésimo hablando',
          b: 'Poeta increíble y desastre en la cama',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Decir todas tus cifras, body count incluido',
          b: 'Dar tu móvil desbloqueado una hora',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Ver tu primera vez en vídeo',
          b: 'Contarla ahora con detalles decentes',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Empezar siempre tú, por contrato',
          b: 'Esperar siempre, incluso meses',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Sexo sin besos nunca',
          b: 'Besos sin nada más nunca',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Una noche con tu peor ex',
          b: 'Seis meses sin nadie',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'El grupo oye tus audios de las tres',
          b: 'El grupo lee tu último sexting',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Que te pillen tus padres en lo peor',
          b: 'Pillarlos tú en lo peor',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Olvidar tus mejores noches',
          b: 'Recordarlas y no poder contarlas',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Probar un fetiche que elija el grupo',
          b: 'Confesar ahora el tuyo',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Solo aventuras de una noche',
          b: 'Solo relaciones serias desde el día uno',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Una historia secreta para siempre',
          b: 'Todo público desde el primer día',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Un amigo de cama que se enamora',
          b: 'Enamorarte tú de tus amigos de cama',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Decir en voz alta quién te atrae aquí',
          b: 'Que el grupo vote a quién atraes',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Tu cajón secreto lo abre tu madre',
          b: 'Lo abre tu jefe',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Sexo solo en tu casa para siempre',
          b: 'Nunca más en tu casa',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Ducha en pareja siempre obligatoria',
          b: 'Nunca más duchas en pareja',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Dormir siempre desnudo en todas partes',
          b: 'Siempre vestido, hasta de luna de miel',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Un tatuaje con el nombre de cada ex',
          b: 'Una lista pública de tus ex online',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Hacer siempre demasiado ruido',
          b: 'Silencio absoluto para siempre',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Tu ex da referencias tuyas a tus citas',
          b: 'Sin referencias pero con sospechas',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Saber cuántas veces fingieron',
          b: 'Vivir tranquilo en la duda',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Sexo de diez una vez al mes',
          b: 'De seis todos los días',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Siempre demasiado rápido',
          b: 'Siempre demasiado largo',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Tu playlist caliente suena en la oficina',
          b: 'Tu mensaje hot leído en familia',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Una noche con tu crush famoso y se sabe',
          b: 'Secreto total y nadie te creerá',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Solo sitios públicos arriesgados',
          b: 'Solo tu cama para siempre',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Confesar el sitio más absurdo',
          b: 'Que el grupo lo adivine preguntando',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Nunca más preliminares',
          b: 'Solo preliminares',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Cada cita acaba en la cama',
          b: 'Ninguna acaba así en la primera',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Saber la nota que te dan tus ex',
          b: 'Dar tú las notas en público',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Un finde sin límites y sin contarlo',
          b: 'Una noche normal contable años',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Tu momento más incómodo contado por otro',
          b: 'Contarlo tú pero entero',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Perder para siempre tu postura favorita',
          b: 'Explicarla ahora al grupo',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Solo sexo agendado',
          b: 'Solo improvisado en el peor momento',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Decir cada vez "ha sido el mejor"',
          b: 'No poder comentar nunca',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Un mes sin tocar a tu pareja',
          b: 'Un mes sin hablarle',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Que se sepa siempre cuándo lo hiciste',
          b: 'Que nadie te crea nunca',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Ropa rota cada vez, y tú pagas',
          b: 'Doblarlo todo antes, con calma',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Tu ex en la habitación de al lado',
          b: 'Tu ex en tu grupo de amigos siempre',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Contar tu sueño erótico más absurdo',
          b: 'Que el grupo elija al protagonista',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Nunca más sexo en vacaciones',
          b: 'Solo sexo en vacaciones',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Perder la cuenta de tus noches',
          b: 'Un contador público siempre al día',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Seducir siempre con la misma frase',
          b: 'No hablar nunca al seducir',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Los vecinos saben si tienes compañía',
          b: 'Tu grupo recibe una notificación',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Desayunar siempre con su familia',
          b: 'Salir siempre por la ventana',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Sexo solo con música trap',
          b: 'Solo con clásica a todo volumen',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Dormir siempre allí, obligatorio',
          b: 'No poder quedarte nunca',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Tu primer pensamiento dicho en voz alta',
          b: 'Tu último pensamiento publicado',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Nunca más besos en el cuello',
          b: 'Solo besos en el cuello',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Buenísimo pero lo olvidas todo',
          b: 'Recuerdas todo pero eres mediocre',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'La verdad sobre cómo fue, siempre',
          b: 'Halagos seguros pero nunca sinceros',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Repetir siempre tu mejor noche',
          b: 'Una noche nueva por sorpresa total',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Sexo solo tras tres citas exactas',
          b: 'Solo en la primera o nunca',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Todos saben tu fetiche',
          b: 'No poder practicarlo nunca más',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Un año soltero con recuerdos vívidos',
          b: 'En pareja pero con amnesia',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Striptease obligatorio en cada fiesta',
          b: 'Nunca más desnudarte con luz',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Decirlo siempre cuando alguien te atrae',
          b: 'No poder insinuarlo nunca',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'El grupo elige con quién flirteas hoy',
          b: 'El grupo observa cómo flirteas',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Nunca más por la mañana',
          b: 'Nunca más de noche',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Solo hoteles por horas',
          b: 'Solo casa de tus padres',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Sexo fantástico solo en verano',
          b: 'Mediocre pero todo el año',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Saber qué piensa de verdad durante',
          b: 'Que sepa cada cosa que piensas',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Tu tipo lo elige el grupo un año',
          b: 'Lo elige tu ex',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Cada cita comentada por el grupo',
          b: 'Siempre solo y sin consejos',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Una noche para contar diez años',
          b: 'Diez noches para olvidar ya',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Tu próxima pareja está en esta sala',
          b: 'No será nunca nadie de aquí',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Confesar lo más fuerte que has hecho',
          b: 'Que lo cuente tu mejor amigo por ti',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Un finde de pasión sin conversación',
          b: 'Un finde de charla perfecta y nada más',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Que cada ex cuente su versión de ti',
          b: 'No poder contar nunca la tuya',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Tragar el esperma cada vez',
          b: 'No recibir nunca más sexo oral',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Tener sexo anal todos los días',
          b: 'No tener sexo nunca más en tu vida',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Ser filmado mientras follas',
          b: 'Hacerlo delante de todo el grupo',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Que todos sepan lo mal que follar',
          b: 'Que sepan cuál es tu fetiche más extremo',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Lamer el ano de tu peor enemigo',
          b: 'Que te lamen el ano un perfecto desconocido',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Venirte en la cara de quien tienes a la derecha',
          b: 'Que se vengan en tu cara quien tienes a la izquierda',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Un trío con dos amigos cercanos',
          b: 'Un trío con dos perfectos desconocidos',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Un año de solo sexo anal',
          b: 'Un año de solo sexo oral',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Que tus padres vean tus mensajes calientes',
          b: 'Que vean un vídeo mientras lo haces',
          tone: ContentTone.cattivo,
        ),
      ];
}
