import '../../../core/i18n/app_locale.dart';
import 'preferisci_pool_intl.dart';

/// Pool gratuito di "Preferisci", una lista per lingua.
///
/// L'indice della coppia finisce dentro `rounds.content['i']`, così l'host sa
/// quali sono già uscite e non le ripesca nella stessa partita.
class PreferisciPool {
  const PreferisciPool._();

  /// Coppie nella lingua scelta dal gruppo.
  static List<({String a, String b})> pairs(AppLocale locale) =>
      switch (locale) {
        AppLocale.it => it,
        AppLocale.en => PreferisciPoolIntl.en,
        AppLocale.es => PreferisciPoolIntl.es,
        AppLocale.fr => PreferisciPoolIntl.fr,
        AppLocale.de => PreferisciPoolIntl.de,
      };

  static const List<({String a, String b})> it = <({String a, String b})>[
    (a: 'Mare', b: 'Montagna'),
    (a: 'Pizza', b: 'Pasta'),
    (a: 'Cane', b: 'Gatto'),
    (a: 'Estate', b: 'Inverno'),
    (a: 'Dolce', b: 'Salato'),
    (a: 'Caffè', b: 'Tè'),
    (a: 'Film al cinema', b: 'Serie TV sul divano'),
    (a: 'Andare a letto presto', b: 'Alzarsi tardi'),
    (a: 'Vivere in città', b: 'Vivere in campagna'),
    (a: 'Aereo', b: 'Treno'),
    (a: 'Cornetto', b: 'Ciambella'),
    (a: 'Netflix', b: 'YouTube'),
    (a: 'Vacanza organizzata nei minimi dettagli', b: 'Partire all\'avventura'),
    (a: 'Colazione dolce', b: 'Colazione salata'),
    (a: 'Sushi', b: 'Hamburger'),
    (a: 'Cioccolato fondente', b: 'Cioccolato al latte'),
    (a: 'Birra', b: 'Vino'),
    (a: 'Palestra', b: 'Correre all\'aperto'),
    (a: 'Musica in cuffia', b: 'Musica a tutto volume'),
    (a: 'Leggere il libro', b: 'Guardare il film'),
    (a: 'Concerto', b: 'Festival'),
    (a: 'Sabato sera fuori', b: 'Sabato sera sul divano'),
    (a: 'Doccia bollente', b: 'Doccia fredda'),
    (a: 'Sveglia alle 6', b: 'Andare a letto alle 3'),
    (a: 'Cucinare', b: 'Farsi consegnare la cena'),
    (a: 'Mobili nuovi', b: 'Mercatino dell\'usato'),
    (a: 'Montagna d\'estate', b: 'Montagna d\'inverno'),
    (a: 'Fare foto', b: 'Fare video'),
    (a: 'Avere un piano', b: 'Improvvisare'),
    (a: 'Posto al finestrino', b: 'Posto al corridoio'),
    (a: 'Pizza margherita', b: 'Pizza con tutto sopra'),
    (a: 'Ananas sulla pizza', b: 'Mai nella vita'),
    (a: 'Ketchup', b: 'Maionese'),
    (a: 'Una stagione tutta in una notte', b: 'Un episodio a settimana'),
    (a: 'Karaoke', b: 'Ballare'),
    (a: 'Spiaggia libera', b: 'Stabilimento con lettino'),
    (a: 'Dormire in tenda', b: 'Dormire in hotel'),
    (a: 'Macchina', b: 'Moto'),
    (a: 'Parlare', b: 'Ascoltare'),
    (a: 'Messaggio vocale', b: 'Messaggio scritto'),
    (a: 'Chiamare', b: 'Scrivere'),
    (a: 'Una verità scomoda', b: 'Una bugia comoda'),
    (a: 'Più soldi', b: 'Più tempo libero'),
    (a: 'Essere famoso', b: 'Essere invisibile alla gente'),
    (a: 'Viaggiare nel passato', b: 'Viaggiare nel futuro'),
    (a: 'Saper volare', b: 'Essere invisibile'),
    (a: 'Leggere nel pensiero', b: 'Prevedere il futuro'),
    (a: 'Vivere in una grande città', b: 'Vivere su un\'isola'),
    (a: 'Mai più social', b: 'Mai più film'),
    (a: 'Perdere il telefono', b: 'Perdere le chiavi di casa'),
    (a: 'Sempre 5 minuti in anticipo', b: 'Sempre 10 minuti in ritardo'),
    (a: 'Lavorare da casa', b: 'Lavorare in ufficio'),
    (a: 'Capo simpatico ma incapace', b: 'Capo antipatico ma bravo'),
    (a: 'Stipendio alto e lavoro noioso', b: 'Stipendio basso e lavoro che ami'),
    (a: 'Svegliarsi da soli', b: 'Sveglia del telefono'),
    (a: 'Estate al mare', b: 'Estate in giro per città'),
    (a: 'Ferragosto in spiaggia', b: 'Ferragosto in casa con l\'aria'),
    (a: 'La tua playlist', b: 'La radio'),
    (a: 'Podcast', b: 'Musica'),
    (a: 'Silenzio assoluto', b: 'Rumore di fondo'),
    (a: 'Scarpe comode', b: 'Scarpe belle'),
    (a: 'Vestirsi eleganti', b: 'Vestirsi comodi'),
    (a: 'Grigliata tra amici', b: 'Cena al ristorante'),
    (a: 'Aperitivo lungo', b: 'Dopocena lungo'),
    (a: 'Colazione al bar', b: 'Colazione a casa'),
    (a: 'Gelato in coppetta', b: 'Gelato in cono'),
    (a: 'Nutella', b: 'Marmellata'),
    (a: 'Carbonara', b: 'Amatriciana'),
    (a: 'Prosciutto cotto', b: 'Prosciutto crudo'),
    (a: 'Tiramisù', b: 'Panna cotta'),
    (a: 'Spritz', b: 'Mojito'),
    (a: 'Acqua frizzante', b: 'Acqua naturale'),
    (a: 'Cena a due', b: 'Serata con tutti gli amici'),
    (a: 'Primo appuntamento al cinema', b: 'Primo appuntamento a cena'),
    (a: 'Convivere dopo un mese', b: 'Convivere dopo anni'),
    (a: 'Matrimonio con 200 invitati', b: 'Matrimonio in due'),
    (a: 'Figli presto', b: 'Figli tardi'),
    (a: 'Regalo utile', b: 'Regalo a sorpresa'),
    (a: 'Compleanno in grande', b: 'Compleanno tranquillo'),
    (a: 'Capodanno in casa', b: 'Capodanno in piazza'),
    (a: 'Natale in famiglia', b: 'Natale in viaggio'),
    (a: 'Una settimana senza uscire', b: 'Uscire tutte le sere'),
    (a: 'Dormire 10 ore', b: 'Dormire 5 ore e stare benissimo'),
    (a: 'Rifare la vacanza perfetta', b: 'Provare un posto nuovo'),
    (a: 'Zaino in spalla', b: 'Valigia con le rotelle'),
    (a: 'Ombrellone', b: 'Telo sulla sabbia'),
    (a: 'Sole', b: 'Pioggia'),
    (a: 'Neve', b: 'Vento'),
    (a: 'Alba', b: 'Tramonto'),
    (a: 'Camminata in montagna', b: 'Giornata alle terme'),
    (a: 'Tatuaggio', b: 'Piercing'),
    (a: 'Sempre lo stesso taglio', b: 'Cambiare look ogni mese'),
    (a: 'Selfie', b: 'Foto scattata da altri'),
    (a: 'Storie', b: 'Post'),
    (a: 'Profilo pubblico', b: 'Profilo privato'),
    (a: 'Rispondere subito', b: 'Rispondere quando ti va'),
    (a: 'Gruppo di amici rumoroso', b: 'Gruppo di amici tranquillo'),
    (a: 'Gli amici di sempre', b: 'Conoscere gente nuova'),
    (a: 'Festa in casa', b: 'Discoteca'),
    (a: 'Guardare lo sport', b: 'Praticare lo sport'),
    (a: 'Calcio', b: 'Tennis'),
    (a: 'Cucina italiana', b: 'Cucina asiatica'),
    (a: 'Piccante da lacrime', b: 'Delicato'),
    (a: 'Colazione abbondante', b: 'Cena abbondante'),
    (a: 'Valigia fatta all\'ultimo', b: 'Valigia pronta una settimana prima'),
    (a: 'Controllare il conto ogni giorno', b: 'Non guardarlo mai'),
    (a: 'Superpotere inutile ma divertente', b: 'Superpotere utile ma noioso'),
    (a: 'Sapere come morirai', b: 'Sapere quando'),
    (a: 'Rileggere sempre lo stesso libro', b: 'Non finirne mai uno'),
    (a: 'Vita senza musica', b: 'Vita senza cinema'),
    (a: 'Sapere sempre la verità', b: 'Vivere felice nell\'illusione'),
    (a: 'Un anno sabbatico', b: 'Andare in pensione un anno prima'),
    (a: 'Parlare tutte le lingue', b: 'Suonare tutti gli strumenti'),
    (a: 'Non provare mai imbarazzo', b: 'Non provare mai paura'),
    (a: 'Rivivere il tuo giorno migliore', b: 'Cancellare il peggiore'),
  ];

  static int get length => it.length;
}
