import '../content_tone.dart';

/// Coppie di "Preferisci" in francese: parità completa col mazzo italiano.
class PreferisciPoolFr {
  const PreferisciPoolFr._();

  static const List<({String a, String b})> pairs = <({String a, String b})>[
    (a: 'Savoir comment tu vas mourir', b: 'Savoir quand'),
    (a: 'Une vérité qui dérange', b: 'Un mensonge confortable'),
    (a: 'Plus d\'argent', b: 'Plus de temps libre'),
    (a: 'Être célèbre', b: 'Être invisible aux yeux des gens'),
    (a: 'Voyager dans le passé', b: 'Voyager dans le futur'),
    (a: 'Savoir voler', b: 'Être invisible'),
    (a: 'Lire les pensées', b: 'Prédire l\'avenir'),
    (a: 'Plus jamais de réseaux', b: 'Plus jamais de films'),
    (a: 'Perdre ton téléphone', b: 'Perdre tes clés de maison'),
    (a: 'Toujours 5 minutes en avance', b: 'Toujours 10 minutes en retard'),
    (a: 'Chef sympa mais incompétent', b: 'Chef odieux mais brillant'),
    (a: 'Gros salaire, boulot ennuyeux', b: 'Petit salaire, boulot passion'),
    (a: 'Mariage à 200 invités', b: 'Mariage à deux'),
    (a: 'Une semaine sans sortir', b: 'Sortir tous les soirs'),
    (a: 'Dormir 10 heures', b: 'Dormir 5 heures et être en forme'),
    (a: 'Refaire les vacances parfaites', b: 'Tester un endroit nouveau'),
    (a: 'Regarder ton compte chaque jour', b: 'Ne jamais le regarder'),
    (a: 'Superpouvoir inutile mais drôle', b: 'Superpouvoir utile mais chiant'),
    (a: 'Relire toujours le même livre', b: 'N\'en finir jamais aucun'),
    (a: 'Une vie sans musique', b: 'Une vie sans cinéma'),
    (a: 'Toujours savoir la vérité', b: 'Vivre heureux dans l\'illusion'),
    (a: 'Une année sabbatique', b: 'Partir à la retraite un an plus tôt'),
    (a: 'Parler toutes les langues', b: 'Jouer de tous les instruments'),
    (a: 'Ne jamais être gêné', b: 'Ne jamais avoir peur'),
    (a: 'Revivre ton plus beau jour', b: 'Effacer le pire'),
    (a: 'Vivre ensemble après un mois', b: 'Vivre ensemble après des années'),
    (a: 'Des enfants tôt', b: 'Des enfants tard'),
    (a: 'Vacances planifiées au détail', b: 'Partir à l\'aventure'),
    (a: 'Une saison en une nuit', b: 'Un épisode par semaine'),
    (a: 'Batterie toujours à 1%', b: 'Internet ultra lent'),
    (
      a: 'Vêtements toujours un peu mouillés',
      b: 'Un caillou dans la chaussure à vie',
    ),
    (a: 'Toujours dire ce que tu penses', b: 'Ne plus pouvoir parler'),
    (a: 'Pas de chauffage en hiver', b: 'Pas de clim en été'),
    (a: 'Le hoquet à vie', b: 'Éternuer toutes les deux minutes'),
    (a: 'Ton plat préféré à chaque repas', b: 'Plus jamais ton plat préféré'),
    (a: 'Ne plus avoir besoin de dormir', b: 'Ne plus avoir besoin de manger'),
    (a: 'Riche mais sans amis', b: 'Fauché mais adoré'),
    (a: 'Plus jamais de loyer', b: 'Salaire doublé'),
    (a: 'Le plus drôle de la salle', b: 'Le plus intelligent de la salle'),
    (a: 'Mémoire photographique', b: 'Oublier chaque humiliation'),
    (a: 'Plus jamais de files d\'attente', b: 'Plus jamais d\'embouteillages'),
    (a: 'Sourcils rasés pendant un an', b: 'Cheveux vert fluo pendant un an'),
    (a: 'Perdre l\'odorat', b: 'Perdre le goût'),
    (a: 'Une voix de dessin animé', b: 'Un rire qui gêne tout le monde'),
    (a: 'Historique visible par tes parents', b: 'Messages lus par ton patron'),
    (a: 'Roter à la fin de chaque phrase', b: 'Rire comme une chèvre'),
    (
      a: 'Utiliser la brosse à dents d\'un inconnu',
      b: 'Boire dans son verre déjà utilisé',
    ),
    (a: 'Mains toujours moites', b: 'Lèvres toujours gercées'),
    (a: 'Sortir avec ton ex', b: 'Avec l\'ex de ton meilleur ami'),
    (a: 'Des pets bruyants mais sans odeur', b: 'Silencieux mais mortels'),
    (a: 'Oublier qui tu es', b: 'Être oublié de tous'),
    (a: 'Perdre tout ton argent', b: 'Perdre tous tes souvenirs'),
    (a: 'Partenaire riche mais ennuyeux', b: 'Partenaire fauché mais hilarant'),
    (
      a: 'Une heure en ascenseur avec ton ex',
      b: 'Une heure en ascenseur avec ton chef',
    ),
    (a: 'Anniversaire oublié par tous', b: 'Fête surprise embarrassante'),
    (a: 'Ton secret révélé à tous', b: 'Connaître les secrets de tous'),
    (a: 'Célèbre mais détesté', b: 'Inconnu mais aimé'),
    (a: 'Ne plus jamais rire', b: 'Ne plus jamais pleurer'),
    (a: 'Retourner au lycée un an', b: 'Repasser le bac chaque année'),
    (a: 'Vivre dans un film d\'horreur', b: 'Vivre dans une comédie musicale'),
    (a: 'Des pieds à la place des mains', b: 'Des mains à la place des pieds'),
    (
      a: 'Un canard grand comme un cheval',
      b: 'Cent chevaux grands comme des canards',
    ),
    (a: 'Vivre sous l\'eau', b: 'Vivre dans l\'espace'),
    (
      a: 'Poursuivi à vie par un escargot tueur',
      b: 'Un clown qui te fixe chaque nuit',
    ),
    (a: 'Parler aux animaux', b: 'Contrôler la météo'),
    (a: 'Danser dès que la musique démarre', b: 'Pleurer quand quelqu\'un rit'),
    (
      a: 'Chaque matin dans un autre pays',
      b: 'Ne plus jamais quitter ta ville',
    ),
    (a: 'Vivre dans un jeu vidéo', b: 'Vivre dans un dessin animé'),
    (a: 'Une touche "pause" pour la vie', b: 'Une touche "retour" pour la vie'),
    (a: 'Téléportation mais sans chaussures', b: 'Voler au pas d\'un piéton'),
    (a: 'Vivre 1000 ans', b: 'Dix vies de 100 ans'),
    (a: 'Une pluie de tacos', b: 'Une neige de glace'),
    (a: 'Roi du monde pour un jour', b: 'Personne normale pour toujours'),
    (
      a: 'Tout savoir sans rien ressentir',
      b: 'Tout ressentir sans rien comprendre',
    ),
    (a: 'Effacer un regret', b: 'T\'assurer un succès futur'),
    (a: 'Toujours affamé', b: 'Toujours endormi'),
    (
      a: 'Une queue qui remue quand tu es content',
      b: 'Des oreilles qui tombent si tu es triste',
    ),
    (a: 'Renoncer au café pour toujours', b: 'Renoncer au chocolat'),
    (
      a: 'Un nez qui pousse quand tu mens',
      b: 'Des cheveux qui changent avec l\'humeur',
    ),
    (a: 'Trouver l\'amour de ta vie', b: 'Trouver le job de tes rêves'),
    (a: 'Très riche mais toujours triste', b: 'Fauché mais toujours heureux'),
    (a: 'Un million tout de suite', b: '3 000 euros par mois à vie'),
    (a: 'Sauver ton chien', b: 'Sauver un inconnu'),
    (a: 'Ne jamais pouvoir mentir', b: 'Croire à chaque mensonge'),
    (a: 'Toujours raison mais tout seul', b: 'Avoir tort mais bien accompagné'),
    (a: 'Génie incompris', b: 'Simplet heureux'),
    (a: 'La même tenue chaque jour', b: 'Ne jamais répéter une tenue'),
    (a: 'Chanter tout ce que tu dis', b: 'Marcher seulement à reculons'),
    (a: 'Wifi gratuit partout à vie', b: 'Vols gratuits à vie'),
    (a: 'Manger seulement brûlant', b: 'Manger seulement glacé'),
    (a: 'Plus jamais de pizza', b: 'Plus jamais de pâtes'),
    (a: 'Plus jamais d\'apéros', b: 'Plus jamais de livraison'),
    (a: 'Vie longue pleine de regrets', b: 'Vie courte sans aucun regret'),
    (
      a: 'Aimer sans être aimé en retour',
      b: 'Être aimé de qui tu n\'aimes pas',
    ),
    (a: 'Ton partenaire lit tes pensées', b: 'Tu lis les siennes'),
    (a: 'Partenaire choisi par tes amis', b: 'Partenaire choisi par un algo'),
    (
      a: 'Toujours démasquer les menteurs',
      b: 'Ne jamais être démasqué en mentant',
    ),
    (a: 'Revivre tes 18 ans pour toujours', b: 'Sauter directement à 40 ans'),
    (
      a: 'Dormir toujours chez les autres',
      b: 'Avoir toujours des invités chez toi',
    ),
    (
      a: 'Le concert de ton groupe mais seul',
      b: 'Un festival entre amis, musique nulle',
    ),
    (
      a: 'Un karaoké faux devant tout le monde',
      b: 'Danser seul une heure en piste',
    ),
    (a: 'Perdre toutes tes photos', b: 'Perdre toutes tes conversations'),
    (a: 'Éternuer des confettis', b: 'Roter des bulles de savon'),
    (a: 'Avoir quatre bras', b: 'Avoir quatre jambes'),
    (a: 'Mesurer 2 m 20', b: 'Mesurer 1 m 20'),
    (a: 'Vivre sans été', b: 'Vivre sans hiver'),
    (a: 'Sauver cinq inconnus', b: 'Sauver ton meilleur ami'),
    (
      a: 'Un million mais plus de smartphone',
      b: 'Zéro argent mais ton téléphone',
    ),
    (
      a: 'Le job de tes rêves à l\'étranger',
      b: 'Un job ennuyeux près de tes amis',
    ),
    (a: 'Avoir 25 ans pour toujours', b: 'Vieillir avec tes amis'),
    (a: 'La maison de rêve au milieu de rien', b: 'Un studio en plein centre'),
    (
      a: 'Savoir ce qu\'on dit derrière ton dos',
      b: 'Vivre tranquille sans le savoir',
    ),
    (a: 'Chaque repas cuisiné par un chef', b: 'Un chauffeur perso à vie'),
    (
      a: 'Commenter à voix haute tout ce que tu fais',
      b: 'Entendre la voix qui narre ta vie',
    ),
    (a: 'Marcher sur des Lego chaque matin', b: 'Douche glacée chaque matin'),
    (a: 'Un moustique chaque nuit', b: 'Une mouche à chaque repas'),
    (a: 'Correcteur auto fou à vie', b: 'Plus jamais d\'emojis'),
    (
      a: 'Appels toujours en haut-parleur',
      b: 'Écran toujours visible par tous',
    ),
    (
      a: 'Ton chien parle mais te critique',
      b: 'Ton miroir te flatte faussement',
    ),
    (a: 'Un million pour toi seul', b: 'Cent mille chacun pour le groupe'),
    (a: 'Toujours sous-estimé', b: 'Toujours surestimé'),
    (
      a: 'Redécouvrir ta série préférée',
      b: 'Voir chaque fin en avant-première',
    ),
    (a: 'Parler seulement en criant', b: 'Parler seulement en chuchotant'),
    (a: 'Rire dans les moments sérieux', b: 'Pleurer à chaque comédie'),
    (
      a: 'Manger toujours avec les mains',
      b: 'Tout manger à la petite cuillère',
    ),
    (a: 'Tes rêves projetés à tes amis', b: 'Tes amis lisent ton journal'),
    (a: 'Le seul célibataire du groupe', b: 'Le premier du groupe à te marier'),
    (a: 'Renaître dans les années 80', b: 'Naître en 2050'),
    (
      a: 'Restos gratuits mais toujours seul',
      b: 'Payer toujours mais bien accompagné',
    ),
    (a: 'Viral pour une honte épique', b: 'Jamais plus de 10 likes'),
    (
      a: 'Boire seulement de l\'eau à vie',
      b: 'Plus jamais d\'eau, que du soda',
    ),
    (a: 'Un seul genre musical à vie', b: 'Une seule appli sur ton téléphone'),
    (a: 'En smoking à la plage', b: 'En maillot à un mariage'),
    (a: 'Cuisiner comme un chef étoilé', b: 'Une maison qui se nettoie seule'),
    (a: 'Long vol à côté d\'un bavard', b: 'Long vol à côté d\'un bébé'),
    (a: 'Petit-déj salé pour toujours', b: 'Dîner sucré pour toujours'),
    (a: 'Vivre sans miroirs', b: 'Vivre sans horloges'),
    (a: 'Revivre le même lundi', b: 'Sauter tous les vendredis'),
    (a: 'Parler avec les plantes', b: 'Comprendre les bébés'),
    (a: 'Toujours gagner aux cartes', b: 'Toujours trouver une place'),
    (a: 'Été à 40 degrés sans mer', b: 'Hiver glacial sans neige'),
    (a: 'Que des films mal doublés', b: 'Que des sous-titres décalés'),
    (a: 'Café gratuit à vie', b: 'Glaces gratuites à vie'),
    (a: 'Déménager chaque année', b: 'La même maison pour toujours'),
    (
      a: 'Sonnerie gênante pour toujours',
      b: 'Fond d\'écran gênant pour toujours',
    ),
    (a: 'Être un mème célèbre', b: 'Avoir un sosie célèbre'),
    (
      a: 'Danser la macarena pour dire bonjour',
      b: 'Saluer tout le monde en s\'inclinant',
    ),
    (a: 'Du Nutella sans pain', b: 'Du pain sans Nutella'),
    (
      a: 'Week-end infini mais toujours pluie',
      b: 'Que des lundis mais toujours soleil',
    ),
    (a: 'Un seul plat mais parfait', b: 'Tout cuisiner de façon moyenne'),
    (a: 'Un aller simple pour Mars', b: 'Ne plus jamais quitter la France'),
    (
      a: 'Dormir chaque nuit sous la tente',
      b: 'Dormir chaque nuit sur le canapé',
    ),
    (a: 'Un majordome robot', b: 'Un cuisinier robot'),
    (a: 'Plus jamais d\'ascenseurs', b: 'Plus jamais d\'escaliers mécaniques'),
    (
      a: 'Savoir tous les potins d\'Hollywood',
      b: 'Savoir la fin de chaque série',
    ),
    (a: 'Que du piquant pendant un an', b: 'Plus jamais de sel'),
    (a: 'Vivre sans musique', b: 'Vivre sans films'),
    (a: 'Toujours cinq minutes en retard', b: 'Toujours une heure en avance'),
    (
      a: 'Très bien danser une seule chanson',
      b: 'Danser bof sur n\'importe quoi',
    ),
    (a: 'Été éternel', b: 'Hiver éternel'),
    (a: 'Plus jamais de friture', b: 'Plus jamais de desserts'),
    (a: 'Lire les pensées des chiens', b: 'Parler avec les chats'),
    (a: 'Toujours choisir la bonne file', b: 'Toujours le bon ascenseur'),
    (a: 'Une maison à la montagne', b: 'Une maison à la mer'),
    (a: 'Revivre le même jour parfait', b: 'Un jour nouveau mais imprévisible'),
    (a: 'Wifi lent pour toujours', b: 'Batterie toujours à dix pour cent'),
    (a: 'Être invisible une heure par jour', b: 'Voler dix minutes par jour'),
    (a: 'Que des douches froides', b: 'Que des trains régionaux'),
    (
      a: 'Cuisiner pour dix chaque soir',
      b: 'Laver la vaisselle de dix chaque soir',
    ),
    (
      a: 'Sac lourd mais tout le nécessaire',
      b: 'Sac léger mais jamais le bon truc',
    ),
    (
      a: 'Photos ratées mais souvenirs nets',
      b: 'Photos parfaites mais souvenirs flous',
    ),
    (
      a: 'Un karaoké obligatoire par semaine',
      b: 'Un discours en public par mois',
    ),
    (a: 'Un majordome humain gênant', b: 'Un robot qui te juge en silence'),
  ];

  /// Dilemmi da modalità Hot: parità completa col mazzo italiano.
  static const List<({String a, String b, String tone})> hot =
      <({String a, String b, String tone})>[
        (
          a: 'Sortir tout nu pendant une minute',
          b: 'Embrasser quelqu\'un de ce groupe',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Passer la nuit avec un du groupe',
          b: 'Une nuit avec un ancien prof',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Montrer ta galerie au groupe',
          b: 'Faire lire tes messages tout haut',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Un an sans sexe',
          b: 'Un an sans sortir le soir',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Dire ton body count au groupe',
          b: 'Montrer ta dernière recherche',
          tone: ContentTone.piccante,
        ),
        (
          a: 'L\'amour sans le sexe',
          b: 'Le sexe sans l\'amour',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Partenaire beau mais nul au lit',
          b: 'Partenaire normal mais génial',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Une nuit avec ton ex',
          b: 'Une nuit avec un inconnu',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Surprendre tes parents',
          b: 'Être surpris par tes parents',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Dire à tous qui te plaît',
          b: 'Ne plus jamais lui parler',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Embrasser un du groupe les yeux fermés',
          b: 'Embrasser ton ex devant tous',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Ne plus pouvoir embrasser',
          b: 'Ne plus pouvoir faire de câlins',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Savoir avec qui on te tromperait',
          b: 'Ne jamais le savoir',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Que des rendez-vous à l\'aveugle un an',
          b: 'Que des dates choisies par ta mère',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Revoir ton premier baiser en vidéo',
          b: 'Que tout le groupe le revoie',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Gémir chaque fois que tu t\'assois',
          b: 'Crier le nom de ton ex à chaque toast',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Envoyer un nude à ton ex par erreur',
          b: 'L\'envoyer au groupe famille',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Sexto au patron par erreur',
          b: 'Appeler ton partenaire du nom de ton ex',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Une nuit avec une célébrité',
          b: 'Un mois de sexe avec ton ex',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Du sexe seulement dans le noir',
          b: 'Seulement avec la lumière allumée',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Dire ton fantasme le plus bizarre',
          b: 'Entendre celui de ta droite',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Sex friend avec ton meilleur ami',
          b: 'Plus de sexe pendant un an',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Un ex qui embrasse divinement',
          b: 'Un nouveau à tout apprendre',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Être déshabillé du regard au bar',
          b: 'Ne plus jamais être remarqué',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Raconter ton pire rendez-vous',
          b: 'Revivre ta honte la plus hot',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Faire toujours le premier pas',
          b: 'Attendre toujours l\'autre',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Un plan à trois avec des inconnus',
          b: 'Un plan à trois avec des amis',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Surprendre ton coloc en action',
          b: 'Être surpris par ton coloc',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Dire combien de fois tu y penses par jour',
          b: 'Dire quand c\'était la dernière fois',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Partenaire très jaloux mais brûlant',
          b: 'Partenaire calme mais paresseux',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Embrasser le premier qui entre',
          b: 'Embrasser le dernier qui t\'a écrit',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Nuit de passion sans baisers',
          b: 'Baisers infinis et rien d\'autre',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Oublier ta première fois',
          b: 'T\'en souvenir chaque jour',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Dire l\'endroit le plus fou où tu l\'as fait',
          b: 'Dire où tu aimerais le faire',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Un flirt avec ton coach sportif',
          b: 'Un flirt avec ton médecin',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Que des coups d\'un soir un an',
          b: 'Que des histoires sérieuses à vie',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Recoucher avec ton ex parfois',
          b: 'Arrêter à jamais mais le regretter',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Un patin avec celui de gauche',
          b: 'Un slow sensuel avec celui de droite',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Dormir nu avec un ami',
          b: 'Te doucher en maillot avec ton ex',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Recevoir un nude de ton patron',
          b: 'Lui en envoyer un par erreur',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Du sexe de dingue une fois par mois',
          b: 'Du sexe moyen tous les jours',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Savoir ce que l\'autre pense au lit',
          b: 'Qu\'il entende chacune de tes pensées',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Un week-end avec ton crush secret',
          b: 'Un mois avec ton premier amour',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Petit-déj au lit après la première nuit',
          b: 'Disparaître avant l\'aube',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Dire ton point faible au lit',
          b: 'Le mimer devant le groupe',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Te tatouer le nom de ton ex',
          b: 'Crier son nom au mauvais moment',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Un match avec ton ex sur une appli',
          b: 'Un match avec ton chef sur une appli',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Ton partenaire connaît tous tes fantasmes',
          b: 'Tu connais tous les siens',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Un strip-tease improvisé maintenant',
          b: 'Un récit très chaud de ton été',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Embrasser un du groupe à ton choix',
          b: 'En embrasser un choisi par le groupe',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Histoire secrète très passionnée',
          b: 'Histoire officielle mais tiède',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Du sexe seulement en été',
          b: 'Du sexe seulement en hiver',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Oublier toutes tes folles nuits',
          b: 'Te souvenir même des pires',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Audio hot envoyé au mauvais numéro',
          b: 'En recevoir un de ton patron',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Faire lire tes messages avec ton ex',
          b: 'Montrer tes photos avec ton ex',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Coup de foudre ce soir',
          b: 'Aventure d\'un soir ce soir',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Dire le nom de ton crush au groupe',
          b: 'Le faire deviner au groupe',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Un slow avec ton ex ce soir',
          b: 'Un karaoké romantique avec un du groupe',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Draguer un inconnu maintenant',
          b: 'Donner ton numéro au premier venu',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Un massage par un du groupe',
          b: 'En faire un à un du groupe',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Interdit de flirter pendant un an',
          b: 'Obligé de flirter avec tous',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Une nuit avec ton idole musicale',
          b: 'Un week-end avec ton acteur préféré',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Avouer un rêve chaud sur un présent',
          b: 'Qu\'un présent l\'avoue sur toi',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Silence total au lit',
          b: 'Commentaire complet au lit',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Un fessier de rêve',
          b: 'Un décolleté à applaudir',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Ton ex devient très célèbre',
          b: 'Ton ex devient ton patron',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Dire ce qui t\'excite le plus',
          b: 'Dire ce qui te coupe l\'envie',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Une aventure d\'été jamais avouée',
          b: 'Un amour à distance infini',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Deux présents te draguent',
          b: 'Draguer deux présents à la fois',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Voir ton ex avec plus beau que toi',
          b: 'Qu\'il te voie avec moins bien',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Des baisers avec morsure',
          b: 'Des bisous sages pour toujours',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Dormir enlacés sans sexe',
          b: 'Du sexe sans jamais dormir ensemble',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Du sexe avec la musique à fond',
          b: 'Avec le journal télé en fond',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Révéler ton nombre d\'ex',
          b: 'Révéler qui était le meilleur',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Draguer le serveur ce soir',
          b: 'Laisser ton numéro sur le ticket',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Première fois gênante mais tendre',
          b: 'Parfaite mais avec la mauvaise personne',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Un tatouage où le groupe décide',
          b: 'Un piercing où le groupe décide',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Un baiser de 30 secondes avec un présent',
          b: 'Dix baisers rapides avec dix inconnus',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Savoir qui du groupe rêve de toi',
          b: 'Savoir qui ne t\'embrasserait jamais',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Du sexe sous tente au camping plein',
          b: 'À l\'hôtel avec des murs en papier',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Des vacances que pour célibataires',
          b: 'Des vacances que pour couples',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Tromper sans jamais être découvert',
          b: 'Être trompé sans jamais le savoir',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Une histoire avec le conjoint d\'un ami',
          b: 'Ton partenaire avec ton meilleur ami',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Que tes pires photos sortent',
          b: 'Que tes pires messages sortent',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Entendre ce que le groupe dit de toi',
          b: 'Que le groupe entende ce que tu dis',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Avouer ton pire secret maintenant',
          b: 'Que ton meilleur ami le révèle',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Du sexe avec l\'ex de ton meilleur ami',
          b: 'Lui dire que tu y as déjà pensé',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Tout savoir sur les présents',
          b: 'Qu\'ils sachent tout sur toi',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Un ex qui revient toujours',
          b: 'Plus jamais de nouvelles d\'un ex',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Te mettre en couple avec un du groupe',
          b: 'Ne plus jamais voir le groupe',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Découvrir une trahison passée',
          b: 'En avouer une à toi maintenant',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Lire le journal secret de l\'autre',
          b: 'Qu\'il lise tous tes messages',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Savoir qui du groupe dit du mal de toi',
          b: 'Savoir qui t\'a le plus menti',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Un ex qui débarque à ton premier date',
          b: 'Un partenaire qui cite toujours son ex',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Tromper en rêve et l\'avouer',
          b: 'Rêver de ton ex chaque nuit et te taire',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Savoir le vrai body count de l\'autre',
          b: 'Qu\'il découvre le tien',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Embrasser l\'ex de ton meilleur ami',
          b: 'Qu\'il embrasse ton ex',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Une nuit avec le conjoint d\'un collègue',
          b: 'Que tous croient que tu l\'as fait',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Découvrir que ton ex te trompait',
          b: 'Découvrir qu\'il t\'a toujours aimé',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Te venger d\'un ex et le regretter',
          b: 'Le pardonner et le regretter plus',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Le groupe lit ton dernier chat hot',
          b: 'Le groupe voit tes photos privées',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Avouer à qui tu as fait un ghosting',
          b: 'Appeler celui qui te l\'a fait',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Être quitté par un message vocal',
          b: 'Quitter quelqu\'un à son anniversaire',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Voler le partenaire de quelqu\'un',
          b: 'Se le faire voler et le reprendre',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Savoir chaque mensonge de l\'autre',
          b: 'Qu\'il sache chacun des tiens',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Dire au groupe ta pire trahison',
          b: 'Dire le pire secret d\'un ami',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Flirter avec le conjoint de ton chef',
          b: 'Que ton chef flirte avec le tien',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Un ami qui drague ton partenaire',
          b: 'Ton partenaire qui drague ton ami',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Trouver un cadeau de son ex chez lui',
          b: 'Trouver leurs messages dans son tél',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Effacer un de tes secrets à jamais',
          b: 'Découvrir ce qu\'on te cache',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Dire avec qui du groupe tu ne sortirais pas',
          b: 'Entendre qui ne sortirait pas avec toi',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Un ex à qui tu dois encore de l\'argent',
          b: 'Un ex qui te doit des excuses',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Avouer que tu as stalké ton ex',
          b: 'Montrer l\'historique de ses profils',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Du sexe en cachette chez tes beaux-parents',
          b: 'Être surpris par eux au pire moment',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Ton meilleur ami te déteste',
          b: 'Ton ami aime ton partenaire',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Une nuit de trahison avouée',
          b: 'Une double vie jamais découverte',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Répondre nu à trois questions',
          b: 'Répondre habillé à trente',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Savoir la date de la fin du couple',
          b: 'Savoir la raison mais pas la date',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Un rival en amour plus beau',
          b: 'Un rival plus sympathique',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Dire tout de suite s\'il embrasse mal',
          b: 'L\'épouser sans jamais le dire',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'L\'ex qui t\'écrit à 3 h du matin',
          b: 'Lui écrire et le nier toujours',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Partenaire ami avec tous ses ex',
          b: 'Partenaire qui t\'interdit les tiens',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Découvrir son profil secret',
          b: 'Qu\'il trouve le tien',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Aimer deux personnes à la fois',
          b: 'Être l\'amant sans le savoir',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Dire qui embrasse le plus mal ici',
          b: 'Être noté par chaque présent',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Saboter le mariage de ton ex',
          b: 'Être témoin à son mariage',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Une liste publique de tes flirts',
          b: 'Une liste de qui t\'a refusé',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Perdre l\'ami en lui disant la vérité',
          b: 'Le garder en lui mentant à vie',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Ton ennemi connaît ton secret',
          b: 'Ta belle-mère sait tout de toi',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Échanger de partenaire une semaine',
          b: 'Vivre célibataire un an',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Le groupe vote ton pire défaut',
          b: 'Les entendre lister tes flirts',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Tromper et l\'avouer dix ans après',
          b: 'Le découvrir dix ans après',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Un week-end avec tes beaux-parents',
          b: 'Un week-end avec l\'ex de ton conjoint',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Savoir combien t\'ont dit non',
          b: 'Savoir qui a regretté son oui',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Tout dire sur un amour secret',
          b: 'Que le groupe enquête une heure',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Lire à voix haute ton dernier message',
          b: 'Appeler le dernier numéro composé',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Briser un couple en disant la vérité',
          b: 'Le sauver avec un énorme mensonge',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Ton ex parle de toi dans un podcast',
          b: 'Le groupe raconte tes pires nuits',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Être le plan B de quelqu\'un',
          b: 'Avoir un plan B et être démasqué',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Ton partenaire fouille ton téléphone',
          b: 'Ne jamais pouvoir voir le sien',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Dire ton dernier mensonge à un présent',
          b: 'Que chaque présent en dise un sur toi',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Sortir avec le jumeau de ton ex',
          b: 'Avec un sosie de ton patron',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Savoir ce que tes ex disent de toi',
          b: 'Les réunir tous à un dîner',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Tromper par vengeance et le dire',
          b: 'Encaisser et comploter en silence',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Embrasser quelqu\'un pour un pari',
          b: 'Découvrir que tu étais un pari',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Un mariage forcé dans un mois',
          b: 'Dix ans de fiançailles sans mariage',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Espionner la soirée de ton ex',
          b: 'Le bloquer et mourir de curiosité',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Avouer le flirt le plus minable',
          b: 'Que celui qui était là le raconte',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Le groupe sait qui te plaît ici',
          b: 'Seule la mauvaise personne le sait',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Découvrir la double vie de l\'autre',
          b: 'Réussir à cacher la tienne',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Briser un couple d\'amis en parlant',
          b: 'Les voir malheureux et te taire',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Le groupe choisit ton partenaire',
          b: 'Le groupe choisit qui tu quittes',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Dire la vraie raison de ta rupture',
          b: 'Entendre la version de ton ex',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Une nuit avec deux ex à la fois',
          b: 'Une nuit avec ton ex et son amour',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Être jaloux et avoir raison',
          b: 'Faire confiance et être trompé',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Un baiser parfait par mois',
          b: 'Des baisers moyens chaque jour',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Savoir ce que ton crush pense de toi',
          b: 'Qu\'il sache tout ce que tu penses',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Une nuit inoubliable sans suite',
          b: 'Dix dates mignonnes sans étincelle',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Dormir enlacés et rien de plus',
          b: 'Tout le reste mais aucun câlin après',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Dire ton body count à ton crush',
          b: 'Montrer ton dernier chat brûlant',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Partenaire qui embrasse très bien',
          b: 'Partenaire qui écrit très bien',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Flirter devant tes parents',
          b: 'Flirter devant ton ex',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Recevoir une photo osée par erreur',
          b: 'En envoyer une au mauvais contact',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Être séduit par les mots',
          b: 'Être séduit par le regard',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Week-end de passion sans téléphone',
          b: 'Semaine de flirt seulement par chat',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Premier baiser au premier rendez-vous',
          b: 'Premier baiser après un mois d\'attente',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Savoir qui te regarde dans un bar',
          b: 'L\'ignorer mais être très regardé',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Un ex qui t\'écrit chaque nuit',
          b: 'Un crush qui ne t\'écrit jamais',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Un slow avec ton crush devant tous',
          b: 'Dîner aux chandelles en silence',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Faire lire ton chat avec ton crush',
          b: 'L\'appeler tout de suite en haut-parleur',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Un massage parfait chaque soir',
          b: 'Petit-déj au lit chaque matin',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Être le meilleur baiser de quelqu\'un',
          b: 'Recevoir le meilleur baiser de ta vie',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Plus jamais de premiers rendez-vous',
          b: 'Que des premiers rendez-vous à vie',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Dire "tu me plais" toujours en premier',
          b: 'Attendre toujours qu\'on te le dise',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Une playlist qui démarre si tu flirtes',
          b: 'Une voix qui commente tes dates',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Ton ex à ton mariage',
          b: 'Ta belle-mère en lune de miel',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Revoir ton premier baiser filmé',
          b: 'Montrer ton profil de rencontres',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Un froid à chaque "il faut qu\'on parle"',
          b: 'Ne jamais l\'entendre de ta vie',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Un flirt d\'été chaque été',
          b: 'Un vrai amour tous les dix ans',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Savoir combien de fois on a parlé de toi',
          b: 'Savoir ce qu\'on a dit mais pas qui',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Des baisers que sous la pluie',
          b: 'Des baisers que dans l\'ascenseur',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Un "bonjour" de la bonne personne',
          b: 'Une "bonne nuit" chaque soir',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Perdre ta voix quand tu flirtes',
          b: 'Toujours dire un mot de trop',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Être irrésistible que le jour',
          b: 'Être irrésistible que la nuit',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Un date à l\'aveugle choisi par le groupe',
          b: 'Un date organisé par ton ex',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Dîner avec le conjoint de ton crush',
          b: 'Leur servir de chauffeur toute la soirée',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Repérer les mensonges en amour',
          b: 'Ne jamais mentir le premier',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Un an sans baisers',
          b: 'Un an sans câlins',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Avouer ton crush à la personne',
          b: 'L\'avouer à toute la salle maintenant',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Célèbre pour une histoire d\'amour',
          b: 'Célèbre pour un râteau épique',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Sortir avec ton sosie',
          b: 'Sortir avec ton exact opposé',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Ton journal lu par ton crush',
          b: 'Ton historique lu par tes parents',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Un baiser volé inoubliable',
          b: 'Cent baisers demandés poliment',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Paraître toujours indifférent',
          b: 'Paraître toujours trop intéressé',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Un coup de foudre une seule fois',
          b: 'Des coups de foudre jamais rendus',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Des fleurs au bureau chaque semaine',
          b: 'Un vocal romantique chaque soir',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Très bien flirter que par écrit',
          b: 'Très bien flirter qu\'en vrai',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Un crush pour un ami de ce groupe',
          b: 'Un crush pour un collègue de bureau',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Savoir si le premier date ira bien',
          b: 'Pouvoir refaire chaque premier date',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Un date romantique planifié à la minute',
          b: 'Improvisation totale chaque fois',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Un partenaire qui danse très bien',
          b: 'Un partenaire qui cuisine très bien',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Zéro jalousie pour toujours',
          b: 'Double passion mais jalousie incluse',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Être courtisé par deux personnes',
          b: 'Choisir toi mais sans être courtisé',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Ton nom dans une chanson d\'amour',
          b: 'Ton visage dans une vidéo romantique',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Que des dates au petit-déjeuner',
          b: 'Que des dates à minuit',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Main dans la main en public toujours',
          b: 'Des câlins qu\'en privé mais intenses',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Oublier tous tes ex',
          b: 'Que tous tes ex t\'oublient',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Un baiser de film une fois par an',
          b: 'Des baisers normaux mais quotidiens',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Te déclarer avec une lettre à la main',
          b: 'Te déclarer devant tout le monde',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Savoir le jour où tu tomberas amoureux',
          b: 'Savoir juste le nom mais pas quand',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Partenaire susceptible mais passionné',
          b: 'Partenaire zen mais tiède',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Revivre ton premier amour',
          b: 'Connaître d\'avance le dernier',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Passer pour timide en flirtant',
          b: 'Passer pour effronté alors que non',
          tone: ContentTone.piccante,
        ),
        (
          a: 'La vraie raison de chaque rupture',
          b: 'Ne jamais le savoir mais finir en paix',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Un date parfait organisé par ton ex',
          b: 'Un désastre avec la bonne personne',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Plaire à tous sauf à ton crush',
          b: 'Plaire qu\'à ton crush et à personne',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Messages toujours lus tout de suite',
          b: 'Réponse garantie en une minute',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Retirer un message par jour',
          b: 'Relire les messages supprimés',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Flirt éhonté mais que le mardi',
          b: 'Flirt léger mais tous les jours',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Le groupe choisit ton prochain date',
          b: 'Le groupe lit le chat du dernier',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Être embrassé sans prévenir',
          b: 'Annoncer chaque baiser dix secondes avant',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Un été de célibataire légendaire',
          b: 'Un hiver en couple parfait',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Ton crush voit toutes tes stories',
          b: 'Tu vois tout ce qu\'il regarde',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Un slow avec la mauvaise personne',
          b: 'Plus jamais un seul slow',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Du sexe dans le noir pour toujours',
          b: 'Que lumière allumée pour toujours',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Une seule position à vie',
          b: 'Toutes sauf ta préférée',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Dire ton fantasme le plus hard au groupe',
          b: 'Montrer ton historique privé',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Un an de chasteté',
          b: 'Un an sans téléphone',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Que les voisins t\'entendent',
          b: 'Entendre les voisins chaque nuit',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Que du sexe le matin',
          b: 'Que du sexe en pleine nuit',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Parfait au lit mais nul en mots',
          b: 'Poète merveilleux mais nul au lit',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Dire tous tes chiffres, body count inclus',
          b: 'Donner ton tél déverrouillé une heure',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Revoir ta première fois en vidéo',
          b: 'La raconter maintenant sans détails',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Commencer toujours toi, par contrat',
          b: 'Attendre toujours, même des mois',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Du sexe sans jamais de baisers',
          b: 'Des baisers sans jamais rien d\'autre',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Une nuit avec ton pire ex',
          b: 'Six mois sans personne',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Le groupe écoute tes vocaux de 3 h',
          b: 'Le groupe lit ton dernier sexto',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Surpris par tes parents au pire moment',
          b: 'Les surprendre toi au pire moment',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Oublier tes meilleures nuits',
          b: 'T\'en souvenir sans jamais le dire',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Tester un fetish choisi par le groupe',
          b: 'Avouer le tien maintenant',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Que des aventures d\'un soir à vie',
          b: 'Que du sérieux dès le premier jour',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Une histoire secrète à jamais',
          b: 'Tout public dès le premier jour',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Un sex friend qui tombe amoureux',
          b: 'Tomber amoureux de tes sex friends',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Dire tout haut qui t\'attire ici',
          b: 'Que le groupe vote qui tu attires',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Ton tiroir secret trouvé par ta mère',
          b: 'Trouvé par ton patron',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Du sexe que chez toi pour toujours',
          b: 'Plus jamais chez toi',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Douche à deux toujours obligatoire',
          b: 'Plus jamais de douche à deux',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Dormir nu partout, toujours',
          b: 'Habillé même en lune de miel',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Un tatouage au nom de chaque ex',
          b: 'Une liste publique de tes ex en ligne',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Faire toujours trop de bruit',
          b: 'Silence absolu pour toujours',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Ton ex sert de référence à tes dates',
          b: 'Aucune référence mais des soupçons',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Savoir combien de fois on a simulé',
          b: 'Vivre serein dans le doute',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Du sexe dix sur dix une fois par mois',
          b: 'Du six sur dix tous les jours',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Toujours trop rapide',
          b: 'Toujours trop long',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Ta playlist hot démarre au bureau',
          b: 'Ton dernier message hot lu en famille',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Une nuit avec ta star et tous le savent',
          b: 'Secret total mais personne te croira',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Que des lieux publics risqués',
          b: 'Que ton lit pour toujours',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Avouer l\'endroit le plus fou',
          b: 'Le faire deviner au groupe',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Plus jamais de préliminaires',
          b: 'Que des préliminaires',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Chaque date finit au lit',
          b: 'Aucune ne finit au lit au premier',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Savoir la note que tes ex te donnent',
          b: 'Donner tes notes en public',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Un week-end sans limites mais secret',
          b: 'Une soirée normale racontable dix ans',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Ton moment le plus gênant raconté par un autre',
          b: 'Le raconter toi mais en entier',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Perdre ta position préférée à jamais',
          b: 'L\'expliquer maintenant au groupe',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Que du sexe planifié à l\'agenda',
          b: 'Que de l\'imprévu au pire moment',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Dire chaque fois "c\'était le meilleur"',
          b: 'Ne jamais pouvoir commenter',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Un mois sans toucher ton partenaire',
          b: 'Un mois sans lui parler',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Qu\'on sache toujours quand tu l\'as fait',
          b: 'Que personne ne te croie jamais',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Des habits déchirés chaque fois, à tes frais',
          b: 'Tout plier avant, tranquillement',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Ton ex dans la chambre d\'à côté',
          b: 'Ton ex dans ton groupe d\'amis à vie',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Raconter ton rêve érotique le plus fou',
          b: 'Que le groupe choisisse le héros',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Plus jamais de sexe en vacances',
          b: 'Du sexe qu\'en vacances',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Perdre le compte de tes nuits',
          b: 'Un compteur public toujours à jour',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Séduire toujours avec la même phrase',
          b: 'Ne plus jamais parler en séduisant',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Les voisins savent quand tu as de la visite',
          b: 'Ton groupe reçoit une notification',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Petit-déj chaque fois avec sa famille',
          b: 'Sortir toujours par la fenêtre',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Du sexe que sur de la trap',
          b: 'Que sur du classique à fond',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Dormir sur place, obligatoire',
          b: 'Ne jamais pouvoir rester dormir',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Ta première pensée dite tout haut',
          b: 'Ta dernière pensée publiée',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Plus jamais de baisers dans le cou',
          b: 'Que des baisers dans le cou',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Excellent mais tu oublies tout',
          b: 'Tu te souviens de tout mais moyen',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'La vérité vraie sur la soirée',
          b: 'Des compliments jamais sincères',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Refaire à vie ta meilleure nuit',
          b: 'Une nuit nouvelle mais surprise totale',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Du sexe qu\'après trois dates pile',
          b: 'Au premier date ou jamais',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Tous connaissent ton fetish',
          b: 'Ne plus jamais le pratiquer',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Un an célibataire aux souvenirs nets',
          b: 'En couple mais amnésique des nuits',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Strip-tease obligatoire à chaque fête',
          b: 'Plus jamais te dévêtir avec la lumière',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Le dire chaque fois qu\'on t\'attire',
          b: 'Ne jamais pouvoir le laisser voir',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Le groupe choisit avec qui tu flirtes',
          b: 'Le groupe observe comment tu flirtes',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Plus jamais le matin',
          b: 'Plus jamais la nuit',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Que des hôtels à l\'heure',
          b: 'Que chez tes parents',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Du sexe génial mais qu\'en été',
          b: 'Moyen mais toute l\'année',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Savoir ce qu\'il pense vraiment pendant',
          b: 'Qu\'il sache tout ce que tu penses toi',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Ton type choisi par le groupe un an',
          b: 'Choisi par ton ex',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Chaque date commentée en oreillette',
          b: 'Toujours seul et sans conseils',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Une nuit à raconter pendant dix ans',
          b: 'Dix nuits à oublier tout de suite',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Ton prochain partenaire est ici',
          b: 'Ce ne sera jamais personne d\'ici',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Avouer maintenant ton truc le plus hard',
          b: 'Que ton meilleur ami le raconte',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Un week-end de passion sans un mot',
          b: 'Un week-end de discussion parfaite',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Que chaque ex donne sa version de vous',
          b: 'Ne jamais pouvoir donner la tienne',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Avaler le sperme à chaque fois',
          b: 'Ne plus jamais recevoir de sexe oral',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Faire du sexe anal tous les jours',
          b: 'Ne plus jamais faire l\'amour de ta vie',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Être filmé pendant que tu baises',
          b: 'Le faire devant tout le groupe',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Que tout le monde sache à quel point tu baises mal',
          b: 'Qu\'ils sachent quel est ton fétiche le plus extrême',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Lécher l\'anus de ton pire ennemi',
          b: 'Te faire lécher l\'anus par un parfait inconnu',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Jouir sur le visage de celui à ta droite',
          b: 'Te faire jouir sur le visage par celui à ta gauche',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Un plan à trois avec deux amis proches',
          b: 'Un plan à trois avec deux parfaits inconnus',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Un an de sexe uniquement anal',
          b: 'Un an de sexe uniquement oral',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Que tes parents voient tes messages hot',
          b: 'Qu\'ils voient une vidéo de toi en train de le faire',
          tone: ContentTone.cattivo,
        ),
      ];
}
