import '../content_tone.dart';

/// Coppie di "Preferisci" in spagnolo: parità completa col mazzo italiano.
class PreferisciPoolEs {
  const PreferisciPoolEs._();

  static const List<({String a, String b})> pairs = <({String a, String b})>[
    (a: 'Saber cómo morirás', b: 'Saber cuándo'),
    (a: 'Una verdad incómoda', b: 'Una mentira cómoda'),
    (a: 'Más dinero', b: 'Más tiempo libre'),
    (a: 'Ser famoso', b: 'Ser invisible para la gente'),
    (a: 'Viajar al pasado', b: 'Viajar al futuro'),
    (a: 'Saber volar', b: 'Ser invisible'),
    (a: 'Leer la mente', b: 'Predecir el futuro'),
    (a: 'Nunca más redes sociales', b: 'Nunca más películas'),
    (a: 'Perder el móvil', b: 'Perder las llaves de casa'),
    (a: 'Siempre 5 minutos antes', b: 'Siempre 10 minutos tarde'),
    (a: 'Jefe simpático pero inútil', b: 'Jefe borde pero brillante'),
    (a: 'Sueldo alto y trabajo aburrido', b: 'Sueldo bajo y trabajo que amas'),
    (a: 'Boda con 200 invitados', b: 'Boda de dos'),
    (a: 'Una semana sin salir', b: 'Salir todas las noches'),
    (a: 'Dormir 10 horas', b: 'Dormir 5 y estar genial'),
    (a: 'Repetir las vacaciones perfectas', b: 'Probar un sitio nuevo'),
    (a: 'Mirar la cuenta cada día', b: 'No mirarla nunca'),
    (a: 'Superpoder inútil pero divertido', b: 'Superpoder útil pero aburrido'),
    (a: 'Releer siempre el mismo libro', b: 'No acabar ninguno nunca'),
    (a: 'Vida sin música', b: 'Vida sin cine'),
    (a: 'Saber siempre la verdad', b: 'Vivir feliz en la ilusión'),
    (a: 'Un año sabático', b: 'Jubilarte un año antes'),
    (a: 'Hablar todos los idiomas', b: 'Tocar todos los instrumentos'),
    (a: 'No sentir nunca vergüenza', b: 'No sentir nunca miedo'),
    (a: 'Revivir tu mejor día', b: 'Borrar el peor'),
    (a: 'Vivir juntos al mes', b: 'Vivir juntos tras años'),
    (a: 'Hijos pronto', b: 'Hijos tarde'),
    (a: 'Viaje planeado al detalle', b: 'Salir a la aventura'),
    (a: 'Una temporada en una noche', b: 'Un episodio por semana'),
    (a: 'Batería siempre al 1%', b: 'Internet lentísimo'),
    (a: 'Ropa siempre algo mojada', b: 'Piedra en el zapato para siempre'),
    (a: 'Decir siempre lo que piensas', b: 'No poder hablar nunca más'),
    (a: 'Sin calefacción en invierno', b: 'Sin aire en verano'),
    (a: 'Hipo de por vida', b: 'Estornudar cada dos minutos'),
    (a: 'Tu plato favorito en cada comida', b: 'Nunca más tu plato favorito'),
    (a: 'No necesitar dormir nunca', b: 'No necesitar comer nunca'),
    (a: 'Rico pero sin amigos', b: 'Sin blanca pero muy querido'),
    (a: 'Nunca más alquiler', b: 'Sueldo el doble'),
    (a: 'El más simpático de la sala', b: 'El más listo de la sala'),
    (a: 'Memoria fotográfica', b: 'Olvidar cada ridículo'),
    (a: 'Nunca más colas', b: 'Nunca más atascos'),
    (a: 'Cejas rapadas un año', b: 'Pelo verde flúor un año'),
    (a: 'Perder el olfato', b: 'Perder el gusto'),
    (a: 'Voz de dibujo animado', b: 'Risa que avergüenza a todos'),
    (a: 'Historial visible para tus padres', b: 'Chats leídos por tu jefe'),
    (a: 'Eructar al final de cada frase', b: 'Reírte como una cabra'),
    (a: 'Usar el cepillo de un desconocido', b: 'Beber de su vaso ya usado'),
    (a: 'Manos siempre sudadas', b: 'Labios siempre agrietados'),
    (a: 'Salir con tu ex', b: 'Con el ex de tu mejor amigo'),
    (a: 'Pedos ruidosos pero sin olor', b: 'Silenciosos pero mortales'),
    (a: 'Olvidar quién eres', b: 'Que todos te olviden'),
    (a: 'Perder todo tu dinero', b: 'Perder todos tus recuerdos'),
    (a: 'Pareja rica pero aburrida', b: 'Pareja pobre pero divertida'),
    (
      a: 'Una hora en el ascensor con tu ex',
      b: 'Una hora en el ascensor con tu jefe',
    ),
    (a: 'Cumpleaños olvidado por todos', b: 'Fiesta sorpresa incómoda'),
    (a: 'Tu secreto contado a todos', b: 'Saber los secretos de todos'),
    (a: 'Famoso pero odiado', b: 'Anónimo pero querido'),
    (a: 'No volver a reír', b: 'No volver a llorar'),
    (a: 'Volver al instituto un año', b: 'Repetir la selectividad cada año'),
    (a: 'Vivir en una peli de terror', b: 'Vivir en un musical'),
    (a: 'Pies en lugar de manos', b: 'Manos en lugar de pies'),
    (
      a: 'Un pato del tamaño de un caballo',
      b: 'Cien caballos del tamaño de un pato',
    ),
    (a: 'Vivir bajo el agua', b: 'Vivir en el espacio'),
    (
      a: 'Perseguido por un caracol asesino',
      b: 'Un payaso que te mira cada noche',
    ),
    (a: 'Hablar con los animales', b: 'Controlar el tiempo'),
    (a: 'Bailar en cuanto suena la música', b: 'Llorar cuando alguien se ríe'),
    (a: 'Cada mañana en un país distinto', b: 'No salir nunca de tu ciudad'),
    (a: 'Vivir en un videojuego', b: 'Vivir en un dibujo animado'),
    (a: 'Botón de pausa para la vida', b: 'Botón de rebobinar para la vida'),
    (a: 'Teletransporte sin zapatos', b: 'Volar a paso de tortuga'),
    (a: 'Vivir 1000 años', b: 'Diez vidas de 100 años'),
    (a: 'Lluvia de tacos', b: 'Nieve de helado'),
    (a: 'Rey del mundo un día', b: 'Persona normal para siempre'),
    (a: 'Saberlo todo sin sentir nada', b: 'Sentir todo sin entender nada'),
    (a: 'Borrar un arrepentimiento', b: 'Garantizarte un éxito futuro'),
    (a: 'Siempre con hambre', b: 'Siempre con sueño'),
    (
      a: 'Cola que se mueve si eres feliz',
      b: 'Orejas que caen si estás triste',
    ),
    (a: 'Renunciar al café para siempre', b: 'Renunciar al chocolate'),
    (a: 'Nariz que crece al mentir', b: 'Pelo que cambia con el ánimo'),
    (
      a: 'Encontrar el amor de tu vida',
      b: 'Encontrar el trabajo de tus sueños',
    ),
    (a: 'Riquísimo pero siempre triste', b: 'Sin un euro pero feliz'),
    (a: 'Un millón ahora', b: '3.000 euros al mes de por vida'),
    (a: 'Salvar a tu perro', b: 'Salvar a un desconocido'),
    (a: 'No poder mentir nunca', b: 'Creerte cualquier mentira'),
    (a: 'Tener razón siempre pero solo', b: 'Equivocarte pero acompañado'),
    (a: 'Genio incomprendido', b: 'Simplón feliz'),
    (a: 'El mismo look cada día', b: 'No repetir look nunca'),
    (a: 'Cantar todo lo que dices', b: 'Andar solo hacia atrás'),
    (a: 'Wifi gratis en todas partes', b: 'Vuelos gratis de por vida'),
    (a: 'Comer solo comida hirviendo', b: 'Solo comida helada'),
    (a: 'Nunca más pizza', b: 'Nunca más pasta'),
    (a: 'Nunca más cañas', b: 'Nunca más comida a domicilio'),
    (a: 'Vida larga llena de reproches', b: 'Vida corta sin arrepentimientos'),
    (a: 'Amar sin ser correspondido', b: 'Que te ame quien no amas'),
    (a: 'Tu pareja te lee la mente', b: 'Tú le lees la mente'),
    (a: 'Pareja elegida por tus amigos', b: 'Pareja elegida por un algoritmo'),
    (a: 'Saber siempre quién te miente', b: 'Que nunca te pillen mintiendo'),
    (a: 'Revivir tus 18 años para siempre', b: 'Saltar directo a los 40'),
    (a: 'Dormir siempre en casa ajena', b: 'Tener siempre invitados en casa'),
    (
      a: 'Tu grupo favorito pero tú solo',
      b: 'Festival con amigos y música que odias',
    ),
    (
      a: 'Karaoke desafinando ante todos',
      b: 'Bailar solo en la pista una hora',
    ),
    (a: 'Perder todas las fotos del móvil', b: 'Perder todos los chats'),
    (a: 'Estornudar confeti', b: 'Eructar pompas de jabón'),
    (a: 'Tener cuatro brazos', b: 'Tener cuatro piernas'),
    (a: 'Medir dos veinte', b: 'Medir uno veinte'),
    (a: 'Vivir sin verano', b: 'Vivir sin invierno'),
    (a: 'Salvar a cinco desconocidos', b: 'Salvar a tu mejor amigo'),
    (a: 'Un millón y nunca más móvil', b: 'Cero dinero pero con móvil'),
    (
      a: 'Trabajo ideal en el extranjero',
      b: 'Trabajo aburrido cerca de amigos',
    ),
    (a: 'Tener 25 años para siempre', b: 'Envejecer con tus amigos'),
    (a: 'Casa ideal en medio de la nada', b: 'Estudio en pleno centro'),
    (
      a: 'Saber qué dicen de ti a tus espaldas',
      b: 'Vivir tranquilo sin saberlo',
    ),
    (a: 'Cada comida hecha por un chef', b: 'Chófer personal de por vida'),
    (
      a: 'Narrar en voz alta todo lo que haces',
      b: 'Oír la voz narradora de tu vida',
    ),
    (a: 'Pisar Legos cada mañana', b: 'Ducha helada cada mañana'),
    (a: 'Un mosquito cada noche', b: 'Una mosca en cada plato'),
    (a: 'Autocorrector loco de por vida', b: 'Nunca más emojis'),
    (
      a: 'Llamadas solo en manos libres',
      b: 'Pantalla siempre visible para todos',
    ),
    (a: 'Tu perro habla pero te critica', b: 'Tu espejo te halaga en falso'),
    (a: 'Un millón solo para ti', b: 'Cien mil por cabeza para el grupo'),
    (a: 'Que siempre te infravaloren', b: 'Que siempre te sobrevaloren'),
    (a: 'Redescubrir tu serie favorita', b: 'Ver antes cada final'),
    (a: 'Hablar solo a gritos', b: 'Hablar solo susurrando'),
    (a: 'Reírte siempre en momentos serios', b: 'Llorar con cada comedia'),
    (a: 'Comer siempre con las manos', b: 'Comer todo con cucharilla'),
    (a: 'Tus sueños proyectados a tus amigos', b: 'Tus amigos leen tu diario'),
    (a: 'El único soltero del grupo', b: 'El primero del grupo en casarte'),
    (a: 'Nacer en los 80', b: 'Nacer en 2050'),
    (a: 'Restaurantes gratis pero solo', b: 'Pagar siempre pero acompañado'),
    (a: 'Viral por un ridículo épico', b: 'Nunca más de 10 likes'),
    (a: 'Beber solo agua para siempre', b: 'Nunca más agua, solo refrescos'),
    (a: 'Un solo género musical de por vida', b: 'Una sola app en el móvil'),
    (a: 'De esmoquin en la playa', b: 'En bañador en una boda'),
    (a: 'Cocinar como un chef con estrella', b: 'Casa que se limpia sola'),
    (a: 'Vuelo largo junto a un charlatán', b: 'Vuelo largo junto a un bebé'),
    (a: 'Desayuno salado para siempre', b: 'Cena dulce para siempre'),
    (a: 'Vivir sin espejos', b: 'Vivir sin relojes'),
    (a: 'Revivir el mismo lunes', b: 'Saltarte todos los viernes'),
    (a: 'Hablar con las plantas', b: 'Entender a los bebés'),
    (a: 'Ganar siempre a las cartas', b: 'Encontrar siempre aparcamiento'),
    (a: 'Verano de 40 grados sin playa', b: 'Invierno helado sin nieve'),
    (a: 'Solo pelis mal dobladas', b: 'Solo pelis con subtítulos desfasados'),
    (a: 'Café gratis de por vida', b: 'Helado gratis de por vida'),
    (a: 'Mudarte cada año', b: 'La misma casa para siempre'),
    (a: 'Tono de móvil vergonzoso siempre', b: 'Fondo de pantalla vergonzoso'),
    (a: 'Ser un meme famoso', b: 'Tener un doble famoso'),
    (
      a: 'Bailar la macarena al saludar',
      b: 'Saludar a todos con una reverencia',
    ),
    (a: 'Nocilla sin pan', b: 'Pan sin Nocilla'),
    (a: 'Fin de semana infinito con lluvia', b: 'Solo lunes pero siempre sol'),
    (a: 'Un solo plato pero perfecto', b: 'Cocinarlo todo regular'),
  ];

  /// Dilemmi da modalità Hot: parità completa col mazzo italiano.
  static const List<({String a, String b, String tone})> hot =
      <({String a, String b, String tone})>[
        (
          a: 'Salir desnudo un minuto',
          b: 'Besar a alguien de este grupo',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Pasar la noche con alguien del grupo',
          b: 'Una noche con un profe del insti',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Mostrar tu galería al grupo',
          b: 'Que lean tus chats en voz alta',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Un año sin sexo',
          b: 'Un año sin salir de noche',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Decir tu body count al grupo',
          b: 'Mostrar tu última búsqueda',
          tone: ContentTone.piccante,
        ),
        (a: 'Amor sin sexo', b: 'Sexo sin amor', tone: ContentTone.piccante),
        (
          a: 'Pareja guapa pero mala en la cama',
          b: 'Pareja normal pero espectacular',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Una noche con tu ex',
          b: 'Una noche con un desconocido',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Pillar a tus padres',
          b: 'Que te pillen tus padres',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Decir a todos quién te gusta',
          b: 'No hablarle nunca más',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Besar a uno del grupo con los ojos cerrados',
          b: 'Besar a tu ex delante de todos',
          tone: ContentTone.piccante,
        ),
        (
          a: 'No poder besar más',
          b: 'No poder abrazar más',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Saber con quién te engañaría tu pareja',
          b: 'No saberlo nunca',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Solo citas a ciegas un año',
          b: 'Solo citas elegidas por tu madre',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Ver en vídeo tu primer beso',
          b: 'Que lo vea todo el grupo',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Gemir cada vez que te sientas',
          b: 'Gritar el nombre de tu ex al brindar',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Mandar un desnudo a tu ex sin querer',
          b: 'Mandarlo al grupo de la familia',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Sexting con tu jefe por error',
          b: 'Llamar a tu pareja como a tu ex',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Una noche con un famoso',
          b: 'Un mes de sexo con tu ex',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Sexo solo a oscuras totales',
          b: 'Solo con la luz siempre encendida',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Decir tu fantasía más rara',
          b: 'Oír la del que tienes a la derecha',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Amigos de cama con tu mejor amigo',
          b: 'Nunca más sexo durante un año',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Un ex que besa de maravilla',
          b: 'Uno nuevo al que enseñar todo',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Que te desnuden con la mirada en el bar',
          b: 'No volver a llamar la atención',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Contar tu peor cita',
          b: 'Revivir tu ridículo más caliente',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Dar tú siempre el primer paso',
          b: 'Esperar siempre al otro',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Un trío con desconocidos',
          b: 'Un trío con amigos',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Pillar a tu compañero de piso',
          b: 'Que él te pille a ti',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Decir cuántas veces lo piensas al día',
          b: 'Decir cuándo fue la última vez',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Pareja celosísima pero ardiente',
          b: 'Pareja tranquila pero perezosa',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Besar al primero que entre por la puerta',
          b: 'Besar al último que te escribió',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Noche de pasión sin besos',
          b: 'Besos infinitos y nada más',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Olvidar tu primera vez',
          b: 'Recordarla cada día',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Decir el sitio más absurdo donde lo hiciste',
          b: 'Decir dónde te gustaría hacerlo',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Un flirteo con tu entrenador',
          b: 'Un flirteo con tu médico',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Solo rollos de una noche un año',
          b: 'Solo relaciones serias de por vida',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Volver con tu ex de vez en cuando',
          b: 'Cerrar para siempre con pena',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Un morreo con quien tienes a la izquierda',
          b: 'Un lento sensual con quien está a tu derecha',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Dormir desnudo con un amigo',
          b: 'Ducharte en bañador con tu ex',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Recibir un desnudo de tu jefe',
          b: 'Mandarle uno sin querer',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Sexo de escándalo una vez al mes',
          b: 'Sexo mediocre cada día',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Saber qué piensa el otro en la cama',
          b: 'Que oiga cada pensamiento tuyo',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Un finde con tu amor secreto',
          b: 'Un mes con tu primer amor',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Desayuno en la cama tras la primera noche',
          b: 'Desaparecer antes del amanecer',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Decir tu punto débil en la cama',
          b: 'Imitarlo delante del grupo',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Tatuarte el nombre de tu ex',
          b: 'Gritarlo en el peor momento',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Match con tu ex en una app',
          b: 'Match con tu jefe en una app',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Tu pareja sabe todas tus fantasías',
          b: 'Tú sabes todas las suyas',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Striptease improvisado ahora',
          b: 'Relato picante de tu verano',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Besar a uno del grupo a tu elección',
          b: 'Besar al que elija el grupo',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Historia secreta muy pasional',
          b: 'Historia oficial pero tibia',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Sexo solo en verano',
          b: 'Sexo solo en invierno',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Olvidar todas tus noches locas',
          b: 'Recordar también las peores',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Audio caliente a quien no debías',
          b: 'Recibir uno de tu jefe',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Que lean tus mensajes con tu ex',
          b: 'Que vean tus fotos con tu ex',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Amor a primera vista esta noche',
          b: 'Aventura de una noche hoy',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Decir el nombre de tu crush al grupo',
          b: 'Que el grupo lo adivine',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Un lento con tu ex esta noche',
          b: 'Karaoke romántico con uno del grupo',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Tirarle la caña a un desconocido ya',
          b: 'Dar tu número al primero que lo pida',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Un masaje de alguien del grupo',
          b: 'Hacérselo tú a alguien del grupo',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Prohibido flirtear un año',
          b: 'Obligado a flirtear con todos',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Una noche con tu ídolo musical',
          b: 'Un finde con tu actor favorito',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Confesar un sueño caliente con un presente',
          b: 'Que un presente lo confiese de ti',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Silencio total en la cama',
          b: 'Narración completa en la cama',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Un culo de escándalo',
          b: 'Un escote de aplauso',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Tu ex se vuelve famosísimo',
          b: 'Tu ex se vuelve tu jefe',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Decir qué te excita más',
          b: 'Decir qué te corta el rollo',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Un lío de verano nunca confesado',
          b: 'Un amor a distancia infinito',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Dos presentes te tiran la caña',
          b: 'Tirársela tú a dos a la vez',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Ver a tu ex con alguien mejor que tú',
          b: 'Que te vea con alguien peor',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Besos con mordisco',
          b: 'Besos de piquito para siempre',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Dormir abrazados sin sexo',
          b: 'Sexo sin dormir juntos nunca',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Sexo con la música a todo volumen',
          b: 'Con el telediario de fondo',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Revelar tu número de ex',
          b: 'Revelar quién fue el mejor',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Tirarle la caña al camarero hoy',
          b: 'Dejarle tu número en el recibo',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Primera vez torpe pero dulce',
          b: 'Perfecta pero con quien no debías',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Un tatuaje donde decida el grupo',
          b: 'Un piercing donde decida el grupo',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Un beso de 30 segundos con un presente',
          b: 'Diez besos rápidos con diez extraños',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Saber quién del grupo sueña contigo',
          b: 'Saber quién no te besaría nunca',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Sexo en tienda en un camping lleno',
          b: 'En un hotel de paredes de papel',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Vacaciones solo para solteros',
          b: 'Vacaciones solo para parejas',
          tone: ContentTone.piccante,
        ),
        (a: 'Tragar', b: 'Escupir', tone: ContentTone.cattivo),
        (
          a: 'Un trío con dos desconocidos',
          b: 'Ver a tu pareja con otro',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Solo sexo oral un año',
          b: 'Nunca más sexo oral',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Sexo anal',
          b: 'Solo sexo vaginal para siempre',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Dominar siempre en la cama',
          b: 'Someterte siempre',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Atada y con los ojos vendados',
          b: 'Atar tú y vendar a tu pareja',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Correrte en 30 segundos',
          b: 'Aguantar una hora sin correrte',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Orgasmo negado toda la noche',
          b: 'Un solo orgasmo rapidísimo',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Sexo con juguetes',
          b: 'Sexo solo con las manos',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Un vibrador toda la tarde',
          b: 'Unas esposas toda la noche',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Grabar un vídeo casero',
          b: 'Hacer fotos desnudos',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Sexo en un baño público',
          b: 'Sexo en el coche aparcado',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Que te den unos azotes',
          b: 'Dar tú los azotes',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Mordiscos por todo el cuerpo',
          b: 'Arañazos en la espalda',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Cera caliente sobre la piel',
          b: 'Hielo sobre la piel',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Ser el juguete de tu pareja',
          b: 'Que tu pareja sea el tuyo',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Sexo oral hasta acabar',
          b: 'Penetración hasta acabar',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Dejar que te aten a la cama',
          b: 'Atar a tu pareja a la cama',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Un consolador grande',
          b: 'Un vibrador pequeño pero potente',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Sexo en la ducha',
          b: 'Sexo en la mesa de la cocina',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Recibir una mamada',
          b: 'Recibir un cunnilingus',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Solo sexo por la mañana',
          b: 'Solo sexo de madrugada',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Un trío con dos hombres',
          b: 'Un trío con dos mujeres',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Ver porno con tu pareja',
          b: 'Grabar el vuestro propio',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Sexo con una máscara puesta',
          b: 'Sexo con los ojos vendados',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Que te tiren del pelo',
          b: 'Que te aprieten el cuello suave',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Sexo tántrico de dos horas',
          b: 'Un polvo rápido y salvaje',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Sentarte encima',
          b: 'Que se sienten encima de ti',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Sexo delante de un espejo',
          b: 'Sexo grabado con el móvil',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Provocar durante horas sin tocar',
          b: 'Ir directos al grano',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Sexo en la playa de noche',
          b: 'Sexo en el bosque de día',
          tone: ContentTone.cattivo,
        ),
        (a: 'Un plug anal', b: 'Unas bolas chinas', tone: ContentTone.cattivo),
        (
          a: 'Sexo con la ropa aún puesta',
          b: 'Desnudos del todo desde el inicio',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Que te laman de arriba abajo',
          b: 'Lamer tú de arriba abajo',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Sexo en casa de amigos',
          b: 'Sexo en el ascensor',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Un rol de jefa y becario',
          b: 'Un rol de médico y paciente',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Que te esposen a la cama',
          b: 'Esposar tú a tu pareja',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Sexo rudo sin preliminares',
          b: 'Preliminares eternos sin sexo',
          tone: ContentTone.cattivo,
        ),
        (a: 'Correrte dentro', b: 'Correrte fuera', tone: ContentTone.cattivo),
        (
          a: 'Que te susurren guarradas',
          b: 'Silencio total en la cama',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Un masaje que acaba en sexo',
          b: 'Sexo que empieza sin avisar',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Sexo en un probador de tienda',
          b: 'Sexo en el trabajo',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Que te venden y te toquen',
          b: 'Vendar y tocar tú',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Un juego de rol de desconocidos',
          b: 'Un juego de amos y sumisos',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Sexo con música a tope',
          b: 'Sexo en absoluto silencio',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Que te hagan un striptease',
          b: 'Hacer tú el striptease',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Sexo con lencería puesta',
          b: 'Sexo con tacones y nada más',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Que te muerdan el cuello',
          b: 'Que te besen todo el cuerpo',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Un látigo suave',
          b: 'Una fusta de cuero',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Sexo por videollamada',
          b: 'Sexted todo el día',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Que te dominen por completo',
          b: 'Dominar tú por completo',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Sexo en un hotel de lujo',
          b: 'Sexo en una tienda de campaña',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Aguantar sin gemir',
          b: 'Gritar sin control',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Que te aten las muñecas',
          b: 'Atar tú las muñecas',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Sexo con aceites por todo el cuerpo',
          b: 'Sexo bajo el agua',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Un orgasmo múltiple',
          b: 'Uno solo pero intensísimo',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Que te digan qué hacer',
          b: 'Dar tú las órdenes',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Sexo rápido en el balcón',
          b: 'Sexo lento en la azotea',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Que te pongan un collar',
          b: 'Ponerlo tú a tu pareja',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Sexo con dos personas a la vez',
          b: 'Solo con una toda la noche',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Que te desnuden despacio',
          b: 'Arrancarte la ropa deprisa',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Una noche de bondage',
          b: 'Una noche de juguetes',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Sexo mirándote a los ojos',
          b: 'Sexo por detrás',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Que te aten los tobillos',
          b: 'Atarte las manos a la espalda',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Provocar a tu pareja en público',
          b: 'Que te provoquen a ti en público',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Sexo en el probador de un gym',
          b: 'Sexo en la piscina',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Que te tapen la boca',
          b: 'Tapar tú la boca a tu pareja',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Un fin de semana solo de sexo',
          b: 'Un mes sin tocaros nada',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Que te penetren con juguete',
          b: 'Penetrar tú con juguete',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Sexo con esposas de peluche',
          b: 'Sexo con cuerdas de verdad',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Que te hagan acabar con la boca',
          b: 'Acabar tú con las manos',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Un rol de profesora severa',
          b: 'Un rol de enfermera traviesa',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Sexo en la escalera del edificio',
          b: 'Sexo en el garaje',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Que te ordenen no correrte',
          b: 'Correrte cuando quieras',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Un beso perfecto al mes',
          b: 'Besos mediocres cada día',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Saber qué piensa tu crush de ti',
          b: 'Que sepa todo lo que piensas tú',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Una noche inolvidable sin más',
          b: 'Diez citas monas sin chispa',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Dormir abrazados y nada más',
          b: 'Todo lo demás pero sin mimos',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Decirle tu body count a tu crush',
          b: 'Mostrar tu último chat con tu ligue',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Pareja que besa de maravilla',
          b: 'Pareja que escribe de maravilla',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Flirtear delante de tus padres',
          b: 'Flirtear delante de tu ex',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Recibir una foto atrevida por error',
          b: 'Mandarla tú a quien no debías',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Que te seduzcan con palabras',
          b: 'Que te seduzcan con la mirada',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Finde de pasión sin móvil',
          b: 'Semana de flirteo solo por chat',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Primer beso en la primera cita',
          b: 'Primer beso tras un mes de espera',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Saber siempre quién te mira en un bar',
          b: 'No saberlo pero que te miren mucho',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Un ex que te escribe cada noche',
          b: 'Un crush que nunca te escribe',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Un lento con tu crush ante todos',
          b: 'Cena romántica en silencio total',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Que el grupo lea tu chat con tu crush',
          b: 'Llamarla ahora en manos libres',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Un masaje perfecto cada noche',
          b: 'Desayuno en la cama cada mañana',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Ser el mejor beso de alguien',
          b: 'Recibir el mejor beso de tu vida',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Nunca más primeras citas',
          b: 'Solo primeras citas para siempre',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Decir "me gustas" siempre primero',
          b: 'Esperar siempre a que lo digan',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Una playlist que suena si flirteas',
          b: 'Una voz que narra tus citas',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Tu ex en tu boda',
          b: 'Tu suegra en tu luna de miel',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Volver a ver en vídeo tu primer beso',
          b: 'Mostrar al grupo tu perfil de citas',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Congelarte con cada "tenemos que hablar"',
          b: 'No oírlo nunca en la vida',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Un flirteo de verano cada año',
          b: 'Un amor de verdad cada diez años',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Saber cuántas veces hablaron de ti',
          b: 'Saber qué dijeron pero no quién',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Besos solo bajo la lluvia',
          b: 'Besos solo en el ascensor',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Un "buenos días" de quien te importa',
          b: 'Un "buenas noches" cada noche',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Perder la voz cuando flirteas',
          b: 'Decir siempre una palabra de más',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Ser irresistible solo de día',
          b: 'Ser irresistible solo de noche',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Una cita a ciegas elegida por el grupo',
          b: 'Una cita organizada por tu ex',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Cenar con la pareja de tu crush',
          b: 'Hacerles de chófer toda la noche',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Saber cuándo mienten por amor',
          b: 'No mentir nunca tú primero',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Un año sin besos',
          b: 'Un año sin abrazos',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Confesar tu crush a esa persona',
          b: 'Confesarla a toda esta sala ya',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Ser famoso por una historia de amor',
          b: 'Ser famoso por una calabaza épica',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Salir con alguien idéntico a ti',
          b: 'Salir con tu opuesto exacto',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Tu diario leído por tu crush',
          b: 'Tu historial leído por tus padres',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Un beso robado inolvidable',
          b: 'Cien besos pedidos con permiso',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Parecer siempre desinteresado',
          b: 'Parecer siempre demasiado ansioso',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Amor a primera vista una sola vez',
          b: 'Flechazos que nunca te corresponden',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Flores en la oficina cada semana',
          b: 'Un audio romántico cada noche',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Flirtear genial solo por escrito',
          b: 'Flirtear genial solo en persona',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Un crush por un amigo de este grupo',
          b: 'Un crush por alguien del trabajo',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Saber si la primera cita irá bien',
          b: 'Poder repetir cada primera cita',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Cita romántica planeada al minuto',
          b: 'Improvisación total cada vez',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Una pareja que baila genial',
          b: 'Una pareja que cocina genial',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Cero celos para siempre',
          b: 'Doble pasión pero con celos',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Que dos personas te cortejen',
          b: 'Elegir tú pero sin ser cortejado',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Tu nombre en una canción de amor',
          b: 'Tu cara en un vídeo romántico viral',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Solo citas en el desayuno',
          b: 'Solo citas a medianoche',
          tone: ContentTone.piccante,
        ),
        (
          a: 'De la mano en público siempre',
          b: 'Cariño solo en privado pero intenso',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Olvidar a todos tus ex',
          b: 'Que todos tus ex te olviden',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Un beso de peli una vez al año',
          b: 'Besos normales pero cada día',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Declararte con una carta a mano',
          b: 'Declararte ante todo el mundo',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Saber el día en que te enamorarás',
          b: 'Saber solo el nombre y no cuándo',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Pareja susceptible pero pasional',
          b: 'Pareja zen pero tibia',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Revivir tu primer amor',
          b: 'Conocer de antemano el último',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Pasar por tímido al flirtear',
          b: 'Pasar por descarado siendo tímido',
          tone: ContentTone.piccante,
        ),
        (
          a: 'La verdad de por qué acabó cada amor',
          b: 'No saberlo pero cerrar en paz',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Una cita perfecta organizada por tu ex',
          b: 'Un desastre con la persona ideal',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Gustar a todos menos a tu crush',
          b: 'Gustar solo a tu crush y a nadie más',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Mensajes leídos siempre al momento',
          b: 'Respuesta garantizada en un minuto',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Retirar un mensaje al día',
          b: 'Leer los mensajes borrados por otros',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Flirteo descarado solo los martes',
          b: 'Flirteo suave todos los días',
          tone: ContentTone.piccante,
        ),
        (
          a: 'El grupo elige tu próxima cita',
          b: 'El grupo lee el chat de la última',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Que te bese sin avisar quien te gusta',
          b: 'Anunciar cada beso diez segundos antes',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Un verano de soltero legendario',
          b: 'Un invierno en pareja perfecto',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Tu crush ve todas tus historias',
          b: 'Tú ves todo lo que ella mira',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Un lento con quien no debías',
          b: 'Ningún lento nunca más',
          tone: ContentTone.piccante,
        ),
        (
          a: 'Ver a tu pareja masturbarse',
          b: 'Que te vean a ti hacerlo',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Sexo con antifaz de encaje',
          b: 'Sexo con las luces encendidas',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Que te aten a una silla',
          b: 'Atar tú a alguien a una silla',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Una orgía pequeña',
          b: 'Un intercambio de parejas',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Que te chupen los dedos',
          b: 'Chupar tú los dedos',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Sexo en un tren nocturno',
          b: 'Sexo en un avión',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Que te den nalgadas fuertes',
          b: 'Dar tú nalgadas fuertes',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Un juego de sumisión toda la noche',
          b: 'Una noche mandando tú',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Sexo con lubricante caliente',
          b: 'Sexo con lubricante frío',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Que te aten y te provoquen',
          b: 'Atar y provocar tú',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Sexo en la oficina vacía',
          b: 'Sexo en el almacén',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Que te obliguen a esperar',
          b: 'Tomarlo cuando te apetezca',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Recibir sexo oral con hielo',
          b: 'Dar sexo oral con menta',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Un rol de amo estricto',
          b: 'Un rol de sumiso obediente',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Sexo con las manos atadas',
          b: 'Sexo con los ojos tapados',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Que te dejen al borde y paren',
          b: 'Llegar hasta el final sin parar',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Un trío con tu mejor amigo',
          b: 'Un trío con un desconocido',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Sexo con vibrador a distancia',
          b: 'Sexo con esposas y venda',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Que te desnuden en un juego',
          b: 'Desnudar tú a alguien jugando',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Sexo salvaje contra la pared',
          b: 'Sexo suave sobre la alfombra',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Que te muerdan los muslos',
          b: 'Morder tú los muslos',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Un show privado para tu pareja',
          b: 'Que te hagan un show a ti',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Sexo con disfraz puesto',
          b: 'Sexo con solo una máscara',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Que te aten y te abaniquen con pluma',
          b: 'Usar tú la pluma',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Sexo en la terraza de noche',
          b: 'Sexo en el jacuzzi',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Que te digan guarradas al oído',
          b: 'Decirlas tú al oído',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Un orgasmo arruinado a propósito',
          b: 'Un orgasmo completo garantizado',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Que te dominen con la voz',
          b: 'Dominar tú con la voz',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Sexo con dos juguetes a la vez',
          b: 'Sexo solo con lengua y dedos',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Que te aten y no puedas tocarles',
          b: 'Tocar tú sin que te toquen',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Sexo en un callejón oscuro',
          b: 'Sexo en el mirador del coche',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Que te pongan un tapón vibrador',
          b: 'Ponerlo tú a tu pareja',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Un rol de secuestro consentido',
          b: 'Un rol de cita a ciegas',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Sexo con crema batida',
          b: 'Sexo con chocolate derretido',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Que te aten boca abajo',
          b: 'Que te aten boca arriba',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Sexo en la cocina de una fiesta',
          b: 'Sexo en el baño de un bar',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Que te controlen el placer con app',
          b: 'Controlar tú con la app',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Recibir mientras estás atada',
          b: 'Dar mientras te atan a ti',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Un rol de masajista indecente',
          b: 'Un rol de vecino atrevido',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Sexo con plumas y cera',
          b: 'Sexo con hielo y esposas',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Que te prohíban gemir',
          b: 'Que te obliguen a gemir alto',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Sexo en un banco del parque',
          b: 'Sexo en la escalera de incendios',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Que te aten con corbatas',
          b: 'Atar tú con corbatas',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Un juego de castigos y premios',
          b: 'Un juego de dados eróticos',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Sexo con antifaz y esposas',
          b: 'Sexo con cuerda y mordaza',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Que te dejen desnuda esperando',
          b: 'Esperar tú a tu pareja desnudo',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Sexo rápido antes de salir',
          b: 'Sexo maratón al volver',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Que te succionen con juguete',
          b: 'Usar tú el juguete succionador',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Un trío planeado con reglas',
          b: 'Un trío espontáneo sin reglas',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Sexo con las luces de colores',
          b: 'Sexo solo con velas',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Que te aten y te hagan cosquillas',
          b: 'Hacer tú las cosquillas atándoles',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Sexo en el probador de una boutique',
          b: 'Sexo en la cabina de fotos',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Que te den órdenes por mensaje',
          b: 'Dar tú las órdenes por mensaje',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Recibir un masaje con final feliz',
          b: 'Darlo tú con final feliz',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Un rol de dueña y mascota',
          b: 'Un rol de entrenadora y novato',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Sexo con arnés y juguete',
          b: 'Sexo con esposas y fusta',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Que te dejen atada toda la peli',
          b: 'Atar tú durante toda la peli',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Sexo en la parte de atrás del cine',
          b: 'Sexo en el último vagón',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Que te venden y te alimenten fresas',
          b: 'Vendar tú y alimentar a tu pareja',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Un orgasmo por sorpresa',
          b: 'Un orgasmo tras horas de espera',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Que te dominen desde otra sala',
          b: 'Dominar tú por videollamada',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Sexo con vela y aceite templado',
          b: 'Sexo con menta y hielo',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Que te aten al cabecero',
          b: 'Atar tú a alguien al cabecero',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Un rol de jefa exigente',
          b: 'Un rol de alumna castigada',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Sexo con música lenta y velas',
          b: 'Sexo con reguetón a todo volumen',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Que te controlen con palabra segura',
          b: 'Controlar tú con palabra segura',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Recibir placer sin poder moverte',
          b: 'Dar placer mientras te inmovilizan',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Sexo con dos vendas y sin manos',
          b: 'Sexo con esposas y tacones',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Que te lleven al límite tres veces',
          b: 'Acabar a la primera sin pausa',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Un juego de verdad o atrevimiento hot',
          b: 'Una ruleta de posturas al azar',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Sexo en un after de madrugada',
          b: 'Sexo al amanecer en la playa',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Que te aten y te lean fantasías',
          b: 'Leer tú las fantasías atándoles',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Provocar bajo la mesa en una cena',
          b: 'Que te provoquen a ti bajo la mesa',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Que te obliguen a pedirlo',
          b: 'Pedirlo tú entre súplicas',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Un final con la boca',
          b: 'Un final con las manos',
          tone: ContentTone.cattivo,
        ),
        (
          a: 'Que te aten y te dejen desear más',
          b: 'Dejar tú a tu pareja deseando más',
          tone: ContentTone.cattivo,
        ),
      ];
}
