import '../content_tone.dart';

/// Coppie di "Preferisci" in inglese: parità completa col mazzo italiano.
class PreferisciPoolEn {
  const PreferisciPoolEn._();

  static const List<({String a, String b})> pairs = <({String a, String b})>[
    (a: 'Knowing how you will die', b: 'Knowing when'),
    (a: 'An uncomfortable truth', b: 'A comfortable lie'),
    (a: 'More money', b: 'More free time'),
    (a: 'Being famous', b: 'Being invisible to everyone'),
    (a: 'Travelling to the past', b: 'Travelling to the future'),
    (a: 'Being able to fly', b: 'Being invisible'),
    (a: 'Reading minds', b: 'Seeing the future'),
    (a: 'No more social media', b: 'No more films'),
    (a: 'Losing your phone', b: 'Losing your house keys'),
    (a: 'Always 5 minutes early', b: 'Always 10 minutes late'),
    (a: 'A lovely but useless boss', b: 'An awful but brilliant boss'),
    (
      a: 'A big salary and a boring job',
      b: 'A small salary and a job you love',
    ),
    (a: 'A wedding with 200 guests', b: 'A wedding for two'),
    (a: 'A week without going out', b: 'Going out every single night'),
    (a: 'Sleeping 10 hours', b: 'Sleeping 5 hours and feeling amazing'),
    (a: 'Repeating the perfect holiday', b: 'Trying somewhere new'),
    (a: 'Checking your bank balance daily', b: 'Never looking at it'),
    (a: 'A useless but fun superpower', b: 'A useful but boring superpower'),
    (a: 'Re-reading the same book forever', b: 'Never finishing a single one'),
    (a: 'A life with no music', b: 'A life with no cinema'),
    (a: 'Always knowing the truth', b: 'Living happily in the illusion'),
    (a: 'A sabbatical year', b: 'Retiring one year early'),
    (a: 'Speaking every language', b: 'Playing every instrument'),
    (a: 'Never feeling embarrassment', b: 'Never feeling fear'),
    (a: 'Reliving your best day', b: 'Erasing your worst one'),
    (
      a: 'Moving in together after a month',
      b: 'Moving in together after years',
    ),
    (a: 'Kids early', b: 'Kids late'),
    (
      a: 'A holiday planned down to the minute',
      b: 'Setting off on an adventure',
    ),
    (a: 'A whole season in one night', b: 'One episode a week'),
    (a: 'Battery always on 1%', b: 'Painfully slow internet'),
    (
      a: 'Clothes that are always slightly damp',
      b: 'A pebble in your shoe forever',
    ),
    (a: 'Always saying what you think', b: 'Never speaking again'),
    (a: 'No heating in winter', b: 'No air conditioning in summer'),
    (a: 'Hiccups for life', b: 'Sneezing every two minutes'),
    (
      a: 'Your favourite dish at every meal',
      b: 'Never your favourite dish again',
    ),
    (a: 'Never needing sleep again', b: 'Never needing food again'),
    (a: 'Rich but with no friends', b: 'Broke but adored'),
    (a: 'Never paying rent again', b: 'Double your salary'),
    (
      a: 'The funniest person in the room',
      b: 'The smartest person in the room',
    ),
    (a: 'A photographic memory', b: 'Forgetting every embarrassing moment'),
    (a: 'No more queues', b: 'No more traffic'),
    (a: 'Shaved eyebrows for a year', b: 'Neon green hair for a year'),
    (a: 'Losing your sense of smell', b: 'Losing your sense of taste'),
    (a: 'A cartoon voice', b: 'A laugh that embarrasses everyone'),
    (
      a: 'Your parents seeing your search history',
      b: 'Your boss reading your chats',
    ),
    (a: 'Burping at the end of every sentence', b: 'Laughing like a goat'),
    (a: 'Using a stranger\'s toothbrush', b: 'Drinking from their used glass'),
    (a: 'Permanently sweaty palms', b: 'Permanently chapped lips'),
    (a: 'Dating your ex', b: 'Dating your best friend\'s ex'),
    (a: 'Loud but odourless farts', b: 'Silent but deadly ones'),
    (a: 'Forgetting who you are', b: 'Being forgotten by everyone'),
    (a: 'Losing all your money', b: 'Losing all your memories'),
    (a: 'A rich but boring partner', b: 'A broke but hilarious partner'),
    (
      a: 'An hour in a lift with your ex',
      b: 'An hour in a lift with your boss',
    ),
    (
      a: 'Everyone forgetting your birthday',
      b: 'An embarrassing surprise party',
    ),
    (
      a: 'Your secret revealed to everyone',
      b: 'Knowing everyone else\'s secrets',
    ),
    (a: 'Famous but hated', b: 'Unknown but loved'),
    (a: 'Never laughing again', b: 'Never crying again'),
    (
      a: 'Going back to school for a year',
      b: 'Resitting your final exams every year',
    ),
    (a: 'Living in a horror film', b: 'Living in a musical'),
    (a: 'Feet instead of hands', b: 'Hands instead of feet'),
    (
      a: 'Fighting one duck the size of a horse',
      b: 'A hundred horses the size of ducks',
    ),
    (a: 'Living underwater', b: 'Living in space'),
    (
      a: 'A killer snail chasing you for life',
      b: 'A clown staring at you every night',
    ),
    (a: 'Talking to animals', b: 'Controlling the weather'),
    (a: 'Dancing whenever music plays', b: 'Crying whenever someone laughs'),
    (
      a: 'Every morning in a different country',
      b: 'Never leaving your city again',
    ),
    (a: 'Living in a video game', b: 'Living in a cartoon'),
    (a: 'A "pause" button for life', b: 'A "rewind" button for life'),
    (
      a: 'Teleporting but always losing your shoes',
      b: 'Flying at walking pace',
    ),
    (a: 'Living 1000 years', b: 'Ten lives of 100 years each'),
    (a: 'Raining tacos', b: 'Snowing ice cream'),
    (a: 'King of the world for one day', b: 'An ordinary person forever'),
    (
      a: 'Knowing everything but feeling nothing',
      b: 'Feeling everything but understanding nothing',
    ),
    (a: 'Erasing one regret', b: 'Guaranteeing one future success'),
    (a: 'Always hungry', b: 'Always sleepy'),
    (
      a: 'A tail that wags when you are happy',
      b: 'Ears that droop when you are sad',
    ),
    (a: 'Giving up coffee forever', b: 'Giving up chocolate'),
    (
      a: 'A nose that grows when you lie',
      b: 'Hair that changes colour with your mood',
    ),
    (a: 'Finding the love of your life', b: 'Finding your dream job'),
    (a: 'Filthy rich but always sad', b: 'Broke but always happy'),
    (a: 'A million right now', b: '3,000 euros a month for life'),
    (a: 'Saving your dog', b: 'Saving a stranger'),
    (a: 'Never being able to lie', b: 'Believing every lie'),
    (a: 'Always right but alone', b: 'Wrong but in good company'),
    (a: 'A misunderstood genius', b: 'A happy simpleton'),
    (a: 'The same outfit every day', b: 'Never repeating an outfit'),
    (a: 'Singing everything you say', b: 'Only walking backwards'),
    (a: 'Free Wi-Fi everywhere for life', b: 'Free flights for life'),
    (a: 'Only scalding hot food', b: 'Only freezing cold food'),
    (a: 'Never pizza again', b: 'Never pasta again'),
    (a: 'Never drinks with friends again', b: 'Never takeaway again'),
    (a: 'A long life full of regrets', b: 'A short life with none'),
    (
      a: 'Loving without being loved back',
      b: 'Being loved by someone you do not love',
    ),
    (a: 'Your partner reads your thoughts', b: 'You read theirs'),
    (
      a: 'A partner chosen by your friends',
      b: 'A partner chosen by an algorithm',
    ),
    (
      a: 'Always knowing when someone lies to you',
      b: 'Never getting caught when you lie',
    ),
    (a: 'Being 18 forever', b: 'Skipping straight to 40'),
    (
      a: 'Always sleeping at other people\'s places',
      b: 'Always having guests at yours',
    ),
    (
      a: 'Your favourite band\'s concert all alone',
      b: 'A festival with friends but music you hate',
    ),
    (
      a: 'Singing karaoke off-key in front of everyone',
      b: 'Dancing alone on the dance floor for an hour',
    ),
    (a: 'Losing all the photos on your phone', b: 'Losing all your chats'),
    (a: 'Sneezing confetti', b: 'Burping soap bubbles'),
    (a: 'Having four arms', b: 'Having four legs'),
    (a: 'Being 2 metres 20 tall', b: 'Being 1 metre 20 tall'),
    (a: 'Living without summer', b: 'Living without winter'),
    (a: 'Saving five strangers', b: 'Saving your best friend'),
    (
      a: 'A million but no smartphone ever again',
      b: 'No money but with your phone',
    ),
    (a: 'Your dream job abroad', b: 'A boring job close to your friends'),
    (a: 'Being 25 forever', b: 'Growing old with your friends'),
    (
      a: 'Your dream house in the middle of nowhere',
      b: 'A studio flat right in the centre',
    ),
    (
      a: 'Knowing what they say behind your back',
      b: 'Living peacefully without knowing',
    ),
    (a: 'Every meal cooked by a chef', b: 'A personal driver for life'),
    (
      a: 'Narrating out loud everything you do',
      b: 'Hearing the voice-over of your own life',
    ),
    (a: 'Walking on Lego every morning', b: 'A freezing shower every morning'),
    (
      a: 'A mosquito in your room every night',
      b: 'A fly on your plate at every meal',
    ),
    (a: 'Autocorrect gone mad for life', b: 'No more emojis ever'),
    (
      a: 'Calls only on speakerphone',
      b: 'Your screen always visible to everyone',
    ),
    (
      a: 'Your dog talks but criticises you',
      b: 'Your mirror pays you fake compliments',
    ),
    (a: 'A million just for you', b: 'A hundred thousand each for the group'),
    (a: 'Always underrated', b: 'Always overrated'),
    (
      a: 'Rediscovering your favourite series',
      b: 'Seeing every finale in advance',
    ),
    (a: 'Only speaking by shouting', b: 'Only speaking in a whisper'),
    (a: 'Always laughing at serious moments', b: 'Crying at every comedy'),
    (
      a: 'Always eating with your hands',
      b: 'Eating everything with a teaspoon',
    ),
    (
      a: 'Your dreams projected to your friends',
      b: 'Your friends reading your diary',
    ),
    (
      a: 'The only single one in the group forever',
      b: 'The first in the group to marry',
    ),
    (a: 'Being reborn in the \'80s', b: 'Being born in 2050'),
    (
      a: 'Free restaurants but always alone',
      b: 'Always paying but in good company',
    ),
    (a: 'Going viral for an epic embarrassment', b: 'Never more than 10 likes'),
    (a: 'Only water forever', b: 'Never water again, only fizzy drinks'),
    (a: 'One music genre for life', b: 'One single app on your phone'),
    (a: 'A tuxedo on the beach', b: 'Swimwear at a wedding'),
    (a: 'Cooking like a starred chef', b: 'A house that cleans itself'),
    (
      a: 'A long flight next to a chatterbox',
      b: 'A long flight next to a newborn',
    ),
    (a: 'Savoury breakfast forever', b: 'Sweet dinner forever'),
    (a: 'Living without mirrors', b: 'Living without clocks'),
    (a: 'Reliving the same Monday', b: 'Skipping every Friday'),
    (a: 'Talking to plants', b: 'Understanding babies'),
    (a: 'Always winning at cards', b: 'Always finding a parking space'),
    (a: 'A 40 degree summer with no sea', b: 'A freezing winter with no snow'),
    (
      a: 'Only terribly dubbed films',
      b: 'Only films with out-of-sync subtitles',
    ),
    (a: 'Free coffee for life', b: 'Free ice cream for life'),
    (a: 'Moving house every year', b: 'The same house forever'),
    (
      a: 'An embarrassing ringtone forever',
      b: 'An embarrassing wallpaper forever',
    ),
    (a: 'Being a famous meme', b: 'Having a famous lookalike'),
    (
      a: 'Dancing the macarena at every greeting',
      b: 'Greeting everyone with a bow',
    ),
    (a: 'Chocolate spread without bread', b: 'Bread without chocolate spread'),
    (
      a: 'An endless weekend of constant rain',
      b: 'Only Mondays but always sunny',
    ),
    (
      a: 'One dish cooked to perfection',
      b: 'Cooking everything just about okay',
    ),
    (a: 'A one-way trip to Mars', b: 'Never leaving the country again'),
    (
      a: 'Sleeping in a tent every night',
      b: 'Sleeping on the sofa every night',
    ),
    (a: 'A robot butler', b: 'A robot cook'),
    (a: 'No more lifts', b: 'No more escalators'),
    (a: 'Knowing every Hollywood gossip', b: 'Knowing every TV series ending'),
    (a: 'Only spicy food for a year', b: 'Never salt again'),
    (a: 'Living without music', b: 'Living without films'),
    (a: 'Always five minutes late', b: 'Always an hour early'),
    (
      a: 'Dancing brilliantly to one song only',
      b: 'Dancing just okay to any song',
    ),
    (a: 'Eternal summer', b: 'Eternal winter'),
    (a: 'Never fried food again', b: 'Never dessert again'),
    (a: 'Reading dogs\' minds', b: 'Talking to cats'),
    (a: 'Always picking the fastest queue', b: 'Always picking the right lift'),
    (a: 'A house in the mountains', b: 'A house by the sea'),
    (a: 'Reliving the same perfect day', b: 'A new but unpredictable day'),
    (a: 'Slow Wi-Fi forever', b: 'Battery always at ten per cent'),
    (a: 'Being invisible one hour a day', b: 'Flying ten minutes a day'),
    (a: 'Only cold showers', b: 'Only slow stopping trains'),
    (a: 'Cooking for ten every evening', b: 'Washing up for ten every evening'),
    (
      a: 'A heavy backpack with everything you need',
      b: 'A light one but never the right thing',
    ),
    (
      a: 'Terrible photos but perfect memories',
      b: 'Perfect photos but hazy memories',
    ),
    (a: 'Compulsory karaoke once a week', b: 'A public speech once a month'),
    (
      a: 'An embarrassing human butler',
      b: 'A robot that judges you in silence',
    ),
  ];

  /// Dilemmi da modalità Hot: parità completa col mazzo italiano.
  static const List<({String a, String b, String tone})>
  hot = <({String a, String b, String tone})>[
    (
      a: 'Walking around naked for a minute',
      b: 'Kissing someone in this group',
      tone: ContentTone.piccante,
    ),
    (
      a: 'A night with someone in the group',
      b: 'A night with an old teacher of yours',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Showing the group your gallery',
      b: 'Having your chats read out loud',
      tone: ContentTone.piccante,
    ),
    (
      a: 'A year without sex',
      b: 'A year without nights out',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Telling the group your body count',
      b: 'Showing your last search',
      tone: ContentTone.piccante,
    ),
    (a: 'Love without sex', b: 'Sex without love', tone: ContentTone.piccante),
    (
      a: 'A gorgeous partner who is awful in bed',
      b: 'An average one who is phenomenal',
      tone: ContentTone.piccante,
    ),
    (
      a: 'A night with your ex',
      b: 'A night with a stranger',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Catching your parents',
      b: 'Being caught by them',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Telling everyone who you fancy right now',
      b: 'Never speaking to them again',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Kissing someone here with your eyes closed',
      b: 'Kissing your ex in front of everyone',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Never kissing again',
      b: 'Never hugging again',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Knowing who your partner would cheat with',
      b: 'Never knowing at all',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Only blind dates for a year',
      b: 'Only dates picked by your mum',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Rewatching your first kiss on video',
      b: 'The whole group rewatching it',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Moaning every time you sit down',
      b: 'Shouting your ex\'s name at every toast',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Sending a nude to your ex by mistake',
      b: 'Sending it to the family group chat',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Sexting your boss by mistake',
      b: 'Calling your partner by your ex\'s name',
      tone: ContentTone.piccante,
    ),
    (
      a: 'One night with a celebrity',
      b: 'A month of sex with your ex',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Sex only in total darkness',
      b: 'Only with the lights full on',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Sharing your weirdest fantasy',
      b: 'Hearing the one from the person on your right',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Friends with benefits with your best friend',
      b: 'No sex at all for a year',
      tone: ContentTone.piccante,
    ),
    (
      a: 'An ex who kisses like a god',
      b: 'Someone new who needs full training',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Being undressed with a look at the bar',
      b: 'Never being noticed again',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Telling us your worst date',
      b: 'Reliving your steamiest embarrassment',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Always making the first move',
      b: 'Always waiting for the other person',
      tone: ContentTone.piccante,
    ),
    (
      a: 'A threesome with strangers',
      b: 'A threesome with friends',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Catching your flatmate in the act',
      b: 'Being caught by your flatmate',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Saying how often you think about it daily',
      b: 'Saying when you last did it',
      tone: ContentTone.piccante,
    ),
    (
      a: 'A super jealous but red-hot partner',
      b: 'A relaxed but lazy one in bed',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Kissing the first person through the door',
      b: 'Kissing the last person who texted you',
      tone: ContentTone.piccante,
    ),
    (
      a: 'A night of passion with no kissing',
      b: 'Endless kissing but nothing else',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Forgetting your first time',
      b: 'Remembering it every single day',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Naming the most absurd place you have done it',
      b: 'Naming the place you would love to',
      tone: ContentTone.piccante,
    ),
    (
      a: 'A fling with your personal trainer',
      b: 'A fling with your doctor',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Only one night stands for a year',
      b: 'Only serious relationships for life',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Hooking up with your ex now and then',
      b: 'Closing the door forever, with regret',
      tone: ContentTone.piccante,
    ),
    (
      a: 'A snog with the person on your left',
      b: 'A sensual slow with the person on your right',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Sleeping naked next to a friend',
      b: 'Showering in swimwear with your ex',
      tone: ContentTone.piccante,
    ),
    (
      a: 'An unsolicited nude from your boss',
      b: 'Sending one to your boss by mistake',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Mind-blowing sex once a month',
      b: 'Mediocre sex every day',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Knowing what they think in bed',
      b: 'Them hearing your every thought in bed',
      tone: ContentTone.piccante,
    ),
    (
      a: 'A weekend with your secret crush',
      b: 'A month with your first love',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Breakfast in bed after the first night',
      b: 'Vanishing before dawn',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Naming your weak spot in bed',
      b: 'Miming it in front of the group',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Tattooing your ex\'s name',
      b: 'Shouting their name at the wrong moment',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Matching with your ex on an app',
      b: 'Matching with your boss on an app',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Your partner knows your every fantasy',
      b: 'You know every one of theirs',
      tone: ContentTone.piccante,
    ),
    (
      a: 'An improvised striptease right now',
      b: 'A spicy tale of your summer',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Kissing someone here of your choosing',
      b: 'Kissing one chosen by the group',
      tone: ContentTone.piccante,
    ),
    (
      a: 'A secret, wildly passionate affair',
      b: 'An official but lukewarm relationship',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Sex only in summer',
      b: 'Sex only in winter',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Forgetting every wild night you have had',
      b: 'Remembering even the ones best forgotten',
      tone: ContentTone.piccante,
    ),
    (
      a: 'A spicy voice note sent to the wrong person',
      b: 'Receiving one from your boss',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Letting us read your chats with your ex',
      b: 'Letting us see your photos with your ex',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Love at first sight tonight',
      b: 'A one night adventure tonight',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Telling the group your crush\'s name',
      b: 'Letting the group guess it',
      tone: ContentTone.piccante,
    ),
    (
      a: 'A slow dance with your ex tonight',
      b: 'Romantic karaoke with someone in the group',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Chatting up a stranger right now',
      b: 'Giving your number to the first who asks',
      tone: ContentTone.piccante,
    ),
    (
      a: 'A massage from someone in the group',
      b: 'Giving one to someone in the group',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Flirting banned for a year',
      b: 'Compulsory flirting with everyone',
      tone: ContentTone.piccante,
    ),
    (
      a: 'A night with your music idol',
      b: 'A weekend with your favourite actor',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Confessing a steamy dream about someone here',
      b: 'Someone here confessing one about you',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Total silence in bed',
      b: 'Full live commentary in bed',
      tone: ContentTone.piccante,
    ),
    (
      a: 'A showstopping behind',
      b: 'A neckline worth applause',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Your ex becomes mega famous',
      b: 'Your ex becomes your boss',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Saying what turns you on most',
      b: 'Saying what kills the mood instantly',
      tone: ContentTone.piccante,
    ),
    (
      a: 'A summer affair never confessed',
      b: 'An endless long-distance love',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Two people here chatting you up',
      b: 'Chatting up two people here at once',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Seeing your ex with someone hotter than you',
      b: 'Them seeing you with someone worse than them',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Kisses with a bite',
      b: 'Closed-lip pecks forever',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Sleeping cuddled up with no sex',
      b: 'Sex without ever sleeping together',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Sex with the music blasting',
      b: 'With the news on in the background',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Revealing your number of exes',
      b: 'Revealing which one was the best',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Chatting up the waiter tonight',
      b: 'Leaving your number on the receipt',
      tone: ContentTone.piccante,
    ),
    (
      a: 'An awkward but sweet first time',
      b: 'A perfect one with the wrong person',
      tone: ContentTone.piccante,
    ),
    (
      a: 'A tattoo where the group decides',
      b: 'A piercing where the group decides',
      tone: ContentTone.piccante,
    ),
    (
      a: 'A 30 second kiss with someone here',
      b: 'Ten quick kisses with ten strangers',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Knowing who here dreams about you at night',
      b: 'Knowing who would never kiss you',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Sex in a tent on a packed campsite',
      b: 'In a hotel with paper-thin walls',
      tone: ContentTone.piccante,
    ),
    (
      a: 'A singles-only holiday',
      b: 'A couples-only holiday',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Cheating and never being found out',
      b: 'Being cheated on and never knowing',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'An affair with a friend\'s partner',
      b: 'Your partner with your best friend',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Your worst photos getting out',
      b: 'Your worst chats getting out',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Hearing what the group says about you',
      b: 'The group hearing what you say',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Confessing your worst secret right now',
      b: 'Your best friend revealing it for you',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Sex with your best friend\'s ex',
      b: 'Telling them you have already considered it',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Knowing everything about everyone here',
      b: 'Everyone here knowing everything about you',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'An ex who always comes back',
      b: 'Never hearing from any ex again',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Becoming a couple with someone in the group',
      b: 'Never seeing the group again',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Discovering a betrayal from the past',
      b: 'Confessing one of yours right now',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Reading your partner\'s secret diary',
      b: 'Them reading all your chats',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Knowing who in the group badmouths you',
      b: 'Knowing who has lied to you the most',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'An ex turning up on your first date',
      b: 'A partner who always mentions their ex',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Cheating in a dream and confessing it',
      b: 'Dreaming of your ex nightly and saying nothing',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Knowing your partner\'s true body count',
      b: 'Them discovering your true one',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Kissing your best friend\'s ex',
      b: 'Them kissing yours',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'A night with a colleague\'s partner',
      b: 'Everyone believing you did it anyway',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Finding out your ex always cheated',
      b: 'Finding out they always loved you',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Taking revenge on an ex and regretting it',
      b: 'Forgiving them and regretting it more',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'The group reads your last spicy chat',
      b: 'The group sees your private photos',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Confessing to everyone you have ghosted',
      b: 'Calling whoever ghosted you, right now',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Being dumped by voice note',
      b: 'Dumping someone on their birthday',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Stealing someone\'s partner',
      b: 'Having yours stolen and winning them back',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Knowing every lie your partner has told',
      b: 'Them knowing every one of yours',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Telling the group your worst betrayal',
      b: 'Telling a friend\'s worst secret',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Flirting with your boss\'s partner',
      b: 'Your boss flirting with yours',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'A friend making a move on your partner',
      b: 'A partner making a move on your friend',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Finding an ex\'s gift at their place',
      b: 'Finding chats with the ex on their phone',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Erasing one of your secrets forever',
      b: 'Discovering what they are hiding from you',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Saying who in the group you would never date',
      b: 'Hearing who would never date you',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'An ex you still owe money',
      b: 'An ex who still owes you an apology',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Admitting you stalked your ex',
      b: 'Showing the history of their profiles',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Secret sex at the in-laws\' house',
      b: 'Caught by them at the worst moment',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Your best friend hates you',
      b: 'Your friend loves your partner',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'A one-night betrayal confessed',
      b: 'A parallel affair never discovered',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Answering three questions naked',
      b: 'Answering thirty fully dressed',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Knowing the date your relationship will end',
      b: 'Knowing the reason but not the date',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'A better-looking love rival',
      b: 'A funnier one',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Telling your partner they kiss badly',
      b: 'Marrying them without ever saying it',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Your ex texting you at 3 am',
      b: 'Texting them and denying it forever',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'A partner still friends with all their exes',
      b: 'A partner who bans you from seeing yours',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Finding your partner\'s secret profile',
      b: 'Them finding yours',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Loving two people at once',
      b: 'Being the affair and not knowing it',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Saying who here kisses the worst',
      b: 'Being rated by every person here',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Sabotaging your ex\'s wedding',
      b: 'Being best man at their wedding',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'A public list of your flirts',
      b: 'A list of everyone who rejected you',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Losing a friend by telling the truth',
      b: 'Keeping them by lying for life',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Your enemy knows your secret',
      b: 'Your mother-in-law knows everything about you',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Swapping partners for a week',
      b: 'Living single for a year',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'The group votes on your worst flaw',
      b: 'Hearing them list all your flirts',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Cheating and confessing after ten years',
      b: 'Finding out after ten years',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'A weekend with your in-laws',
      b: 'A weekend with your partner\'s ex',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Knowing how many said no to you',
      b: 'Knowing who regretted saying yes',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Spilling everything about a secret love',
      b: 'The group interrogating you for an hour',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Reading your last message out loud',
      b: 'Calling the last number in your contacts',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Wrecking a couple by telling the truth',
      b: 'Saving them with an enormous lie',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Your ex discussing you on a podcast',
      b: 'The group recounting your worst nights',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Being someone\'s plan B',
      b: 'Having a plan B and getting caught',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Your partner checks your phone',
      b: 'Never being allowed to look at theirs',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Telling the last lie you told someone here',
      b: 'Everyone here telling one about you',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Dating your ex\'s twin',
      b: 'Dating your boss\'s double',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Knowing what your exes say about you',
      b: 'Gathering them all for one dinner',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Cheating for revenge and admitting it',
      b: 'Taking the hit and plotting in silence',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Kissing someone for a bet',
      b: 'Discovering you were the bet',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'A shotgun wedding in a month',
      b: 'Ten years engaged with no wedding',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Stalking your ex\'s night out on social media',
      b: 'Blocking them and dying of curiosity',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Confessing your grubbiest flirt',
      b: 'Someone who was there telling it instead',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'The group knows who you fancy in here',
      b: 'Only the wrong person knows',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Discovering your partner\'s double life',
      b: 'Managing to hide your own',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Breaking up a couple of friends by speaking',
      b: 'Watching them be unhappy and staying silent',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'The group picks your partner',
      b: 'The group picks who you must dump',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Telling the real reason for your last break-up',
      b: 'Hearing your ex\'s version of it',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'A night with two exes at once',
      b: 'A night with your ex and their new love',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Being jealous and being right',
      b: 'Trusting and being betrayed',
      tone: ContentTone.cattivo,
    ),
    // -------------------------------------------- piccante (extra)
    (
      a: 'One perfect kiss a month',
      b: 'Mediocre kisses every day',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Knowing what your crush thinks of you',
      b: 'Them knowing everything you think',
      tone: ContentTone.piccante,
    ),
    (
      a: 'One unforgettable night with no follow-up',
      b: 'Ten lovely dates with no spark',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Sleeping cuddled up and nothing more',
      b: 'Everything else but no cuddles after',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Revealing your body count to your crush',
      b: 'Showing your last chat with your flame',
      tone: ContentTone.piccante,
    ),
    (
      a: 'A partner brilliant at kissing',
      b: 'A partner brilliant at texting',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Flirting in front of your parents',
      b: 'Flirting in front of your ex',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Getting a daring photo from the wrong person',
      b: 'Sending one to the wrong person yourself',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Being seduced with words',
      b: 'Being seduced with a look',
      tone: ContentTone.piccante,
    ),
    (
      a: 'A weekend of passion with no phone',
      b: 'A week of flirting by chat only',
      tone: ContentTone.piccante,
    ),
    (
      a: 'A first kiss on the first date',
      b: 'A first kiss after a month of waiting',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Always knowing who is watching you in a bar',
      b: 'Never knowing but being watched often',
      tone: ContentTone.piccante,
    ),
    (
      a: 'An ex who texts you every night',
      b: 'A crush who never texts you',
      tone: ContentTone.piccante,
    ),
    (
      a: 'A slow with your crush in front of everyone',
      b: 'A candlelit dinner in total silence',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Letting the group read your crush chat',
      b: 'Calling them right now on speaker',
      tone: ContentTone.piccante,
    ),
    (
      a: 'A perfect massage every evening',
      b: 'Breakfast in bed every morning',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Being the best kiss of someone\'s life',
      b: 'Receiving the best kiss of yours',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Never any first dates again',
      b: 'Only first dates forever',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Always saying "I like you" first',
      b: 'Always waiting to hear it first',
      tone: ContentTone.piccante,
    ),
    (
      a: 'A playlist that starts when you flirt',
      b: 'A voice-over narrating your dates',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Your ex at your wedding',
      b: 'Your mother-in-law on your honeymoon',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Rewatching your first kiss on video',
      b: 'Showing the group your dating profile',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Freezing at every "we need to talk"',
      b: 'Never hearing "we need to talk" again',
      tone: ContentTone.piccante,
    ),
    (
      a: 'A summer fling every summer',
      b: 'A true love every ten years',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Knowing how often they talked about you',
      b: 'Knowing what they said but not who',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Kisses only in the rain',
      b: 'Kisses only in lifts',
      tone: ContentTone.piccante,
    ),
    (
      a: 'A "good morning" from the right person daily',
      b: 'A "goodnight" every evening',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Losing your voice whenever you flirt',
      b: 'Always saying one word too many',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Irresistible only by day',
      b: 'Irresistible only by night',
      tone: ContentTone.piccante,
    ),
    (
      a: 'A blind date arranged by the group',
      b: 'A date organised by your ex',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Dinner with your crush\'s partner',
      b: 'Driving the couple around all evening',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Always knowing when someone lies in love',
      b: 'Never being the first to lie yourself',
      tone: ContentTone.piccante,
    ),
    (
      a: 'A year without kisses',
      b: 'A year without hugs',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Confessing the crush to their face',
      b: 'Confessing it to this whole room right now',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Famous for a love story',
      b: 'Famous for an epic rejection',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Dating someone identical to you',
      b: 'Dating your exact opposite',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Your diary read by your crush',
      b: 'Your search history read by your parents',
      tone: ContentTone.piccante,
    ),
    (
      a: 'One stolen kiss you remember forever',
      b: 'A hundred kisses asked for permission',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Always seeming uninterested',
      b: 'Always seeming far too keen',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Love at first sight once in a lifetime',
      b: 'Constant crushes never returned straight away',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Flowers at the office every week',
      b: 'A romantic voice note every evening',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Flirting brilliantly only in writing',
      b: 'Flirting brilliantly only in person',
      tone: ContentTone.piccante,
    ),
    (
      a: 'A crush on a friend in this group',
      b: 'A crush on a colleague you see daily',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Always knowing if a first date will go well',
      b: 'Getting to redo every first date once',
      tone: ContentTone.piccante,
    ),
    (
      a: 'A romantic date planned to the minute',
      b: 'Total improvisation every time',
      tone: ContentTone.piccante,
    ),
    (
      a: 'A partner who dances beautifully',
      b: 'A partner who cooks beautifully',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Zero jealousy forever',
      b: 'Double the passion but jealousy included',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Being courted by two people at once',
      b: 'Always choosing but never being courted',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Your name in a famous love song',
      b: 'Your face in a viral romantic video',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Only breakfast dates',
      b: 'Only midnight dates',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Holding hands in public always',
      b: 'Affection only in private but intense',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Forgetting all your exes',
      b: 'All your exes forgetting you',
      tone: ContentTone.piccante,
    ),
    (
      a: 'A film-worthy kiss once a year',
      b: 'Ordinary kisses but daily',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Declaring your love in a handwritten letter',
      b: 'Declaring it in a speech in front of everyone',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Knowing the exact day you will fall in love',
      b: 'Knowing only the name but not when',
      tone: ContentTone.piccante,
    ),
    (
      a: 'A touchy but passionate partner',
      b: 'A zen but lukewarm one',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Reliving your first love',
      b: 'Knowing your last one in advance',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Coming across as shy when you flirt',
      b: 'Coming across as brazen when you are shy',
      tone: ContentTone.piccante,
    ),
    (
      a: 'The truth about why each relationship ended',
      b: 'Never knowing but ending in peace',
      tone: ContentTone.piccante,
    ),
    (
      a: 'A perfect date organised by your ex',
      b: 'A total disaster but with the right person',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Everyone fancying you except your crush',
      b: 'Only your crush fancying you and nobody else',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Messages always read instantly',
      b: 'Replies guaranteed within a minute',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Unsending one message a day',
      b: 'Reading every message others delete',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Shameless flirting but only on Tuesdays',
      b: 'Light flirting but every day',
      tone: ContentTone.piccante,
    ),
    (
      a: 'The group picks your next date',
      b: 'The group reads the chat from your last one',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Being kissed without warning',
      b: 'Announcing every kiss ten seconds early',
      tone: ContentTone.piccante,
    ),
    (
      a: 'A legendary single summer',
      b: 'A perfect coupled-up winter',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Your crush sees all your stories',
      b: 'You see everything they look at',
      tone: ContentTone.piccante,
    ),
    (
      a: 'A slow dance with the wrong person',
      b: 'No slow dances ever again',
      tone: ContentTone.piccante,
    ),
    // --------------------------------------------- cattivo (extra)
    (
      a: 'Sex only in the dark forever',
      b: 'Only with the lights on forever',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'One single position for life',
      b: 'Every position except your favourite',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Telling the group your wildest fantasy',
      b: 'Showing your incognito history',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'A year of celibacy',
      b: 'A year without your phone',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'The neighbours hearing you',
      b: 'Hearing the neighbours every night',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Only morning sex',
      b: 'Only the dead of night',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Perfect in bed but hopeless with words',
      b: 'A wonderful poet but a disaster in bed',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Sharing every number, body count included',
      b: 'Handing over your unlocked phone for an hour',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Rewatching your first time on video',
      b: 'Recounting it now in decent detail',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Always initiating, by contract',
      b: 'Always waiting, even for months',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Sex with no kissing ever',
      b: 'Kissing with never anything more',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'One night with your worst ex',
      b: 'Six months with nobody',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'The group hears your 3 am voice notes',
      b: 'The group reads your last sexting',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Caught by your parents at the worst moment',
      b: 'Catching your parents at the worst moment',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Forgetting your best nights',
      b: 'Remembering them all but never telling a soul',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Trying a fetish assigned by the group',
      b: 'Confessing yours right now',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Only one night stands forever',
      b: 'Only dead-serious relationships from day one',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'A secret affair kept secret forever',
      b: 'Everything public from day one',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'A friend with benefits who falls in love',
      b: 'Always falling for your friends with benefits',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Saying out loud who here attracts you',
      b: 'The group voting on who you attract',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Your secret drawer found by your mum',
      b: 'Found by your boss',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Sex only at your place forever',
      b: 'Never at your place again',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Showers for two always compulsory',
      b: 'Never a shower for two again',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Always sleeping naked, everywhere',
      b: 'Always fully dressed, even on honeymoon',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'A tattoo with every ex\'s name',
      b: 'A public online list of your exes',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Always making too much noise',
      b: 'Total silence compulsory forever',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Your ex gives a reference to every new partner',
      b: 'No references but plenty of suspicion',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Knowing how many times they faked it with you',
      b: 'Living serenely in doubt',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Ten-out-of-ten sex once a month',
      b: 'Six-out-of-ten every day',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Always far too quick',
      b: 'Always far too long',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Your steamy playlist starting at the office',
      b: 'Your spicy message read at family dinner',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'A night with your star and everyone knows',
      b: 'Total secrecy but nobody will ever believe you',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Only risky public places',
      b: 'Only your own bed forever',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Confessing the most absurd place',
      b: 'Letting the group guess it with questions',
      tone: ContentTone.cattivo,
    ),
    (a: 'No more foreplay ever', b: 'Only foreplay', tone: ContentTone.cattivo),
    (
      a: 'Every date ends in bed',
      b: 'None ever does on the first',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Knowing the marks your exes give you',
      b: 'Giving out your marks publicly',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'A no-limits weekend you can never talk about',
      b: 'A normal night you can retell for years',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Your worst moment told by a witness',
      b: 'Telling it yourself but in full',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Losing your favourite position forever',
      b: 'Explaining it to the group right now',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Only sex scheduled in the diary',
      b: 'Only spontaneous at the worst moments',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Saying "that was the best ever" every time',
      b: 'Never being allowed to comment',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'A month without touching your partner',
      b: 'A month without speaking to them',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Everyone always knowing when you have done it',
      b: 'Nobody ever believing you',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Clothes ripped every time, at your expense',
      b: 'Always folding everything first, calmly',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Your ex in the next room every night',
      b: 'Your ex in your friend group forever',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Recounting your most absurd erotic dream',
      b: 'The group choosing who stars in it',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Never holiday sex again',
      b: 'Only holiday sex',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Losing count of your nights',
      b: 'A public counter always up to date',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Seducing with the exact same line every time',
      b: 'Never speaking again while seducing',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'The neighbours know when you have company',
      b: 'Your group gets a notification',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Breakfast with their family every time',
      b: 'Always leaving through the window',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Sex only to trap music',
      b: 'Only to classical music at full volume',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Always sleeping over, compulsory',
      b: 'Never being allowed to stay the night',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Your first morning thought said out loud',
      b: 'Your last thought of the night posted online',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'No more neck kisses ever',
      b: 'Only neck kisses',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Brilliant but you forget everything each time',
      b: 'You remember everything but you are mediocre',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'The honest truth about how it went, always',
      b: 'Guaranteed compliments but never sincere',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Repeating your best night forever',
      b: 'A brand new night but a total surprise',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Sex only after exactly three dates',
      b: 'Only on the first or never',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Everyone knows your fetish',
      b: 'Never being able to practise it again',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'A single year with vivid memories',
      b: 'Coupled up but with amnesia of the nights',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'A compulsory striptease at every party',
      b: 'Never undressing with the light on again',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Always saying it when you feel attraction',
      b: 'Never being able to show it',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'The group picks who you flirt with tonight',
      b: 'The group watches how you usually flirt',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Never mornings again',
      b: 'Never nights again',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Only hotels by the hour',
      b: 'Only your parents\' house',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Fantastic sex but only in summer',
      b: 'Mediocre but all year round',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Knowing what they really think during',
      b: 'Them knowing every thought of yours',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'The group picks your type for a year',
      b: 'Your ex picks it',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Every date commented on by the group',
      b: 'Always alone with no advice at all',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'One night to brag about for ten years',
      b: 'Ten nights to forget immediately',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Your next partner is in this room',
      b: 'It will never be anyone here',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Confessing the raciest thing you did',
      b: 'Your best friend telling it for you',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'A weekend of passion with zero conversation',
      b: 'A weekend of perfect talk and nothing else',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Every ex telling their version of you two',
      b: 'Never being able to tell yours',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Swallowing semen every time',
      b: 'Never receiving oral sex again',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Having anal sex every day',
      b: 'Never having sex again in your life',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Being filmed while having sex',
      b: 'Doing it in front of the whole group',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Everyone knowing how bad you are in bed',
      b: 'Them knowing what your most extreme fetish is',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Licking your worst enemy\'s anus',
      b: 'Having your anus licked by a complete stranger',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Coming on the face of the person to your right',
      b: 'Having the person to your left come on your face',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'A threesome with two close friends',
      b: 'A threesome with two complete strangers',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'A year of only anal sex',
      b: 'A year of only oral sex',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Your parents seeing your hot messages',
      b: 'Them seeing a video of you doing it',
      tone: ContentTone.cattivo,
    ),
  ];
}
