import '../content_tone.dart';

/// Coppie di "Preferisci" in tedesco: parità completa col mazzo italiano.
class PreferisciPoolDe {
  const PreferisciPoolDe._();

  static const List<({String a, String b})> pairs = <({String a, String b})>[
    (a: 'Wissen, wie du stirbst', b: 'Wissen, wann'),
    (a: 'Eine unbequeme Wahrheit', b: 'Eine bequeme Lüge'),
    (a: 'Mehr Geld', b: 'Mehr Freizeit'),
    (a: 'Berühmt sein', b: 'Für alle unsichtbar sein'),
    (a: 'In die Vergangenheit reisen', b: 'In die Zukunft reisen'),
    (a: 'Fliegen können', b: 'Unsichtbar sein'),
    (a: 'Gedanken lesen', b: 'Die Zukunft vorhersagen'),
    (a: 'Nie mehr Social Media', b: 'Nie mehr Filme'),
    (a: 'Dein Handy verlieren', b: 'Deine Hausschlüssel verlieren'),
    (a: 'Immer 5 Minuten zu früh', b: 'Immer 10 Minuten zu spät'),
    (a: 'Netter aber unfähiger Chef', b: 'Fieser aber genialer Chef'),
    (a: 'Top Gehalt, langweiliger Job', b: 'Wenig Geld, aber Traumjob'),
    (a: 'Hochzeit mit 200 Gästen', b: 'Hochzeit zu zweit'),
    (a: 'Eine Woche nicht rausgehen', b: 'Jeden Abend ausgehen'),
    (a: 'Zehn Stunden schlafen', b: 'Fünf Stunden und top fit sein'),
    (a: 'Den perfekten Urlaub wiederholen', b: 'Einen neuen Ort ausprobieren'),
    (a: 'Jeden Tag aufs Konto schauen', b: 'Nie draufschauen'),
    (
      a: 'Nutzlose aber witzige Superkraft',
      b: 'Nützliche aber fade Superkraft',
    ),
    (a: 'Immer dasselbe Buch lesen', b: 'Nie eines fertig lesen'),
    (a: 'Leben ohne Musik', b: 'Leben ohne Kino'),
    (a: 'Immer die Wahrheit kennen', b: 'Glücklich in der Illusion leben'),
    (a: 'Ein Sabbatjahr', b: 'Ein Jahr früher in Rente'),
    (a: 'Alle Sprachen sprechen', b: 'Alle Instrumente spielen'),
    (a: 'Nie peinlich berührt sein', b: 'Nie Angst haben'),
    (a: 'Deinen besten Tag neu erleben', b: 'Den schlimmsten löschen'),
    (
      a: 'Nach einem Monat zusammenziehen',
      b: 'Erst nach Jahren zusammenziehen',
    ),
    (a: 'Früh Kinder', b: 'Spät Kinder'),
    (a: 'Urlaub bis ins Detail geplant', b: 'Einfach losfahren'),
    (a: 'Eine Staffel in einer Nacht', b: 'Eine Folge pro Woche'),
    (a: 'Akku immer bei 1%', b: 'Extrem langsames Internet'),
    (a: 'Klamotten immer etwas feucht', b: 'Für immer ein Stein im Schuh'),
    (a: 'Immer sagen, was du denkst', b: 'Nie mehr sprechen können'),
    (a: 'Keine Heizung im Winter', b: 'Keine Klimaanlage im Sommer'),
    (a: 'Für immer Schluckauf', b: 'Alle zwei Minuten niesen'),
    (a: 'Lieblingsessen bei jeder Mahlzeit', b: 'Nie mehr dein Lieblingsessen'),
    (a: 'Nie mehr schlafen müssen', b: 'Nie mehr essen müssen'),
    (a: 'Reich aber ohne Freunde', b: 'Pleite aber sehr beliebt'),
    (a: 'Nie mehr Miete zahlen', b: 'Doppeltes Gehalt'),
    (a: 'Der Lustigste im Raum', b: 'Der Klügste im Raum'),
    (a: 'Fotografisches Gedächtnis', b: 'Jede Blamage vergessen'),
    (a: 'Nie mehr Schlangen', b: 'Nie mehr Staus'),
    (a: 'Ein Jahr rasierte Augenbrauen', b: 'Ein Jahr neongrüne Haare'),
    (a: 'Den Geruchssinn verlieren', b: 'Den Geschmack verlieren'),
    (a: 'Eine Cartoon-Stimme', b: 'Ein Lachen, das alle nervt'),
    (a: 'Verlauf für die Eltern sichtbar', b: 'Chats vom Chef gelesen'),
    (a: 'Nach jedem Satz rülpsen', b: 'Wie eine Ziege lachen'),
    (a: 'Fremde Zahnbürste benutzen', b: 'Aus seinem benutzten Glas trinken'),
    (a: 'Immer feuchte Hände', b: 'Immer spröde Lippen'),
    (a: 'Mit deinem Ex ausgehen', b: 'Mit dem Ex des besten Freundes'),
    (a: 'Laute aber geruchlose Pupse', b: 'Lautlos aber tödlich'),
    (a: 'Vergessen, wer du bist', b: 'Von allen vergessen werden'),
    (a: 'Dein ganzes Geld verlieren', b: 'Alle Erinnerungen verlieren'),
    (a: 'Reicher aber langweiliger Partner', b: 'Armer aber witziger Partner'),
    (
      a: 'Eine Stunde im Aufzug mit dem Ex',
      b: 'Eine Stunde im Aufzug mit dem Chef',
    ),
    (a: 'Geburtstag von allen vergessen', b: 'Peinliche Überraschungsparty'),
    (
      a: 'Dein Geheimnis wird allen verraten',
      b: 'Die Geheimnisse aller kennen',
    ),
    (a: 'Berühmt aber gehasst', b: 'Unbekannt aber geliebt'),
    (a: 'Nie mehr lachen', b: 'Nie mehr weinen'),
    (
      a: 'Ein Jahr zurück in die Schule',
      b: 'Jedes Jahr das Abitur wiederholen',
    ),
    (a: 'Im Horrorfilm leben', b: 'Im Musical leben'),
    (a: 'Füße statt Hände', b: 'Hände statt Füße'),
    (
      a: 'Eine Ente so groß wie ein Pferd',
      b: 'Hundert Pferde so groß wie Enten',
    ),
    (a: 'Unter Wasser leben', b: 'Im Weltraum leben'),
    (
      a: 'Von einer Killerschnecke gejagt',
      b: 'Ein Clown starrt dich nachts an',
    ),
    (a: 'Mit Tieren sprechen', b: 'Das Wetter steuern'),
    (a: 'Tanzen, sobald Musik läuft', b: 'Weinen, wenn jemand lacht'),
    (
      a: 'Jeden Morgen in einem anderen Land',
      b: 'Nie mehr aus deiner Stadt raus',
    ),
    (a: 'In einem Videospiel leben', b: 'In einem Zeichentrickfilm leben'),
    (
      a: 'Eine Pause-Taste für das Leben',
      b: 'Eine Rückspul-Taste für das Leben',
    ),
    (a: 'Teleportieren ohne Schuhe', b: 'Fliegen im Schritttempo'),
    (a: '1000 Jahre leben', b: 'Zehn Leben à 100 Jahre'),
    (a: 'Tacos-Regen', b: 'Eis-Schnee'),
    (a: 'Einen Tag König der Welt', b: 'Für immer ein normaler Mensch'),
    (a: 'Alles wissen ohne Gefühle', b: 'Alles fühlen ohne Verstehen'),
    (a: 'Ein Bedauern löschen', b: 'Einen Erfolg garantiert bekommen'),
    (a: 'Immer hungrig', b: 'Immer müde'),
    (
      a: 'Ein Schwanz, der bei Freude wackelt',
      b: 'Ohren, die bei Trauer hängen',
    ),
    (a: 'Für immer auf Kaffee verzichten', b: 'Auf Schokolade verzichten'),
    (a: 'Nase wächst beim Lügen', b: 'Haare wechseln die Farbe je nach Laune'),
    (a: 'Die Liebe deines Lebens finden', b: 'Den Traumjob finden'),
    (a: 'Superreich aber immer traurig', b: 'Pleite aber immer glücklich'),
    (a: 'Eine Million sofort', b: '3.000 Euro im Monat für immer'),
    (a: 'Deinen Hund retten', b: 'Einen Fremden retten'),
    (a: 'Nie lügen können', b: 'Jede Lüge glauben'),
    (
      a: 'Immer recht haben aber allein',
      b: 'Falsch liegen aber in Gesellschaft',
    ),
    (a: 'Verkanntes Genie', b: 'Glücklicher Einfaltspinsel'),
    (a: 'Jeden Tag dasselbe Outfit', b: 'Nie ein Outfit wiederholen'),
    (a: 'Alles singen, was du sagst', b: 'Nur rückwärts laufen'),
    (a: 'Überall gratis WLAN, für immer', b: 'Für immer gratis fliegen'),
    (a: 'Nur kochend heißes Essen', b: 'Nur eiskaltes Essen'),
    (a: 'Nie mehr Pizza', b: 'Nie mehr Pasta'),
    (a: 'Nie mehr Aperitifs', b: 'Nie mehr Lieferessen'),
    (a: 'Langes Leben voller Reue', b: 'Kurzes Leben ohne Reue'),
    (a: 'Lieben ohne Gegenliebe', b: 'Geliebt werden ohne Liebe'),
    (a: 'Der Partner liest deine Gedanken', b: 'Du liest seine Gedanken'),
    (
      a: 'Partner von Freunden ausgesucht',
      b: 'Partner vom Algorithmus gewählt',
    ),
    (a: 'Immer Lügner erkennen', b: 'Beim Lügen nie erwischt werden'),
    (a: 'Für immer 18 sein', b: 'Direkt auf 40 springen'),
    (a: 'Immer bei anderen schlafen', b: 'Immer Gäste bei dir haben'),
    (
      a: 'Konzert deiner Band aber allein',
      b: 'Festival mit Freunden, Musik grässlich',
    ),
    (a: 'Falsch singendes Karaoke vor allen', b: 'Eine Stunde allein tanzen'),
    (a: 'Alle Handyfotos verlieren', b: 'Alle Chats verlieren'),
    (a: 'Konfetti niesen', b: 'Seifenblasen rülpsen'),
    (a: 'Vier Arme haben', b: 'Vier Beine haben'),
    (a: '2,20 Meter groß sein', b: '1,20 Meter groß sein'),
    (a: 'Leben ohne Sommer', b: 'Leben ohne Winter'),
    (a: 'Fünf Fremde retten', b: 'Deinen besten Freund retten'),
    (a: 'Eine Million ohne Smartphone', b: 'Kein Geld aber mit Handy'),
    (a: 'Traumjob im Ausland', b: 'Fader Job bei den Freunden'),
    (a: 'Für immer 25 sein', b: 'Mit deinen Freunden altern'),
    (a: 'Traumhaus mitten im Nichts', b: 'Einzimmerwohnung im Zentrum'),
    (
      a: 'Wissen, was hinter dem Rücken läuft',
      b: 'Ruhig leben, ohne es zu wissen',
    ),
    (a: 'Jede Mahlzeit von einem Chef', b: 'Ein Privatchauffeur für immer'),
    (
      a: 'Alles laut kommentieren, was du tust',
      b: 'Die Erzählerstimme deines Lebens hören',
    ),
    (a: 'Jeden Morgen auf Lego treten', b: 'Jeden Morgen eiskalt duschen'),
    (a: 'Jede Nacht eine Mücke im Raum', b: 'Bei jeder Mahlzeit eine Fliege'),
    (a: 'Für immer irre Autokorrektur', b: 'Nie mehr Emojis'),
    (a: 'Anrufe nur über Lautsprecher', b: 'Display immer für alle sichtbar'),
    (a: 'Dein Hund spricht und kritisiert', b: 'Dein Spiegel lügt dich schön'),
    (a: 'Eine Million nur für dich', b: 'Hunderttausend pro Person'),
    (a: 'Immer unterschätzt werden', b: 'Immer überschätzt werden'),
    (a: 'Lieblingsserie neu entdecken', b: 'Jedes Finale vorab sehen'),
    (a: 'Nur schreiend sprechen', b: 'Nur flüsternd sprechen'),
    (a: 'In ernsten Momenten lachen', b: 'Bei jeder Komödie weinen'),
    (a: 'Immer mit den Händen essen', b: 'Alles mit dem Teelöffel essen'),
    (a: 'Deine Träume für Freunde sichtbar', b: 'Freunde lesen dein Tagebuch'),
    (a: 'Für immer der einzige Single', b: 'Als Erster in der Gruppe heiraten'),
    (a: 'In den 80ern geboren werden', b: 'Im Jahr 2050 geboren werden'),
    (
      a: 'Gratis essen aber immer allein',
      b: 'Immer zahlen aber in Gesellschaft',
    ),
    (a: 'Viral wegen einer Blamage', b: 'Nie mehr als 10 Likes'),
    (a: 'Für immer nur Wasser trinken', b: 'Nie mehr Wasser, nur Limo'),
    (a: 'Für immer nur ein Musikgenre', b: 'Nur eine App auf dem Handy'),
    (a: 'Im Smoking am Strand', b: 'In Badehose auf einer Hochzeit'),
    (a: 'Wie ein Sternekoch kochen', b: 'Eine Wohnung, die sich selbst putzt'),
    (a: 'Langer Flug neben einem Schwätzer', b: 'Langer Flug neben einem Baby'),
    (a: 'Für immer salziges Frühstück', b: 'Für immer süßes Abendessen'),
    (a: 'Leben ohne Spiegel', b: 'Leben ohne Uhren'),
    (a: 'Denselben Montag neu erleben', b: 'Alle Freitage überspringen'),
    (a: 'Mit Pflanzen sprechen', b: 'Babys verstehen'),
    (a: 'Immer beim Kartenspiel gewinnen', b: 'Immer einen Parkplatz finden'),
    (a: '40 Grad Sommer ohne Meer', b: 'Eiskalter Winter ohne Schnee'),
    (
      a: 'Nur schlecht synchronisierte Filme',
      b: 'Nur Filme mit versetzten Untertiteln',
    ),
    (a: 'Für immer gratis Kaffee', b: 'Für immer gratis Eis'),
    (a: 'Jedes Jahr umziehen', b: 'Für immer dieselbe Wohnung'),
    (
      a: 'Für immer peinlicher Klingelton',
      b: 'Für immer peinlicher Hintergrund',
    ),
    (a: 'Ein berühmtes Meme sein', b: 'Einen berühmten Doppelgänger haben'),
    (a: 'Zur Begrüßung Macarena tanzen', b: 'Alle mit einer Verbeugung grüßen'),
    (a: 'Nutella ohne Brot', b: 'Brot ohne Nutella'),
    (a: 'Endloses Wochenende mit Regen', b: 'Nur Montage aber immer Sonne'),
    (a: 'Nur ein Gericht, aber perfekt', b: 'Alles nur mittelmäßig kochen'),
  ];

  /// Dilemmi da modalità Hot: parità completa col mazzo italiano.
  static const List<({String a, String b, String tone})>
  hot = <({String a, String b, String tone})>[
    (
      a: 'Eine Minute nackt rumlaufen',
      b: 'Jemanden aus dieser Gruppe küssen',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Die Nacht mit einem hier verbringen',
      b: 'Eine Nacht mit einem alten Lehrer',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Deine Galerie der Gruppe zeigen',
      b: 'Deine Chats laut vorlesen lassen',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Ein Jahr ohne Sex',
      b: 'Ein Jahr ohne Abende draußen',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Deinen Body Count verraten',
      b: 'Deine letzte Suche zeigen',
      tone: ContentTone.piccante,
    ),
    (a: 'Liebe ohne Sex', b: 'Sex ohne Liebe', tone: ContentTone.piccante),
    (
      a: 'Schöner Partner, schlecht im Bett',
      b: 'Normaler Partner, phänomenal',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Eine Nacht mit deinem Ex',
      b: 'Eine Nacht mit einem Fremden',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Deine Eltern erwischen',
      b: 'Von deinen Eltern erwischt werden',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Allen sagen, wen du magst',
      b: 'Nie mehr mit ihm sprechen',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Einen hier mit geschlossenen Augen küssen',
      b: 'Deinen Ex vor allen küssen',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Nie mehr küssen können',
      b: 'Nie mehr umarmen können',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Wissen, mit wem er dich betrügt',
      b: 'Es nie erfahren',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Ein Jahr nur Blind Dates',
      b: 'Nur Dates, die deine Mutter wählt',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Deinen ersten Kuss im Video sehen',
      b: 'Die ganze Gruppe sieht ihn',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Bei jedem Sitzen stöhnen',
      b: 'Beim Anstoßen den Ex-Namen rufen',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Ein Nude versehentlich an den Ex',
      b: 'Es in die Familiengruppe schicken',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Sexting mit dem Chef aus Versehen',
      b: 'Den Partner mit Ex-Namen rufen',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Eine Nacht mit einem Star',
      b: 'Ein Monat Sex mit deinem Ex',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Sex nur in völliger Dunkelheit',
      b: 'Nur mit immer angeschaltetem Licht',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Deine seltsamste Fantasie sagen',
      b: 'Die von rechts hören',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Bettfreunde mit dem besten Freund',
      b: 'Ein Jahr keinen Sex mehr',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Ein Ex, der göttlich küsst',
      b: 'Ein Neuer, dem du alles beibringst',
      tone: ContentTone.piccante,
    ),
    (
      a: 'An der Bar mit Blicken ausgezogen',
      b: 'Nie mehr bemerkt werden',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Von deinem schlimmsten Date erzählen',
      b: 'Deine heißeste Blamage neu erleben',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Immer den ersten Schritt machen',
      b: 'Immer auf den anderen warten',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Ein Dreier mit Fremden',
      b: 'Ein Dreier mit Freunden',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Den Mitbewohner erwischen',
      b: 'Vom Mitbewohner erwischt werden',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Sagen, wie oft du am Tag dran denkst',
      b: 'Sagen, wann es das letzte Mal war',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Extrem eifersüchtig aber heiß',
      b: 'Ruhig aber faul im Bett',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Den Ersten küssen, der reinkommt',
      b: 'Den Letzten küssen, der schrieb',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Leidenschaft ohne einen Kuss',
      b: 'Endlose Küsse und nichts weiter',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Dein erstes Mal vergessen',
      b: 'Dich jeden Tag daran erinnern',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Den absurdesten Ort verraten',
      b: 'Sagen, wo du es tun willst',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Ein Flirt mit deinem Trainer',
      b: 'Ein Flirt mit deinem Arzt',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Ein Jahr nur One-Night-Stands',
      b: 'Lebenslang nur feste Beziehungen',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Ab und zu wieder mit dem Ex',
      b: 'Für immer Schluss, aber mit Reue',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Knutschen mit dem links von dir',
      b: 'Sinnlicher Tanz mit dem rechts',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Nackt neben einem Freund schlafen',
      b: 'Mit dem Ex in Badehose duschen',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Ein Nude vom Chef bekommen',
      b: 'Ihm eins versehentlich schicken',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Sagenhafter Sex einmal im Monat',
      b: 'Mittelmäßiger Sex jeden Tag',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Wissen, was er im Bett denkt',
      b: 'Er hört jeden deiner Gedanken',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Ein Wochenende mit dem Schwarm',
      b: 'Ein Monat mit der ersten Liebe',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Frühstück im Bett danach',
      b: 'Vor dem Morgengrauen verschwinden',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Deine Schwachstelle im Bett sagen',
      b: 'Sie vor der Gruppe vormachen',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Den Ex-Namen tätowieren',
      b: 'Ihn im falschen Moment rufen',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Ein Match mit dem Ex in der App',
      b: 'Ein Match mit dem Chef in der App',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Er kennt alle deine Fantasien',
      b: 'Du kennst alle seine',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Jetzt ein Striptease improvisiert',
      b: 'Eine heiße Story deines Sommers',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Einen hier küssen, den du wählst',
      b: 'Einen küssen, den die Gruppe wählt',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Heimliche, sehr heiße Beziehung',
      b: 'Offizielle aber lauwarme',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Sex nur im Sommer',
      b: 'Sex nur im Winter',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Alle wilden Nächte vergessen',
      b: 'Auch die schlimmsten erinnern',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Heißes Audio an die falsche Person',
      b: 'Eins vom Chef bekommen',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Chats mit dem Ex vorlesen lassen',
      b: 'Fotos mit dem Ex zeigen',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Heute Liebe auf den ersten Blick',
      b: 'Heute Abend ein Abenteuer',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Den Namen deines Schwarms sagen',
      b: 'Die Gruppe rätseln lassen',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Heute ein Tanz mit dem Ex',
      b: 'Romantisches Karaoke mit einem hier',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Jetzt einen Fremden anbaggern',
      b: 'Die Nummer dem Ersten geben',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Eine Massage von einem hier',
      b: 'Einem hier eine Massage geben',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Ein Jahr Flirtverbot',
      b: 'Pflicht, mit allen zu flirten',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Eine Nacht mit deinem Musikidol',
      b: 'Ein Wochenende mit deinem Star',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Einen heißen Traum gestehen',
      b: 'Einer hier gesteht einen über dich',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Totale Stille im Bett',
      b: 'Volle Reportage im Bett',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Ein Traumhintern',
      b: 'Ein Dekolleté zum Applaudieren',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Dein Ex wird superberühmt',
      b: 'Dein Ex wird dein Chef',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Sagen, was dich am meisten anmacht',
      b: 'Sagen, was dich sofort abtörnt',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Ein Sommerflirt, nie gestanden',
      b: 'Eine endlose Fernbeziehung',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Zwei hier baggern dich an',
      b: 'Du baggerst zwei gleichzeitig an',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Den Ex mit einem Schöneren sehen',
      b: 'Er sieht dich mit einem Schlechteren',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Küsse mit Biss',
      b: 'Für immer nur brave Küsse',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Umarmt schlafen ohne Sex',
      b: 'Sex ohne je zusammen zu schlafen',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Sex mit Musik in voller Lautstärke',
      b: 'Mit den Nachrichten im Hintergrund',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Deine Anzahl an Ex verraten',
      b: 'Verraten, wer der Beste war',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Heute den Kellner anbaggern',
      b: 'Ihm die Nummer auf den Bon schreiben',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Erstes Mal peinlich aber süß',
      b: 'Perfekt aber mit dem Falschen',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Ein Tattoo, wo die Gruppe entscheidet',
      b: 'Ein Piercing, wo die Gruppe will',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Ein 30-Sekunden-Kuss mit einem hier',
      b: 'Zehn kurze Küsse mit zehn Fremden',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Wissen, wer hier von dir träumt',
      b: 'Wissen, wer dich nie küssen würde',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Sex im Zelt auf vollem Campingplatz',
      b: 'Im Hotel mit Papierwänden',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Urlaub nur für Singles',
      b: 'Urlaub nur für Paare',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Ein perfekter Kuss pro Monat',
      b: 'Mittelmäßige Küsse jeden Tag',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Wissen, was dein Schwarm denkt',
      b: 'Er weiß alles, was du denkst',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Eine unvergessliche Nacht ohne mehr',
      b: 'Zehn süße Dates ohne Funken',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Nur umarmt schlafen',
      b: 'Alles andere, aber kein Kuscheln',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Dem Schwarm den Body Count sagen',
      b: 'Den letzten heißen Chat zeigen',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Partner, der sehr gut küsst',
      b: 'Partner, der sehr gut schreibt',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Vor deinen Eltern flirten',
      b: 'Vor deinem Ex flirten',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Ein freches Foto falsch erhalten',
      b: 'Selbst eins falsch verschicken',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Mit Worten verführt werden',
      b: 'Mit Blicken verführt werden',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Ein Wochenende Leidenschaft ohne Handy',
      b: 'Eine Woche Flirt nur per Chat',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Erster Kuss beim ersten Date',
      b: 'Erster Kuss nach einem Monat',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Immer wissen, wer dich ansieht',
      b: 'Es nie wissen, aber oft angesehen',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Ein Ex, der jede Nacht schreibt',
      b: 'Ein Schwarm, der nie schreibt',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Ein Tanz mit dem Schwarm vor allen',
      b: 'Candle-Light-Dinner in Stille',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Den Chat mit dem Schwarm vorlesen',
      b: 'Ihn jetzt auf Lautsprecher anrufen',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Jeden Abend eine perfekte Massage',
      b: 'Jeden Morgen Frühstück im Bett',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Jemandes bester Kuss sein',
      b: 'Den besten Kuss deines Lebens',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Nie mehr erste Dates',
      b: 'Für immer nur erste Dates',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Immer zuerst "ich mag dich" sagen',
      b: 'Immer warten, bis es gesagt wird',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Eine Playlist startet beim Flirten',
      b: 'Eine Stimme kommentiert deine Dates',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Dein Ex auf deiner Hochzeit',
      b: 'Die Schwiegermutter im Honeymoon',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Den ersten Kuss erneut sehen',
      b: 'Dein Dating-Profil der Gruppe zeigen',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Frost bei jedem "wir müssen reden"',
      b: 'Es nie zu hören bekommen',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Jeden Sommer ein Flirt',
      b: 'Alle zehn Jahre echte Liebe',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Wissen, wie oft man über dich sprach',
      b: 'Wissen, was gesagt wurde, nicht wer',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Küsse nur im Regen',
      b: 'Küsse nur im Aufzug',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Jeden Morgen ein "guten Morgen"',
      b: 'Jeden Abend eine "gute Nacht"',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Beim Flirten die Stimme verlieren',
      b: 'Immer ein Wort zu viel sagen',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Nur tagsüber unwiderstehlich',
      b: 'Nur nachts unwiderstehlich',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Ein Blind Date von der Gruppe gewählt',
      b: 'Ein Date von deinem Ex organisiert',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Mit dem Partner deines Schwarms essen',
      b: 'Den ganzen Abend ihr Fahrer sein',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Lügen in der Liebe erkennen',
      b: 'Nie als Erster lügen',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Ein Jahr ohne Küsse',
      b: 'Ein Jahr ohne Umarmungen',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Dem Schwarm alles gestehen',
      b: 'Es jetzt dem ganzen Raum gestehen',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Berühmt für eine Liebesgeschichte',
      b: 'Berühmt für einen Korb',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Mit deinem Ebenbild ausgehen',
      b: 'Mit deinem Gegenteil ausgehen',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Dein Tagebuch beim Schwarm',
      b: 'Dein Verlauf bei deinen Eltern',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Ein unvergesslicher geklauter Kuss',
      b: 'Hundert höflich erbetene Küsse',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Immer desinteressiert wirken',
      b: 'Immer zu interessiert wirken',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Nur einmal Liebe auf ersten Blick',
      b: 'Ständige Funken, nie erwidert',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Jede Woche Blumen im Büro',
      b: 'Jeden Abend eine Liebesnachricht',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Nur schriftlich super flirten',
      b: 'Nur live super flirten',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Verknallt in einen aus der Gruppe',
      b: 'Verknallt in einen Kollegen',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Wissen, ob das erste Date gut wird',
      b: 'Jedes erste Date wiederholen können',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Romantisches Date minutiös geplant',
      b: 'Jedes Mal völlig improvisiert',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Ein Partner, der super tanzt',
      b: 'Ein Partner, der super kocht',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Für immer keine Eifersucht',
      b: 'Doppelte Leidenschaft mit Eifersucht',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Von zwei Personen umworben werden',
      b: 'Immer wählen, aber nie umworben',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Dein Name in einem Liebeslied',
      b: 'Dein Gesicht in einem viralen Video',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Nur Dates beim Frühstück',
      b: 'Nur Dates um Mitternacht',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Immer Händchen halten in der Stadt',
      b: 'Nur privat, aber intensiv',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Alle deine Ex vergessen',
      b: 'Alle deine Ex vergessen dich',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Ein Filmkuss einmal im Jahr',
      b: 'Normale Küsse, aber täglich',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Mit einem handgeschriebenen Brief',
      b: 'Mit einer Rede vor allen',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Den Tag deiner Verliebtheit kennen',
      b: 'Nur den Namen kennen, nicht wann',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Empfindlich aber leidenschaftlich',
      b: 'Entspannt aber lauwarm',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Deine erste Liebe neu erleben',
      b: 'Die letzte vorher kennen',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Beim Flirten schüchtern wirken',
      b: 'Frech wirken, obwohl schüchtern',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Die Wahrheit über jedes Ende',
      b: 'Es nie wissen, aber in Ruhe enden',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Perfektes Date vom Ex organisiert',
      b: 'Ein Desaster mit dem Richtigen',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Allen gefallen außer dem Schwarm',
      b: 'Nur dem Schwarm gefallen',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Nachrichten immer sofort gelesen',
      b: 'Antwort garantiert in einer Minute',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Eine Nachricht pro Tag löschen',
      b: 'Gelöschte Nachrichten lesen können',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Frecher Flirt nur am Dienstag',
      b: 'Leichter Flirt jeden Tag',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Die Gruppe wählt dein nächstes Date',
      b: 'Die Gruppe liest den letzten Chat',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Ohne Warnung geküsst werden',
      b: 'Jeden Kuss zehn Sekunden vorher ansagen',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Ein legendärer Single-Sommer',
      b: 'Ein perfekter Winter als Paar',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Dein Schwarm sieht alle Storys',
      b: 'Du siehst alles, was er ansieht',
      tone: ContentTone.piccante,
    ),
    (
      a: 'Ein Tanz mit dem Falschen',
      b: 'Nie mehr ein langsamer Tanz',
      tone: ContentTone.piccante,
    ),
    (a: 'Schlucken', b: 'Ausspucken', tone: ContentTone.cattivo),
    (
      a: 'Ein Jahr lang nur Oralsex',
      b: 'Nie wieder Oralsex',
      tone: ContentTone.cattivo,
    ),
    (a: 'Oralsex geben', b: 'Oralsex bekommen', tone: ContentTone.cattivo),
    (
      a: '69 die ganze Nacht',
      b: 'Nur klassischer Verkehr',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Ihm beim Abspritzen zusehen',
      b: 'Selbst schlucken',
      tone: ContentTone.cattivo,
    ),
    (a: 'Deepthroat', b: 'Nur sanft lecken', tone: ContentTone.cattivo),
    (
      a: 'Auf dem Gesicht abspritzen lassen',
      b: 'Auf die Brust abspritzen lassen',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Beim Oralsex geführt werden',
      b: 'Selbst das Tempo bestimmen',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Oralsex im Auto',
      b: 'Oralsex unter dem Tisch',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Ihn zum Höhepunkt lecken',
      b: 'Selbst geleckt werden',
      tone: ContentTone.cattivo,
    ),
    (a: 'Analsex geben', b: 'Analsex bekommen', tone: ContentTone.cattivo),
    (
      a: 'Ein Jahr nur Analsex',
      b: 'Nie wieder Analsex',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Analsex zum ersten Mal',
      b: 'Beim Klassiker bleiben',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Buttplug den ganzen Abend tragen',
      b: 'Ganz darauf verzichten',
      tone: ContentTone.cattivo,
    ),
    (a: 'Rimming geben', b: 'Rimming bekommen', tone: ContentTone.cattivo),
    (
      a: 'Doppelte Penetration',
      b: 'Nur eine Stelle gleichzeitig',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Analtraining mit Plugs',
      b: 'Direkt ohne Vorbereitung',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Orgasmus hinauszögern',
      b: 'Sofort kommen dürfen',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Eine Woche Orgasmusverbot',
      b: 'Jeden Tag zum Höhepunkt',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Edging bis zum Betteln',
      b: 'Schneller Höhepunkt',
      tone: ContentTone.cattivo,
    ),
    (a: 'Ruined Orgasm', b: 'Voller Orgasmus', tone: ContentTone.cattivo),
    (
      a: 'Auf Kommando kommen müssen',
      b: 'Kommen wann du willst',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Mehrere Orgasmen hintereinander',
      b: 'Ein einziger intensiver',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Keuschheitskäfig für eine Woche',
      b: 'Freier Zugang',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Orgasmus verweigert bekommen',
      b: 'Immer erlaubt kommen',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Vibrator beim Sex benutzen',
      b: 'Nur Hände und Mund',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Fernbedienter Vibrator in der Öffentlichkeit',
      b: 'Nur zu Hause',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Ein Jahr nur mit Sexspielzeug',
      b: 'Nie wieder Spielzeug',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Dildo benutzen lassen',
      b: 'Nur echter Verkehr',
      tone: ContentTone.cattivo,
    ),
    (a: 'Penisring tragen', b: 'Ganz ohne', tone: ContentTone.cattivo),
    (
      a: 'Klitorissauger ausprobieren',
      b: 'Beim klassischen Vibrator bleiben',
      tone: ContentTone.cattivo,
    ),
    (a: 'Analkette benutzen', b: 'Verzichten', tone: ContentTone.cattivo),
    (
      a: 'Melkmaschine ausprobieren',
      b: 'Nur von Hand',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Gefesselt werden',
      b: 'Den anderen fesseln',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Augen verbunden Sex haben',
      b: 'Alles sehen',
      tone: ContentTone.cattivo,
    ),
    (a: 'Dominant sein', b: 'Unterwürfig sein', tone: ContentTone.cattivo),
    (
      a: 'Beim Sex versohlt werden',
      b: 'Ganz sanft behandelt',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Mit Handschellen ans Bett',
      b: 'Frei bewegen',
      tone: ContentTone.cattivo,
    ),
    (a: 'Ein Halsband tragen', b: 'Ohne Halsband', tone: ContentTone.cattivo),
    (
      a: 'Wachsspiel auf der Haut',
      b: 'Nur Federn und Streicheln',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Ausgepeitscht werden',
      b: 'Nur leichtes Klapsen',
      tone: ContentTone.cattivo,
    ),
    (a: 'Geknebelt werden', b: 'Laut sein dürfen', tone: ContentTone.cattivo),
    (a: 'Nippelklemmen tragen', b: 'Ganz ohne', tone: ContentTone.cattivo),
    (
      a: 'Komplette Kontrolle abgeben',
      b: 'Immer die Kontrolle behalten',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Als Sub einen Tag gehorchen',
      b: 'Als Dom einen Tag befehlen',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Impact Play mit Paddle',
      b: 'Nur mit bloßer Hand',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Shibari-Fesselung tragen',
      b: 'Frei bleiben',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Beim Sex an den Haaren gezogen',
      b: 'Ganz zärtlich',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Ein Dreier mit zwei Fremden',
      b: 'Beim Partner mit anderem zusehen',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Dreier mit zwei Frauen',
      b: 'Dreier mit zwei Männern',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'An einem Gruppensex teilnehmen',
      b: 'Nur zusehen',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Partnertausch für eine Nacht',
      b: 'Treu bleiben',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Sex in einem Swingerclub',
      b: 'Nur zu Hause allein',
      tone: ContentTone.cattivo,
    ),
    (a: 'Gangbang erleben', b: 'Nur zu zweit', tone: ContentTone.cattivo),
    (
      a: 'Zusehen wie dein Partner geleckt wird',
      b: 'Selbst im Mittelpunkt stehen',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Eine Orgie mit acht Leuten',
      b: 'Ein intimes Date zu zweit',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Von zwei Menschen gleichzeitig verwöhnt',
      b: 'Nur von einem',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Cuckold-Fantasie ausleben',
      b: 'Streng monogam bleiben',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Sex am FKK-Strand',
      b: 'Sex im dunklen Kino',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Quickie auf der Bürotoilette',
      b: 'Nur zu Hause im Bett',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Sex auf dem Balkon bei Tageslicht',
      b: 'Nur nachts drinnen',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Erwischt werden riskieren',
      b: 'Immer auf Nummer sicher',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Sex im fahrenden Zug',
      b: 'Sex im geparkten Auto',
      tone: ContentTone.cattivo,
    ),
    (a: 'Im Umkleideraum ran', b: 'Erst zu Hause', tone: ContentTone.cattivo),
    (a: 'Sex im Fahrstuhl', b: 'Sex im Treppenhaus', tone: ContentTone.cattivo),
    (
      a: 'Nackt vor dem Fenster zeigen',
      b: 'Vorhänge zu',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Sex im Schwimmbad nach Schließung',
      b: 'Nur in der Wanne daheim',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Handjob unter der Restaurantdecke',
      b: 'Warten bis zu Hause',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Füße küssen und lecken',
      b: 'Nur Hände halten',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Dessous des Partners tragen',
      b: 'Ganz nackt bleiben',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'High Heels beim Sex anbehalten',
      b: 'Barfuß',
      tone: ContentTone.cattivo,
    ),
    (a: 'Latexanzug tragen', b: 'Nackte Haut', tone: ContentTone.cattivo),
    (
      a: 'Beim Sex angespuckt werden',
      b: 'Nur geküsst werden',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Dirty Talk die ganze Zeit',
      b: 'Komplett still',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Beim Sex fotografiert werden',
      b: 'Keine Aufnahmen',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Ein Sexvideo drehen',
      b: 'Nichts festhalten',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Am Nacken geknabbert werden',
      b: 'Ganz zärtlich geküsst',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Strapse und Nylons tragen',
      b: 'Ohne alles',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Mit verbundenen Händen essen lassen',
      b: 'Selbst füttern',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Beim Sex beobachtet werden',
      b: 'Ganz privat bleiben',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Uniform-Fetisch ausleben',
      b: 'Alltagskleidung',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Sich gegenseitig rasieren',
      b: 'Behaart bleiben',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Chef und Sekretärin spielen',
      b: 'Fremde in einer Bar spielen',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Arzt und Patientin spielen',
      b: 'Lehrerin und Nachhilfe spielen',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Ein unschuldiges Rollenspiel',
      b: 'Ein dominantes Rollenspiel',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Als Fremde neu kennenlernen',
      b: 'Als altes Paar spielen',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Verführungsspiel mit Kostümen',
      b: 'Ganz ohne Verkleidung',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Einen Massage-Salon nachspielen',
      b: 'Direkt zur Sache',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Herr und Zofe spielen',
      b: 'Auf Augenhöhe bleiben',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Fotoshooting-Rollenspiel',
      b: 'Kein Skript',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Eine Fantasie beichten',
      b: 'Dein Geheimnis behalten',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Die wildeste Fantasie ausleben',
      b: 'Nur davon träumen',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Partner sucht dein Sexspielzeug aus',
      b: 'Du entscheidest selbst',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Ein ganzes Wochenende nur Sex',
      b: 'Ein Monat Enthaltsamkeit',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Sex mit Musik laut aufgedreht',
      b: 'In völliger Stille',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Beim ersten Date direkt Sex',
      b: 'Monate warten',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Ein Sexdate mit Unbekanntem übers Netz',
      b: 'Nur mit Vertrauten',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Deine Suchhistorie zeigen',
      b: 'Für immer geheim halten',
      tone: ContentTone.cattivo,
    ),
    (a: 'Oben liegen', b: 'Unten liegen', tone: ContentTone.cattivo),
    (a: 'Doggy Style', b: 'Reiten', tone: ContentTone.cattivo),
    (
      a: 'Sex im Stehen an der Wand',
      b: 'Gemütlich im Bett',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Schneller harter Sex',
      b: 'Langsam und zärtlich',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Morgens beim Aufwachen',
      b: 'Mitten in der Nacht',
      tone: ContentTone.cattivo,
    ),
    (a: 'Sex im Dunkeln', b: 'Bei hellem Licht', tone: ContentTone.cattivo),
    (
      a: 'Rauer Quickie',
      b: 'Stundenlanges Vorspiel',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Löffelchen-Stellung',
      b: 'Missionarsstellung',
      tone: ContentTone.cattivo,
    ),
    (a: 'Auf dem Küchentisch', b: 'Auf dem Sofa', tone: ContentTone.cattivo),
    (
      a: 'Sex unter der heißen Dusche',
      b: 'Im warmen Bett',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Eiswürfel auf der Haut',
      b: 'Heißes Massageöl',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Am ganzen Körper geleckt',
      b: 'Nur an einer Stelle',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Sinnliche Ganzkörpermassage zuerst',
      b: 'Sofort zur Sache',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Federkitzeln bis zum Betteln',
      b: 'Direkt fester Griff',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Ohren angehaucht bekommen',
      b: 'Nur berührt werden',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Beim Sex am Hals gebissen',
      b: 'Sanft geküsst',
      tone: ContentTone.cattivo,
    ),
    (a: 'Laut stöhnen', b: 'Ganz leise bleiben', tone: ContentTone.cattivo),
    (
      a: 'Beim Höhepunkt den Namen rufen',
      b: 'Still genießen',
      tone: ContentTone.cattivo,
    ),
    (a: 'Dominant führen', b: 'Sich fallen lassen', tone: ContentTone.cattivo),
    (
      a: 'Betteln müssen',
      b: 'Alles verlangen dürfen',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Eine Woche kein Höhepunkt erlaubt',
      b: 'Jederzeit erlaubt',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Beim Selbstbefriedigen zuschauen lassen',
      b: 'Ganz privat für dich',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Gegenseitig masturbieren',
      b: 'Nur der eine macht es',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Sexting den ganzen Tag',
      b: 'Erst am Abend real',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Nacktfotos schicken',
      b: 'Nur persönlich zeigen',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Beim Duschen gemeinsam verwöhnen',
      b: 'Getrennt duschen',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Spanking mit der flachen Hand',
      b: 'Nur streicheln',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Rollentausch der Machtpositionen',
      b: 'Feste Rollen behalten',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Beim Sex Befehle geben',
      b: 'Befehle empfangen',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Ein Safeword vereinbaren',
      b: 'Ganz ohne Grenzen spielen',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Sensory Deprivation mit Maske',
      b: 'Alle Sinne offen',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Mit Kerzenwachs bemalt werden',
      b: 'Nur mit Ölen',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Am Bettpfosten festgebunden',
      b: 'Frei bewegen',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Ein Rollenspiel als Sklave',
      b: 'Als Herrscher befehlen',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Mit einem Ex noch einmal',
      b: 'Mit einem Fremden zum ersten Mal',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Sex mit dem besten Freund des Partners',
      b: 'Streng nur zu zweit',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Voyeurismus ausleben',
      b: 'Exhibitionismus ausleben',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Ein Paar zu euch einladen',
      b: 'Für euch bleiben',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Gemeinsam Pornos schauen',
      b: 'Lieber allein',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Eine Nacht offene Beziehung',
      b: 'Für immer treu',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Sperma über den ganzen Körper',
      b: 'Alles schlucken',
      tone: ContentTone.cattivo,
    ),
    (a: 'Cremepie erleben', b: 'Immer mit Kondom', tone: ContentTone.cattivo),
    (
      a: 'Squirting erleben',
      b: 'Klassischer Orgasmus',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Facesitting geben',
      b: 'Facesitting empfangen',
      tone: ContentTone.cattivo,
    ),
    (a: 'Ganz ohne Kondom', b: 'Immer mit Schutz', tone: ContentTone.cattivo),
    (
      a: 'Nach dem Sex sofort noch eine Runde',
      b: 'Kuscheln und schlafen',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Beim Sex komplett angezogen bleiben',
      b: 'Sofort alles ausziehen',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Deinen geheimsten Wunsch flüstern',
      b: 'Für dich behalten',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Sex nur mit Blickkontakt',
      b: 'Von hinten ohne Blick',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Beim Höhepunkt in die Augen sehen',
      b: 'Den Blick abwenden',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Aphrodisiaka ausprobieren',
      b: 'Ganz natürlich bleiben',
      tone: ContentTone.cattivo,
    ),
    (
      a: 'Ein Tantra-Ritual üben',
      b: 'Schnell und direkt',
      tone: ContentTone.cattivo,
    ),
  ];
}
