/// Bugie pre-scritte per Bluff Story (versione gratuita): 150 affermazioni
/// generiche ma plausibili, nella stessa forma in cui i giocatori scrivono la
/// propria verità.
///
/// Con il premium AI queste vengono sostituite da bugie costruite sul testo
/// vero appena inserito, quindi molto più difficili da smascherare.
class BluffStoryPool {
  const BluffStoryPool._();

  static const List<String> fakes = <String>[
    'Una volta ho dormito dodici ore di fila in un aeroporto.',
    'Ho imparato a nuotare solo a diciotto anni.',
    'Ho perso un volo per essermi addormentato al gate.',
    'Da piccolo mi sono perso in un centro commerciale per un\'ora.',
    'Ho vinto una gara di ballo alle medie.',
    'Sono finito per sbaglio in una foto di matrimonio di sconosciuti.',
    'Ho lavorato una settimana come cameriere e mi hanno licenziato.',
    'Ho cucinato per venti persone senza aver mai cucinato prima.',
    'Sono stato in televisione per tre secondi durante un telegiornale.',
    'Ho incontrato un attore famoso in un supermercato.',
    'Ho fatto l\'autostop per cinquanta chilometri.',
    'Ho dormito in macchina durante un temporale in montagna.',
    'Ho preso il treno sbagliato e sono finito in un\'altra regione.',
    'Ho passato un capodanno in ospedale con un amico.',
    'Sono caduto da un albero da bambino senza farmi niente.',
    'Ho rotto un braccio giocando a nascondino.',
    'Ho fatto un tatuaggio e me ne sono pentito il giorno dopo.',
    'Mi sono tagliato i capelli da solo durante un periodo difficile.',
    'Ho tinto i capelli di verde per una scommessa.',
    'Ho cantato al karaoke davanti a cento persone.',
    'Ho suonato la chitarra in una band per due mesi.',
    'Ho scritto una canzone che non ho mai fatto sentire a nessuno.',
    'Ho tenuto un diario per cinque anni di fila.',
    'Ho letto un libro intero in una notte.',
    'Ho visto lo stesso film al cinema tre volte.',
    'Ho imparato a memoria un intero monologo di un film.',
    'Ho recitato in uno spettacolo scolastico dimenticando le battute.',
    'Sono stato in un coro per un anno.',
    'Ho imparato una lingua guardando le serie TV.',
    'Ho fatto un esame senza aver studiato e l\'ho passato.',
    'Ho copiato a un compito e sono stato scoperto.',
    'Ho saltato una settimana di scuola senza che nessuno se ne accorgesse.',
    'Sono stato l\'ultimo a scoprire una notizia importante della mia famiglia.',
    'Ho scoperto di avere un cugino che non sapevo esistesse.',
    'Ho vissuto in tre città diverse in due anni.',
    'Ho traslocato da solo con una macchina piccolissima.',
    'Ho vissuto un mese senza televisione né internet.',
    'Ho passato un\'estate intera senza usare i social.',
    'Ho cancellato tutti i social per tre mesi.',
    'Ho perso il telefono in mare.',
    'Ho lasciato il portafoglio su un treno e me lo hanno restituito.',
    'Ho trovato dei soldi per strada e li ho consegnati.',
    'Ho vinto venti euro a un gratta e vinci.',
    'Ho comprato un biglietto della lotteria e non l\'ho mai controllato.',
    'Ho pagato una cena a sconosciuti per sbaglio.',
    'Ho ordinato lo stesso piatto per un mese intero.',
    'Ho mangiato la pizza per sette giorni di fila.',
    'Ho provato a diventare vegetariano e ho resistito due settimane.',
    'Ho cucinato un dolce che nessuno è riuscito a mangiare.',
    'Ho bruciato una pentola dimenticandola sul fuoco.',
    'Ho fatto scattare l\'allarme antincendio cucinando.',
    'Ho rotto il forno il giorno prima di una cena importante.',
    'Ho montato un mobile e mi sono avanzati dei pezzi.',
    'Ho dipinto una stanza di un colore che ho odiato subito.',
    'Ho dormito su un materasso per terra per sei mesi.',
    'Ho vissuto con un coinquilino che non ho mai visto sveglio.',
    'Ho adottato un animale d\'impulso.',
    'Ho dato un nome a una pianta.',
    'Ho fatto morire tutte le piante che mi hanno regalato.',
    'Ho salvato un gatto da un albero.',
    'Ho avuto paura di un cane grande quanto un gatto.',
    'Ho corso una mezza maratona senza allenarmi.',
    'Mi sono iscritto in palestra e ci sono andato tre volte.',
    'Ho giocato a calcio in una squadra per una sola partita.',
    'Ho fatto sci per la prima volta a trent\'anni.',
    'Ho provato il paracadutismo e non lo rifarei.',
    'Ho fatto immersione e mi sono spaventato a dieci metri.',
    'Ho scalato una montagna senza scarpe adatte.',
    'Ho dormito in tenda sotto la pioggia per due notti.',
    'Ho fatto un viaggio da solo senza dirlo a nessuno.',
    'Ho prenotato un viaggio nel giorno sbagliato.',
    'Ho passato una notte in stazione aspettando il primo treno.',
    'Ho conosciuto il mio migliore amico in fila da qualche parte.',
    'Ho ritrovato un amico d\'infanzia per caso all\'estero.',
    'Ho mantenuto un\'amicizia per anni solo per messaggi.',
    'Ho scritto una lettera che non ho mai spedito.',
    'Ho ricevuto una lettera che mi ha cambiato la giornata.',
    'Ho chiamato il numero sbagliato e ho parlato per dieci minuti.',
    'Ho risposto a una chiamata di lavoro mentre ero in spiaggia.',
    'Ho lavorato durante tutte le vacanze di Natale.',
    'Ho cambiato lavoro senza avere un piano B.',
    'Ho rifiutato un\'offerta di lavoro migliore di quella che avevo.',
    'Ho fatto un colloquio in una lingua che conoscevo poco.',
    'Ho preso una decisione importante lanciando una moneta.',
    'Ho dormito durante una riunione importante.',
    'Ho mandato una mail a tutta l\'azienda per sbaglio.',
    'Ho chiamato il capo con il nome sbagliato.',
    'Ho lavorato con qualcuno per mesi senza sapere il suo cognome.',
    'Ho fatto finta di conoscere una persona che mi salutava.',
    'Ho salutato uno sconosciuto pensando fosse un amico.',
    'Ho riconosciuto qualcuno solo dalla voce dopo dieci anni.',
    'Ho dimenticato il compleanno di una persona importante.',
    'Ho organizzato una festa a sorpresa che è stata scoperta prima.',
    'Ho tenuto un segreto per cinque anni.',
    'Ho detto una bugia che è durata un anno intero.',
    'Ho confessato una cosa solo perché mi sentivo in colpa.',
    'Ho pianto guardando una pubblicità.',
    'Ho riso in un momento assolutamente sbagliato.',
    'Mi sono addormentato al cinema durante un film che volevo vedere.',
    'Ho applaudito da solo alla fine di un film.',
    'Ho cantato in macchina credendo che nessuno mi vedesse.',
    'Ho ballato in ascensore con qualcuno che non conoscevo.',
    'Ho fatto amicizia con un vicino solo dopo tre anni.',
    'Ho perso le chiavi di casa il giorno del trasloco.',
    'Sono rimasto chiuso fuori casa in pigiama.',
    'Sono rimasto bloccato in ascensore per venti minuti.',
    'Ho preso la scala mobile nel verso sbagliato.',
    'Ho sbagliato bagno in un ristorante.',
    'Sono entrato in una riunione sbagliata e sono rimasto dieci minuti.',
    'Ho parlato al telefono con il volume alto senza accorgermene.',
    'Ho mandato un messaggio alla persona di cui stavo parlando.',
    'Ho fatto uno screenshot e l\'ho mandato alla persona sbagliata.',
    'Ho messo mi piace a una foto di dieci anni fa per sbaglio.',
    'Ho scritto un commento e l\'ho cancellato dopo un secondo.',
    'Ho creato un profilo social che non ho mai usato.',
    'Ho guardato tutta una serie in un weekend senza uscire.',
    'Ho finito un videogioco in una notte.',
    'Ho giocato allo stesso gioco per cinque anni.',
    'Ho vinto un torneo di carte in famiglia barando.',
    'Ho perso una scommessa e ho dovuto tingermi i capelli.',
    'Ho fatto una scommessa che mi è costata una cena per otto.',
    'Ho mangiato qualcosa di piccantissimo per una scommessa.',
    'Ho bevuto tre caffè in un\'ora e non ho dormito.',
    'Ho passato una notte in bianco per un\'ansia inutile.',
    'Ho fatto un sogno così realistico da crederci al risveglio.',
    'Ho parlato nel sonno rivelando una cosa importante.',
    'Ho camminato nel sonno da bambino.',
    'Mi sono svegliato in un posto diverso da dove mi ero addormentato.',
    'Ho dormito su una panchina in un parco di pomeriggio.',
    'Ho passato un\'intera giornata senza parlare con nessuno.',
    'Ho parlato con uno sconosciuto per due ore in treno.',
    'Ho restituito un portafoglio pieno trovato per strada.',
    'Ho vinto un premio a una lotteria di paese e non l\'ho mai ritirato.',
    'Ho mangiato la stessa cosa a pranzo per un mese intero.',
    'Ho finto di parlare una lingua straniera per non farmi riconoscere.',
    'Sono rimasto chiuso fuori casa in pigiama per tre ore.',
    'Ho risposto a una chiamata importante fingendo di non essere a letto.',
    'Ho applaudito da solo al cinema alla fine del film.',
    'Ho portato a spasso il cane sbagliato per venti minuti.',
    'Ho salutato con entusiasmo una persona che non conoscevo affatto.',
    'Ho seguito un tour turistico della mia stessa città fingendomi straniero.',
    'Ho mandato gli auguri di compleanno alla persona sbagliata due anni di fila.',
    'Ho vinto una discussione citando una statistica inventata sul momento.',
    'Ho tenuto l\'ombrello aperto per dieci minuti dopo che aveva smesso di piovere.',
    'Ho fatto una figuraccia a un colloquio e mi hanno preso lo stesso.',
    'Ho tenuto una pianta finta in casa per anni innaffiandola ogni tanto.',
    'Ho perso le chiavi e le ho ritrovate nel frigorifero.',
    'Ho detto "buon appetito" al cameriere che me lo aveva augurato.',
    'Ho corso dietro a un autobus per duecento metri e l\'ho preso.',
    'Ho dimenticato dove avevo parcheggiato e ho girato per un\'ora.',
  ];
}
