import '../content_tone.dart';

/// Contenuti di gioco in francese.
class ContentFr {
  const ContentFr._();

  static const List<({String text, String tone})> nonHoMai =
      <({String text, String tone})>[
        (text: 'prétexté une maladie pour ne pas travailler', tone: ContentTone.soft),
        (text: 'dormi jusqu\'en début d\'après-midi', tone: ContentTone.soft),
        (text: 'mangé un truc tombé par terre', tone: ContentTone.soft),
        (text: 'chanté sous la douche à pleine voix', tone: ContentTone.soft),
        (text: 'fait semblant de connaître une chanson', tone: ContentTone.soft),
        (text: 'oublié l\'anniversaire d\'un ami proche', tone: ContentTone.soft),
        (text: 'raté un avion ou un train', tone: ContentTone.soft),
        (text: 'voyagé complètement seul', tone: ContentTone.soft),
        (text: 'cassé un os', tone: ContentTone.soft),
        (text: 'fait un tatouage', tone: ContentTone.soft),
        (text: 'teint mes cheveux d\'une couleur absurde', tone: ContentTone.soft),
        (text: 'envoyé un message à la mauvaise personne', tone: ContentTone.soft),
        (text: 'ri à une blague que je n\'avais pas comprise', tone: ContentTone.soft),
        (text: 'parlé tout seul à voix haute', tone: ContentTone.soft),
        (text: 'pleuré devant un film', tone: ContentTone.soft),
        (text: 'regardé une saison entière en un jour', tone: ContentTone.soft),
        (text: 'cramé le dîner sans espoir', tone: ContentTone.soft),
        (text: 'laissé mes clés à l\'intérieur', tone: ContentTone.soft),
        (text: 'oublié où j\'avais garé', tone: ContentTone.soft),
        (text: 'fait semblant de ne pas voir quelqu\'un dans la rue', tone: ContentTone.soft),
        (text: 'inventé une excuse pour ne pas sortir', tone: ContentTone.soft),
        (text: 'annulé un plan à la dernière minute', tone: ContentTone.soft),
        (text: 'dit « j\'arrive dans cinq minutes » depuis mon canapé', tone: ContentTone.soft),
        (text: 'fait les courses en ayant faim', tone: ContentTone.soft),
        (text: 'acheté un truc que je n\'ai jamais utilisé', tone: ContentTone.soft),
        (text: 'gagné un prix', tone: ContentTone.soft),
        (text: 'fait un karaoké à jeun', tone: ContentTone.soft),
        (text: 'dormi dans un aéroport', tone: ContentTone.soft),
        (text: 'dormi dans une voiture', tone: ContentTone.soft),
        (text: 'nagé dans la mer la nuit', tone: ContentTone.soft),
        (text: 'dormi avec la lumière allumée en étant adulte', tone: ContentTone.soft),
        (text: 'cassé quelque chose sans rien dire', tone: ContentTone.soft),
        (text: 'accusé quelqu\'un d\'autre à ma place', tone: ContentTone.soft),
        (text: 'triché à un contrôle', tone: ContentTone.soft),
        (text: 'envoyé un mail sans la pièce jointe', tone: ContentTone.soft),
        (text: 'cherché mon nom sur internet', tone: ContentTone.soft),
        (text: 'utilisé le wifi du voisin sans demander', tone: ContentTone.soft),
        (text: 'donné un prénom à ma voiture', tone: ContentTone.soft),
        (text: 'menti sur mon âge', tone: ContentTone.soft),
        (text: 'offert un cadeau qu\'on m\'avait offert', tone: ContentTone.soft),
        (text: 'embrassé quelqu\'un le premier soir', tone: ContentTone.piccante),
        (text: 'craqué pour quelqu\'un de cette pièce', tone: ContentTone.piccante),
        (text: 'craqué pour le copain ou la copine d\'un ami', tone: ContentTone.piccante),
        (text: 'écrit à un ex en pleine nuit', tone: ContentTone.piccante),
        (text: 'fait semblant de dormir pour éviter une discussion', tone: ContentTone.piccante),
        (text: 'regardé le téléphone de mon copain ou ma copine', tone: ContentTone.piccante),
        (text: 'eu deux rendez-vous le même jour', tone: ContentTone.piccante),
        (text: 'dit « je t\'aime » sans le penser', tone: ContentTone.piccante),
        (text: 'rompu par message', tone: ContentTone.piccante),
        (text: 'gardé une relation secrète', tone: ContentTone.piccante),
        (text: 'dragué pour obtenir quelque chose', tone: ContentTone.piccante),
        (text: 'utilisé une appli de rencontres', tone: ContentTone.piccante),
        (text: 'perdu le compte de ce que j\'avais bu', tone: ContentTone.piccante),
        (text: 'regretté les messages de la veille', tone: ContentTone.piccante),
        (text: 'oublié une soirée entière', tone: ContentTone.piccante),
        (text: 'nagé sans maillot', tone: ContentTone.piccante),
        (text: 'ghosté quelqu\'un', tone: ContentTone.piccante),
        (text: 'partagé la capture d\'une conversation privée', tone: ContentTone.piccante),
        (text: 'remonté trois ans en arrière sur un profil', tone: ContentTone.piccante),
        (text: 'menti sur l\'endroit où je passais la soirée', tone: ContentTone.piccante),
        (text: 'demandé à un ami de m\'appeler pour fuir un rendez-vous', tone: ContentTone.piccante),
        (text: 'fait croire à un anniversaire pour un dessert gratuit', tone: ContentTone.piccante),
        (text: 'menti pendant cette partie', tone: ContentTone.piccante),
      ];

  static const List<({String text, String tone})> chiLoPotrebbeFare =
      <({String text, String tone})>[
        (text: 'Qui se perdrait dans une ville qu\'il connaît par cœur ?', tone: ContentTone.soft),
        (text: 'Qui serait en retard à son propre mariage ?', tone: ContentTone.soft),
        (text: 'Qui deviendrait célèbre par accident ?', tone: ContentTone.soft),
        (text: 'Qui survivrait le plus longtemps sur une île déserte ?', tone: ContentTone.soft),
        (text: 'Qui passerait un week-end entier sans sortir ?', tone: ContentTone.soft),
        (text: 'Qui engagerait la conversation dans un ascenseur ?', tone: ContentTone.soft),
        (text: 'Qui s\'engueulerait avec le GPS ?', tone: ContentTone.soft),
        (text: 'Qui achèterait un truc en ligne à trois heures du matin ?', tone: ContentTone.soft),
        (text: 'Qui mangerait de la pizza sept jours de suite ?', tone: ContentTone.soft),
        (text: 'Qui s\'endormirait au cinéma ?', tone: ContentTone.soft),
        (text: 'Qui chanterait au karaoké sans hésiter ?', tone: ContentTone.soft),
        (text: 'Qui serait le premier sur la piste ?', tone: ContentTone.soft),
        (text: 'Qui organiserait les vacances de tout le groupe ?', tone: ContentTone.soft),
        (text: 'Qui perdrait son passeport à l\'aéroport ?', tone: ContentTone.soft),
        (text: 'Qui prendrait trois valises pour deux jours ?', tone: ContentTone.soft),
        (text: 'Qui partirait vivre à l\'étranger sans réfléchir ?', tone: ContentTone.soft),
        (text: 'Qui adopterait dix chats ?', tone: ContentTone.soft),
        (text: 'Qui laisserait mourir toutes ses plantes ?', tone: ContentTone.soft),
        (text: 'Qui cuisinerait pour vingt personnes sans raison ?', tone: ContentTone.soft),
        (text: 'Qui renverrait un plat au restaurant ?', tone: ContentTone.soft),
        (text: 'Qui laisserait le plus gros pourboire ?', tone: ContentTone.soft),
        (text: 'Qui oublierait son portefeuille pile à son tour de payer ?', tone: ContentTone.soft),
        (text: 'Qui dépenserait tout son salaire en une semaine ?', tone: ContentTone.soft),
        (text: 'Qui deviendrait riche grâce à une idée absurde ?', tone: ContentTone.soft),
        (text: 'Qui s\'inscrirait à la salle en janvier et arrêterait en février ?', tone: ContentTone.soft),
        (text: 'Qui courrait un marathon sans entraînement ?', tone: ContentTone.soft),
        (text: 'Qui irait aux urgences pour un ongle cassé ?', tone: ContentTone.soft),
        (text: 'Qui chercherait ses symptômes en ligne et paniquerait ?', tone: ContentTone.soft),
        (text: 'Qui mettrait dix réveils et les ignorerait tous ?', tone: ContentTone.soft),
        (text: 'Qui enverrait un vocal de sept minutes ?', tone: ContentTone.soft),
        (text: 'Qui te laisserait en vu pendant des jours ?', tone: ContentTone.soft),
        (text: 'Qui a toujours 1% de batterie ?', tone: ContentTone.soft),
        (text: 'Qui prendrait cent photos pour en publier une ?', tone: ContentTone.soft),
        (text: 'Qui dirait oui à tout puis le regretterait ?', tone: ContentTone.soft),
        (text: 'Qui serait le dernier à partir d\'une soirée ?', tone: ContentTone.soft),
        (text: 'Qui partirait sans dire au revoir ?', tone: ContentTone.soft),
        (text: 'Qui ramènerait les restes chez lui ?', tone: ContentTone.soft),
        (text: 'Qui se souviendrait de tous les anniversaires ?', tone: ContentTone.soft),
        (text: 'Qui pleurerait devant une publicité ?', tone: ContentTone.soft),
        (text: 'Qui spoilerait la fin sans s\'en rendre compte ?', tone: ContentTone.soft),
        (text: 'Qui écrirait à un ex à trois heures du matin ?', tone: ContentTone.piccante),
        (text: 'Qui se remettrait avec un ex pour la troisième fois ?', tone: ContentTone.piccante),
        (text: 'Qui tomberait amoureux en deux jours de vacances ?', tone: ContentTone.piccante),
        (text: 'Qui dirait « je t\'aime » en premier ?', tone: ContentTone.piccante),
        (text: 'Qui romprait par message ?', tone: ContentTone.piccante),
        (text: 'Qui draguerait le serveur devant tout le monde ?', tone: ContentTone.piccante),
        (text: 'Qui a le plus de conversations ouvertes en ce moment ?', tone: ContentTone.piccante),
        (text: 'Qui regarderait le téléphone de son partenaire ?', tone: ContentTone.piccante),
        (text: 'Qui cacherait une relation au groupe ?', tone: ContentTone.piccante),
        (text: 'Qui embrasserait quelqu\'un pour un pari ?', tone: ContentTone.piccante),
        (text: 'Qui ghosterait quelqu\'un sans explication ?', tone: ContentTone.piccante),
        (text: 'Qui lâcherait un secret après deux verres ?', tone: ContentTone.piccante),
        (text: 'Qui finirait à chanter sur une table ?', tone: ContentTone.piccante),
        (text: 'Qui oublierait une soirée entière ?', tone: ContentTone.piccante),
        (text: 'Qui se ferait tatouer sur un coup de tête en vacances ?', tone: ContentTone.piccante),
        (text: 'Qui sauterait dans la piscine tout habillé ?', tone: ContentTone.piccante),
        (text: 'Qui écouterait une conversation privée ?', tone: ContentTone.piccante),
        (text: 'Qui mentirait en te regardant dans les yeux ?', tone: ContentTone.cattivo),
        (text: 'Qui ici a déjà menti ce soir ?', tone: ContentTone.cattivo),
        (text: 'Qui pense à quelqu\'un en ce moment même ?', tone: ContentTone.cattivo),
      ];

  static const Map<String, List<String>> obblighi = {
    ContentTone.soft: [
      'Imite la personne à ta droite jusqu\'à ce qu\'elle devine.',
      'Chante le refrain de la dernière chanson que tu as écoutée.',
      'Parle en rimes jusqu\'à ton prochain tour.',
      'Danse dix secondes sans musique.',
      'Montre la dernière photo que tu as prise.',
      'Montre ton écran d\'accueil sans rien ouvrir.',
      'Lis à voix haute la dernière note de ton téléphone.',
      'Présente la météo comme à la télé.',
      'Fais un discours de remerciement pour un prix imaginaire.',
      'Parle avec un accent jusqu\'à la prochaine manche.',
      'Tiens vingt secondes de gainage pendant qu\'on compte.',
      'Raconte ton talent le plus inutile et prouve-le.',
      'Fais un compliment sincère à chaque personne.',
      'Explique ton travail comme le ferait un enfant de cinq ans.',
      'Ne réponds qu\'avec des questions jusqu\'à ton prochain tour.',
      'Récite l\'alphabet à l\'envers le plus vite possible.',
      'Écris à quelqu\'un que tu n\'as pas contacté depuis un an.',
      'Laisse le groupe choisir ton prochain gage.',
      'Fais le robot pendant une minute.',
      'Prends le pire selfie possible.',
    ],
    ContentTone.piccante: [
      'Lis à voix haute le dernier message que tu as envoyé.',
      'Montre les trois dernières photos de ta galerie.',
      'Appelle le troisième contact de ton répertoire et demande comment il va.',
      'Laisse le groupe écrire un message et envoie-le pour de vrai.',
      'Montre ton temps d\'écran et lis les trois applis du top.',
      'Regarde la personne en face dans les yeux pendant trente secondes.',
      'Raconte ton pire premier rendez-vous.',
      'Montre comment tu dragues quand tu essaies vraiment.',
      'Dis quelles deux personnes ici iraient bien ensemble.',
      'Raconte la chose la plus gênante que tu aies faite bourré.',
      'Chuchote quelque chose à la personne en face, puis dis-le à tous.',
      'Donne ton classement sincère des personnes présentes.',
      'Dis ce que tu as vraiment pensé la première fois que tu as vu la personne en face.',
      'Confesse une chose que personne ici ne sait.',
      'Tiens la main de la personne à ta droite jusqu\'à la prochaine manche.',
      'Fais ta meilleure danse sensuelle pendant dix secondes.',
      'Laisse quelqu\'un choisir une photo de toi à publier.',
      'Raconte la chose la plus culottée qu\'un inconnu t\'ait dite.',
      'Révèle combien de temps tu as passé sur ton téléphone aujourd\'hui.',
      'Dis qui tu appellerais à quatre heures du matin en cas de drame.',
    ],
    ContentTone.cattivo: [
      'Dis à chacun ce que tu as pensé la première fois que tu l\'as vu.',
      'Classe les présents du plus au moins fiable.',
      'Dis qui ici ment le plus, en le regardant en face.',
      'Dis à la personne en face une chose chez elle qui t\'agace.',
      'Lis la dernière conversation avec la personne que le groupe choisit.',
      'Donne ton téléphone déverrouillé à ta gauche pendant trente secondes.',
      'Raconte la pire chose que tu aies faite à un ami.',
      'Confesse une chose pour laquelle tu ne t\'es jamais excusé.',
      'Excuse-toi maintenant, devant tout le monde, auprès de qui il faut.',
      'Dis qui ici t\'a le plus déçu.',
      'Dis combien tu gagnes, ou perds ton prochain tour.',
      'Raconte la chose la plus malhonnête que tu aies faite au travail.',
      'Dis ce dont tu as le plus honte.',
      'Dis ce que tu n\'as jamais osé dire à ta famille.',
      'Dis quelle amitié de ce groupe ne durera pas, selon toi.',
      'Dis qui tu sortirais du groupe si tu devais choisir.',
      'Montre la dernière chose que tu as cherchée en ligne.',
      'Dis la pire pensée que tu aies eue ce soir.',
      'Réponds avec une honnêteté totale aux trois prochaines questions.',
      'Termine la partie avec une vérité que personne n\'attend.',
    ],
  };

  static const Map<String, List<String>> verita = {
    ContentTone.soft: [
      'Quelle est la chose la plus gênante que tu aies faite en public ?',
      'Quel était ton plus gros mensonge d\'enfant ?',
      'Quel est ton plaisir coupable musical ?',
      'Quel film t\'a le plus fait pleurer ?',
      'Pour quelle bêtise t\'es-tu disputé ?',
      'Quelle est la chose la plus chère que tu aies cassée ?',
      'Quelle excuse utilises-tu le plus souvent ?',
      'Que fais-tu quand personne ne te voit ?',
      'Combien de temps passes-tu vraiment sur ton téléphone ?',
      'Quelle est la dernière chose que tu as cherchée ?',
      'À qui as-tu écrit en dernier ?',
      'Quelle est la plus belle chose qu\'on t\'ait dite ?',
      'Qui appellerais-tu à trois heures du matin pour un vrai problème ?',
      'Quel a été le meilleur moment de ton année ?',
      'De quoi as-tu le plus peur pour l\'avenir ?',
      'Que ferais-tu si tu ne devais plus jamais travailler ?',
      'Quelle décision changerais-tu si tu pouvais ?',
      'De quoi es-tu le plus fier ?',
      'Quel est ton talent caché ?',
      'Dans quel endroit retournerais-tu demain ?',
    ],
    ContentTone.piccante: [
      'As-tu déjà craqué pour quelqu\'un de ce groupe ?',
      'Quel a été ton coup de cœur le plus gênant ?',
      'Quelle est la chose la plus romantique que tu aies faite ?',
      'As-tu déjà embrassé deux personnes le même soir ?',
      'As-tu déjà menti à un partenaire ? Sur quoi ?',
      'As-tu déjà regardé le téléphone de ton partenaire ? Tu cherchais quoi ?',
      'As-tu déjà écrit à un ex en sachant que c\'était une mauvaise idée ?',
      'As-tu déjà ghosté quelqu\'un ? Pourquoi ?',
      'Quelle est la pire excuse que tu aies utilisée pour ne pas sortir ?',
      'Quelle est la pire chose que tu aies dite pour rompre ?',
      'As-tu déjà gardé une relation secrète ? Qui le savait ?',
      'Quelle est la chose la plus gênante que tu aies faite bourré ?',
      'As-tu déjà fait semblant de t\'amuser à une soirée ?',
      'Quel est le plus gros mensonge sur ton profil de rencontres ?',
      'As-tu déjà espionné le nouveau partenaire de ton ex ?',
      'Quelle est la chose la plus gênante dans ton téléphone ?',
      'À qui ici confierais-tu ton téléphone déverrouillé ?',
      'À qui ne le confierais-tu jamais ?',
      'Quelle chose regrettes-tu de ne pas avoir dite ?',
      'Y a-t-il une question de ce soir à laquelle tu as menti ?',
    ],
    ContentTone.cattivo: [
      'Qui ici n\'inviterais-tu pas à ton mariage ?',
      'De qui ici as-tu parlé dans son dos ?',
      'Qui considères-tu comme un vrai ami, et qui comme une simple connaissance ?',
      'Qui ici t\'a le plus déçu ?',
      'As-tu déjà trahi la confiance de quelqu\'un dans cette pièce ?',
      'Quel est le mensonge que tu racontes encore aujourd\'hui ?',
      'À qui dois-tu des excuses, et pourquoi ne les as-tu pas faites ?',
      'Quelle est la pire chose que tu aies faite à un ex ?',
      'As-tu déjà trompé quelqu\'un ? Le referais-tu ?',
      'Es-tu encore en colère contre quelqu\'un ici ? Pour quoi ?',
      'As-tu déjà été content du malheur de quelqu\'un ?',
      'Quelle est la chose la plus égoïste que tu aies faite ?',
      'As-tu déjà laissé quelqu\'un payer pour ton erreur ?',
      'Combien gagnes-tu, et est-ce que ça te paraît juste ?',
      'Qu\'y a-t-il dans ton téléphone qui casserait une amitié ici ?',
      'Quelle émotion fais-tu semblant d\'avoir le plus souvent ?',
      'Quelle partie de toi caches-tu le mieux ?',
      'Quel est ton plus grand échec, et à qui la faute vraiment ?',
      'Y a-t-il quelqu\'un que tu aimes et qui ne le sait pas ?',
      'Que ne nous diras-tu jamais ?',
    ],
  };

  static const List<String> bluffFakes = [
    'Une fois j\'ai dormi douze heures d\'affilée dans un aéroport.',
    'Je n\'ai appris à nager qu\'à dix-huit ans.',
    'J\'ai raté un avion en m\'endormant à la porte d\'embarquement.',
    'Petit, je me suis perdu une heure dans un centre commercial.',
    'J\'ai gagné un concours de danse au collège.',
    'Je suis apparu par erreur sur la photo de mariage d\'inconnus.',
    'J\'ai été serveur une semaine et on m\'a viré.',
    'J\'ai cuisiné pour vingt personnes sans jamais avoir cuisiné.',
    'Je suis passé trois secondes à la télévision.',
    'J\'ai croisé un acteur connu dans un supermarché.',
    'J\'ai fait cinquante kilomètres en stop.',
    'J\'ai dormi en voiture pendant un orage en montagne.',
    'J\'ai pris le mauvais train et fini dans une autre région.',
    'J\'ai passé un réveillon à l\'hôpital avec un ami.',
    'Enfant, je suis tombé d\'un arbre sans rien me faire.',
    'Je me suis cassé le bras en jouant à cache-cache.',
    'Je me suis coupé les cheveux moi-même dans une mauvaise période.',
    'J\'ai chanté en karaoké devant cent personnes.',
    'J\'ai joué de la guitare dans un groupe pendant deux mois.',
    'J\'ai écrit une chanson que je n\'ai jamais fait écouter.',
    'J\'ai tenu un journal pendant cinq ans.',
    'J\'ai lu un livre entier en une nuit.',
    'J\'ai vu le même film trois fois au cinéma.',
    'J\'ai appris une langue en regardant des séries.',
    'J\'ai réussi un examen sans réviser du tout.',
    'J\'ai vécu dans trois villes en deux ans.',
    'J\'ai passé un mois entier sans internet.',
    'J\'ai perdu mon téléphone dans la mer.',
    'J\'ai oublié mon portefeuille dans un train et on me l\'a rendu.',
    'J\'ai trouvé de l\'argent dans la rue et je l\'ai rapporté.',
  ];

  static const List<String> impostoreWords = [
    'Plage', 'Montagne', 'Aéroport', 'Gare', 'Métro',
    'Hôpital', 'Pharmacie', 'Supermarché', 'Boulangerie', 'Pizzeria',
    'Restaurant', 'Bar', 'Boîte de nuit', 'Salle de sport', 'Piscine',
    'Bibliothèque', 'Musée', 'Cinéma', 'Théâtre', 'Stade',
    'École', 'Université', 'Bureau', 'Usine', 'Chantier',
    'Coiffeur', 'Dentiste', 'Banque', 'Poste', 'Hôtel',
    'Camping', 'Zoo', 'Aquarium', 'Parc', 'Jardin',
    'Forêt', 'Désert', 'Île', 'Volcan', 'Cascade',
    'Ascenseur', 'Escalator', 'Feu rouge', 'Autoroute', 'Ferry',
    'Avion', 'Train', 'Vélo', 'Trottinette', 'Scooter',
    'Parapluie', 'Lunettes', 'Montre', 'Sac à dos', 'Valise',
    'Portefeuille', 'Clés', 'Téléphone', 'Chargeur', 'Écouteurs',
  ];
}
