import '../content_tone.dart';

/// Contenuti di gioco in inglese.
class ContentEn {
  const ContentEn._();

  static const List<({String text, String tone})> nonHoMai =
      <({String text, String tone})>[
        (text: 'called in sick when I was perfectly fine', tone: ContentTone.soft),
        (text: 'slept until the afternoon', tone: ContentTone.soft),
        (text: 'eaten something off the floor', tone: ContentTone.soft),
        (text: 'sung in the shower at full volume', tone: ContentTone.soft),
        (text: 'pretended to know a song I had never heard', tone: ContentTone.soft),
        (text: 'forgotten a close friend\'s birthday', tone: ContentTone.soft),
        (text: 'missed a flight or a train', tone: ContentTone.soft),
        (text: 'travelled somewhere completely alone', tone: ContentTone.soft),
        (text: 'broken a bone', tone: ContentTone.soft),
        (text: 'got a tattoo', tone: ContentTone.soft),
        (text: 'dyed my hair a ridiculous colour', tone: ContentTone.soft),
        (text: 'sent a message to the wrong person', tone: ContentTone.soft),
        (text: 'laughed at a joke I did not understand', tone: ContentTone.soft),
        (text: 'talked to myself out loud', tone: ContentTone.soft),
        (text: 'cried at a film', tone: ContentTone.soft),
        (text: 'watched a whole season in one day', tone: ContentTone.soft),
        (text: 'burnt dinner beyond saving', tone: ContentTone.soft),
        (text: 'locked myself out of the house', tone: ContentTone.soft),
        (text: 'forgotten where I parked', tone: ContentTone.soft),
        (text: 'pretended not to see someone in the street', tone: ContentTone.soft),
        (text: 'invented an excuse to stay in', tone: ContentTone.soft),
        (text: 'cancelled plans at the last second', tone: ContentTone.soft),
        (text: 'said "five minutes away" from my sofa', tone: ContentTone.soft),
        (text: 'gone food shopping starving', tone: ContentTone.soft),
        (text: 'bought something I have never used', tone: ContentTone.soft),
        (text: 'won a prize', tone: ContentTone.soft),
        (text: 'done karaoke sober', tone: ContentTone.soft),
        (text: 'slept in an airport', tone: ContentTone.soft),
        (text: 'slept in a car', tone: ContentTone.soft),
        (text: 'swum in the sea at night', tone: ContentTone.soft),
        (text: 'slept with the light on as an adult', tone: ContentTone.soft),
        (text: 'broken something and said nothing', tone: ContentTone.soft),
        (text: 'blamed someone else for my mistake', tone: ContentTone.soft),
        (text: 'cheated on a school test', tone: ContentTone.soft),
        (text: 'sent an email without the attachment', tone: ContentTone.soft),
        (text: 'googled my own name', tone: ContentTone.soft),
        (text: 'used someone else\'s Wi-Fi without asking', tone: ContentTone.soft),
        (text: 'given my car a name', tone: ContentTone.soft),
        (text: 'lied about my age', tone: ContentTone.soft),
        (text: 're-gifted a present', tone: ContentTone.soft),
        (text: 'kissed someone on the first night', tone: ContentTone.piccante),
        (text: 'had a crush on someone in this room', tone: ContentTone.piccante),
        (text: 'had a crush on a friend\'s partner', tone: ContentTone.piccante),
        (text: 'texted an ex after midnight', tone: ContentTone.piccante),
        (text: 'pretended to be asleep to avoid a conversation', tone: ContentTone.piccante),
        (text: 'checked a partner\'s phone', tone: ContentTone.piccante),
        (text: 'had two dates in one day', tone: ContentTone.piccante),
        (text: 'said "I love you" without meaning it', tone: ContentTone.piccante),
        (text: 'ended a relationship by message', tone: ContentTone.piccante),
        (text: 'kept a relationship secret', tone: ContentTone.piccante),
        (text: 'flirted to get something', tone: ContentTone.piccante),
        (text: 'used a dating app', tone: ContentTone.piccante),
        (text: 'lost count of how much I had drunk', tone: ContentTone.piccante),
        (text: 'regretted the texts I sent the night before', tone: ContentTone.piccante),
        (text: 'forgotten an entire evening', tone: ContentTone.piccante),
        (text: 'swum with no clothes on', tone: ContentTone.piccante),
        (text: 'ghosted someone', tone: ContentTone.piccante),
        (text: 'shared a screenshot of a private chat', tone: ContentTone.piccante),
        (text: 'scrolled three years back on someone\'s profile', tone: ContentTone.piccante),
        (text: 'lied about where I was spending the evening', tone: ContentTone.piccante),
        (text: 'asked a friend to call me to escape a date', tone: ContentTone.piccante),
        (text: 'faked a birthday for free dessert', tone: ContentTone.piccante),
        (text: 'told a lie during this game', tone: ContentTone.piccante),
      ];

  static const List<({String text, String tone})> chiLoPotrebbeFare =
      <({String text, String tone})>[
        (text: 'Who would get lost in a city they know well?', tone: ContentTone.soft),
        (text: 'Who would be late to their own wedding?', tone: ContentTone.soft),
        (text: 'Who would become famous by accident?', tone: ContentTone.soft),
        (text: 'Who would survive longest on a desert island?', tone: ContentTone.soft),
        (text: 'Who would spend a whole weekend without leaving the house?', tone: ContentTone.soft),
        (text: 'Who would start a conversation in a lift?', tone: ContentTone.soft),
        (text: 'Who would argue with a satnav?', tone: ContentTone.soft),
        (text: 'Who would buy something online at 3am?', tone: ContentTone.soft),
        (text: 'Who would eat pizza seven days in a row?', tone: ContentTone.soft),
        (text: 'Who would fall asleep at the cinema?', tone: ContentTone.soft),
        (text: 'Who would sing karaoke without hesitating?', tone: ContentTone.soft),
        (text: 'Who would be first on the dance floor?', tone: ContentTone.soft),
        (text: 'Who would organise the whole group holiday?', tone: ContentTone.soft),
        (text: 'Who would lose their passport at the airport?', tone: ContentTone.soft),
        (text: 'Who would pack three suitcases for two days?', tone: ContentTone.soft),
        (text: 'Who would move abroad without thinking twice?', tone: ContentTone.soft),
        (text: 'Who would adopt ten cats?', tone: ContentTone.soft),
        (text: 'Who would let every plant in the house die?', tone: ContentTone.soft),
        (text: 'Who would cook for twenty people for no reason?', tone: ContentTone.soft),
        (text: 'Who would send food back at a restaurant?', tone: ContentTone.soft),
        (text: 'Who would leave the biggest tip?', tone: ContentTone.soft),
        (text: 'Who would forget their wallet on their round?', tone: ContentTone.soft),
        (text: 'Who would spend a whole salary in a week?', tone: ContentTone.soft),
        (text: 'Who would get rich from a ridiculous idea?', tone: ContentTone.soft),
        (text: 'Who would join a gym in January and quit in February?', tone: ContentTone.soft),
        (text: 'Who would run a marathon with no training?', tone: ContentTone.soft),
        (text: 'Who would go to A&E for a broken nail?', tone: ContentTone.soft),
        (text: 'Who would google their symptoms and panic?', tone: ContentTone.soft),
        (text: 'Who would set ten alarms and ignore them all?', tone: ContentTone.soft),
        (text: 'Who would send a seven minute voice note?', tone: ContentTone.soft),
        (text: 'Who would leave you on read for days?', tone: ContentTone.soft),
        (text: 'Who always has 1% battery?', tone: ContentTone.soft),
        (text: 'Who would take a hundred photos to post one?', tone: ContentTone.soft),
        (text: 'Who would say yes to everything and regret it?', tone: ContentTone.soft),
        (text: 'Who would be the last to leave a party?', tone: ContentTone.soft),
        (text: 'Who would leave without saying goodbye?', tone: ContentTone.soft),
        (text: 'Who would take the leftovers home?', tone: ContentTone.soft),
        (text: 'Who would remember everyone\'s birthday?', tone: ContentTone.soft),
        (text: 'Who would cry at an advert?', tone: ContentTone.soft),
        (text: 'Who would spoil the ending without noticing?', tone: ContentTone.soft),
        (text: 'Who would text an ex at 3am?', tone: ContentTone.piccante),
        (text: 'Who would get back with an ex for the third time?', tone: ContentTone.piccante),
        (text: 'Who would fall in love on holiday in two days?', tone: ContentTone.piccante),
        (text: 'Who would say "I love you" first?', tone: ContentTone.piccante),
        (text: 'Who would break up over text?', tone: ContentTone.piccante),
        (text: 'Who would flirt with the waiter in front of everyone?', tone: ContentTone.piccante),
        (text: 'Who has the most chats open right now?', tone: ContentTone.piccante),
        (text: 'Who would check their partner\'s phone?', tone: ContentTone.piccante),
        (text: 'Who would hide a relationship from the group?', tone: ContentTone.piccante),
        (text: 'Who would kiss someone on a dare?', tone: ContentTone.piccante),
        (text: 'Who would ghost someone with no explanation?', tone: ContentTone.piccante),
        (text: 'Who would spill a secret after two drinks?', tone: ContentTone.piccante),
        (text: 'Who would end up singing on a table?', tone: ContentTone.piccante),
        (text: 'Who would forget an entire night out?', tone: ContentTone.piccante),
        (text: 'Who would get a tattoo on holiday on impulse?', tone: ContentTone.piccante),
        (text: 'Who would jump in the pool fully dressed?', tone: ContentTone.piccante),
        (text: 'Who would eavesdrop on a private conversation?', tone: ContentTone.piccante),
        (text: 'Who would lie straight to your face?', tone: ContentTone.cattivo),
        (text: 'Who in this room has already lied tonight?', tone: ContentTone.cattivo),
        (text: 'Who is thinking about someone right now?', tone: ContentTone.cattivo),
      ];

  static const Map<String, List<String>> obblighi = {
    ContentTone.soft: [
      'Imitate the person on your right until they guess it is them.',
      'Sing the chorus of the last song you listened to.',
      'Speak in rhyme until your next turn.',
      'Dance for ten seconds with no music.',
      'Show the last photo you took.',
      'Show your home screen without opening anything.',
      'Read your last saved note out loud.',
      'Do the weather forecast like on television.',
      'Give an award acceptance speech for nothing.',
      'Talk in an accent until the next round.',
      'Do twenty seconds of plank while everyone counts.',
      'Tell the group your most useless talent and prove it.',
      'Give an honest compliment to everyone here.',
      'Describe your job as a five year old would.',
      'Answer only in questions until your next turn.',
      'Say the alphabet backwards as fast as you can.',
      'Text someone you have not spoken to in a year.',
      'Let the group choose your next dare.',
      'Do your best impression of a robot for a minute.',
      'Take the worst selfie you can manage.',
    ],
    ContentTone.piccante: [
      'Read out the last message you sent.',
      'Show the last three photos in your gallery.',
      'Call the third contact in your phone and ask how they are.',
      'Let the group write a message and send it for real.',
      'Show your screen time and read the top three apps.',
      'Look the person opposite in the eyes for thirty seconds.',
      'Tell us your worst first date.',
      'Show how you flirt when you are trying.',
      'Say which two people here would work as a couple.',
      'Tell us the most embarrassing thing you did while drunk.',
      'Whisper something to the person opposite, then tell everyone.',
      'Give the group your honest ranking of everyone here.',
      'Say what you really thought when you first met the person opposite.',
      'Confess something you have never told anyone in this room.',
      'Hold hands with the person on your right until the next round.',
      'Do your best seductive dance for ten seconds.',
      'Let someone else pick a photo of you to post.',
      'Tell us the cheekiest thing a stranger ever said to you.',
      'Reveal how much time you spent on your phone today.',
      'Tell us who you would call at 4am with a crisis.',
    ],
    ContentTone.cattivo: [
      'Tell everyone the first thing you thought when you met them.',
      'Rank everyone here from most to least reliable.',
      'Say who in this room you think lies the most, to their face.',
      'Tell the person opposite one thing about them that annoys you.',
      'Read out the last conversation with the person the group picks.',
      'Hand your unlocked phone to the person on your left for thirty seconds.',
      'Tell us the worst thing you ever did to a friend.',
      'Confess something you have never apologised for.',
      'Apologise now, in front of everyone, to whoever deserves it.',
      'Say who in this room has disappointed you the most.',
      'Say how much you earn, or lose your next turn.',
      'Tell us the most dishonest thing you have done at work.',
      'Tell us what you are most ashamed of.',
      'Say the thing you have never dared to tell your family.',
      'Tell us which friendship here you think will not last.',
      'Say who you would cut out of the group if you had to.',
      'Show the last thing you searched for online.',
      'Tell the group the worst thought you have had tonight.',
      'Answer the next three questions with total honesty.',
      'End the game with a truth nobody expects.',
    ],
  };

  static const Map<String, List<String>> verita = {
    ContentTone.soft: [
      'What is the most embarrassing thing you have done in public?',
      'What was your biggest childhood lie?',
      'What is your guilty pleasure song?',
      'Which film made you cry the most?',
      'What is the silliest thing you have argued about?',
      'What is the most expensive thing you have broken?',
      'What excuse do you use most often?',
      'What do you do when nobody is watching?',
      'How long do you really spend on your phone?',
      'What was the last thing you searched for?',
      'Who was the last person you messaged?',
      'What is the nicest thing anyone has said to you?',
      'Who would you call at 3am with a real problem?',
      'What was the best moment of your year?',
      'What are you most afraid of about the future?',
      'What would you do if you never had to work again?',
      'Which decision would you change if you could?',
      'What are you proudest of?',
      'What is your hidden talent?',
      'What is the place you would go back to tomorrow?',
    ],
    ContentTone.piccante: [
      'Have you ever fancied someone in this group?',
      'Who was your most embarrassing crush?',
      'What is the most romantic thing you have done?',
      'Have you ever kissed two people in one night?',
      'Have you ever lied to a partner? About what?',
      'Have you ever checked a partner\'s phone? What were you looking for?',
      'Have you ever texted an ex knowing it was a bad idea?',
      'Have you ever ghosted someone? Why?',
      'What is the worst excuse you have used to avoid going out?',
      'What is the worst thing you have said to end a relationship?',
      'Have you ever kept a relationship secret? Who knew?',
      'What is the most embarrassing thing you have done while drunk?',
      'Have you ever pretended to enjoy a party?',
      'What is the biggest lie on a dating profile you have told?',
      'Have you ever looked up an ex\'s new partner?',
      'What is the most embarrassing thing in your phone?',
      'Who here would you trust with your unlocked phone?',
      'Who here would you never trust with it?',
      'What is the thing you regret not saying?',
      'Is there a question tonight you answered with a lie?',
    ],
    ContentTone.cattivo: [
      'Who here would you not invite to your wedding?',
      'Who here have you talked about behind their back?',
      'Which of us do you consider a real friend, and which just an acquaintance?',
      'Who here has disappointed you the most?',
      'Have you ever betrayed the trust of someone in this room?',
      'What is the lie you are still telling today?',
      'Who do you owe an apology to, and why have you not made it?',
      'What is the worst thing you have done to an ex?',
      'Have you ever cheated on someone? Would you do it again?',
      'Are you still angry at someone here? What for?',
      'Have you ever enjoyed someone else\'s bad luck?',
      'What is the most selfish thing you have done?',
      'Have you ever let someone else take the blame for you?',
      'How much do you earn, and does it feel fair?',
      'What would ruin a friendship in this room if we saw it on your phone?',
      'What emotion do you fake most often?',
      'Which part of yourself do you hide best?',
      'What is your biggest failure, and whose fault was it really?',
      'Is there someone you love who does not know it?',
      'What will you never tell any of us?',
    ],
  };

  static const List<String> bluffFakes = [
    'One time I slept twelve hours straight in an airport.',
    'I only learned to swim at eighteen.',
    'I once missed a flight because I fell asleep at the gate.',
    'As a kid I got lost in a shopping centre for an hour.',
    'I won a dance competition at school.',
    'I ended up in a stranger\'s wedding photo by accident.',
    'I worked as a waiter for one week and got fired.',
    'I once cooked for twenty people having never cooked before.',
    'I was on national television for three seconds.',
    'I met a famous actor in a supermarket.',
    'I hitchhiked fifty kilometres on my own.',
    'I slept in a car during a storm in the mountains.',
    'I got on the wrong train and ended up in another county.',
    'I spent a New Year\'s Eve in hospital with a friend.',
    'I fell out of a tree as a child and walked away fine.',
    'I broke my arm playing hide and seek.',
    'I cut my own hair during a rough patch.',
    'I sang karaoke in front of a hundred people.',
    'I played guitar in a band for two months.',
    'I wrote a song I have never played to anyone.',
    'I kept a diary for five years straight.',
    'I read an entire book in one night.',
    'I have seen the same film in the cinema three times.',
    'I learned a language just from watching series.',
    'I passed an exam without studying at all.',
    'I lived in three cities in two years.',
    'I went a whole month with no internet.',
    'I lost my phone in the sea.',
    'I left my wallet on a train and got it back.',
    'I once found money in the street and handed it in.',
  ];

  static const List<String> impostoreWords = [
    'Beach', 'Mountain', 'Airport', 'Station', 'Underground',
    'Hospital', 'Pharmacy', 'Supermarket', 'Bakery', 'Pizzeria',
    'Restaurant', 'Bar', 'Nightclub', 'Gym', 'Swimming pool',
    'Library', 'Museum', 'Cinema', 'Theatre', 'Stadium',
    'School', 'University', 'Office', 'Factory', 'Building site',
    'Hairdresser', 'Dentist', 'Bank', 'Post office', 'Hotel',
    'Campsite', 'Zoo', 'Aquarium', 'Park', 'Garden',
    'Forest', 'Desert', 'Island', 'Volcano', 'Waterfall',
    'Lift', 'Escalator', 'Traffic light', 'Motorway', 'Ferry',
    'Aeroplane', 'Train', 'Bicycle', 'Scooter', 'Motorbike',
    'Umbrella', 'Glasses', 'Watch', 'Backpack', 'Suitcase',
    'Wallet', 'Keys', 'Phone', 'Charger', 'Headphones',
  ];
}
