import '../content_tone.dart';

/// Contenuti di gioco in spagnolo.
class ContentEs {
  const ContentEs._();

  static const List<({String text, String tone})> nonHoMai =
      <({String text, String tone})>[
        (text: 'fingido estar enfermo para no ir a trabajar', tone: ContentTone.soft),
        (text: 'dormido hasta media tarde', tone: ContentTone.soft),
        (text: 'comido algo que se había caído al suelo', tone: ContentTone.soft),
        (text: 'cantado en la ducha a todo volumen', tone: ContentTone.soft),
        (text: 'fingido conocer una canción', tone: ContentTone.soft),
        (text: 'olvidado el cumpleaños de un amigo cercano', tone: ContentTone.soft),
        (text: 'perdido un vuelo o un tren', tone: ContentTone.soft),
        (text: 'viajado completamente solo', tone: ContentTone.soft),
        (text: 'roto un hueso', tone: ContentTone.soft),
        (text: 'hecho un tatuaje', tone: ContentTone.soft),
        (text: 'teñido el pelo de un color absurdo', tone: ContentTone.soft),
        (text: 'enviado un mensaje a la persona equivocada', tone: ContentTone.soft),
        (text: 'reído de un chiste que no había entendido', tone: ContentTone.soft),
        (text: 'hablado solo en voz alta', tone: ContentTone.soft),
        (text: 'llorado viendo una película', tone: ContentTone.soft),
        (text: 'visto una temporada entera en un día', tone: ContentTone.soft),
        (text: 'quemado la cena sin remedio', tone: ContentTone.soft),
        (text: 'dejado las llaves dentro de casa', tone: ContentTone.soft),
        (text: 'olvidado dónde había aparcado', tone: ContentTone.soft),
        (text: 'fingido no ver a alguien por la calle', tone: ContentTone.soft),
        (text: 'inventado una excusa para no salir', tone: ContentTone.soft),
        (text: 'cancelado un plan en el último momento', tone: ContentTone.soft),
        (text: 'dicho "llego en cinco minutos" desde el sofá', tone: ContentTone.soft),
        (text: 'ido a la compra con hambre', tone: ContentTone.soft),
        (text: 'comprado algo que no he usado nunca', tone: ContentTone.soft),
        (text: 'ganado un premio', tone: ContentTone.soft),
        (text: 'cantado en un karaoke sin haber bebido', tone: ContentTone.soft),
        (text: 'dormido en un aeropuerto', tone: ContentTone.soft),
        (text: 'dormido en el coche', tone: ContentTone.soft),
        (text: 'nadado de noche en el mar', tone: ContentTone.soft),
        (text: 'dormido con la luz encendida siendo adulto', tone: ContentTone.soft),
        (text: 'roto algo y no haberlo dicho', tone: ContentTone.soft),
        (text: 'culpado a otro de algo mío', tone: ContentTone.soft),
        (text: 'copiado en un examen', tone: ContentTone.soft),
        (text: 'enviado un correo sin el adjunto', tone: ContentTone.soft),
        (text: 'buscado mi nombre en internet', tone: ContentTone.soft),
        (text: 'usado el wifi del vecino sin permiso', tone: ContentTone.soft),
        (text: 'puesto nombre a mi coche', tone: ContentTone.soft),
        (text: 'mentido sobre mi edad', tone: ContentTone.soft),
        (text: 'regalado algo que me habían regalado a mí', tone: ContentTone.soft),
        (text: 'besado a alguien la primera noche', tone: ContentTone.piccante),
        (text: 'estado colado por alguien de esta sala', tone: ContentTone.piccante),
        (text: 'estado colado por la pareja de un amigo', tone: ContentTone.piccante),
        (text: 'escrito a un ex de madrugada', tone: ContentTone.piccante),
        (text: 'fingido dormir para evitar una conversación', tone: ContentTone.piccante),
        (text: 'mirado el móvil de mi pareja', tone: ContentTone.piccante),
        (text: 'tenido dos citas el mismo día', tone: ContentTone.piccante),
        (text: 'dicho "te quiero" sin sentirlo', tone: ContentTone.piccante),
        (text: 'cortado una relación por mensaje', tone: ContentTone.piccante),
        (text: 'mantenido una relación en secreto', tone: ContentTone.piccante),
        (text: 'flirteado para conseguir algo', tone: ContentTone.piccante),
        (text: 'usado una app de citas', tone: ContentTone.piccante),
        (text: 'perdido la cuenta de lo que había bebido', tone: ContentTone.piccante),
        (text: 'arrepentido de los mensajes de la noche anterior', tone: ContentTone.piccante),
        (text: 'olvidado una noche entera', tone: ContentTone.piccante),
        (text: 'bañado sin bañador', tone: ContentTone.piccante),
        (text: 'hecho ghosting a alguien', tone: ContentTone.piccante),
        (text: 'compartido la captura de un chat privado', tone: ContentTone.piccante),
        (text: 'llegado tres años atrás en el perfil de alguien', tone: ContentTone.piccante),
        (text: 'mentido sobre dónde estaba pasando la noche', tone: ContentTone.piccante),
        (text: 'pedido a un amigo que me llamara para escapar de una cita', tone: ContentTone.piccante),
        (text: 'fingido un cumpleaños para que el postre saliera gratis', tone: ContentTone.piccante),
        (text: 'mentido durante esta partida', tone: ContentTone.piccante),
      ];

  static const List<({String text, String tone})> chiLoPotrebbeFare =
      <({String text, String tone})>[
        (text: '¿Quién se perdería en una ciudad que conoce de sobra?', tone: ContentTone.soft),
        (text: '¿Quién llegaría tarde a su propia boda?', tone: ContentTone.soft),
        (text: '¿Quién se haría famoso por accidente?', tone: ContentTone.soft),
        (text: '¿Quién sobreviviría más tiempo en una isla desierta?', tone: ContentTone.soft),
        (text: '¿Quién pasaría un fin de semana entero sin salir de casa?', tone: ContentTone.soft),
        (text: '¿Quién daría conversación en un ascensor?', tone: ContentTone.soft),
        (text: '¿Quién discutiría con el GPS?', tone: ContentTone.soft),
        (text: '¿Quién compraría algo por internet a las tres de la mañana?', tone: ContentTone.soft),
        (text: '¿Quién comería pizza siete días seguidos?', tone: ContentTone.soft),
        (text: '¿Quién se dormiría en el cine?', tone: ContentTone.soft),
        (text: '¿Quién cantaría en un karaoke sin dudarlo?', tone: ContentTone.soft),
        (text: '¿Quién sería el primero en la pista de baile?', tone: ContentTone.soft),
        (text: '¿Quién organizaría el viaje de todo el grupo?', tone: ContentTone.soft),
        (text: '¿Quién perdería el pasaporte en el aeropuerto?', tone: ContentTone.soft),
        (text: '¿Quién llevaría tres maletas para dos días?', tone: ContentTone.soft),
        (text: '¿Quién se mudaría al extranjero sin pensarlo?', tone: ContentTone.soft),
        (text: '¿Quién adoptaría diez gatos?', tone: ContentTone.soft),
        (text: '¿Quién dejaría morir todas las plantas de casa?', tone: ContentTone.soft),
        (text: '¿Quién cocinaría para veinte personas sin motivo?', tone: ContentTone.soft),
        (text: '¿Quién devolvería un plato en el restaurante?', tone: ContentTone.soft),
        (text: '¿Quién dejaría la mejor propina?', tone: ContentTone.soft),
        (text: '¿Quién olvidaría la cartera justo cuando le toca pagar?', tone: ContentTone.soft),
        (text: '¿Quién se gastaría el sueldo en una semana?', tone: ContentTone.soft),
        (text: '¿Quién se haría rico con una idea absurda?', tone: ContentTone.soft),
        (text: '¿Quién se apuntaría al gimnasio en enero y lo dejaría en febrero?', tone: ContentTone.soft),
        (text: '¿Quién correría una maratón sin entrenar?', tone: ContentTone.soft),
        (text: '¿Quién iría a urgencias por una uña rota?', tone: ContentTone.soft),
        (text: '¿Quién buscaría sus síntomas en internet y entraría en pánico?', tone: ContentTone.soft),
        (text: '¿Quién pondría diez alarmas y las apagaría todas?', tone: ContentTone.soft),
        (text: '¿Quién mandaría un audio de siete minutos?', tone: ContentTone.soft),
        (text: '¿Quién te dejaría en visto durante días?', tone: ContentTone.soft),
        (text: '¿Quién siempre tiene el móvil al 1%?', tone: ContentTone.soft),
        (text: '¿Quién haría cien fotos para publicar una?', tone: ContentTone.soft),
        (text: '¿Quién diría que sí a todo y luego se arrepentiría?', tone: ContentTone.soft),
        (text: '¿Quién sería el último en irse de la fiesta?', tone: ContentTone.soft),
        (text: '¿Quién se iría sin despedirse?', tone: ContentTone.soft),
        (text: '¿Quién se llevaría las sobras a casa?', tone: ContentTone.soft),
        (text: '¿Quién se acordaría del cumpleaños de todos?', tone: ContentTone.soft),
        (text: '¿Quién lloraría con un anuncio?', tone: ContentTone.soft),
        (text: '¿Quién haría spoiler sin darse cuenta?', tone: ContentTone.soft),
        (text: '¿Quién escribiría a un ex a las tres de la mañana?', tone: ContentTone.piccante),
        (text: '¿Quién volvería con un ex por tercera vez?', tone: ContentTone.piccante),
        (text: '¿Quién se enamoraría en dos días de vacaciones?', tone: ContentTone.piccante),
        (text: '¿Quién diría "te quiero" primero?', tone: ContentTone.piccante),
        (text: '¿Quién cortaría por mensaje?', tone: ContentTone.piccante),
        (text: '¿Quién flirtearía con el camarero delante de todos?', tone: ContentTone.piccante),
        (text: '¿Quién tiene más chats abiertos ahora mismo?', tone: ContentTone.piccante),
        (text: '¿Quién miraría el móvil de su pareja?', tone: ContentTone.piccante),
        (text: '¿Quién escondería una relación al grupo?', tone: ContentTone.piccante),
        (text: '¿Quién besaría a alguien por una apuesta?', tone: ContentTone.piccante),
        (text: '¿Quién haría ghosting sin explicaciones?', tone: ContentTone.piccante),
        (text: '¿Quién contaría un secreto después de dos copas?', tone: ContentTone.piccante),
        (text: '¿Quién acabaría cantando encima de una mesa?', tone: ContentTone.piccante),
        (text: '¿Quién olvidaría una noche entera?', tone: ContentTone.piccante),
        (text: '¿Quién se haría un tatuaje de vacaciones por impulso?', tone: ContentTone.piccante),
        (text: '¿Quién se tiraría a la piscina vestido?', tone: ContentTone.piccante),
        (text: '¿Quién escucharía una conversación privada?', tone: ContentTone.piccante),
        (text: '¿Quién mentiría mirándote a los ojos?', tone: ContentTone.cattivo),
        (text: '¿Quién de aquí ya ha mentido esta noche?', tone: ContentTone.cattivo),
        (text: '¿Quién está pensando en alguien ahora mismo?', tone: ContentTone.cattivo),
      ];

  static const Map<String, List<String>> obblighi = {
    ContentTone.soft: [
      'Imita a la persona de tu derecha hasta que adivine que es ella.',
      'Canta el estribillo de la última canción que escuchaste.',
      'Habla en verso hasta tu próximo turno.',
      'Baila diez segundos sin música.',
      'Enseña la última foto que hiciste.',
      'Enseña tu pantalla de inicio sin abrir nada.',
      'Lee en voz alta la última nota de tu móvil.',
      'Da el parte del tiempo como en la tele.',
      'Haz un discurso de agradecimiento por un premio inventado.',
      'Habla con acento hasta la siguiente ronda.',
      'Aguanta veinte segundos de plancha mientras cuentan.',
      'Cuenta tu talento más inútil y demuéstralo.',
      'Haz un cumplido sincero a cada persona.',
      'Explica tu trabajo como lo haría un niño de cinco años.',
      'Responde solo con preguntas hasta tu próximo turno.',
      'Di el abecedario al revés lo más rápido que puedas.',
      'Escribe a alguien con quien no hablas desde hace un año.',
      'Deja que el grupo elija tu próximo reto.',
      'Haz de robot durante un minuto.',
      'Hazte el peor selfie posible.',
    ],
    ContentTone.piccante: [
      'Lee en voz alta el último mensaje que enviaste.',
      'Enseña las últimas tres fotos de tu galería.',
      'Llama al tercer contacto de tu agenda y pregúntale qué tal.',
      'Deja que el grupo escriba un mensaje y mándalo de verdad.',
      'Enseña tu tiempo de uso y lee las tres apps top.',
      'Mira a los ojos a quien tienes enfrente treinta segundos.',
      'Cuenta tu peor primera cita.',
      'Enseña cómo ligas cuando lo intentas de verdad.',
      'Di qué dos personas de aquí harían buena pareja.',
      'Cuenta lo más vergonzoso que hiciste borracho.',
      'Susurra algo a quien tienes enfrente y luego cuéntalo a todos.',
      'Haz tu ranking sincero de los presentes.',
      'Di qué pensaste de verdad la primera vez que viste a quien tienes enfrente.',
      'Confiesa algo que nadie de esta sala sabe.',
      'Dale la mano a quien tienes a la derecha hasta la próxima ronda.',
      'Haz tu mejor baile sensual durante diez segundos.',
      'Deja que otro elija una foto tuya para publicar.',
      'Cuenta lo más descarado que te ha dicho un desconocido.',
      'Revela cuánto tiempo has pasado hoy en el móvil.',
      'Di a quién llamarías a las cuatro de la mañana con un drama.',
    ],
    ContentTone.cattivo: [
      'Di a cada uno lo primero que pensaste al conocerlo.',
      'Ordena a los presentes del más al menos fiable.',
      'Di quién de esta sala miente más, mirándolo a la cara.',
      'Di a quien tienes enfrente algo suyo que te irrita.',
      'Lee la última conversación con quien elija el grupo.',
      'Dale el móvil desbloqueado a quien tienes a la izquierda treinta segundos.',
      'Cuenta lo peor que le has hecho a un amigo.',
      'Confiesa algo por lo que nunca te has disculpado.',
      'Pide perdón ahora, delante de todos, a quien toque.',
      'Di quién de esta sala te ha decepcionado más.',
      'Di cuánto ganas o pierde el próximo turno.',
      'Cuenta lo más deshonesto que has hecho en el trabajo.',
      'Cuenta de qué te avergüenzas más.',
      'Di lo que nunca te has atrevido a decirle a tu familia.',
      'Di qué amistad de este grupo crees que no durará.',
      'Di a quién dejarías fuera del grupo si tuvieras que elegir.',
      'Enseña lo último que buscaste en internet.',
      'Di el peor pensamiento que has tenido esta noche.',
      'Responde con sinceridad absoluta a las próximas tres preguntas.',
      'Cierra la partida con una verdad que nadie espera.',
    ],
  };

  static const Map<String, List<String>> verita = {
    ContentTone.soft: [
      '¿Qué es lo más vergonzoso que has hecho en público?',
      '¿Cuál fue tu mentira más gorda de pequeño?',
      '¿Cuál es tu placer culpable musical?',
      '¿Qué película te ha hecho llorar más?',
      '¿Por la tontería más grande que has discutido?',
      '¿Qué es lo más caro que has roto?',
      '¿Qué excusa usas más a menudo?',
      '¿Qué haces cuando no te ve nadie?',
      '¿Cuánto tiempo pasas de verdad en el móvil?',
      '¿Qué es lo último que has buscado en internet?',
      '¿Quién es la última persona a la que escribiste?',
      '¿Qué es lo más bonito que te han dicho?',
      '¿A quién llamarías a las tres de la mañana con un problema serio?',
      '¿Cuál ha sido el mejor momento de tu año?',
      '¿Qué te da más miedo del futuro?',
      '¿Qué harías si no tuvieras que trabajar nunca más?',
      '¿Qué decisión cambiarías si pudieras?',
      '¿De qué estás más orgulloso?',
      '¿Cuál es tu talento oculto?',
      '¿A qué sitio volverías mañana mismo?',
    ],
    ContentTone.piccante: [
      '¿Te ha gustado alguna vez alguien de este grupo?',
      '¿Cuál fue tu enamoramiento más vergonzoso?',
      '¿Qué es lo más romántico que has hecho?',
      '¿Has besado a dos personas la misma noche?',
      '¿Has mentido a una pareja? ¿Sobre qué?',
      '¿Has mirado el móvil de tu pareja? ¿Qué buscabas?',
      '¿Has escrito a un ex sabiendo que era mala idea?',
      '¿Has hecho ghosting a alguien? ¿Por qué?',
      '¿Cuál es la peor excusa que has usado para no salir?',
      '¿Qué es lo peor que has dicho para cortar una relación?',
      '¿Has tenido una relación en secreto? ¿Quién lo sabía?',
      '¿Qué es lo más vergonzoso que has hecho borracho?',
      '¿Has fingido pasártelo bien en una fiesta?',
      '¿Cuál es la mentira más grande de tu perfil de citas?',
      '¿Has espiado a la nueva pareja de tu ex?',
      '¿Qué es lo más vergonzoso que tienes en el móvil?',
      '¿A quién de aquí le dejarías el móvil desbloqueado?',
      '¿A quién no se lo dejarías jamás?',
      '¿Qué es lo que te arrepientes de no haber dicho?',
      '¿Hay alguna pregunta de esta noche que hayas respondido con mentira?',
    ],
    ContentTone.cattivo: [
      '¿A quién de aquí no invitarías a tu boda?',
      '¿De quién de aquí has hablado a sus espaldas?',
      '¿A quién consideras amigo de verdad y a quién solo un conocido?',
      '¿Quién de aquí te ha decepcionado más?',
      '¿Has traicionado la confianza de alguien de esta sala?',
      '¿Cuál es la mentira que sigues contando hoy?',
      '¿A quién le debes una disculpa y por qué no se la has pedido?',
      '¿Qué es lo peor que le has hecho a un ex?',
      '¿Has sido infiel? ¿Lo volverías a hacer?',
      '¿Sigues enfadado con alguien de aquí? ¿Por qué?',
      '¿Te has alegrado alguna vez de la desgracia de otro?',
      '¿Qué es lo más egoísta que has hecho?',
      '¿Has dejado que otro pagara por un error tuyo?',
      '¿Cuánto ganas y te parece justo?',
      '¿Qué hay en tu móvil que rompería una amistad de esta sala?',
      '¿Qué emoción finges más a menudo?',
      '¿Qué parte de ti escondes mejor?',
      '¿Cuál es tu mayor fracaso y de quién fue la culpa de verdad?',
      '¿Hay alguien a quien quieres y no lo sabe?',
      '¿Qué no nos contarás nunca?',
    ],
  };

  static const List<String> bluffFakes = [
    'Una vez dormí doce horas seguidas en un aeropuerto.',
    'Aprendí a nadar a los dieciocho años.',
    'Perdí un vuelo por quedarme dormido en la puerta de embarque.',
    'De pequeño me perdí una hora en un centro comercial.',
    'Gané un concurso de baile en el colegio.',
    'Salí sin querer en la foto de boda de unos desconocidos.',
    'Trabajé una semana de camarero y me despidieron.',
    'Cociné para veinte personas sin haber cocinado nunca.',
    'Salí tres segundos en la televisión.',
    'Me encontré a un actor famoso en el supermercado.',
    'Hice cincuenta kilómetros a dedo.',
    'Dormí en el coche durante una tormenta en la montaña.',
    'Me subí al tren equivocado y acabé en otra provincia.',
    'Pasé un fin de año en el hospital con un amigo.',
    'Me caí de un árbol de pequeño y no me hice nada.',
    'Me rompí un brazo jugando al escondite.',
    'Me corté el pelo yo mismo en una mala época.',
    'Canté en un karaoke delante de cien personas.',
    'Toqué la guitarra en un grupo durante dos meses.',
    'Escribí una canción que no le he enseñado a nadie.',
    'Llevé un diario cinco años seguidos.',
    'Me leí un libro entero en una noche.',
    'He visto la misma película tres veces en el cine.',
    'Aprendí un idioma viendo series.',
    'Aprobé un examen sin haber estudiado nada.',
    'Viví en tres ciudades en dos años.',
    'Estuve un mes entero sin internet.',
    'Perdí el móvil en el mar.',
    'Me dejé la cartera en un tren y me la devolvieron.',
    'Encontré dinero en la calle y lo entregué.',
  ];

  static const List<String> impostoreWords = [
    'Playa', 'Montaña', 'Aeropuerto', 'Estación', 'Metro',
    'Hospital', 'Farmacia', 'Supermercado', 'Panadería', 'Pizzería',
    'Restaurante', 'Bar', 'Discoteca', 'Gimnasio', 'Piscina',
    'Biblioteca', 'Museo', 'Cine', 'Teatro', 'Estadio',
    'Colegio', 'Universidad', 'Oficina', 'Fábrica', 'Obra',
    'Peluquería', 'Dentista', 'Banco', 'Correos', 'Hotel',
    'Camping', 'Zoo', 'Acuario', 'Parque', 'Jardín',
    'Bosque', 'Desierto', 'Isla', 'Volcán', 'Cascada',
    'Ascensor', 'Escalera mecánica', 'Semáforo', 'Autopista', 'Ferry',
    'Avión', 'Tren', 'Bicicleta', 'Patinete', 'Moto',
    'Paraguas', 'Gafas', 'Reloj', 'Mochila', 'Maleta',
    'Cartera', 'Llaves', 'Móvil', 'Cargador', 'Auriculares',
  ];
}
