import '../content_tone.dart';

/// Contenuti di gioco in tedesco.
class ContentDe {
  const ContentDe._();

  static const List<({String text, String tone})>
  nonHoMai = <({String text, String tone})>[
    (
      text: 'mich krankgemeldet, obwohl mir nichts fehlte',
      tone: ContentTone.soft,
    ),
    (text: 'bis in den Nachmittag geschlafen', tone: ContentTone.soft),
    (
      text: 'etwas gegessen, das auf den Boden gefallen war',
      tone: ContentTone.soft,
    ),
    (text: 'unter der Dusche lauthals gesungen', tone: ContentTone.soft),
    (text: 'so getan, als kennte ich ein Lied', tone: ContentTone.soft),
    (
      text: 'den Geburtstag eines engen Freundes vergessen',
      tone: ContentTone.soft,
    ),
    (text: 'einen Flug oder Zug verpasst', tone: ContentTone.soft),
    (text: 'ganz allein verreist', tone: ContentTone.soft),
    (text: 'mir einen Knochen gebrochen', tone: ContentTone.soft),
    (text: 'mir ein Tattoo stechen lassen', tone: ContentTone.soft),
    (
      text: 'meine Haare in einer absurden Farbe gefärbt',
      tone: ContentTone.soft,
    ),
    (
      text: 'eine Nachricht an die falsche Person geschickt',
      tone: ContentTone.soft,
    ),
    (
      text: 'über einen Witz gelacht, den ich nicht verstanden habe',
      tone: ContentTone.soft,
    ),
    (text: 'laut mit mir selbst geredet', tone: ContentTone.soft),
    (text: 'bei einem Film geweint', tone: ContentTone.soft),
    (text: 'eine ganze Staffel an einem Tag geschaut', tone: ContentTone.soft),
    (text: 'das Abendessen komplett verbrannt', tone: ContentTone.soft),
    (text: 'mich aus der Wohnung ausgesperrt', tone: ContentTone.soft),
    (text: 'vergessen, wo ich geparkt habe', tone: ContentTone.soft),
    (
      text: 'so getan, als hätte ich jemanden auf der Straße nicht gesehen',
      tone: ContentTone.soft,
    ),
    (
      text: 'eine Ausrede erfunden, um zu Hause zu bleiben',
      tone: ContentTone.soft,
    ),
    (text: 'in letzter Sekunde abgesagt', tone: ContentTone.soft),
    (
      text: '„bin in fünf Minuten da" vom Sofa aus geschrieben',
      tone: ContentTone.soft,
    ),
    (text: 'hungrig einkaufen gegangen', tone: ContentTone.soft),
    (text: 'etwas gekauft und nie benutzt', tone: ContentTone.soft),
    (text: 'einen Preis gewonnen', tone: ContentTone.soft),
    (text: 'nüchtern Karaoke gesungen', tone: ContentTone.soft),
    (text: 'an einem Flughafen geschlafen', tone: ContentTone.soft),
    (text: 'im Auto geschlafen', tone: ContentTone.soft),
    (text: 'nachts im Meer gebadet', tone: ContentTone.soft),
    (text: 'als Erwachsener mit Licht geschlafen', tone: ContentTone.soft),
    (text: 'etwas kaputt gemacht und nichts gesagt', tone: ContentTone.soft),
    (text: 'jemand anderem meine Schuld zugeschoben', tone: ContentTone.soft),
    (text: 'bei einer Klassenarbeit abgeschrieben', tone: ContentTone.soft),
    (text: 'eine Mail ohne Anhang verschickt', tone: ContentTone.soft),
    (text: 'meinen eigenen Namen gegoogelt', tone: ContentTone.soft),
    (text: 'fremdes WLAN ohne Fragen benutzt', tone: ContentTone.soft),
    (text: 'meinem Auto einen Namen gegeben', tone: ContentTone.soft),
    (text: 'über mein Alter gelogen', tone: ContentTone.soft),
    (text: 'ein Geschenk weiterverschenkt', tone: ContentTone.soft),
    (text: 'jemanden am ersten Abend geküsst', tone: ContentTone.piccante),
    (
      text: 'für jemanden in diesem Raum geschwärmt',
      tone: ContentTone.piccante,
    ),
    (
      text: 'für den Partner eines Freundes geschwärmt',
      tone: ContentTone.piccante,
    ),
    (
      text: 'einem Ex mitten in der Nacht geschrieben',
      tone: ContentTone.piccante,
    ),
    (
      text: 'geschlafen getan, um einem Gespräch zu entgehen',
      tone: ContentTone.piccante,
    ),
    (
      text: 'das Handy meines Partners kontrolliert',
      tone: ContentTone.piccante,
    ),
    (text: 'zwei Dates an einem Tag gehabt', tone: ContentTone.piccante),
    (
      text: '„ich liebe dich" gesagt, ohne es zu meinen',
      tone: ContentTone.piccante,
    ),
    (text: 'per Nachricht Schluss gemacht', tone: ContentTone.piccante),
    (text: 'eine Beziehung geheim gehalten', tone: ContentTone.piccante),
    (text: 'geflirtet, um etwas zu bekommen', tone: ContentTone.piccante),
    (text: 'eine Dating-App benutzt', tone: ContentTone.piccante),
    (
      text: 'den Überblick verloren, wie viel ich getrunken hatte',
      tone: ContentTone.piccante,
    ),
    (text: 'die Nachrichten vom Vorabend bereut', tone: ContentTone.piccante),
    (text: 'einen ganzen Abend vergessen', tone: ContentTone.piccante),
    (text: 'ohne Badesachen gebadet', tone: ContentTone.piccante),
    (text: 'jemanden geghostet', tone: ContentTone.piccante),
    (
      text: 'den Screenshot eines privaten Chats weitergeschickt',
      tone: ContentTone.piccante,
    ),
    (
      text: 'mich drei Jahre zurück durch ein Profil gescrollt',
      tone: ContentTone.piccante,
    ),
    (text: 'gelogen, wo ich den Abend verbringe', tone: ContentTone.piccante),
    (
      text: 'einen Freund gebeten, mich aus einem Date zu retten',
      tone: ContentTone.piccante,
    ),
    (
      text: 'einen Geburtstag vorgetäuscht für ein Gratis-Dessert',
      tone: ContentTone.piccante,
    ),
    (text: 'in dieser Runde gelogen', tone: ContentTone.piccante),
  ];

  static const List<({String text, String tone})>
  chiLoPotrebbeFare = <({String text, String tone})>[
    (
      text: 'Wer würde sich in einer Stadt verlaufen, die er gut kennt?',
      tone: ContentTone.soft,
    ),
    (text: 'Wer käme zur eigenen Hochzeit zu spät?', tone: ContentTone.soft),
    (text: 'Wer würde aus Versehen berühmt?', tone: ContentTone.soft),
    (
      text: 'Wer würde auf einer einsamen Insel am längsten überleben?',
      tone: ContentTone.soft,
    ),
    (
      text: 'Wer würde ein ganzes Wochenende nicht rausgehen?',
      tone: ContentTone.soft,
    ),
    (
      text: 'Wer würde im Aufzug ein Gespräch anfangen?',
      tone: ContentTone.soft,
    ),
    (text: 'Wer würde mit dem Navi streiten?', tone: ContentTone.soft),
    (
      text: 'Wer würde nachts um drei online etwas bestellen?',
      tone: ContentTone.soft,
    ),
    (
      text: 'Wer würde sieben Tage hintereinander Pizza essen?',
      tone: ContentTone.soft,
    ),
    (text: 'Wer würde im Kino einschlafen?', tone: ContentTone.soft),
    (text: 'Wer würde ohne zu zögern Karaoke singen?', tone: ContentTone.soft),
    (text: 'Wer wäre zuerst auf der Tanzfläche?', tone: ContentTone.soft),
    (
      text: 'Wer würde den Urlaub für die ganze Gruppe organisieren?',
      tone: ContentTone.soft,
    ),
    (
      text: 'Wer würde den Pass am Flughafen verlieren?',
      tone: ContentTone.soft,
    ),
    (
      text: 'Wer würde drei Koffer für zwei Tage packen?',
      tone: ContentTone.soft,
    ),
    (
      text: 'Wer würde ohne nachzudenken ins Ausland ziehen?',
      tone: ContentTone.soft,
    ),
    (text: 'Wer würde zehn Katzen adoptieren?', tone: ContentTone.soft),
    (
      text: 'Wer würde jede Pflanze in der Wohnung eingehen lassen?',
      tone: ContentTone.soft,
    ),
    (
      text: 'Wer würde grundlos für zwanzig Leute kochen?',
      tone: ContentTone.soft,
    ),
    (
      text: 'Wer würde im Restaurant ein Gericht zurückgehen lassen?',
      tone: ContentTone.soft,
    ),
    (text: 'Wer würde das größte Trinkgeld geben?', tone: ContentTone.soft),
    (
      text: 'Wer würde genau beim Zahlen das Portemonnaie vergessen?',
      tone: ContentTone.soft,
    ),
    (
      text: 'Wer würde ein ganzes Gehalt in einer Woche ausgeben?',
      tone: ContentTone.soft,
    ),
    (text: 'Wer würde mit einer absurden Idee reich?', tone: ContentTone.soft),
    (
      text:
          'Wer meldet sich im Januar im Fitnessstudio an und hört im Februar auf?',
      tone: ContentTone.soft,
    ),
    (
      text: 'Wer würde ohne Training einen Marathon laufen?',
      tone: ContentTone.soft,
    ),
    (
      text: 'Wer würde wegen eines abgebrochenen Nagels in die Notaufnahme?',
      tone: ContentTone.soft,
    ),
    (
      text: 'Wer würde Symptome googeln und in Panik geraten?',
      tone: ContentTone.soft,
    ),
    (
      text: 'Wer stellt zehn Wecker und ignoriert alle?',
      tone: ContentTone.soft,
    ),
    (
      text: 'Wer verschickt Sprachnachrichten von sieben Minuten?',
      tone: ContentTone.soft,
    ),
    (
      text: 'Wer lässt dich tagelang auf Antwort warten?',
      tone: ContentTone.soft,
    ),
    (text: 'Wer hat immer 1% Akku?', tone: ContentTone.soft),
    (
      text: 'Wer macht hundert Fotos, um eins zu posten?',
      tone: ContentTone.soft,
    ),
    (text: 'Wer sagt zu allem Ja und bereut es dann?', tone: ContentTone.soft),
    (text: 'Wer geht als Letzter von einer Party?', tone: ContentTone.soft),
    (text: 'Wer geht, ohne sich zu verabschieden?', tone: ContentTone.soft),
    (text: 'Wer nimmt die Reste mit nach Hause?', tone: ContentTone.soft),
    (text: 'Wer merkt sich alle Geburtstage?', tone: ContentTone.soft),
    (text: 'Wer weint bei einer Werbung?', tone: ContentTone.soft),
    (text: 'Wer spoilert das Ende, ohne es zu merken?', tone: ContentTone.soft),
    (
      text: 'Wer würde einem Ex um drei Uhr nachts schreiben?',
      tone: ContentTone.piccante,
    ),
    (
      text: 'Wer würde zum dritten Mal zu einem Ex zurück?',
      tone: ContentTone.piccante,
    ),
    (
      text: 'Wer würde sich im Urlaub in zwei Tagen verlieben?',
      tone: ContentTone.piccante,
    ),
    (
      text: 'Wer würde zuerst „ich liebe dich" sagen?',
      tone: ContentTone.piccante,
    ),
    (
      text: 'Wer würde per Nachricht Schluss machen?',
      tone: ContentTone.piccante,
    ),
    (
      text: 'Wer würde vor allen mit dem Kellner flirten?',
      tone: ContentTone.piccante,
    ),
    (
      text: 'Wer hat gerade die meisten Chats offen?',
      tone: ContentTone.piccante,
    ),
    (
      text: 'Wer würde das Handy des Partners kontrollieren?',
      tone: ContentTone.piccante,
    ),
    (
      text: 'Wer würde eine Beziehung vor der Gruppe verheimlichen?',
      tone: ContentTone.piccante,
    ),
    (
      text: 'Wer würde für eine Wette jemanden küssen?',
      tone: ContentTone.piccante,
    ),
    (
      text: 'Wer würde jemanden ohne Erklärung ghosten?',
      tone: ContentTone.piccante,
    ),
    (
      text: 'Wer würde nach zwei Gläsern ein Geheimnis ausplaudern?',
      tone: ContentTone.piccante,
    ),
    (
      text: 'Wer würde am Ende auf einem Tisch singen?',
      tone: ContentTone.piccante,
    ),
    (
      text: 'Wer würde einen ganzen Abend vergessen?',
      tone: ContentTone.piccante,
    ),
    (
      text: 'Wer würde sich im Urlaub spontan tätowieren lassen?',
      tone: ContentTone.piccante,
    ),
    (
      text: 'Wer würde in Klamotten in den Pool springen?',
      tone: ContentTone.piccante,
    ),
    (
      text: 'Wer würde ein privates Gespräch belauschen?',
      tone: ContentTone.piccante,
    ),
    (text: 'Wer würde dir ins Gesicht lügen?', tone: ContentTone.cattivo),
    (
      text: 'Wer hier hat heute Abend schon gelogen?',
      tone: ContentTone.cattivo,
    ),
    (text: 'Wer denkt gerade an jemanden?', tone: ContentTone.cattivo),
  ];

  static const Map<String, List<String>> obblighi = {
    ContentTone.soft: [
      'Imitiere die Person rechts von dir, bis sie es merkt.',
      'Sing den Refrain des letzten Lieds, das du gehört hast.',
      'Sprich bis zu deinem nächsten Zug in Reimen.',
      'Tanz zehn Sekunden ohne Musik.',
      'Zeig das letzte Foto, das du gemacht hast.',
      'Zeig deinen Startbildschirm, ohne etwas zu öffnen.',
      'Lies die letzte Notiz auf deinem Handy laut vor.',
      'Präsentiere das Wetter wie im Fernsehen.',
      'Halte eine Dankesrede für einen erfundenen Preis.',
      'Sprich bis zur nächsten Runde mit Akzent.',
      'Halte zwanzig Sekunden Plank, während alle zählen.',
      'Erzähl dein nutzlosestes Talent und beweise es.',
      'Mach jedem hier ein ehrliches Kompliment.',
      'Erklär deinen Job so, wie es ein Fünfjähriger täte.',
      'Antworte bis zum nächsten Zug nur mit Fragen.',
      'Sag das Alphabet rückwärts, so schnell du kannst.',
      'Schreib jemandem, mit dem du seit einem Jahr nicht gesprochen hast.',
      'Lass die Gruppe deine nächste Aufgabe wählen.',
      'Sei eine Minute lang ein Roboter.',
      'Mach das schlechteste Selfie, das du hinkriegst.',
    ],
    ContentTone.piccante: [
      'Lies die letzte Nachricht vor, die du verschickt hast.',
      'Zeig die letzten drei Fotos in deiner Galerie.',
      'Ruf den dritten Kontakt im Handy an und frag, wie es ihm geht.',
      'Lass die Gruppe eine Nachricht schreiben und schick sie wirklich ab.',
      'Zeig deine Bildschirmzeit und lies die drei Top-Apps vor.',
      'Schau der Person gegenüber dreißig Sekunden in die Augen.',
      'Erzähl von deinem schlimmsten ersten Date.',
      'Zeig, wie du flirtest, wenn du es ernst meinst.',
      'Sag, welche zwei Personen hier gut zusammenpassen würden.',
      'Erzähl das Peinlichste, das du betrunken gemacht hast.',
      'Flüster der Person gegenüber etwas zu und sag es dann allen.',
      'Gib der Gruppe dein ehrliches Ranking der Anwesenden.',
      'Sag, was du wirklich dachtest, als du die Person gegenüber kennengelernt hast.',
      'Gestehe etwas, das niemand hier von dir weiß.',
      'Halte bis zur nächsten Runde die Hand der Person rechts von dir.',
      'Tanz zehn Sekunden so verführerisch du kannst.',
      'Lass jemand anderen ein Foto von dir zum Posten aussuchen.',
      'Erzähl das Frechste, das ein Fremder je zu dir gesagt hat.',
      'Verrate, wie lange du heute am Handy warst.',
      'Sag, wen du um vier Uhr nachts mit einem Drama anrufen würdest.',
    ],
    ContentTone.cattivo: [
      'Sag jedem, was du beim ersten Treffen über ihn gedacht hast.',
      'Sortiere die Anwesenden vom Verlässlichsten zum Unzuverlässigsten.',
      'Sag ins Gesicht, wer hier am meisten lügt.',
      'Sag der Person gegenüber eine Sache, die dich an ihr nervt.',
      'Lies das letzte Gespräch mit der Person vor, die die Gruppe wählt.',
      'Gib dein entsperrtes Handy dreißig Sekunden nach links.',
      'Erzähl das Schlimmste, das du einem Freund angetan hast.',
      'Gestehe etwas, wofür du dich nie entschuldigt hast.',
      'Entschuldige dich jetzt, vor allen, bei wem es nötig ist.',
      'Sag, wer hier dich am meisten enttäuscht hat.',
      'Sag, wie viel du verdienst, oder setz eine Runde aus.',
      'Erzähl das Unehrlichste, das du auf der Arbeit gemacht hast.',
      'Sag, wofür du dich am meisten schämst.',
      'Sag, was du deiner Familie nie zu sagen gewagt hast.',
      'Sag, welche Freundschaft in dieser Gruppe nicht halten wird.',
      'Sag, wen du aus der Gruppe streichen würdest, wenn du müsstest.',
      'Zeig, was du zuletzt im Netz gesucht hast.',
      'Sag den schlimmsten Gedanken, den du heute Abend hattest.',
      'Beantworte die nächsten drei Fragen völlig ehrlich.',
      'Beende die Runde mit einer Wahrheit, die niemand erwartet.',
    ],
  };

  static const Map<String, List<String>> verita = {
    ContentTone.soft: [
      'Was ist das Peinlichste, das du in der Öffentlichkeit gemacht hast?',
      'Was war deine größte Lüge als Kind?',
      'Was ist dein musikalisches Guilty Pleasure?',
      'Bei welchem Film hast du am meisten geweint?',
      'Wegen welcher Kleinigkeit hast du dich gestritten?',
      'Was ist das Teuerste, das du kaputt gemacht hast?',
      'Welche Ausrede benutzt du am häufigsten?',
      'Was machst du, wenn dich niemand sieht?',
      'Wie lange bist du wirklich am Handy?',
      'Was hast du zuletzt gesucht?',
      'Wem hast du zuletzt geschrieben?',
      'Was ist das Schönste, das jemand zu dir gesagt hat?',
      'Wen würdest du um drei Uhr nachts bei einem echten Problem anrufen?',
      'Was war dein bester Moment dieses Jahr?',
      'Wovor hast du in der Zukunft am meisten Angst?',
      'Was würdest du tun, wenn du nie wieder arbeiten müsstest?',
      'Welche Entscheidung würdest du ändern, wenn du könntest?',
      'Worauf bist du am stolzesten?',
      'Was ist dein verstecktes Talent?',
      'An welchen Ort würdest du morgen zurückkehren?',
    ],
    ContentTone.piccante: [
      'Hattest du je ein Auge auf jemanden in dieser Gruppe?',
      'Wer war dein peinlichster Schwarm?',
      'Was ist das Romantischste, das du getan hast?',
      'Hast du je zwei Menschen an einem Abend geküsst?',
      'Hast du je einen Partner angelogen? Worüber?',
      'Hast du je das Handy eines Partners kontrolliert? Wonach hast du gesucht?',
      'Hast du je einem Ex geschrieben, obwohl du wusstest, dass es falsch ist?',
      'Hast du je jemanden geghostet? Warum?',
      'Was ist die schlechteste Ausrede, um nicht rauszugehen?',
      'Was ist das Schlimmste, das du beim Schlussmachen gesagt hast?',
      'Hattest du je eine geheime Beziehung? Wer wusste davon?',
      'Was ist das Peinlichste, das du betrunken gemacht hast?',
      'Hast du je vorgetäuscht, dass dir eine Party gefällt?',
      'Was ist die größte Lüge in deinem Dating-Profil?',
      'Hast du je den neuen Partner deines Ex ausspioniert?',
      'Was ist das Peinlichste auf deinem Handy?',
      'Wem hier würdest du dein entsperrtes Handy geben?',
      'Wem hier auf keinen Fall?',
      'Was bereust du, nicht gesagt zu haben?',
      'Gibt es eine Frage heute Abend, die du gelogen beantwortet hast?',
    ],
    ContentTone.cattivo: [
      'Wen hier würdest du nicht zu deiner Hochzeit einladen?',
      'Über wen hier hast du hinter dem Rücken geredet?',
      'Wen hältst du für einen echten Freund und wen nur für eine Bekanntschaft?',
      'Wer hier hat dich am meisten enttäuscht?',
      'Hast du je das Vertrauen von jemandem in diesem Raum missbraucht?',
      'Welche Lüge erzählst du bis heute?',
      'Wem schuldest du eine Entschuldigung, und warum hast du sie nicht gemacht?',
      'Was ist das Schlimmste, das du einem Ex angetan hast?',
      'Hast du je jemanden betrogen? Würdest du es wieder tun?',
      'Bist du noch auf jemanden hier wütend? Weswegen?',
      'Hast du dich je über das Pech eines anderen gefreut?',
      'Was ist das Egoistischste, das du getan hast?',
      'Hast du je jemand anderen für deinen Fehler geradestehen lassen?',
      'Wie viel verdienst du, und findest du das fair?',
      'Was auf deinem Handy würde hier eine Freundschaft zerstören?',
      'Welches Gefühl täuschst du am häufigsten vor?',
      'Welchen Teil von dir versteckst du am besten?',
      'Was ist dein größter Fehlschlag, und wer war wirklich schuld?',
      'Gibt es jemanden, den du liebst und der es nicht weiß?',
      'Was wirst du keinem von uns je erzählen?',
    ],
  };

  static const List<String> bluffFakes = [
    'Einmal habe ich zwölf Stunden am Stück in einem Flughafen geschlafen.',
    'Schwimmen habe ich erst mit achtzehn gelernt.',
    'Ich habe einen Flug verpasst, weil ich am Gate eingeschlafen bin.',
    'Als Kind habe ich mich eine Stunde in einem Einkaufszentrum verlaufen.',
    'Ich habe in der Schule einen Tanzwettbewerb gewonnen.',
    'Ich bin aus Versehen auf dem Hochzeitsfoto von Fremden gelandet.',
    'Ich habe eine Woche als Kellner gearbeitet und wurde gefeuert.',
    'Ich habe für zwanzig Leute gekocht, ohne je gekocht zu haben.',
    'Ich war drei Sekunden lang im Fernsehen.',
    'Ich habe einen bekannten Schauspieler im Supermarkt getroffen.',
    'Ich bin fünfzig Kilometer per Anhalter gefahren.',
    'Ich habe bei einem Gewitter in den Bergen im Auto geschlafen.',
    'Ich bin in den falschen Zug gestiegen und in einem anderen Bundesland gelandet.',
    'Ich habe Silvester mit einem Freund im Krankenhaus verbracht.',
    'Als Kind bin ich von einem Baum gefallen und hatte nichts.',
    'Ich habe mir beim Versteckspielen den Arm gebrochen.',
    'Ich habe mir in einer schweren Zeit selbst die Haare geschnitten.',
    'Ich habe vor hundert Leuten Karaoke gesungen.',
    'Ich habe zwei Monate in einer Band Gitarre gespielt.',
    'Ich habe ein Lied geschrieben, das niemand je gehört hat.',
    'Ich habe fünf Jahre lang Tagebuch geführt.',
    'Ich habe ein ganzes Buch in einer Nacht gelesen.',
    'Ich habe denselben Film dreimal im Kino gesehen.',
    'Ich habe eine Sprache nur durch Serien gelernt.',
    'Ich habe eine Prüfung ohne jede Vorbereitung bestanden.',
    'Ich habe in zwei Jahren in drei Städten gewohnt.',
    'Ich war einen ganzen Monat ohne Internet.',
    'Ich habe mein Handy im Meer verloren.',
    'Ich habe meine Geldbörse im Zug vergessen und zurückbekommen.',
    'Ich habe Geld auf der Straße gefunden und abgegeben.',
  ];

  static const List<String> impostoreWords = [
    'Strand',
    'Berg',
    'Flughafen',
    'Bahnhof',
    'U-Bahn',
    'Krankenhaus',
    'Apotheke',
    'Supermarkt',
    'Bäckerei',
    'Pizzeria',
    'Restaurant',
    'Bar',
    'Club',
    'Fitnessstudio',
    'Schwimmbad',
    'Bibliothek',
    'Museum',
    'Kino',
    'Theater',
    'Stadion',
    'Schule',
    'Universität',
    'Büro',
    'Fabrik',
    'Baustelle',
    'Friseur',
    'Zahnarzt',
    'Bank',
    'Post',
    'Hotel',
    'Campingplatz',
    'Zoo',
    'Aquarium',
    'Park',
    'Garten',
    'Wald',
    'Wüste',
    'Insel',
    'Vulkan',
    'Wasserfall',
    'Aufzug',
    'Rolltreppe',
    'Ampel',
    'Autobahn',
    'Fähre',
    'Flugzeug',
    'Zug',
    'Fahrrad',
    'Roller',
    'Motorrad',
    'Regenschirm',
    'Brille',
    'Uhr',
    'Rucksack',
    'Koffer',
    'Geldbörse',
    'Schlüssel',
    'Handy',
    'Ladekabel',
    'Kopfhörer',
  ];
}
