import '../content_tone.dart';

/// Contenuti di gioco in francese: parità completa con i pool italiani.
class ContentFr {
  const ContentFr._();

  // ------------------------------------------------------------- nonHoMai
  static const List<({String text, String tone})>
  nonHoMai = <({String text, String tone})>[
    // soft
    (text: 'séché le travail ou les cours en me faisant passer pour malade', tone: ContentTone.soft),
    (text: 'dormi jusqu\'à midi passé', tone: ContentTone.soft),
    (text: 'mangé un truc tombé par terre', tone: ContentTone.soft),
    (text: 'chanté sous la douche à tue-tête', tone: ContentTone.soft),
    (text: 'fait semblant de connaître une chanson pour ne pas passer pour un nul', tone: ContentTone.soft),
    (text: 'oublié l\'anniversaire d\'un ami proche', tone: ContentTone.soft),
    (text: 'raté un train ou un avion', tone: ContentTone.soft),
    (text: 'voyagé tout seul', tone: ContentTone.soft),
    (text: 'cassé un os', tone: ContentTone.soft),
    (text: 'fait un tatouage', tone: ContentTone.soft),
    (text: 'teint mes cheveux d\'une couleur absurde', tone: ContentTone.soft),
    (text: 'envoyé un message à la mauvaise personne', tone: ContentTone.soft),
    (text: 'ri à une blague que je n\'avais pas comprise', tone: ContentTone.soft),
    (text: 'parlé tout seul à voix haute', tone: ContentTone.soft),
    (text: 'pleuré devant un film', tone: ContentTone.soft),
    (text: 'regardé une saison entière en un jour', tone: ContentTone.soft),
    (text: 'mangé la pizza avec des couverts', tone: ContentTone.soft),
    (text: 'mis de l\'ananas sur la pizza', tone: ContentTone.soft),
    (text: 'cuisiné un plat immangeable', tone: ContentTone.soft),
    (text: 'cramé le dîner', tone: ContentTone.soft),
    (text: 'oublié la plaque de cuisson allumée', tone: ContentTone.soft),
    (text: 'laissé mes clés enfermées à l\'intérieur', tone: ContentTone.soft),
    (text: 'oublié où j\'avais garé la voiture', tone: ContentTone.soft),
    (text: 'pris une amende', tone: ContentTone.soft),
    (text: 'fait semblant de ne pas voir une connaissance dans la rue', tone: ContentTone.soft),
    (text: 'inventé une excuse pour ne pas sortir', tone: ContentTone.soft),
    (text: 'annulé un plan à la dernière minute', tone: ContentTone.soft),
    (text: 'dit « j\'arrive dans cinq minutes » alors que j\'étais encore chez moi', tone: ContentTone.soft),
    (text: 'fait les courses en ayant faim', tone: ContentTone.soft),
    (text: 'acheté un truc que je n\'ai jamais utilisé', tone: ContentTone.soft),
    (text: 'dépensé trop pour un objet inutile', tone: ContentTone.soft),
    (text: 'gagné un prix', tone: ContentTone.soft),
    (text: 'chanté au karaoké', tone: ContentTone.soft),
    (text: 'dansé sans musique', tone: ContentTone.soft),
    (text: 'joué d\'un instrument devant quelqu\'un', tone: ContentTone.soft),
    (text: 'dormi dans un aéroport', tone: ContentTone.soft),
    (text: 'dormi dans une voiture', tone: ContentTone.soft),
    (text: 'dormi sous une tente', tone: ContentTone.soft),
    (text: 'nagé dans la mer en pleine nuit', tone: ContentTone.soft),
    (text: 'eu peur du noir en étant adulte', tone: ContentTone.soft),
    (text: 'dormi avec la lumière allumée', tone: ContentTone.soft),
    (text: 'crié à cause d\'un cauchemar', tone: ContentTone.soft),
    (text: 'marché en dormant', tone: ContentTone.soft),
    (text: 'ronflé au point de réveiller quelqu\'un', tone: ContentTone.soft),
    (text: 'mangé au lit', tone: ContentTone.soft),
    (text: 'sauté le petit-déjeuner une semaine entière', tone: ContentTone.soft),
    (text: 'bu un café oublié et complètement froid', tone: ContentTone.soft),
    (text: 'renversé un truc sur quelqu\'un', tone: ContentTone.soft),
    (text: 'cassé un objet précieux sans rien dire', tone: ContentTone.soft),
    (text: 'accusé quelqu\'un d\'autre à ma place', tone: ContentTone.soft),
    (text: 'triché à un contrôle', tone: ContentTone.soft),
    (text: 'fini un devoir la dernière nuit possible', tone: ContentTone.soft),
    (text: 'envoyé un mail sans la pièce jointe', tone: ContentTone.soft),
    (text: 'appelé quelqu\'un par le mauvais prénom en face', tone: ContentTone.soft),
    (text: 'oublié un mot de passe important', tone: ContentTone.soft),
    (text: 'cherché mon nom sur internet', tone: ContentTone.soft),
    (text: 'bloqué quelqu\'un sur les réseaux', tone: ContentTone.soft),
    (text: 'publié un truc et supprimé cinq minutes après', tone: ContentTone.soft),
    (text: 'prétendu que mon téléphone était déchargé pour ne pas répondre', tone: ContentTone.soft),
    (text: 'répondu après des jours en jurant ne rien avoir vu', tone: ContentTone.soft),
    (text: 'utilisé le wifi de quelqu\'un d\'autre sans demander', tone: ContentTone.soft),
    (text: 'chanté en voiture en fixant les autres conducteurs', tone: ContentTone.soft),
    (text: 'dansé tout seul dans un ascenseur', tone: ContentTone.soft),
    (text: 'parlé à un animal comme s\'il comprenait tout', tone: ContentTone.soft),
    (text: 'donné un prénom à ma voiture', tone: ContentTone.soft),
    (text: 'fait une promesse en sachant que je ne la tiendrais pas', tone: ContentTone.soft),
    (text: 'menti sur mon âge', tone: ContentTone.soft),
    (text: 'exagéré ma joie en ouvrant un cadeau', tone: ContentTone.soft),
    (text: 'offert à quelqu\'un un cadeau qu\'on m\'avait offert', tone: ContentTone.soft),
    (text: 'gardé pendant des années un truc qu\'on m\'avait prêté', tone: ContentTone.soft),
    (text: 'prêté de l\'argent sans jamais le revoir', tone: ContentTone.soft),
    (text: 'demandé une augmentation', tone: ContentTone.soft),
    (text: 'changé de travail sur un coup de tête', tone: ContentTone.soft),
    (text: 'passé un entretien pour un poste que je ne voulais pas', tone: ContentTone.soft),
    (text: 'mangé au fast-food deux fois le même jour', tone: ContentTone.soft),
    (text: 'mangé une glace au petit-déjeuner', tone: ContentTone.soft),
    (text: 'fait des heures de queue pour un truc', tone: ContentTone.soft),
    (text: 'oublié un rendez-vous important', tone: ContentTone.soft),
    (text: 'fait une scène pour la télécommande', tone: ContentTone.soft),
    (text: 'regardé le même film plus de cinq fois', tone: ContentTone.soft),
    (text: 'appris par cœur une scène de film', tone: ContentTone.soft),
    (text: 'perdu un pari stupide', tone: ContentTone.soft),
    (text: 'gagné aux cartes en trichant', tone: ContentTone.soft),
    (text: 'cassé un écran de téléphone', tone: ContentTone.soft),
    (text: 'oublié mon téléphone dans un bar', tone: ContentTone.soft),
    (text: 'foncé dans une porte vitrée impeccable', tone: ContentTone.soft),
    (text: 'salué quelqu\'un qui saluait en fait la personne derrière moi', tone: ContentTone.soft),
    (text: 'tiré une porte marquée « pousser »', tone: ContentTone.soft),
    (text: 'cherché mon téléphone en panique alors que je l\'avais dans la main', tone: ContentTone.soft),
    (text: 'appelé un prof « maman » devant tout le monde', tone: ContentTone.soft),
    (text: 'envoyé un vocal de cinq minutes pour un truc de dix secondes', tone: ContentTone.soft),
    (text: 'réécouté ma voix dans un vocal et eu honte', tone: ContentTone.soft),
    (text: 'fait semblant d\'être au téléphone pour éviter quelqu\'un', tone: ContentTone.soft),
    (text: 'applaudi à l\'atterrissage de l\'avion', tone: ContentTone.soft),
    (text: 'ri au pire moment possible', tone: ContentTone.soft),
    (text: 'trébuché en public et continué comme si de rien n\'était', tone: ContentTone.soft),
    (text: 'mis dix réveils et ignoré chacun d\'eux', tone: ContentTone.soft),
    (text: 'cherché mes symptômes en ligne et cru à une maladie rare', tone: ContentTone.soft),
    (text: 'pleuré devant une publicité', tone: ContentTone.soft),
    (text: 'répondu « vous aussi » au serveur qui me souhaitait bon appétit', tone: ContentTone.soft),
    (text: 'dormi pendant une visio avec la caméra allumée', tone: ContentTone.soft),
    (text: 'porté le même haut une semaine d\'affilée', tone: ContentTone.soft),
    (text: 'reniflé un tee-shirt pour décider s\'il était encore mettable', tone: ContentTone.soft),
    (text: 'mangé directement dans la casserole debout dans la cuisine', tone: ContentTone.soft),
    (text: 'dit « dernier épisode et je dors » puis vu le lever du soleil', tone: ContentTone.soft),
    (text: 'oublié pourquoi j\'étais entré dans une pièce', tone: ContentTone.soft),
    (text: 'ri tout seul en repensant à une honte d\'il y a des années', tone: ContentTone.soft),
    (text: 'mangé la pâte à tartiner à la cuillère directement dans le pot', tone: ContentTone.soft),
    (text: 'pleuré parce que j\'avais faim', tone: ContentTone.soft),
    (text: 'commandé une pizza entière rien que pour moi et tout fini', tone: ContentTone.soft),
    (text: 'engueulé le GPS à voix haute', tone: ContentTone.soft),
    (text: 'relu vingt fois un message avant de l\'envoyer', tone: ContentTone.soft),
    (text: 'demandé « juste les pointes » et quitté le coiffeur méconnaissable', tone: ContentTone.soft),
    (text: 'perdu des heures à regarder des vidéos d\'animaux', tone: ContentTone.soft),
    (text: 'convaincu quelqu\'un d\'un truc inventé pour rire', tone: ContentTone.soft),
    (text: 'fait semblant de travailler à l\'arrivée du chef', tone: ContentTone.soft),
    (text: 'envoyé « ok » juste pour clore une discussion', tone: ContentTone.soft),
    (text: 'mis mon pyjama à six heures du soir', tone: ContentTone.soft),
    (text: 'séché la salle de sport pour aller manger', tone: ContentTone.soft),
    (text: 'reporté le régime « à lundi » pendant des mois', tone: ContentTone.soft),
    (text: 'utilisé le vélo d\'appartement comme portemanteau', tone: ContentTone.soft),
    (text: 'dit « à bientôt » en espérant ne jamais revoir la personne', tone: ContentTone.soft),
    (text: 'parlé aux plantes de la maison', tone: ContentTone.soft),
    (text: 'accusé le chien pour un truc que j\'avais fait', tone: ContentTone.soft),
    (text: 'fini le popcorn avant le début du film', tone: ContentTone.soft),
    (text: 'caché des gâteaux pour ne pas les partager', tone: ContentTone.soft),
    (text: 'ouvert le frigo dix fois en espérant y trouver du nouveau', tone: ContentTone.soft),
    (text: 'utilisé l\'excuse « je me lève tôt demain » pour quitter une fête', tone: ContentTone.soft),
    (text: 'emballé un cadeau cinq minutes avant de l\'offrir', tone: ContentTone.soft),
    (text: 'commandé à emporter après avoir oublié de décongeler le dîner', tone: ContentTone.soft),
    (text: 'lu seulement le titre d\'un article et commenté en expert', tone: ContentTone.soft),
    (text: 'supporté une équipe juste parce qu\'elle gagnait', tone: ContentTone.soft),
    (text: 'pris la pluie pour ne pas avoir écouté la météo', tone: ContentTone.soft),
    (text: 'commencé dix livres sans en finir un', tone: ContentTone.soft),
    (text: 'liké un post sans l\'avoir lu', tone: ContentTone.soft),
    (text: 'pris cent photos identiques pour en choisir une', tone: ContentTone.soft),
    (text: 'demandé un avis sur une photo puis ignoré la réponse', tone: ContentTone.soft),
    (text: 'mis un filtre sur chaque photo publiée', tone: ContentTone.soft),
    (text: 'regardé mes propres stories plus que quiconque', tone: ContentTone.soft),
    (text: 'dansé dans ma chambre comme en concert', tone: ContentTone.soft),
    (text: 'répété un discours important devant le miroir', tone: ContentTone.soft),
    (text: 'gagné une dispute imaginaire sous la douche', tone: ContentTone.soft),
    (text: 'donné dix surnoms différents à mon animal', tone: ContentTone.soft),
    (text: 'mangé la dernière part sans demander à personne', tone: ContentTone.soft),
    (text: 'bu directement à la bouteille devant le frigo', tone: ContentTone.soft),
    (text: 'porté des chaussettes dépareillées en espérant que ça passe', tone: ContentTone.soft),
    (text: 'dormi avec une peluche en étant adulte', tone: ContentTone.soft),
    (text: 'vérifié derrière les rideaux après un film d\'horreur', tone: ContentTone.soft),
    (text: 'monté l\'escalier en courant après avoir éteint la lumière', tone: ContentTone.soft),
    (text: 'exulté pour un créneau réussi du premier coup', tone: ContentTone.soft),
    (text: 'déclaré la guerre à un moustique à trois heures du matin', tone: ContentTone.soft),
    (text: 'allumé la clim pour dormir sous la couette', tone: ContentTone.soft),
    (text: 'écrit une liste de choses à faire et complètement ignorée', tone: ContentTone.soft),
    (text: 'fait semblant d\'avoir lu un livre célèbre', tone: ContentTone.soft),
    (text: 'perdu le fil de la conversation alors que c\'était moi qui parlais', tone: ContentTone.soft),
    // piccante
    (text: 'embrassé quelqu\'un le premier soir', tone: ContentTone.piccante),
    (text: 'eu un crush sur quelqu\'un de ce groupe', tone: ContentTone.piccante),
    (text: 'eu un crush sur le partenaire d\'un ami', tone: ContentTone.piccante),
    (text: 'écrit à un ex en pleine nuit', tone: ContentTone.piccante),
    (text: 'répondu à un ex après des mois de silence', tone: ContentTone.piccante),
    (text: 'fait semblant de dormir pour éviter un moment d\'intimité', tone: ContentTone.piccante),
    (text: 'menti à la personne que je fréquentais', tone: ContentTone.piccante),
    (text: 'fouillé le téléphone d\'un partenaire', tone: ContentTone.piccante),
    (text: 'eu deux rencards le même jour', tone: ContentTone.piccante),
    (text: 'embrassé deux personnes dans la même soirée', tone: ContentTone.piccante),
    (text: 'dit « je t\'aime » sans le penser vraiment', tone: ContentTone.piccante),
    (text: 'rompu par message', tone: ContentTone.piccante),
    (text: 'recollé les morceaux avec un ex', tone: ContentTone.piccante),
    (text: 'caché une relation', tone: ContentTone.piccante),
    (text: 'flirté pour obtenir quelque chose', tone: ContentTone.piccante),
    (text: 'utilisé une appli de rencontres', tone: ContentTone.piccante),
    (text: 'utilisé une photo de profil vieille de dix ans', tone: ContentTone.piccante),
    (text: 'rencontré en vrai quelqu\'un connu en ligne', tone: ContentTone.piccante),
    (text: 'dédié une chanson à quelqu\'un présent dans cette pièce', tone: ContentTone.piccante),
    (text: 'dormi chez quelqu\'un que je venais de rencontrer', tone: ContentTone.piccante),
    (text: 'perdu le compte de ce que j\'avais bu', tone: ContentTone.piccante),
    (text: 'fait un truc gênant en étant ivre', tone: ContentTone.piccante),
    (text: 'regretté au réveil les messages de la veille', tone: ContentTone.piccante),
    (text: 'oublié des morceaux entiers d\'une soirée', tone: ContentTone.piccante),
    (text: 'chanté dans la rue à quatre heures du matin', tone: ContentTone.piccante),
    (text: 'nagé sans maillot', tone: ContentTone.piccante),
    (text: 'circulé chez moi sans vêtements avec de la visite à la maison', tone: ContentTone.piccante),
    (text: 'oublié de fermer la porte de la salle de bain', tone: ContentTone.piccante),
    (text: 'sorti un énorme mensonge à un premier rencard', tone: ContentTone.piccante),
    (text: 'fait semblant d\'être célibataire', tone: ContentTone.piccante),
    (text: 'espionné le profil du nouveau partenaire de mon ex', tone: ContentTone.piccante),
    (text: 'eu une dispute en public avec un partenaire', tone: ContentTone.piccante),
    (text: 'fait la paix avec un baiser sans rien régler', tone: ContentTone.piccante),
    (text: 'embrassé quelqu\'un pour un pari', tone: ContentTone.piccante),
    (text: 'regretté une réponse donnée à Action ou Vérité', tone: ContentTone.piccante),
    (text: 'entendu les voisins faire l\'amour à travers le mur', tone: ContentTone.piccante),
    (text: 'eu un flirt au travail', tone: ContentTone.piccante),
    (text: 'écrit au chef des choses que je n\'aurais pas dû', tone: ContentTone.piccante),
    (text: 'posé un lapin sans prévenir', tone: ContentTone.piccante),
    (text: 'dit « tu montes boire un verre ? » en sachant très bien ce que je voulais dire', tone: ContentTone.piccante),
    (text: 'embrassé quelqu\'un dans les toilettes d\'un bar', tone: ContentTone.piccante),
    (text: 'passé un film entier au cinéma sans en regarder une seule scène', tone: ContentTone.piccante),
    (text: 'gardé une photo gênante d\'un ami', tone: ContentTone.piccante),
    (text: 'remonté le profil de quelqu\'un jusqu\'à trois ans en arrière', tone: ContentTone.piccante),
    (text: 'répondu à une story juste pour me faire remarquer', tone: ContentTone.piccante),
    (text: 'menti sur l\'endroit où je passais la soirée', tone: ContentTone.piccante),
    (text: 'dit que j\'étais chez moi alors que j\'étais dehors', tone: ContentTone.piccante),
    (text: 'caché une relation à ma famille', tone: ContentTone.piccante),
    (text: 'embrassé quelqu\'un dont je ne me rappelais pas le prénom', tone: ContentTone.piccante),
    (text: 'demandé à un ami de m\'appeler pour fuir un rencard', tone: ContentTone.piccante),
    (text: 'quitté un bar en douce pour ne dire au revoir à personne', tone: ContentTone.piccante),
    (text: 'fini la soirée dans un endroit dont je ne me souviens pas', tone: ContentTone.piccante),
    (text: 'donné mon numéro à quelqu\'un tout juste rencontré dans un bar', tone: ContentTone.piccante),
    (text: 'menti pendant cette partie', tone: ContentTone.piccante),
    (text: 'ghosté quelqu\'un sans explication', tone: ContentTone.piccante),
    (text: 'relu une vieille conversation par nostalgie', tone: ContentTone.piccante),
    (text: 'liké une photo d\'il y a trois ans en plein stalking nocturne', tone: ContentTone.piccante),
    (text: 'inventé un partenaire imaginaire pour me débarrasser de quelqu\'un', tone: ContentTone.piccante),
    (text: 'répété des phrases de drague devant le miroir', tone: ContentTone.piccante),
    (text: 'embrassé l\'ex d\'un ami', tone: ContentTone.piccante),
    (text: 'demandé à un ami d\'enquêter pour savoir si je plaisais à quelqu\'un', tone: ContentTone.piccante),
    (text: 'vomi dans un endroit absurde pendant une soirée', tone: ContentTone.piccante),
    (text: 'eu une histoire d\'un soir', tone: ContentTone.piccante),
    (text: 'fait le trajet de la honte avec les vêtements de la veille', tone: ContentTone.piccante),
    (text: 'envoyé une photo que je n\'enverrais jamais à mes parents', tone: ContentTone.piccante),
    (text: 'fait un rêve coquin sur une personne présente dans cette pièce', tone: ContentTone.piccante),
    (text: 'flirté avec quelqu\'un du personnel pour avoir des verres gratuits', tone: ContentTone.piccante),
    (text: 'passé la nuit dehors en mentant sur où j\'étais', tone: ContentTone.piccante),
    (text: 'enregistré un contact sous un faux nom pour ne pas me faire griller', tone: ContentTone.piccante),
    (text: 'embrassé quelqu\'un juste parce que c\'était minuit au Nouvel An', tone: ContentTone.piccante),
    (text: 'échangé des sextos jusque tard dans la nuit', tone: ContentTone.piccante),
    (text: 'lancé moi-même une conversation qui a fini en sextos', tone: ContentTone.piccante),
    (text: 'embrassé quelqu\'un de beaucoup plus âgé ou plus jeune que moi', tone: ContentTone.piccante),
    (text: 'eu un fantasme sur un collègue', tone: ContentTone.piccante),
    (text: 'fait un massage qui a fini en tout autre chose', tone: ContentTone.piccante),
    (text: 'embrassé quelqu\'un moins d\'une heure après l\'avoir rencontré', tone: ContentTone.piccante),
    (text: 'acheté de la lingerie en pensant à qui la verrait', tone: ContentTone.piccante),
    (text: 'flirté à la salle de sport au lieu de m\'entraîner', tone: ContentTone.piccante),
    (text: 'eu un flirt d\'été terminé avec la fin des vacances', tone: ContentTone.piccante),
    (text: 'embrassé quelqu\'un dans un ascenseur', tone: ContentTone.piccante),
    (text: 'pris une douche avec quelqu\'un d\'autre', tone: ContentTone.piccante),
    (text: 'partagé le lit d\'un ami en me demandant s\'il allait se passer quelque chose', tone: ContentTone.piccante),
    (text: 'embrassé quelqu\'un pendant un jeu comme celui-ci', tone: ContentTone.piccante),
    (text: 'envoyé ma position à un ami avant un rencard à l\'aveugle', tone: ContentTone.piccante),
    (text: 'tenté de draguer avec une phrase trouvée en ligne', tone: ContentTone.piccante),
    (text: 'fait un compliment osé à un inconnu', tone: ContentTone.piccante),
    (text: 'pris un râteau devant tout le monde', tone: ContentTone.piccante),
    // cattivo
    (text: 'dit du mal d\'une personne présente dans cette pièce', tone: ContentTone.cattivo),
    (text: 'révélé le secret d\'un ami', tone: ContentTone.cattivo),
    (text: 'partagé la capture d\'écran d\'une conversation privée', tone: ContentTone.cattivo),
    (text: 'créé un faux profil pour espionner quelqu\'un', tone: ContentTone.cattivo),
    (text: 'secrètement savouré l\'échec de quelqu\'un que je ne supporte pas', tone: ContentTone.cattivo),
    (text: 'fait semblant d\'être content pour un ami en rageant à l\'intérieur', tone: ContentTone.cattivo),
    (text: 'pensé que le partenaire d\'un ami ne le méritait pas du tout', tone: ContentTone.cattivo),
    (text: 'espéré qu\'un couple d\'amis finisse par se séparer', tone: ContentTone.cattivo),
    (text: 'dit « je ne le dirai à personne » et tout balancé en moins d\'une heure', tone: ContentTone.cattivo),
    (text: 'créé un groupe sans une personne juste pour parler d\'elle', tone: ContentTone.cattivo),
    (text: 'flirté avec quelqu\'un juste pour rendre jalouse une autre personne', tone: ContentTone.cattivo),
    (text: 'donné un mauvais conseil exprès', tone: ContentTone.cattivo),
    (text: 'gâché une surprise volontairement', tone: ContentTone.cattivo),
    (text: 'fait semblant d\'avoir oublié mon portefeuille pour ne pas payer', tone: ContentTone.cattivo),
    (text: 'répété un ragot en ajoutant des détails inventés', tone: ContentTone.cattivo),
    (text: 'utilisé les larmes pour obtenir ce que je voulais', tone: ContentTone.cattivo),
    (text: 'lu une conversation sur le téléphone d\'un ami pendant qu\'il était aux toilettes', tone: ContentTone.cattivo),
    (text: 'fait semblant d\'écouter les problèmes d\'un ami en pensant à mes affaires', tone: ContentTone.cattivo),
    (text: 'nié jusqu\'à la mort un truc que j\'avais vraiment fait', tone: ContentTone.cattivo),
    (text: 'cassé du sucre sur le dos de quelqu\'un et tout nié quand on me l\'a demandé en face', tone: ContentTone.cattivo),
    (text: 'utilisé le secret de quelqu\'un pour gagner une dispute', tone: ContentTone.cattivo),
    (text: 'partagé l\'addition à parts égales en sachant que j\'avais commandé trois fois plus que les autres', tone: ContentTone.cattivo),
    (text: 'invité une personne juste parce qu\'elle avait une voiture', tone: ContentTone.cattivo),
    (text: 'caché à un ami que son partenaire flirtait avec d\'autres', tone: ContentTone.cattivo),
    (text: 'supprimé un message du téléphone de quelqu\'un d\'autre', tone: ContentTone.cattivo),
    (text: 'fait l\'amour dans un lieu public', tone: ContentTone.cattivo),
    (text: 'eu un sex friend en le cachant à tout le monde', tone: ContentTone.cattivo),
    (text: 'envoyé un message coquin à la mauvaise personne', tone: ContentTone.cattivo),
    (text: 'revu un ex juste pour une nuit en jurant que c\'était la dernière', tone: ContentTone.cattivo),
    (text: 'oublié le prénom de quelqu\'un avec qui j\'avais passé la nuit', tone: ContentTone.cattivo),
    (text: 'pensé à quelqu\'un d\'autre en embrassant mon partenaire', tone: ContentTone.cattivo),
    (text: 'menti sur le nombre de mes conquêtes', tone: ContentTone.cattivo),
    (text: 'fait l\'amour à une fête alors que la maison était pleine de monde', tone: ContentTone.cattivo),
    (text: 'utilisé mon charme pour me faire pardonner un truc grave', tone: ContentTone.cattivo),
    (text: 'passé la nuit avec quelqu\'un rencontré le soir même sur une appli', tone: ContentTone.cattivo),
    (text: 'fait ou rêvé de faire un plan à trois', tone: ContentTone.cattivo),
    (text: 'trompé un partenaire', tone: ContentTone.cattivo),
    (text: 'embrassé quelqu\'un d\'autre alors que j\'étais en couple', tone: ContentTone.cattivo),
    (text: 'envoyé une photo de moi sans vêtements', tone: ContentTone.cattivo),
    (text: 'montré à un ami une photo hot reçue en privé', tone: ContentTone.cattivo),
    (text: 'passé la nuit avec l\'ex d\'un ami', tone: ContentTone.cattivo),
    (text: 'fait l\'amour dans une voiture', tone: ContentTone.cattivo),
    (text: 'fait l\'amour chez les parents de mon partenaire', tone: ContentTone.cattivo),
    (text: 'couché avec deux personnes différentes dans la même semaine', tone: ContentTone.cattivo),
    (text: 'eu une histoire avec une personne déjà en couple', tone: ContentTone.cattivo),
    (text: 'simulé le plaisir au lit', tone: ContentTone.cattivo),
    (text: 'noté les performances de mes ex en en parlant avec mes amis', tone: ContentTone.cattivo),
    (text: 'utilisé le sexe pour me faire pardonner après une dispute', tone: ContentTone.cattivo),
    (text: 'écrit à quelqu\'un à trois heures du matin avec une seule idée en tête', tone: ContentTone.cattivo),
    (text: 'passé une nuit torride avec quelqu\'un de ce groupe', tone: ContentTone.cattivo),
    (text: 'imaginé comment serait au lit une personne présente dans cette pièce', tone: ContentTone.cattivo),
    (text: 'comparé un partenaire à un ex au lit', tone: ContentTone.cattivo),
    (text: 'gardé une conversation secrète avec un ex alors que j\'étais en couple', tone: ContentTone.cattivo),
    (text: 'accepté une invitation à « regarder un film » en sachant comment ça finirait', tone: ContentTone.cattivo),
    (text: 'flirté avec le partenaire d\'un ami', tone: ContentTone.cattivo),
    (text: 'envoyé un message hot alors que j\'étais à table avec d\'autres gens', tone: ContentTone.cattivo),
    (text: 'échangé des sextos pendant que mon partenaire était dans la pièce d\'à côté', tone: ContentTone.cattivo),
    (text: 'gardé un plan B sous le coude alors que j\'étais en couple', tone: ContentTone.cattivo),
    (text: 'embrassé quelqu\'un juste pour me venger d\'un ex', tone: ContentTone.cattivo),
    (text: 'couché avec une personne que je ne supportais pas', tone: ContentTone.cattivo),
    (text: 'fait espérer quelqu\'un juste pour le mettre dans mon lit', tone: ContentTone.cattivo),
    (text: 'ghosté quelqu\'un après avoir passé la nuit avec', tone: ContentTone.cattivo),
    (text: 'gardé les photos hot d\'un ex après la rupture', tone: ContentTone.cattivo),
    (text: 'raconté partout les détails intimes d\'un ex', tone: ContentTone.cattivo),
    (text: 'simulé des sentiments juste pour ne pas rester seul', tone: ContentTone.cattivo),
    (text: 'tenté de séduire la personne qui plaisait à un ami', tone: ContentTone.cattivo),
    (text: 'disparu juste après avoir obtenu ce que je voulais', tone: ContentTone.cattivo),
    (text: 'dit « je t\'aime » au lit juste pour le moment', tone: ContentTone.cattivo),
    (text: 'fait l\'amour en sachant qu\'on nous entendait depuis la pièce d\'à côté', tone: ContentTone.cattivo),
    (text: 'répondu à un ex alors que j\'étais au lit avec quelqu\'un d\'autre', tone: ContentTone.cattivo),
    // piccante (extra)
    (text: 'couché dès le premier rencard', tone: ContentTone.piccante),
    (text: 'simulé un orgasme', tone: ContentTone.piccante),
    (text: 'échangé des sextos avec quelqu\'un rencontré moins de vingt-quatre heures plus tôt', tone: ContentTone.piccante),
    (text: 'demandé en premier une photo osée', tone: ContentTone.piccante),
    (text: 'reçu une photo hot non sollicitée et répondu par un compliment', tone: ContentTone.piccante),
    (text: 'fait l\'amour dans un endroit public', tone: ContentTone.piccante),
    (text: 'embué les vitres d\'une voiture, et pas à cause du froid', tone: ContentTone.piccante),
    (text: 'couché chez des inconnus pendant une fête', tone: ContentTone.piccante),
    (text: 'passé la nuit avec quelqu\'un dont je ne me rappelais pas le prénom', tone: ContentTone.piccante),
    (text: 'croisé une connaissance pendant le trajet de la honte et salué comme si de rien n\'était', tone: ContentTone.piccante),
    (text: 'embrassé quelqu\'un juste parce que c\'était la bonne soirée', tone: ContentTone.piccante),
    (text: 'embrassé quelqu\'un dans les dix premières minutes du premier rencard', tone: ContentTone.piccante),
    (text: 'embrassé une personne du même sexe', tone: ContentTone.piccante),
    (text: 'désiré quelqu\'un présent dans cette pièce', tone: ContentTone.piccante),
    (text: 'fait un rêve érotique sur un ami', tone: ContentTone.piccante),
    (text: 'imaginé tout un futur avec quelqu\'un à peine rencontré', tone: ContentTone.piccante),
    (text: 'eu une relation purement physique qui a duré plus de six mois', tone: ContentTone.piccante),
    (text: 'dit « je t\'aime » juste pour finir la soirée', tone: ContentTone.piccante),
    (text: 'fait la paix au lit après une dispute déclenchée exprès', tone: ContentTone.piccante),
    (text: 'flirté avec quelqu\'un pour me faire offrir un truc', tone: ContentTone.piccante),
    (text: 'donné un faux numéro à quelqu\'un qui me draguait', tone: ContentTone.piccante),
    (text: 'utilisé une phrase de drague trouvée sur internet', tone: ContentTone.piccante),
    (text: 'dragué à la salle de sport', tone: ContentTone.piccante),
    (text: 'dragué à un mariage', tone: ContentTone.piccante),
    (text: 'dragué au supermarché', tone: ContentTone.piccante),
    (text: 'embrassé mon meilleur ami ou ma meilleure amie', tone: ContentTone.piccante),
    (text: 'ressenti de l\'attirance pour le partenaire d\'un ami', tone: ContentTone.piccante),
    (text: 'couché avec un collègue', tone: ContentTone.piccante),
    (text: 'eu une histoire avec quelqu\'un de beaucoup plus âgé que moi', tone: ContentTone.piccante),
    (text: 'menti sur mon body count', tone: ContentTone.piccante),
    (text: 'oublié le prénom de quelqu\'un pendant qu\'on était au lit', tone: ContentTone.piccante),
    (text: 'fait semblant de dormir pour esquiver un moment intime', tone: ContentTone.piccante),
    (text: 'fait l\'amour en gardant mes chaussettes', tone: ContentTone.piccante),
    (text: 'ri pendant un moment intime en gâchant tout', tone: ContentTone.piccante),
    (text: 'envoyé un message hot à la mauvaise personne', tone: ContentTone.piccante),
    (text: 'relu mes sextos et ressenti de la fierté', tone: ContentTone.piccante),
    (text: 'créé une playlist exprès pour les nuits en bonne compagnie', tone: ContentTone.piccante),
    (text: 'regardé mon téléphone pendant que l\'autre dormait à côté de moi', tone: ContentTone.piccante),
    (text: 'cherché sur internet comment m\'améliorer au lit', tone: ContentTone.piccante),
    (text: 'demandé à un ami un avis honnête sur mes talents', tone: ContentTone.piccante),
    (text: 'regardé un film pour adultes en compagnie', tone: ContentTone.piccante),
    (text: 'acheté de la lingerie exprès pour une nuit précise', tone: ContentTone.piccante),
    (text: 'fait l\'amour sous la douche', tone: ContentTone.piccante),
    (text: 'fait l\'amour sur le canapé de quelqu\'un d\'autre', tone: ContentTone.piccante),
    (text: 'fait du bruit exprès pour qu\'on nous entende', tone: ContentTone.piccante),
    (text: 'dû me cacher en vitesse à l\'arrivée de quelqu\'un', tone: ContentTone.piccante),
    (text: 'remis mes vêtements en vitesse et enfilé le mauvais tee-shirt', tone: ContentTone.piccante),
    (text: 'laissé des marques visibles dans le cou de quelqu\'un', tone: ContentTone.piccante),
    (text: 'camouflé un suçon avec du maquillage ou une écharpe', tone: ContentTone.piccante),
    (text: 'dit à un partenaire qu\'il était le meilleur, en mentant', tone: ContentTone.piccante),
    (text: 'noté une nuit en en parlant avec mes amis le lendemain', tone: ContentTone.piccante),
    (text: 'fait des classements de mes ex avec mes amis', tone: ContentTone.piccante),
    (text: 'recroisé un coup d\'un soir sur mon lieu de travail', tone: ContentTone.piccante),
    (text: 'flirté avec deux personnes en même temps dans la même soirée', tone: ContentTone.piccante),
    (text: 'utilisé une appli de rencontres assis à côté de mes parents', tone: ContentTone.piccante),
    (text: 'eu un match et jamais écrit par peur', tone: ContentTone.piccante),
    (text: 'fait le premier pas et encaissé un non', tone: ContentTone.piccante),
    (text: 'embrassé quelqu\'un sous la pluie en me croyant dans un film', tone: ContentTone.piccante),
    (text: 'organisé une rencontre « par hasard » avec mon crush', tone: ContentTone.piccante),
    (text: 'proposé un massage avec des arrière-pensées évidentes', tone: ContentTone.piccante),
    (text: 'accepté un massage en sachant très bien où ça allait finir', tone: ContentTone.piccante),
    (text: 'pris le petit-déjeuner au lit avec quelqu\'un rencontré la veille', tone: ContentTone.piccante),
    (text: 'gardé une brosse à dents de secours pour les invités d\'un soir', tone: ContentTone.piccante),
    // cattivo (extra)
    (text: 'couché avec quelqu\'un présent dans cette pièce', tone: ContentTone.cattivo),
    (text: 'couché avec plus d\'une personne dans les mêmes vingt-quatre heures', tone: ContentTone.cattivo),
    (text: 'fait un plan à trois', tone: ContentTone.cattivo),
    (text: 'reçu une proposition de plan à trois et accepté', tone: ContentTone.cattivo),
    (text: 'couché avec une personne en couple en le sachant', tone: ContentTone.cattivo),
    (text: 'trompé sans jamais l\'avouer', tone: ContentTone.cattivo),
    (text: 'découvert une tromperie et fait comme si de rien n\'était', tone: ContentTone.cattivo),
    (text: 'couché avec l\'ex de mon meilleur ami', tone: ContentTone.cattivo),
    (text: 'utilisé des jouets, seul ou en compagnie', tone: ContentTone.cattivo),
    (text: 'acheté un jouet en ligne en vérifiant le colis toutes les heures', tone: ContentTone.cattivo),
    (text: 'filmé une vidéo pendant que je faisais l\'amour', tone: ContentTone.cattivo),
    (text: 'revu cette vidéo', tone: ContentTone.cattivo),
    (text: 'gardé des photos hot dans mon téléphone sans mot de passe', tone: ContentTone.cattivo),
    (text: 'envoyé la même photo hot à plusieurs personnes', tone: ContentTone.cattivo),
    (text: 'simulé un orgasme plus d\'une fois avec la même personne', tone: ContentTone.cattivo),
    (text: 'dit le mauvais prénom au lit', tone: ContentTone.cattivo),
    (text: 'entendu le mauvais prénom et fait comme si de rien n\'était', tone: ContentTone.cattivo),
    (text: 'fait l\'amour dans des toilettes publiques', tone: ContentTone.cattivo),
    (text: 'fait l\'amour en plein air en risquant d\'être vu', tone: ContentTone.cattivo),
    (text: 'été pris en flagrant délit par quelqu\'un', tone: ContentTone.cattivo),
    (text: 'surpris quelqu\'un en flagrant délit', tone: ContentTone.cattivo),
    (text: 'fait l\'amour pendant que d\'autres dormaient dans la même pièce', tone: ContentTone.cattivo),
    (text: 'fait l\'amour chez mes parents alors qu\'ils étaient à la maison', tone: ContentTone.cattivo),
    (text: 'fait l\'amour chez ses parents alors qu\'ils étaient à la maison', tone: ContentTone.cattivo),
    (text: 'séché le travail pour rester au lit en bonne compagnie', tone: ContentTone.cattivo),
    (text: 'fait l\'amour pendant les heures de travail', tone: ContentTone.cattivo),
    (text: 'utilisé le bureau d\'une façon pas très professionnelle', tone: ContentTone.cattivo),
    (text: 'eu un sérieux faible pour un supérieur', tone: ContentTone.cattivo),
    (text: 'couché avec un ami sans jamais en reparler', tone: ContentTone.cattivo),
    (text: 'ruiné une amitié pour une nuit', tone: ContentTone.cattivo),
    (text: 'mené deux histoires en parallèle sans que personne ne le sache', tone: ContentTone.cattivo),
    (text: 'écrit aux deux le même soir sans me faire griller', tone: ContentTone.cattivo),
    (text: 'utilisé l\'appart d\'un ami pour un rendez-vous secret', tone: ContentTone.cattivo),
    (text: 'fait entrer quelqu\'un en douce et sortir à l\'aube', tone: ContentTone.cattivo),
    (text: 'caché une personne dans l\'armoire ou sur le balcon, littéralement', tone: ContentTone.cattivo),
    (text: 'supprimé des messages pour qu\'on ne les trouve pas', tone: ContentTone.cattivo),
    (text: 'enregistré une personne dans mes contacts sous un faux nom', tone: ContentTone.cattivo),
    (text: 'pensé à quelqu\'un de cette pièce pendant que j\'étais avec une autre personne', tone: ContentTone.cattivo),
    (text: 'commencé un truc dans un bar et fini sur le parking', tone: ContentTone.cattivo),
    (text: 'couché sans connaître le nom de famille de l\'autre', tone: ContentTone.cattivo),
    (text: 'dépassé la limite avec un sex friend et fait comme si rien n\'avait changé', tone: ContentTone.cattivo),
    (text: 'gardé un sex friend secret pendant plus d\'un an', tone: ContentTone.cattivo),
    (text: 'accepté un « viens voir un film » en sachant qu\'on ne verrait rien du tout', tone: ContentTone.cattivo),
    (text: 'envoyé un « t\'es réveillé ? » à trois heures du matin et obtenu une réponse', tone: ContentTone.cattivo),
    (text: 'répondu à un « t\'es réveillé ? » à trois heures du matin et quitté la maison', tone: ContentTone.cattivo),
    (text: 'couché avec quelqu\'un que je détestais', tone: ContentTone.cattivo),
    (text: 'utilisé le sexe pour me faire pardonner', tone: ContentTone.cattivo),
    (text: 'utilisé le sexe pour obtenir quelque chose', tone: ContentTone.cattivo),
    (text: 'dit non en début de soirée et changé d\'avis à la moitié', tone: ContentTone.cattivo),
    (text: 'dit « ça n\'arrivera plus jamais » alors que c\'était déjà arrivé trois fois', tone: ContentTone.cattivo),
    (text: 'compté mon body count et dû recommencer depuis le début', tone: ContentTone.cattivo),
    (text: 'annoncé à mon partenaire un body count plus bas que le vrai', tone: ContentTone.cattivo),
    (text: 'tenu une liste écrite des personnes avec qui j\'ai couché', tone: ContentTone.cattivo),
    (text: 'donné un nom de code à une aventure pour en parler librement', tone: ContentTone.cattivo),
    (text: 'raconté les détails d\'une nuit à tout un groupe', tone: ContentTone.cattivo),
    (text: 'reconnu sur une appli de rencontres une personne en couple que je connais', tone: ContentTone.cattivo),
    (text: 'trouvé un profil qui n\'aurait pas dû exister et fait une capture d\'écran', tone: ContentTone.cattivo),
    (text: 'utilisé un faux profil pour surveiller quelqu\'un', tone: ContentTone.cattivo),
    (text: 'fouillé le téléphone de mon partenaire pendant qu\'il dormait', tone: ContentTone.cattivo),
    (text: 'trouvé quelque chose que j\'aurais préféré ne pas trouver', tone: ContentTone.cattivo),
    (text: 'fait comme si de rien n\'était après avoir tout trouvé', tone: ContentTone.cattivo),
    (text: 'essayé un fétiche et découvert que j\'aimais ça', tone: ContentTone.cattivo),
    (text: 'avoué un fétiche et vu le visage de l\'autre changer', tone: ContentTone.cattivo),
    (text: 'attaché quelqu\'un ou été attaché pour jouer', tone: ContentTone.cattivo),
    (text: 'utilisé des glaçons ou de la nourriture au lit', tone: ContentTone.cattivo),
    (text: 'bandé les yeux de quelqu\'un ou eu les yeux bandés', tone: ContentTone.cattivo),
    (text: 'mis la musique à fond pour couvrir les bruits', tone: ContentTone.cattivo),
    (text: 'reçu des plaintes des voisins', tone: ContentTone.cattivo),
    (text: 'cassé quelque chose à la maison pendant l\'amour', tone: ContentTone.cattivo),
    (text: 'expliqué un bleu ou une griffure avec une excuse inventée', tone: ContentTone.cattivo),
    (text: 'utilisé la table de la cuisine pour autre chose qu\'un dîner', tone: ContentTone.cattivo),
    (text: 'fait l\'amour dans un ascenseur ou dans une cage d\'escalier', tone: ContentTone.cattivo),
    (text: 'fait l\'amour sur la plage et retrouvé du sable partout pendant des jours', tone: ContentTone.cattivo),
    (text: 'fait l\'amour dans une piscine ou dans la mer', tone: ContentTone.cattivo),
    (text: 'fait l\'amour sous la tente avec d\'autres gens dans le camping', tone: ContentTone.cattivo),
    (text: 'fait l\'amour dans un train ou en avion', tone: ContentTone.cattivo),
    (text: 'payé une chambre juste pour quelques heures', tone: ContentTone.cattivo),
    (text: 'utilisé la pause déjeuner de façon très créative', tone: ContentTone.cattivo),
    (text: 'eu un réveil dont je ne parlerai jamais en détail', tone: ContentTone.cattivo),
    (text: 'fait au lit un truc que ce groupe ne croirait jamais de moi', tone: ContentTone.cattivo),
  ];

  // ---------------------------------------------------- chiLoPotrebbeFare
  static const List<({String text, String tone})>
  chiLoPotrebbeFare = <({String text, String tone})>[
    // __B1__
  ];
}
