import '../content_tone.dart';

/// Generato da tool/generate_content.dart (traduzione DeepL dai
/// pool italiani). Stesse posizioni e stesso tono degli originali IT.
class ContentDeObbligoOVerita {
  const ContentDeObbligoOVerita._();

  static const Map<String, List<String>> obblighi = {
    ContentTone.normal: [
      'Ahme die Art und Weise nach, wie die Person zu deiner Rechten geht.',
      'Sing den Refrain des letzten Liedes, das du gehört hast.',
      'Sprich in Reimen, bis du wieder an der Reihe bist.',
      'Imitier die Laute von drei Tieren und lass sie raten, um welche es sich handelt.',
      'Tanz zehn Sekunden lang ohne Musik.',
      'Erzähl einen Witz: Wenn niemand lacht, erzähl ihn noch einmal, aber lauter.',
      'Imitier deine Lieblingsfigur aus einer Serie.',
      'Nimm eine Statuenpose ein und bleibe dreißig Sekunden lang regungslos stehen.',
      'Sprich eine Minute lang wie ein Sportkommentator.',
      'Zeige das letzte Foto, das du aufgenommen hast.',
      'Zeige deinen Startbildschirm an, ohne etwas zu öffnen.',
      'Zeig uns das Emoji, das du am häufigsten verwendest, und erkläre, warum gerade dieses.',
      'Zeig mal, wie viele Wecker du gestellt hast.',
      'Stelle dem Sprachassistenten deines Handys eine absurde Frage, die von der Gruppe ausgewählt wurde.',
      'Schicke einem zufällig ausgewählten Kontakt eine gesungene Sprachnachricht.',
      'Ruf einen Freund an und sing ihm ein Ständchen, auch wenn er nicht Geburtstag hat.',
      'Mach jeder anwesenden Person ein aufrichtiges Kompliment.',
      'Beschreibe die Person zu deiner Linken mit nur drei Wörtern.',
      'Erfinde einen 20-Sekunden-Rap über die Person zu deiner Linken.',
      'Ahme den Lehrer nach, an den du dich am schlechtesten erinnerst.',
      'Stell dir vor, du wärst ein Verkäufer, und verkauf uns diesen Tisch.',
      'Präsentiere die Wettervorhersage für morgen so wie im Fernsehen.',
      'Sprich bis zur nächsten Runde mit einem ausländischen Akzent.',
      'Erzähle die Handlung eines Films, ohne den Titel zu nennen – die anderen sollen raten.',
      'Halte eine Dankesrede, als hättest du einen Preis gewonnen.',
      'Erstelle spontan eine Anzeige für den Artikel, der dir gerade am nächsten ist.',
      'Zeig mal, wie du tanzt, wenn du allein zu Hause bist.',
      'Sing in den nächsten zwei Minuten, anstatt zu sprechen.',
      'Er geht und balanciert dabei ein Buch auf dem Kopf.',
      'Zieh die Kleidung zwei Runden lang verkehrt herum an.',
      'Lass dir von der Person zu deiner Rechten eine neue Frisur machen.',
      'Zeichne in dreißig Sekunden ein Bild von der Gruppe.',
      'Schreibe deinen Namen mit der falschen Hand und zeige ihn her.',
      'Zeichne mit geschlossenen Augen ein Porträt der Gegenwart und schenke es ihr dann.',
      'Sag das Alphabet rückwärts auf, so schnell du kannst.',
      'Zähle bis zwanzig und überspringe dabei die Vielfachen von drei.',
      'Nenne drei Wörter rückwärts, beginnend mit dem letzten.',
      'Erzähle eine 30-Sekunden-Geschichte, die mit „Gestern Nacht …“ beginnt.',
      'Erzähle von deinem Tag, als wäre er ein Horrorfilm.',
      'Beschreibe deinen Beruf oder deinen typischen Tagesablauf so, wie es ein Kind tun würde.',
      'Tu einfach mal eine Minute lang so, als wärst du ein Roboter.',
      'Antworte bis zur nächsten Runde nur mit Fragen.',
      'Du darfst bis zu deinem nächsten Zug weder „Ja“ noch „Nein“ sagen.',
      'Sprich bis zu deinem nächsten Zug in der dritten Person von dir.',
      'Lache so laut du kannst, ohne Grund.',
      'Bleib dreißig Sekunden lang ganz ernst, während die anderen versuchen, dich zum Lachen zu bringen.',
      'Mach zwanzig Sekunden lang eine Plank, während die anderen zählen.',
      'Mach fünf Liegestütze, die von der Gruppe gezählt werden.',
      'Lauf auf der Stelle bis zum Ende der Schicht.',
      'Mach zehn Kniebeugen und sag bei jeder Kniebeuge den Namen eines Anwesenden.',
      'Iss etwas, das die Person zu deiner Linken ausgesucht hat.',
      'Probier mal zwei Dinge zusammen, die nicht gut zusammenpassen.',
      'Schreibe eine Bewertung wie ein Sterne-Kritiker über das Letzte, was du heute gegessen hast.',
      'Bereite einen alkoholfreien Drink zu und lass ihn jemanden probieren.',
      'Halte eine spontane Tischrede zu Ehren der Gruppe.',
      'Erzähl von deiner schönsten Erinnerung mit einer Person, die hier anwesend ist.',
      'Erzähl, wie du die Person kennengelernt hast, die dir gegenüber sitzt.',
      'Sag, was du an jeder hier Anwesenden (im positiven Sinne) beneidest.',
      'Mache eine Vorhersage über die Zukunft einer hier anwesenden Person.',
      'Gib jedem einen Spitznamen und erkläre ihn.',
      'Beantworte bis zum Ende des Spiels nur unter dem neuen Spitznamen, den die Gruppe gewählt hat.',
      'Entscheide, wen aus der Gruppe du auf eine einsame Insel mitnehmen würdest und warum.',
      'Erzähl uns von dem teuersten Ding, das du unnötigerweise gekauft hast.',
      'Gib eine deiner seltsamen Gewohnheiten zu.',
      'Erzähl von einer deiner lächerlichen Ängste.',
      'Tu so, als hättest du Angst vor einem Gegenstand im Zimmer.',
      'Erzähl von einer deiner nutzlosen Fähigkeiten und zeig sie uns.',
      'Zeig uns deinen besten improvisierten „Zaubertrick“.',
      'Falte aus dem, was du findest, in einer Minute ein Origami.',
      'Baue einen Turm aus drei Gegenständen aus dem Raum.',
      'Finde innerhalb von dreißig Sekunden drei gelbe Gegenstände in der Wohnung.',
      'Tausche ein Kleidungsstück mit der Person zu deiner Rechten aus.',
      'Mach ein Selfie mit dem hässlichsten Gesicht, das du hinbekommst.',
      'Mach ein Foto von dir, auf dem du die Pose der Person zu deiner Linken nachahmst.',
      'Drehe ein zehnsekündiges Video, als wärst du ein Influencer.',
      'Nimm eine motivierende Botschaft für die Gruppe auf.',
      'Lies das heutige Horoskop mit dramatischer Stimme vor.',
      'Erfinde ein Horoskop für die Person zu deiner Rechten.',
      'Beschreibe, wie dein Leben in zehn Jahren aussehen wird, ohne groß darüber nachzudenken.',
      'Bekunde einem Gegenstand im Zimmer deine ewige Liebe: Das Sofa zählt.',
      'Spiele eine rührende Abschiedsszene mit einem Kissen.',
      'Sag mal, welches Lied du auswendig kennst, und sing ein Stück davon.',
      'Sing zehn Sekunden lang Karaoke ohne Musik.',
      'Pfeife ein Lied vor und lass die anderen raten, welches es ist.',
      'Mach mal einen fünf Sekunden langen Beatbox-Part.',
      'Es ahmt den Klang von drei verschiedenen Instrumenten nach.',
      'Tu so, als würdest du Gitarre spielen, wie bei einem Konzert.',
      'Tanz so, als wärst du ganz allein in der Disco.',
      'Bring der Gruppe einen Tanzschritt bei.',
      'Mach ein Gruppenfoto und gib dabei die Anweisungen.',
      'Wähle den Soundtrack für den Abend aus und begründe deine Wahl.',
      'Erzähl uns, was dir diese Woche am besten gefallen hat.',
      'Nenne eine Sache, die du gerne lernen würdest, und sag, warum du noch nicht damit angefangen hast.',
      'Erstelle eine Liste mit drei Dingen, für die du im Moment dankbar bist.',
      'Schick einer Person, der du schon lange nicht mehr geschrieben hast, eine nette Nachricht.',
      'Ruf deine Mutter oder einen Verwandten an und sag ihm, dass du ihn liebst.',
      'Schick „Guten Morgen!“ mit drei zufälligen Emojis im Familienchat.',
      'Lass die Gruppe entscheiden, welche Aufgabe du in der nächsten Runde übernehmen sollst.',
      'Er schreitet wie ein Model von einer Seite des Raums zur anderen, inklusive einer Drehung.',
      'Benimm dich bis zu deinem nächsten Zug wie ein T-Rex mit kurzen Armen.',
      'Verwende bei jeder Runde, wenn du sprichst, eine Fernbedienung oder eine Bürste als Mikrofon.',
      'Spiele den Kellner: Nimm die imaginären Bestellungen aller Gäste mit äußerst ernstem Gesichtsausdruck entgegen.',
      'Stelle einen Film pantomimisch dar, ohne zu sprechen, bis die Gruppe ihn errät.',
      'Imitieren Sie eine berühmte Persönlichkeit, die von der Gruppe ausgewählt wurde, bis jemand errät, um wen es sich handelt.',
      'Mach jedem Anwesenden ein Kompliment, während du auf einem Bein hüpft.',
      'Versuche einmal, zehn Sekunden lang mit vollem Einsatz an deinem Ellbogen zu lecken.',
      'Erzähl in dreißig Sekunden eine Gutenachtgeschichte und imitiere dabei alle Stimmen.',
      'Sprich eine Minute lang über ein von der Gruppe ausgewähltes Thema, als wärst du der größte Experte auf diesem Gebiet.',
      'Wiederhole dreimal hintereinander einen von der Gruppe ausgewählten Zungenbrecher, ohne dabei einen Fehler zu machen.',
      'Beschreibe, was die Person gegenüber tut, so, als würdest du einen Naturdokumentarfilm drehen.',
      'Zeige auf Kommando fünf Gesichtsausdrücke: glücklich, wütend, überrascht, verliebt, misstrauisch.',
      'Tanz einen romantischen Slow mit einem Besen oder einem Kissen.',
      'Moderieren Sie eine Nachrichtensendung mit drei absurden Meldungen über die Anwesenden.',
      'Wiederhole: Wiederhole das letzte Wort des Sprechers, bis du wieder an der Reihe bist.',
      'Sprich leise, bis du wieder an der Reihe bist, egal was passiert.',
      'Behalte drei Minuten lang ein breites Lächeln im Gesicht, egal was passiert.',
      'Erfinde eine Gruppenhymne zur Melodie eines bekannten Liedes und singe sie vor.',
      'Lass dich von der Gruppe wie eine Statue in Pose bringen und bleib so für ein Foto stehen.',
      'Du machst eine dramatische Szene wie in einer Seifenoper, weil ein Keks aufgegessen ist.',
      'Versuche, die ernsteste Person in der Gruppe innerhalb von 30 Sekunden zum Lachen zu bringen, ohne sie zu berühren.',
      'Staple so viele Kissen wie möglich auf dich und halte das Gleichgewicht zehn Sekunden lang.',
      'Erfinde eine Sprache und „übersetze“, was die Person zu deiner Rechten sagt.',
      'Tu so, als wärst du in einer unsichtbaren Kiste gefangen, bis dich jemand „befreit“.',
      'Erzähle im Stil einer historischen Dokumentation, wie diese Gruppe entstanden ist.',
      'Behandle alle bis zu deiner nächsten Schicht mit „Sie“ und sei dabei äußerst förmlich.',
      'Erstelle ein fiktives Koch-Tutorial mit den Gegenständen, die du vor dir hast.',
      'Beweg dich in Zeitlupe bis zum Ende der Runde, einschließlich der Wiederholungen.',
      'Grüße in fünf verschiedenen Sprachen und erfinde dabei diejenigen, die du nicht kennst.',
      'Imitieren Sie ein Tier, bis jemand errät, welches es ist.',
      'Antworte singend auf alles, was dir gesagt wird, bis du an der Reihe bist.',
      'Mach zehn kleine Sprünge auf der Stelle und rufe dabei deinen Namen.',
      'Denk dir ein Motto für die Gruppe aus und sprich es laut aus.',
      'Spiele 30 Sekunden lang den Kommentator im Raum.',
      'Erfinde eine Werbung für den Gegenstand zu deiner Rechten.',
      'Sprich bis zu deinem nächsten Zug nur flüsternd.',
      'Du stehst regungslos da wie eine Statue, während die anderen versuchen, dich zum Lachen zu bringen.',
      'Lippe-Synchronisiere fünfzehn Sekunden lang ein Lied deiner Wahl aus dem Repertoire der Band.',
      'Imitieren Sie eine berühmte Persönlichkeit, die von der Gruppe ausgewählt wurde.',
      'Beschreibe die Handlung eines berühmten Films in genau zehn Wörtern.',
      'Sag die Wochentage so schnell wie möglich rückwärts auf.',
      'Tu so, als würdest du einen Oscar gewinnen, und bedanke dich nacheinander bei allen Anwesenden.',
      'Geh wie ein Roboter bis zur Tür und zurück.',
      'Denk dir für jeden Anwesenden einen lustigen Spitznamen aus.',
      'Sing „Tanti auguri“ so, als wäre es ein Rocklied.',
      'Mach in fünf Sekunden fünf verschiedene Gesichtsausdrücke.',
      'Balanciere ein Kissen eine ganze Runde lang auf deinem Kopf.',
      'Beschreibe deinen Tag ausschließlich mit Geräuschen.',
      'Erstelle eine erfundene Wettervorhersage und nimm das Ganze dabei absolut ernst.',
      'Bestelle eine imaginäre Pizza auf epische und dramatische Weise.',
      'Applaudiere jedem Satz, den die anderen sagen, bis du an der Reihe bist.',
    ],
    ContentTone.mix: [
      'Massiere 30 Sekunden lang sinnlich die Innenseite des Oberschenkels einer Person, die damit einverstanden ist.',
      'Flüstere der Person zu deiner Rechten deine versauteste Fantasie ins Ohr.',
      'Küsse den Hals einer Person, die damit einverstanden ist, und hauche sanft auf ihre Haut.',
      'Lass dich von einer Person, die damit einverstanden ist, ein Kleidungsstück aussuchen, das du ausziehen sollst.',
      'Täusche vor allen Anwesenden fünfzehn Sekunden lang einen Orgasmus vor, mit Geräuschen und Gesten.',
      'Zieh drei Kleidungsstücke aus (Accessoires ausgenommen) und bleib für den Rest des Spiels so.',
      'Leck das Ohrläppchen der Person zu deiner Linken (sofern sie damit einverstanden ist).',
      'Zieh ein Accessoire oder eine Kleidungsschicht so provokant und langsam wie möglich aus.',
      'Lass dir die Augen verbinden und errate drei Personen aus der Gruppe, indem du ihnen nur auf die Hand oder den Arm küsst.',
      'Stelle deine Lieblingsposition mit einem Kissen äußerst realistisch nach.',
      'Lege deinen Kopf auf den Schoß einer Person, die damit einverstanden ist, und bleibe dort für drei Runden.',
      'Schick ein Nacktfoto (oder ein sehr provokantes Foto) an jemanden deiner Wahl und zeig der Gruppe die Versandbenachrichtigung.',
      'Führe einen 30-sekündigen Lapdance für eine einwilligende Person aus der Gruppe durch.',
      'Tanze eine Minute lang einen sinnlichen Slow Dance, Körper an Körper, mit einer Person, die damit einverstanden ist.',
      'Fahre mit der Zunge die Kontur des Halses der Person zu deiner Linken nach (sofern diese damit einverstanden ist).',
      'Halte die Hand der attraktivsten Person im Raum, indem du sie unter ihr Shirt schiebst (sofern sie damit einverstanden ist).',
      'Schau der Person, die du am attraktivsten findest, dreißig Sekunden lang in die Augen, während du dir auf die Lippe beißt.',
      'Zeig der Gruppe den Gesichtsausdruck, den du beim Orgasmus machst: Halte diese Pose fünf Sekunden lang.',
      'Küsse langsam die Brust oder die Schulter einer Person deiner Wahl, die damit einverstanden ist.',
      'Imitier mal, wie du reagierst, wenn dir jemand Oralsex macht – mit Ton.',
      'Lies dein Sexting-Repertoire laut vor, in einem äußerst ernsten Tonfall.',
      'Sag der Gruppe, welche besonders gewagte Flirtnachricht du deinem Schwarm gerade schicken würdest.',
      'Beschreibe laut, wie du die Person zu deiner Linken Schritt für Schritt ins Bett bringen würdest.',
      'Zeig der Gruppe deinen Lieblingstrick, mit dem man jemanden in weniger als einer Minute in Stimmung bringen kann.',
      'Beschreibe Schritt für Schritt deine ideale Nacht: vom Vorspiel bis zum Frühstück.',
      'Dreh einen 30-Sekunden-Werbespot über dich selbst als Liebhaber und hebe dabei deine besten Eigenschaften hervor.',
      'Erzähle von deiner besten Nacht und gehe dabei auf Stellungen und Empfindungen ein.',
      'Beschreibe deinen perfekten Kuss und schenk ihn sofort einer Person, die damit einverstanden ist (wenn sie Lust dazu hat).',
      'Sag laut den versautesten Satz, den dir jemals im Bett zugeflüstert wurde.',
      'Flüstere „Ich will dich jetzt“ mit deiner sinnlichsten Stimme drei verschiedenen Personen ins Ohr.',
      'Schick der letzten Person, mit der du zusammen warst, eine heiße Nachricht und zeig die Antwort.',
      'Imitier mal, wie du flirtest, wenn du betrunken bist und einfach nur zum Ziel kommen willst.',
      'Zeige in Zeitlupe, wie du deine Zunge beim Küssen einsetzt: Die Gruppe bewertet deine Technik.',
      'Sende „Ich denke gerade an uns beide im Bett“ an einen Kontakt deiner Wahl aus der Gruppe.',
      'Lies den pikantesten Chat, den du auf deinem Handy hast, laut vor – ohne irgendetwas zu zensieren.',
      'Zeige das gewagteste Foto, das du in den letzten Monaten aufgenommen oder erhalten hast.',
      'Zeige der Gruppe deinen Inkognito-Verlauf der letzten zwei Tage.',
      'Schreibe der Person, die du magst, „Ich möchte das mit dir machen“ und zeige ihr den Screenshot.',
      'Schicke eine zehnsekündige Verführungsnachricht an einen Ex, den die Gruppe ausgewählt hat.',
      'Erzähl uns, wie weit du an dem öffentlichsten Ort, an dem du je gewesen bist, gegangen bist.',
      'Beschreibe ganz offen die drei Dinge, die dich im Bett am meisten anmachen.',
      'Erzähl uns von deinem peinlichsten Erwachen nach einer Nacht voller wildem Sex.',
      'Gib zu, welchen Fetisch du noch nicht gewagt hast auszuprobieren.',
      'Nenne den Namen der hier anwesenden Person, mit der du heute Abend am ehesten ins Bett landen würdest.',
      'Stelle eine Rangliste der Anwesenden auf, wobei du dich ausschließlich auf ihre potenziellen Fähigkeiten im Bett stützt.',
      'Gib jedem Anwesenden eine „Attraktivitätsbewertung“ von 1 bis 10, während du ihm in die Augen schaust.',
      'Sag mal, welches Paar aus diesem Raum würde im Bett für Funken sorgen und warum.',
      'Wähle aus, wen aus der Gruppe du gerade gerne nackt sehen würdest.',
      'Mach einer Person aus der Gruppe das gewagteste Kompliment, das dir zu ihrem Körper einfällt.',
      'Schlage der Person zu deiner Rechten ein kurzes „Rollenspiel“ vor und sprich den ersten Satz.',
      'Geh durch den Raum, als wärst du in einem Stripclub, bleib vor jemandem stehen und winke ihm zu.',
      'Lass die Gruppe eine gewagte Nachricht von deinem Handy aus schreiben und sie an wen auch immer sie wollen verschicken.',
      'Zieh zwei Kleidungsstücke oder Accessoires deiner Wahl so langsam wie möglich aus, während die Gruppe ein erotisches Lied singt.',
      'Gib der von der Gruppe ausgewählten Person – mit deren Einverständnis – einen kräftigen Klaps auf den Hintern.',
      'Imitieren Sie zehn Sekunden lang die Geräusche, die Sie im Bett im Moment des höchsten Lustempfindens machen.',
      'Küsse langsam den Hals einer einwilligenden Person, beginnend am Ohr und nach unten hin.',
      'Mima, bleibe angezogen und halte deine Lieblingsposition zehn Sekunden lang mit vollem Einsatz.',
      'Sag laut den Namen der Person in diesem Raum, die du sofort küssen würdest.',
      'Massiere den Rücken einer Person, die damit einverstanden ist, eine Minute lang und schiebe dabei deine Hände unter die Kleidung (sofern sie damit einverstanden ist).',
      'Flüstere der Person zu deiner Rechten ins Ohr, was du mit ihr machen würdest, wenn ihr beide allein in diesem Raum wärt.',
      'Wechsle drei Mal intensive Blicke mit der Person aus, die du am attraktivsten findest, ohne dabei jemals zu lachen.',
      'Beschreibe die Unterwäsche, die du heute Abend trägst, bis ins kleinste Detail.',
      'Tanz eine halbe Minute lang Reggaeton und reibe dich dabei (mit Einverständnis) an einer Person aus der Gruppe.',
      'Lass dir ein Eiswürfelchen in die Hose stecken und halte es eine Minute lang aus, ohne zu schreien.',
      'Flüstere jemandem den Namen deines Lieblings-Sexspielzeugs ins Ohr, als wäre es ein Gebet.',
      'Beschreibe, wie du dich selbst berührst, wenn du allein bist und es schnell hinter dich bringen willst.',
      'Erläutere den Unterschied zwischen einem normalen Kuss und einem „Bettkuss“ anhand theoretischer Beispiele.',
      'Stell dir vor: „Ich schreibe meiner Angebeteten, um sie mit nach Hause zu nehmen“ – mit all den Phasen der Panik und des Erfolgs.',
      'Zeig uns deine beste „Ich will ficken“-Pose und erkläre uns deine Strategie dahinter.',
      'Erzähl mal, was das anzüglichste Kompliment war, das du je bekommen hast, und wer es dir gemacht hat.',
      'Wiederhole „Ich will mehr“ mit fünf verschiedenen Absichten: Die Gruppe muss die richtige erraten.',
      'Führe die erotischste Geste aus, die dir einfällt, und benutze dabei nur einen Eiswürfel.',
      'Zeig der Gruppe, wie man einen perfekten Knutschfleck macht, ohne dabei zu große Spuren zu hinterlassen.',
      'Verrate uns, welcher Duft dich dazu bringt, jemanden sofort ausziehen zu wollen.',
      'Tanz mit einem Anwesenden zwanzig Sekunden lang einen Slow Dance und flüstere ihm anzügliche Dinge zu.',
      'Mach noch mal den Gesichtsausdruck, den du beim Orgasmus machst: Die Gruppe bewertet die Intensität.',
      'Verfasse eine „Guten-Morgen-Nach-dem-Sex“-Nachricht, die jeden um den Verstand bringen würde.',
      'Wähle aus der Gruppe jemanden aus, den du einen ganzen Monat lang als „Bettfreund“ haben möchtest.',
      'Beiß sanft in die Schulter einer Person, die damit einverstanden ist, und wecke in ihr das Verlangen nach mehr.',
      'Fahre mit einem Finger über den nackten Rücken einer einwilligenden Person, beginnend am Nacken bis zur Taille.',
      'Lass einen Eiswürfel mit dem Mund am Hals einer Person, die damit einverstanden ist, entlanggleiten.',
      'Lass dein Haar offen und lass es auf eine Person fallen, die damit einverstanden ist, während du ihr etwas zuflüsterst.',
      'Sie knabbert nacheinander an den Fingern einer Person, die damit einverstanden ist, und schaut ihr dabei in die Augen.',
      'Tanze, indem du dich langsam vor einer einwilligenden Person hinkniest, die von der Gruppe ausgewählt wurde.',
      'Berühre die Lippen der attraktivsten Person mit deinen eigenen, ohne sie dabei zu küssen – zehn Sekunden lang.',
      'Lass dir von einer Person, die damit einverstanden ist, mit dem Finger ein Schimpfwort auf den Körper schreiben und rate, welches es ist.',
      'Lege deine Stirn an die Stirn der Person, die du am attraktivsten findest, und atmet zwanzig Sekunden lang gemeinsam.',
      'Streichle den Nacken einer Person, die damit einverstanden ist, während du ihr den erotischsten Satz vorliest, den du kennst.',
      'Küsse das Handgelenk von drei verschiedenen, einwilligenden Personen und tue dabei jedes Mal so, als ob du es noch mehr begehrst.',
      'Massiere sanft die Schultern der Person zu deiner Rechten und flüstere ihr dabei zu, wie sehr dir ihre Haut gefällt.',
      'Fahre provokativ mit der Zunge am Rand eines Glases entlang, während du deinen Schwarm anstarrst.',
      'Beiß dir auf die Unterlippe und halte den Blickkontakt mit der attraktivsten Person eine ganze Runde lang aufrecht.',
      'Zieh langsam den Gürtel oder ein Bändchen ab und benutze es, um (mit Einverständnis) die Handgelenke einer Person für eine Minute zu fesseln.',
      'Lass deine Hand von einer einwilligenden Person zehn Sekunden lang überall dort hinführen, wo sie es über der Kleidung möchte.',
      'Sag vor allen Leuten einen Satz aus einem Erotikfilm mit der heiseresten Stimme, die du hinbekommst.',
      'Simuliere einen leidenschaftlichen Kuss mit deinem Handrücken – so realistisch wie möglich.',
      'Beschreibe der Gruppe – während du eine Person ansiehst, die damit einverstanden ist –, was du mit ihren Lippen machen würdest, wenn du könntest.',
      'Flüstere jemandem einen Countdown von fünf bis eins ins Ohr, als ob gleich etwas passieren würde.',
      'Sie reibt ihre Wange langsam an der Wange einer willigen Person, so wie es eine rollige Katze tun würde.',
      'Beiß in die Luft nahe am Hals einer einwilligenden Person, ohne sie zu berühren, sodass sie erschauert.',
      'Zeichne mit der Zunge ein Herz auf die offene Handfläche einer Person, die damit einverstanden ist.',
      'Tanz eine halbe Minute lang vor der Gruppe und bewege dabei nur die Hüften – so sinnlich wie möglich.',
      'Lege deine Hände auf die Hüften einer Person, die damit einverstanden ist, und führe sie zwanzig Sekunden lang in einem langsamen Tanz.',
      'Lass dir von einer Person, die damit einverstanden ist, in den Nacken pusten und tu so, als würde sie dich damit in den Wahnsinn treiben.',
      'Flüstere einer Person, die damit einverstanden ist, „Schließ die Augen“ zu und lass sie erraten, wo du sie leicht berühren wirst.',
      'Beschreibe laut, wie dein ideales Erwachen an der Seite der Person zu deiner Rechten aussieht.',
      'Tu so, als würdest du die attraktivste Person im Raum zehn Sekunden lang schweigend mit den Augen ausziehen.',
      'Er küsst eine willige Person auf die Wange und kommt dabei gefährlich nah an die Lippen heran.',
      'Zeige, wie du jemanden im Regen küssen würdest, wobei die Gruppe als Publikum und ein Kissen als Partner dienen.',
      'Erzähl von dem Moment, als du dich am meisten nach jemandem gesehnt hast, ohne ihn haben zu können.',
      'Fahre mit einer Erdbeere (oder einem Finger) über die Lippen einer einwilligenden Person und lass sie davon probieren.',
      'Lass dir von einer Person, die damit einverstanden ist, mit dem Finger eine Linie vom Hals bis zur Hand zeichnen und halte dabei den Atem an.',
      'Wiederhole „Komm her“ in drei verschiedenen Tonlagen, bis die Gruppe sich einig ist, welche davon am verführerischsten ist.',
      'Mach ein Vorsprechen für die Hauptrolle in einem Erotikfilm, indem du die Eröffnungsszene spielst – bekleidet.',
      'Beschreibe genau, wo du gerade gerne geküsst werden würdest, und lass es jemanden ausprobieren (mit Einverständnis).',
      'Zeige mit deinen Händen die Silhouette der Person nach, die du am attraktivsten findest, während du ihr in die Augen schaust.',
      'Flüstere der Person zu deiner Linken ins Ohr, zu welcher Tageszeit du am meisten an Sex denkst.',
      'Lass dir von einer Person, die damit einverstanden ist, sanft ins Ohr beißen und lache zehn Sekunden lang nicht.',
      'Tanze, indem du dich mit dem Rücken an eine einwilligende Person lehnst und deren Bewegungen mit deinen Hüften führst.',
      'Erzähl mir, während du sie ansiehst, was dich an der Person zu deiner Rechten körperlich anzieht – Detail für Detail.',
      'Halte den Blick einer willigen Person fest, während du langsam ihren Handrücken küsst und dich dabei bis zum Handgelenk vorarbeitest.',
      'Tu so, als würdest du dein Trikot so langsam wie möglich ausziehen, und halte dabei auf halbem Weg inmitten der Proteste der Gruppe inne.',
      'Flüstere deinem Schwarm ein pikantes Versprechen ins Ohr, als wäre es ein Staatsgeheimnis.',
      'Beschreibe die perfekte Verführungsszene und lass einen Anwesenden die Hauptrolle übernehmen.',
      'Küsse deinen eigenen Unterarm leidenschaftlich und zeige der Gruppe genau, wie du normalerweise küsst.',
      'Lass dir ein paar Tropfen Wasser auf den Nacken träufeln (oder träufle sie selbst darauf) und lass sie eine Runde lang herunterlaufen, ohne sie abzuwischen.',
      'Schau eine Person an, die damit einverstanden ist, und forme mit den Lippen – ohne zu sprechen – drei Worte, die du ihr im Bett sagen möchtest.',
      'Laufe wie ein Model über einen imaginären Laufsteg und halte kurz inne, um deinem Schwarm einen Kuss zuzuwerfen.',
      'Streichle langsam den Arm der Person neben dir, während du von deinem letzten erotischen Traum erzählst.',
      'Leg ein langsames Lied auf und lade die Person, die du am meisten begehrst, zum Tanzen ein – Körper an Körper.',
      'Lass dir die Augen verbinden und identifiziere drei Personen, die damit einverstanden sind, allein anhand des Dufts ihrer Haut.',
      'Flüstere der Person zu deiner Rechten „Du bist alles, was ich heute Abend will“ zu, als ob du es wirklich so meinen würdest.',
      'Beschreibe, was du mit einer Person tun würdest, die damit einverstanden ist, wenn ihr nur fünf Minuten in einem abgeschlossenen Raum hättet.',
      'Beiß sanft in die Seite eines Kissens, als würdest du deinem Partner einen Knutschfleck hinterlassen.',
      'Halte das Kinn einer einwilligenden Person fest und nähere dein Gesicht ihrem so weit, dass es nur einen Hauch von ihren Lippen entfernt ist.',
      'Sag der attraktivsten Person im Raum auf den Knien eine Liebeserklärung auf.',
      'Lass deine Hände langsam an deinen Hüften entlanggleiten, während du deinen Schwarm wie in einem Musikvideo anstarrst.',
      'Flüstere einer willigen Person deinen Lieblingsmoment beim Vorspiel ins Ohr.',
      'Lass dir von einer Person, die damit einverstanden ist, eine Körperstelle nennen, und mach ihr ein heißes Kompliment darüber.',
      'Tanze einen improvisierten Tango mit einer Person, die damit einverstanden ist, und beende den Tanz in einer Pose, bei der du nur wenige Zentimeter von ihrem Gesicht entfernt bist.',
      'Beschreibe, wie du jemanden allein mit deiner Stimme verführen würdest, und zeige es anhand eines Beispiels von zehn Sekunden.',
      'Lass dir den Namen der Person, die dich anspricht, mit dem Finger auf den Nacken schreiben und lass die Gruppe raten, um wen es sich handelt.',
      'Erzähl von der Fantasie, die du am liebsten mit jemandem aus diesem Raum verwirklichen würdest.',
      'Zeige der Gruppe, wie du dich zehn Sekunden lang mit einem Kissen auf einem Partner bewegst.',
      'Flüstere der attraktivsten Person zu, was dir jedes Mal als Erstes an ihr auffällt, wenn sie einen Raum betritt.',
      'Fahre langsam mit einem Finger über deine Lippen, während du dem Blick der Person, die du begehrst, standhältst.',
      'Lass dir von der Gruppe drei Schimpfwörter diktieren und verwende sie in einem verführerischen Satz, der an deinen Schwarm gerichtet ist.',
      'Küsse langsam die Fingerknöchel einer Person, die damit einverstanden ist, und lass deinen Blick dabei zu ihren Augen wandern.',
      'Beschreibe den Körpergeruch, den du bei einem Partner am liebsten magst, und rieche (mit dessen Einverständnis) am Hals einer Person, um dies zu überprüfen.',
      'Lass dir von einer Person, die damit einverstanden ist, ihre Fantasie ins Ohr flüstern und reagiere nur mit deinem Blick.',
    ],
    ContentTone.hot: [
      'Küss die Person zu deiner Rechten mit der Zunge, sofern sie damit einverstanden ist.',
      'Lass dir von einer einwilligenden Person ein Kleidungsstück mit den Zähnen ausziehen.',
      'Imitieren Sie 30 Sekunden lang Ihre Lieblingsstellung an einer einwilligenden Person.',
      'Beschreibe laut, wie du die Person, die dir gegenübersteht, ins Bett bringen würdest.',
      'Zeig mal den Gesichtsausdruck, den du machst, wenn du zum Orgasmus kommst.',
      'Lecke den Hals der Person zu deiner Linken, bis sie erschauert – sofern sie damit einverstanden ist.',
      'Mach einen gut sichtbaren Knutschfleck auf der Schulter einer Person, die damit einverstanden ist.',
      'Setz dich rittlings auf eine Person, die damit einverstanden ist, und bleib dort eine ganze Runde lang sitzen.',
      'Simuliere vor allen Anwesenden zwanzig Sekunden lang einen lauten, realistischen Orgasmus.',
      'Flüstere der Person gegenüber ins Ohr, was du ihr am versautesten antun würdest.',
      'Führe einen einminütigen Lapdance für eine einwilligende Person durch, die von der Gruppe ausgewählt wird.',
      'Knabbere an der Ohrläppchen der Person zu deiner Rechten, sofern diese damit einverstanden ist.',
      'Gib einen Eiswürfel von deinem Mund in den Mund einer Person, die damit einverstanden ist.',
      'Zeig der Gruppe, wie du beim Sex im Stehen deine Hüften bewegst.',
      'Leck einen Tropfen eines Getränks vom Hals einer Person ab, die damit einverstanden ist.',
      'Zieh ein Kleidungsstück aus und behalte es für die nächsten drei Runden an.',
      'Zeige, in welcher Position du schläfst, indem du dich auf den Boden legst.',
      'Küsse eine Stelle am Körper einer Person, die damit einverstanden ist, ganz nach deinem Geschmack.',
      'Imitieren Sie fünfzehn Sekunden lang Oralsex an einer Banane oder einem anderen Gegenstand.',
      'Tanze einen langsamen Tanz Körper an Körper mit einer einwilligenden Person, ohne die Hände zu benutzen.',
      'Beschreibe möglichst detailliert, wann du das letzte Mal masturbiert hast.',
      'Zeige mit Gesten, wie begabt dein unvergesslichster Ex ist.',
      'Leg deine Hand auf den Oberschenkel einer Person, die damit einverstanden ist, und lass sie eine Runde lang dort liegen.',
      'Imitier die Laute, die du im Bett von dir gibst, wenn du kurz vor dem Orgasmus stehst.',
      'Leck den Finger einer Person, die damit einverstanden ist, so provokativ wie möglich.',
      'Zieh dich bis auf die Unterwäsche aus und tausche den Platz mit der Person vor dir.',
      'Zeig, wie sinnlich du sein kannst, indem du dir langsam die Socken oder Schuhe ausziehst.',
      'Beiß sanft in den Hals einer Person, die damit einverstanden ist, und hinterlasse dabei Zahnabdrücke.',
      'Zeige an einer Hand, wie du deine Zunge bei einem Zungenkuss bewegen würdest.',
      'Versohle eine Person, die damit einverstanden ist, und lass dich dann selbst versohlen.',
      'Beschreibe die sexuelle Fantasie, die dich am meisten erregt – ganz ohne Zensur.',
      'Tue so, als würdest du zwanzig Sekunden lang auf einem Stuhl sitzend auf jemandem reiten.',
      'Massiere eine einwilligende Person eine Minute lang sinnlich am Rücken.',
      'Zeige, wie man leidenschaftlich mit dem Handrücken küsst.',
      'Entblöße deine Schulter und lass dich dort von einer einwilligenden Person küssen.',
      'Erzähl laut den erotischsten Traum, an den du dich erinnern kannst.',
      'Imitieren Sie zehn Sekunden lang die Missionarsstellung in der Luft, mit Ausdruck.',
      'Flüstere der Person zu deiner Rechten ein Stöhnen ins Ohr, sofern sie damit einverstanden ist.',
      'Lass dir die Handgelenke von einer Person, die damit einverstanden ist, für eine Runde mit einem Schal fesseln.',
      'Beschreibe, was dich am Körper der Person vor dir am meisten anmacht.',
      'Zeig mal, wie du den BH mit nur einer Hand und geschlossenen Augen ausziehen würdest.',
      'Lecke Sahne oder Zucker vom Finger einer Person ab, die damit einverstanden ist.',
      'Zeige deine schönste Nahaufnahme mit verführerischem Blick und halte sie zehn Sekunden lang.',
      'Tue fünfzehn Sekunden lang mit größter Ernsthaftigkeit so, als würdest du einer Gurke einen blasen.',
      'Lass dir von einer Person, die damit einverstanden ist, in den Nacken pusten und reagiere so, wie du es im Bett tun würdest.',
      'Beschreibe das Erlebnis, bei dem du den intensivsten Orgasmus deines Lebens hattest.',
      'Tanz 30 Sekunden lang Pole Dance, wobei du einen Stuhl als Stange benutzt.',
      'Halte deine Lippen zehn Sekunden lang einen Zentimeter von den Lippen deines Gegenübers entfernt, ohne ihn zu küssen.',
      'Stöhne immer lauter, bis es in einem Schrei gipfelt – wie bei einem echten Höhepunkt.',
      'Fahre mit der Zunge über deine Oberlippe und schaue dabei die Person an, die dich hier am meisten anzieht.',
      'Zieh deine Unterwäsche unter der Kleidung aus und zeig sie der Gruppe.',
      'Lass dir fünf Sekunden lang von einer Person, die damit einverstanden ist, in den Nacken beißen.',
      'Beschreibe dein Lieblings-Sexspielzeug und wie du es benutzt.',
      'Sie tut so, als würde sie jeden Anwesenden mit ihren Blicken entkleiden, einen nach dem anderen.',
      'Führe zwanzig Sekunden lang einen langsamen und verführerischen Bauchtanz aus.',
      'Leck langsam an einem Finger und steck ihn dir in den Mund, während du die Person ansiehst, die dir gegenübersteht.',
      'Flüstere einer Person, die damit einverstanden ist, zu, in welcher Stellung du sie gerne hättest.',
      'Lege deinen Kopf für eine ganze Runde auf den Schoß einer Person, die damit einverstanden ist.',
      'Zeig mal, wie du deine Zunge bewegst, wenn du Oralsex hast, an einem Eis am Stiel oder an einem Löffel.',
      'Lass dir die Oberschenkel 30 Sekunden lang von einer Person massieren, die damit einverstanden ist.',
      'Beschreibe die Stelle an deinem Körper, die dich in den Wahnsinn treibt, wenn sie berührt wird.',
      'Tue zwanzig Sekunden lang so, als würdest du ein Kissen leidenschaftlich umarmen.',
      'Küsse die Hand einer Person, die damit einverstanden ist, und fahre dabei bis zum Ellbogen fort.',
      'Zeig, wie frech du sein kannst, indem du einen zehnsekündigen Striptease nachahmst.',
      'Flüstere jedem aus der Gruppe nacheinander ins Ohr, wie heiß du sie findest.',
      'Lass dir die Augen verbinden und rate, wer von den bereitwilligen Personen dir auf die Wange küsst.',
      'Beschreibe, wie du beim Vorspiel gerne berührt wirst.',
      'Imitieren Sie zehn Sekunden lang überzeugend die Hündchenstellung in der Luft.',
      'Er leckt ganz unanständig am Glasrand, während alle zuschauen.',
      'Mach vor der Gruppe einen 30 Sekunden langen, wilden Twerk.',
      'Lege die Hand einer Person, die damit einverstanden ist, auf deine Hüfte und führe sie beim Tanzen.',
      'Erzähl uns, was das Gewagteste war, das du im Bett getan hast, um Eindruck zu machen.',
      'Tue so, als würdest du im Stehen deine Beine mit Hilfe der Luft um jemanden schlingen.',
      'Lass dich von einer Person, die damit einverstanden ist, leicht am Nacken berühren und zeig, wie du darauf reagierst.',
      'Beschreibe ausführlich, wie du dir den Geschlechtsverkehr heute Abend vorstellst.',
      'Mache den erotischsten Laut, den du kannst, und schau dabei der Person, die dich anzieht, in die Augen.',
      'Küsse das Handgelenk einer Person, die damit einverstanden ist, und gleite mit deinen Lippen langsam nach oben.',
      'Zeig mir, wie du deinen Rücken am Höhepunkt der Lust durchbiegst.',
      'Flüstere der Person zu deiner Linken drei unanständige Wörter ins Ohr, sofern sie damit einverstanden ist.',
      'Lass dir von einer Person, die damit einverstanden ist, auf provokante Weise in den Finger beißen.',
      'Beschreibe den Körperteil einer hier anwesenden Person, der dich am meisten beeindruckt.',
      'Simuliere einen langsamen Orgasmus, indem du nur deinen Hals und dein Gesicht leicht berührst.',
      'Wende deinen verführerischen Blick und deine Lippen der Person zu, die dir am besten gefällt.',
      'Zieh dein T-Shirt aus oder öffne den Kragen und bleib zwei Runden lang so, wenn du dich dazu in der Lage fühlst.',
      'Lecke vor einem „Cicchetto“ das Salz von der Hand einer Person, die damit einverstanden ist.',
      'Lege deine Hände auf die Hüften einer Person, die damit einverstanden ist, und tanze mit ihr.',
      'Beschreibe das Unanständigste, was dir jemals im Bett ins Ohr geflüstert wurde.',
      'Tu so, als würdest du zehn Sekunden lang etwas sehr Intimes an einer Frucht ablecken.',
      'Lass dich von einer einwilligenden Person von hinten umarmen und bleib eine Runde lang so stehen.',
      'Zeig mal, wie du dich beim Sex bewegst, wenn du oben auf einem Stuhl sitzt.',
      'Flüstere demjenigen, der vor dir steht, deinen verbotenen Wunsch ins Ohr.',
      'Küsse langsam den Hals einer Person, die damit einverstanden ist, und zähle dabei bis zehn.',
      'Zeige dein Repertoire an Stöhnen in drei verschiedenen Intensitätsstufen.',
      'Lass dir von einer Person, die damit einverstanden ist, sanft ins Ohr pusten und reagiere darauf.',
      'Beschreibe, wie du deine Hände bei der Person vor dir einsetzen würdest, wenn du könntest.',
      'Simuliere einen Verführungstanz, indem du langsam einen Gürtel oder ein Accessoire abnimmst.',
      'Leck den Zucker von den Lippen einer Person, die damit einverstanden ist, sofern sie zustimmt.',
      'Imitier mal so gut es geht, wie du jemanden im Bett beim Namen rufst.',
      'Lege deine Stirn an die Stirn deines Gegenübers und atme zehn Sekunden lang tief ein und aus.',
      'Beschreibe die Dreier-Fantasie, die du dir vorstellst, und mit wem du sie ausleben würdest.',
      'Imitieren Sie in 30 Sekunden einen kompletten Striptease, ohne sich dabei auszuziehen.',
      'Lass dir von einer einwilligenden Person sanft über der Kleidung den Rücken kraulen.',
      'Zeig, wie du beim Betreten eines Raums mit den Hüften schwenkst, damit sich alle nach dir umdrehen.',
      'Flüstere einer Person, die damit einverstanden ist, zu, was du mit ihr machen würdest, wenn wir allein wären.',
      'Küsse die Innenseite des Handgelenks deines Gegenübers, während du ihm fest in die Augen schaust.',
      'Beschreibe das Geräusch, das dich beim Sex am meisten erregt.',
      'Simuliere eine stehende Umarmung, indem du dich fünfzehn Sekunden lang an die Wand lehnst.',
      'Zeige mit deinen Händen, wie groß der beeindruckendste Penis war, den du je hattest.',
      'Leck deinen Zeigefinger ab und streiche damit über deine Lippen, während du denjenigen ansiehst, der dich am meisten anzieht.',
      'Lass dir von einer Person, die damit einverstanden ist, sanft an den Haaren ziehen und zeige, wie du darauf reagierst.',
      'Beschreibe den absurdesten Ort, an dem du gerne Sex haben würdest.',
      'Imitieren Sie die 69er-Stellung mit einem Kissen für zehn Sekunden.',
      'Streichele sinnlich über das Gesicht einer Person, die damit einverstanden ist, und gleite dabei bis zum Hals hinab.',
      'Flüstere deinem Gegenüber eine Liste mit drei Dingen zu, die du heute Nacht mit ihm tun würdest.',
      'Zeige, wie man in einer Disco eng an jemanden geschmiegt tanzt – mit einer Person, die damit einverstanden ist.',
      'Lass dir von einer Person, die damit einverstanden ist, einen Abdruckkuss auf den Hals geben.',
      'Beschreibe das Aufregendste, was dir an einem öffentlichen Ort passiert ist.',
      'Tu so, als würdest du den Namen der attraktivsten Person im Raum stöhnen.',
      'Lecke langsam die Außenseite der Hand deines Gegenübers.',
      'Zeig mal, wie du dich ausziehst, wenn du jemanden verführen willst – ganz in Ruhe.',
      'Fahre mit einer Hand durch die Haare einer Person, die damit einverstanden ist, und nähere dein Gesicht.',
      'Beschreibe, was du mit den Lippen der Person tun würdest, die dich in diesem Raum am meisten anzieht.',
      'Tue zehn Sekunden lang so, als wärst du mit Handschellen ans Bett gefesselt, und setze dabei einen entsprechenden Gesichtsausdruck auf.',
      'Lass dir den entblößten Rücken von einer Person streicheln, die damit einverstanden ist, sofern sie zustimmt.',
      'Stöhne leise, als würdest du dich an einem öffentlichen Ort zurückhalten.',
      'Flüstere der Person zu deiner Rechten ins Ohr, was dein Fetisch ist – sofern sie damit einverstanden ist.',
      'Küss den Hals eines Kissens, als wäre es die Person, nach der du dich am meisten sehnst.',
      'Beschreibe das Verrückteste, was du mindestens einmal erleben möchtest.',
      'Tu so, als würdest du eine Tracht Prügel bekommen, und stöhne dabei zehn Sekunden lang.',
      'Lutsch langsam an einem Lutscher oder einem Eis am Stiel und schau dabei die Person an, die dir gefällt.',
      'Zeig mal, wie du dich krümmst, wenn dich jemand genau an der richtigen Stelle küsst.',
      'Lege deine Lippen auf die Schulter einer Person, die damit einverstanden ist, und gleite bis zum Ohr hinauf.',
      'Beschreibe das Vorspiel, das dich nie langweilt und dich in Ekstase versetzt.',
      'Tue so, als hättest du fünfzehn Sekunden lang leidenschaftlichen Sex gegen eine Tür.',
      'Lass dir von einer einwilligenden Person sanft auf die Unterlippe beißen.',
      'Mach ein besonders verführerisches Gesicht, während du mit den Händen über deinen Körper streichelst.',
      'Flüstere der Person, die vor dir steht, mit deutlichen Worten zu, wie sehr du sie begehrst.',
      'Küsse die Finger einer Person, die damit einverstanden ist, nacheinander auf sinnliche Weise.',
      'Beschreibe die Stellung, in der du am leichtesten zum Orgasmus kommst.',
      'Simuliere einen erotischen Tanz, indem du dich langsam an einem Stuhl reibst.',
      'Leck einen imaginären Tropfen von der Brust oder dem Hals der Person vor dir ab, sofern diese damit einverstanden ist.',
      'Zeig mal, wie du dich unter der Bettdecke bewegst, wenn du Liebe machst.',
      'Lege deine Hand auf das Herz einer Person, die damit einverstanden ist, und gleite langsam in Richtung Bauch.',
      'Beschreibe den längsten Orgasmus, den du je hattest, und wie es dazu kam.',
      'Tu so, als würdest du zehn Sekunden lang auf anzügliche Weise an einem Finger lutschen, während du die Gruppe ansiehst.',
      'Lass dich von einer Person, die damit einverstanden ist, fest umarmen und flüstere ein Stöhnen.',
      'Mach dein „Höhepunkt“-Gesicht, während du den Rücken krümmst – fünf Sekunden lang.',
      'Flüstere jedem ins Ohr, was du gerne mit ihm machen würdest – und zwar einmal rundherum.',
      'Zeig mal, wie du reagierst, wenn man dich in den Nacken knabbert – mit deiner Stimme und einem Schaudern.',
      'Stelle deinen intensivsten Moment der Lust mit deiner Stimme und deinen Bewegungen zehn Sekunden lang nach.',
    ],
  };

  static const Map<String, List<String>> verita = {
    ContentTone.normal: [
      'Was war das Peinlichste, was du jemals in der Öffentlichkeit gemacht hast?',
      'Was war deine größte Lüge als Kind?',
      'Was ist dein musikalisches „Guilty Pleasure“?',
      'Welcher Film hat dich am meisten zum Weinen gebracht?',
      'Was war der dümmste Grund, wegen dem ihr euch gestritten habt?',
      'Was ist deiner Meinung nach dein größter Fehler?',
      'Welchen Fehler werfen dir deine Freunde vor, den du selbst überhaupt nicht erkennst?',
      'Was war das Teuerste, das du schon einmal kaputtgemacht hast?',
      'Hast du schon mal so getan, als ginge es dir schlecht, um etwas zu vermeiden?',
      'Welche Ausrede benutzt du am häufigsten?',
      'Was machst du, wenn du allein bist und dich niemand sieht?',
      'Was ist deine seltsamste Angewohnheit?',
      'Wie viel Zeit verbringst du tatsächlich jeden Tag mit deinem Handy?',
      'Welche App öffnest du am häufigsten, ohne einen bestimmten Grund zu haben?',
      'Was war deine letzte echte Suche im Internet?',
      'Was ist das älteste Foto, das du auf deinem Handy hast?',
      'Wem hast du zuletzt geschrieben?',
      'Was war die peinlichste Nachricht, die du je verschickt hast?',
      'Hast du schon einmal eine Nachricht an die falsche Person geschickt? Was stand darin?',
      'Was war das Schönste, was dir jemals jemand gesagt hat?',
      'Was war das seltsamste Kompliment, das du je bekommen hast?',
      'Wer ist der wichtigste Mensch in deinem Leben?',
      'Wen würdest du anrufen, wenn du um drei Uhr nachts ein ernstes Problem hättest?',
      'Was schätzt du an einem Freund am meisten?',
      'Was war der schönste Moment dieses Jahres?',
      'Was war der schwierigste Moment dieses Jahres?',
      'Wovor hast du in Bezug auf die Zukunft am meisten Angst?',
      'Was ist dein Traum, den du noch niemandem erzählt hast?',
      'Was würdest du tun, wenn du morgen nicht mehr arbeiten müsstest?',
      'Wenn du eine Entscheidung rückgängig machen könntest, welche wäre das?',
      'Worauf bist du am stolzesten?',
      'Welches Kompliment würdest du gerne erhalten?',
      'Was hebt deine Stimmung in fünf Minuten?',
      'Was bringt dich am schnellsten auf die Palme?',
      'Welcher Marotte kannst du einfach nicht entkommen?',
      'Bist du ordentlicher oder unordentlicher, als du zugibst?',
      'Wann hast du das letzte Mal so sehr gelacht, dass dir die Tränen kamen?',
      'Was war das Mutigste, was du je getan hast?',
      'Was würdest du niemals für Geld tun?',
      'Für wie viel Geld würdest du dir die Haare komplett abrasieren lassen?',
      'Was ist dein verborgenes Talent?',
      'Was ist eine Sache, die alle außer dir können?',
      'Was war das Schwierigste, was du gelernt hast?',
      'Welche Note würdest du deinem Leben im Moment auf einer Skala von 1 bis 10 geben?',
      'Was fehlt dir noch, um eine glatte 10 zu erreichen?',
      'Was war der schönste Ort, an dem du schon einmal warst?',
      'Wo würdest du gerne leben, wenn du die Wahl hättest?',
      'Welche Reise würdest du morgen noch einmal unternehmen?',
      'Was war dein schlimmster Urlaub?',
      'Hast du schon einmal einen Flug oder einen Zug verpasst? Wie ist es ausgegangen?',
      'Was war das Seltsamste, das du je gegessen hast?',
      'Welches Gericht kannst du am besten kochen?',
      'Was ist dein Lieblingsessen, das dir Trost spendet?',
      'Würdest du einen Monat lang jeden Tag dasselbe Gericht essen, wenn du dafür tausend Euro bekämst?',
      'Was war das Nutzloseste, das du je gekauft hast?',
      'Wie lange brauchst du wirklich, um dich fertig zu machen?',
      'Welches Kleid würdest du nicht wegwerfen, obwohl du es eigentlich solltest?',
      'Welchem Modetrend bist du gefolgt, den du jetzt ablehnst?',
      'Welche Frisur bereust du?',
      'Würdest du dir ein Tattoo stechen lassen? Wo und was?',
      'Was hast du schon einmal nur getan, um jemand anderem eine Freude zu machen?',
      'Hast du schon mal so getan, als hättest du etwas verstanden, um dich nicht zu blamieren?',
      'Bei welchem Thema bluffst du am meisten?',
      'Welches Buch hast du angeblich gelesen, aber nicht zu Ende gelesen?',
      'Welche Serie hast du auf halbem Weg abgebrochen?',
      'Welche Figur ähnelt dir am meisten?',
      'Wenn du ein Tier wärst, welches würdest du sein und warum?',
      'Wenn du deinen Namen ändern müsstest, welchen würdest du wählen?',
      'Welchen Spitznamen hast du als Kind gehasst?',
      'Was war das Langweiligste, was du jemals beruflich gemacht hast?',
      'Welchen Kollegen oder Klassenkameraden konntest du nicht ausstehen und warum?',
      'Was schiebst du schon am längsten vor dir her?',
      'Um wie viel Uhr gehst du eigentlich ins Bett?',
      'Wie oft schaltest du den Wecker aus, bevor du aufstehst?',
      'Wo ist dein Lieblingsplatz in der Wohnung?',
      'Was würdest du mitnehmen, wenn du innerhalb einer Minute aus deinem Zuhause fliehen müsstest?',
      'Welcher Gegenstand liegt dir am meisten am Herzen?',
      'Was war das schönste Geschenk, das du je bekommen hast?',
      'Was war das hässlichste Geschenk, das du je bekommen hast?',
      'Hast du schon einmal ein Geschenk weiterverschenkt?',
      'Welchen Vorsatz hast du zu Beginn des Jahres gefasst, den du nie eingehalten hast?',
      'Welche Gewohnheit möchtest du ablegen?',
      'Welche Gewohnheit möchtest du dir aneignen?',
      'Wen aus der Gruppe würdest du um einen ernsthaften Rat bitten?',
      'Wer aus der Gruppe bringt dich am meisten zum Lachen?',
      'Was hast du von den Leuten gelernt, die heute Abend hier waren?',
      'Was soll die Gruppe über dich wissen?',
      'Welche Frage hättest du dir gewünscht, dass sie heute Abend nicht gestellt worden wäre?',
      'Gibt es etwas, das du schon immer mal jemanden hier fragen wolltest?',
      'Wenn du diesen Abend mit einem Wort beschreiben müsstest, welches wäre das?',
      'Was war das Peinlichste, das dir in der Schule passiert ist?',
      'Was ist der absurdeste Traum, an den du dich erinnern kannst?',
      'Welche „weiße Lüge“ erzählst du am häufigsten?',
      'Welches Essen tust du aus reiner Höflichkeit so, als würde es dir schmecken?',
      'Wenn du für einen Tag eine Superkraft hättest, was würdest du als Erstes tun?',
      'Welche berühmte Person würdest du gerne zum Abendessen einladen und was würdest du sie fragen?',
      'Was war das Lustigste, das bei einem deiner Familientreffen passiert ist?',
      'Wenn du für einen Tag dein Leben mit jemandem tauschen könntest, wen würdest du wählen?',
      'Welches Lied singst du immer, ohne den Text richtig hinzubekommen?',
      'Was war das Seltsamste, was du aus Langeweile getan hast?',
      'Ist dir schon einmal in einem Moment, in dem es absolut verboten war, ein Lachen entwischt? Erzähl mal.',
      'Was war die peinliche Situation, über die du heute lachst, die dich damals aber völlig aus der Bahn geworfen hat?',
      'Was ist der seltsamste Gegenstand, den du in deinem Zimmer aufbewahrst?',
      'Was ist das Kindischste, was du heute noch tust?',
      'Wenn dein Leben ein Film wäre, welcher Schauspieler würde dich dann spielen?',
      'Was war deine schlechteste „geniale“ Idee?',
      'Hast du schon mal vor dem Spiegel gesungen und dabei die Haarbürste als Mikrofon benutzt?',
      'Welches Wort sprichst du immer falsch aus?',
      'Was ist dein verrücktestes Rekord, ganz gleich, was als Rekord zählt?',
      'Was würdest du als Erstes tun, wenn du morgen früh eine Million gewinnen würdest?',
      'Was ist die nutzloseste App, die du dir heruntergeladen und nie benutzt hast?',
      'Bist du schon mal an einem seltsamen Ort eingeschlafen? Wo?',
      'Was suchst du im Internet, weil du dich schämst, es nicht zu wissen?',
      'Welches Gericht hast du auf die spektakulärste Art und Weise vermasselt?',
      'Welche Regel gab es bei dir zu Hause, die du für ganz normal gehalten hast, die aber eigentlich total seltsam war?',
      'Welche Zeichentrickfigur hat dir als Kind Angst gemacht?',
      'Was war das Absurdeste, woran du als Kind geglaubt hast?',
      'Hast du schon einmal auf die Begrüßung von jemandem geantwortet, der eigentlich eine andere Person begrüßt hat?',
      'Welche Benachrichtigung macht dir am meisten Angst?',
      'Welches Lied weckt jedes Mal Erinnerungen in dir?',
      'Wenn du dich für einen Tag an einen beliebigen Ort teleportieren könntest, wohin würdest du gehen?',
      'Von welchem Beruf hast du als Kind geträumt?',
      'Was ist das, was alle lieben, du aber überhaupt nicht?',
      'Welche Trash-Sendung schaust du dir an und würdest du mit aller Kraft verteidigen?',
      'Hast du schon einmal mit deinem Haustier oder mit Pflanzen so gesprochen, als ob sie alles verstehen würden?',
      'Was kannst du am schlechtesten, machst aber trotzdem immer wieder mit Begeisterung?',
      'Was ist die schönste Nachricht, die du auf deinem Handy gespeichert hast?',
      'Welche abwegige Theorie glaubst du ein bisschen, obwohl du weißt, dass sie absurd ist?',
      'Wie sieht dein Überlebensplan für den Fall einer Zombie-Apokalypse aus?',
      'Was würdest du lieber können: fliegen oder Gedanken lesen – und warum?',
      'Was war die kreativste Ausrede, die du schon einmal für eine Verspätung benutzt hast?',
      'Was hast du als Kind gemacht, von dem du dir wünschst, dass es auch heute noch gesellschaftlich akzeptiert wäre?',
      'Wer aus der Gruppe würde deiner Meinung nach auf einer einsamen Insel am längsten überleben?',
      'Welches italienische Wort findest du am lustigsten?',
      'Welches Geräusch oder welche Geräusche kannst du absolut nicht ertragen?',
      'Was war das Netteste, was du heimlich für jemanden getan hast?',
      'Hast du schon einmal bei einem Gewinnspiel oder einer Verlosung etwas gewonnen? Was denn?',
      'Welche Eissorte sollte deiner Meinung nach gesetzlich verboten werden?',
      'Welchen Film lieben alle, den du aber nie bis zum Ende geschafft hast?',
      'Welches Essen tust du so, als würdest du es nicht mögen, würdest es aber heimlich essen?',
      'Welches Lied singst du nur, wenn du dir sicher bist, dass dich niemand hört?',
      'Was ist das Absurdeste, was du tust, wenn du dir sicher bist, dass dich niemand beobachtet?',
      'Was ist deine nutzloseste Begabung?',
      'Was ist deine irrationalste Angst?',
      'Was war das schlechteste Geschenk, das du je weiterverschenkt hast?',
      'Was ist das Peinlichste in deinem YouTube-Verlauf?',
      'Welche Ausrede benutzt du am häufigsten, um eine Party zu verlassen?',
      'Welchen Zeichentrickfilm würdest du dir auch heute noch ganz ohne Scham ansehen?',
      'Wenn du für einen Tag deinen Job gegen den eines der Anwesenden tauschen könntest, wen würdest du wählen?',
      'Welches Kompliment freut dich am meisten?',
    ],
    ContentTone.mix: [
      'Wie war dein erstes Mal? Alter, Ort, Stellung und Bewertung von 1 bis 10.',
      'Mit wie vielen Leuten warst du im Bett? Nenne die genaue Zahl, ohne aufzurunden.',
      'Was war der absurdeste oder riskanteste Ort, an dem du es schon einmal gemacht hast?',
      'Hast du schon mal Analsex gehabt? Hat es dir gefallen? Sei ehrlich.',
      'Hast du schon einmal am selben Tag, an dem du jemanden kennengelernt hast, mit dieser Person geschlafen? Wie oft?',
      'Was war dein verrücktestes One-Night-Stand-Erlebnis und wo hat es stattgefunden?',
      'Hast du schon mal mit einem Freund Sex gehabt und dann so getan, als wäre nichts gewesen? Wer war das?',
      'Hast du schon einmal mit mehr als drei Personen gleichzeitig Sexting betrieben?',
      'Was war die unanständigste Nachricht, die du je verschickt oder erhalten hast? Nenne sie.',
      'Hast du schon einmal ein explizites Video von dir verschickt oder erhalten? Würdest du das wieder tun?',
      'Hast du schon einmal ein ungewolltes freizügiges Foto erhalten? Wie hast du wirklich reagiert?',
      'Was ist deine extremste erotische Fantasie, die du noch niemandem erzählt hast?',
      'Hast du schon mal einen Dreier gemacht? Wenn nicht, mit wem aus dieser Gruppe würdest du es machen?',
      'Gibt es in diesem Raum jemanden, mit dem du gerne die Nacht verbringen würdest? Einen Namen.',
      'Was würdest du lieber haben: einen wahnsinnigen, drei Minuten langen Orgasmus oder eine Stunde vollkommener Zärtlichkeit?',
      'Wer war der beste Liebhaber deines Lebens und warum? Was hat er Besonderes gemacht?',
      'Hast du schon einmal zwei verschiedene Personen innerhalb derselben Stunde geküsst? Wo wart ihr?',
      'Hast du es jemals schon mitten beim Sex bitter bereut, mit jemandem ins Bett gegangen zu sein?',
      'Bist du schon einmal neben jemandem aufgewacht und dann aus dem Fenster oder heimlich davongeschlichen?',
      'Was zählt im Bett mehr: die Technik, die Größe oder die geistige Verbundenheit?',
      'Bist du im Bett eher dominant oder devot? Nenne ein Beispiel dafür, was du gerne machst.',
      'Licht an, Spiegel und Videos oder völlige Dunkelheit? Begründe deine Wahl.',
      'Was war das aufregendste Kompliment, das dir beim Sex gemacht wurde?',
      'Hast du schon einmal einen Orgasmus vorgetäuscht, damit der Geschlechtsverkehr schneller vorbei ist? Wie oft?',
      'Was war das Peinlichste, das dir dabei je passiert ist?',
      'Wurdest du schon einmal von deinen Eltern oder einem Fremden dabei erwischt, als du gerade in Aktion warst?',
      'Hast du schon mal so getan, als würdest du schlafen, um das Schlafen zu vermeiden? Weil du keine Lust dazu hattest?',
      'Hast du schon mal über deine Leistungen gelogen, um bei deinen Freunden Eindruck zu machen?',
      'Was war dein längster Sexmarathon? Wie oft an einem Tag?',
      'Gibt es jemanden in dieser Gruppe, der dich schon allein durch das Reden mit ihm in Wallung gebracht hat?',
      'Was fällt dir als Erstes an einer Person auf, sodass du denkst: „Mit der möchte ich ins Bett gehen“?',
      'Welches Kleidungsstück findest du am sexyesten? Und welches lässt dich den Reiz verlieren?',
      'Hältst du dich für gut im Bett? Was ist deine unschlagbare Stärke?',
      'Was würdest du gerne im Bett besser können? Hast du dir schon mal Tutorials angesehen?',
      'Was war der frechste Anmachspruch, den du je benutzt hast und der tatsächlich funktioniert hat?',
      'Hast du schon einmal mit dem Partner eines engen Freundes geflirtet? Wie weit bist du dabei gegangen?',
      'Hast du schon mal jemandem eine falsche Telefonnummer gegeben, nachdem ihr geknutscht habt? Warum?',
      'Was war das Gewagteste, was du jemals an einem belebten öffentlichen Ort getan hast?',
      'Hattest du schon mal einen Sommerflirt, der mit einem heißen Video oder Foto endete?',
      'Was war der größte Altersunterschied, den du in einer sexuellen Beziehung hattest?',
      'Hast du schon einmal jemanden aus diesem Raum geküsst, ohne dass die anderen davon wussten?',
      'Wen von uns würdest du sofort küssen, wenn das Licht für eine Minute ausgehen würde?',
      'Wer von uns ist deiner Meinung nach im Bett am „wildesten“, wenn man ihn sich jetzt so ansieht?',
      'Hast du schon mal eine Dating-App nur für Gelegenheitssex genutzt? Wie viele Matches haben es ins Bett geschafft?',
      'Was ist der peinlichste Chat, den du gerade auf deinem Handy hast?',
      'Hast du schon mal um drei Uhr nachts einem Ex geschrieben, nur weil du einfach Lust dazu hattest?',
      'Was vermisst du am meisten im Bett an deinem letzten Partner?',
      'Hattest du schon einmal eine heimliche Affäre mit jemandem, der in einer Beziehung war? Wie ist es ausgegangen?',
      'Warst du schon einmal bewusst „der Andere“ oder „die Andere“? Hast du dich schuldig gefühlt?',
      'Was ist dein seltsamster oder unanständigster „Kink“?',
      'Oben oder unten? Vorne oder hinten? Antworte schnell, ohne darüber nachzudenken.',
      'Hast du schon einmal Schmerzen im Bett erlebt und festgestellt, dass es dir gefallen hat?',
      'Hast du schon einmal Sex in einem Büro oder am Arbeitsplatz gehabt?',
      'Hast du dich schon einmal selbst berührt, während du an jemanden gedacht hast, der sich in diesem Raum befindet?',
      'Welcher Teil deines Körpers bekommt im Bett die meisten Komplimente?',
      'Hast du schon mal für jemanden einen Striptease getanzt? Wie ist es gelaufen?',
      'Was war das Unanständigste, was du jemals zu jemandem gesagt hast, während ihr es getan habt?',
      'Wenn du dir eine berühmte Person für eine Nacht voller Sex aussuchen könntest, wer wäre das?',
      'Hast du schon einmal Sex im Meer, in einem Schwimmbad oder in einem öffentlichen Whirlpool gehabt?',
      'Zu welcher Tageszeit bist du normalerweise am meisten erregt?',
      'Was trägst du normalerweise zum Schlafen, wenn du mit jemandem zusammen bist, den du provozieren willst?',
      'Hast du schon mal Sex mit Socken an gehabt? Die Gruppe verurteilt dich, wenn du mit „Ja“ antwortest.',
      'Welche Stellung findest du am anstrengendsten, die dir aber am meisten Freude bereitet?',
      'Hast du schon einmal tantrischen Sex oder besonders lange Sex-Sessions ausprobiert? Erzähl mal.',
      'Hast du beim Vorspiel schon einmal Essen oder Eis benutzt? Wie ist es ausgegangen?',
      'Was ist das eindeutige Signal, das du sendest, wenn du es sofort tun willst?',
      'Wen von uns würdest du jetzt in einen privaten Raum mitnehmen, wenn du könntest?',
      'Was ist das Erste, woran du merkst, dass jemand dich wirklich begehrt?',
      'Hast du schon einmal jemanden deines eigenen Geschlechts geküsst? Hat es dir gefallen oder war es nur Neugier?',
      'Welche scheinbar harmlose Geste erregt dich mehr als jede andere?',
      'Verführst du lieber oder lässt du dich lieber verführen? Nenne ein konkretes Beispiel für deine letzte Eroberung.',
      'Was war das Mutigste, worum du im Bett gebeten hast, und wie wurde darauf reagiert?',
      'Hast du schon einmal einen erotischen Traum von einer Person gehabt, die sich gerade in diesem Raum befindet?',
      'Welcher Körperteil eines Partners bringt dich völlig aus der Fassung?',
      'Wie lange dauert für dich die perfekte Nacht und wie oft würdest du das gerne tun?',
      'Hast du schon einmal zu zweit ein Sexspielzeug benutzt? Wenn nicht, würdest du es gerne einmal ausprobieren?',
      'Was war die größte Lüge, die du jemals erzählt hast, um mit jemandem ins Bett zu kommen?',
      'Hattest du schon einmal heimlich ein Auge auf einen Freund deines Partners geworfen?',
      'Wo in deiner Wohnung machst du das am liebsten, abgesehen vom Bett?',
      'Hast du schon mal beim ersten Date Sex gehabt? Hast du es bereut oder es noch einmal gemacht?',
      'Welcher Satz lässt dich sofort jemandem zu Füßen liegen?',
      'Bevorzugst du eine ganz langsame erotische Massage oder möchtest du gleich zur Sache kommen?',
      'Was war das Gewagteste, das du je getragen hast, um jemanden um den Verstand zu bringen?',
      'Hast du schon einmal versehentlich zwei Menschen dabei beobachtet oder belauscht, wie sie es getan haben? Erzähl mal.',
      'Wie lange hat dein Vorspiel bisher am längsten gedauert, und würdest du dir mehr oder weniger davon wünschen?',
      'Wenn du deinen Stil im Bett mit einem einzigen Wort beschreiben müsstest, welches wäre das?',
      'Hattest du schon einmal ein heimliches Treffen in einer öffentlichen Toilette oder in einem Auto?',
      'Wann hast du dir schon einmal jemanden gewünscht, den du nicht haben konntest?',
      'Hast du dich schon einmal in jemanden verliebt, nur wegen der Art, wie er oder sie geküsst hat?',
      'Was würde niemand jemals von dir im Bett vermuten?',
      'Hast du schon mal eine anzügliche Nachricht an die falsche Person geschickt? Wie ist das ausgegangen?',
      'Wer in diesem Raum kann deiner Meinung nach am besten flirten, ohne dass es auffällt?',
      'Was ist deine absolute Grenze im Bett, das, was du niemals tun würdest?',
      'Hast du schon einmal jemanden geküsst, nur um eine andere Person eifersüchtig zu machen?',
      'Welchen Teil von dir würdest du dir wünschen, dass jemand öfter küsst?',
      'Hattest du schon einmal eine Beziehung, die ausschließlich auf Sex beruhte? Wie lange hat sie gedauert?',
      'Welche Fantasie teilst du mit deinem Partner, die du aber noch nie in die Tat umgesetzt hast?',
      'Was erregt dich mehr: die Stimme, der Blick oder die Hände einer Person?',
      'Hast du schon einmal so getan, als wärst du an jemandem nicht interessiert, den du aber eigentlich unbedingt haben wolltest?',
      'Was war die längste Verführung, bevor du schließlich mit jemandem ins Bett gegangen bist?',
      'Hast du schon mal Sex gehabt, während du ein bestimmtes Lied gehört hast? Welches?',
      'Welches Kompliment über dein Aussehen sorgt dafür, dass du dich sofort begehrenswert fühlst?',
      'Hast du dich schon einmal auf rein körperlicher Ebene auf den ersten Blick verliebt? In wen und wie ist das abgelaufen?',
      'Magst du lieber langsame, innige Küsse oder heftige, leidenschaftliche Küsse?',
      'Was war das Heißeste, was dir jemand ins Ohr geflüstert hat, während ihr es getan habt?',
      'Hast du dich schon einmal gleichzeitig nach zwei Menschen gesehnt? Wie bist du damit umgegangen?',
      'Welcher Duft – dein eigener oder der eines anderen – verbindet sich bei dir mit dem besten Sex, den du je hattest?',
      'Hast du schon einmal vor den Augen deines Partners ganz unverhohlen mit jemandem geflirtet?',
      'Welche Stellung würdest du gerne einmal ausprobieren, hast dich aber noch nie getraut, sie vorzuschlagen?',
      'Hast du schon einmal eine Erfahrung mit mehr als zwei Personen gemacht? Wenn nicht, würdest du es tun – und mit wem hier?',
      'Was nimmt dir sofort die Lust, gerade wenn du dabei bist, es zu tun?',
      'Was ist das Sexieste, was jemand voll bekleidet tun kann?',
      'Hattest du schon einmal einen Flirt mit jemandem, der viel älter oder jünger war als du?',
      'Was ist dein geheimes Zeichen, um jemandem zu verstehen zu geben, dass du ihn heute Abend willst?',
      'Hast du dich schon einmal in einem völlig unpassenden Moment erregt? Wo warst du da?',
      'Was macht dich nach Meinung derjenigen, die schon mit dir zusammen waren, zu einem unvergesslichen Liebhaber?',
      'Hast du schon mal an einen Ex gedacht, während du mit einem anderen im Bett warst?',
      'Was ist das unanständigste Wort, das du gerne ins Ohr geflüstert bekommst?',
      'Hast du schon mal jemanden geküsst, als der Adrenalinspiegel hoch war, zum Beispiel nach einer gefährlichen Situation?',
      'Magst du lieber geplanten und gut vorbereiteten Sex oder spontanen und mitreißenden?',
      'Wann warst du am ehesten in Gefahr, bei deiner Tat entdeckt zu werden?',
      'Hast du jemals einen erotischen Brief oder eine erotische Nachricht geschrieben oder erhalten, die du noch aufbewahrst?',
      'Wen aus diesem Raum würdest du küssen, wen würdest du mit ins Bett nehmen und wen würdest du meiden? Sei ehrlich.',
      'Was ist dein versautester Gedanke, wenn du jemanden siehst, den du total toll findest?',
      'Hast du im Urlaub schon einmal ein Abenteuer erlebt, von dem du noch niemandem erzählt hast?',
      'Welches Rollenspiel würdest du gerne mindestens einmal im Leben ausprobieren?',
      'Bist du schon mal erregt neben einem Freund aufgewacht? Was hast du gemacht?',
      'Was war das Peinlichste, das du online zum Thema Sex gesucht hast?',
      'Hattest du schon einmal Angst, jemanden im Bett zu enttäuschen? Wie ist es dann gelaufen?',
      'Wann hast du dich am meisten begehrt gefühlt?',
      'Machst du lieber im Dunkeln Liebe oder möchtest du deinem Partner dabei direkt in die Augen schauen?',
      'Hast du schon einmal an einem Abend mehr als eine Person geküsst? Wie viele?',
      'Was wäre das Verrückteste, das du für eine Nacht mit der Person tun würdest, die du dir wünschst?',
      'Ist es dir schon einmal passiert, dass du deine Stöhnen unterdrücken musstest, damit dich niemand hört? Wo?',
      'Was ist deine geheime erogene Zone, die nur wenige entdeckt haben?',
      'Hast du schon einmal ohne zu zögern den ersten Schritt bei einer Person gemacht, die du gerade erst kennengelernt hast?',
      'Was gibt dir das größte Selbstvertrauen, wenn du nackt bist?',
      'Hattest du schon einmal eine Fernbeziehung, die ausschließlich von heißen Videoanrufen getragen wurde?',
      'Welche erotische Erinnerung kommt dir am häufigsten in den Sinn, wenn du allein bist?',
      'Wenn dein Traumpartner dich im Bett um nur eine Sache bitten würde, was würdest du dir wünschen?',
      'Hast du nach einem heftigen Streit schon mal Versöhnungssex gehabt? War er besser?',
      'Mit wem hast du die größte Chemie im Bett gehabt und warum?',
      'Hast du schon einmal versucht, einer Versuchung zu widerstehen, und bist dann kläglich gescheitert? Mit wem?',
      'Auf welche Körperpartie deines idealen Partners fällt dein Blick als Erstes?',
      'Was erregt dich mehr: beobachtet zu werden oder zuzuschauen, während du es tust?',
      'Hast du schon einmal eine „Freunde-mit-Vorteilen“-Vereinbarung getroffen, die schiefgelaufen ist? Erzähl mal.',
      'Was ist das Romantischste und das Versauteste, das du dir in ein und derselben Nacht wünschen würdest?',
      'Wer in diesem Raum versucht deiner Meinung nach gerade, dich anzubaggern?',
      'Was ist die intimste Frage, die du einer der heute Abend anwesenden Personen stellen würdest?',
      'Was würdest du am liebsten gerade jetzt tun, wenn das Spiel es zulassen würde?',
    ],
    ContentTone.hot: [
      'Hast du dich beim Sex schon einmal gefesselt oder dich fesseln lassen?',
      'Hast du schon einmal das Sperma oder den Samenerguss deines Partners probiert?',
      'Hättest du Lust auf einen Dreier? Mit wem von den Anwesenden?',
      'Wo war der riskanteste Ort, an dem du das gemacht hast?',
      'Wie oft am Tag masturbierst du im Durchschnitt?',
      'Welche Sexstellung bringt dich am schnellsten zum Orgasmus?',
      'Hast du schon mal einen Orgasmus vorgetäuscht? Bei wie vielen Leuten?',
      'Was war das Unanständigste, was dir jemand im Bett ins Ohr geflüstert hat?',
      'Hast du schon einmal an einem öffentlichen Ort Oralsex gehabt?',
      'Mit wem von den Anwesenden würdest du ohne zu zögern Sex haben?',
      'Was ist dein Lieblings-Sexspielzeug und wie oft benutzt du es?',
      'Hattest du schon einmal einen Orgasmus allein durch Oralsex?',
      'Was macht dich mehr an: Oralsex zu geben oder zu empfangen?',
      'Hast du schon mal ein intimes Video an jemanden geschickt?',
      'Welche sexuelle Fantasie hast du noch niemandem anvertraut?',
      'Hast du schon einmal in derselben Nacht mit mehr als einer Person Sex gehabt?',
      'Welche Körperstelle bringt dich um den Verstand, wenn sie berührt wird?',
      'Hast du schon einmal Bondage ausprobiert oder reizt dich der Gedanke daran?',
      'Wie lange hat dein längster Geschlechtsverkehr gedauert?',
      'Hast du schon mal beim ersten Date Sex gehabt?',
      'Was war das Versauteste, was du je im Bett gemacht hast?',
      'Hast du schon einmal jemanden deines eigenen Geschlechts geküsst?',
      'Hast du dich schon mal masturbiert, während du an jemanden hier im Raum gedacht hast?',
      'Wie viele Partner hattest du bisher?',
      'Hattest du schon einmal Analsex? Hat es dir gefallen?',
      'Was ist deine geheimste erogene Zone?',
      'Hast du beim Sex schon einmal Handschellen oder Fesseln benutzt?',
      'Wie lange brauchst du normalerweise, um zum Orgasmus zu kommen?',
      'Hast du schon mal Sex im Auto gehabt? Wo habt ihr geparkt?',
      'Wer von den Anwesenden ist wohl der Beste im Bett?',
      'Hast du schon einmal Spanking ausprobiert – sei es als Gebender oder als Empfangender?',
      'Was war das Gewagteste, das du jemals getan hast, um einen Partner in Stimmung zu bringen?',
      'Hast du schon mal Sex gehabt, während andere im Nebenzimmer waren?',
      'Magst du Sex im Dunkeln oder bei eingeschaltetem Licht?',
      'Hattest du schon einmal eine Beziehung mit jemandem, der viel älter oder jünger war als du?',
      'Was ist dein ausgefallenster Fetisch?',
      'Hast du schon mal Sex im Wasser gehabt, im Schwimmbad oder am Meer?',
      'Wie oft pro Woche würdest du am liebsten Sex haben?',
      'Hast du schon mal Sex mit verbundenen Augen ausprobiert?',
      'Mit wem deiner Ex-Partner würdest du noch einmal Sex haben, und sei es auch nur für eine Nacht?',
      'Welche Stellung im Bett kannst du überhaupt nicht ausstehen?',
      'Hattest du schon einmal einen multiplen Orgasmus?',
      'Hast du schon einmal eine eher ungewöhnliche Körperstelle deines Partners geleckt oder geküsst?',
      'Was war der unanständigste Gedanke, den du heute hattest?',
      'Hast du schon mal mit jemandem Sex gehabt, dessen Namen du nicht mehr wusstest?',
      'Reizt dich der Gedanke, beim Sex beobachtet zu werden?',
      'Hast du schon mal beim Vorspiel Essen benutzt? Was denn?',
      'Welche Fantasie würdest du gerne mit einer der hier anwesenden Personen verwirklichen?',
      'Hast du schon mal bei den Eltern von jemandem Sex gehabt?',
      'Wie wichtig ist dir das Aussehen eines Partners – auf einer Skala von eins bis zehn?',
      'Hast du beim Sex schon einmal einvernehmliche Schmerzen erlebt und es hat dir gefallen?',
      'Was war das Seltsamste, das dich erregt hat?',
      'Hattest du schon einmal eine Beziehung mit zwei Personen gleichzeitig?',
      'Masturbierst du eher morgens oder abends?',
      'Hast du schon mal Telefonsex oder Sex per Videoanruf gehabt?',
      'An welcher Stelle deines Körpers würdest du am liebsten öfter geküsst werden?',
      'Hast du schon einmal mit einem Partner eine Pornoszene nachgespielt?',
      'Mit wem von den Anwesenden würdest du gerne einen Zungenkuss austauschen?',
      'Hattest du schon einmal eine Beziehung, bei der es nur um Sex ging?',
      'Was war dein peinlichster Orgasmus, den du jemals erklären musstest?',
      'Hast du schon einmal besondere Dessous oder Unterwäsche getragen, um jemanden zu verführen?',
      'Magst du es, beim Sex schmutzige Sachen zu sagen, oder ist dir das unangenehm?',
      'Hast du schon mal Sex in einer öffentlichen Toilette gehabt?',
      'Wie viele Minuten dauert dein Vorspiel normalerweise?',
      'Hast du schon einmal tantrischen Sex oder langsamen, ausgedehnten Sex ausprobiert?',
      'Was war das Unverschämteste, was du im Bett schon einmal verlangt hast?',
      'Hattest du schon einmal Sex mit einem Kollegen oder einem Vorgesetzten?',
      'Was erregt dich mehr: leidenschaftlicher Sex oder zärtlicher Sex?',
      'Hattest du schon einmal ein Treffen, das ausschließlich online zum Zweck des Sex vereinbart wurde?',
      'Auf welchen Teil deines Körpers bist du im Bett am meisten stolz?',
      'Hast du schon einmal Sex im Freien gehabt, im Wald oder in einem Park?',
      'Mit wem von den Anwesenden würdest du flirten, wenn du heute Abend Single wärst?',
      'Hast du schon einmal mehr als einen Orgasmus während desselben Geschlechtsverkehrs erlebt?',
      'Was ist das Verbortenste, das du wenigstens einmal ausprobieren möchtest?',
      'Hast du schon mal mit jemandem Sex gehabt, der viel mehr Erfahrung hatte als du?',
      'Magst du es, dominiert zu werden, oder hast du lieber die Kontrolle?',
      'Hast du schon einmal Sex in der Dusche oder in der Badewanne gehabt?',
      'Was ist dein Rekord an sexuellen Begegnungen an einem einzigen Tag?',
      'Hast du schon einmal an einem Abend zwei Personen geküsst?',
      'In welcher Position fühlst du dich am sexiesten?',
      'Hast du schon mal Sex gehabt, während du mit jemand anderem telefoniert hast?',
      'Hast du dich schon mal in einem völlig unpassenden Moment erregt?',
      'Hast du schon mal mit der falschen Person Sex gehabt und es bereut?',
      'Was ist das Intimste, das du nur einem Partner anvertraut hast?',
      'Hast du schon einmal Sex mit einem gemeinsamen Vibrator ausprobiert?',
      'Mit wem von den Anwesenden glaubst du, die größte sexuelle Anziehungskraft zu haben?',
      'Hast du schon mal auf einem Tisch oder einem Küchenregal Sex gehabt?',
      'Schaut du dir gerne heiße Videos an – allein oder zu zweit?',
      'Hattest du schon einmal Sex im Aufzug oder an einem ungewöhnlichen Ort?',
      'Was war das aufregendste Kompliment, das dir jemals zu deinem Körper gemacht wurde?',
      'Hast du schon mal Rollenspiele im Bett ausprobiert? Welches Szenario?',
      'Wie viele verschiedene Stellungen schaffst du in einem einzigen Geschlechtsverkehr?',
      'Hast du schon einmal allein durch die Stimulation des Halses oder der Ohren einen Orgasmus gehabt?',
      'Was ist es, das bei dir sofort Lust auf Sex weckt?',
      'Hast du schon mal Sex im Zelt oder auf dem Campingplatz gehabt?',
      'Hast du dich schon einmal in jemanden verliebt, nur wegen dessen Leistung im Bett?',
      'Hast du schon einmal Öle oder Cremes beim Sex oder bei Massagen verwendet?',
      'Wer ist die Person hier, mit der du noch nie geflirtet hast, an die du aber schon einmal gedacht hast?',
      'Hast du schon mal Sex gehabt, ohne dabei auch nur ein Wort zu sagen?',
      'Was erregt dich mehr: Küsse auf den Hals oder auf die Lippen?',
      'Hast du schon mal Sex in einem Stundenhotel gehabt?',
      'Was war das Verrückteste, was dir ein Partner jemals vorgeschlagen hat?',
      'Hast du schon einmal versucht, mit gefesselten Händen und Füßen zu sein?',
      'Mit wem von den Anwesenden würdest du gerne eine leidenschaftliche Nacht verbringen?',
      'Hattest du schon einmal Geschlechtsverkehr, der gerade dann unterbrochen wurde, als es am schönsten war? Von wem?',
      'Machst du lieber Sex bei Musik oder in völliger Stille?',
      'Hast du schon einmal Essen vom Körper eines Partners abgeleckt?',
      'Welche Fantasie bringt dich am schnellsten zum Orgasmus?',
      'Hast du schon mal im Urlaub mit jemandem Sex gehabt, den du gerade erst kennengelernt hast?',
      'Wie laut bist du im Bett, auf einer Skala von eins bis zehn?',
      'Hast du schon einmal im Rahmen eines erotischen Spiels eine Tracht Prügel auf den Hintern bekommen?',
      'Was macht dich beim Vorspiel total verrückt?',
      'Hast du schon mal an einem Ort Sex gehabt, an dem ihr entdeckt werden hättet können?',
      'Hast du dich schon einmal an einem öffentlichen Ort masturbiert?',
      'Hast du dir schon einmal gewünscht, dass der aktuelle oder ehemalige Partner eines Freundes dabei wäre?',
      'Was war der aufregendste Moment, an den du dich mit einem Partner erinnern kannst?',
      'Hast du schon einmal Sex mit verbundenen Augen und gefesselten Händen ausprobiert?',
      'Mit welcher berühmten Person würdest du ohne zu zögern Sex haben?',
      'Hast du schon mal mehr als dreimal in einer Nacht Sex gehabt?',
      'Was gefällt dir besser: Sex am Morgen oder nachts?',
      'Hast du schon mal jemanden nur aus einer Wette heraus geküsst und es hat dir dann gefallen?',
      'Was war das Erotischste, das du jemals in einer Nachricht geschrieben hast?',
      'Hast du schon mal bei einer Party bei Freunden Sex gehabt?',
      'Was ist deine Schwachstelle, wenn dich jemand verführen will?',
      'Hast du schon einmal versucht, Sex mit einem neuen Accessoire oder Sexspielzeug zu haben?',
      'Mit wem von den Anwesenden kannst du dir eine unvergessliche Nacht vorstellen?',
      'Hast du schon einmal am Arbeitsplatz Sex gehabt?',
      'Was erregt dich beim Sex mehr: Augenkontakt oder Worte?',
      'Hattest du schon einmal Sex, der so intensiv war, dass dir die Kräfte ausgegangen sind?',
      'Was war das Versauteste, was du je getan hast, um einen Partner zu befriedigen?',
      'Hast du schon mal nachts am Strand Sex gehabt?',
      'Magst du es, beim Sex gebissen zu werden?',
      'Hattest du schon einmal einen Orgasmus, der so intensiv war, dass es dir fast peinlich war?',
      'Welchen Körperteil deines Partners küsst du als Erstes?',
      'Hast du schon mal versucht, vor einem Spiegel Sex zu haben?',
      'Mit wem von den Anwesenden würdest du dein erotischstes Geheimnis teilen?',
      'Hast du schon einmal mit jemandem Sex gehabt, von dem du dir geschworen hattest, ihn zu meiden?',
      'Nimmst du lieber die Initiative oder lässt du dich lieber verführen?',
      'Hast du dir schon einmal etwas mit einer Person ausgemalt, mit der du das eigentlich nicht tun solltest?',
      'Was ist das Gewagteste, das du nur für einen besonderen Abend tragen würdest?',
      'Hast du schon mal Sex gehabt, während es regnete – draußen oder in der Nähe eines offenen Fensters?',
      'Hast du dich schon mal daran aufgeilte, jemandem beim Ausziehen zuzusehen, ohne dass er es gemerkt hat?',
      'Hast du schon einmal in derselben Woche mehrere Partner gehabt?',
      'Welche Geste lässt dich sofort wissen, dass du jemanden im Bett haben willst?',
      'Hast du schon mal Sex gehabt und dabei über etwas Peinliches gelacht, das passiert ist?',
      'Mit wem von den Anwesenden würdest du gerne ein Verführungsspiel spielen?',
      'Hast du schon einmal Sex gehabt und dabei an jemand anderen gedacht als an die Person, mit der du gerade zusammen warst?',
      'Was war das Aufregendste, was dir schon einmal jemand gesagt hat, dass er mit dir machen möchte?',
      'Hattest du schon einmal Sex, der so leise war, dass du jedes Stöhnen unterdrücken musstest?',
      'Was ist dein geheimster sexueller Wunsch, den du hier noch niemandem verraten hast?',
    ],
  };
}
