class ContentDeBluff {
  const ContentDeBluff._();

  static const List<String> bluffFakes = [
    'Ich habe zwölf Stunden am Stück auf einem Flughafen geschlafen, während ich auf meinen Anschlussflug gewartet habe.',
    'Ich habe erst mit achtzehn Jahren schwimmen gelernt, weil ich Angst vor dem Wasser hatte.',
    'Ich habe einen Interkontinentalflug verpasst, weil ich am Gate eingeschlafen bin.',
    'Als Kind habe ich mich über eine Stunde lang in einem Einkaufszentrum verlaufen.',
    'In der Mittelstufe habe ich zusammen mit meiner Cousine einen Tanzwettbewerb gewonnen.',
    'Ich bin versehentlich auf einem Hochzeitsfoto von mir völlig unbekannten Leuten gelandet.',
    'Ich habe eine Woche lang als Kellner gearbeitet und wurde sofort entlassen.',
    'Ich habe für zwanzig Leute gekocht, ohne jemals zuvor einen Herd angezündet zu haben.',
    'Ich war während eines Beitrags in den Fernsehnachrichten für drei Sekunden im Fernsehen zu sehen.',
    'Ich habe in der Tiefkühlabteilung des Supermarkts einen sehr berühmten Schauspieler getroffen.',
    'Ich bin in einem fremden Land fünfzig Kilometer per Anhalter gefahren.',
    'Ich habe während eines heftigen Gewitters in den Bergen im Auto geschlafen.',
    'Ich bin in den falschen Zug gestiegen und auf der anderen Seite Italiens gelandet.',
    'Ich habe einen ganzen Silvesterabend im Krankenhaus verbracht, um einem Freund beizustehen.',
    'Als Kind bin ich von einem sehr hohen Baum gefallen, ohne mir auch nur einen Kratzer zuzuziehen.',
    'Ich habe mir beim Versteckspielen im Haus mir den Arm gebrochen.',
    'Ich habe mir spontan ein Tattoo stechen lassen und es schon am nächsten Tag bereut.',
    'Ich habe mir die Haare selbst geschnitten und musste sie ganz kurz rasieren.',
    'Ich habe mir die Haare neongrün gefärbt, um eine verlorene Wette einzulösen.',
    'Ich habe beim Karaoke vor hundert Leuten gesungen, die mich ausgebuht haben.',
    'Ich habe weniger als zwei Monate lang in einer Metal-Band Gitarre gespielt.',
    'Ich habe ein Liebeslied geschrieben, das ich noch niemandem vorgespielt habe.',
    'Ich habe fünf Jahre lang jeden Tag ein geheimes Tagebuch geführt, ohne auch nur einen Tag auszulassen.',
    'Ich habe ein 600-seitiges Buch in nur einer Nacht komplett gelesen.',
    'Ich habe denselben Film in derselben Woche dreimal im Kino gesehen.',
    'Ich habe einen ganzen dreiminütigen Monolog aus einem Film auswendig gelernt.',
    'Ich habe in einem Schultheaterstück mitgespielt und mir alle Dialoge ausgedacht.',
    'Ich habe ein ganzes Jahr lang in einem mehrstimmigen Chor gesungen.',
    'Ich habe eine Fremdsprache gelernt, indem ich mir einfach Fernsehserien in der Originalsprache angesehen habe.',
    'Ich habe eine Universitätsprüfung abgelegt, ohne gelernt zu haben, und habe eine 30 bekommen.',
    'Ich habe bei einer wichtigen Klassenarbeit abgeschrieben, und der Lehrer hat mich dabei erwischt.',
    'Ich habe eine ganze Woche lang die Schule geschwänzt, ohne dass meine Eltern davon wussten.',
    'Ich war der Letzte, der von einer riesigen Neuigkeit erfahren hat, die meine Familie betraf.',
    'Ich habe herausgefunden, dass ich einen Cousin zweiten Grades habe, der in Amerika lebt.',
    'Ich habe innerhalb von nur zwei Jahren in drei verschiedenen Städten gelebt.',
    'Ich habe einen kompletten Umzug ganz allein mit einem winzigen Auto bewältigt.',
    'Ich habe einen ganzen Monat lang in einem Haus ohne Fernseher und ohne Internet gelebt.',
    'Ich habe einen ganzen Sommer lang auf soziale Netzwerke verzichtet.',
    'Ich habe alle meine Social-Media-Profile für drei aufeinanderfolgende Monate gelöscht.',
    'Ich habe mein neues Handy ins Meer verloren, als ich ein Video gedreht habe.',
    'Ich habe meine gefüllte Brieftasche im Zug liegen lassen, und sie wurde mir zurückgegeben.',
    'Ich habe auf der Straße fünfzig Euro gefunden und sie bei der Polizei abgegeben.',
    'Ich habe zwanzig Euro mit einem Rubbellos gewonnen, das ich zufällig gekauft hatte.',
    'Ich habe ein Lottolos gekauft und es vor der Ziehung verloren.',
    'Aufgrund eines Fehlers des Kellners habe ich das Abendessen für eine Gruppe von Fremden bezahlt.',
    'Ich habe einen Monat lang jeden Tag genau dasselbe Gericht bestellt.',
    'Ich habe sieben Tage hintereinander zum Mittag- und Abendessen nur Pizza gegessen.',
    'Ich habe versucht, Veganer zu werden, und habe es nur zwei Wochen durchgehalten.',
    'Ich habe einen Kuchen gebacken, der so hart geworden ist, dass man ihn nicht essen konnte.',
    'Ich habe einen Topf komplett verbrannt, weil ich ihn auf dem eingeschalteten Herd vergessen hatte.',
    'Ich habe den Feueralarm im Hotel ausgelöst, als ich in meinem Zimmer gekocht habe.',
    'Genau am Tag vor einem wichtigen Abendessen ist mir der Backofen zu Hause kaputtgegangen.',
    'Ich habe ein riesiges Möbelstück zusammengebaut und am Ende blieben mir zehn Teile übrig.',
    'Ich habe mein Zimmer in einer Farbe gestrichen, die ich sofort zu hassen begann.',
    'Ich habe sechs Monate lang auf einer aufblasbaren Matratze auf dem Boden geschlafen.',
    'Ich habe mit einem Mitbewohner zusammengelebt, mit dem ich ein Jahr lang kein einziges Mal gesprochen habe.',
    'Ich habe mir während eines Auslandsurlaubs spontan einen Hund geholt.',
    'Ich habe jeder einzelnen Pflanze, die ich zu Hause habe, einen eigenen Namen gegeben.',
    'Ich habe alle Sukkulenten, die ich im Laufe der Jahre geschenkt bekommen habe, eingehen lassen.',
    'Ich habe ein Kätzchen gerettet, das auf einem sehr hohen Ast festsaß.',
    'Ich hatte schreckliche Angst vor einem Hund, der so groß war wie eine Katze.',
    'Ich bin einen Halbmarathon gelaufen, ohne auch nur einen Tag trainiert zu haben.',
    'Ich habe mich in einem teuren Fitnessstudio angemeldet und bin nur dreimal hingegangen.',
    'Ich habe nur ein einziges Mal in einer offiziellen Mannschaft Fußball gespielt.',
    'Mit dreißig habe ich zum ersten Mal versucht, Ski zu fahren, und bin sofort gestürzt.',
    'Ich habe einmal Fallschirmspringen ausprobiert und mir geschworen, das nie wieder zu tun.',
    'Ich habe einen Tauchgang gemacht und bin in zehn Metern Tiefe in Panik geraten.',
    'Ich habe einen kleinen Berg bestiegen, obwohl ich ungeeignete Schuhe trug.',
    'Ich habe zwei Nächte hintereinander im Zelt unter einem heftigen Gewitter geschlafen.',
    'Ich habe ganz allein eine Auslandsreise unternommen, ohne es jemandem zu sagen.',
    'Ich habe einen Flug für den falschen Tag gebucht und bin nicht abgeflogen.',
    'Ich habe eine ganze Nacht am Bahnhof verbracht und auf den nächsten Zug gewartet.',
    'Ich habe meinen besten Freund kennengelernt, als wir im Supermarkt in der Schlange standen.',
    'Ich habe zufällig einen alten Klassenkameraden wiedergetroffen, als ich in London war.',
    'Ich habe eine wichtige Freundschaft über Jahre hinweg aufrechterhalten, indem ich ausschließlich über den Chat kommuniziert habe.',
    'Ich habe einen sehr langen Liebesbrief geschrieben, den ich nie abgeschickt habe.',
    'Ich habe einen anonymen Brief erhalten, der meinen Tag völlig auf den Kopf gestellt hat.',
    'Ich habe die falsche Nummer gewählt und zehn Minuten lang telefoniert.',
    'Ich habe einen wichtigen geschäftlichen Anruf entgegengenommen, während ich nackt am Strand war.',
    'Ich habe während der gesamten Weihnachtsferien ununterbrochen gearbeitet.',
    'Ich habe meinen alten Job gekündigt, ohne einen Plan B zu haben.',
    'Ich habe ein Stellenangebot mit einem deutlich höheren Gehalt abgelehnt.',
    'Ich hatte ein Vorstellungsgespräch in einer Sprache, die ich nur sehr schlecht beherrschte.',
    'Ich habe eine für mein Leben entscheidende Entscheidung getroffen, indem ich eine Münze geworfen habe.',
    'Ich habe während einer sehr wichtigen Arbeitsbesprechung tief und fest geschlafen.',
    'Ich habe aufgrund eines technischen Fehlers eine vertrauliche E-Mail an das gesamte Unternehmen verschickt.',
    'Ich habe meinen neuen Chef versehentlich mit dem Namen meines Ex-Partners angesprochen.',
    'Ich habe monatelang mit einem Kollegen zusammengearbeitet, ohne jemals seinen Nachnamen zu erfahren.',
    'Ich habe so getan, als würde ich die Person, die mich auf der Straße begrüßt hat, sehr gut kennen.',
    'Ich habe einen Fremden begeistert begrüßt, weil ich dachte, er sei ein guter Freund von mir.',
    'Ich habe eine Person allein an ihrer Stimme erkannt, obwohl ich sie seit zehn Jahren nicht mehr gehört hatte.',
    'Ich habe den Geburtstag meiner Mutter vergessen und mich erst nach einer Woche wieder daran erinnert.',
    'Ich habe eine Überraschungsparty organisiert, die schon am Tag zuvor aufgeflogen war.',
    'Ich habe mehr als fünf Jahre lang ein sehr wichtiges Geheimnis für mich behalten.',
    'Ich habe meinen Eltern eine Lüge erzählt, die ein ganzes Jahr lang Bestand hatte.',
    'Ich habe meine Schuld gestanden, nur weil ich nachts nicht mehr schlafen konnte.',
    'Ich habe so verzweifelt geweint, als ich im Fernsehen eine Werbung mit Welpen gesehen habe.',
    'Ich habe bei einer Beerdigung laut vor Lachen gelacht und konnte einfach nicht mehr aufhören.',
    'Ich bin im Kino während der Vorpremiere eines Films, den ich unbedingt sehen wollte, eingeschlafen.',
    'Am Ende eines Films im Kino habe ich ganz allein und begeistert applaudiert.',
    'Ich habe im Auto aus voller Kehle gesungen, weil ich dachte, ich wäre ganz allein.',
    'Ich habe im Aufzug mit einem Fremden getanzt, der mich dabei beobachtet hat.',
    'Erst nach drei Jahren, in denen wir dort gewohnt hatten, habe ich mich mit meinem Nachbarn angefreundet.',
    'Gerade am Tag meines Umzugs habe ich alle Hausschlüssel verloren.',
    'Ich stand in meinem Pyjama auf dem Treppenabsatz und hatte mich aus meiner Wohnung ausgesperrt.',
    'Ich saß mehr als zwanzig Minuten lang in einem alten Aufzug fest.',
    'Ich bin versehentlich in die falsche Richtung auf eine sehr lange Rolltreppe gestiegen.',
    'Ich habe mich in einem eleganten Restaurant in der Toilette geirrt und bin in die gegenüberliegende Toilette gegangen.',
    'Ich bin versehentlich in in eine Arbeitsbesprechung hineingegangen und bin zehn Minuten dort geblieben.',
    'Ich habe im Zug laut telefoniert, ohne auf die Lautstärke zu achten.',
    'Ich habe genau der Person, über die ich gerade schlecht gesprochen hatte, eine liebevolle Nachricht geschickt.',
    'Ich habe einen Screenshot eines Chats gemacht und ihn versehentlich an die Person geschickt, mit der ich gechattet hatte.',
    'Ich habe versehentlich ein Foto meines Ex-Partners von vor zehn Jahren mit „Gefällt mir“ markiert.',
    'Ich habe einen sehr gemeinen Kommentar geschrieben und ihn nach einer Sekunde wieder gelöscht.',
    'Ich habe ein gefälschtes Social-Media-Profil erstellt, das ich nie zu nutzen gewagt habe.',
    'Ich habe mir an einem einzigen Wochenende eine ganze Fernsehserie mit drei Staffeln angesehen.',
    'Ich habe ein extrem schwieriges Videospiel in nur einer Nacht durchgespielt.',
    'Ich habe fünf Jahre lang wie besessen dasselbe Online-Spiel gespielt.',
    'Ich habe ein Kartenspiel in der Familie gewonnen, indem ich schamlos geschummelt habe.',
    'Ich habe eine absurde Wette verloren und musste mir die Haare blau färben.',
    'Ich habe eine dumme Wette abgeschlossen, die mich ein Abendessen für acht Personen gekostet hat.',
    'Ich habe eine extrem scharfe Chilischote gegessen, nur um eine Wette zu gewinnen.',
    'Ich habe innerhalb einer Stunde drei doppelte Espressi getrunken und die ganze Nacht kein Auge zugetan.',
    'Ich habe eine ganze Nacht lang nicht geschlafen, weil ich mir unnötigerweise Sorgen gemacht habe.',
    'Ich hatte einen Traum, der so realistisch war, dass ich gleich nach dem Aufwachen fest daran geglaubt habe.',
    'Ich habe im Schlaf gesprochen und dabei ein Geheimnis preisgegeben, das geheim bleiben sollte.',
    'Als Kind bin ich im Schlaf durch das ganze Haus gelaufen bin.',
    'Ich bin an einer anderen Stelle im Haus aufgewacht als dort, wo ich eingeschlafen bin.',
    'Ich habe am Nachmittag auf einer Bank in einem öffentlichen Park tief und fest geschlafen.',
    'Ich habe einen ganzen Tag verbracht, ohne mit jemandem ein Wort zu wechseln.',
    'Während einer Zugfahrt habe ich mich zwei Stunden lang intensiv mit einem Unbekannten unterhalten.',
    'Ich habe eine Brieftasche voller Geld zurückgegeben, die ich auf der Straße gefunden hatte.',
    'Ich habe bei einer Wohltätigkeitsverlosung einen Preis gewonnen und ihn nie abgeholt.',
    'Ich habe dreißig Tage hintereinander genau dasselbe zum Mittagessen gegessen.',
    'Ich habe so getan, als würde ich eine Fremdsprache sprechen, um im Urlaub nicht erkannt zu werden.',
    'Ich musste die Nachbarn um Hilfe bitten, weil ich meine Katze nicht mehr finden konnte.',
    'Ich habe so getan, als gäbe es Verbindungsprobleme, um ein langweiliges Geschäftsgespräch zu beenden.',
    'Ich bin mitten im Film aus dem Kino gegangen, weil ich mich zu Tode gelangweilt hatte.',
    'Ich bin zehn Minuten lang mit dem Hund eines Nachbarn Gassi gegangen, weil ich dachte, es wäre mein eigener.',
    'Ich habe eine Person, die ich überhaupt nicht kannte, mit großer Begeisterung begrüßt.',
    'Ich habe an einer Stadtführung durch meine Stadt teilgenommen und mich dabei als ausländischer Tourist ausgegeben.',
    'Ich habe zwei Jahre hintereinander meine Geburtstagsglückwünsche an die falsche Person geschickt.',
    'Ich habe eine hitzige Diskussion gewonnen, indem ich eine völlig erfundene Statistik angeführt habe.',
    'Ich habe den Regenschirm noch zehn Minuten lang offen gehalten, obwohl die Sonne bereits herausgekommen war.',
    'Ich habe mich bei einem Vorstellungsgespräch total blamiert, und trotzdem haben sie mich eingestellt.',
    'Ich habe jahrelang eine Kunstpflanze im Wohnzimmer stehen gehabt und sie regelmäßig gegossen.',
    'Ich habe meine Autoschlüssel verloren und sie nach einem Monat im Gefrierschrank wiedergefunden.',
    'Ich habe dem Kellner, der mir den Teller brachte, „Guten Appetit“ gewünscht.',
    'Ich bin zweihundert Meter hinter einem Bus hergelaufen und habe ihn noch gerade so eingeholt.',
    'Ich hatte vergessen, wo ich mein Auto geparkt hatte, und bin eine Stunde lang vergeblich herumgefahren.',
  ];
}
