class ContentDeApp {
  const ContentDeApp._();

  static const Map<String, String> ui = {
    'app.tagline':
        'Das Partyspiel, bei dem\nalle verbunden sind.',
    'common.retry': 'Erneut versuchen',
    'common.cancel': 'Abbrechen',
    'common.continue': 'WEITER',
    'common.back_home': 'ZUR STARTSEITE ZURÜCK',
    'common.loading': 'Einen Moment…',
    'common.you': 'du',
    'onboarding.slide1.title': 'Der Abend nimmt\neine unerwartete Wendung',
    'onboarding.slide1.body':
        'Jeder spielt mit seinem eigenen Handy, aber alle spielen gemeinsam. Joyo bringt euch zusammen – ihr seid dran.',
    'onboarding.slide2.title': 'Ein Code und\nihr seid dabei.',
    'onboarding.slide2.body':
        'Erstelle einen Raum, teile den Code und hol deine Freunde dazu. In wenigen Sekunden könnt ihr loslegen.',
    'onboarding.slide3.title': 'Sechs Spiele.\nEndlose Möglichkeiten.',
    'onboarding.slide3.body':
        'Stimme ab, bluffe, verrate Geheimnisse oder lass die Flasche entscheiden. Wählt euer Spiel und legt los.',
    'onboarding.slide4.title': 'Du entscheidest,\nwie weit du gehen willst',
    'onboarding.slide4.body':
        'Normal zum entspannten Einstieg, Mix für mehr Abwechslung, Hot für alle, die noch einen Schritt weitergehen wollen.',
    'onboarding.language': 'Welche Sprache spielt ihr?',
    'onboarding.start': 'START',
    'onboarding.skip': 'Überspringen',
    'home.create': 'RAUM ERSTELLEN',
    'home.join': 'MIT CODE BEITRETEN',
    'home.games': 'Die Spiele',
    'home.connection_failed': 'Verbindung zu Joyo nicht möglich.',
    'home.language': 'Sprache',
    'join.title_create': 'Raum erstellen',
    'join.title_join': 'Raum beitreten',
    'join.name_question': 'Wie heißt du?',
    'join.name_hint': 'Dein Name',
    'join.color': 'Deine Farbe',
    'join.avatar': 'Wähle deinen Avatar',
    'join.error_avatar': 'Wähle einen Avatar.',
    'join.code': 'Raumcode',
    'join.cta_create': 'RAUM ERSTELLEN',
    'join.cta_join': 'BEITRETEN',
    'join.error_name': 'Gib deinen Namen ein.',
    'join.error_code': 'Der Code muss 6 Zeichen enthalten.',
    'error.room_not_found': 'Wir haben keinen Raum mit diesem Code gefunden.',
    'error.room_full': 'Der Raum ist voll. Maximal 10 Spieler.',
    'error.room_finished': 'Dieses Spiel ist bereits beendet.',
    'error.connection':
        'Verbindung verloren. Prüfe deine Verbindung und versuche es erneut.',
    'lobby.title': 'Lobby',
    'lobby.code_label': 'RAUMCODE',
    'lobby.code_hint': 'Teile ihn mit deinen Freunden · antippen zum Kopieren',
    'lobby.code_copied': 'Code kopiert',
    'lobby.players': 'Spieler',
    'lobby.you': 'du',
    'lobby.host_badge': 'HOST',
    'lobby.pick_game': 'WÄHLE DAS SPIEL',
    'lobby.waiting_host': 'Der Host wählt gerade ein Spiel…',
    'lobby.which_game': 'Was spielen wir?',
    'lobby.remove_player': '{name} entfernen?',
    'lobby.remove_player_body':
        'Nutze diese Funktion, wenn jemand die App geschlossen hat, ohne den Raum zu verlassen. Mit demselben Code kann die Person wieder beitreten.',
    'lobby.remove': 'Entfernen',
    'lobby.exit_host_title': 'Raum schließen?',
    'lobby.exit_host_body':
        'Der Raum wird für alle geschlossen. Die anderen Spieler kehren zur Startseite zurück.',
    'lobby.exit_title': 'Den Raum verlassen?',
    'lobby.exit_body':
        'Die anderen Spieler sehen, dass du den Raum verlassen hast.',
    'lobby.stay': 'BLEIBEN',
    'lobby.close': 'SCHLIESSEN',
    'lobby.leave': 'VERLASSEN',
    'lobby.exit_failed': 'Verlassen nicht möglich: {detail}',
    'lobby.room_closed': 'Der Host hat den Raum geschlossen.',
    'lobby.reconnecting': 'Verbindung wird wiederhergestellt…',
    'lobby.entering': 'Raum wird betreten…',
    'mode.title': 'Modus',
    'mode.normale': 'Normal',
    'mode.mix': 'Mix',
    'mode.hot': 'Hot',
    'mode.normale.desc':
        'Der einfache Einstieg. Perfekt, um das Eis zu brechen.',
    'mode.mix.desc':
        'Mehr Abwechslung, mehr Überraschungen und ein schnelleres Tempo.',
    'mode.hot.desc': 'Direkter und persönlicher. Nur, wenn ihr bereit seid.',
    'settings.rounds': 'Runden pro Spiel',
    'game.round_of': 'Runde {n} von {total}',
    'game.preparing': 'Runde wird vorbereitet…',
    'game.create_failed': 'Runde konnte nicht erstellt werden: {detail}',
    'game.close_failed': 'Runde konnte nicht beendet werden: {detail}',
    'game.vote_failed': 'Antwort wurde nicht gespeichert: {detail}',
    'game.next_round': 'NÄCHSTE RUNDE',
    'game.see_podium': 'PODIUM ANSEHEN',
    'game.waiting_next': 'Der Host startet gleich die nächste Runde…',
    'game.finished': 'Spiel beendet',
    'game.answered': '{n} von {total} haben geantwortet',
    'game.back_to_lobby': 'ZURÜCK ZUR LOBBY',
    'game.lobby_short': 'LOBBY',
    'game.host_only': 'Nur der Host kann das Spiel aus der Lobby neu starten.',
    'game.coming_soon': 'BALD VERFÜGBAR',
    'podium.title': 'Spiel beendet',
    'podium.winner': '{name} gewinnt',
    'podium.no_scores':
        'Bei diesem Spiel gibt es keine Punkte. Hier geht es einfach ums Spielen.',
    'podium.points': '{n} Punkte',
    'podium.points_one': '{n} Punkt',
    'preferisci.name': 'Was würdest du lieber tun?',
    'preferisci.tagline':
        'Zwei schwierige Entscheidungen. Wofür entscheidest du dich?',
    'preferisci.prompt': 'Was würdest du lieber…',
    'preferisci.or': 'oder',
    'preferisci.split': 'So hat die Gruppe abgestimmt',
    'preferisci.no_votes': 'Niemand hat geantwortet',
    'non_ho_mai.name': 'Noch nie',
    'non_ho_mai.tagline':
        'Keine Geheimnisse. Mal sehen, wer was schon gemacht hat.',
    'non_ho_mai.prompt': 'Noch nie…',
    'non_ho_mai.done': 'HABE ICH GEMACHT',
    'non_ho_mai.never': 'NOCH NIE',
    'non_ho_mai.anonymous':
        'Deine Antwort bleibt anonym. Es wird nur die Anzahl angezeigt.',
    'non_ho_mai.nobody': 'Niemand hat das gemacht',
    'non_ho_mai.count': '{n} von {total}',
    'non_ho_mai.guess_who': 'Jetzt müsst ihr herausfinden, wer es war',
    'chi.name': 'Wer würde das tun?',
    'chi.tagline': 'Eine Frage. Ein Name. Ihr entscheidet.',
    'chi.decided': 'Die Gruppe hat entschieden',
    'chi.tie': 'Gleichstand',
    'chi.no_votes': 'Keine Stimmen',
    'obbligo.name': 'Wahrheit oder Pflicht',
    'obbligo.tagline': 'Die Flasche entscheidet. Du bist dran.',
    'obbligo.spinning': 'Die Flasche dreht sich…',
    'obbligo.your_turn': 'Du bist dran',
    'obbligo.turn_of': '{name} ist dran',
    'obbligo.choosing': 'Wählt…',
    'obbligo.dare': 'PFLICHT',
    'obbligo.truth': 'WAHRHEIT',
    'obbligo.no_choice': '{name} hat sich nicht rechtzeitig entschieden',
    'obbligo.when_done':
        'Wenn die Person fertig ist, kann der Host die nächste Runde starten',
    'bluff.name': 'Bluff Story',
    'bluff.tagline': 'Eine Wahrheit. Zwei Lügen. Kannst du bluffen?',
    'bluff.writing': '{name} schreibt\neine Wahrheit über sich selbst',
    'bluff.your_turn_body':
        'Schreib eine Wahrheit über dich. Wir fügen zwei Lügen hinzu. Die anderen müssen herausfinden, welche Aussage wirklich stimmt.',
    'bluff.hint': 'Schreib deine Wahrheit…',
    'bluff.send': 'TEILE DEINE WAHRHEIT',
    'bluff.too_short': 'Schreib etwas ausführlicher.',
    'bluff.which_true': 'Welche Aussage über {name} ist wahr?',
    'bluff.in_play': 'Deine Geschichte ist im Spiel',
    'bluff.dont_tell': 'Verrate nicht, welche Aussage die Wahrheit ist.',
    'bluff.your_truth': 'deine Wahrheit',
    'bluff.true_label': 'wahr',
    'bluff.truth_of': 'Die Wahrheit über {name}',
    'bluff.nobody_guessed':
        'Niemand hat es erraten. {name} hat euch alle getäuscht.',
    'bluff.guessed': '{n} haben richtig geraten',
    'bluff.guessed_one': '{n} hat es erraten',
    'bluff.scoring':
        '+2 für jede richtige Antwort · +1 für {name} für jeden erfolgreichen Bluff',
    'bluff.ai_working': 'Ich erfinde zwei Lügen…',
    'bluff.ai_working_sub': 'passend zu {name}s Geschichte',
    'impostore.name': 'Impostor',
    'impostore.tagline':
        'Einer von euch kennt die Wahrheit nicht. Findet den Impostor.',
    'impostore.only_you': 'Nur du kannst das sehen',
    'impostore.you_are': 'Du bist der Impostor',
    'impostore.you_are_body':
        'Du kennst das geheime Wort nicht. Hör gut zu, improvisiere und bleib unauffällig. Wenn du enttarnt wirst, aber das Wort errätst, bekommst du Punkte.',
    'impostore.the_word': 'Das geheime Wort ist',
    'impostore.one_doesnt': 'Einer von euch kennt das Wort nicht.',
    'impostore.round_of_words': 'Wörter-Runde',
    'impostore.round_of_words_body':
        'Nacheinander sagt jeder ein einziges Wort, das mit dem Geheimnis zu tun hat.\nIst es zu präzise, versteht der Impostor es; ist es zu vage, seht ihr selbst wie der Impostor aus.',
    'impostore.your_word': 'Dein Wort: {word}',
    'impostore.to_vote': 'ABSTIMMEN',
    'impostore.who': 'Wer ist der Impostor?',
    'impostore.guess_hint': 'Das geheime Wort war…',
    'impostore.guess_body':
        'Du bist der Impostor: Versuche, das Wort zu erraten. Wenn du entlarvt wirst, aber das Wort richtig errätst, bekommst du Punkte zurück.',
    'impostore.confirm': 'BESTÄTIGEN',
    'impostore.vote_registered': 'Stimme gespeichert',
    'impostore.caught': 'Der Impostor wurde entlarvt',
    'impostore.escaped': 'Der Impostor ist ungestraft davongekommen',
    'impostore.word_was': 'Das geheime Wort war',
    'impostore.guessed_it': 'Richtig geraten: „{guess}“ · +3 Punkte',
    'impostore.said': 'Gesagt wurde: „{guess}“',
    'impostore.points_caught':
        '+2 für diejenigen, die für den Impostor gestimmt haben',
    'impostore.points_escaped': '+5 für den Impostor',
    'impostore.votes': '{n} Stimmen',
    'impostore.votes_one': '{n} Stimme',
    'premium.title': 'Personalisierte Inhalte',
    'premium.body':
        'In „Wer würde das tun?“ und „Bluff Story“ werden die Sätze für eure Gruppe geschrieben, anstatt aus einer Liste gezogen zu werden.',
    'premium.active': 'KI ist in diesem Raum aktiv',
    'premium.active_body': 'Inhalte, die für eure Gruppe erstellt wurden',
    'premium.unlock': 'ENTSPERREN',
    'premium.watch_ad': 'WERBUNG ANSEHEN',
    'premium.host_only': 'Nur der Host kann sie freischalten.',
    'premium.credits': '{n} Credits',
    'premium.unlocked': 'KI für diesen Raum freigeschaltet',
    'premium.ad_reward': 'Du hast KI-Inhalte freigeschaltet',
    'premium.ad_incomplete': 'Werbung nicht vollständig angesehen.',
    'premium.no_store':
        'Käufe sind hier nicht verfügbar. Nutze Google Play oder den App Store.',
    'premium.ads_mobile_only': 'Werbung ist nur auf dem Handy verfügbar.',
  };
}
