/// Generato da tool/generate_content.dart (traduzione DeepL dai
/// pool italiani). Stesse posizioni e stesso tono degli originali IT.
class ContentDeApp {
  const ContentDeApp._();

  static const Map<String, String> ui = {
    'app.tagline': 'Das Partyspiel, bei dem\njeder ein eigenes Handy hat.',
    'common.retry': 'Versuche es noch einmal',
    'common.cancel': 'Abbrechen',
    'common.continue': 'WEITER',
    'common.back_home': 'ZUR STARTSEITE ZURÜCK',
    'common.loading': 'Moment mal…',
    'common.you': 'du',
    'onboarding.slide1.title': 'Der Abend nimmt\neine unerwartete Wendung',
    'onboarding.slide1.body':
        'Jeder mit seinem Handy, alle im selben Raum. Joyo verbindet die Bildschirme, ihr sorgt für Chaos.',
    'onboarding.slide2.title':
        'Mit dem Code in der Hand\ngeht es nun richtig los',
    'onboarding.slide2.body':
        'Öffne den Raum, rufe den Code und sieh zu, wie deine Freunde innerhalb weniger Sekunden hineinstürmen.',
    'onboarding.slide3.title': 'Sechs Spiele, damit\nnie Langeweile aufkommt',
    'onboarding.slide3.body':
        'Bewerte deine Freunde, denk dir riesige Lügen aus oder fordere das Schicksal mit der Flasche heraus. Vollgas.',
    'onboarding.slide4.title': 'Entscheide selbst,\nwie weit du gehen willst',
    'onboarding.slide4.body':
        '„Normal“-Modus zum Aufwärmen, „Mix“ für einen schwungvollen Abend, „Hot“ für den Moment, in dem die Masken fallen.',
    'onboarding.language': 'In welcher Sprache spielt ihr?',
    'onboarding.start': 'START',
    'onboarding.skip': 'Überspringen',
    'home.create': 'RAUM ERSTELLEN',
    'home.join': 'MIT EINEM CODE ANMELDEN',
    'home.games': 'Die Spiele',
    'home.connection_failed': 'Die Verbindung zu Joyo ist fehlgeschlagen.',
    'home.language': 'Sprache',
    'join.title_create': 'Raum erstellen',
    'join.title_join': 'Mach mit',
    'join.name_question': 'Wie heißt du?',
    'join.name_hint': 'Dein Name',
    'join.color': 'Deine Farbe',
    'join.code': 'Raumcode',
    'join.cta_create': 'RAUM ERSTELLEN',
    'join.cta_join': 'BEITRETEN',
    'join.error_name': 'Schreib deinen Namen auf.',
    'join.error_code': 'Der Code besteht aus 6 Zeichen.',
    'error.room_not_found': 'Es gibt kein Zimmer mit dieser Nummer.',
    'error.room_full': 'Der Raum ist voll: maximal 10 Spieler.',
    'error.room_finished': 'Dieses Spiel ist bereits vorbei.',
    'error.connection':
        'Die Verbindung wurde unterbrochen. Öffne die App erneut und versuche es noch einmal.',
    'lobby.title': 'Lobby',
    'lobby.code_label': 'RAUMCODE',
    'lobby.code_hint': 'Sag es laut · Zum Kopieren antippen',
    'lobby.code_copied': 'Code kopiert',
    'lobby.players': 'Spieler',
    'lobby.you': 'du',
    'lobby.host_badge': 'HOST',
    'lobby.pick_game': 'WÄHLE DAS SPIEL',
    'lobby.waiting_host': 'Der Gastgeber wählt gerade das Spiel aus…',
    'lobby.which_game': 'Was spielen wir?',
    'lobby.remove_player': '{name} entfernen?',
    'lobby.remove_player_body':
        'Verwende diese Funktion, wenn jemand die App geschlossen hat, ohne sich abzumelden. Mit dem Code kann er sich jederzeit wieder anmelden.',
    'lobby.remove': 'Entfernen',
    'lobby.exit_host_title': 'Den Raum schließen?',
    'lobby.exit_host_body':
        'Der Raum wird für alle geschlossen: Die anderen Spieler kehren zur Startseite zurück.',
    'lobby.exit_title': 'Den Raum verlassen?',
    'lobby.exit_body':
        'Die anderen Spieler werden sehen, wie du den Raum verlässt.',
    'lobby.stay': 'Bleib',
    'lobby.close': 'Schließen',
    'lobby.leave': 'Beenden',
    'lobby.exit_failed': 'Verlassen fehlgeschlagen: {detail}',
    'lobby.room_closed': 'Der Raum wurde vom Gastgeber geschlossen.',
    'lobby.reconnecting': 'Wiederverbindung…',
    'lobby.entering': 'Ich betrete den Raum…',
    'mode.title': 'Modus',
    'mode.normale': 'Normal',
    'mode.mix': 'Mix',
    'mode.hot': 'Heiß',
    'mode.normale.desc':
        'Perfekt, um das Eis ohne allzu große Probleme zu brechen.',
    'mode.mix.desc':
        'Die Spiele wechseln und das Tempo nimmt zu. Haltet euch fest.',
    'mode.hot.desc':
        'Ohne Bremsen. Nur spielen, wenn ihr zu allem bereit seid.',
    'settings.rounds': 'Runden pro Spiel',
    'game.round_of': 'Runde {n} von {total}',
    'game.preparing': 'Ich bereite die Runde vor…',
    'game.create_failed': 'Ich kann die Runde nicht erstellen: {detail}',
    'game.close_failed': 'Ich kann die Runde nicht abschließen: {detail}',
    'game.vote_failed': 'Nicht gespeicherte Antwort: {detail}',
    'game.next_round': 'NÄCHSTE RUNDE',
    'game.see_podium': 'PODIUM ANSEHEN',
    'game.waiting_next':
        'Der Moderator wird gleich die nächste Runde einläuten…',
    'game.finished': 'Das Spiel ist vorbei',
    'game.answered': '{n} von {total} haben geantwortet',
    'game.back_to_lobby': 'ZURÜCK ZUR LOBBY',
    'game.lobby_short': 'LOBBY',
    'game.host_only': 'Der Host kann das Spiel von der Lobby aus neu starten.',
    'game.coming_soon': 'Demnächst',
    'podium.title': 'Spielende',
    'podium.winner': '{name} gewinnt',
    'podium.no_scores':
        'Bei diesem Spiel gibt es keine Punkte: keine Rangliste, nur das Spiel.',
    'podium.points': '{n} Punkte',
    'podium.points_one': '{n} Punkt',
    'preferisci.name': 'Was bevorzugst du?',
    'preferisci.tagline':
        'Grausame Entscheidungen: Wer sieht das genauso wie du?',
    'preferisci.prompt': 'Was bevorzugst du…',
    'preferisci.or': 'oder',
    'preferisci.split': 'Die Gruppe hat sich wie folgt aufgeteilt',
    'preferisci.no_votes': 'Niemand hat geantwortet.',
    'non_ho_mai.name': 'Ich habe noch nie',
    'non_ho_mai.tagline': 'Der Beichtstuhl ist geöffnet. Beichte und überlebe.',
    'non_ho_mai.prompt': 'Ich habe noch nie…',
    'non_ho_mai.done': 'ICH HABE ES GEMACHT',
    'non_ho_mai.never': 'NIEMALS',
    'non_ho_mai.anonymous':
        'Niemand wird sehen, was du geantwortet hast: Man sieht nur die Punktzahl.',
    'non_ho_mai.nobody': 'Das hat niemand getan',
    'non_ho_mai.count': '{n} von {total}',
    'non_ho_mai.guess_who': 'Jetzt seid ihr dran, herauszufinden, wer',
    'chi.name': 'Wer könnte das tun?',
    'chi.tagline':
        'Das Spiel, bei dem man (im wahrsten Sinne des Wortes) mit dem Finger zeigt.',
    'chi.decided': 'Die Gruppe hat beschlossen',
    'chi.tie': 'Gleichstand',
    'chi.no_votes': 'Keine Stimmen',
    'obbligo.name': 'Wahrheit oder Pflicht',
    'obbligo.tagline': 'Die Flasche entscheidet, du schwitzt. Keine Ausreden.',
    'obbligo.spinning': 'Die Flasche dreht sich…',
    'obbligo.your_turn': 'Jetzt bist du dran',
    'obbligo.turn_of': 'Jetzt ist {name} an der Reihe',
    'obbligo.choosing': 'Wählt gerade aus…',
    'obbligo.dare': 'PFLICHT',
    'obbligo.truth': 'WAHRHEIT',
    'obbligo.no_choice': '{name} hat sich nicht rechtzeitig entschieden',
    'obbligo.when_done':
        'Wenn er fertig ist, gibt der Gastgeber die nächste Runde aus',
    'bluff.name': 'Bluff-Geschichte',
    'bluff.tagline':
        'Lügen ist eine Kunst. Schaffst du es, nicht erwischt zu werden?',
    'bluff.writing': '{name} schreibt\neine wahre Begebenheit über sich selbst',
    'bluff.your_turn_body':
        'Schreibe eine wahre Tatsache über dich auf. Das Spiel mischt zwei Lügen dazwischen: Die anderen müssen erraten, welche davon deine ist.',
    'bluff.hint': 'Schreib hier…',
    'bluff.send': 'SENDE DEINE WAHRHEIT',
    'bluff.too_short': 'Schreib doch mal etwas Längeres.',
    'bluff.which_true': 'Was ist die Wahrheit über {name}?',
    'bluff.in_play': 'Deine Geschichte steht auf dem Spiel',
    'bluff.dont_tell': 'Lass dir nicht entgehen, welche die richtige ist.',
    'bluff.your_truth': 'deine Wahrheit',
    'bluff.true_label': 'wahr',
    'bluff.truth_of': 'Die Wahrheit über {name}',
    'bluff.nobody_guessed':
        'Niemand hat es erraten: {name} hat euch alle reingelegt',
    'bluff.guessed': '{n} haben richtig geraten',
    'bluff.guessed_one': '{n} hat es erraten',
    'bluff.scoring':
        '+2 für denjenigen, der es erraten hat · +1 für {name} für jeden gelungenen Bluff',
    'bluff.ai_working': 'Ich denke mir gerade zwei Lügen aus…',
    'bluff.ai_working_sub': 'maßgeschneidert für die Geschichte von {name}',
    'impostore.name': 'Betrüger',
    'impostore.tagline':
        'Ein Eindringling unter uns. Finde ihn, bevor es zu spät ist.',
    'impostore.only_you': 'Nur du siehst das',
    'impostore.you_are': 'Du bist der Betrüger',
    'impostore.you_are_body':
        'Du kennst das Wort nicht. Hör zu, improvisiere und lass dich nicht erwischen: Wenn du das Wort am Ende errätst, bekommst du Punkte.',
    'impostore.the_word': 'Das Wort lautet',
    'impostore.one_doesnt': 'Einer von euch kennt sie nicht.',
    'impostore.round_of_words': 'Wortrunde',
    'impostore.round_of_words_body':
        'Nacheinander sagt jeder ein einziges Wort, das mit dem Geheimnis zu tun hat.\nIst es zu präzise, versteht der Betrüger es; ist es zu vage, seht ihr selbst wie der Betrüger aus.',
    'impostore.your_word': 'Dein Wort: {word}',
    'impostore.to_vote': 'ZUR ABSTIMMUNG GEHEN',
    'impostore.who': 'Wer ist der Betrüger?',
    'impostore.guess_hint': 'Das Geheimwort lautete…',
    'impostore.guess_body':
        'Du bist der Betrüger: Versuche, das Wort zu erraten. Wenn du entlarvt wirst, aber das Wort richtig errätst, bekommst du Punkte zurück.',
    'impostore.confirm': 'BESTÄTIGUNG',
    'impostore.vote_registered': 'Abgegebene Stimme',
    'impostore.caught': 'Der Betrüger wurde entlarvt',
    'impostore.escaped': 'Der Betrüger ist ungestraft davongekommen',
    'impostore.word_was': 'Das Wort lautete',
    'impostore.guessed_it': 'Sie haben richtig geraten: „{guess}“ · +3 Punkte',
    'impostore.said': 'Er hatte gesagt: „{guess}“',
    'impostore.points_caught':
        '+2 für diejenigen, die für den Betrüger gestimmt haben',
    'impostore.points_escaped': '+5 für den Betrüger',
    'impostore.votes': '{n} Stimmen',
    'impostore.votes_one': '{n} Stimme',
    'premium.title': 'Maßgeschneiderte Inhalte',
    'premium.body':
        'In „Wer könnte das tun?“ und „Bluff Story“ werden die Sätze für eure Gruppe geschrieben, anstatt aus einer Liste gezogen zu werden.',
    'premium.active': 'KI ist in diesem Raum aktiv',
    'premium.active_body': 'Fragen und Lügen, die in eurer Gruppe aufkommen',
    'premium.unlock': 'ENTSPERREN',
    'premium.watch_ad': 'ANZEIGE',
    'premium.host_only': 'Der Gastgeber kann sie freischalten.',
    'premium.credits': '{n} Kreditpunkte',
    'premium.unlocked': 'AI für diesen Raum freigeschaltet',
    'premium.ad_reward': 'Du hast einen KI-Inhalt freigeschaltet',
    'premium.ad_incomplete': 'Anzeige nicht abgeschlossen.',
    'premium.no_store':
        'Käufe sind hier nicht möglich: Sie benötigen Google Play oder den App Store.',
    'premium.ads_mobile_only': 'Die Anzeigen funktionieren nur auf dem Handy.',
  };
}
