import '../content_tone.dart';

/// Generato da tool/generate_content.dart (traduzione DeepL dai
/// pool italiani). Stesse posizioni e stesso tono degli originali IT.
class ContentEsObbligoOVerita {
  const ContentEsObbligoOVerita._();

  static const Map<String, List<String>> obblighi = {
    ContentTone.normal: [
      'Imita la forma de caminar de la persona que tienes a tu derecha.',
      'Canta el estribillo de la última canción que has escuchado.',
      'Habla rimando hasta tu próximo turno.',
      'Imita los sonidos de tres animales y haz que adivinen cuáles son.',
      'Baila diez segundos sin música.',
      'Cuenta un chiste: si nadie se ríe, repítelo más alto.',
      'Imita a tu personaje favorito de una serie.',
      'Adopta una postura de estatua y quédate quieto durante treinta segundos.',
      'Habla como un comentarista deportivo durante un minuto.',
      'Muestra la última foto que has hecho.',
      'Muestra tu pantalla de inicio sin abrir nada.',
      'Muéstranos el emoji que más usas y explícanos por qué precisamente ese.',
      'Muéstranos cuántas alarmas tienes programadas.',
      'Hazle al asistente de voz del móvil una pregunta absurda que haya elegido el grupo.',
      'Envía un mensaje de voz cantado a un contacto al azar.',
      'Llama a un amigo y deséale lo mejor, aunque no sea su cumpleaños.',
      'Haz un cumplido sincero a cada una de las personas presentes.',
      'Describe a la persona que tienes a tu izquierda utilizando solo tres palabras.',
      'Inventa un rap de veinte segundos sobre la persona que tienes a tu izquierda.',
      'Imita al profesor que menos te guste.',
      'Imagina que eres un vendedor y véndenos esta mesa.',
      'Presenta el tiempo de mañana como en la televisión.',
      'Habla con acento extranjero hasta la próxima ronda.',
      'Cuenta el argumento de una película sin decir el título; los demás tienen que adivinarlo.',
      'Da un discurso de agradecimiento como si hubieras ganado un premio.',
      'Crea un anuncio para el artículo que tengas más a mano.',
      'Enséñanos cómo bailas cuando estás solo en casa.',
      'Canta en lugar de hablar durante los próximos dos minutos.',
      'Camina con un libro en equilibrio sobre la cabeza.',
      'Ponte la ropa al revés durante dos rondas.',
      'Deja que la persona que está a tu derecha te haga un nuevo peinado.',
      'Haz un dibujo del grupo en treinta segundos.',
      'Escribe tu nombre con la mano contraria y enséñalo.',
      'Dibuja el retrato de un presente con los ojos cerrados y luego regálaselo.',
      'Recita el alfabeto al revés lo más rápido que puedas.',
      'Cuenta hasta veinte saltándote los múltiplos de tres.',
      'Di tres palabras al revés, empezando por la última.',
      'Cuenta una historia inventada de treinta segundos que empiece con «Anoche…».',
      'Cuenta cómo ha sido tu día como si fuera una película de terror.',
      'Describe tu trabajo o tu día a día tal y como lo haría un niño.',
      'Imagina que eres un robot durante un minuto.',
      'Responde solo con preguntas hasta la próxima ronda.',
      'No puedes decir ni «sí» ni «no» hasta que te toque el turno.',
      'Habla de ti en tercera persona hasta que te toque el turno.',
      'Ríete tan fuerte como puedas sin motivo alguno.',
      'Mantén una expresión muy seria durante treinta segundos mientras los demás intentan hacerte reír.',
      'Haz veinte segundos de plancha mientras los demás cuentan.',
      'Haz cinco flexiones, que contará el grupo.',
      'Corre sin moverte del sitio hasta que termine el turno.',
      'Haz diez sentadillas diciendo el nombre de un objeto que tengas a mano cada vez que te agaches.',
      'Come algo que haya elegido la persona que tienes a tu izquierda.',
      'Prueba dos cosas a la vez que no combinan bien.',
      'Escribe una reseña, como si fueras un crítico de restaurantes con estrellas, sobre lo último que has comido hoy.',
      'Prepara una bebida sin alcohol y dásela a probar a alguien.',
      'Haz un brindis improvisado en honor al grupo.',
      'Cuéntanos tu mejor recuerdo con una persona que esté aquí presente.',
      'Cuéntanos cómo conociste a la persona que tienes delante.',
      'Di qué es lo que envidias (en el buen sentido) de cada una de las personas presentes.',
      'Haz una predicción sobre el futuro de una persona que está aquí presente.',
      'Ponle un apodo a cada uno y explícalo.',
      'Responde solo con el nuevo apodo elegido por el grupo hasta el final del partido.',
      'Elige a quién del grupo te llevarías a una isla desierta y explica por qué.',
      'Cuéntanos cuál es la cosa más cara que has comprado sin necesidad.',
      'Confiesa un hábito extraño que tengas.',
      'Cuéntanos algún miedo ridículo que tengas.',
      'Finge que te da miedo algún objeto de la habitación.',
      'Cuéntanos cuál es uno de tus talentos inútiles y demuéstralo.',
      'Muestra tu mejor «truco de magia» improvisado.',
      'Haz un origami con lo que tengas a mano en un minuto.',
      'Construye una torre con tres objetos de la habitación.',
      'Encuentra tres objetos amarillos en casa en treinta segundos.',
      'Intercambia algo que lleves puesto con la persona que tienes a tu derecha.',
      'Hazte un selfie con la cara más fea que puedas poner.',
      'Hazte una foto imitando la pose de la persona que está a tu izquierda.',
      'Graba un vídeo de diez segundos como si fueras un influencer.',
      'Graba un mensaje motivador para el grupo.',
      'Lee el horóscopo de hoy con voz dramática.',
      'Inventa un horóscopo para la persona que tienes a tu derecha.',
      'Describe cómo será tu vida dentro de diez años, sin darle muchas vueltas.',
      'Declara tu amor eterno a un objeto de la habitación: el sofá cuenta.',
      'Interpreta una escena de despedida conmovedora con una almohada.',
      'Di qué canción te sabes de memoria y canta un fragmento.',
      'Canta al karaoke durante diez segundos sin música.',
      'Silba una canción y haz que la adivine.',
      'Haz un beatbox de cinco segundos.',
      'Imita el sonido de tres instrumentos diferentes.',
      'Finge que tocas la guitarra como si estuvieras en un concierto.',
      'Baila como si estuvieras solo en una discoteca.',
      'Enséñales al grupo un paso de baile.',
      'Haz una foto de grupo y dale las instrucciones.',
      'Elige la banda sonora de la velada y explica por qué.',
      'Cuéntanos lo más bonito que te ha pasado esta semana.',
      'Di algo que te gustaría aprender y por qué aún no has empezado.',
      'Haz una lista de tres cosas por las que te sientes agradecido en este momento.',
      'Envía un mensaje simpático a alguien a quien no hayas escrito desde hace tiempo.',
      'Llama a tu madre o a algún familiar y diles que les quieres.',
      'Envía «¡Buenos días!» con tres emojis al azar en el chat familiar.',
      'Deja que el grupo elija tu próxima tarea para la siguiente ronda.',
      'Desfila como un modelo de un extremo a otro de la habitación, con giro incluido.',
      'Compórtate como un T-Rex con los brazos cortos hasta tu próximo turno.',
      'Utiliza un mando a distancia o un cepillo como micrófono cada vez que hables, durante una vuelta.',
      'Haz de camarero: toma con total seriedad los pedidos imaginarios de todo el mundo.',
      'Imita una película sin hablar hasta que el grupo la adivine.',
      'Imita a un personaje famoso elegido por el grupo hasta que alguien adivine quién es.',
      'Haz un cumplido a cada uno de los presentes saltando a la pata coja.',
      'Intenta lamerte el codo con toda tu fuerza durante diez segundos.',
      'Cuenta un cuento para dormir en treinta segundos imitando todas las voces.',
      'Habla durante un minuto sobre un tema elegido por el grupo como si fueras el mayor experto en la materia.',
      'Repite tres veces seguidas un trabalenguas elegido por el grupo sin cometer ningún error.',
      'Describe lo que hace la persona que tienes delante como si fuera un documental sobre la naturaleza.',
      'Haz cinco expresiones según te indiquen: feliz, enfadado, sorprendido, enamorado, receloso.',
      'Baila un lento romántico con una escoba o un cojín.',
      'Presenta un telediario con tres noticias absurdas sobre los presentes.',
      'Haz de eco: repite la última palabra de quien esté hablando hasta que te toque hablar.',
      'Habla en voz baja hasta que te toque el turno, pase lo que pase.',
      'Mantén una sonrisa enorme en la cara durante tres minutos, pase lo que pase.',
      'Invéntate un himno para el grupo con la melodía de una canción famosa y cántalo.',
      'Deja que el grupo te haga posar como una estatua y quédate así para una foto.',
      'Monta una escena dramática de telenovela porque se ha acabado una galleta.',
      'Intenta hacer reír a la persona más seria del grupo en treinta segundos, sin tocarla.',
      'Apila sobre ti mismo tantos cojines como puedas y mantén el equilibrio durante diez segundos.',
      'Invéntate un idioma y «traduce» lo que dice la persona que tienes a tu derecha.',
      'Finge que estás atrapado en una caja invisible hasta que alguien te «libere».',
      'Cuenta cómo se formó este grupo, al estilo de un documental histórico.',
      'Tutea a todo el mundo hasta que te toque el turno, con extrema formalidad.',
      'Haz un tutorial de cocina imaginario con los objetos que tienes delante.',
      'Muévete a cámara lenta hasta el final del turno, incluidas las repeticiones.',
      'Saluda en cinco idiomas diferentes, inventándote los que no conoces.',
      'Imita a un animal hasta que alguien adivine cuál es.',
      'Responde cantando a todo lo que te digan hasta que te toque a ti.',
      'Da diez saltitos sin moverte del sitio mientras gritas tu nombre.',
      'Inventa un lema para el grupo y repítelo en voz alta.',
      'Haz de comentarista de lo que ocurre en la habitación durante treinta segundos.',
      'Inventa un anuncio para el objeto que tienes a tu derecha.',
      'Habla solo en voz baja hasta que te toque el turno.',
      'Te quedas inmóvil como una estatua mientras los demás intentan hacerte reír.',
      'Haz playback de una canción que elija el grupo durante quince segundos.',
      'Imita a un personaje famoso elegido por el grupo.',
      'Cuenta el argumento de una película famosa en exactamente diez palabras.',
      'Recita los días de la semana al revés lo más rápido que puedas.',
      'Imagina que ganas un Óscar y da las gracias a los presentes uno por uno.',
      'Camina como un robot hasta la puerta y vuelve.',
      'Invéntate un apodo divertido para cada uno de los presentes.',
      'Canta «Feliz cumpleaños» como si fuera una canción de rock.',
      'Haz cinco caras diferentes en cinco segundos.',
      'Mantén un cojín en equilibrio sobre la cabeza durante una vuelta completa.',
      'Describe tu día utilizando solo sonidos.',
      'Haz una previsión meteorológica inventada con la mayor seriedad posible.',
      'Pide una pizza imaginaria de una forma épica y dramática.',
      'Aplaude cada frase que digan los demás hasta que te toque a ti.',
    ],
    ContentTone.mix: [
      'Da un masaje sensual en la parte interior del muslo de una persona que esté de acuerdo durante treinta segundos.',
      'Susurra al oído de la persona que tienes a tu derecha tu fantasía más atrevida.',
      'Besa el cuello de una persona que esté de acuerdo y sopla suavemente sobre su piel.',
      'Pide a una persona que dé su consentimiento que elija una prenda para que te la quite.',
      'Finge un orgasmo durante quince segundos, con sonidos y gestos, delante de todo el mundo.',
      'Quítate tres prendas de ropa (sin contar los complementos) y quédate así durante el resto del partido.',
      'Lame el lóbulo de la oreja de la persona que tienes a tu izquierda (si está de acuerdo).',
      'Quítate un accesorio o una prenda de la forma más seductora y lenta posible.',
      'Déjate vendar los ojos y adivina quiénes son tres personas del grupo besándoles solo la mano o el brazo.',
      'Imita tu postura favorita con un cojín de forma extremadamente realista.',
      'Apoya la cabeza en el regazo de alguien que esté de acuerdo y quédate ahí durante tres asaltos.',
      'Envía una foto desnuda (o una foto muy provocativa) a quien quieras y muestra la notificación de envío al grupo.',
      'Haz un lap dance de treinta segundos a una persona que dé su consentimiento y que elija el grupo.',
      'Baila un lento sensual, cuerpo a cuerpo, con una persona que esté de acuerdo, durante un minuto.',
      'Recorre con la lengua el contorno del cuello de la persona que tienes a tu izquierda (si está de acuerdo).',
      'Coge la mano de la persona más atractiva de la sala y deslízala por debajo de su camiseta (si ella está de acuerdo).',
      'Mira a los ojos a la persona que te resulte más atractiva durante treinta segundos mientras te muerdes el labio.',
      'Muéstrale al grupo la cara que pones en el momento del orgasmo: mantén esa expresión durante cinco segundos.',
      'Besa lentamente el pecho o el hombro de una persona que dé su consentimiento y que tú elijas.',
      'Imita cómo reaccionas cuando te practican sexo oral, con sonido.',
      'Recita en voz alta tu repertorio de sexting, con un tono extremadamente serio.',
      'Cuéntale al grupo cuál sería el mensaje más atrevido que le enviarías ahora mismo a la persona que te gusta.',
      'Describe en voz alta cómo te llevarías a la cama a la persona que tienes a tu izquierda, paso a paso.',
      'Enséñale al grupo tu truco favorito para excitar a alguien en menos de un minuto.',
      'Explica paso a paso cómo sería tu noche ideal: desde los preliminares hasta el desayuno.',
      'Haz un anuncio de treinta segundos sobre ti mismo como amante, destacando tus mejores cualidades.',
      'Cuéntanos cómo fue tu mejor noche, incluyendo detalles sobre las posturas y las sensaciones.',
      'Describe tu beso perfecto y dáselo ya mismo a alguien que esté de acuerdo (si le apetece).',
      'Di en voz alta la frase más obscena que te hayan susurrado nunca en la cama.',
      'Susurra «te quiero ahora» con la voz más sensual que tengas al oído de tres personas diferentes.',
      'Envía un mensaje picante a la última persona con la que has estado y muestra la respuesta.',
      'Imita cómo coqueteas cuando estás borracho y lo único que quieres es ligar.',
      'Muestra a cámara lenta cómo utilizas la lengua durante un beso: el grupo valora tu técnica.',
      'Envía «Estoy pensando en nosotros dos en la cama» a un contacto que elijas del grupo.',
      'Lee en voz alta el chat más picante que tengas en el móvil, sin censurar nada.',
      'Muestra la foto más atrevida que hayas hecho o recibido en los últimos meses.',
      'Muéstrale al grupo tu historial de navegación en modo incógnito de los últimos dos días.',
      'Escribe «Quiero hacerlo contigo» a la persona que te gusta y enséñale la captura de pantalla.',
      'Envía un mensaje de voz seductor de diez segundos a una expareja elegida por el grupo.',
      'Cuéntanos hasta dónde te has atrevido a llegar en el lugar más público en el que hayas estado nunca.',
      'Describe las tres cosas que más te excitan en la cama, sin andarte con rodeos.',
      'Cuéntanos cuál ha sido tu despertar más embarazoso después de una noche de sexo salvaje.',
      'Confiesa cuál es el fetiche que aún no te has atrevido a probar.',
      'Di el nombre de la persona de las que están aquí con la que tendrías más probabilidades de acabar en la cama esta noche.',
      'Haz una clasificación de los presentes basándote únicamente en su potencial en la cama.',
      'Asigna a cada uno de los presentes una «puntuación de atracción» del 1 al 10, mirándoles a los ojos.',
      'Di qué pareja de esta habitación haría chispas en la cama y por qué.',
      'Elige a quién del grupo te gustaría ver desnudo ahora mismo.',
      'Hazle a alguien del grupo el cumplido más atrevido que se te ocurra sobre su cuerpo.',
      'Propón un «juego de rol» rápido a la persona que tienes a tu derecha y di la primera frase.',
      'Atraviesa la sala como si estuvieras en un club de striptease, detente delante de alguien y hazle una señal con la mano.',
      'Deja que el grupo escriba un mensaje atrevido desde tu teléfono y lo envíe a quien quiera.',
      'Quítate dos prendas o complementos de tu elección, lo más despacio posible, mientras el grupo canta una canción sensual.',
      'Dale una palmada fuerte, con su consentimiento, a la persona que elija el grupo.',
      'Reproduce durante diez segundos los sonidos que haces en la cama en el momento de mayor placer.',
      'Besa lentamente el cuello de una persona que esté de acuerdo, empezando por la oreja y bajando poco a poco.',
      'Mima, sin quitarte la ropa, imita tu postura favorita durante diez segundos, con total dedicación.',
      'Di en voz alta el nombre de la persona que hay en esta habitación a la que besarías ahora mismo.',
      'Dale un masaje de un minuto en la espalda a alguien que esté de acuerdo, metiendo las manos por debajo de la ropa (si está de acuerdo).',
      'Susurra al oído de la persona que tienes a tu derecha lo que le harías si estuvierais solos en esta habitación.',
      'Intercambia tres miradas intensas con la persona que te parezca más sexy sin reírte en ningún momento.',
      'Describe con todo detalle la ropa interior que llevas puesta esta noche.',
      'Baila medio minuto de reggaeton contoneándote (con consentimiento) contra alguien del grupo.',
      'Pide que te pongan un cubito de hielo en los pantalones y aguanta un minuto sin gritar.',
      'Susurra el nombre de tu juguete sexual favorito al oído de alguien, como si fuera una plegaria.',
      'Describe cómo te tocas cuando estás solo y quieres acabar rápido.',
      'Explica la diferencia entre un beso normal y un beso «de cama», con ejemplos teóricos.',
      'Imita «le estoy escribiendo a la chica que me gusta para llevármela a casa», con todas las fases del pánico y del éxito.',
      'Muestra tu mejor pose de «quiero follar» y explica cuál es tu estrategia.',
      'Cuéntanos cuál es el cumplido más subido de tono que te han hecho nunca y quién te lo dijo.',
      'Repite «quiero más» con cinco intenciones diferentes: el grupo tiene que adivinar cuál es la correcta.',
      'Haz el gesto más erótico posible utilizando solo un cubito de hielo.',
      'Enséñale al grupo cómo hacer un chupetón perfecto sin dejar demasiada marca.',
      'Descubre qué aroma te da ganas de desnudar a alguien al instante.',
      'Baila un lento de veinte segundos con alguien que esté ahí, susurrándole cosas atrevidas.',
      'Haz la misma cara que pones cuando te corres: el grupo vota la intensidad.',
      'Escribe un mensaje de «buenos días después del sexo» que volvería loco a cualquiera.',
      'Elige a quién del grupo te gustaría tener como «amigo de cama» durante todo un mes.',
      'Muerde suavemente el hombro de alguien que esté de acuerdo y deja que se quede con ganas de más.',
      'Recorre con el dedo la espalda desnuda de una persona que esté de acuerdo, desde la nuca hasta la cintura.',
      'Desliza un cubito de hielo por el cuello de una persona que esté de acuerdo con la boca.',
      'Suéltate el pelo y deja que caiga sobre una persona que esté de acuerdo mientras le susurras algo.',
      'Le muerde los dedos, uno a uno, a una persona que se lo permite, mirándola a los ojos.',
      'Baila agachándote lentamente delante de una persona que haya dado su consentimiento y que haya elegido el grupo.',
      'Roza con tus labios los de la persona más atractiva sin llegar a besarla, durante diez segundos.',
      'Pide a alguien que esté de acuerdo que te escriba en el cuerpo, con un dedo, una palabra obscena y adivínala.',
      'Apoya la frente contra la de la persona que te parezca más atractiva y respirad juntos durante veinte segundos.',
      'Acaricia la nuca de una persona que esté de acuerdo mientras le susurras la frase más sensual que conozcas.',
      'Besa la muñeca de tres personas diferentes que den su consentimiento, fingiendo cada vez más deseo.',
      'Dale un suave masaje en los hombros a la persona que tienes a tu derecha, susurrándole lo mucho que te gusta su piel.',
      'Pasa la lengua por el borde de un vaso de forma provocativa mientras miras fijamente a la persona que te gusta.',
      'Muerde el labio inferior y mantén el contacto visual con la persona más atractiva durante todo un asalto.',
      'Quítate lentamente el cinturón o una correa y utilízala para atar (con consentimiento) las muñecas de alguien durante un minuto.',
      'Deja que una persona que esté de acuerdo te guíe la mano por donde quiera sobre la ropa, durante diez segundos.',
      'Recita una frase de una película erótica con la voz más ronca que puedas, delante de todos.',
      'Simula un beso apasionado con el dorso de la mano, lo más realista posible.',
      'Describe al grupo, mirando a una persona que esté de acuerdo, qué le harías a sus labios si pudieras.',
      'Susurra una cuenta atrás de cinco a uno al oído de alguien, como si fuera a pasar algo.',
      'Frota lentamente la mejilla contra la de alguien que está de acuerdo, como lo haría un gato en celo.',
      'Muerde el aire cerca del cuello de una persona que está de acuerdo, sin tocarla, para que se estremezca.',
      'Dibuja un corazón con la lengua en la palma abierta de una persona que esté de acuerdo.',
      'Baila medio minuto moviendo solo las caderas, de la forma más sensual posible, delante del grupo.',
      'Coloca las manos en las caderas de una persona que esté de acuerdo y guíala en un movimiento lento durante veinte segundos.',
      'Deja que alguien, con tu consentimiento, te sople en el cuello y reacciona como si te estuviera volviendo loco.',
      'Susurra «cierra los ojos» a una persona que esté de acuerdo y haz que adivine dónde la vas a rozar.',
      'Describe en voz alta cómo sería tu despertar ideal junto a la persona que tienes a tu derecha.',
      'Imagina que, con la mirada, desnudás a la persona más atractiva de la sala, en silencio, durante diez segundos.',
      'Besa en la mejilla a una persona que da su consentimiento, acercándose peligrosamente a los labios.',
      'Muestra cómo besarías a alguien bajo la lluvia utilizando al grupo como público y un cojín como pareja.',
      'Cuéntanos aquella vez en la que más deseaste a alguien sin poder tenerlo.',
      'Pasa una fresa (o un dedo) por los labios de una persona que esté de acuerdo y haz que la pruebe.',
      'Pide a alguien que, con el consentimiento de esa persona, te trace con el dedo una línea desde el cuello hasta la mano y aguanta la respiración.',
      'Repite «ven aquí» con tres tonos diferentes hasta que el grupo decida cuál es el más seductor.',
      'Haz una prueba para el papel protagonista de una película para adultos interpretando la escena inicial, vestido.',
      'Describe el lugar exacto en el que te gustaría que te besaran ahora mismo y deja que alguien lo intente (con tu consentimiento).',
      'Imita con las manos la silueta de la persona que te parezca más sexy mientras la miras a los ojos.',
      'Susurra al oído de la persona que tienes a tu izquierda en qué momento del día piensas más en el sexo.',
      'Deja que alguien, con tu consentimiento, te muerda suavemente la oreja y no te rías durante diez segundos.',
      'Baila apoyándote de espaldas contra una persona que esté de acuerdo, guiando sus movimientos con las caderas.',
      'Cuéntame, mientras la miras, qué te atrae físicamente de la persona que tienes a tu derecha, detalle por detalle.',
      'Mantén la mirada fija en la de una persona que está de acuerdo mientras le besas lentamente el dorso de la mano, subiendo hacia la muñeca.',
      'Haz el gesto de quitarte la camiseta lo más despacio posible, deteniéndote a mitad de camino entre las protestas del grupo.',
      'Susurra una promesa picante al oído de la persona que te gusta, como si fuera un secreto de Estado.',
      'Describe la escena de seducción perfecta y asigna a un presente el papel de protagonista.',
      'Besa con entusiasmo tu propio antebrazo, mostrando al grupo exactamente cómo sueles besar.',
      'Pide que te echan (o échate) unas gotas de agua en el cuello y deja que resbale sin secártelo durante una ronda.',
      'Mira a una persona que esté de acuerdo y articula con los labios, sin emitir ningún sonido, las tres palabras que te gustaría decirle en la cama.',
      'Desfilá como una modelo por una pasarela imaginaria y detente para lanzarle un beso a la persona que te gusta.',
      'Acaricia lentamente el brazo de la persona que tienes a tu lado mientras le cuentas tu sueño erótico más reciente.',
      'Pon una canción lenta e invita a bailar a la persona que más te gusta, cuerpo contra cuerpo.',
      'Deja que te tapen los ojos y reconoce a tres personas que están de acuerdo solo por el aroma de su piel.',
      'Susurra «eres todo lo que quiero esta noche» a la persona que tienes a tu derecha, como si realmente lo pensaras.',
      'Describe qué le harías a una persona que diera su consentimiento si solo tuvierais cinco minutos en una habitación a puerta cerrada.',
      'Muerde suavemente el hombro de una almohada, como si le estuvieras haciendo un chupetón a tu pareja.',
      'Sujeta la barbilla de una persona que esté de acuerdo y acerca tu cara a la suya, hasta que estés a un soplo de sus labios.',
      'Recita, de rodillas, una declaración de puro deseo a la persona más sexy de la sala.',
      'Desliza lentamente las manos por tus caderas mientras miras fijamente a la persona que te gusta, como en un videoclip.',
      'Susurra al oído de alguien que esté de acuerdo cuál es tu momento favorito de los preliminares.',
      'Pide a una persona que te dé su consentimiento para que elijas una parte de su cuerpo y hazle un cumplido muy atrevido sobre esa parte.',
      'Baila un tango improvisado con alguien que esté de acuerdo, y termina en una pose a pocos centímetros de su cara.',
      'Describe cómo seducirías a alguien utilizando solo la voz y demuéstralo en una actuación de diez segundos.',
      'Pide a alguien que te escriba en el cuello, con un dedo, el nombre de la persona que te atrae y deja que el grupo adivine de quién se trata.',
      'Cuéntanos la fantasía que te gustaría hacer realidad precisamente con alguien de esta habitación.',
      'Muestra al grupo cómo te mueves sobre tu pareja, utilizando un cojín, durante diez segundos.',
      'Susurra a la persona más atractiva qué es lo primero que te llama la atención de ella cada vez que entra en una habitación.',
      'Pasa un dedo por tus labios lentamente mientras mantienes la mirada fija en la persona que deseas.',
      'Pide al grupo que te diga tres palabrotas y úsalas en una frase seductora dirigida a la persona que te gusta.',
      'Besa lentamente los nudillos de una persona que da su consentimiento, mientras elevas la mirada hasta sus ojos.',
      'Describe el aroma corporal que más te gusta en una pareja y huele (con su consentimiento) el cuello de alguien para comprobarlo.',
      'Deja que una persona que esté de acuerdo te susurre al oído su fantasía y reacciona solo con la mirada.',
    ],
    ContentTone.hot: [
      'Dale un beso con lengua a la persona que tienes a tu derecha, si está de acuerdo.',
      'Deja que una persona que esté de acuerdo te quite una prenda con los dientes.',
      'Imita tu postura favorita con una persona que esté de acuerdo durante treinta segundos.',
      'Describe en voz alta cómo te llevarías a la cama a la persona que tienes delante.',
      'Muéstrame la cara que pones cuando alcanzas el orgasmo.',
      'Lame el cuello de la persona que tienes a tu izquierda hasta que se estremezca, siempre que esté de acuerdo.',
      'Haz un chupetón bien visible en el hombro de alguien que esté de acuerdo.',
      'Siéntate a horcajadas sobre una persona que esté de acuerdo y quédate así durante todo un asalto.',
      'Finge un orgasmo ruidoso y realista durante veinte segundos delante de todo el mundo.',
      'Susurra al oído de la persona que tienes delante la cosa más obscena que le harías.',
      'Haz un lap dance de un minuto a una persona que dé su consentimiento y que elija el grupo.',
      'Muerde suavemente el lóbulo de la oreja de la persona que tienes a tu derecha, si está de acuerdo.',
      'Pasa un cubito de hielo de tu boca a la de otra persona que esté de acuerdo.',
      'Muéstrale al grupo cómo mueves las caderas durante el sexo, estando de pie.',
      'Lame una gota de bebida del cuello de una persona que esté de acuerdo.',
      'Quítate una prenda de ropa y quédate así durante las tres siguientes rondas.',
      'Muestra en qué postura duermes, tumbándote en el suelo.',
      'Besa la parte del cuerpo que prefieras de una persona que dé su consentimiento.',
      'Simula una felación con un plátano u otro objeto durante quince segundos.',
      'Baila un lento cuerpo a cuerpo con una persona que esté de acuerdo, con las manos libres.',
      'Describe con todo detalle la última vez que te masturbaste.',
      'Expresa con gestos lo especial que es tu ex más memorable.',
      'Pon la mano sobre el muslo de una persona que esté de acuerdo y déjala ahí durante un asalto.',
      'Imita los sonidos que haces en la cama cuando estás a punto de correrte.',
      'Lámete el dedo de una persona que esté de acuerdo con ello de la forma más provocativa posible.',
      'Quítate la ropa hasta quedarte en ropa interior y cambia de sitio con la persona que tienes delante.',
      'Demuestra lo sensual que puedes ser quitándote lentamente los calcetines o los zapatos.',
      'Muerde suavemente el cuello de una persona que esté de acuerdo, dejando la marca de los dientes.',
      'Muestra con una mano el movimiento de la lengua que harías en un beso francés.',
      'Dale unas nalgadas a alguien que esté de acuerdo y deja que te den unas nalgadas a ti también.',
      'Describe la fantasía sexual que más te excita, sin tapujos.',
      'Imagina que estás montando a alguien mientras estás sentado en una silla durante veinte segundos.',
      'Dale un masaje sensual en la espalda a una persona que esté de acuerdo durante un minuto.',
      'Demuestra cómo besar apasionadamente utilizando el dorso de la mano.',
      'Desnuda el hombro y deja que una persona que esté de acuerdo te bese ahí.',
      'Cuenta en voz alta el sueño erótico más atrevido que recuerdes.',
      'Imita la postura del misionero en el aire durante diez segundos, con expresión.',
      'Susurra un gemido al oído de la persona que tienes a tu derecha, si está de acuerdo.',
      'Deja que una persona que esté de acuerdo te ate las muñecas con una bufanda durante un asalto.',
      'Describe qué es lo que más te excita del cuerpo de la persona que tienes delante.',
      'Demuestra cómo te quitarías el sujetador con una sola mano y con los ojos cerrados.',
      'Lamer la nata o el azúcar del dedo de una persona que esté de acuerdo.',
      'Muestra tu mejor primer plano con una mirada seductora y mantenla durante diez segundos.',
      'Finge que le estás haciendo una mamada a un pepino con la máxima seriedad durante quince segundos.',
      'Deja que alguien, con tu consentimiento, te sople en el cuello y reacciona como lo harías en la cama.',
      'Describe la vez en que tuviste el orgasmo más intenso de tu vida.',
      'Baila pole dance utilizando una silla como barra durante treinta segundos.',
      'Acerca tus labios un centímetro a los de la persona que tienes delante, sin besarla, durante diez segundos.',
      'Emite un gemido que va aumentando de intensidad y termina en un grito, como un auténtico clímax.',
      'Pasa la lengua por el labio superior mientras miras fijamente a la persona que más te atrae aquí.',
      'Quítate la ropa interior que llevas debajo de la ropa y enséñasela al grupo.',
      'Deja que una persona que esté de acuerdo te muerda el cuello durante cinco segundos.',
      'Describe tu juguete sexual favorito y cómo lo utilizas.',
      'Finge desnudar con la mirada a cada una de las personas presentes, una por una.',
      'Haz un baile del vientre lento y seductor durante veinte segundos.',
      'Lámete un dedo despacio y métetelo en la boca, sin apartar la mirada de la persona que tienes delante.',
      'Susurra a una persona que esté de acuerdo en qué postura te gustaría que estuviera.',
      'Apoya la cabeza en el regazo de una persona que esté de acuerdo durante toda una ronda.',
      'Muestra cómo mueves la lengua cuando practicas sexo oral, con un polo o con una cuchara.',
      'Pide a alguien que te dé un masaje en los muslos durante treinta segundos, siempre que esa persona esté de acuerdo.',
      'Describe la parte de tu cuerpo que te vuelve loco cuando te la tocan.',
      'Simula un abrazo apasionado con una almohada durante veinte segundos.',
      'Besa la mano de una persona que esté de acuerdo y ve subiendo hasta el codo.',
      'Demuestra lo atrevido que sabes ser imitando un striptease de diez segundos.',
      'Susurra al oído de cada uno de los miembros del grupo, uno por uno, lo mucho que te parecen atractivos.',
      'Que te tapen los ojos y adivina quién te besa en la mejilla de entre las personas que están de acuerdo.',
      'Describe cómo te gusta que te toquen durante los preliminares.',
      'Imita la postura de la perrita en el aire durante diez segundos, con convicción.',
      'Lame el borde del vaso de forma obscena mientras todos miran.',
      'Haz un twerk desenfrenado de treinta segundos delante del grupo.',
      'Coloca la mano de una persona que esté de acuerdo en tu costado y guíala mientras bailas.',
      'Cuéntanos qué es lo más atrevido que has hecho en la cama para causar impresión.',
      'Simula rodear a alguien con las piernas utilizando el aire, sin dejar de estar de pie.',
      'Deja que una persona que esté de acuerdo te toque ligeramente la nuca y muestra cómo reaccionas.',
      'Describe con detalle la relación sexual que te gustaría tener esta noche.',
      'Haz el sonido más erótico que se te ocurra mientras miras a los ojos a la persona que te atrae.',
      'Besa la muñeca de una persona que esté de acuerdo y sube lentamente con los labios.',
      'Muestra cómo arqueas la espalda en el momento álgido del placer.',
      'Susurra tres palabras subidas de tono al oído de la persona que tienes a tu izquierda, si está de acuerdo.',
      'Deja que una persona que esté de acuerdo te muerda un dedo de forma provocativa.',
      'Describe la parte del cuerpo de una persona de las que están aquí que más te llama la atención.',
      'Simula un orgasmo lento acariciándote solo el cuello y la cara.',
      'Lanza una mirada seductora y mueve los labios hacia la persona que más te gusta.',
      'Quítate la camiseta o desabrochátela y quédate así durante dos asaltos, si te apetece.',
      'Lame la sal de la mano de una persona que esté de acuerdo antes de tomarte un «cicchetto».',
      'Pon las manos en las caderas de una persona que esté de acuerdo y haz que baile contigo.',
      'Describe lo más obsceno que te hayan susurrado alguna vez en la cama.',
      'Finge que lames algo muy íntimo de una fruta durante diez segundos.',
      'Deja que alguien que esté de acuerdo te abrace por detrás y quédate así durante un asalto.',
      'Muéstranos cómo te mueves cuando estás encima durante el sexo, en una silla.',
      'Susurra al oído de la persona que tienes delante tu deseo más prohibido.',
      'Besa lentamente el cuello de una persona que esté de acuerdo, contando hasta diez.',
      'Muestra tu repertorio de gemidos en tres intensidades diferentes.',
      'Deja que alguien, con tu consentimiento, te sople suavemente en la oreja y reacciona.',
      'Describe cómo le pondrías las manos encima a la persona que tienes delante, si pudieras.',
      'Simula un baile seductor quitándote lentamente un cinturón o un accesorio.',
      'Lame el azúcar de los labios de una persona que esté de acuerdo, si ella lo acepta.',
      'Haz tu mejor imitación de cómo llamas a alguien por su nombre en la cama.',
      'Acerca tu frente a la de la persona que tienes delante y respira profundamente durante diez segundos.',
      'Describe la fantasía a tres que te gustaría vivir y con quién la vivirías.',
      'Simula un striptease completo sin quitarte la ropa, en treinta segundos.',
      'Deja que una persona que esté de acuerdo te haga cosquillas suavemente en la espalda, por encima de la ropa.',
      'Muestra cómo contoneas las caderas al entrar en una habitación para que todos se queden boquiabiertos.',
      'Susurra a alguien que esté de acuerdo lo que le harías si estuviéramos solos.',
      'Besa la parte interior de la muñeca de la persona que tienes delante sin apartar la mirada.',
      'Describe el sonido que más te excita durante el sexo.',
      'Simula un abrazo de pie, apoyándote en la pared durante quince segundos.',
      'Muestra con las manos el tamaño de la relación sexual más impresionante que hayas tenido.',
      'Lámete el dedo índice y roza tus labios mientras miras a quien más te atraiga.',
      'Deja que alguien, con tu consentimiento, te tire suavemente del pelo y muestra cómo reaccionas.',
      'Describe el lugar más descabellado en el que te gustaría tener sexo.',
      'Imita la postura del 69 con un cojín durante diez segundos.',
      'Acaricia sensualmente el rostro de una persona que esté de acuerdo, bajando hasta el cuello.',
      'Susurra una lista de tres cosas que le harías a la persona que tienes delante esta noche.',
      'Muestra cómo se baila pegado a alguien en una discoteca, con una persona que esté de acuerdo.',
      'Pide a alguien que te dé un beso de those en el cuello, siempre que sea con su consentimiento.',
      'Describe lo más emocionante que te ha pasado en un lugar público.',
      'Finge gemir el nombre de la persona más sexy de la sala.',
      'Lame lentamente la parte exterior de la mano de la persona que tienes delante.',
      'Muéstranos cómo te desnudas cuando quieres seducir a alguien, con calma.',
      'Pasa una mano por el pelo de una persona que esté de acuerdo y acerca tu cara.',
      'Describe qué harías con los labios de la persona que más te atrae en esta sala.',
      'Finge que estás esposado a la cama durante diez segundos, con expresión.',
      'Deja que alguien te acaricie la espalda desnuda, si está de acuerdo.',
      'Suelta un gemido ahogado, como si te estuvieras conteniendo en un lugar público.',
      'Susurra al oído de la persona que tienes a tu derecha cuál es tu fetiche, siempre que esté de acuerdo.',
      'Besa el cuello de una almohada como si fuera la persona que más deseas.',
      'Describe la experiencia más alocada que te gustaría vivir al menos una vez.',
      'Finge que te están dando azotes y reacciona con un gemido durante diez segundos.',
      'Chupa lentamente una piruleta o un polo mientras miras fijamente a la persona que te gusta.',
      'Muéstranos cómo te arqueas cuando alguien te besa justo en el punto adecuado.',
      'Acerca los labios al hombro de una persona que esté de acuerdo y sube hasta la oreja.',
      'Describe los preliminares que nunca te cansan y te llevan al éxtasis.',
      'Simula una relación apasionada contra una puerta durante quince segundos.',
      'Deja que una persona que esté de acuerdo te muerda suavemente el labio inferior.',
      'Ponte tu mirada más seductora mientras te pasas las manos por el cuerpo.',
      'Susurra a la persona que tienes delante lo mucho que la deseas, utilizando palabras explícitas.',
      'Besa los dedos de una persona que esté de acuerdo, uno a uno, de forma sensual.',
      'Describe la postura en la que alcanzas el orgasmo más fácilmente.',
      'Simula un baile erótico frotándote lentamente contra una silla.',
      'Lame una gota imaginaria del pecho o del cuello de la persona que tengas delante, si está de acuerdo.',
      'Enséñanos cómo te mueves entre las sábanas cuando haces el amor.',
      'Pon la mano sobre el corazón de una persona que esté de acuerdo y desciende lentamente hacia el abdomen.',
      'Describe el orgasmo más largo que hayas tenido nunca y cómo ocurrió.',
      'Finge chuparte un dedo de forma obscena durante diez segundos mientras miras al grupo.',
      'Deja que alguien que esté de acuerdo contigo te abrace con fuerza y susúrrale un gemido.',
      'Pon tu cara de clímax mientras arqueas la espalda durante cinco segundos.',
      'Susurra al oído de cada uno lo que te gustaría hacerle, una vuelta completa.',
      'Muéstranos cómo reaccionas cuando te mordisquean el cuello, con la voz y los escalofríos.',
      'Imita tu momento de mayor placer, con la voz y los movimientos, durante diez segundos.',
    ],
  };

  static const Map<String, List<String>> verita = {
    ContentTone.normal: [
      '¿Qué es lo más vergonzoso que has hecho en público?',
      '¿Cuál fue la mentira más gorda que contaste de pequeño?',
      '¿Cuál es tu «placer culpable» musical?',
      '¿Qué película te ha hecho llorar más?',
      '¿Cuál es la tontería más grande por la que te has peleado?',
      '¿Cuál crees que es tu peor defecto?',
      '¿Qué defecto te achacan tus amigos y tú no reconoces en absoluto?',
      '¿Cuál es la cosa más cara que has roto?',
      '¿Alguna vez has fingido estar mal para evitar algo?',
      '¿Cuál es la excusa que utilizas con más frecuencia?',
      '¿Qué haces cuando estás solo y nadie te ve?',
      '¿Cuál es tu costumbre más extraña?',
      '¿Cuánto tiempo pasas realmente con el móvil cada día?',
      '¿Cuál es la aplicación que abres más a menudo sin motivo alguno?',
      '¿Cuál fue tu última búsqueda en Internet, la de verdad?',
      '¿Cuál es la foto más antigua que tienes en el móvil?',
      '¿Quién es la última persona a la que le has escrito?',
      '¿Cuál es el mensaje más embarazoso que has enviado?',
      '¿Alguna vez has enviado un mensaje a la persona equivocada? ¿Qué decía?',
      '¿Qué es lo más bonito que te ha dicho alguien?',
      '¿Cuál es el cumplido más raro que te han hecho nunca?',
      '¿Quién es la persona más importante de tu vida?',
      '¿A quién llamarías si tuvieras un problema grave a las tres de la madrugada?',
      '¿Qué es lo que más valoras en un amigo?',
      '¿Cuál ha sido el mejor momento de este año?',
      '¿Cuál ha sido el momento más difícil de este año?',
      '¿Qué es lo que más te da miedo de cara al futuro?',
      '¿Cuál es ese sueño que aún no le has contado a nadie?',
      '¿Qué harías si mañana ya no tuvieras que trabajar?',
      'Si pudieras cambiar una decisión, ¿cuál sería?',
      '¿De qué es de lo que te sientes más orgulloso?',
      '¿Qué cumplido te gustaría que te hicieran?',
      '¿Qué te pone de buen humor en cinco minutos?',
      '¿Qué es lo que más rápido te hace enfadar?',
      '¿Cuál es esa manía de la que no consigues librarte?',
      '¿Eres más ordenado o más desordenado de lo que admites?',
      '¿Cuándo fue la última vez que te reíste hasta llorar?',
      '¿Qué es lo más valiente que has hecho?',
      '¿Qué es lo que nunca harías por dinero?',
      '¿Por cuánto dinero te afeitarías la cabeza al cero?',
      '¿Cuál es tu talento oculto?',
      '¿Qué es lo único que todos saben hacer menos tú?',
      '¿Qué es lo más difícil que has aprendido?',
      '¿Qué nota le darías a tu vida ahora mismo, del 1 al 10?',
      '¿Qué te falta para sacar un 10 redondo?',
      '¿Cuál es el lugar más bonito en el que has estado?',
      '¿Dónde te gustaría vivir si pudieras elegir?',
      '¿Qué viaje volverías a hacer mañana?',
      '¿Cuáles han sido las peores vacaciones que has tenido?',
      '¿Alguna vez has perdido un vuelo o un tren? ¿Cómo acabó todo?',
      '¿Qué es lo más raro que te has comido?',
      '¿Cuál es el plato que mejor sabes cocinar?',
      '¿Cuál es tu comida reconfortante?',
      '¿Te comerías el mismo plato durante un mes por mil euros?',
      '¿Cuál es la cosa más inútil que has comprado?',
      '¿Cuánto tiempo tardas realmente en prepararte?',
      '¿Cuál es ese vestido que no te deshaces de él aunque deberías?',
      '¿Cuál es la moda que seguías y que ahora rechazas?',
      '¿Qué corte de pelo te arrepientes de haberte hecho?',
      '¿Te harías un tatuaje? ¿Dónde y qué?',
      '¿Qué es lo último que has hecho solo para hacer feliz a otra persona?',
      '¿Alguna vez has fingido que habías entendido algo para no quedar mal?',
      '¿Cuál es el tema sobre el que más finges?',
      '¿Cuál es el libro que dices que has leído pero que no has terminado?',
      '¿Qué serie has dejado de ver a mitad?',
      '¿Qué personaje se parece más a ti?',
      'Si fueras un animal, ¿cuál serías y por qué?',
      'Si tuvieras que cambiarte de nombre, ¿cuál elegirías?',
      '¿Cuál es el apodo que odiabas de pequeño?',
      '¿Qué es lo más aburrido que has hecho en el trabajo?',
      '¿Cuál era el compañero de clase o de trabajo que no soportabas y por qué?',
      '¿Qué es lo que más tiempo llevas posponiendo?',
      '¿A qué hora te acuestas realmente?',
      '¿Cuántas veces apagas el despertador antes de levantarte?',
      '¿Cuál es tu rincón favorito de casa?',
      '¿Qué te llevarías si tuvieras que huir de casa en un minuto?',
      '¿Cuál es el objeto al que más cariño le tienes?',
      '¿Cuál es el mejor regalo que has recibido?',
      '¿Cuál es el peor regalo que te han hecho nunca?',
      '¿Alguna vez has reciclado un regalo?',
      '¿Cuál es el propósito de Año Nuevo que nunca has cumplido?',
      '¿Qué hábito te gustaría eliminar?',
      '¿Qué hábito te gustaría empezar a practicar?',
      '¿A quién del grupo llamarías para pedirle un consejo serio?',
      '¿Quién del grupo te hace reír más?',
      '¿Qué has aprendido de las personas que estaban aquí esta noche?',
      '¿Qué te gustaría que el grupo supiera de ti?',
      '¿Cuál es la pregunta que esperabas que no te hicieran esta noche?',
      '¿Hay algo que siempre hayas querido preguntarle a alguien de aquí?',
      'Si tuvieras que describir esta velada con una sola palabra, ¿cuál sería?',
      '¿Qué es lo más embarazoso que te ha pasado en el colegio?',
      '¿Cuál es el sueño más absurdo que recuerdas?',
      '¿Cuál es la mentira piadosa que más sueles decir?',
      '¿Qué comida finges que te gusta por pura cortesía?',
      'Si tuvieras un superpoder durante un día, ¿qué harías lo primero?',
      '¿A qué persona famosa te gustaría invitar a cenar y qué le preguntarías?',
      '¿Cuál es la cosa más divertida que te ha pasado en una reunión familiar?',
      'Si pudieras intercambiar tu vida con la de otra persona durante un día, ¿a quién elegirías?',
      '¿Cuál es la canción que siempre cantas equivocándote en la letra?',
      '¿Qué es lo más raro que has hecho por aburrimiento?',
      '¿Alguna vez se te ha escapado una risa en un momento en el que estaba totalmente prohibido? Cuéntanoslo.',
      '¿Cuál es esa metedura de pata que hoy te hace reír, pero que en su momento te dejó hecho polvo?',
      '¿Cuál es el objeto más raro que tienes en tu habitación?',
      '¿Qué es lo más infantil que sigues haciendo hoy en día?',
      'Si tu vida fuera una película, ¿qué actor te interpretaría?',
      '¿Cuál ha sido tu peor idea «genial»?',
      '¿Alguna vez has cantado delante del espejo usando el cepillo como micrófono?',
      '¿Cuál es la palabra que siempre se te escapa al pronunciarla?',
      '¿Cuál es tu récord más absurdo, sea lo que sea que cuente como récord?',
      '¿Qué harías primero si mañana por la mañana ganaras un millón?',
      '¿Cuál es la aplicación más inútil que te has descargado y que nunca has usado?',
      '¿Te has quedado dormido alguna vez en un sitio insólito? ¿Dónde?',
      '¿Qué es lo que buscas en Internet porque te da vergüenza no saberlo?',
      '¿Cuál es el plato que has estropeado de la forma más espectacular?',
      '¿Cuál es la norma de tu casa que creías que era normal y, en cambio, resultaba muy extraña?',
      '¿Qué personaje de dibujos animados te daba miedo cuando eras niño?',
      '¿Cuál es la cosa más absurda en la que creías cuando eras niño?',
      '¿Alguna vez has respondido al saludo de alguien que estaba saludando a otra persona?',
      '¿Qué notificación te causa más ansiedad?',
      '¿Cuál es la canción que te hace revivir los recuerdos cada vez que la escuchas?',
      'Si pudieras teletransportarte a cualquier lugar durante un día, ¿adónde irías?',
      '¿Qué profesión soñabas con ejercer cuando eras niño?',
      '¿Qué es lo que a todo el mundo le encanta y a ti, en cambio, no?',
      '¿Qué programa basura ves y defenderías a capa y espada?',
      '¿Alguna vez has hablado con tu mascota o con las plantas como si lo entendieran todo?',
      '¿Qué es lo que peor se te da, pero sigues haciendo con entusiasmo?',
      '¿Cuál es el mensaje más bonito que guardas en el móvil?',
      '¿Cuál es esa teoría descabellada en la que crees un poco, aunque sabes que es absurda?',
      '¿Cuál es tu plan de supervivencia en caso de un apocalipsis zombi?',
      '¿Preferirías saber volar o leer la mente, y por qué?',
      '¿Cuál es la excusa más creativa que has utilizado para justificar un retraso?',
      '¿Qué hacías de niño que te gustaría que fuera socialmente aceptable también hoy en día?',
      '¿Quién del grupo crees que sobreviviría más tiempo en una isla desierta?',
      '¿Cuál es la palabra italiana que te parece más graciosa?',
      '¿Cuál es el sonido o ruido que no puedes soportar en absoluto?',
      '¿Qué es lo más bonito que has hecho en secreto por alguien?',
      '¿Alguna vez has ganado algo en un concurso o en una lotería? ¿Qué?',
      '¿Qué sabor de helado crees que debería prohibirse por ley?',
      '¿Cuál es esa película que a todo el mundo le encanta y que tú nunca has conseguido terminar de ver?',
      '¿Cuál es la comida que finges que no te gusta, pero que te comerías a escondidas?',
      '¿Cuál es la canción que solo cantas cuando estás seguro de que nadie te oye?',
      '¿Qué es lo más absurdo que haces cuando estás seguro de que nadie te está mirando?',
      '¿Cuál es tu talento más inútil?',
      '¿Cuál es el miedo más irracional que tienes?',
      '¿Cuál es el peor regalo que has vuelto a regalar?',
      '¿Qué es lo más embarazoso que hay en tu historial de YouTube?',
      '¿Cuál es la excusa que utilizas más a menudo para irte de una fiesta?',
      '¿Qué dibujos animados te verías ahora mismo sin que te diera vergüenza?',
      'Si pudieras intercambiar tu trabajo por el de uno de los aquí presentes durante un día, ¿a quién elegirías?',
      '¿Cuál es el cumplido que más te gusta que te hagan?',
    ],
    ContentTone.mix: [
      '¿Cómo fue tu primera vez? Edad, lugar, postura y puntuación del 1 al 10.',
      '¿Con cuántas personas te has acostado? Di el número exacto, sin redondear.',
      '¿Cuál es el lugar más absurdo o arriesgado en el que lo has hecho?',
      '¿Alguna vez has practicado sexo anal? ¿Te gustó? Sé sincero.',
      '¿Alguna vez te has acostado con alguien el mismo día que lo conociste? ¿Cuántas veces?',
      '¿Cuál ha sido tu aventura de una noche más loca y dónde ocurrió?',
      '¿Alguna vez te has acostado con un amigo y luego has hecho como si nada? ¿Quién era?',
      '¿Alguna vez has practicado sexting con más de tres personas a la vez?',
      '¿Cuál es el mensaje más obsceno que has enviado o recibido nunca? Cítalo.',
      '¿Alguna vez has enviado o recibido un vídeo explícito de ti mismo? ¿Lo volverías a hacer?',
      '¿Alguna vez has recibido una foto atrevida que no habías pedido? ¿Cuál fue tu verdadera reacción?',
      '¿Cuál es tu fantasía erótica más extrema que nunca le has contado a nadie?',
      '¿Alguna vez has tenido un trío? Si no es así, ¿con quién de este grupo lo harías?',
      '¿Hay alguien en esta sala con quien te gustaría pasar la noche? Un nombre.',
      '¿Preferirías un orgasmo alucinante de tres minutos o una hora de mimos perfectos?',
      '¿Quién ha sido el mejor amante de tu vida y por qué? ¿Qué tenía de especial?',
      '¿Alguna vez has besado a dos personas diferentes en la misma hora? ¿Dónde estabais?',
      '¿Alguna vez te has arrepentido amargamente de haberte acostado con alguien mientras lo hacías?',
      '¿Alguna vez te has despertado junto a alguien y te has escapado por la ventana o a escondidas?',
      '¿Qué es lo que más importa en la cama: la técnica, el tamaño o la conexión mental?',
      '¿En la cama eres más dominante o sumiso? Pon un ejemplo de lo que te gusta hacer.',
      '¿Luces encendidas, espejos y vídeos, o oscuridad total? Justifica tu elección.',
      '¿Cuál es el cumplido más excitante que te han hecho mientras tenías relaciones sexuales?',
      '¿Alguna vez has fingido un orgasmo para que la relación sexual terminara antes? ¿Cuántas veces?',
      '¿Cuál es la situación más embarazosa que te ha pasado alguna vez mientras lo hacías?',
      '¿Alguna vez te han pillado tus padres o un desconocido mientras estabas en plena acción?',
      '¿Alguna vez has fingido estar dormido para evitar dormir? ¿Porque no te apetecía?',
      '¿Alguna vez has mentido sobre tus logros para impresionar a tus amigos?',
      '¿Cuál ha sido tu maratón sexual más largo? ¿Cuántas veces al día?',
      '¿Hay alguien en este grupo que te haya puesto a tono con solo hablar?',
      '¿Qué es lo primero que te llama la atención de una persona y te hace pensar «quiero acostarme con ella»?',
      '¿Cuál es la prenda de ropa que te parece más sexy de todas? ¿Y la que te quita las ganas?',
      '¿Te consideras bueno en la cama? ¿Cuál es tu punto fuerte indiscutible?',
      '¿Qué te gustaría aprender a hacer mejor en la cama? ¿Alguna vez has visto tutoriales?',
      '¿Cuál es la frase de ligue más descarada que has utilizado y que te ha funcionado?',
      '¿Alguna vez has coqueteado con la pareja de un amigo íntimo? ¿Hasta dónde llegaste?',
      '¿Alguna vez le has dado un número falso a alguien después de haberte liado con él o ella? ¿Por qué?',
      '¿Qué es lo más atrevido que has hecho en un lugar público lleno de gente?',
      '¿Alguna vez has tenido un ligue de verano que haya acabado con un vídeo o una foto picante?',
      '¿Cuál ha sido la mayor diferencia de edad que has tenido en una relación sexual?',
      '¿Alguna vez has besado a alguien de esta sala sin que los demás se dieran cuenta?',
      '¿A quién de nosotros besarías enseguida si se fuera la luz durante un minuto?',
      '¿Quién de nosotros crees que es el más «salvaje» en la cama, viéndolo ahora?',
      '¿Alguna vez has usado una aplicación de citas solo para tener sexo esporádico? ¿Cuántas personas con las que has coincidido han acabado en la cama?',
      '¿Cuál es la conversación más comprometedora que tienes ahora mismo en el móvil?',
      '¿Alguna vez le has escrito a un ex a las tres de la madrugada solo porque te apetecía hacerlo?',
      '¿Qué es lo que más echas de menos en la cama de tu última pareja?',
      '¿Alguna vez has tenido una aventura secreta con alguien que ya tenía pareja? ¿Cómo acabó?',
      '¿Alguna vez has sido «el otro» o «la otra» a sabiendas? ¿Te has sentido culpable?',
      '¿Cuál es tu «fetiche» más raro o inconfesable?',
      '¿Arriba o abajo? ¿Delante o detrás? Responde rápido, sin pensarlo.',
      '¿Alguna vez has sentido dolor en la cama y has descubierto que te gustaba?',
      '¿Alguna vez has tenido relaciones sexuales en una oficina o en el trabajo?',
      '¿Alguna vez te has tocado pensando en alguien que está en esta habitación?',
      '¿Qué parte de tu cuerpo es la que más cumplidos recibe en la cama?',
      '¿Alguna vez has hecho un striptease para alguien? ¿Cómo te fue?',
      '¿Qué es lo más obsceno que le has dicho a alguien mientras lo hacías?',
      'Si pudieras elegir a una persona famosa para pasar una noche dedicada exclusivamente al sexo, ¿a quién elegirías?',
      '¿Alguna vez has tenido relaciones sexuales en el mar, en una piscina o en un jacuzzi público?',
      '¿A qué hora del día sueles sentirte más excitado?',
      '¿Qué sueles ponerte para dormir cuando estás con alguien a quien quieres provocar?',
      '¿Alguna vez has tenido relaciones sexuales con los calcetines puestos? El grupo te juzga si dices que sí.',
      '¿Cuál es la postura que te resulta más agotadora, pero que más te gusta?',
      '¿Alguna vez has probado el sexo tántrico o las sesiones muy largas? Cuéntanoslo.',
      '¿Alguna vez has utilizado comida o hielo durante los preliminares? ¿Cómo acabó todo?',
      '¿Cuál es la señal inequívoca que envías cuando quieres hacerlo ya mismo?',
      '¿A quién de nosotros te llevarías ahora mismo a una habitación privada, si pudieras?',
      '¿Qué es lo primero que te hace darte cuenta de que una persona te desea de verdad?',
      '¿Alguna vez has besado a alguien de tu mismo sexo? ¿Te gustó o te quedó curiosidad?',
      '¿Cuál es ese gesto aparentemente inocente que te excita más que ningún otro?',
      '¿Prefieres seducir o que te seduzcan? Pon un ejemplo concreto de tu última conquista.',
      '¿Qué es lo más atrevido que has pedido en la cama y cómo te lo tomaron?',
      '¿Alguna vez has tenido un sueño erótico con alguien que esté aquí presente?',
      '¿Qué parte del cuerpo de tu pareja te vuelve completamente loco?',
      '¿Cuánto dura para ti la noche perfecta y cuántas veces te gustaría vivirla?',
      '¿Alguna vez has usado un juguete sexual en pareja? Si no es así, ¿te gustaría probarlo?',
      '¿Cuál es la mayor mentira que te has inventado para acostarte con alguien?',
      '¿Alguna vez te has enamorado en secreto de un amigo de tu pareja?',
      '¿Cuál es el lugar de tu casa donde más te gusta hacerlo, aparte de la cama?',
      '¿Alguna vez has tenido relaciones sexuales en la primera cita? ¿Te has arrepentido o lo has vuelto a hacer?',
      '¿Cuál es la frase que te hace caer rendido a los pies de alguien al instante?',
      '¿Prefieres un masaje erótico muy lento o ir directamente al grano?',
      '¿Qué es lo más atrevido que te has puesto para volver loco a alguien?',
      '¿Alguna vez has espiado o has oído por casualidad a dos personas que lo estaban haciendo? Cuéntanoslo.',
      '¿Cuál es tu récord en cuanto a la duración de los preliminares? ¿Te gustaría que duraran más o menos?',
      'Si tuvieras que describir tu estilo en la cama con una sola palabra, ¿cuál sería?',
      '¿Alguna vez has tenido un encuentro secreto en un baño público o en un coche?',
      '¿Cuándo fue la última vez que deseaste a alguien a quien no podías tener?',
      '¿Te has enamorado alguna vez de alguien solo por cómo besaba?',
      '¿Qué es lo que nadie se imaginaría jamás de ti en la cama?',
      '¿Alguna vez has enviado un mensaje picante a la persona equivocada? ¿Cómo acabó todo?',
      '¿Quién de los que están en esta sala crees que es el que mejor sabe coquetear sin que se note?',
      '¿Cuál es tu límite absoluto en la cama, eso que nunca harías?',
      '¿Alguna vez has besado a alguien solo para dar celos a otra persona?',
      '¿Qué parte de ti te gustaría que alguien besara más a menudo?',
      '¿Alguna vez has tenido una relación basada únicamente en el sexo? ¿Cuánto tiempo duró?',
      '¿Cuál es la fantasía que compartes con tu pareja pero que nunca has llevado a cabo?',
      '¿Qué te excita más: la voz, la mirada o las manos de una persona?',
      '¿Alguna vez has fingido que no te interesaba alguien a quien, en realidad, deseabas con todas tus fuerzas?',
      '¿Cuál ha sido el proceso de seducción más largo que has vivido antes de acabar finalmente en la cama con alguien?',
      '¿Alguna vez has tenido relaciones sexuales mientras escuchabas una canción concreta? ¿Cuál?',
      '¿Qué cumplido sobre tu aspecto físico te hace sentir deseable al instante?',
      '¿Alguna vez te has enamorado a primera vista por razones puramente físicas? ¿De quién y cómo fue?',
      '¿Prefieres los besos lentos y profundos o los apasionados y frenéticos?',
      '¿Qué es lo más picante que te han susurrado mientras lo hacíais?',
      '¿Alguna vez has sentido atracción por dos personas a la vez? ¿Cómo lo gestionaste?',
      '¿Cuál es el aroma, ya sea tuyo o de otra persona, que asocias con el mejor polvo que te has echado?',
      '¿Alguna vez has coqueteado descaradamente con alguien delante de tu pareja?',
      '¿Cuál es la postura que te gustaría probar pero nunca te has atrevido a proponer?',
      '¿Alguna vez has tenido una experiencia con más de dos personas? Si no es así, ¿lo harías y con quién de aquí?',
      '¿Qué es lo que te quita las ganas al instante justo cuando estás a punto de hacerlo?',
      '¿Qué es lo más sexy que puede hacer una persona sin quitarse nada de ropa?',
      '¿Alguna vez has tenido un coqueteo con alguien mucho mayor o mucho más joven que tú?',
      '¿Cuál es tu señal secreta para hacerle entender a alguien que te gusta, esta noche?',
      '¿Alguna vez te has excitado en un momento totalmente inapropiado? ¿Dónde estabas?',
      '¿Qué es lo que te convierte en un amante inolvidable, según quienes han estado contigo?',
      '¿Alguna vez has seguido pensando en un ex mientras estabas en la cama con otra persona?',
      '¿Cuál es la palabra más obscena que te gusta que te susurren al oído?',
      '¿Alguna vez has besado a alguien bajo los efectos de la adrenalina, por ejemplo, después de pasar un susto?',
      '¿Prefieres el sexo planificado y bien organizado o el espontáneo y apasionado?',
      '¿En qué ocasión corriste más riesgo de que te pillaran en plena acción?',
      '¿Alguna vez has escrito o recibido una carta o un mensaje erótico que aún conservas?',
      '¿A quién de los que están en esta habitación besarías, con quién te irías a la cama y a quién evitarías? Sé sincero.',
      '¿Cuál es el pensamiento más picante que se te pasa por la cabeza cuando ves a alguien que te gusta muchísimo?',
      '¿Alguna vez has vivido una aventura durante las vacaciones que nunca le has contado a nadie?',
      '¿Cuál es el juego de rol que te gustaría probar al menos una vez en la vida?',
      '¿Alguna vez te has despertado con ganas junto a un amigo? ¿Qué hiciste?',
      '¿Cuál es la cosa más embarazosa que has buscado en Internet sobre sexo?',
      '¿Alguna vez has tenido miedo de decepcionar a alguien en la cama? ¿Y cómo te fue al final?',
      '¿Cuál fue el momento en el que te sentiste más deseado de toda tu vida?',
      '¿Prefieres hacer el amor a oscuras o mirar todo a los ojos de tu pareja?',
      '¿Alguna vez has besado a más de una persona en una misma noche? ¿A cuántas?',
      '¿Qué es lo más descabellado que harías por pasar una noche con la persona que te gusta?',
      '¿Alguna vez te ha pasado que has tenido que contener los gemidos para que no te oyeran? ¿Dónde?',
      '¿Cuál es tu zona erógena secreta que pocos han descubierto?',
      '¿Alguna vez has dado el primer paso, sin dudarlo, con alguien que acababas de conocer?',
      '¿Qué es lo que te hace sentir más seguro de ti mismo cuando estás desnudo?',
      '¿Alguna vez has tenido una relación a distancia basada únicamente en videollamadas picantes?',
      '¿Cuál es el recuerdo erótico que te viene a la mente con más frecuencia cuando estás solo?',
      'Si la pareja de tus sueños te pidiera una sola cosa en la cama, ¿qué te gustaría que fuera?',
      '¿Alguna vez has tenido sexo de reconciliación después de una pelea furiosa? ¿Fue mejor?',
      '¿Con quién has tenido más química en la cama y por qué?',
      '¿Alguna vez has intentado resistirte a una tentación y luego has sucumbido estrepitosamente? ¿Con quién?',
      '¿Qué parte del cuerpo de tu pareja ideal es lo primero que miras?',
      '¿Te excita más que te miren o mirar mientras lo haces?',
      '¿Alguna vez has tenido un acuerdo de «amigos con derecho a roce» que haya salido mal? Cuéntanoslo.',
      '¿Qué es lo más romántico y lo más atrevido que te gustaría hacer en una misma noche?',
      '¿Quién de los que están en esta sala crees que está intentando ligar contigo en este momento?',
      '¿Cuál es la pregunta más íntima que te gustaría hacerle a alguien de los que están aquí esta noche?',
      '¿Qué es lo que más te apetecería hacer ahora mismo, si el juego te lo permitiera?',
    ],
    ContentTone.hot: [
      '¿Alguna vez has atado o te han atado durante el sexo?',
      '¿Alguna vez has probado el semen o la eyaculación de tu pareja?',
      '¿Te gustaría hacer un trío? ¿Con quién de los que están aquí?',
      '¿Cuál es el lugar más peligroso en el que lo has hecho?',
      '¿Cuántas veces al día te masturbas, de media?',
      '¿Cuál es la postura sexual que te permite alcanzar el orgasmo más rápido?',
      '¿Alguna vez has fingido un orgasmo? ¿Con cuántas personas?',
      '¿Qué es lo más picante que te han susurrado en la cama?',
      '¿Alguna vez has practicado sexo oral en un lugar público?',
      '¿Con quién de los aquí presentes te acostarías sin pensártelo dos veces?',
      '¿Cuál es tu juguete sexual favorito y con qué frecuencia lo usas?',
      '¿Alguna vez has tenido un orgasmo solo gracias al sexo oral?',
      '¿Te excita más dar o recibir sexo oral?',
      '¿Alguna vez has enviado un vídeo íntimo a alguien?',
      '¿Cuál es la fantasía sexual que nunca le has confesado a nadie?',
      '¿Alguna vez has tenido relaciones sexuales con más de una persona en la misma noche?',
      '¿Qué parte del cuerpo te vuelve loco cuando te la tocan?',
      '¿Alguna vez has probado el bondage o te excita la idea?',
      '¿Cuánto duró la relación sexual más larga que has tenido?',
      '¿Alguna vez te has acostado con alguien en la primera cita?',
      '¿Qué es lo más atrevido que has hecho en la cama?',
      '¿Alguna vez has besado a alguien de tu mismo sexo?',
      '¿Alguna vez te has masturbado pensando en alguien de los que están aquí?',
      '¿Cuántas parejas has tenido hasta ahora?',
      '¿Alguna vez has tenido sexo anal? ¿Te gustó?',
      '¿Cuál es tu zona erógena más secreta?',
      '¿Alguna vez has usado esposas o ataduras durante el sexo?',
      '¿Cuánto tiempo tardas normalmente en alcanzar el orgasmo?',
      '¿Alguna vez has tenido relaciones sexuales en un coche? ¿Dónde estabais aparcados?',
      '¿Quién de los aquí presentes crees que es el mejor en la cama?',
      '¿Alguna vez has probado el spanking, ya sea dándolo o recibiéndolo?',
      '¿Qué es lo más atrevido que has hecho para excitar a tu pareja?',
      '¿Alguna vez has tenido relaciones sexuales mientras había gente en la habitación de al lado?',
      '¿Te gusta el sexo a oscuras o con la luz encendida?',
      '¿Alguna vez has tenido una relación con alguien mucho mayor o mucho más joven que tú?',
      '¿Cuál es tu fetiche más peculiar?',
      '¿Alguna vez has tenido relaciones sexuales en el agua, en la piscina o en el mar?',
      '¿Cuántas veces a la semana te gustaría tener relaciones sexuales, en teoría?',
      '¿Alguna vez has probado a tener sexo con los ojos vendados?',
      '¿Con cuál de tus ex volverías a acostarte, aunque solo fuera por una noche?',
      '¿Cuál es la postura que no soportas en la cama?',
      '¿Alguna vez has tenido un orgasmo múltiple?',
      '¿Alguna vez has lamido o besado alguna parte del cuerpo poco convencional de tu pareja?',
      '¿Cuál es el pensamiento más obsceno que has tenido hoy?',
      '¿Alguna vez te has acostado con alguien cuyo nombre no recordabas?',
      '¿Te excita la idea de que te miren mientras tienes relaciones sexuales?',
      '¿Alguna vez has utilizado comida durante los preliminares? ¿Qué?',
      '¿Cuál es la fantasía que te gustaría hacer realidad con alguna de las personas aquí presentes?',
      '¿Alguna vez has tenido relaciones sexuales en casa de los padres de alguien?',
      '¿Qué importancia tiene para ti el aspecto físico de tu pareja, del uno al diez?',
      '¿Alguna vez has sentido dolor consentido durante el sexo y te ha gustado?',
      '¿Qué es lo más raro que te ha excitado?',
      '¿Alguna vez has tenido una relación con dos personas a la vez?',
      '¿Te masturbas más por la mañana o por la noche?',
      '¿Alguna vez has tenido sexo por teléfono o por videollamada?',
      '¿En qué parte de tu cuerpo te gustaría que te besaran más a menudo?',
      '¿Alguna vez has simulado una escena porno con tu pareja?',
      '¿Con quién de los aquí presentes te gustaría dar un beso con lengua?',
      '¿Alguna vez has tenido una relación solo por el sexo?',
      '¿Cuál ha sido el orgasmo que más te ha costado explicar?',
      '¿Alguna vez te has puesto lencería o ropa interior especial para seducir a alguien?',
      '¿Te gusta decir obscenidades mientras tienes relaciones sexuales o te resulta incómodo?',
      '¿Alguna vez has tenido relaciones sexuales en un baño público?',
      '¿Cuántos minutos suelen durar tus preliminares?',
      '¿Alguna vez has probado el sexo tántrico o el sexo lento y prolongado?',
      '¿Qué es lo más atrevido que has pedido en la cama?',
      '¿Alguna vez te has acostado con un compañero de trabajo o con un jefe?',
      '¿Te excita más el sexo apasionado o el tierno?',
      '¿Alguna vez has tenido una cita organizada exclusivamente por Internet con el único fin de mantener relaciones sexuales?',
      '¿Cuál es la parte de tu cuerpo de la que te sientes más orgulloso en la cama?',
      '¿Alguna vez has tenido relaciones sexuales al aire libre, en un bosque o en un parque?',
      '¿Con quién de los aquí presentes coquetearías si esta noche estuvieras soltero?',
      '¿Alguna vez has tenido más de un orgasmo en una misma relación sexual?',
      '¿Cuál es la cosa más prohibida que te gustaría probar al menos una vez?',
      '¿Alguna vez has tenido relaciones sexuales con alguien mucho más experimentado que tú?',
      '¿Te gusta que te dominen o prefieres tener el control?',
      '¿Alguna vez has tenido relaciones sexuales en la ducha o en la bañera?',
      '¿Cuál es tu récord de relaciones sexuales en un solo día?',
      '¿Alguna vez has besado a dos personas en la misma noche?',
      '¿En qué postura te sientes más sexy?',
      '¿Alguna vez has tenido relaciones sexuales mientras hablabas por teléfono con otra persona?',
      '¿Alguna vez te has excitado en un momento totalmente inoportuno?',
      '¿Alguna vez te has acostado con la persona equivocada y te has arrepentido?',
      '¿Cuál es la cosa más íntima que le has confesado solo a tu pareja?',
      '¿Alguna vez has probado a tener relaciones sexuales con un vibrador compartido?',
      '¿Con quién de los aquí presentes crees que tienes más afinidad sexual?',
      '¿Alguna vez has tenido relaciones sexuales sobre una mesa o una encimera de cocina?',
      '¿Te gusta ver vídeos picantes, ya sea solo o en pareja?',
      '¿Alguna vez has tenido relaciones sexuales en un ascensor o en un lugar insólito?',
      '¿Cuál es el cumplido más emocionante que te han hecho sobre tu cuerpo?',
      '¿Alguna vez has probado los juegos de rol en la cama? ¿Qué tipo de escenario?',
      '¿Cuántas posturas diferentes eres capaz de hacer en una sola relación sexual?',
      '¿Alguna vez has tenido un orgasmo solo con la estimulación del cuello o de las orejas?',
      '¿Qué es lo que te da ganas de tener sexo al instante?',
      '¿Alguna vez has tenido relaciones sexuales en una tienda de campaña o en un camping?',
      '¿Te has enamorado alguna vez de alguien solo por cómo era en la cama?',
      '¿Alguna vez has usado aceites o cremas durante las relaciones sexuales o los masajes?',
      '¿Quién es la persona que está aquí y con la que nunca has coqueteado, pero en la que sí has pensado?',
      '¿Alguna vez has tenido relaciones sexuales sin decir ni una palabra en todo el rato?',
      '¿Te excita más besar el cuello o los labios?',
      '¿Alguna vez has tenido relaciones sexuales en un hotel por horas?',
      '¿Qué es lo más atrevido que te ha propuesto alguna vez una pareja?',
      '¿Alguna vez has probado a estar atado de pies y manos?',
      '¿Con quién de los aquí presentes te gustaría pasar una noche de pasión?',
      '¿Alguna vez te han interrumpido el sexo justo cuando más te gustaba? ¿Quién lo hizo?',
      '¿Te gusta tener relaciones sexuales con música o en silencio absoluto?',
      '¿Alguna vez has lamido comida del cuerpo de tu pareja?',
      '¿Cuál es la fantasía que te hace alcanzar el orgasmo más rápido?',
      '¿Alguna vez te has acostado con alguien que acababas de conocer durante las vacaciones?',
      '¿Cuánto ruido haces en la cama, del uno al diez?',
      '¿Alguna vez has probado a dar unas nalgadas como parte de un juego erótico?',
      '¿Qué es lo que más te vuelve loco de los preliminares?',
      '¿Alguna vez has tenido relaciones sexuales en un lugar en el que os pudieran pillar?',
      '¿Te has masturbado alguna vez en un lugar público?',
      '¿Alguna vez has deseado que la pareja actual o la ex de un amigo estuviera presente?',
      '¿Cuál es el momento más emocionante que recuerdas con tu pareja?',
      '¿Alguna vez has probado a tener sexo con los ojos vendados y las manos atadas?',
      '¿Con qué persona famosa te acostarías sin dudarlo?',
      '¿Alguna vez has tenido relaciones sexuales más de tres veces en una noche?',
      '¿Te gusta más el sexo por la mañana o por la noche?',
      '¿Alguna vez has besado a alguien solo por una apuesta y luego te ha gustado?',
      '¿Qué es lo más erótico que has escrito en un mensaje?',
      '¿Alguna vez has tenido relaciones sexuales en casa de unos amigos durante una fiesta?',
      '¿Cuál es tu punto débil cuando alguien quiere seducirte?',
      '¿Alguna vez has probado a tener relaciones sexuales con un accesorio o un juguete nuevo?',
      '¿Con quién de los aquí presentes te imaginas pasando una noche inolvidable?',
      '¿Alguna vez has tenido relaciones sexuales en el trabajo?',
      '¿Te excita más el contacto visual o las palabras durante el sexo?',
      '¿Alguna vez has tenido una relación tan intensa que te has quedado sin fuerzas?',
      '¿Qué es lo más obsceno que has hecho para complacer a tu pareja?',
      '¿Alguna vez has tenido relaciones sexuales en la playa por la noche?',
      '¿Te gusta que te muerdan durante el sexo?',
      '¿Alguna vez has tenido un orgasmo tan intenso que casi te ha dado vergüenza?',
      '¿Qué parte del cuerpo de tu pareja besas primero?',
      '¿Alguna vez has probado a tener relaciones sexuales delante de un espejo?',
      '¿Con quién de los aquí presentes compartirías tu secreto más erótico?',
      '¿Alguna vez te has acostado con alguien a quien te habías prometido evitar?',
      '¿Te gusta tomar la iniciativa o que te seduzcan?',
      '¿Alguna vez has tenido una fantasía con alguien con quien no deberías?',
      '¿Cuál es la prenda más atrevida que te pondrías solo para una noche especial?',
      '¿Alguna vez has tenido relaciones sexuales mientras llovía, al aire libre o junto a una ventana abierta?',
      '¿Alguna vez te has excitado viendo a alguien desnudarse sin que se diera cuenta?',
      '¿Alguna vez has tenido más de una pareja en la misma semana?',
      '¿Cuál es el gesto que te hace darte cuenta al instante de que quieres a alguien en la cama?',
      '¿Alguna vez has tenido relaciones sexuales y te has reído por algo embarazoso que ha pasado?',
      '¿Con quién de los aquí presentes te gustaría jugar al juego de la seducción?',
      '¿Alguna vez has tenido relaciones sexuales pensando en otra persona que no fuera con la que estabas?',
      '¿Qué es lo más emocionante que te ha dicho alguien que quiere hacerte?',
      '¿Alguna vez has tenido una relación sexual tan silenciosa que has tenido que contener cada gemido?',
      '¿Cuál es el deseo sexual más secreto que nunca le has contado a nadie aquí?',
    ],
  };
}
