class ContentEsBluff {
  const ContentEsBluff._();

  static const List<String> bluffFakes = [
    'Dormí doce horas seguidas en un aeropuerto mientras esperaba una conexión.',
    'No aprendí a nadar hasta los dieciocho años porque le tenía miedo al agua.',
    'Perdí un vuelo intercontinental porque me quedé dormido en la puerta de embarque.',
    'De pequeño me perdí en un centro comercial durante más de una hora.',
    'Gané un concurso de baile de salón en el instituto con mi prima.',
    'Sin querer, aparecí en una foto de boda de unos completos desconocidos.',
    'Trabajé una semana como camarero y me despidieron enseguida.',
    'He cocinado para veinte personas sin haber encendido nunca antes un fogón.',
    'Aparecí en televisión durante tres segundos en un reportaje del telediario.',
    'Me encontré con un actor muy famoso en la sección de congelados del supermercado.',
    'Hice autostop durante cincuenta kilómetros en un país extranjero.',
    'Dormí en el coche durante una tormenta muy fuerte en la montaña.',
    'Me subí al tren equivocado y acabé al otro lado de Italia.',
    'Me pasé toda la Nochevieja en el hospital para acompañar a un amigo.',
    'De niño me caí de un árbol muy alto sin hacerme ni un solo rasguño.',
    'Me rompí un brazo jugando al escondite en casa.',
    'Me hice un tatuaje por impulso y al día siguiente ya me arrepentí.',
    'Me corté el pelo yo mismo y tuve que afeitarme la cabeza al cero.',
    'Me he teñido el pelo de verde fluorescente para cumplir una apuesta que perdí.',
    'Canté en el karaoke delante de cien personas que me silbaban.',
    'Toqué la guitarra en un grupo de metal durante menos de dos meses.',
    'He escrito una canción de amor que nunca le he dejado escuchar a nadie.',
    'Llevé un diario secreto durante cinco años seguidos sin saltarme ni un solo día.',
    'Me leí un libro de seiscientas páginas de un tirón en una sola noche.',
    'He visto la misma película en el cine tres veces en la misma semana.',
    'Me he aprendido de memoria un monólogo completo de tres minutos de una película.',
    'Actué en una obra del colegio y me inventé todas las frases.',
    'Canté en un coro polifónico durante todo un año.',
    'He aprendido un idioma extranjero simplemente viendo series de televisión en versión original.',
    'Hice un examen universitario sin haber estudiado y saqué un treinta.',
    'Copié en un examen importante y el profesor me pilló.',
    'Me he saltado toda una semana de colegio sin que mis padres se enteraran.',
    'Fui el último en enterarme de una noticia muy importante que afectaba a mi familia.',
    'He descubierto que tengo un primo en segundo grado que vive en Estados Unidos.',
    'He vivido en tres ciudades diferentes en tan solo dos años.',
    'Hice toda la mudanza yo solo con un coche muy pequeño.',
    'He pasado un mes entero en una casa sin televisión ni Internet.',
    'Me pasé todo el verano sin usar las redes sociales.',
    'He borrado todos mis perfiles en redes sociales durante tres meses seguidos.',
    'He perdido mi móvil nuevo en el mar mientras grababa un vídeo.',
    'Me dejé la cartera llena en un tren y me la devolvieron.',
    'Encontré cincuenta euros en la calle y se los entregué a la policía.',
    'He ganado veinte euros con un rasca y gana que compré por casualidad.',
    'Compré un boleto de lotería y lo perdí antes del sorteo.',
    'Pagué la cena a una mesa de desconocidos por un error del camarero.',
    'He pedido exactamente el mismo plato todos los días durante un mes.',
    'He comido solo pizza tanto en la comida como en la cena durante siete días seguidos.',
    'Intenté hacerme vegano y solo aguanté dos semanas.',
    'He hecho un pastel que ha quedado tan duro que es imposible comerlo.',
    'Se me ha quemado por completo una olla porque me olvidé de ella en el fuego.',
    'He activado la alarma contra incendios del hotel mientras cocinaba en la habitación.',
    'Se me ha estropeado el horno de casa justo el día antes de una cena importante.',
    'He montado un mueble enorme y al final me han sobrado diez piezas.',
    'Pinté mi habitación de un color que empecé a odiar enseguida.',
    'He dormido en un colchón hinchable en el suelo durante seis meses.',
    'He vivido con un compañero de piso con el que no he hablado ni una sola vez en todo un año.',
    'Adopté un perro por impulso mientras estaba de vacaciones en el extranjero.',
    'Le he puesto un nombre a cada una de las plantas que tengo en casa.',
    'He matado todas las plantas suculentas que me han regalado a lo largo de los años.',
    'He rescatado a un gatito que se había quedado atrapado en una rama muy alta.',
    'Me dio muchísimo miedo un perro del tamaño de un gato.',
    'He corrido una media maratón sin haber entrenado ni un solo día.',
    'Me apunté a un gimnasio caro y solo he ido tres veces.',
    'Solo he jugado un partido de fútbol en un equipo oficial.',
    'Probé a esquiar por primera vez a los treinta años y me caí enseguida.',
    'Probé el paracaidismo una vez y juré que nunca más lo volvería a hacer.',
    'Hice una inmersión y me entró el pánico a diez metros de profundidad.',
    'He escalado una pequeña montaña con un calzado inadecuado.',
    'He dormido en una tienda de campaña bajo una tormenta tremenda durante dos noches seguidas.',
    'Me fui de viaje al extranjero yo solo sin decírselo a nadie.',
    'Reservé un vuelo para el día equivocado y no llegué a viajar.',
    'Me pasé toda la noche en la estación esperando el primer tren que saliera.',
    'Conocí a mi mejor amigo mientras estábamos haciendo cola en el supermercado.',
    'Me encontré por casualidad con un antiguo compañero de clase mientras estaba en Londres.',
    'He mantenido una amistad importante durante años comunicándome únicamente por chat.',
    'Escribí una carta de amor muy larga que nunca envié.',
    'He recibido una carta anónima que me ha cambiado por completo el día.',
    'Llamé al número equivocado y me quedé hablando con esa persona durante diez minutos.',
    'Contesté una llamada importante de trabajo mientras estaba desnudo en la playa.',
    'He trabajado sin parar durante todas las vacaciones de Navidad.',
    'Dejé mi antiguo trabajo sin tener un plan B.',
    'He rechazado una oferta de trabajo con un sueldo mucho más alto.',
    'Tuve una entrevista de trabajo en un idioma que hablaba muy mal.',
    'Tomé una decisión fundamental para mi vida lanzando una moneda al aire.',
    'Me quedé profundamente dormido durante una reunión de trabajo muy importante.',
    'He enviado un correo electrónico confidencial a toda la empresa por un error técnico.',
    'Por error, llamé a mi nuevo jefe por el nombre de mi ex.',
    'He trabajado con un compañero durante meses sin llegar a saber nunca su apellido.',
    'Hice como si conociera muy bien a una persona que me saludó por la calle.',
    'Saludé con entusiasmo a un desconocido pensando que era un buen amigo mío.',
    'He reconocido a una persona solo por la voz después de diez años sin haberla oído.',
    'Se me olvidó el cumpleaños de mi madre y no me acordé hasta una semana después.',
    'Organicé una fiesta sorpresa que se descubrió el día anterior.',
    'He guardado un secreto muy importante durante más de cinco años seguidos.',
    'Les conté a mis padres una mentira que duró todo un año.',
    'Confesé mi culpa solo porque ya no podía dormir por las noches.',
    'Lloré desconsoladamente al ver un anuncio de cachorros en la tele.',
    'Me reí a carcajadas durante un funeral y no podía parar.',
    'Me quedé dormido en el cine durante el preestreno de una película que me encantaba.',
    'Aplaudí yo solo y con entusiasmo al terminar una película en el cine.',
    'Canté a todo pulmón en el coche, creyendo que estaba completamente solo.',
    'Bailé en el ascensor con un desconocido que me miraba.',
    'No me hice amigo de mi vecino hasta tres años después de mudarnos allí.',
    'He perdido todas las llaves de casa justo el día de la mudanza.',
    'Me quedé fuera de casa, en el rellano, en pijama.',
    'Me quedé atrapado en un ascensor viejo durante más de veinte minutos.',
    'Por error, me subí a una escalera mecánica muy larga en la dirección equivocada.',
    'Me equivoqué de baño en un restaurante elegante y entré en el de enfrente.',
    'Entré por error en una reunión de trabajo y me quedé allí diez minutos.',
    'Hablé por teléfono en voz alta en un tren sin darme cuenta del volumen.',
    'Le envié un mensaje de amor precisamente a la persona de la que estaba hablando mal.',
    'Hice una captura de pantalla de un chat y se la envié por error al destinatario.',
    'Por error, le he dado a «Me gusta» a una foto de hace diez años de una de mis ex.',
    'Escribí un comentario muy desagradable y lo borré al cabo de un segundo.',
    'He creado un perfil falso en las redes sociales que nunca me he atrevido a usar.',
    'Me he visto una serie de televisión completa de tres temporadas en un solo fin de semana.',
    'Me he pasado un videojuego muy difícil en una sola noche.',
    'He jugado de forma obsesiva al mismo juego en línea durante cinco años.',
    'Gané un torneo de cartas en familia haciendo trampas sin ningún pudor.',
    'Perdí una apuesta absurda y tuve que teñirme el pelo de azul.',
    'Hice una apuesta tonta que me costó una cena para ocho personas.',
    'Me comí un chile muy picante solo para ganar un reto.',
    'Me he tomado tres cafés dobles en una hora y no he pegado ojo en toda la noche.',
    'Pasé toda la noche en vela por una preocupación que al final resultó ser infundada.',
    'Tuve un sueño tan realista que, nada más despertarme, me lo creí a pies juntillas.',
    'Hablé en sueños y revelé un secreto que debía mantenerse en secreto.',
    'Cuando era niño, solía caminar sonámbulo por toda la casa.',
    'Me desperté en una parte de la casa distinta de aquella en la que me había quedado dormido.',
    'Por la tarde, me quedé profundamente dormido en un banco de un parque público.',
    'Me pasé todo el día sin dirigir la palabra a nadie.',
    'Hablé animadamente con un desconocido durante dos horas en un viaje en tren.',
    'Devolví una cartera llena de dinero que había encontrado en la calle.',
    'Gané un premio en una rifa benéfica y nunca lo he recogido.',
    'He comido exactamente lo mismo durante treinta días seguidos.',
    'Fingí hablar un idioma extranjero para que no me reconocieran durante unas vacaciones.',
    'Tuve que pedir ayuda a los vecinos porque no encontraba a mi gato.',
    'Fingí tener problemas con la línea para colgar una llamada de trabajo aburrida.',
    'Me fui del cine a mitad de la película porque me estaba aburriendo muchísimo.',
    'Saqué a pasear durante diez minutos al perro de un vecino pensando que era el mío.',
    'Saludé con muchísimo entusiasmo a una persona a la que no conocía en absoluto.',
    'Hice un recorrido turístico por mi ciudad haciéndome pasar por un turista extranjero.',
    'He enviado felicitaciones de cumpleaños a la persona equivocada durante dos años seguidos.',
    'Gané una acalorada discusión citando una estadística totalmente inventada.',
    'Mantuve el paraguas abierto durante diez minutos después de que ya hubiera salido el sol.',
    'Hice el ridículo a lo grande en una entrevista de trabajo y, aun así, me contrataron.',
    'He tenido una planta artificial en el salón durante años y la he regado con regularidad.',
    'Perdí las llaves del coche y las encontré un mes después en el congelador.',
    'Le dije «buen provecho» al camarero que me traía el plato.',
    'He corrido detrás de un autobús durante doscientos metros y he conseguido cogerlo.',
    'Había olvidado dónde había aparcado el coche y estuve dando vueltas sin sentido durante una hora.',
  ];
}
