/// Generato da tool/generate_content.dart (traduzione DeepL dai
/// pool italiani). Stesse posizioni e stesso tono degli originali IT.
class ContentEsApp {
  const ContentEsApp._();

  static const Map<String, String> ui = {
    'app.tagline':
        'El juego de mesa para quienes tienen\ncada uno su propio móvil.',
    'common.retry': 'Inténtalo de nuevo',
    'common.cancel': 'Cancelar',
    'common.continue': 'CONTINÚA',
    'common.back_home': 'VOLVER A LA PÁGINA DE INICIO',
    'common.loading': 'Un momento…',
    'common.you': 'tú',
    'onboarding.slide1.title': 'La velada da\nun giro inesperado',
    'onboarding.slide1.body':
        'Cada uno con su móvil, todos en la misma habitación. Joyo conecta las pantallas, vosotros creáis el caos.',
    'onboarding.slide2.title': 'Con el código a mano,\nentramos en materia',
    'onboarding.slide2.body':
        'Abre la sala, grita el código y mira cómo tus amigos se cuelan en ella en cuestión de segundos.',
    'onboarding.slide3.title': 'Seis juegos para\nno aburrirse nunca',
    'onboarding.slide3.body':
        'Vota a tus amigos, inventa mentiras colosales o pon a prueba tu suerte con el juego de la botella. A toda velocidad.',
    'onboarding.slide4.title': 'Tú decides\nhasta dónde atreverte',
    'onboarding.slide4.body':
        'Modo «Normal» para entrar en ambiente, «Mix» para animar la noche y «Hot» para cuando se caen las máscaras.',
    'onboarding.language': '¿En qué idioma jugáis?',
    'onboarding.start': 'EMPEZAR',
    'onboarding.skip': 'Saltar',
    'home.create': 'CREAR HABITACIÓN',
    'home.join': 'ÚNETE CON UN CÓDIGO',
    'home.games': 'Los juegos',
    'home.connection_failed':
        'No se ha podido establecer la conexión con Joyo.',
    'home.language': 'Idioma',
    'join.title_create': 'Crear habitación',
    'join.title_join': 'Únete',
    'join.name_question': '¿Cómo te llamas?',
    'join.name_hint': 'Tu nombre',
    'join.color': 'Tu color',
    'join.code': 'Código de la habitación',
    'join.cta_create': 'CREA LA HABITACIÓN',
    'join.cta_join': 'ENTRA',
    'join.error_name': 'Escribe tu nombre.',
    'join.error_code': 'El código tiene 6 caracteres.',
    'error.room_not_found': 'No hay ninguna habitación con este código.',
    'error.room_full': 'La sala está llena: máximo 10 jugadores.',
    'error.room_finished': 'Este partido ya ha terminado.',
    'error.connection':
        'Se ha perdido la conexión. Vuelve a abrir la aplicación e inténtalo de nuevo.',
    'lobby.title': 'Vestíbulo',
    'lobby.code_label': 'CÓDIGO DE HABITACIÓN',
    'lobby.code_hint': 'Dilo en voz alta · toca para copiar',
    'lobby.code_copied': 'Código copiado',
    'lobby.players': 'Jugadores',
    'lobby.you': 'tú',
    'lobby.host_badge': 'ANFITRIÓN',
    'lobby.pick_game': 'ELIGE EL JUEGO',
    'lobby.waiting_host': 'El anfitrión está eligiendo el juego…',
    'lobby.which_game': '¿A qué jugamos?',
    'lobby.remove_player': '¿Quieres eliminar {name}?',
    'lobby.remove_player_body':
        'Úsalo si alguien ha cerrado la aplicación sin salir. Siempre podrá volver a entrar con el código.',
    'lobby.remove': 'Eliminar',
    'lobby.exit_host_title': '¿Cerrar la habitación?',
    'lobby.exit_host_body':
        'La sala se cierra para todos: los demás jugadores vuelven a la página de inicio.',
    'lobby.exit_title': '¿Salir de la habitación?',
    'lobby.exit_body': 'Los demás jugadores te verán salir.',
    'lobby.stay': 'Queda',
    'lobby.close': 'Cerrar',
    'lobby.leave': 'Salir',
    'lobby.exit_failed': 'Error al salir: {detail}',
    'lobby.room_closed': 'El anfitrión ha cerrado la habitación.',
    'lobby.reconnecting': 'Reconexión…',
    'lobby.entering': 'Entro en la habitación…',
    'mode.title': 'Modalidades',
    'mode.normale': 'Normal',
    'mode.mix': 'Mix',
    'mode.hot': 'De moda',
    'mode.normale.desc':
        'Perfecta para romper el hielo sin demasiados problemas.',
    'mode.mix.desc':
        'La situación cambia constantemente y el ritmo se acelera. Agárrense fuerte.',
    'mode.hot.desc':
        'Sin límites. Solo para jugar si estáis preparados para todo.',
    'settings.rounds': 'Rondas por partido',
    'game.round_of': 'Ronda {n} de {total}',
    'game.preparing': 'Voy a preparar el asalto…',
    'game.create_failed': 'No consigo crear la ronda: {detail}',
    'game.close_failed': 'No consigo cerrar la ronda: {detail}',
    'game.vote_failed': 'Respuesta no registrada: {detail}',
    'game.next_round': 'PRÓXIMA RONDA',
    'game.see_podium': 'VER EL PODIO',
    'game.waiting_next':
        'El presentador está a punto de dar inicio a la siguiente ronda…',
    'game.finished': 'El partido ha terminado',
    'game.answered': 'Han respondido {n} de un total de {total}',
    'game.back_to_lobby': 'VOLVER AL VESTÍBULO',
    'game.lobby_short': 'LOBBY',
    'game.host_only':
        'El anfitrión puede reiniciar la partida desde la sala de espera.',
    'game.coming_soon': 'Próximamente',
    'podium.title': 'Fin del partido',
    'podium.winner': 'Gana {name}',
    'podium.no_scores':
        'En este juego no se otorgan puntos: no hay clasificación, solo el partido.',
    'podium.points': '{n} puntos',
    'podium.points_one': '{n} punto',
    'preferisci.name': '¿Qué prefieres?',
    'preferisci.tagline': 'Decisiones atroces: ¿quién piensa como tú?',
    'preferisci.prompt': '¿Prefieres…',
    'preferisci.or': 'o bien',
    'preferisci.split': 'El grupo se dividió de la siguiente manera:',
    'preferisci.no_votes': 'Nadie ha respondido',
    'non_ho_mai.name': 'Nunca he',
    'non_ho_mai.tagline':
        'El confesionario está abierto. Confiesa y sobrevive.',
    'non_ho_mai.prompt': 'Nunca he…',
    'non_ho_mai.done': 'LO HE HECHO',
    'non_ho_mai.never': 'NUNCA',
    'non_ho_mai.anonymous':
        'Nadie verá lo que has respondido: solo se ve el recuento.',
    'non_ho_mai.nobody': 'Nadie lo ha hecho',
    'non_ho_mai.count': '{n} de {total}',
    'non_ho_mai.guess_who': 'Ahora os toca a vosotros averiguar quién',
    'chi.name': '¿Quién podría hacerlo?',
    'chi.tagline': 'El juego en el que se señala con el dedo (literalmente).',
    'chi.decided': 'El grupo ha decidido',
    'chi.tie': 'Empate',
    'chi.no_votes': 'Sin valoraciones',
    'obbligo.name': 'Verdad o reto',
    'obbligo.tagline': 'La botella decide, tú sudas. No hay excusas.',
    'obbligo.spinning': 'La botella gira…',
    'obbligo.your_turn': 'Ahora te toca a ti',
    'obbligo.turn_of': 'Le toca a {name}',
    'obbligo.choosing': 'Está eligiendo…',
    'obbligo.dare': 'OBLIGACIÓN',
    'obbligo.truth': 'VERDAD',
    'obbligo.no_choice': '{name} no ha elegido a tiempo',
    'obbligo.when_done':
        'Cuando termine, el anfitrión propone la siguiente ronda',
    'bluff.name': 'La historia del farol',
    'bluff.tagline': 'Mentir es un arte. ¿Eres capaz de que no te pillen?',
    'bluff.writing': '{name} está escribiendo\nun hecho real sobre sí mismo',
    'bluff.your_turn_body':
        'Escribe un dato real sobre ti. El juego nos presentará dos mentiras: los demás tendrán que adivinar cuál es el tuyo.',
    'bluff.hint': 'Escribe aquí…',
    'bluff.send': 'ENVÍA TU VERDAD',
    'bluff.too_short': 'Escribe algo un poco más largo.',
    'bluff.which_true': '¿Cuál es la verdad sobre {name}?',
    'bluff.in_play': 'Tu historia está en juego',
    'bluff.dont_tell': 'No te pierdas cuál es la auténtica.',
    'bluff.your_truth': 'tu verdad',
    'bluff.true_label': 'verdadera',
    'bluff.truth_of': 'La verdad de {name}',
    'bluff.nobody_guessed':
        'Nadie lo ha adivinado: {name} os ha engañado a todos',
    'bluff.guessed': '{n} han acertado',
    'bluff.guessed_one': '{n} lo ha acertado',
    'bluff.scoring':
        '+2 para quien haya acertado · +1 para {name} por cada farol que haya salido bien',
    'bluff.ai_working': 'Me estoy inventando dos mentiras…',
    'bluff.ai_working_sub': 'hecho a medida para la historia de {name}',
    'impostore.name': 'Impostor',
    'impostore.tagline':
        'Hay un intruso entre nosotros. Encuéntralo antes de que sea demasiado tarde.',
    'impostore.only_you': 'Solo tú ves esto',
    'impostore.you_are': 'Tú eres el impostor',
    'impostore.you_are_body':
        'No sabes cuál es la palabra. Escucha, improvisa y no dejes que te descubran: si adivinas la palabra al final, recuperarás puntos.',
    'impostore.the_word': 'La palabra es',
    'impostore.one_doesnt': 'Uno de vosotros no la conoce.',
    'impostore.round_of_words': 'Juego de palabras',
    'impostore.round_of_words_body':
        'Por turnos, cada uno dice una sola palabra relacionada con el secreto.\nSi es demasiado concreta, el impostor lo adivina; si es demasiado vaga, parecerá que vosotros sois el impostor.',
    'impostore.your_word': 'Tu palabra: {word}',
    'impostore.to_vote': 'PASA A LA VOTACIÓN',
    'impostore.who': '¿Quién es el impostor?',
    'impostore.guess_hint': 'La palabra secreta era…',
    'impostore.guess_body':
        'Tú eres el impostor: intenta adivinar la palabra. Si te descubren pero aciertas, recuperas puntos.',
    'impostore.confirm': 'CONFIRMACIÓN',
    'impostore.vote_registered': 'Voto registrado',
    'impostore.caught': 'Un impostor desenmascarado',
    'impostore.escaped': 'El impostor se ha salido con la suya',
    'impostore.word_was': 'La palabra era',
    'impostore.guessed_it': 'Ha acertado: «{guess}» · +3 puntos',
    'impostore.said': 'Había dicho: «{guess}»',
    'impostore.points_caught': '+2 para quien haya votado al impostor',
    'impostore.points_escaped': '+5 para el impostor',
    'impostore.votes': '{n} votos',
    'impostore.votes_one': '{n} voto',
    'premium.title': 'Contenidos a medida',
    'premium.body':
        'En «¿Quién podría hacerlo?» y «Bluff Story», las frases se escriben en vuestro grupo en lugar de sacarlas de una lista.',
    'premium.active': 'IA activa en esta habitación',
    'premium.active_body':
        'Preguntas y mentiras que se han generado en vuestro grupo',
    'premium.unlock': 'DESBLOQUEAR',
    'premium.watch_ad': 'ANUNCIO',
    'premium.host_only': 'El anfitrión puede desbloquearla.',
    'premium.credits': '{n} créditos',
    'premium.unlocked': 'IA desbloqueada para esta sala',
    'premium.ad_reward': 'Has ganado un contenido generado por IA',
    'premium.ad_incomplete': 'Anuncio no completado.',
    'premium.no_store':
        'Las compras no están disponibles aquí: hay que utilizar Google Play o la App Store.',
    'premium.ads_mobile_only': 'Los anuncios solo funcionan en el móvil.',
  };
}
