class ContentEsApp {
  const ContentEsApp._();

  static const Map<String, String> ui = {
    'app.tagline':
        'El juego de fiesta donde\ntodos están conectados.',
    'common.retry': 'REINTENTAR',
    'common.cancel': 'CANCELAR',
    'common.continue': 'CONTINUAR',
    'common.back_home': 'VOLVER A INICIO',
    'common.loading': 'Un momento…',
    'common.you': 'tú',
    'onboarding.slide1.title': 'La noche está a punto de\ncambiar de ritmo',
    'onboarding.slide1.body':
        'Cada uno usa su propio móvil, pero todos jugáis juntos. Joyo lo pone todo en común y vosotros hacéis el resto.',
    'onboarding.slide2.title': 'Un código y estáis dentro',
    'onboarding.slide2.body':
        'Crea una sala, comparte el código y haz entrar a tus amigos. En pocos segundos estaréis listos.',
    'onboarding.slide3.title': 'Seis juegos.\nInfinitas posibilidades.',
    'onboarding.slide3.body':
        '¿Qué prefieres?, Nunca he, ¿Quién podría hacerlo?, Verdad o reto, Bluff Story e Impostor. Elegid vuestro juego y empezad.',
    'onboarding.slide4.title': 'Tú eliges\nel nivel de juego',
    'onboarding.slide4.body':
        'Normal para empezar, Mix para cambiar el ritmo, Hot cuando queráis hacer la noche más interesante.',
    'onboarding.language': '¿En qué idioma jugáis?',
    'onboarding.start': 'EMPEZAR',
    'onboarding.skip': 'SALTAR',
    'home.create': 'CREAR SALA',
    'home.join': 'ENTRAR CON UN CÓDIGO',
    'home.games': 'Los juegos',
    'home.connection_failed': 'No se ha podido conectar con Joyo.',
    'home.language': 'Idioma',
    'join.title_create': 'Crear una sala',
    'join.title_join': 'Entrar en la sala',
    'join.name_question': '¿Cómo te llamas?',
    'join.name_hint': 'Introduce tu nombre',
    'join.color': 'Elige tu color',
    'join.avatar': 'Elige tu avatar',
    'join.error_avatar': 'Elige un avatar.',
    'join.code': 'Código de la sala',
    'join.cta_create': 'CREAR LA SALA',
    'join.cta_join': 'ENTRAR',
    'join.error_name': 'Introduce tu nombre.',
    'join.error_code': 'El código debe tener 6 caracteres.',
    'error.room_not_found': 'No encontramos ninguna sala con este código.',
    'error.room_full': 'La sala está llena. Máximo 10 jugadores.',
    'error.room_finished': 'Esta partida ya ha terminado.',
    'error.connection':
        'Conexión perdida. Comprueba tu conexión y vuelve a intentarlo.',
    'lobby.title': 'Sala',
    'lobby.code_label': 'CÓDIGO DE LA SALA',
    'lobby.code_hint': 'Compártelo con tus amigos · toca para copiarlo',
    'lobby.code_copied': 'Código copiado',
    'lobby.players': 'Jugadores',
    'lobby.you': 'tú',
    'lobby.host_badge': 'ANFITRIÓN',
    'lobby.pick_game': 'ELIGE EL JUEGO',
    'lobby.waiting_host': 'El anfitrión está eligiendo el juego…',
    'lobby.which_game': '¿A qué jugamos?',
    'lobby.remove_player': '¿Eliminar a {name}?',
    'lobby.remove_player_body':
        'Úsalo si alguien ha cerrado la aplicación sin salir. Podrá volver a entrar con el mismo código.',
    'lobby.remove': 'ELIMINAR',
    'lobby.exit_host_title': '¿Cerrar la sala?',
    'lobby.exit_host_body':
        'La sala se cerrará para todos y los demás jugadores volverán a la pantalla de inicio.',
    'lobby.exit_title': '¿Salir de la sala?',
    'lobby.exit_body':
        'Estás a punto de salir de la sala. Los demás jugadores lo verán.',
    'lobby.stay': 'QUEDARSE',
    'lobby.close': 'CERRAR',
    'lobby.leave': 'SALIR',
    'lobby.exit_failed': 'No se ha podido salir: {detail}',
    'lobby.room_closed': 'El anfitrión ha cerrado la sala.',
    'lobby.reconnecting': 'Reconectando…',
    'lobby.entering': 'Entrando en la sala…',
    'mode.title': 'Modos',
    'mode.normale': 'Normal',
    'mode.mix': 'Mix',
    'mode.hot': 'Hot',
    'mode.normale.desc':
        'Las reglas básicas. La forma más sencilla de empezar.',
    'mode.mix.desc': 'Más variedad, más ritmo y alguna sorpresa más.',
    'mode.hot.desc': 'Más directo, más personal. Solo si estáis preparados.',
    'age.title': 'Contenido para adultos',
    'age.body':
        'Los modos Mix y Hot contienen contenido explícito para mayores de edad. ¿Confirmas que todos los jugadores tienen al menos 18 años?',
    'age.confirm': 'CONFIRMO',
    'settings.rounds': 'Rondas por partida',
    'game.round_of': 'Ronda {n} de {total}',
    'game.preparing': 'Preparando la ronda…',
    'game.create_failed': 'No se ha podido crear la ronda: {detail}',
    'game.close_failed': 'No se ha podido cerrar la ronda: {detail}',
    'game.vote_failed': 'Respuesta no registrada: {detail}',
    'game.next_round': 'SIGUIENTE RONDA',
    'game.see_podium': 'VER EL PODIO',
    'game.waiting_next':
        'El anfitrión está a punto de iniciar la siguiente ronda…',
    'game.finished': 'Partida terminada',
    'game.answered': 'Han respondido {n} de {total}',
    'game.back_to_lobby': 'VOLVER A LA SALA',
    'game.lobby_short': 'SALA',
    'game.host_only':
        'Solo el anfitrión puede reiniciar el juego desde la sala.',
    'game.coming_soon': 'Próximamente',
    'podium.title': 'Fin de la partida',
    'podium.winner': 'Gana {name}',
    'podium.no_scores':
        'Este juego no otorga puntos. Aquí lo importante es jugar.',
    'podium.points': '{n} puntos',
    'podium.points_one': '{n} punto',
    'preferisci.name': '¿Qué prefieres?',
    'preferisci.tagline': 'Dos opciones. Una respuesta. ¿Cuál eliges?',
    'preferisci.prompt': '¿Qué prefieres…',
    'preferisci.or': 'o',
    'preferisci.split': 'El grupo ha elegido así',
    'preferisci.no_votes': 'Nadie ha respondido',
    'non_ho_mai.name': 'Nunca he',
    'non_ho_mai.tagline': '¿Ha pasado o no? Ahora lo descubrimos.',
    'non_ho_mai.prompt': 'Nunca he…',
    'non_ho_mai.done': 'LO HE HECHO',
    'non_ho_mai.never': 'NUNCA',
    'non_ho_mai.anonymous':
        'Las respuestas son anónimas. Solo se muestra el total.',
    'non_ho_mai.nobody': 'Nadie lo ha hecho',
    'non_ho_mai.count': '{n} de {total}',
    'non_ho_mai.guess_who': 'Ahora intentad descubrir quién lo ha hecho',
    'chi.name': '¿Quién podría hacerlo?',
    'chi.tagline': 'Una pregunta. Un nombre. Vosotros decidís.',
    'chi.decided': 'El grupo ha decidido',
    'chi.tie': 'Empate',
    'chi.no_votes': 'Sin votos',
    'obbligo.name': 'Verdad o reto',
    'obbligo.tagline': 'La decisión ya no está en tus manos.',
    'obbligo.spinning': 'La botella gira…',
    'obbligo.your_turn': 'Te toca a ti',
    'obbligo.turn_of': 'Le toca a {name}',
    'obbligo.choosing': 'Está eligiendo…',
    'obbligo.dare': 'RETO',
    'obbligo.truth': 'VERDAD',
    'obbligo.no_choice': '{name} no ha elegido a tiempo',
    'obbligo.when_done':
        'Cuando termine, el anfitrión puede iniciar la siguiente ronda',
    'bluff.name': 'Bluff Story',
    'bluff.tagline': 'Una verdad. Dos mentiras. ¿Conseguirás engañarlos?',
    'bluff.writing': '{name} está escribiendo\nuna verdad sobre sí mismo',
    'bluff.your_turn_body':
        'Escribe una verdad sobre ti. Nosotros añadiremos dos mentiras. Los demás tendrán que descubrir cuál es la verdadera.',
    'bluff.hint': 'Escribe tu verdad…',
    'bluff.send': 'ENVÍA TU VERDAD',
    'bluff.too_short': 'Escribe al menos 30 caracteres.',
    'bluff.which_true': '¿Cuál es la verdad de {name}?',
    'bluff.in_play': 'Tu historia está en juego',
    'bluff.dont_tell': 'No dejes que los demás descubran cuál es la verdadera.',
    'bluff.your_truth': 'tu verdad',
    'bluff.true_label': 'verdadera',
    'bluff.truth_of': 'La verdad de {name}',
    'bluff.nobody_guessed':
        'Nadie lo ha adivinado. {name} os ha engañado a todos.',
    'bluff.guessed': '{n} han acertado',
    'bluff.guessed_one': '{n} ha acertado',
    'bluff.scoring':
        '+2 para quien acierte · +1 para {name} por cada farol conseguido',
    'bluff.multilang_title': 'Idiomas distintos en la mesa',
    'bluff.multilang_body':
        'Vuestro grupo juega en idiomas distintos: las mentiras salen '
        'traducidas, pero la frase verdadera queda en el idioma de quien la '
        'escribe y puede delatarse al instante.',
    'impostore.name': 'Impostor',
    'impostore.tagline': 'Uno de vosotros juega con información diferente.',
    'impostore.only_you': 'Solo tú puedes verlo',
    'impostore.you_are': 'Tú eres el impostor',
    'impostore.you_are_body':
        'No conoces la palabra. Escucha a los demás, improvisa y no dejes que te descubran. Si te desenmascaran pero adivinas la palabra, recuperas puntos.',
    'impostore.the_word': 'La palabra secreta es',
    'impostore.one_doesnt': 'Uno de vosotros no conoce la palabra.',
    'impostore.round_of_words': 'Ronda de palabras',
    'impostore.round_of_words_body':
        'Por turnos, cada uno dice una sola palabra relacionada con el secreto.\nSi es demasiado concreta, ayudas al impostor. Si es demasiado vaga, parecerás tú el impostor.',
    'impostore.your_word': 'Tu palabra: {word}',
    'impostore.to_vote': 'PASAR A LA VOTACIÓN',
    'impostore.who': '¿Quién es el impostor?',
    'impostore.guess_hint': 'La palabra secreta era…',
    'impostore.guess_body':
        'Tú eres el impostor. Intenta adivinar la palabra: si te descubren pero aciertas, recuperas puntos.',
    'impostore.confirm': 'CONFIRMAR',
    'impostore.vote_registered': 'Voto registrado',
    'impostore.caught': 'Impostor descubierto',
    'impostore.escaped': 'El impostor ha escapado',
    'impostore.word_was': 'La palabra era',
    'impostore.guessed_it': 'Ha acertado: «{guess}» · +3 puntos',
    'impostore.said': 'Había dicho: «{guess}»',
    'impostore.points_caught': '+2 para quien haya votado al impostor',
    'impostore.points_escaped': '+5 para el impostor',
    'impostore.votes': '{n} votos',
    'impostore.votes_one': '{n} voto',
    'premium.title': 'Contenido personalizado',
    'premium.body':
        'En «¿Quién podría hacerlo?» y «Bluff Story», la IA crea contenido pensado para vuestro grupo en lugar de usar frases predeterminadas.',
    'premium.active': 'IA activa en esta sala',
    'premium.active_body': 'Contenido generado para vuestro grupo',
    'premium.unlock': 'DESBLOQUEAR',
    'premium.watch_ad': 'VER ANUNCIO',
    'premium.host_only': 'Solo el anfitrión puede desbloquearla.',
    'premium.credits': '{n} créditos',
    'premium.unlocked': 'IA desbloqueada para esta sala',
    'premium.ad_reward': 'Has obtenido contenido generado por IA',
    'premium.ad_incomplete': 'Anuncio no completado.',
    'premium.ad_limit': 'Límite de anuncios alcanzado por hoy. ¡Vuelve mañana!',
    'premium.bank_full':
        'Ya tienes el máximo de partidas premium: juega esas antes de ganar más.',
    'premium.no_store':
        'Las compras no están disponibles aquí. Usa Google Play o App Store.',
    'premium.ads_mobile_only':
        'Los anuncios solo están disponibles en el móvil.',

    'shop.badge': 'Premium',
    'shop.title': 'Desbloquea Mix y Hot',
    'shop.body':
        'Mix y Hot son modos premium. Mira 3 anuncios para desbloquearlos durante una partida.',
    'shop.progress': '{n}/3 anuncios',
    'shop.watch': 'VER UN ANUNCIO',
    'shop.unlocked': 'Mix y Hot desbloqueados para una partida',
    'shop.host_only': 'Solo el anfitrión puede desbloquearlos.',
    'shop.go_premium': 'O pásate a Premium',
    'shop.page_title': 'Tienda',
    'shop.free_title': 'Desbloquea con anuncios',
    'shop.in_room_only': 'Disponible en una sala, como anfitrión.',
    'shop.games': '{n} partidas premium listas',
    'endgame.promo': '¿Quieres más chispa y menos anuncios?',
    'endgame.shop_cta': 'DESCUBRE PREMIUM',

    'paywall.title': 'Pásate a Premium',
    'paywall.no_ads_name': 'Sin anuncios',
    'paywall.no_ads_desc': 'Juega sin anuncios.',
    'paywall.premium_name': 'Premium',
    'paywall.premium_desc': 'Mix, Hot, partidas más largas y sin anuncios.',
    'paywall.best_value': 'El más elegido',
    'paywall.feat_modes': 'Modos Mix y Hot',
    'paywall.feat_rounds': 'Partidas más largas',
    'paywall.per_month': '/mes',
    'paywall.active': 'Activo',
    'paywall.subscribe': 'SUSCRIBIRSE',
    'paywall.restore': 'Restaurar compras',
    'shop.privacy': 'Política de privacidad',
    'shop.ad_privacy': 'Opciones de privacidad de anuncios',
    'paywall.restored': 'Suscripción restaurada',
    'paywall.nothing_restored': 'No hay suscripción que restaurar',
    'paywall.terms': 'Términos de uso',

    'settings.title': 'Ajustes',
    'settings.notifications': 'Notificaciones',
    'settings.notifications_desc': 'Recordatorios y novedades',
    'notif.comeback_1_title': 'Tus amigos te esperan 🎉',
    'notif.comeback_1_body': '¿Cuánto sin jugar juntos? ¡Abre Joyo!',
    'notif.comeback_2_title': 'Te echamos de menos 👀',
    'notif.comeback_2_body': 'El grupo no es lo mismo sin ti.',
    'notif.comeback_3_title': 'La silla vacía eres tú 🃏',
    'notif.comeback_3_body': 'Vuelve a la mesa, ¡empezamos!',
    'notif.comeback_4_title': '¿Revancha? 🏆',
    'notif.comeback_4_body': 'La última partida se te atragantó. Vuelve a ganar.',
    'notif.comeback_5_title': '¿Quién manda esta noche? 🔥',
    'notif.comeback_5_body': 'Abre Joyo y descúbrelo con un nuevo reto.',
    'notif.comeback_6_title': '¿Listo para resarcirte? 🎯',
    'notif.comeback_6_body': 'Una partida rápida y quedas en paz.',
    'notif.comeback_7_title': '¿Noche de Joyo? 🌙',
    'notif.comeback_7_body': 'Reúne al grupo, bastan 5 minutos.',
    'notif.comeback_8_title': 'Solo falta el juego 🍕',
    'notif.comeback_8_body': 'Amigos, sofá, Joyo. ¿Empezamos?',
    'settings.manage_sub': 'Gestionar suscripción',
    'settings.manage_sub_desc': 'Renovar, cambiar o cancelar',
    'settings.restore': 'Restaurar compras',
    'settings.rate': 'Valora la app',
    'settings.rate_desc': 'Déjanos una reseña',
    'settings.contact': 'Contáctanos',
    'settings.contact_desc': 'Escríbenos para ayuda o comentarios',
    'settings.coming_soon': 'Próximamente',
  };
}
