import '../content_tone.dart';

/// Generato da tool/generate_content.dart (traduzione DeepL dai
/// pool italiani). Stesse posizioni e stesso tono degli originali IT.
class ContentEnPreferisci {
  const ContentEnPreferisci._();

  static const List<({String a, String b})> preferisciPairs = [
    (a: 'Knowing How You\'ll Die', b: 'Knowing when'),
    (a: 'An Uncomfortable Truth', b: 'A Convenient Lie'),
    (a: 'More money', b: 'More free time'),
    (a: 'Being Famous', b: 'To be invisible to others'),
    (a: 'Traveling Back in Time', b: 'Traveling into the Future'),
    (a: 'Mind Reading', b: 'Predicting the Future'),
    (a: 'No More Social Media', b: 'No More Movies'),
    (a: 'Losing Your Phone', b: 'Losing Your House Keys'),
    (a: 'Always 5 minutes early', b: 'Always 10 minutes late'),
    (a: 'A likable but incompetent boss', b: 'An unlikable but competent boss'),
    (a: 'High salary and a boring job', b: 'A low salary and a job you love'),
    (a: 'Wedding with 200 guests', b: 'A Wedding for Two'),
    (a: 'A week without going out', b: 'Going out every night'),
    (a: 'Sleep 10 hours', b: 'Sleep 5 hours and feel great'),
    (a: 'Reliving the Perfect Vacation', b: 'Try a new place'),
    (a: 'Check your account every day', b: 'Never look at it'),
    (a: 'A useless but fun superpower', b: 'A Useful but Boring Superpower'),
    (a: 'Rereading the Same Book Over and Over Again', b: 'Never finish one'),
    (a: 'Always Knowing the Truth', b: 'Living Happily in an Illusion'),
    (a: 'A sabbatical year', b: 'Retiring a year early'),
    (a: 'Speaking All Languages', b: 'Play all the instruments'),
    (a: 'Never feel embarrassed', b: 'Never be afraid'),
    (a: 'Relive Your Best Day', b: 'Delete the worst one'),
    (
      a: 'Living Together After a Month',
      b: 'Living Together After All These Years',
    ),
    (
      a: 'A vacation planned down to the last detail',
      b: 'Set Off on an Adventure',
    ),
    (a: 'An Entire Season in One Night', b: 'One episode per week'),
    (a: 'Battery Always at 1%', b: 'Very slow Internet'),
    (
      a: 'Clothes that are always a little damp',
      b: 'A pebble in my shoe forever',
    ),
    (a: 'Always Say What You Think', b: 'No longer being able to speak'),
    (a: 'No heating in the winter', b: 'No air conditioning in the summer'),
    (a: 'Favorite dish at every meal', b: 'Never again your favorite dish'),
    (a: 'No more need to sleep', b: 'No more need to eat'),
    (a: 'Rich but without friends', b: 'Penniless but Beloved'),
    (a: 'No More Rent to Pay', b: 'Salary Doubled'),
    (a: 'The nicest person in the room', b: 'The smartest person in the room'),
    (a: 'Photographic Memory', b: 'Forget all the embarrassing moments'),
    (a: 'No More Lines', b: 'No More Traffic'),
    (a: 'Shaved Eyebrows for a Year', b: 'Neon-green hair for a year'),
    (a: 'Losing one\'s sense of smell', b: 'Losing Your Sense of Taste'),
    (a: 'Cartoon voice', b: 'A laugh that makes everyone feel awkward'),
    (a: 'Timeline visible to parents', b: 'Chats Read by Your Boss'),
    (a: 'Burp at the end of every sentence', b: 'To laugh like a goat'),
    (
      a: 'Using a stranger\'s toothbrush',
      b: 'Drinking from his glass that\'s already been used',
    ),
    (a: 'Going out with your ex', b: 'With your best friend\'s ex'),
    (a: 'Loud but odorless farts', b: 'Silent but deadly'),
    (a: 'Forget Who You Are', b: 'To be forgotten by everyone'),
    (a: 'To lose all your money', b: 'Losing All Your Memories'),
    (a: 'A Rich but Boring Partner', b: 'A broke but incredibly funny partner'),
    (
      a: 'An hour in an elevator with your ex',
      b: 'An hour in the elevator with the boss',
    ),
    (a: 'A Birthday Everyone Forgot', b: 'An Awkward Surprise Party'),
    (a: 'Your secret revealed to everyone', b: 'Knowing everyone\'s secrets'),
    (a: 'Famous but hated', b: 'Unknown but Beloved'),
    (a: 'Never Laugh Again', b: 'Never Cry Again'),
    (
      a: 'Going Back to High School for a Year',
      b: 'Taking the high school graduation exam every year',
    ),
    (a: 'Living in a Horror Movie', b: 'Living in a Musical'),
    (
      a: 'Taking on a duck as big as a horse',
      b: 'One hundred horses as big as ducks',
    ),
    (a: 'Living Underwater', b: 'Living in Space'),
    (
      a: 'Chased for the rest of his life by a killer snail',
      b: 'A clown who stares at you every night',
    ),
    (a: 'Talking to Animals', b: 'Check the weather'),
    (a: 'Dance as soon as the music starts', b: 'Crying When Someone Laughs'),
    (a: 'Every morning in a different town', b: 'Never Leave Your City Again'),
    (a: 'Living in a Video Game', b: 'Living in a Cartoon'),
    (a: 'A "Pause" Button for Life', b: 'A "rewind" button for life'),
    (
      a: 'Teleportation, but you always lose your shoes',
      b: 'Flying at a snail\'s pace',
    ),
    (a: 'Living 1,000 Years', b: 'Ten Lives, Each 100 Years Long'),
    (a: 'King of the World for a Day', b: 'A Normal Person Forever'),
    (
      a: 'Knowing everything but feeling nothing',
      b: 'Try everything but understand nothing',
    ),
    (a: 'Erase a Regret', b: 'Ensuring Your Future Success'),
    (
      a: 'A tail that wags when you\'re happy',
      b: 'Ears that droop when you\'re sad',
    ),
    (a: 'Giving Up Coffee for Good', b: 'Giving Up Chocolate'),
    (
      a: 'A nose that grows when you lie',
      b: 'Hair That Changes Color Depending on Your Mood',
    ),
    (a: 'Finding the Love of Your Life', b: 'Finding Your Dream Job'),
    (a: 'Extremely wealthy but always sad', b: 'Broke but Still Happy'),
    (a: 'One million right away', b: '3,000 euros a month for life'),
    (a: 'Save Your Dog', b: 'Saving a Stranger'),
    (a: 'Never Being Able to Lie', b: 'Believing Every Lie'),
    (
      a: 'Always being right, but all by yourself',
      b: 'Making Mistakes, but in Good Company',
    ),
    (a: 'A Misunderstood Genius', b: 'Happy Simpleton'),
    (a: 'The Same Outfit Every Day', b: 'Never wear the same outfit twice'),
    (a: 'Sing Everything You Say', b: 'Walking Only Backward'),
    (a: 'Free Wi-Fi Everywhere for Life', b: 'Free Flights for Life'),
    (a: 'Eating only piping hot food', b: 'Only frozen food'),
    (a: 'No More Aperitifs', b: 'No More Food Delivery'),
    (a: 'A long life full of regrets', b: 'A Short Life Without Regrets'),
    (
      a: 'To love without being loved in return',
      b: 'Being loved by someone you don\'t love',
    ),
    (a: 'Your partner can read your mind', b: 'You read his'),
    (
      a: 'A partner chosen by your friends',
      b: 'A partner selected by an algorithm',
    ),
    (
      a: 'Always Know Who\'s Lying to You',
      b: 'Never let anyone catch you lying',
    ),
    (a: 'Relive Your 18th Birthday Forever', b: 'Skip directly to 40'),
    (
      a: 'Always sleeping at other people\'s houses',
      b: 'Always Having Guests in Your Home',
    ),
    (
      a: 'A concert by your favorite band—all by yourself',
      b: 'A festival with friends, but music you hate',
    ),
    (
      a: 'Singing karaoke off-key in front of everyone',
      b: 'Dancing alone on the dance floor for an hour',
    ),
    (a: 'Losing all the photos on your phone', b: 'Delete All Chats'),
    (a: 'To be 2 meters 20 tall', b: 'To be 1.20 meters tall'),
    (a: 'Living Without Summer', b: 'Living Without Winter'),
    (a: 'Save Five Strangers', b: 'Save Your Best Friend'),
    (
      a: 'One million, but no more smartphones',
      b: 'No money, but with a phone',
    ),
    (a: 'Dream Job Abroad', b: 'A boring job near my friends'),
    (a: 'To Be 25 Forever', b: 'Growing Old with Your Friends'),
    (
      a: 'A dream home in the middle of nowhere',
      b: 'Studio Apartment in the Heart of Downtown',
    ),
    (
      a: 'Knowing what people say about you behind your back',
      b: 'Living peacefully without realizing it',
    ),
    (a: 'Every meal prepared by a chef', b: 'Personal Driver for Life'),
    (
      a: 'Comment aloud on everything you do',
      b: 'Hear the Narrator\'s Voice of Your Life',
    ),
    (
      a: 'A mosquito in my bedroom every night',
      b: 'A fly on the plate at every meal',
    ),
    (a: 'Autocorrect Gone Wild Forever', b: 'No More Emojis'),
    (a: 'Calls on speakerphone only', b: 'Screen Always Visible to Everyone'),
    (
      a: 'Your dog talks, but he criticizes you',
      b: 'Your mirror gives you false compliments',
    ),
    (a: 'A million just for you', b: 'One hundred thousand each for the group'),
    (a: 'Always Being Underestimated', b: 'Always Being Overrated'),
    (
      a: 'Rediscover Your Favorite Show from Scratch',
      b: 'Get a sneak peek at every finale',
    ),
    (a: 'Speaking Only by Yelling', b: 'Speak only in a whisper'),
    (
      a: 'Always laugh during serious moments',
      b: 'Crying at Every Comedy Movie',
    ),
    (a: 'Always eat with your hands', b: 'Eating Everything with a Teaspoon'),
    (a: 'Your Dreams Shared with Friends', b: 'Your friends read your diary'),
    (
      a: 'The only single person in the group forever',
      b: 'The first in the group to get married',
    ),
    (a: 'A Rebirth in the 1980s', b: 'Being Born in 2050'),
    (
      a: 'Free meals, but always alone',
      b: 'Always Pay, But Do It with Friends',
    ),
    (a: 'Went viral for an epic blunder', b: 'No more than 10 likes'),
    (a: 'Drinking Only Water Forever', b: 'No more water—just soft drinks'),
    (a: 'Just one musical genre for life', b: 'Just one app on your phone'),
    (a: 'In a tuxedo on the beach', b: 'Wearing a swimsuit to a wedding'),
    (
      a: 'Cooking Like a Michelin-Starred Chef',
      b: 'A House That Cleans Itself',
    ),
    (
      a: 'A Long Flight Next to a Chatterbox',
      b: 'A Long Flight Next to a Newborn',
    ),
    (a: 'Savory Breakfast Forever', b: 'A Sweet Dinner Forever'),
    (a: 'Living Without Mirrors', b: 'Living Without Watches'),
    (a: 'Talking to Plants', b: 'Understanding Newborns'),
    (a: 'Always Win at Cards', b: 'Always Finding Parking'),
    (
      a: 'A 40-degree summer without the ocean',
      b: 'A Freezing Winter Without Snow',
    ),
    (
      a: 'Only movies that are terribly dubbed',
      b: 'Only movies with out-of-sync subtitles',
    ),
    (a: 'Moving Every Year', b: 'The Same Home Forever'),
    (
      a: 'An Embarrassing Ringtone Forever',
      b: 'An Embarrassing Background Forever',
    ),
    (a: 'Being a Famous Meme', b: 'Having a Famous Look-Alike'),
    (
      a: 'Dancing the Macarena Every Time Someone Says Goodbye',
      b: 'Greet everyone with a bow',
    ),
    (
      a: 'An endless weekend, but it\'s still raining',
      b: 'It\'s only Monday, but it\'s always sunny',
    ),
    (
      a: 'Just one dish, but cooked to perfection',
      b: 'Cooking everything mediocrely',
    ),
    (a: 'A One-Way Trip to Mars', b: 'Never Leave Italy Again'),
    (
      a: 'Sleeping in a tent every night',
      b: 'Sleeping on the couch every night',
    ),
    (a: 'A robot butler', b: 'A robot chef'),
    (a: 'Know all the Hollywood gossip', b: 'Knowing Every TV Series Finale'),
    (a: 'Nothing but spicy food for a year', b: 'No More Salt'),
    (
      a: 'To dance exceptionally well to just one song',
      b: 'Dancing to just about any song',
    ),
    (a: 'Reading Dogs\' Minds', b: 'Talking to Cats'),
    (a: 'Always pick the fastest line', b: 'Always Get in the Right Elevator'),
    (a: 'Relive the Same Perfect Day', b: 'A new but unpredictable day'),
    (a: 'Being Invisible for One Hour a Day', b: 'Fly for ten minutes a day'),
    (a: 'Cooking for Ten Every Night', b: 'Wash ten dishes every night'),
    (
      a: 'A heavy backpack, but with everything I need',
      b: 'A lightweight backpack, but never quite the right one',
    ),
    (
      a: 'The photos always turn out bad, but the memories are perfect',
      b: 'Perfect photos, but fuzzy memories',
    ),
    (
      a: 'One mandatory karaoke session per week',
      b: 'One public speech a month',
    ),
    (a: 'An Embarrassing Human Butler', b: 'A robot that silently judges you'),
  ];

  static const List<({String a, String b, String tone})> preferisciHot = [
    (
      a: 'Walk around naked for a minute',
      b: 'Kissing someone from the group',
      tone: ContentTone.mix,
    ),
    (
      a: 'Spend the night with someone from the group',
      b: 'Spending a night with one of your old teachers',
      tone: ContentTone.mix,
    ),
    (
      a: 'Show the gallery to the group',
      b: 'Have Your Chats Read Aloud',
      tone: ContentTone.mix,
    ),
    (
      a: 'A Year Without Sex',
      b: 'A year without going out at night',
      tone: ContentTone.mix,
    ),
    (
      a: 'Tell the group your body count',
      b: 'Show the most recent search',
      tone: ContentTone.mix,
    ),
    (a: 'Love Without Sex', b: 'Sex Without Love', tone: ContentTone.mix),
    (
      a: 'A handsome partner, but terrible in bed',
      b: 'An ordinary partner, but phenomenal in bed',
      tone: ContentTone.mix,
    ),
    (
      a: 'A Night with Your Ex',
      b: 'A Night with a Stranger',
      tone: ContentTone.mix,
    ),
    (
      a: 'Catching Your Parents in the Act',
      b: 'Getting caught by your parents',
      tone: ContentTone.mix,
    ),
    (
      a: 'Tell everyone who you like right now',
      b: 'Never talk to the person you like again',
      tone: ContentTone.mix,
    ),
    (
      a: 'Kiss someone from the group with your eyes closed',
      b: 'Kissing Your Ex in Front of Everyone',
      tone: ContentTone.mix,
    ),
    (
      a: 'No Longer Being Able to Kiss',
      b: 'No longer being able to hug',
      tone: ContentTone.mix,
    ),
    (
      a: 'Finding Out Who Your Partner Might Cheat With',
      b: 'Never to know',
      tone: ContentTone.mix,
    ),
    (
      a: 'Nothing but blind dates for a year',
      b: 'Only outings chosen by your mother',
      tone: ContentTone.mix,
    ),
    (
      a: 'Watch a video of your first kiss',
      b: 'Let the whole group review it',
      tone: ContentTone.mix,
    ),
    (
      a: 'Groaning every time you sit down',
      b: 'Shouting your ex\'s name at every toast',
      tone: ContentTone.mix,
    ),
    (
      a: 'Accidentally sending a nude to an ex',
      b: 'Send him to the family group',
      tone: ContentTone.mix,
    ),
    (
      a: 'Accidentally Sexting with My Boss',
      b: 'Calling Your Partner by Your Ex\'s Name',
      tone: ContentTone.mix,
    ),
    (
      a: 'A Night with a Celebrity',
      b: 'A Month of Sex with Your Ex',
      tone: ContentTone.mix,
    ),
    (
      a: 'Have sex only in total darkness',
      b: 'Only with the light always on',
      tone: ContentTone.mix,
    ),
    (
      a: 'Share your wildest fantasy',
      b: 'Listen to the person on your right',
      tone: ContentTone.mix,
    ),
    (
      a: 'Friends with Benefits with Your Best Friend',
      b: 'No more sex for a year',
      tone: ContentTone.mix,
    ),
    (
      a: 'An ex who kisses like a dream',
      b: 'A new one who needs to be trained from scratch',
      tone: ContentTone.mix,
    ),
    (
      a: 'Watching you undress with my eyes at the bar',
      b: 'Never Be Noticed Again',
      tone: ContentTone.mix,
    ),
    (
      a: 'Tell the Story of Your Worst Date',
      b: 'Relive Your Hottest Embarrassing Moment',
      tone: ContentTone.mix,
    ),
    (
      a: 'Always Make the First Move',
      b: 'Always waiting for the other person to make the first move',
      tone: ContentTone.mix,
    ),
    (
      a: 'A threesome with strangers',
      b: 'A threesome with friends',
      tone: ContentTone.mix,
    ),
    (
      a: 'Catching Your Roommate in the Act',
      b: 'Getting Caught by Your Roommate',
      tone: ContentTone.mix,
    ),
    (
      a: 'Say how many times a day you think about it',
      b: 'Tell me when you last did it',
      tone: ContentTone.mix,
    ),
    (
      a: 'A super-jealous partner who\'s hot in bed',
      b: 'A calm but lazy partner in bed',
      tone: ContentTone.mix,
    ),
    (
      a: 'Kiss the first person who walks through the door',
      b: 'Kiss the last person who texted you',
      tone: ContentTone.mix,
    ),
    (
      a: 'A Night of Passion Without Kisses',
      b: 'Endless kisses, but nothing else',
      tone: ContentTone.mix,
    ),
    (
      a: 'Forgetting Your First Time',
      b: 'To remember her every single day',
      tone: ContentTone.mix,
    ),
    (
      a: 'Name the most absurd place where you\'ve done it',
      b: 'Tell us where you\'d like to do it',
      tone: ContentTone.mix,
    ),
    (
      a: 'A Flirtation with Your Personal Trainer',
      b: 'A Flirtation with Your Doctor',
      tone: ContentTone.mix,
    ),
    (
      a: 'Just one-night stands for a year',
      b: 'Serious, lifelong relationships only',
      tone: ContentTone.mix,
    ),
    (
      a: 'Get back together with your ex every once in a while',
      b: 'To close for good, but with regret',
      tone: ContentTone.mix,
    ),
    (
      a: 'A make-out session with the person on your left',
      b: 'A slow, sensual dance with the person on your right',
      tone: ContentTone.mix,
    ),
    (
      a: 'Sleeping Naked with a Friend',
      b: 'Taking a shower in a swimsuit with my ex',
      tone: ContentTone.mix,
    ),
    (
      a: 'Receiving an unsolicited nude from your boss',
      b: 'Sending one to the boss by mistake',
      tone: ContentTone.mix,
    ),
    (
      a: 'Amazing sex once a month',
      b: 'Mediocre sex every day',
      tone: ContentTone.mix,
    ),
    (
      a: 'Knowing what the other person is thinking in bed',
      b: 'May he hear your every thought in bed',
      tone: ContentTone.mix,
    ),
    (
      a: 'A Weekend with Your Secret Crush',
      b: 'A Month with Your First Love',
      tone: ContentTone.mix,
    ),
    (
      a: 'Breakfast in bed after the first night',
      b: 'Disappear Before Dawn',
      tone: ContentTone.mix,
    ),
    (
      a: 'Talking About Your Weakness in Bed',
      b: 'Act it out in front of the group',
      tone: ContentTone.mix,
    ),
    (
      a: 'Getting a tattoo of your ex\'s name',
      b: 'Shouting his name at the wrong moment',
      tone: ContentTone.mix,
    ),
    (
      a: 'Matching with your ex on an app',
      b: 'Match with your boss on an app',
      tone: ContentTone.mix,
    ),
    (
      a: 'Your partner knows all your fantasies',
      b: 'You know all of his fantasies',
      tone: ContentTone.mix,
    ),
    (
      a: 'An impromptu striptease right now',
      b: 'A Spicy Tale of Your Summer',
      tone: ContentTone.mix,
    ),
    (
      a: 'Kiss someone from the group of your choice',
      b: 'Kiss one chosen by the group',
      tone: ContentTone.mix,
    ),
    (
      a: 'A Super-Passionate Secret Story',
      b: 'An official but lukewarm account',
      tone: ContentTone.mix,
    ),
    (
      a: 'Having Sex Only in the Summer',
      b: 'Having Sex Only in the Winter',
      tone: ContentTone.mix,
    ),
    (
      a: 'Forget all your wild nights out',
      b: 'Remembering Even the Ones We Should Forget',
      tone: ContentTone.mix,
    ),
    (
      a: 'Sensitive audio message sent to the wrong person',
      b: 'Getting one from your boss',
      tone: ContentTone.mix,
    ),
    (
      a: 'Have them read the messages with their ex',
      b: 'Showing photos with my ex',
      tone: ContentTone.mix,
    ),
    (
      a: 'Love at First Sight Tonight',
      b: 'A One-Night Adventure Tonight',
      tone: ContentTone.mix,
    ),
    (
      a: 'Tell the group the name of your crush',
      b: 'Let the group guess',
      tone: ContentTone.mix,
    ),
    (
      a: 'Dancing a slow dance with your ex tonight',
      b: 'Romantic karaoke with one of the group',
      tone: ContentTone.mix,
    ),
    (
      a: 'Trying to pick up a stranger right now',
      b: 'Give your number to the first person who asks for it',
      tone: ContentTone.mix,
    ),
    (
      a: 'A massage from one of the group',
      b: 'You do it to someone in the group',
      tone: ContentTone.mix,
    ),
    (
      a: 'No flirting for a year',
      b: 'The Obligation to Flirt with Anyone',
      tone: ContentTone.mix,
    ),
    (
      a: 'A Night with Your Musical Idol',
      b: 'A Weekend with Your Favorite Actor',
      tone: ContentTone.mix,
    ),
    (
      a: 'Confessing a steamy dream about someone who\'s present',
      b: 'Let someone here testify about you',
      tone: ContentTone.mix,
    ),
    (
      a: 'Complete silence in bed',
      b: 'Full play-by-play commentary from bed',
      tone: ContentTone.mix,
    ),
    (
      a: 'An amazing backside',
      b: 'A neckline worthy of applause',
      tone: ContentTone.mix,
    ),
    (
      a: 'Your ex becomes incredibly famous',
      b: 'Your ex becomes your boss',
      tone: ContentTone.mix,
    ),
    (
      a: 'Tell me what turns you on the most',
      b: 'Say what turns you off right away',
      tone: ContentTone.mix,
    ),
    (
      a: 'A Summer Affair That Was Never Admitted',
      b: 'An Infinite Long-Distance Love',
      tone: ContentTone.mix,
    ),
    (
      a: 'Let two people there flirt with you',
      b: 'Flirting with two people who are together',
      tone: ContentTone.mix,
    ),
    (
      a: 'Seeing your ex with someone who\'s better-looking than you',
      b: 'May he see you with someone worse than him',
      tone: ContentTone.mix,
    ),
    (
      a: 'Kisses with a Bite',
      b: 'Kisses from the mold, forever',
      tone: ContentTone.mix,
    ),
    (
      a: 'Sleeping in each other\'s arms without having sex',
      b: 'Sex Without Ever Sleeping Together',
      tone: ContentTone.mix,
    ),
    (
      a: 'Having sex with the music blaring',
      b: 'With the news playing in the background',
      tone: ContentTone.mix,
    ),
    (
      a: 'Reveal how many exes you\'ve had',
      b: 'To Reveal Who Was the Best',
      tone: ContentTone.mix,
    ),
    (
      a: 'Try to hit on the waiter tonight',
      b: 'Leave your number on the receipt',
      tone: ContentTone.mix,
    ),
    (
      a: 'An Awkward but Sweet First Time',
      b: 'Perfect, but with the wrong person',
      tone: ContentTone.mix,
    ),
    (
      a: 'A tattoo where the group decides',
      b: 'A piercing where the group decides',
      tone: ContentTone.mix,
    ),
    (
      a: 'A 30-second kiss with someone who is present',
      b: 'Ten quick kisses with ten strangers',
      tone: ContentTone.mix,
    ),
    (
      a: 'Find out who in your group dreams about you at night',
      b: 'Knowing who would never kiss you',
      tone: ContentTone.mix,
    ),
    (
      a: 'Sex in a Tent at a Crowded Campground',
      b: 'At a hotel with paper walls',
      tone: ContentTone.mix,
    ),
    (
      a: 'A vacation just for singles',
      b: 'A vacation just for couples',
      tone: ContentTone.mix,
    ),
    (
      a: 'Anal sex every time',
      b: 'No more sex for a year',
      tone: ContentTone.mix,
    ),
    (a: 'To be dominated', b: 'Being Dominant', tone: ContentTone.mix),
    (
      a: 'Having sex with two people at the same time',
      b: 'Going without it for six months',
      tone: ContentTone.mix,
    ),
    (
      a: 'Having yourself filmed while you do it',
      b: 'Don\'t ever do that again',
      tone: ContentTone.mix,
    ),
    (a: 'Lick everywhere', b: 'To be licked all over', tone: ContentTone.mix),
    (a: 'To swallow', b: 'To spit', tone: ContentTone.hot),
    (
      a: 'Let yourself be treated to a massage',
      b: 'Surprise him or her',
      tone: ContentTone.mix,
    ),
    (
      a: 'Wild Sex with a Stranger',
      b: 'Mediocre Sex with the Ideal Partner',
      tone: ContentTone.mix,
    ),
    (
      a: 'Make him swallow it',
      b: 'Make him spit it on you',
      tone: ContentTone.hot,
    ),
    (
      a: 'A threesome with coworkers',
      b: 'With two close friends from the group',
      tone: ContentTone.mix,
    ),
    (
      a: 'Only oral sex for a year',
      b: 'No More Oral Sex',
      tone: ContentTone.hot,
    ),
    (
      a: 'Always Take the Oral Exam',
      b: 'You\'re always the one who has to do it',
      tone: ContentTone.hot,
    ),
    (
      a: 'Oral sex that ends in the mouth',
      b: 'Oral sex that ends on the face',
      tone: ContentTone.hot,
    ),
    (
      a: 'Licking Until Orgasm',
      b: 'Being licked to orgasm',
      tone: ContentTone.hot,
    ),
    (
      a: 'A 30-minute blowjob',
      b: 'How to Get There in 30 Seconds',
      tone: ContentTone.hot,
    ),
    (
      a: 'Threesome with two strangers',
      b: 'Watching Your Partner with Someone Else',
      tone: ContentTone.hot,
    ),
    (
      a: 'Threesome with two men',
      b: 'Threesome with two women',
      tone: ContentTone.hot,
    ),
    (
      a: 'An orgy with eight people',
      b: 'Sex Alone for a Year',
      tone: ContentTone.hot,
    ),
    (
      a: 'Watching your partner have sex with someone else',
      b: 'Having someone watch you while you have sex',
      tone: ContentTone.hot,
    ),
    (
      a: 'A stranger watches you come',
      b: 'Watch a stranger come',
      tone: ContentTone.hot,
    ),
    (
      a: 'Have yourself tied up and blindfolded',
      b: 'Tie up and blindfold your partner',
      tone: ContentTone.hot,
    ),
    (
      a: 'To be gently whipped',
      b: 'You spank your partner',
      tone: ContentTone.hot,
    ),
    (
      a: 'Submissive for One Night',
      b: 'Dominatrix for a Night',
      tone: ContentTone.hot,
    ),
    (
      a: 'You\'re wearing a collar and a leash',
      b: 'Pass them to your partner',
      tone: ContentTone.hot,
    ),
    (
      a: 'Spanked until it left a mark',
      b: 'Spank until it leaves a mark',
      tone: ContentTone.hot,
    ),
    (
      a: 'Tied to the bed all night',
      b: 'Tie Your Partner to the Bed',
      tone: ContentTone.hot,
    ),
    (
      a: 'Blindfolded and at her partner\'s mercy',
      b: 'Blindfold Your Partner and Take Charge',
      tone: ContentTone.hot,
    ),
    (
      a: 'A vibrator that runs for an hour without stopping',
      b: 'No orgasms for a month',
      tone: ContentTone.hot,
    ),
    (
      a: 'Denied an orgasm for days',
      b: 'Repeated Orgasms on Command',
      tone: ContentTone.hot,
    ),
    (
      a: 'A plug worn all day long',
      b: 'A vibrator in public',
      tone: ContentTone.hot,
    ),
    (
      a: 'Try all the sex toys in the store',
      b: 'Just Hands Forever',
      tone: ContentTone.hot,
    ),
    (
      a: 'A huge dildo',
      b: 'A small vibrator that\'s always on',
      tone: ContentTone.hot,
    ),
    (
      a: 'Real handcuffs on the wrists',
      b: 'Silk ropes on the body',
      tone: ContentTone.hot,
    ),
    (
      a: 'Sex in a club bathroom',
      b: 'Sex in a Dark Alley',
      tone: ContentTone.hot,
    ),
    (
      a: 'Doing it on the beach at night',
      b: 'Doing it in the elevator',
      tone: ContentTone.hot,
    ),
    (
      a: 'Sex in a Car in a Parking Lot',
      b: 'Sex on a Rooftop at Night',
      tone: ContentTone.hot,
    ),
    (
      a: 'Risking being caught at the office',
      b: 'Doing it in a dressing room',
      tone: ContentTone.hot,
    ),
    (
      a: 'Sex on a Moving Train',
      b: 'Sex Under a Crowded Table',
      tone: ContentTone.hot,
    ),
    (
      a: 'A racy video that\'s making the rounds',
      b: 'Your steamy chats that are making the rounds',
      tone: ContentTone.hot,
    ),
    (
      a: 'Your nude photos on his phone',
      b: 'An intimate video of you that was saved',
      tone: ContentTone.hot,
    ),
    (
      a: 'Record while you\'re doing it',
      b: 'Taking nude photos of yourself for him',
      tone: ContentTone.hot,
    ),
    (
      a: 'A nude photo sent to the boss by mistake',
      b: 'A nude photo seen by your friends',
      tone: ContentTone.hot,
    ),
    (
      a: 'Having sex in front of a webcam',
      b: 'Having sex with the lights on the whole time',
      tone: ContentTone.hot,
    ),
    (
      a: 'Rough, Merciless Sex',
      b: 'Slow sex all night long',
      tone: ContentTone.hot,
    ),
    (
      a: 'To come five times in a row',
      b: 'A single, very long orgasm',
      tone: ContentTone.hot,
    ),
    (
      a: 'Always Faking an Orgasm',
      b: 'Never come again',
      tone: ContentTone.hot,
    ),
    (
      a: 'One orgasm every hour for a day',
      b: 'No orgasms for a year',
      tone: ContentTone.hot,
    ),
    (
      a: 'Squirting in front of him',
      b: 'To see it coming onto your body',
      tone: ContentTone.hot,
    ),
    (a: 'Anal sex', b: 'Double Penetration', tone: ContentTone.hot),
    (
      a: 'Trying Anal Sex for the First Time',
      b: 'Never try it',
      tone: ContentTone.hot,
    ),
    (
      a: 'Pick up a stranger tonight',
      b: 'An Ex for One Last Night',
      tone: ContentTone.hot,
    ),
    (
      a: 'A Night with Your Favorite Movie Star',
      b: 'A Night with Your Ex-Best Friend',
      tone: ContentTone.hot,
    ),
    (
      a: 'Sex with His Best Friend',
      b: 'Sex with her best friend',
      tone: ContentTone.hot,
    ),
    (
      a: 'Swinging with Friends',
      b: 'Exchange with Complete Strangers',
      tone: ContentTone.hot,
    ),
    (
      a: 'Kissing Everyone at an Orgy',
      b: 'Choose only one person',
      tone: ContentTone.hot,
    ),
    (
      a: 'A massage that ends in bed',
      b: 'A private lap dance',
      tone: ContentTone.hot,
    ),
    (
      a: 'Striptease in front of the group',
      b: 'Dancing naked on a pole',
      tone: ContentTone.hot,
    ),
    (
      a: 'Licking the cream off your partner\'s body',
      b: 'Have him lick the chocolate off your body',
      tone: ContentTone.hot,
    ),
    (
      a: 'Sex with your body covered in oil',
      b: 'Sex in a steamy shower',
      tone: ContentTone.hot,
    ),
    (
      a: 'Satisfying a foot fetish',
      b: 'Satisfying a butt fetish',
      tone: ContentTone.hot,
    ),
    (
      a: 'Have someone suck your toes',
      b: 'You suck on hers',
      tone: ContentTone.hot,
    ),
    (
      a: 'Wearing only lingerie for dinner out',
      b: 'No Underwear When Dining Out',
      tone: ContentTone.hot,
    ),
    (
      a: 'A tight corset all evening',
      b: 'Stiletto heels and nothing else',
      tone: ContentTone.hot,
    ),
    (
      a: 'Sex While Wearing a Mask',
      b: 'Sex in Total Darkness',
      tone: ContentTone.hot,
    ),
    (
      a: 'Say Your Fantasies Out Loud',
      b: 'Make one at random',
      tone: ContentTone.hot,
    ),
    (
      a: 'A role-playing game between a teacher and a student',
      b: 'A role-playing game between a boss and a secretary',
      tone: ContentTone.hot,
    ),
    (
      a: 'Pretend you\'re two strangers in a bar',
      b: 'Pretend you\'re two exes who run into each other',
      tone: ContentTone.hot,
    ),
    (
      a: 'Sex while others are sleeping nearby',
      b: 'Unrestrained, Screaming Sex',
      tone: ContentTone.hot,
    ),
    (
      a: 'Have someone whisper dirty things in your ear',
      b: 'You tell him',
      tone: ContentTone.hot,
    ),
    (
      a: 'Sexting All Day at Work',
      b: 'Hot photos every hour',
      tone: ContentTone.hot,
    ),
    (
      a: 'A blowjob while he\'s driving',
      b: 'Masturbating at the movies',
      tone: ContentTone.hot,
    ),
    (
      a: 'Seduce him with your gaze for an hour',
      b: 'Jump on him right away',
      tone: ContentTone.hot,
    ),
    (
      a: 'Ride him until he\'s exhausted',
      b: 'Let yourself be taken from behind',
      tone: ContentTone.hot,
    ),
    (
      a: 'Sex in Three Positions in a Row',
      b: 'An hour in the same position',
      tone: ContentTone.hot,
    ),
    (
      a: 'Making him come using only your hands',
      b: 'Only with the mouth',
      tone: ContentTone.hot,
    ),
    (a: 'A Blindfolded Blowjob', b: 'Blindfolded sex', tone: ContentTone.hot),
    (a: 'Ice on bare skin', b: 'Hot wax on the body', tone: ContentTone.hot),
    (
      a: 'Bite until you leave marks',
      b: 'Scratch your back deeply',
      tone: ContentTone.hot,
    ),
    (
      a: 'Visible hickies on the neck',
      b: 'Bite marks on the inner thighs',
      tone: ContentTone.hot,
    ),
    (
      a: 'Sex with just one partner for the rest of your life',
      b: 'A different partner every month',
      tone: ContentTone.hot,
    ),
    (
      a: 'Seeing your partner naked with someone else',
      b: 'Never knowing what he\'s up to',
      tone: ContentTone.hot,
    ),
    (
      a: 'A trio planned down to the last detail',
      b: 'A completely improvised trio',
      tone: ContentTone.hot,
    ),
    (
      a: 'Let him undress you slowly',
      b: 'Undress him with your teeth',
      tone: ContentTone.hot,
    ),
    (
      a: 'Sex with him in uniform',
      b: 'Sex with a Partner in Uniform',
      tone: ContentTone.hot,
    ),
    (
      a: 'Extremely long foreplay without penetration',
      b: 'Penetration right away, without foreplay',
      tone: ContentTone.hot,
    ),
    (
      a: 'Edging for an hour',
      b: 'Instant orgasm and that\'s it',
      tone: ContentTone.hot,
    ),
    (
      a: 'Being touched in a crowded club',
      b: 'You touch him under the table',
      tone: ContentTone.hot,
    ),
    (
      a: 'An Extra Finger During Sex',
      b: 'An extra tongue during sex',
      tone: ContentTone.hot,
    ),
    (
      a: 'Sex in front of the mirror',
      b: 'Sex Filmed on a Phone',
      tone: ContentTone.hot,
    ),
    (
      a: 'Wearing a butt plug to dinner at your in-laws\' house',
      b: 'A vibrator controlled remotely by your partner',
      tone: ContentTone.hot,
    ),
    (
      a: 'Remote-Controlled Vibrator on the Subway',
      b: 'Remote-Controlled Vibrator at a Restaurant',
      tone: ContentTone.hot,
    ),
    (
      a: 'A long spanking session',
      b: 'A long bondage session',
      tone: ContentTone.hot,
    ),
    (
      a: 'Being suspended by Japanese ropes',
      b: 'Being restrained with tape',
      tone: ContentTone.hot,
    ),
    (
      a: 'A full-body massage from a member of the group',
      b: 'Taking a shower with someone from the group',
      tone: ContentTone.mix,
    ),
    (
      a: 'Kissing the coworker you\'ve had a crush on for months',
      b: 'Hearing him say he feels the same way, but he\'s engaged',
      tone: ContentTone.mix,
    ),
    (
      a: 'Slow sex all night long',
      b: 'Fast and Passionate Sex in One Minute',
      tone: ContentTone.mix,
    ),
    (
      a: 'Say your passphrase out loud',
      b: 'Imitate your favorite position',
      tone: ContentTone.mix,
    ),
    (
      a: 'A steamy fling with your ex\'s best friend',
      b: 'A Steamy Flirtation with the Neighbor',
      tone: ContentTone.mix,
    ),
    (
      a: 'Having sex only in public places',
      b: 'Have sex only with the door open',
      tone: ContentTone.mix,
    ),
    (
      a: 'A weekend of sex without talking',
      b: 'A weekend of pampering without sex',
      tone: ContentTone.mix,
    ),
    (
      a: 'Get a lap dance from the person on your right',
      b: 'Give one to the person on your left',
      tone: ContentTone.mix,
    ),
    (
      a: 'Admit which person here you would try to woo',
      b: 'Have the group help you choose a suitor',
      tone: ContentTone.mix,
    ),
    (
      a: 'Try everything in one night with a stranger',
      b: 'Staying Chaste for a Year with True Love',
      tone: ContentTone.mix,
    ),
    (
      a: 'A French kiss with your first love',
      b: 'An endless hug from your latest crush',
      tone: ContentTone.mix,
    ),
    (
      a: 'Kiss everyone present, one by one',
      b: 'Kissing just one person for ten minutes',
      tone: ContentTone.mix,
    ),
    (
      a: 'Saying how long you last on average in bed',
      b: 'Tell us your personal best',
      tone: ContentTone.mix,
    ),
    (
      a: 'A Forbidden Encounter with the Dance Teacher',
      b: 'A Forbidden Encounter with the Bartender Down the Street',
      tone: ContentTone.mix,
    ),
    (
      a: 'How to Seduce a Stranger in Ten Minutes',
      b: 'Let Yourself Be Seduced Without Saying a Word',
      tone: ContentTone.mix,
    ),
    (
      a: 'Nothing but sexy lingerie for a month',
      b: 'Nothing but baggy pajamas for a year',
      tone: ContentTone.mix,
    ),
    (
      a: 'Perfect chemistry in bed but zero connection outside of it',
      b: 'A perfect match on the outside, but zero chemistry in bed',
      tone: ContentTone.mix,
    ),
    (
      a: 'Having someone undress you in the dark without knowing who they are',
      b: 'To undress someone without saying a word',
      tone: ContentTone.mix,
    ),
    (
      a: 'Describe the fantasy you\'ve never acted on',
      b: 'Do it tonight with someone present',
      tone: ContentTone.mix,
    ),
    (
      a: 'A passionate kiss in the rain',
      b: 'A Fiery Night in Front of the Fireplace',
      tone: ContentTone.mix,
    ),
    (
      a: 'Sex with the most beautiful person I\'ve ever seen',
      b: 'Unforgettable sex with the one you truly love',
      tone: ContentTone.mix,
    ),
    (
      a: 'Let the person on your right bite your neck',
      b: 'You bite the neck of the person to your left',
      tone: ContentTone.mix,
    ),
    (
      a: 'How many times have you thought about someone who\'s here?',
      b: 'Get someone who\'s there to admit how often they think about you',
      tone: ContentTone.mix,
    ),
    (
      a: 'A year of carefree adventures with no tomorrow',
      b: 'A whole year of just waiting for the right person',
      tone: ContentTone.mix,
    ),
    (
      a: 'Kiss Someone with a Blindfold On and Guess Who It Is',
      b: 'Let him kiss you and let everyone guess',
      tone: ContentTone.mix,
    ),
    (
      a: 'Uninhibited sex, but without ever seeing each other again',
      b: 'An endless wait, but then forever',
      tone: ContentTone.mix,
    ),
    (
      a: 'A provocative dance in front of the whole group',
      b: 'A surprise kiss chosen by the group',
      tone: ContentTone.mix,
    ),
    (
      a: 'Taking a Shower with Your Ex',
      b: 'Taking a bath with your crush',
      tone: ContentTone.mix,
    ),
    (
      a: 'Say who in the group you\'d kiss in the dark',
      b: 'Say who in the group you would never kiss',
      tone: ContentTone.mix,
    ),
    (
      a: 'A foot massage from a sexy stranger',
      b: 'A back massage from your ex',
      tone: ContentTone.mix,
    ),
    (
      a: 'Have sex only in the dark with candles',
      b: 'Having sex only in front of the mirror',
      tone: ContentTone.mix,
    ),
    (
      a: 'A Secret Flirtation with Your Swimming Instructor',
      b: 'A Secret Flirtation with Your Tattoo Artist',
      tone: ContentTone.mix,
    ),
    (
      a: 'Reveal the risqué item you own',
      b: 'Show it to the group',
      tone: ContentTone.mix,
    ),
    (
      a: 'Spending the night with your high school crush',
      b: 'Spend the night with your current crush',
      tone: ContentTone.mix,
    ),
    (
      a: 'Only slow kisses for a month',
      b: 'Just nights of passion, but no kisses',
      tone: ContentTone.mix,
    ),
    (
      a: 'To have steamy things whispered in your ear',
      b: 'Whisper it to the person next to you',
      tone: ContentTone.mix,
    ),
    (
      a: 'Tell us the sexy nickname you give your partner',
      b: 'Say what your partner gives you',
      tone: ContentTone.mix,
    ),
    (
      a: 'A night with the person who rejected you years ago',
      b: 'A night with the one who\'s always wanted you',
      tone: ContentTone.mix,
    ),
    (
      a: 'Always having sex on the first date',
      b: 'Waiting three months every time',
      tone: ContentTone.mix,
    ),
    (
      a: 'Kiss the person in front of you for twenty seconds',
      b: 'Hug the person behind you for two minutes',
      tone: ContentTone.mix,
    ),
    (
      a: 'The riskiest place where you\'ve tried it',
      b: 'The most absurd time you ever did that',
      tone: ContentTone.mix,
    ),
    (
      a: 'A weekend at the spa with just one person from the group',
      b: 'A romantic cruise with a stranger',
      tone: ContentTone.mix,
    ),
    (
      a: 'How to Let Someone Read Your Mind During a Kiss',
      b: 'You can read the thoughts of the person you\'re kissing',
      tone: ContentTone.mix,
    ),
    (
      a: 'Nothing but steamy dates, but never a second',
      b: 'Just sweet dates, but without any chemistry',
      tone: ContentTone.mix,
    ),
    (
      a: 'Find out how many people in the audience you would find attractive',
      b: 'Have everyone tell you if they find you attractive',
      tone: ContentTone.mix,
    ),
    (
      a: 'Having sex while listening to your favorite song',
      b: 'Do it in complete silence',
      tone: ContentTone.mix,
    ),
    (
      a: 'A Night with a Model, but Without Words',
      b: 'A night with a funny guy, but no sex',
      tone: ContentTone.mix,
    ),
    (
      a: 'A passionate kiss with the person on your right',
      b: 'A sensual massage from the person on your left',
      tone: ContentTone.mix,
    ),
    (
      a: 'Which part of the body drives you wild?',
      b: 'Let the group guess',
      tone: ContentTone.mix,
    ),
    (
      a: 'How to Seduce Someone You Like Using Only Emojis',
      b: 'Seduce him with a single embarrassing voice message',
      tone: ContentTone.mix,
    ),
    (
      a: 'Having sex only early in the morning',
      b: 'Having sex only late at night',
      tone: ContentTone.mix,
    ),
    (
      a: 'A kiss stolen from your boss because of a bet',
      b: 'A stolen kiss from your partner\'s best friend',
      tone: ContentTone.mix,
    ),
    (
      a: 'Confess Your Fantasy About a Celebrity',
      b: 'Listen to the person in front of you',
      tone: ContentTone.mix,
    ),
    (
      a: 'Only long-distance but passionate relationships',
      b: 'Only close but lukewarm relationships',
      tone: ContentTone.mix,
    ),
    (
      a: 'Get a clearly visible hickey',
      b: 'Do something nice for the person next to you',
      tone: ContentTone.mix,
    ),
    (
      a: 'Say how many times you\'ve made the first move',
      b: 'Tell me how many times you backed out',
      tone: ContentTone.mix,
    ),
    (
      a: 'A night of passion—but you\'ll forget it',
      b: 'Not a single night, but the memory of a kiss',
      tone: ContentTone.mix,
    ),
    (
      a: 'Kissing the shyest person in the group',
      b: 'Kissing the boldest girl in the group',
      tone: ContentTone.mix,
    ),
    (
      a: 'Play strip poker with the people there',
      b: 'Play a game of "Truth or Dare" with just a spicy twist',
      tone: ContentTone.mix,
    ),
    (
      a: 'To seduce someone with just a glance',
      b: 'Seduce him with just one sentence',
      tone: ContentTone.mix,
    ),
    (
      a: 'A steamy date set up by your ex',
      b: 'A steamy date arranged by your mom',
      tone: ContentTone.mix,
    ),
    (a: 'A bite on the nipple', b: 'Nipple Clamps', tone: ContentTone.hot),
    (
      a: 'A blindfold and impromptu surprises',
      b: 'Knowing Everything in Advance',
      tone: ContentTone.hot,
    ),
    (
      a: 'Being Verbally Humiliated in Bed',
      b: 'Verbally humiliate him',
      tone: ContentTone.hot,
    ),
    (
      a: 'Dominate for one night',
      b: 'Surrender for One Night',
      tone: ContentTone.hot,
    ),
    (
      a: 'Obey every order for one hour',
      b: 'You get to call the shots for an hour',
      tone: ContentTone.hot,
    ),
    (
      a: 'Sex with a safe word',
      b: 'Sex Without Agreed-Upon Limits',
      tone: ContentTone.hot,
    ),
    (
      a: 'A threesome with an escort',
      b: 'A plan involving three people and a friend',
      tone: ContentTone.hot,
    ),
    (
      a: 'Being filmed by a third person who is present',
      b: 'To be watched only by a third person',
      tone: ContentTone.hot,
    ),
    (
      a: 'Sex on a Balcony in Plain View',
      b: 'Sex in the Garden at Night',
      tone: ContentTone.hot,
    ),
    (
      a: 'A quick encounter in the kitchen',
      b: 'A Marathon in the Bedroom',
      tone: ContentTone.hot,
    ),
    (
      a: 'Do it on the table in the living room',
      b: 'Do it against the wall by the entrance',
      tone: ContentTone.hot,
    ),
    (
      a: 'Sex first thing in the morning every day',
      b: 'Sex only at midnight every night',
      tone: ContentTone.hot,
    ),
    (a: 'Try wax play', b: 'Try temperature play', tone: ContentTone.hot),
    (
      a: 'A vibrator while he watches you',
      b: 'His hands as you watch',
      tone: ContentTone.hot,
    ),
    (
      a: 'Masturbate in front of him',
      b: 'Watching him masturbate for you',
      tone: ContentTone.hot,
    ),
    (
      a: 'An orgasm from words alone',
      b: 'An orgasm using only a sex toy',
      tone: ContentTone.hot,
    ),
    (
      a: 'Quiet sex so you won\'t be heard',
      b: 'Noisy, Unrestrained Sex',
      tone: ContentTone.hot,
    ),
    (
      a: 'Quick, Spontaneous Sex',
      b: 'Extremely long foreplay without sex',
      tone: ContentTone.hot,
    ),
    (a: 'A creampie', b: 'A facial', tone: ContentTone.hot),
    (
      a: 'Lick it after he comes',
      b: 'Having him lick you after you\'ve come',
      tone: ContentTone.hot,
    ),
    (
      a: 'Sex in broad daylight',
      b: 'Sex by candlelight only',
      tone: ContentTone.hot,
    ),
    (
      a: 'Sex with music blaring',
      b: 'Sex in Complete Silence',
      tone: ContentTone.hot,
    ),
    (
      a: 'Having Your Wrists Tied with a Tie',
      b: 'Tie the ankles with the socks',
      tone: ContentTone.hot,
    ),
    (
      a: 'A blindfold and soundproof headphones',
      b: 'Just the blindfold',
      tone: ContentTone.hot,
    ),
    (
      a: 'To be completely in control for a day',
      b: 'Surrender yourself completely for one day',
      tone: ContentTone.hot,
    ),
    (
      a: 'Sex in a Tent While Camping',
      b: 'Sex in the Pool at Night',
      tone: ContentTone.hot,
    ),
    (
      a: 'Sex in the back seat of a car',
      b: 'Sex on the hood of the car',
      tone: ContentTone.hot,
    ),
    (a: 'Try pegging', b: 'Try rimming', tone: ContentTone.hot),
    (
      a: 'A wearable dildo for her',
      b: 'A vibrating ring for him',
      tone: ContentTone.hot,
    ),
    (
      a: 'Let me take you all the way in my mouth',
      b: 'You take it all the way',
      tone: ContentTone.hot,
    ),
    (a: 'Deep Throat', b: 'Face sitting', tone: ContentTone.hot),
    (a: 'Sit on his face', b: 'Have him sit on yours', tone: ContentTone.hot),
    (a: 'An Endless Sixty-Nine', b: 'Take turns', tone: ContentTone.hot),
    (
      a: 'Sex with a warming lubricant',
      b: 'Sex with a cooling gel',
      tone: ContentTone.hot,
    ),
    (
      a: 'Have yourself blindfolded and guess the toys',
      b: 'Guessing His Hands While Blindfolded',
      tone: ContentTone.hot,
    ),
    (
      a: 'A role-playing game between a nurse and a patient',
      b: 'A role-playing game between a policewoman and a suspect',
      tone: ContentTone.hot,
    ),
    (
      a: 'Pretending to Be Strangers at a Hotel',
      b: 'Pretend to be nosy neighbors',
      tone: ContentTone.hot,
    ),
    (
      a: 'Sex while wearing torn lingerie',
      b: 'Sex While Staying Almost Fully Clothed',
      tone: ContentTone.hot,
    ),
    (
      a: 'To have your panties ripped off',
      b: 'Rip his boxers off with my teeth',
      tone: ContentTone.hot,
    ),
    (
      a: 'An orgasm in less than a minute',
      b: 'Hold on for twenty minutes',
      tone: ContentTone.hot,
    ),
    (
      a: 'Counting Orgasms Out Loud',
      b: 'To remain in complete silence',
      tone: ContentTone.hot,
    ),
    (
      a: 'A threesome with your crush',
      b: 'A threesome with her crush',
      tone: ContentTone.hot,
    ),
    (
      a: 'Watching porn together and acting it out',
      b: 'Making everything up from scratch without any references',
      tone: ContentTone.hot,
    ),
    (
      a: 'Recreating a Famous Porn Scene',
      b: 'Shoot your own intimate amateur video',
      tone: ContentTone.hot,
    ),
    (
      a: 'Sex While Still Wearing Heels',
      b: 'Sex While Completely Naked',
      tone: ContentTone.hot,
    ),
    (
      a: 'To have you hold a little egg all day long',
      b: 'A plug all afternoon',
      tone: ContentTone.hot,
    ),
    (
      a: 'A Full-Body Erotic Massage',
      b: 'An Erotic Bath for Two',
      tone: ContentTone.hot,
    ),
    (
      a: 'Sex with scented oil everywhere',
      b: 'Sex scenes covered in foam',
      tone: ContentTone.hot,
    ),
    (
      a: 'Have him be seduced by another woman right in front of you',
      b: 'If you seduce someone else in front of him',
      tone: ContentTone.hot,
    ),
    (
      a: 'A game of strip poker that ends in bed',
      b: 'A "Truth or Dare" that\'s totally hot',
      tone: ContentTone.hot,
    ),
    (
      a: 'Kissing a woman in front of him',
      b: 'Watching him kiss a man',
      tone: ContentTone.hot,
    ),
    (
      a: 'A first kiss between two women',
      b: 'A first kiss between two men',
      tone: ContentTone.hot,
    ),
    (
      a: 'Sex with Both Hands on You',
      b: 'Sex with two mouths on you',
      tone: ContentTone.hot,
    ),
    (
      a: 'To have your neck gently caressed',
      b: 'You hold his wrists',
      tone: ContentTone.hot,
    ),
    (
      a: 'A light, agreed-upon choke',
      b: 'A firm tug on the hair',
      tone: ContentTone.hot,
    ),
    (
      a: 'Sex with my hair pulled back',
      b: 'Sex with fingernails on the back',
      tone: ContentTone.hot,
    ),
    (
      a: 'Getting taken from behind in front of the mirror',
      b: 'Take him by riding him in front of the mirror',
      tone: ContentTone.hot,
    ),
    (
      a: 'No orgasm for three days',
      b: 'Three orgasms in an hour',
      tone: ContentTone.hot,
    ),
    (
      a: 'Let people watch you undress on webcam',
      b: 'Watching him undress on webcam',
      tone: ContentTone.hot,
    ),
    (
      a: 'A vibrator shared in turns',
      b: 'Two toys at the same time',
      tone: ContentTone.hot,
    ),
    (
      a: 'Sex on a tied-up chair',
      b: 'Sex Standing Up by the Window',
      tone: ContentTone.hot,
    ),
    (
      a: 'To make you bite your lip until it bleeds',
      b: 'Bite his neck fiercely',
      tone: ContentTone.hot,
    ),
    (
      a: 'Sex stopped and restarted several times',
      b: 'One continuous session with no breaks',
      tone: ContentTone.hot,
    ),
    (
      a: 'Experiencing Sensory Deprivation',
      b: 'Experiencing Sensory Overload',
      tone: ContentTone.hot,
    ),
    (
      a: 'Getting tickled while blindfolded',
      b: 'Tickle him while he\'s pinned down',
      tone: ContentTone.hot,
    ),
  ];
}
