import '../content_tone.dart';

class ContentEnObbligoOVerita {
  const ContentEnObbligoOVerita._();

  static const Map<String, List<String>> obblighi = {
    ContentTone.normal: [
      'Imitate the way the person on your right walks.',
      'Sing the chorus of the last song you listened to.',
      'Speak in rhyme until it\'s your next turn.',
      'Imitate the sounds of three animals and see if they can guess which ones they are.',
      'Dance for ten seconds without music.',
      'Tell a joke: if no one laughs, repeat it louder.',
      'Imitate your favorite character from a TV show.',
      'Strike a statue-like pose and stay still for thirty seconds.',
      'Talk like a sports commentator for a minute.',
      'Show the last photo you took.',
      'Show your home screen without opening anything.',
      'Show us the emoji you use the most and explain why you chose that one.',
      'Show us how many alarms you\'ve set.',
      'Ask your phone\'s voice assistant a ridiculous question chosen by the group.',
      'Send a sung voice message to a random contact of yours.',
      'Call a friend and sing "Happy Birthday" to them, even if it\'s not their birthday.',
      'Give a sincere compliment to everyone present.',
      'Describe the person to your left using only three words.',
      'Come up with a 20-second rap about the person to your left.',
      'Imitate the teacher you remember the least.',
      'Pretend you\'re a salesperson and sell us this table.',
      'Present tomorrow\'s weather forecast just like on TV.',
      'Speak with a foreign accent until the next round.',
      'Summarize the plot of a movie without mentioning its title; let the others guess.',
      'Give a thank-you speech as if you had won an award.',
      'Create an ad for the item closest to you.',
      'Show us how you dance when you\'re home alone.',
      'Sing instead of talking for the next two minutes.',
      'Walk with a book balanced on your head.',
      'Wear your clothes inside out for two rounds.',
      'Have the person on your right give you a new hairstyle.',
      'Draw a picture of the group in thirty seconds.',
      'Write your name with your non-dominant hand and show it to us.',
      'Draw a portrait of someone here with your eyes closed, then give it to them as a gift.',
      'Recite the alphabet backward as fast as you can.',
      'Count to twenty, skipping every third number.',
      'Say three words backward, starting with the last one.',
      'Tell a 30-second made-up story that begins with "Last night…".',
      'Describe your day as if it were a horror movie.',
      'Describe your job or a typical day as a child would.',
      'Pretend you\'re a robot for a minute.',
      'Respond only with questions until the next round.',
      'You can\'t say "yes" or "no" until your next turn.',
      'Talk about yourself in the third person until it\'s your next turn.',
      'Laugh as loud as you can for no reason.',
      'Stay completely serious for thirty seconds while the others try to make you laugh.',
      'Do a 20-second plank while the others count.',
      'Do five push-ups as counted by the group.',
      'Run in place until the end of your shift.',
      'Do ten squats, saying the name of one person present with each squat.',
      'Eat something chosen by the person to your left.',
      'Try eating two things together that don\'t go well together.',
      'Write a review—as if you were a Michelin-starred critic—of the last thing you ate today.',
      'Make a non-alcoholic drink and let someone try it.',
      'Make an impromptu toast in honor of the group.',
      'Share your fondest memory with someone here.',
      'Tell us how you met the person sitting across from you.',
      'Tell us what you envy (in a positive way) about each person here.',
      'Make a prediction about the future of someone who is here right now.',
      'Give each one a nickname and explain it.',
      'Respond only to a new nickname chosen by the group until the end of the game.',
      'Choose who from the group you would take to a deserted island and why.',
      'Tell us about the most expensive thing you\'ve ever bought that you didn\'t really need.',
      'Confess one of your strange habits.',
      'Tell us about one of your silly fears.',
      'Pretend you\'re afraid of an object in the room.',
      'Tell us about one of your useless talents and show us what you can do.',
      'Show off your best impromptu "magic trick."',
      'Make an origami figure out of whatever you can find in one minute.',
      'Build a tower using three objects from the room.',
      'Find three yellow objects in the house in thirty seconds.',
      'Swap an item of clothing you\'re wearing with the person to your right.',
      'Take a selfie with the ugliest face you can make.',
      'Take a photo of yourself imitating the pose of the person to your left.',
      'Make a 10-second video as if you were an influencer.',
      'Record a motivational message for the group.',
      'Read today\'s horoscope in a dramatic voice.',
      'Come up with a horoscope for the person to your right.',
      'Describe what your life will be like in ten years, without overthinking it.',
      'Declare your eternal love for an object in the room: the couch counts.',
      'Act out a tear-jerking farewell scene using a pillow.',
      'Tell me which song you know by heart and sing a bit of it.',
      'Sing a 10-second karaoke song without music.',
      'Whistle a song and have them guess it.',
      'Do a five-second beatbox.',
      'Imitate the sound of three different instruments.',
      'Pretend you\'re playing the guitar like you\'re at a concert.',
      'Dance as if you were at a club all by yourself.',
      'Teach the group a dance step.',
      'Take a group photo and give the instructions yourself.',
      'Choose the soundtrack for the evening and explain why.',
      'Tell us about the best thing that happened to you this week.',
      'Tell me one thing you\'d like to learn and why you haven\'t started yet.',
      'Make a list of three things you\'re grateful for right now.',
      'Send a nice message to someone you haven\'t written to in a while.',
      'Call your mother or a relative and tell them you love them.',
      'Send "Good morning!" with three random emojis in the family chat.',
      'Let the group choose your next task for the following shift.',
      'Strut like a model from one side of the room to the other, complete with a twirl.',
      'Act like a T-Rex with short arms until your next turn.',
      'Use a remote control or a brush as a microphone every time you speak, for one lap.',
      'Play the waiter: take everyone\'s imaginary orders with a very serious expression.',
      'Act out a movie without speaking until the group guesses what it is.',
      'Imitate a famous person chosen by the group until someone guesses who it is.',
      'Give everyone here a compliment while hopping on one leg.',
      'Try licking your elbow with all your might for ten seconds.',
      'Tell a bedtime story in thirty seconds, doing all the voices.',
      'Talk for one minute about a topic chosen by the group as if you were the leading expert on it.',
      'Say a tongue twister chosen by the group three times in a row without making a mistake.',
      'Describe what the person in front of you is doing as if you were making a nature documentary.',
      'Make five facial expressions on command: happy, angry, surprised, in love, suspicious.',
      'Dance a romantic slow dance with a broom or a pillow.',
      'Host a newscast featuring three absurd stories about the people in the audience.',
      'Play "Echo": Repeat the last word the speaker said until it\'s your turn.',
      'Speak in a whisper until it\'s your next turn, no matter what happens.',
      'Keep a huge smile on your face for three minutes, no matter what happens.',
      'Come up with a group anthem based on the tune of a famous song and sing it.',
      'Have the group pose you like a statue and stay that way for a photo.',
      'You throw a dramatic, soap-opera-style tantrum because you ran out of a cookie.',
      'Try to make the most serious person in the group laugh in thirty seconds, without touching them.',
      'Stack as many pillows as you can on top of yourself and balance for ten seconds.',
      'Make up a language and "translate" what the person to your right is saying.',
      'Pretend you\'re trapped inside an invisible box until someone "frees" you.',
      'Tell us how this group came together, in the style of a historical documentary.',
      'Address everyone formally using "Sir" or "Ma\'am" until it\'s your turn again.',
      'Create an imaginary cooking tutorial using the items in front of you.',
      'Move in slow motion until the end of the shift, including replays.',
      'Say hello in five different languages, making up the ones you don\'t know.',
      'Act like an animal until someone guesses which one it is.',
      'Respond by singing to everything you\'re told until it\'s your turn.',
      'Jump up and down ten times in place while shouting your name.',
      'Come up with a slogan for the group and say it out loud.',
      'Be the room commentator for thirty seconds.',
      'Come up with an ad for the object on your right.',
      'Speak only in whispers until it\'s your next turn.',
      'You stand there motionless, like a statue, while the others try to make you laugh.',
      'Lip-sync to a song of the group\'s choice for fifteen seconds.',
      'Imitate a famous person chosen by the group.',
      'Summarize the plot of a famous movie in exactly ten words.',
      'Say the days of the week in reverse as fast as you can.',
      'Pretend you\'ve won an Oscar and thank everyone there one by one.',
      'Walk like a robot to the door and back.',
      'Come up with a fun nickname for everyone here.',
      'Sing "Happy Birthday" as if it were a rock song.',
      'Make five different faces in five seconds.',
      'Balance a pillow on your head for a full lap.',
      'Describe your day using only sounds.',
      'Make up a weather forecast as seriously as possible.',
      'Order an imaginary pizza in an epic and dramatic way.',
      'Applaud every sentence the others say until it\'s your turn.',
    ],
    ContentTone.mix: [
      'Give a sensual massage to the inner thigh of a consenting person for thirty seconds.',
      'Whisper your dirtiest fantasy into the ear of the person to your right.',
      'Kiss a willing person on the neck and gently blow on their skin.',
      'Have a consenting person choose an item of clothing for you to remove.',
      'Fake an orgasm for fifteen seconds—with sounds and gestures—in front of everyone.',
      'Take off three items of clothing (excluding accessories) and stay that way for the rest of the game.',
      'Lick the earlobe of the person to your left (if they consent).',
      'Remove an accessory or a layer as provocatively and slowly as possible.',
      'Have someone blindfold you and guess the identities of three people in the group by kissing only their hands or arms.',
      'Replicate your favorite position with a pillow in an extremely realistic way.',
      'Rest your head on a willing person\'s lap and stay there for three rounds.',
      'Send a nude photo (or a very provocative photo) to whoever you want and show the send notification to the group.',
      'Perform a 30-second lap dance for a consenting person chosen by the group.',
      'Dance a sensual slow dance, body-to-body, with a willing partner for one minute.',
      'Use your tongue to trace the outline of the neck of the person to your left (if they consent).',
      'Hold the hand of the most attractive person in the room by slipping it under their shirt (if they\'re willing).',
      'Look into the eyes of the person you find most attractive for thirty seconds while biting your lip.',
      'Show the group the face you make when you have an orgasm: hold the pose for five seconds.',
      'Slowly kiss the chest or shoulder of a consenting person of your choice.',
      'Imitate how you react when someone performs oral sex on you—with sound.',
      'Read your sexting repertoire aloud, in an extremely serious tone.',
      'Tell the group the most risqué flirty message you\'d send to your crush right now.',
      'Describe out loud, step by step, how you would take the person to your left to bed.',
      'Teach the group your favorite move for turning someone on in less than a minute.',
      'Describe your ideal night, step by step: from foreplay to breakfast.',
      'Make a 30-second commercial about yourself as a lover, highlighting your best qualities.',
      'Tell us about your best night, including details about positions and sensations.',
      'Describe your perfect kiss and give it right away to someone who’s willing (if they’re up for it).',
      'Say out loud the dirtiest thing anyone has ever whispered to you in bed.',
      'Whisper "I want you now" in the warmest voice you can muster into the ears of three different people.',
      'Send a flirty message to the last person you were with and show the reply.',
      'Do an impression of how you flirt when you\'re drunk and just want to get laid.',
      'Show in slow motion how you use your tongue while kissing: the group rates your technique.',
      'Send "I\'m thinking about the two of us in bed" to a contact of your choice from the group.',
      'Read aloud the raunchiest chat you have on your phone, without censoring anything.',
      'Show us the most daring photo you\'ve taken or received in the last few months.',
      'Show the group your incognito browsing history from the last two days.',
      'Text "I want to do it with you" to the person you like and show them the screenshot.',
      'Send a 10-second flirty voice message to an ex chosen by the group.',
      'Tell us how far you went in the most public place you\'ve ever been.',
      'Describe the three things that turn you on the most in bed—don\'t beat around the bush.',
      'Tell us about your most embarrassing wake-up moment after a wild night of sex.',
      'Admit it—what\'s the fetish you haven\'t had the courage to try yet?',
      'Name the person here with whom you\'re most likely to end up in bed tonight.',
      'Rank the people here based solely on their potential skills in bed.',
      'Give everyone here an "attraction rating" from 1 to 10, looking them in the eyes.',
      'Tell us which couple in this room would be a wild ride in bed—and why.',
      'Choose who from the group you\'d like to see naked right now.',
      'Give one person in the group the most risqué compliment you can think of about their body.',
      'Suggest a quick "role-playing game" to the person on your right and say the first line.',
      'Walk across the room as if you were in a strip club, stop in front of someone, and wave at them.',
      'Let the group write a bold message from your phone and send it to whoever they want.',
      'Take off two items of clothing or accessories of your choice, as slowly as possible, while the group sings a sexy song.',
      'Give the person chosen by the group a firm spanking—with their consent.',
      'For ten seconds, imitate the sounds you make in bed when you reach the peak of pleasure.',
      'Slowly kiss a consenting person\'s neck, starting at the ear and working your way down.',
      'Act out your favorite sex position while fully clothed for ten seconds, giving it your all.',
      'Say out loud the name of the person in this room whom you\'d kiss right now.',
      'Give a one-minute back massage to a willing person, slipping your hands under their clothes (if they agree).',
      'Whisper in the ear of the person to your right what you would do to her if the two of you were alone in this room.',
      'Exchange three rounds of intense eye contact with the person you find sexiest without ever laughing.',
      'Describe the underwear you\'re wearing tonight in great detail.',
      'Dance to reggaeton for half a minute, grinding (with consent) against someone in the group.',
      'Have someone put an ice cube in your pants and try to hold out for a minute without screaming.',
      'Whisper the name of your favorite sex toy into someone\'s ear as if it were a prayer.',
      'Describe how you touch yourself when you\'re alone and want to finish quickly.',
      'Explain the difference between a normal kiss and a "bedroom" kiss, using theoretical examples.',
      'Act out "I\'m texting my crush to get her to come home with me," with all the stages of panic and success.',
      'Show off your best "I want to have sex" pose and explain your strategy.',
      'Tell us about the raunchiest compliment you\'ve ever received and who gave it to you.',
      'Repeat "I want more" with five different intentions: the group has to guess the right one.',
      'Do the most erotic thing you can using just one ice cube.',
      'Teach the group how to give a perfect hickey without leaving too much of a mark.',
      'Find out which scent makes you want to undress someone right away.',
      'Dance a twenty-second slow dance with someone you\'re with, whispering risqué things to them.',
      'Make the face you make when you come: the group will vote on how intense it is.',
      'Write a "good morning after sex" message that would drive anyone wild.',
      'Choose who from the group you\'d like as a "bed buddy" for a whole month.',
      'Gently bite the shoulder of a willing partner and leave them wanting more.',
      'Run your finger down the bare back of a willing partner, starting at the nape of the neck and moving down to the waist.',
      'Run an ice cube along the neck of a consenting person with your mouth.',
      'Let your hair down and let it fall over a willing person while you whisper something to them.',
      'She nibbles on the fingers of a willing person, one by one, while looking them in the eyes.',
      'Dance by slowly crouching down in front of a willing person chosen by the group.',
      'Gently brush your lips against the lips of the most attractive person without ever kissing them, for ten seconds.',
      'Have a willing person write a dirty word on your body with a finger, and try to guess what it is.',
      'Rest your forehead against the forehead of the person you find sexiest, and breathe together for twenty seconds.',
      'Stroke the back of a consenting person\'s neck while whispering the sexiest line you know to them.',
      'Kiss the wrists of three different consenting people, feigning greater desire each time.',
      'Gently massage the shoulders of the person on your right while whispering how much you love their skin.',
      'Run your tongue provocatively along the rim of a glass while staring at your crush.',
      'Bite your lower lip and hold eye contact with the most attractive person for an entire round.',
      'Slowly slip off a belt or a string and use it to tie (with consent) someone\'s wrists for a minute.',
      'Have a consenting person guide your hand wherever they want on top of your clothes for ten seconds.',
      'Recite a line from an erotic movie in the hoarsest voice you can manage, in front of everyone.',
      'Simulate a passionate kiss with the back of your hand, making it as realistic as possible.',
      'Describe to the group—while looking at a willing person—what you would do to their lips if you could.',
      'Whisper a countdown from five to one into someone\'s ear as if something were about to happen.',
      'She slowly rubs her cheek against that of a willing person, just as a cat in heat would.',
      'Bite the air near a willing person\'s neck without touching them, making them shiver.',
      'Trace a heart with your tongue on the open palm of a consenting person.',
      'Dance for half a minute, moving only your hips as sensually as possible, in front of the group.',
      'Place your hands on the hips of a consenting person and guide them in a slow dance for twenty seconds.',
      'Have a willing person breathe on your neck and react as if it were driving you crazy.',
      'Whisper "close your eyes" to a willing partner and have them guess where you\'ll touch them.',
      'Describe aloud your ideal way of waking up next to the person on your right.',
      'Pretend to undress the most attractive person in the room with your eyes, in silence, for ten seconds.',
      'Kiss a willing person on the cheek, coming dangerously close to their lips.',
      'Show how you would kiss someone in the rain, using the group as your audience and a pillow as your partner.',
      'Tell us about the time you wanted someone the most but couldn\'t have them.',
      'Run a strawberry (or your finger) over the lips of a consenting person and let them taste it.',
      'Have a willing person trace a line with their finger from your neck to your hand, and hold your breath.',
      'Repeat "come here" in three different tones until the group decides which one is the most seductive.',
      'Audition for the lead role in an adult film by performing the opening scene—fully clothed.',
      'Describe the exact spot where you\'d like to be kissed right now, and let someone try it (with consent).',
      'Use your hands to trace the silhouette of the person you find sexiest while looking them in the eyes.',
      'Whisper in the ear of the person on your left the time of day when you think about sex the most.',
      'Have a willing person gently bite your ear, and don\'t laugh for ten seconds.',
      'Dance with your back against a willing partner, guiding their movements with your hips.',
      'As you look at her, describe, detail by detail, what physically attracts you to the person on your right.',
      'Hold the gaze of a willing partner as you slowly kiss the back of their hand, working your way up toward their wrist.',
      'Make a motion to take off your shirt as slowly as possible, pausing halfway amid the group\'s protests.',
      'Whisper a spicy promise into your crush\'s ear as if it were a state secret.',
      'Describe the perfect seduction scene and cast someone here in the lead role.',
      'Kiss your own forearm passionately, showing the group exactly how you usually kiss.',
      'Have someone pour (or pour) a few drops of water on your neck and let it run down without wiping it off for one round.',
      'Look at a willing partner and mouth—without making a sound—the three words you\'d like to say to them in bed.',
      'Strut like a model down an imaginary runway, stopping to blow a kiss to your crush.',
      'Slowly stroke the arm of the person next to you as you recount your most recent erotic dream.',
      'Put on a slow song and ask the person you want most to dance—body to body.',
      'Close your eyes and identify three consenting people based solely on the scent of their skin.',
      'Whisper "You\'re all I want tonight" to the person on your right as if you really meant it.',
      'Describe what you would do to a consenting person if you had only five minutes in a locked room.',
      'Gently bite the shoulder of a pillow, pretending you\'re leaving a hickey on a partner.',
      'Hold the chin of a consenting person and bring your face close to theirs, just a breath away from their lips.',
      'Get down on one knee and recite a declaration of pure desire to the sexiest person in the room.',
      'Slowly run your hands down your sides as you stare at your crush, just like in a music video.',
      'Whisper your favorite part of foreplay into the ear of a consenting partner.',
      'Ask a consenting person to choose a body part, and give them a steamy compliment about it.',
      'Dance an improvised tango with a willing partner, ending in a pose just a few centimeters from their face.',
      'Describe how you would seduce someone using only your voice, and demonstrate it for ten seconds.',
      'Have someone write the name of the person you\'re attracted to on your neck with a finger, and have the group guess who it is.',
      'Describe the fantasy you\'d like to make come true with someone in this room.',
      'Show the group how you move on top of a partner, using a pillow, for ten seconds.',
      'Whisper to the most attractive person what you notice about her first every time she walks into a room.',
      'Run your finger slowly over your lips while holding the gaze of the person you desire.',
      'Have the group suggest three dirty words, and use them in a seductive sentence directed at your crush.',
      'Slowly kiss the knuckles of a consenting person, letting your gaze wander up to their eyes.',
      'Describe your favorite body scent in a partner, and then (with consent) smell someone\'s neck to check.',
      'Have a willing partner whisper their fantasy in your ear, and respond only with your eyes.',
    ],
    ContentTone.hot: [
      'Give the person to your right a French kiss, if they\'re willing.',
      'Have a willing person remove a piece of clothing from you using their teeth.',
      'Mimic your favorite position on a consenting person for thirty seconds.',
      'Describe out loud how you would take the person in front of you to bed.',
      'Show us the face you make when you reach orgasm.',
      'Lick the neck of the person to your left until they shiver, if they consent.',
      'Give a clearly visible hickey on the shoulder of a willing person.',
      'Sit astride a willing partner and stay there for an entire round.',
      'Fake a loud, realistic orgasm for twenty seconds in front of everyone.',
      'Whisper in the other person\'s ear the naughtiest thing you\'d do to them.',
      'Perform a one-minute lap dance for a consenting person chosen by the group.',
      'Gently nibble on the earlobe of the person to your right, if they\'re okay with it.',
      'Pass an ice cube from your mouth to the mouth of a consenting person.',
      'Show the group how you move your hips during sex while standing.',
      'Lick a drop of a beverage off the neck of a consenting person.',
      'Take off one item of clothing and keep it off for the next three rounds.',
      'Show us what position you sleep in by lying down on the floor.',
      'Kiss any part of the body you like on a consenting person.',
      'Pretend to perform oral sex on a banana or another object for fifteen seconds.',
      'Dance a slow, close-contact dance with a willing partner, with your hands free.',
      'Describe in great detail the last time you masturbated.',
      'Use gestures to show just how talented your most memorable ex is.',
      'Place your hand on a consenting person\'s thigh and leave it there for one round.',
      'Imitate the sounds you make in bed when you\'re about to come.',
      'Lick a consenting person\'s finger in the most provocative way possible.',
      'Take off your clothes until you\'re in your underwear, and switch places with the person in front of you.',
      'Show how sensual you can be by slowly taking off your socks or shoes.',
      'Gently bite the neck of a consenting person, leaving a bite mark.',
      'Demonstrate the tongue movement you would use in a French kiss, using one hand.',
      'Spank a willing partner, and let them spank you in return.',
      'Describe the sexual fantasy that turns you on the most—without holding back.',
      'Pretend to ride someone while sitting in a chair for twenty seconds.',
      'Give a consenting person a sensual back massage for one minute.',
      'Show how to kiss passionately using the back of your hand.',
      'Expose your shoulder and let a willing person kiss you there.',
      'Describe out loud the wildest erotic dream you can remember.',
      'Mimic the missionary position in the air for ten seconds, with expression.',
      'Whisper a moan into the ear of the person to your right, if they consent.',
      'Have a willing person tie your wrists together with a scarf for one round.',
      'Describe what turns you on the most about the body of the person in front of you.',
      'Show us how you would take off your bra with just one hand, with your eyes closed.',
      'Lick the whipped cream or sugar off a consenting person\'s finger.',
      'Show off your best close-up of a seductive gaze, and hold it for ten seconds.',
      'Pretend to give a cucumber a blowjob with the utmost seriousness for fifteen seconds.',
      'Have a willing partner breathe on your neck, and react the way you would in bed.',
      'Describe the time you had the most intense orgasm of your life.',
      'Do a pole dance using a chair as a pole for thirty seconds.',
      'Hold your lips one centimeter away from the lips of the person in front of you—without kissing them—for ten seconds.',
      'Let out a rising moan that ends in a scream, just like a real climax.',
      'Run your tongue over your upper lip while staring at the person who attracts you the most here.',
      'Take off your underwear under your clothes and show it to the group.',
      'Have a consenting person bite your neck for five seconds.',
      'Describe your favorite sex toy and how you use it.',
      'Pretend to undress everyone present with your eyes, one by one.',
      'Perform a slow, seductive belly dance for twenty seconds.',
      'Slowly lick your finger and put it in your mouth, looking at the person in front of you.',
      'Whisper to a consenting person what position you\'d like them to be in.',
      'Rest your head on a willing person\'s lap for an entire round.',
      'Show how you move your tongue when you\'re performing oral sex, on a popsicle, or on a spoon.',
      'Have a willing person massage your thighs for thirty seconds.',
      'Describe the spot on your body that drives you wild when it\'s touched.',
      'Pretend to have passionate sex with a pillow for twenty seconds.',
      'Kiss the hand of a willing person, working your way up to the elbow.',
      'Show off how cheeky you can be by mimicking a ten-second striptease.',
      'Whisper in each member\'s ear, one by one, how hot you find them.',
      'Have someone cover your eyes and guess who\'s kissing your cheek from among the willing participants.',
      'Describe how you like to be touched during foreplay.',
      'Mimic the doggy-style position in the air for ten seconds, with conviction.',
      'He licks the rim of the glass in an obscene way while everyone watches.',
      'Do a wild 30-second twerk in front of the group.',
      'Place the hand of a willing partner on your hip and guide them as you dance.',
      'Tell us about the wildest thing you\'ve ever done in bed to impress someone.',
      'Pretend to wrap your legs around someone using your arms, while standing.',
      'Have a consenting person gently touch the back of your neck and show how you react.',
      'Describe in detail the sexual encounter you\'d like to have tonight.',
      'Make the sexiest sound you can while looking into the eyes of someone you\'re attracted to.',
      'Kiss the wrist of a consenting person and slowly move your lips upward.',
      'Show how you would arch your back at the height of pleasure.',
      'Whisper three dirty words into the ear of the person to your left, if they\'re willing.',
      'Have a willing person bite your finger in a provocative way.',
      'Describe the part of a person\'s body here that makes the biggest impression on you.',
      'Fake a slow orgasm by just lightly touching your neck and face.',
      'Make a seductive gesture with your eyes and lips toward the person you like the most.',
      'Take off your shirt or unbutton it and stay that way for two rounds, if you\'re up for it.',
      'Lick the salt off a willing person\'s hand before taking a shot.',
      'Place your hands on a willing partner\'s hips and make them dance with you.',
      'Describe the dirtiest thing anyone has ever whispered to you in bed.',
      'Pretend to lick something very intimate on a piece of fruit for ten seconds.',
      'Let a consenting person hug you from behind, and stay that way for one round.',
      'Show us how you move when you\'re on top during sex, on a chair.',
      'Whisper your most forbidden desire into the ear of the person standing before you.',
      'Slowly kiss a consenting person\'s neck while counting to ten.',
      'Show off your repertoire of moans in three different intensities.',
      'Have a willing person gently blow on your ear and see how you react.',
      'Describe how you would use your hands on the person in front of you, if you could.',
      'Simulate a seductive dance by slowly removing a belt or accessory.',
      'Lick the sugar off the lips of a consenting person, if they agree.',
      'Do your best impression of how you call someone\'s name in bed.',
      'Press your forehead against the forehead of the person in front of you and breathe deeply for ten seconds.',
      'Describe the threesome fantasy you\'d have and who you\'d do it with.',
      'Act out a full striptease while staying fully clothed, in thirty seconds.',
      'Have a consenting person gently scratch your back through your clothes.',
      'Sway your hips as you walk into a room to turn everyone\'s heads.',
      'Whisper to a willing person what you would do to them if we were alone.',
      'Kiss the inside of the wrist of the person in front of you while keeping your eyes locked on them.',
      'Describe the sound that turns you on the most during sex.',
      'Pretend you\'re having sex while standing, leaning against the wall for fifteen seconds.',
      'Use your hands to show the size of the most impressive sexual experience you\'ve ever had.',
      'Lick your index finger and brush it against your lips while looking at the person who attracts you the most.',
      'Have a consenting person gently pull your hair and show how you react.',
      'Describe the most absurd place where you\'d like to have sex.',
      'Imitate the 69 position using a pillow for ten seconds.',
      'Gently caress a consenting person\'s face, moving down toward their neck.',
      'Whisper a list of three things you\'d do to the person in front of you tonight.',
      'Show how to dance close to someone at a nightclub, using a willing partner.',
      'Have a consenting person give you a kiss on the neck.',
      'Describe the most exciting thing that has ever happened to you in a public place.',
      'Pretend to moan the name of the sexiest person in the room.',
      'Slowly lick the outside of the hand of the person in front of you.',
      'Show us how you undress when you want to seduce someone—take your time.',
      'Run your hand through a consenting person\'s hair and bring your face closer.',
      'Describe what you would do with your lips to the person in this room who attracts you the most.',
      'Pretend to be handcuffed to the bed for ten seconds, with a convincing expression.',
      'Have a willing person stroke your bare back, if they agree.',
      'Let out a muffled groan, as if you were trying to hold it in while in a public place.',
      'Whisper in the ear of the person on your right what your fetish is, if they consent.',
      'Kiss the neck of a pillow as if it were the person you desire most.',
      'Describe the wildest thing you\'d like to try at least once.',
      'Pretend to be spanked by reacting with a moan for ten seconds.',
      'Slowly lick a lollipop or popsicle while staring at the person you like.',
      'Show us how you arch your back when someone kisses you in just the right spot.',
      'Place your lips on the shoulder of a willing person and move up toward their ear.',
      'Describe the foreplay that never gets old and sends you into ecstasy.',
      'Pretend to have passionate sex against a door for fifteen seconds.',
      'Have a consenting person gently bite your lower lip.',
      'Put on your most seductive look as you run your hands over your body.',
      'Whisper to the person in front of you just how much you want them, using explicit words.',
      'Sensually kiss the fingers of a consenting person, one by one.',
      'Describe the position in which you reach orgasm most easily.',
      'Pretend to do an erotic dance by slowly grinding against a chair.',
      'Lick away an imaginary drop from the chest or neck of the person in front of you, if they consent.',
      'Show me how you move under the sheets when you make love.',
      'Place your hand on the heart of a consenting person and slowly move it down toward the abdomen.',
      'Describe the longest orgasm you\'ve ever had and how it happened.',
      'Pretend to suck your thumb in a suggestive way for ten seconds while looking at the group.',
      'Let a willing partner hold you tight and whisper a moan.',
      'Make your "climax" face while arching your back for five seconds.',
      'Whisper in each person\'s ear what you\'d like to do to them, as you go around the room.',
      'Show how you react when someone nibbles your neck—with your voice and shivers.',
      'Act out your most intense moment of pleasure—using your voice and body movements—for ten seconds.',
    ],
  };

  static const Map<String, List<String>> verita = {
    ContentTone.normal: [
      'What\'s the most embarrassing thing you\'ve ever done in public?',
      'What was the biggest lie you ever told as a kid?',
      'What\'s your guilty pleasure when it comes to music?',
      'Which movie made you cry the most?',
      'What\'s the silliest thing you\'ve ever argued about?',
      'What do you think is your worst flaw?',
      'What flaw do your friends say you have that you don\'t recognize at all?',
      'What\'s the most expensive thing you\'ve ever broken?',
      'Have you ever pretended to be sick to get out of something?',
      'What\'s the excuse you use most often?',
      'What do you do when you\'re alone and no one can see you?',
      'What\'s your strangest habit?',
      'How much time do you actually spend on your phone every day?',
      'What\'s the app you open most often for no particular reason?',
      'What was the last thing you actually searched for on the internet?',
      'What\'s the oldest photo you have on your phone?',
      'Who was the last person you texted?',
      'What\'s the most embarrassing message you\'ve ever sent?',
      'Have you ever sent a message to the wrong person? What did it say?',
      'What\'s the nicest thing anyone has ever said to you?',
      'What\'s the strangest compliment you\'ve ever received?',
      'Who is the most important person in your life?',
      'Who would you call if you had a serious problem at 3 a.m.?',
      'What do you value most in a friend?',
      'What was the best moment of this year?',
      'What was the hardest moment of this year?',
      'What are you most afraid of when it comes to the future?',
      'What\'s your dream that you haven\'t told anyone about yet?',
      'What would you do if you didn\'t have to work anymore starting tomorrow?',
      'If you could change one decision, what would it be?',
      'What are you most proud of?',
      'What\'s the compliment you\'d like to receive?',
      'What puts you in a good mood in five minutes?',
      'What\'s the thing that makes you get angry the fastest?',
      'What\'s the habit you just can\'t seem to break?',
      'Are you more organized or more disorganized than you admit?',
      'When was the last time you laughed until you cried?',
      'What\'s the bravest thing you\'ve ever done?',
      'What would you never do for money?',
      'How much money would you pay to have your hair shaved off?',
      'What\'s your hidden talent?',
      'What\'s one thing that everyone can do except you?',
      'What\'s the hardest thing you\'ve ever learned?',
      'On a scale of 1 to 10, how would you rate your life right now?',
      'What do you need to score a perfect 10?',
      'What\'s the most beautiful place you\'ve ever been to?',
      'Where would you like to live if you could choose?',
      'What trip would you take again tomorrow?',
      'What was the worst vacation you\'ve ever taken?',
      'Have you ever missed a flight or a train? How did it turn out?',
      'What\'s the strangest thing you\'ve ever eaten?',
      'What\'s the dish you\'re best at cooking?',
      'What\'s your comfort food?',
      'Would you eat the same dish every day for a month for 1,000 euros?',
      'What\'s the most useless thing you\'ve ever bought?',
      'How long does it really take you to get ready?',
      'What\'s the one piece of clothing you won\'t throw away even though you should?',
      'What fashion trend did you follow that you now reject?',
      'What haircut do you regret?',
      'Would you get a tattoo? Where and what?',
      'What\'s the one thing you\'ve done just to make someone else happy?',
      'Have you ever pretended to understand something so you wouldn\'t look bad?',
      'What\'s the topic you bluff about the most?',
      'What\'s the book you say you\'ve read but haven\'t actually finished?',
      'Which TV series did you stop watching halfway through?',
      'Which character is most like you?',
      'If you were an animal, which one would you be, and why?',
      'If you had to change your name, which one would you choose?',
      'What nickname did you hate as a kid?',
      'What\'s the most boring thing you\'ve ever done for work?',
      'Which coworker or classmate couldn\'t you stand, and why?',
      'What\'s the one thing you\'ve been putting off the longest?',
      'What time do you actually go to sleep?',
      'How many times do you hit the snooze button before getting out of bed?',
      'What\'s your favorite spot in the house?',
      'What would you take with you if you had to flee your home in one minute?',
      'What\'s the item you\'re most attached to?',
      'What\'s the best gift you\'ve ever received?',
      'What\'s the worst gift you\'ve ever received?',
      'Have you ever reused a gift?',
      'What\'s the New Year\'s resolution you\'ve never kept?',
      'What habit would you like to break?',
      'What habit would you like to start?',
      'Who in the group would you call for some serious advice?',
      'Who in the group makes you laugh the most?',
      'What did you learn from the people here tonight?',
      'What would you like the group to know about you?',
      'What\'s the question you were hoping wouldn\'t come up tonight?',
      'Is there something you\'ve always wanted to ask someone here?',
      'If you had to describe this evening in one word, what would it be?',
      'What\'s the most embarrassing thing that\'s ever happened to you at school?',
      'What\'s the most absurd dream you can remember having?',
      'What\'s the white lie you tell most often?',
      'What food do you pretend to like just to be polite?',
      'If you had a superpower for one day, what would you do first?',
      'Which famous person would you like to have over for dinner, and what would you ask them?',
      'What\'s the funniest thing that\'s ever happened at one of your family gatherings?',
      'If you could swap lives with someone for a day, who would you choose?',
      'What\'s the song you always sing while messing up the lyrics?',
      'What\'s the strangest thing you\'ve ever done out of boredom?',
      'Have you ever burst out laughing at a time when it was absolutely forbidden? Tell us about it.',
      'What\'s the embarrassing moment that makes you laugh now but totally crushed you at the time?',
      'What\'s the strangest thing you have in your room?',
      'What\'s the most childish thing you still do today?',
      'If your life were a movie, which actor would play you?',
      'What was your worst "brilliant" idea?',
      'Have you ever sung in front of the mirror using a hairbrush as a microphone?',
      'What\'s the word you always mispronounce?',
      'What\'s your craziest record—if anything can count as a record?',
      'What would you do first if you won a million tomorrow morning?',
      'What\'s the most useless app you\'ve ever downloaded but never used?',
      'Have you ever fallen asleep in a weird place? Where?',
      'What\'s the one thing you look up online because you\'re embarrassed that you don\'t know it?',
      'What\'s the dish you\'ve messed up the most spectacularly?',
      'What\'s a rule in your house that you thought was normal but turned out to be really weird?',
      'Which cartoon character scared you when you were a kid?',
      'What\'s the most absurd thing you believed as a child?',
      'Have you ever responded to someone who was greeting someone else?',
      'Which notification makes you the most anxious?',
      'What\'s the song that always brings back memories for you?',
      'If you could teleport yourself anywhere for a day, where would you go?',
      'What job did you dream of having when you were a child?',
      'What\'s the one thing that everyone loves but you really don\'t?',
      'What trash TV show do you watch, and would you defend it tooth and nail?',
      'Have you ever talked to your pet or your plants as if they understood everything?',
      'What\'s the one thing you\'re worst at but still do with enthusiasm?',
      'What\'s the best message you have saved on your phone?',
      'What\'s the outlandish theory that you kind of believe in even though you know it\'s absurd?',
      'What\'s your survival plan in the event of a zombie apocalypse?',
      'Would you rather be able to fly or read minds, and why?',
      'What\'s the most creative excuse you\'ve ever used for being late?',
      'What did you do as a child that you wish were socially acceptable today?',
      'Who do you think would survive the longest on a desert island?',
      'What\'s the funniest Italian word you know?',
      'What sound or noise do you absolutely can\'t stand?',
      'What\'s the nicest thing you\'ve ever done for someone in secret?',
      'Have you ever won anything in a contest or a raffle? What?',
      'Which ice cream flavor do you think should be banned by law?',
      'What\'s the movie that everyone loves but you\'ve never been able to finish watching?',
      'What\'s a food you pretend not to like but would secretly eat?',
      'What\'s the song you sing only when you\'re sure no one can hear you?',
      'What\'s the craziest thing you do when you\'re sure no one is watching?',
      'What\'s your most useless talent?',
      'What is your most irrational fear?',
      'What\'s the worst gift you\'ve ever re-given?',
      'What\'s the most embarrassing thing in your YouTube history?',
      'What\'s the excuse you use most often to leave a party?',
      'What\'s a cartoon you\'d still watch right now without feeling embarrassed?',
      'If you could swap jobs with one of the people here for a day, who would you choose?',
      'What\'s the compliment you like to hear the most?',
    ],
    ContentTone.mix: [
      'How was your first time? Age, place, position, and a rating from 1 to 10.',
      'How many people have you slept with? Give the exact number—don\'t round it off.',
      'What\'s the most absurd or risky place you\'ve ever done it?',
      'Have you ever had anal sex? Did you like it? Be honest.',
      'Have you ever slept with someone on the very day you met them? How many times?',
      'What was your wildest one-night stand, and where did it happen?',
      'Have you ever had sex with a friend and then acted like nothing happened? Who was it?',
      'Have you ever sexted with more than three people at the same time?',
      'What\'s the raunchiest message you\'ve ever sent or received? Quote it.',
      'Have you ever sent or received a sexually explicit video of yourself? Would you do it again?',
      'Have you ever received an unsolicited risqué photo? What was your real reaction?',
      'What\'s your wildest erotic fantasy that you\'ve never told anyone about?',
      'Have you ever had a threesome? If not, who from this group would you do it with?',
      'Is there anyone in this room you\'d like to spend the night with? One name.',
      'Would you rather have an insane three-minute orgasm or an hour of perfect cuddling?',
      'Who was the best lover you\'ve ever had, and why? What made him special?',
      'Have you ever kissed two different people in the same hour? Where were you?',
      'Have you ever bitterly regretted sleeping with someone while you were actually doing it?',
      'Have you ever woken up next to someone and slipped out the window or snuck out?',
      'What matters most in bed: technique, size, or mental connection?',
      'In bed, are you more dominant or submissive? Give an example of something you like to do.',
      'Lights on, mirrors, and videos—or total darkness? Explain your choice.',
      'What\'s the most exciting compliment you\'ve ever received during sex?',
      'Have you ever faked an orgasm to make sex end sooner? How many times?',
      'What\'s the most embarrassing thing that\'s ever happened to you while you were doing it?',
      'Have you ever been caught by your parents or a stranger while you were in the middle of something?',
      'Have you ever pretended to be asleep to avoid going to sleep? Because you didn\'t feel like it?',
      'Have you ever lied about your performance to impress your friends?',
      'What was your longest sex marathon? How many times in a day?',
      'Is there anyone in this group who has ever turned you on just by talking?',
      'What\'s the first thing you notice about someone that makes you think, "I want to sleep with them"?',
      'What\'s the sexiest piece of clothing you can think of? And what\'s a total turn-off for you?',
      'Do you consider yourself good in bed? What\'s your unbeatable strength?',
      'What would you like to learn to do better in bed? Have you ever watched any tutorials?',
      'What\'s the cheesiest pickup line you\'ve ever used that actually worked?',
      'Have you ever flirted with a close friend\'s partner? How far did it go?',
      'Have you ever given someone a fake phone number after making out with them? Why?',
      'What\'s the boldest thing you\'ve ever done in a crowded public place?',
      'Have you ever had a summer fling that ended with a racy video or photo?',
      'What was the biggest age difference you\'ve ever had in a sexual relationship?',
      'Have you ever kissed someone in this room without the others knowing?',
      'Which one of us would you kiss right away if the lights went out for a minute?',
      'Looking at him now, who do you think is the "wildest" of us in bed?',
      'Have you ever used a dating app just for casual sex? How many matches have ended up in bed?',
      'What\'s the most compromising chat you have on your phone right now?',
      'Have you ever texted an ex at 3 a.m. just because you felt like it?',
      'What do you miss most about your last partner in bed?',
      'Have you ever had a secret affair with someone who was already in a relationship? How did it end?',
      'Have you ever consciously been "the other"—whether male or female? Did you feel guilty?',
      'What\'s your strangest or most shameful "kink"?',
      'Above or below? In front or behind? Answer quickly, without thinking.',
      'Have you ever experienced pain in bed and found that you liked it?',
      'Have you ever had sex in an office or at work?',
      'Have you ever touched yourself while thinking about someone in this room?',
      'Which part of your body gets the most compliments in bed?',
      'Have you ever done a striptease for someone? How did it go?',
      'What\'s the dirtiest thing you\'ve ever said to someone while you were having sex?',
      'If you could choose a famous person for a one-night stand, who would it be?',
      'Have you ever had sex in the ocean, a swimming pool, or a public hot tub?',
      'What time of day do you usually feel the most excited?',
      'What do you usually wear to bed when you\'re with someone you want to tease?',
      'Have you ever had sex while wearing socks? The group will judge you if you say yes.',
      'What is the position that you find most tiring but that gives you the most pleasure?',
      'Have you ever tried tantric sex or really long sessions? Tell us about it.',
      'Have you ever used food or ice during foreplay? How did it go?',
      'What\'s the unmistakable signal you send when you want to do it right away?',
      'Which one of us would you take into a private room right now, if you could?',
      'What\'s the first thing that makes you realize that someone really wants you?',
      'Have you ever kissed someone of the same sex? Did you enjoy it, or were you just curious?',
      'What is the seemingly innocent gesture that turns you on more than any other?',
      'Do you prefer to seduce or be seduced? Give a specific example of your latest conquest.',
      'What\'s the boldest thing you\'ve ever asked for in bed, and how was it received?',
      'Have you ever had a sexual dream about someone in this room?',
      'What part of your partner\'s body makes you completely lose your mind?',
      'How long does the perfect night last for you, and how many times would you like to do it?',
      'Have you ever used a sex toy with your partner? If not, would you like to try it?',
      'What\'s the biggest lie you\'ve ever told to get someone to sleep with you?',
      'Have you ever had a secret crush on one of your partner\'s friends?',
      'Where in your house do you like doing it best, other than in bed?',
      'Have you ever had sex on a first date? Did you regret it, or did you do it again?',
      'What\'s the one phrase that makes you fall head over heels for someone instantly?',
      'Would you prefer a very slow erotic massage, or would you rather get right to it?',
      'What\'s the wildest thing you\'ve ever worn to drive someone crazy?',
      'Have you ever accidentally spied on or overheard two people doing that? Tell us about it.',
      'What\'s your longest foreplay session, and would you like it to be longer or shorter?',
      'If you had to describe your style in bed with just one word, what would it be?',
      'Have you ever had a secret encounter in a public restroom or in a car?',
      'When was the last time you wanted someone you couldn\'t have?',
      'Have you ever fallen in love with someone just because of the way they kissed?',
      'What\'s one thing no one would ever imagine about you in bed?',
      'Have you ever sent a sexy text to the wrong person? How did it turn out?',
      'Who in this room do you think is the best at flirting without anyone noticing?',
      'What\'s your absolute limit in bed—the one thing you\'d never do?',
      'Have you ever kissed someone just to make someone else jealous?',
      'What part of yourself would you like someone to kiss more often?',
      'Have you ever been in a relationship based solely on sex? How long did it last?',
      'What\'s a fantasy you share with your partner but have never acted on?',
      'What turns you on more—a person\'s voice, their gaze, or their hands?',
      'Have you ever pretended not to be interested in someone you actually wanted very much?',
      'What was the longest time you spent flirting before you finally ended up in bed with someone?',
      'Have you ever had sex while listening to a specific song? Which one?',
      'What\'s the physical compliment that makes you feel instantly desirable?',
      'Have you ever had a purely physical case of love at first sight? With whom, and how did it go?',
      'Do you prefer slow, deep kisses or quick, passionate ones?',
      'What\'s the naughtiest thing someone whispered to you while you were doing it?',
      'Have you ever had feelings for two people at the same time? How did you handle it?',
      'What scent—whether your own or someone else’s—do you associate with the best sex you’ve ever had?',
      'Have you ever shamelessly flirted with someone right in front of your partner?',
      'What\'s a position you\'d like to try but have never had the courage to suggest?',
      'Have you ever had a threesome? If not, would you do it, and with whom here?',
      'What makes you lose the urge instantly right when you\'re about to do it?',
      'What\'s the sexiest thing a person can do while fully clothed?',
      'Have you ever had a fling with someone much older or younger than you?',
      'What\'s your secret signal to let someone know you want them tonight?',
      'Have you ever gotten turned on at a totally inappropriate moment? Where were you?',
      'What is it that makes you an unforgettable lover, according to those who have been with you?',
      'Have you ever found yourself thinking about an ex while you were in bed with someone else?',
      'What\'s the dirtiest word you like to hear whispered in your ear?',
      'Have you ever kissed someone when you were feeling a rush of adrenaline, like right after a dangerous situation?',
      'Do you prefer planned, well-organized sex or spontaneous, passionate sex?',
      'When was the time you came closest to being caught in the act?',
      'Have you ever written or received an erotic letter or message that you still have?',
      'Who in this room would you kiss, who would you sleep with, and who would you avoid? Be honest.',
      'What\'s the naughtiest thought that crosses your mind when you see someone you really like?',
      'Have you ever had a vacation adventure that you\'ve never told anyone about?',
      'What role-playing game would you like to try at least once in your life?',
      'Have you ever woken up aroused next to a friend? What did you do?',
      'What\'s the most embarrassing thing you\'ve ever searched for online about sex?',
      'Have you ever been afraid of letting someone down in bed? How did it go in the end?',
      'When did you feel most desired?',
      'Do you prefer making love in the dark or looking into your partner\'s eyes the whole time?',
      'Have you ever kissed more than one person in the same night? How many?',
      'What\'s the craziest thing you\'d do for a night with the person you desire?',
      'Have you ever had to hold back your moans so no one would hear you? Where?',
      'What is your secret erogenous zone that few people have discovered?',
      'Have you ever made the first move, without hesitation, with someone you\'d just met?',
      'What makes you feel most confident when you\'re naked?',
      'Have you ever been in a long-distance relationship that relied solely on steamy video calls?',
      'What is the erotic memory that comes back to you most often when you\'re alone?',
      'If your dream partner asked you for just one thing in bed, what would you want it to be?',
      'Have you ever had make-up sex after a heated argument? Was it better?',
      'Who was the person you had the strongest connection with in bed, and why?',
      'Have you ever tried to resist a temptation and then failed miserably? With whom?',
      'What part of your ideal partner\'s body do you look at first?',
      'Does it turn you on more to be watched or to watch while you\'re doing it?',
      'Have you ever been in a "friends with benefits" arrangement that ended badly? Tell us about it.',
      'What\'s the most romantic and the naughtiest thing you\'d want to do on the same night?',
      'Who do you think in this room is trying to hit on you right now?',
      'What is the most personal question you\'d like to ask someone here tonight?',
      'What\'s the one thing you\'d be excited to do right now, if the game allowed it?',
    ],
    ContentTone.hot: [
      'Have you ever tied someone up or been tied up during sex?',
      'Have you ever tasted your partner\'s semen or ejaculate?',
      'Would you like to have a threesome? With who here?',
      'What\'s the riskiest place you\'ve ever done it?',
      'On average, how many times a day do you masturbate?',
      'What is the sexual position that helps you reach orgasm the fastest?',
      'Have you ever faked an orgasm? With how many people?',
      'What\'s the dirtiest thing anyone has ever whispered to you in bed?',
      'Have you ever had oral sex in a public place?',
      'Who here would you have sex with without a second thought?',
      'What\'s your favorite sex toy, and how often do you use it?',
      'Have you ever had an orgasm just from oral sex?',
      'Does giving or receiving oral sex turn you on more?',
      'Have you ever sent an intimate video to someone?',
      'What\'s the sexual fantasy you\'ve never confessed to anyone?',
      'Have you ever had sex with more than one person in the same night?',
      'Which part of your body drives you wild when it\'s touched?',
      'Have you ever tried bondage, or does the idea turn you on?',
      'How long was the longest sexual encounter you\'ve ever had?',
      'Have you ever had sex on a first date?',
      'What\'s the kinkiest thing you\'ve ever done in bed?',
      'Have you ever kissed someone of the same sex?',
      'Have you ever masturbated while thinking about anyone here?',
      'How many partners have you had so far?',
      'Have you ever had anal sex? Did you enjoy it?',
      'What is your most secret erogenous zone?',
      'Have you ever used handcuffs or restraints during sex?',
      'How long does it usually take you to reach orgasm?',
      'Have you ever had sex in a car? Where were you parked?',
      'Who among those present do you think is the best in bed?',
      'Have you ever tried spanking—either giving it or receiving it?',
      'What\'s the wildest thing you\'ve ever done to turn a partner on?',
      'Have you ever had sex while other people were in the next room?',
      'Do you like having sex in the dark or with the lights on?',
      'Have you ever been in a relationship with someone much older or younger than you?',
      'What\'s your most unusual fetish?',
      'Have you ever had sex in the water—in a pool or at the beach?',
      'Ideally, how many times a week would you like to have sex?',
      'Have you ever tried having sex while blindfolded?',
      'Which of your exes would you have sex with again, even if just for one night?',
      'What\'s the one position you can\'t stand in bed?',
      'Have you ever had a multiple orgasm?',
      'Have you ever licked or kissed an unconventional part of your partner\'s body?',
      'What\'s the dirtiest thought you\'ve had today?',
      'Have you ever had sex with someone whose name you couldn\'t remember?',
      'Does the idea of being watched while having sex turn you on?',
      'Have you ever used food during foreplay? What?',
      'What fantasy would you like to fulfill with one of the people here?',
      'Have you ever had sex at someone\'s parents\' house?',
      'On a scale of one to ten, how important is a partner\'s physical appearance to you?',
      'Have you ever experienced consensual pain during sex and enjoyed it?',
      'What\'s the strangest thing that\'s ever turned you on?',
      'Have you ever had a relationship with two people at the same time?',
      'Do you masturbate more in the morning or in the evening?',
      'Have you ever had phone sex or sex via video call?',
      'Where on your body would you like to be kissed most often?',
      'Have you ever acted out a porn scene with a partner?',
      'Who here would you like to share a French kiss with?',
      'Have you ever been in a relationship just for sex?',
      'What was the most embarrassing orgasm you\'ve ever had to explain?',
      'Have you ever worn special lingerie or underwear to seduce someone?',
      'Do you like talking dirty during sex, or does it make you uncomfortable?',
      'Have you ever had sex in a public restroom?',
      'How many minutes does your foreplay usually last?',
      'Have you ever tried tantric sex—or slow, drawn-out sex?',
      'What\'s the naughtiest thing you\'ve ever asked for in bed?',
      'Have you ever had sex with a coworker or a boss?',
      'Does passionate sex or tender sex turn you on more?',
      'Have you ever had a date arranged solely online for sex?',
      'What part of your body are you most proud of in bed?',
      'Have you ever had sex outdoors, in the woods, or in a park?',
      'If you were single tonight, who here would you flirt with?',
      'Have you ever had more than one orgasm during the same sexual encounter?',
      'What\'s the most forbidden thing you\'d like to try at least once?',
      'Have you ever had sex with someone who was much more experienced than you?',
      'Do you like being dominated, or do you prefer to be in control?',
      'Have you ever had sex in the shower or in the bathtub?',
      'What\'s your record for the number of times you\'ve had sex in a single day?',
      'Have you ever kissed two people on the same night?',
      'What\'s the position in which you feel sexiest?',
      'Have you ever had sex while on the phone with someone else?',
      'Have you ever gotten turned on at a totally inappropriate moment?',
      'Have you ever had sex with the wrong person and regretted it?',
      'What\'s the most intimate thing you\'ve ever confessed to a partner?',
      'Have you ever tried having sex with a shared vibrator?',
      'Who among those present do you think you have the most sexual chemistry with?',
      'Have you ever had sex on a table or a kitchen counter?',
      'Do you like watching sexy videos by yourself or with a partner?',
      'Have you ever had sex in an elevator or in an unusual place?',
      'What\'s the most exciting compliment you\'ve ever received about your body?',
      'Have you ever tried role-playing in bed? What kind of scenario?',
      'How many different positions can you do in a single sexual encounter?',
      'Have you ever had an orgasm just from having your neck or ears stimulated?',
      'What\'s the one thing that makes you want to have sex right away?',
      'Have you ever had sex in a tent or while camping?',
      'Have you ever fallen in love with someone just because of how they were in bed?',
      'Have you ever used oils or lotions during sex or massages?',
      'Who here have you never flirted with, but have thought about doing so?',
      'Have you ever had sex without saying a word the whole time?',
      'Does kissing the neck or the lips turn you on more?',
      'Have you ever had sex in a hotel by the hour?',
      'What\'s the wildest thing a partner has ever suggested to you?',
      'Have you ever tried being tied up, hands and feet?',
      'Who here would you like to spend a night of passion with?',
      'Have you ever had sex that was cut short right when it was getting good? By whom?',
      'Do you like having sex with music playing or in total silence?',
      'Have you ever licked food off your partner\'s body?',
      'What fantasy helps you reach orgasm the fastest?',
      'Have you ever had sex with someone you just met while on vacation?',
      'How loud are you in bed, on a scale of one to ten?',
      'Have you ever experienced spanking as part of a sexual game?',
      'What\'s the one thing that drives you wild during foreplay?',
      'Have you ever had sex in a place where you could have been caught?',
      'Have you ever masturbated in a public place?',
      'Have you ever wished a friend\'s current or former partner were here?',
      'What\'s the most exciting moment you remember with a partner?',
      'Have you ever tried having sex while blindfolded and with your hands tied?',
      'Which famous person would you have sex with without hesitation?',
      'Have you ever had sex more than three times in one night?',
      'Do you prefer morning sex or nighttime sex?',
      'Have you ever kissed someone just on a dare and then ended up liking it?',
      'What\'s the sexiest thing you\'ve ever written in a message?',
      'Have you ever had sex at a friend\'s house during a party?',
      'What\'s your weak spot when someone tries to seduce you?',
      'Have you ever tried having sex with a new accessory or toy?',
      'Who here do you imagine spending a night to remember with?',
      'Have you ever had sex at work?',
      'Does eye contact or words turn you on more during sex?',
      'Have you ever had sex so intense that it left you completely drained?',
      'What\'s the dirtiest thing you\'ve ever done to please a partner?',
      'Have you ever had sex on a beach at night?',
      'Do you like being bitten during sex?',
      'Have you ever had an orgasm so intense that it almost made you feel embarrassed?',
      'Which part of your partner\'s body do you kiss first?',
      'Have you ever tried having sex in front of a mirror?',
      'Who among those here would you share your most erotic secret with?',
      'Have you ever had sex with someone you swore you\'d avoid?',
      'Do you like to take the initiative or be seduced?',
      'Have you ever had a fantasy about someone you shouldn\'t?',
      'What\'s the boldest thing you\'d wear just for a special night out?',
      'Have you ever had sex while it was raining, outside or near an open window?',
      'Have you ever gotten turned on watching someone undress without them knowing?',
      'Have you ever had more than one partner in the same week?',
      'What\'s the one thing that makes you realize right away that you want to sleep with someone?',
      'Have you ever had sex and laughed because something embarrassing happened?',
      'Who here would you like to play a game of seduction with?',
      'Have you ever had sex while thinking about someone other than the person you were with?',
      'What\'s the most exciting thing someone has ever told you they want to do to you?',
      'Have you ever had sex that was so quiet you had to hold back every moan?',
      'What\'s the most secret sexual desire you\'ve never told anyone here?',
    ],
  };
}
