class ContentEnImpostore {
  const ContentEnImpostore._();

  static const List<String> impostoreWords = [
    'Beach',
    'Mountain',
    'Airport',
    'Station',
    'Subway',
    'Hospital',
    'Pharmacy',
    'Supermarket',
    'Bakery',
    'Pizza Place',
    'Restaurant',
    'Bar',
    'Nightclub',
    'Gym',
    'Swimming Pool',
    'Library',
    'Museum',
    'Movies',
    'Theater',
    'Stadium',
    'School',
    'University',
    'Office',
    'Factory',
    'Construction Site',
    'Hair Salon',
    'Dentist',
    'Bank',
    'Post Office',
    'Hotel',
    'Camping',
    'Zoo',
    'Aquarium',
    'Park',
    'Garden',
    'Forest',
    'Desert',
    'Island',
    'Volcano',
    'Waterfall',
    'Elevator',
    'Escalator',
    'Traffic Light',
    'Highway',
    'Ferry',
    'Airplane',
    'Train',
    'Bicycle',
    'Scooter',
    'Moped',
    'Umbrella',
    'Eyeglasses',
    'Watch',
    'Backpack',
    'Suitcase',
    'Wallet',
    'Keys',
    'Phone',
    'Battery Charger',
    'Headphones',
    'Television',
    'Refrigerator',
    'Washing Machine',
    'Vacuum Cleaner',
    'Oven',
    'Mattress',
    'Pillow',
    'Blanket',
    'Sofa',
    'Armchair',
    'Mirror',
    'Shower',
    'Towel',
    'Toothbrush',
    'Soap',
    'Coffee',
    'Croissant',
    'Ice Cream',
    'Pizza',
    'Lasagna',
    'Sandwich',
    'Salad',
    'Pasta',
    'Risotto',
    'Soup',
    'Chocolate',
    'Popcorn',
    'Potato chips',
    'Watermelon',
    'Pineapple',
    'Lemon',
    'Chili Pepper',
    'Cheese',
    'Honey',
    'Salt',
    'Dog',
    'Cat',
    'Horse',
    'Penguin',
    'Dolphin',
    'Shark',
    'Bee',
    'Ant',
    'Spider',
    'Snake',
    'Ball',
    'Racket',
    'Basketball Hoop',
    'Skates',
    'Skiing',
    'Guitar',
    'Piano',
    'Drums',
    'Microphone',
    'Karaoke',
    'Wedding',
    'Birthday',
    'New Year\'s Eve',
    'Vacation',
    'Moving',
    'Lighthouse',
    'Cruise',
    'Farm',
    'Circus',
    'Vineyard',
    'Carousel',
    'Planetarium',
    'Mill',
    'Gas Station',
    'Car Wash',
    'Laundromat',
    'Market',
    'Ice Cream Shop',
    'Sushi',
    'Barbecue',
    'Picnic',
    'Mine',
    'Bowling',
    'Amusement Park',
    'Glacier',
    'Sauna',
    'Hot Springs',
    'Luge',
    'Surfing',
    'Tent',
    'Bonfire',
    'Karate',
    'Marathon',
    'Tattoo',
    'Castle',
  ];
}
