class ContentEnApp {
  const ContentEnApp._();

  static const Map<String, String> ui = {
    'app.tagline': 'The party game where\neveryone is connected.',
    'common.retry': 'TRY AGAIN',
    'common.cancel': 'CANCEL',
    'common.continue': 'CONTINUE',
    'common.back_home': 'BACK TO HOME',
    'common.loading': 'One moment…',
    'common.you': 'you',
    'onboarding.slide1.title': 'The night is about to\ntake a new turn',
    'onboarding.slide1.body':
        'Everyone plays on their own phone, but you all play together. Joyo brings everything together, you take it from there.',
    'onboarding.slide2.title': 'One code and\nyou’re in',
    'onboarding.slide2.body':
        'Create a room, share the code and get your friends in. You’ll be ready to play in seconds.',
    'onboarding.slide3.title': 'Six games.\nEndless possibilities.',
    'onboarding.slide3.body':
        'Would You Rather, Never Have I Ever, Who Would Do It?, Truth or Dare, Bluff Story and Impostor. Pick your game and get started.',
    'onboarding.slide4.title': 'You choose\nhow far to take it',
    'onboarding.slide4.body':
        'Normal to get started, Mix to change things up, Hot when you want to make the night more interesting.',
    'onboarding.language': 'What language are you playing in?',
    'onboarding.start': 'GET STARTED',
    'onboarding.skip': 'SKIP',
    'home.create': 'CREATE ROOM',
    'home.join': 'JOIN WITH A CODE',
    'home.games': 'Games',
    'home.connection_failed': 'Unable to connect to Joyo.',
    'home.language': 'Language',
    'join.title_create': 'Create a room',
    'join.title_join': 'Join the room',
    'join.name_question': 'What’s your name?',
    'join.name_hint': 'Enter your name',
    'join.color': 'Choose your color',
    'join.avatar': 'Choose your avatar',
    'join.error_avatar': 'Pick an avatar.',
    'join.code': 'Room code',
    'join.cta_create': 'CREATE ROOM',
    'join.cta_join': 'JOIN',
    'join.error_name': 'Enter your name.',
    'join.error_code': 'The code must be 6 characters.',
    'error.room_not_found': 'We couldn’t find a room with this code.',
    'error.room_full': 'The room is full. Maximum 10 players.',
    'error.room_finished': 'This game has already ended.',
    'error.connection': 'Connection lost. Check your connection and try again.',
    'lobby.title': 'Lobby',
    'lobby.code_label': 'ROOM CODE',
    'lobby.code_hint': 'Share it with your friends · tap to copy',
    'lobby.code_copied': 'Code copied',
    'lobby.players': 'Players',
    'lobby.you': 'you',
    'lobby.host_badge': 'HOST',
    'lobby.pick_game': 'CHOOSE A GAME',
    'lobby.waiting_host': 'The host is choosing a game…',
    'lobby.which_game': 'What are we playing?',
    'lobby.remove_player': 'Remove {name}?',
    'lobby.remove_player_body':
        'Use this if someone closed the app without leaving. They can rejoin with the same code.',
    'lobby.remove': 'REMOVE',
    'lobby.exit_host_title': 'Close the room?',
    'lobby.exit_host_body':
        'The room will close for everyone, and the other players will return to the home screen.',
    'lobby.exit_title': 'Leave the room?',
    'lobby.exit_body':
        'You’re about to leave the room. The other players will see it.',
    'lobby.stay': 'STAY',
    'lobby.close': 'CLOSE',
    'lobby.leave': 'LEAVE',
    'lobby.exit_failed': 'Unable to leave: {detail}',
    'lobby.room_closed': 'The host closed the room.',
    'lobby.reconnecting': 'Reconnecting…',
    'lobby.entering': 'Joining the room…',
    'mode.title': 'Modes',
    'mode.normale': 'Normal',
    'mode.mix': 'Mix',
    'mode.hot': 'Hot',
    'mode.normale.desc': 'The basic rules. The easiest way to get started.',
    'mode.mix.desc': 'More variety, more pace and a few extra surprises.',
    'mode.hot.desc': 'More direct, more personal. Only if you’re ready.',
    'age.title': 'Adult content',
    'age.body':
        'The Mix and Hot modes contain explicit content intended for adults. Do you confirm that all players are at least 18 years old?',
    'age.confirm': 'I CONFIRM',
    'settings.rounds': 'Rounds per game',
    'game.round_of': 'Round {n} of {total}',
    'game.preparing': 'Getting the round ready…',
    'game.create_failed': 'Unable to create the round: {detail}',
    'game.close_failed': 'Unable to close the round: {detail}',
    'game.vote_failed': 'Response not recorded: {detail}',
    'game.next_round': 'NEXT ROUND',
    'game.see_podium': 'SEE THE PODIUM',
    'game.waiting_next': 'The host is about to start the next round…',
    'game.finished': 'Game over',
    'game.answered': '{n} out of {total} answered',
    'game.back_to_lobby': 'BACK TO LOBBY',
    'game.lobby_short': 'LOBBY',
    'game.host_only': 'Only the host can restart the game from the lobby.',
    'game.coming_soon': 'COMING SOON',
    'podium.title': 'Game over',
    'podium.winner': '{name} wins',
    'podium.no_scores':
        'This game doesn’t use points. The point is simply to play.',
    'podium.points': '{n} points',
    'podium.points_one': '{n} point',
    'preferisci.name': 'Would You Rather',
    'preferisci.tagline': 'Two choices. One answer. What’s yours?',
    'preferisci.prompt': 'Would you rather…',
    'preferisci.or': 'or',
    'preferisci.split': 'Here’s how the group voted',
    'preferisci.no_votes': 'No one answered',
    'non_ho_mai.name': 'Never Have I Ever',
    'non_ho_mai.tagline': 'Did it happen or not? Let’s find out.',
    'non_ho_mai.prompt': 'Never have I ever…',
    'non_ho_mai.done': 'I DID IT',
    'non_ho_mai.never': 'NEVER',
    'non_ho_mai.anonymous':
        'Your answers are anonymous. Only the total is shown.',
    'non_ho_mai.nobody': 'No one has done it',
    'non_ho_mai.count': '{n} out of {total}',
    'non_ho_mai.guess_who': 'Now try to figure out who did it',
    'chi.name': 'Who Would Do It?',
    'chi.tagline': 'One question. One name. You decide.',
    'chi.decided': 'The group has decided',
    'chi.tie': 'Tie',
    'chi.no_votes': 'No votes',
    'obbligo.name': 'Truth or Dare',
    'obbligo.tagline': 'The choice is no longer in your hands.',
    'obbligo.spinning': 'The bottle is spinning…',
    'obbligo.your_turn': 'Your turn',
    'obbligo.turn_of': '{name}’s turn',
    'obbligo.choosing': 'Choosing…',
    'obbligo.dare': 'DARE',
    'obbligo.truth': 'TRUTH',
    'obbligo.no_choice': '{name} didn’t choose in time',
    'obbligo.when_done': 'When they’re done, the host can start the next round',
    'bluff.name': 'Bluff Story',
    'bluff.tagline': 'One truth. Two lies. Can you pull it off?',
    'bluff.writing': '{name} is writing\na truth about themselves',
    'bluff.your_turn_body':
        'Write a truth about yourself. We’ll add two lies. Everyone else has to figure out which one is true.',
    'bluff.hint': 'Write your truth…',
    'bluff.send': 'SHARE YOUR TRUTH',
    'bluff.too_short': 'Write at least 30 characters.',
    'bluff.which_true': 'Which one is the truth about {name}?',
    'bluff.in_play': 'Your story is in play',
    'bluff.dont_tell': 'Don’t let the others figure out which one is true.',
    'bluff.your_truth': 'your truth',
    'bluff.true_label': 'true',
    'bluff.truth_of': 'The truth about {name}',
    'bluff.nobody_guessed': 'Nobody guessed it. {name} fooled everyone.',
    'bluff.guessed': '{n} guessed correctly',
    'bluff.guessed_one': '{n} guessed correctly',
    'bluff.scoring':
        '+2 for each correct guess · +1 to {name} for every successful bluff',
    'bluff.multilang_title': 'Different languages at the table',
    'bluff.multilang_body':
        'Your group is playing in different languages: the lies come out '
        'translated, but the true line stays in the language of whoever '
        'wrote it and may give itself away right away.',
    'impostore.name': 'Impostor',
    'impostore.tagline': 'One of you has different information.',
    'impostore.only_you': 'Only you can see this',
    'impostore.you_are': 'You’re the impostor',
    'impostore.you_are_body':
        'You don’t know the word. Listen to the others, improvise and don’t get caught. If you’re exposed but guess the word, you get points back.',
    'impostore.the_word': 'The secret word is',
    'impostore.one_doesnt': 'One of you doesn’t know the word.',
    'impostore.round_of_words': 'Word round',
    'impostore.round_of_words_body':
        'Take turns saying one word related to the secret.\nToo specific and you help the impostor. Too vague and you might look like the impostor.',
    'impostore.your_word': 'Your word: {word}',
    'impostore.to_vote': 'GO TO VOTE',
    'impostore.who': 'Who is the impostor?',
    'impostore.guess_hint': 'The secret word was…',
    'impostore.guess_body':
        'You’re the impostor. Try to guess the word: if you’re caught but get it right, you recover points.',
    'impostore.confirm': 'CONFIRM',
    'impostore.vote_registered': 'Vote recorded',
    'impostore.caught': 'Impostor caught',
    'impostore.escaped': 'The impostor got away',
    'impostore.word_was': 'The word was',
    'impostore.guessed_it': 'They guessed it: “{guess}” · +3 points',
    'impostore.said': 'They said: “{guess}”',
    'impostore.points_caught': '+2 for anyone who voted for the impostor',
    'impostore.points_escaped': '+5 to the impostor',
    'impostore.votes': '{n} votes',
    'impostore.votes_one': '{n} vote',
    'premium.title': 'Custom content',
    'premium.body':
        'In “Who Would Do It?” and “Bluff Story”, AI creates content designed for your group instead of using preset prompts.',
    'premium.active': 'AI active in this room',
    'premium.active_body': 'Content generated for your group',
    'premium.unlock': 'UNLOCK',
    'premium.watch_ad': 'WATCH AD',
    'premium.host_only': 'Only the host can unlock it.',
    'premium.credits': '{n} credits',
    'premium.unlocked': 'AI unlocked for this room',
    'premium.ad_reward': 'You’ve unlocked AI content',
    'premium.ad_incomplete': 'Ad not completed.',
    'premium.ad_limit': 'Ad limit reached for today. Try again tomorrow!',
    'premium.bank_full':
        'You already have the maximum premium games: play those before earning more.',
    'premium.no_store':
        'Purchases aren’t available here. Use Google Play or the App Store.',
    'premium.ads_mobile_only': 'Ads are only available on mobile.',

    'shop.badge': 'Premium',
    'shop.title': 'Unlock Mix and Hot',
    'shop.body':
        'Mix and Hot are premium modes. Watch 3 ads to unlock them for one game.',
    'shop.progress': '{n}/3 ads',
    'shop.watch': 'WATCH AN AD',
    'shop.unlocked': 'Mix and Hot unlocked for one game',
    'shop.host_only': 'Only the host can unlock them.',
    'shop.go_premium': 'Or go Premium',
    'shop.page_title': 'Shop',
    'shop.free_title': 'Unlock with ads',
    'shop.in_room_only': 'Available in a room, as host.',
    'shop.games': '{n} premium games ready',
    'endgame.promo': 'Want more sparkle and fewer ads?',
    'endgame.shop_cta': 'DISCOVER PREMIUM',

    'paywall.title': 'Go Premium',
    'paywall.no_ads_name': 'No ads',
    'paywall.no_ads_desc': 'Play without ads.',
    'paywall.premium_name': 'Premium',
    'paywall.premium_desc': 'Mix, Hot, longer games and no ads.',
    'paywall.best_value': 'Most popular',
    'paywall.feat_modes': 'Mix and Hot modes',
    'paywall.feat_rounds': 'Longer games',
    'paywall.per_month': '/month',
    'paywall.active': 'Active',
    'paywall.subscribe': 'SUBSCRIBE',
    'paywall.restore': 'Restore purchases',
    'shop.privacy': 'Privacy Policy',
    'shop.ad_privacy': 'Ads privacy options',
    'paywall.restored': 'Subscription restored',
    'paywall.nothing_restored': 'No subscription to restore',
  };
}
