/// Generato da tool/generate_content.dart (traduzione DeepL dai
/// pool italiani). Stesse posizioni e stesso tono degli originali IT.
class ContentEnApp {
  const ContentEnApp._();

  static const Map<String, String> ui = {
    'app.tagline': 'The party game for people who each have\ntheir own phone.',
    'common.retry': 'Try again',
    'common.cancel': 'Cancel',
    'common.continue': 'CONTINUE',
    'common.back_home': 'BACK TO HOME',
    'common.loading': 'Wait a second…',
    'common.you': 'you',
    'onboarding.slide1.title': 'The evening takes\nan unexpected turn',
    'onboarding.slide1.body':
        'Everyone with their own phone, all in the same room. Joyo connects the screens; you create the chaos.',
    'onboarding.slide2.title':
        'With the code in hand,\nwe get down to business',
    'onboarding.slide2.body':
        'Open the room, shout out the code, and watch your friends rush in within seconds.',
    'onboarding.slide3.title': 'Six games to\nkeep you from ever getting bored',
    'onboarding.slide3.body':
        'Vote for your friends, make up outrageous lies, or take a chance with the bottle. Full speed ahead.',
    'onboarding.slide4.title': 'It\'s up to you\nhow daring you want to be',
    'onboarding.slide4.body':
        'Normal Mode to get warmed up, Mix to liven up the evening, Hot for when the masks come off.',
    'onboarding.language': 'What language do you play in?',
    'onboarding.start': 'GET STARTED',
    'onboarding.skip': 'Skip',
    'home.create': 'CREATE ROOM',
    'home.join': 'JOIN US WITH A CODE',
    'home.games': 'Games',
    'home.connection_failed': 'Failed to connect to Joyo.',
    'home.language': 'Language',
    'join.title_create': 'Create a room',
    'join.title_join': 'Join Us',
    'join.name_question': 'What\'s your name?',
    'join.name_hint': 'Your name',
    'join.color': 'Your Color',
    'join.code': 'Room Code',
    'join.cta_create': 'CREATE THE ROOM',
    'join.cta_join': 'ENTER',
    'join.error_name': 'Write your name.',
    'join.error_code': 'The code is 6 characters long.',
    'error.room_not_found': 'There are no rooms with this code.',
    'error.room_full': 'The room is full: maximum 10 players.',
    'error.room_finished': 'This game is already over.',
    'error.connection': 'Connection lost. Reopen the app and try again.',
    'lobby.title': 'Lobby',
    'lobby.code_label': 'ROOM CODE',
    'lobby.code_hint': 'Say it out loud · tap to copy',
    'lobby.code_copied': 'Code copied',
    'lobby.players': 'Players',
    'lobby.you': 'you',
    'lobby.host_badge': 'HOST',
    'lobby.pick_game': 'CHOOSE A GAME',
    'lobby.waiting_host': 'The host is choosing the game…',
    'lobby.which_game': 'What should we play?',
    'lobby.remove_player': 'Remove {name}?',
    'lobby.remove_player_body':
        'Use this if someone has closed the app without logging out. They can always log back in with the code.',
    'lobby.remove': 'Remove',
    'lobby.exit_host_title': 'Should we close the room?',
    'lobby.exit_host_body':
        'The room closes for everyone: the other players return to the home screen.',
    'lobby.exit_title': 'Leave the room?',
    'lobby.exit_body': 'The other players will see you leave.',
    'lobby.stay': 'Stay',
    'lobby.close': 'Close',
    'lobby.leave': 'Log Out',
    'lobby.exit_failed': 'Failed to leave: {detail}',
    'lobby.room_closed': 'The room has been closed by the host.',
    'lobby.reconnecting': 'Reconnecting…',
    'lobby.entering': 'Entering the room…',
    'mode.title': 'Modes',
    'mode.normale': 'Normal',
    'mode.mix': 'Mix',
    'mode.hot': 'Hot',
    'mode.normale.desc': 'Perfect for breaking the ice without too much fuss.',
    'mode.mix.desc':
        'The action keeps changing, and the pace is picking up. Hold on tight.',
    'mode.hot.desc':
        'No holds barred. Play only if you\'re ready for anything.',
    'settings.rounds': 'Rounds per game',
    'game.round_of': 'Round {n} of {total}',
    'game.preparing': 'I\'m setting up the round…',
    'game.create_failed': 'I can\'t create the round: {detail}',
    'game.close_failed': 'I can\'t finish the round: {detail}',
    'game.vote_failed': 'Unrecorded response: {detail}',
    'game.next_round': 'NEXT ROUND',
    'game.see_podium': 'SEE THE PODIUM',
    'game.waiting_next': 'The host is about to start the next round…',
    'game.finished': 'The game is over',
    'game.answered': '{n} out of {total} responded',
    'game.back_to_lobby': 'BACK TO THE LOBBY',
    'game.lobby_short': 'LOBBY',
    'game.host_only': 'The host can restart the game from the lobby.',
    'game.coming_soon': 'Coming Soon',
    'podium.title': 'End of the game',
    'podium.winner': '{name} wins',
    'podium.no_scores':
        'This game doesn\'t award points: no leaderboard, just the game itself.',
    'podium.points': '{n} points',
    'podium.points_one': '{n} point',
    'preferisci.name': 'Which do you prefer?',
    'preferisci.tagline': 'Harsh Choices: Who Agrees with You?',
    'preferisci.prompt': 'Would you prefer…',
    'preferisci.or': 'or',
    'preferisci.split': 'The group split up as follows',
    'preferisci.no_votes': 'No one replied',
    'non_ho_mai.name': 'I\'ve never',
    'non_ho_mai.tagline': 'The confessional is open. Confess and survive.',
    'non_ho_mai.prompt': 'I\'ve never…',
    'non_ho_mai.done': 'I DID IT',
    'non_ho_mai.never': 'NEVER',
    'non_ho_mai.anonymous':
        'No one will see what you answered—only the count will be visible.',
    'non_ho_mai.nobody': 'No one has done it',
    'non_ho_mai.count': '{n} out of {total}',
    'non_ho_mai.guess_who': 'Now it\'s up to you to figure out who',
    'chi.name': 'Who could do that?',
    'chi.tagline': 'The game where you point your finger (literally).',
    'chi.decided': 'The group has decided',
    'chi.tie': 'It\'s a tie',
    'chi.no_votes': 'No votes',
    'obbligo.name': 'Truth or Dare',
    'obbligo.tagline': 'The bottle decides, you sweat. No excuses.',
    'obbligo.spinning': 'The bottle spins…',
    'obbligo.your_turn': 'It\'s your turn',
    'obbligo.turn_of': 'It\'s {name}\'s turn',
    'obbligo.choosing': 'Choosing…',
    'obbligo.dare': 'DARE',
    'obbligo.truth': 'TRUTH',
    'obbligo.no_choice': '{name} didn\'t make a choice in time',
    'obbligo.when_done':
        'When he\'s finished, the host calls for the next round',
    'bluff.name': 'Bluff Story',
    'bluff.tagline': 'Lying is an art. Can you avoid getting caught?',
    'bluff.writing': '{name} is writing\na true fact about themselves',
    'bluff.your_turn_body':
        'Write down a true fact about yourself. The game will mix it in with two lies: the others will have to guess which one is yours.',
    'bluff.hint': 'Write here…',
    'bluff.send': 'SHARE YOUR TRUTH',
    'bluff.too_short': 'Write something a little longer.',
    'bluff.which_true': 'What is the truth about {name}?',
    'bluff.in_play': 'Your story is on the line',
    'bluff.dont_tell':
        'Don\'t miss out on finding out which one is the real one.',
    'bluff.your_truth': 'your truth',
    'bluff.true_label': 'true',
    'bluff.truth_of': 'The Truth About {name}',
    'bluff.nobody_guessed': 'No one guessed it: {name} tricked you all',
    'bluff.guessed': '{n} guessed correctly',
    'bluff.guessed_one': '{n} guessed correctly',
    'bluff.scoring':
        '+2 to whoever guessed correctly · +1 to {name} for every successful bluff',
    'bluff.ai_working': 'I\'m making up two lies…',
    'bluff.ai_working_sub': 'tailored to the story of {name}',
    'impostore.name': 'Impostor',
    'impostore.tagline':
        'An intruder among us. Find him before it\'s too late.',
    'impostore.only_you': 'Only you can see this',
    'impostore.you_are': 'You\'re the impostor',
    'impostore.you_are_body':
        'You don\'t know the word. Listen, improvise, and don\'t let anyone catch you: if you guess the word at the end, you\'ll get points back.',
    'impostore.the_word': 'The word is',
    'impostore.one_doesnt': 'One of you doesn\'t know it.',
    'impostore.round_of_words': 'Wordplay',
    'impostore.round_of_words_body':
        'One by one, each person says a single word related to the secret.\nIf it\'s too specific, the imposter will figure it out; if it\'s too vague, you\'ll look like the imposter.',
    'impostore.your_word': 'Your word: {word}',
    'impostore.to_vote': 'PROCEED TO THE VOTE',
    'impostore.who': 'Who is the impostor?',
    'impostore.guess_hint': 'The secret word was…',
    'impostore.guess_body':
        'You\'re the imposter: try to guess the word. If you\'re exposed but you guess it correctly, you\'ll earn points.',
    'impostore.confirm': 'CONFIRM',
    'impostore.vote_registered': 'Recorded vote',
    'impostore.caught': 'Impostor Unmasked',
    'impostore.escaped': 'The impostor got away with it',
    'impostore.word_was': 'The word was',
    'impostore.guessed_it': 'You guessed it: "{guess}" · +3 points',
    'impostore.said': 'He had said, "{guess}"',
    'impostore.points_caught': '+2 to anyone who voted for the impostor',
    'impostore.points_escaped': '+5 to the imposter',
    'impostore.votes': '{n} votes',
    'impostore.votes_one': '{n} vote',
    'premium.title': 'Custom Content',
    'premium.body':
        'In "Who Could Do It" and "Bluff Story," the phrases are written about your group instead of being drawn from a list.',
    'premium.active': 'AI is active in this room',
    'premium.active_body': 'Questions and Lies Posted in Your Group',
    'premium.unlock': 'UNLOCK',
    'premium.watch_ad': 'WATCH AD',
    'premium.host_only': 'The host can unlock it.',
    'premium.credits': '{n} credits',
    'premium.unlocked': 'AI unlocked for this room',
    'premium.ad_reward': 'You\'ve earned some AI content',
    'premium.ad_incomplete': 'Ad not completed.',
    'premium.no_store':
        'Purchases aren\'t available here: you\'ll need Google Play or the App Store.',
    'premium.ads_mobile_only': 'The ads only work on mobile phones.',
  };
}
