class ContentEnBluff {
  const ContentEnBluff._();

  static const List<String> bluffFakes = [
    'I slept for twelve hours straight at an airport while waiting for a connecting flight.',
    'I didn\'t learn to swim until I was eighteen because I was afraid of the water.',
    'I missed an intercontinental flight because I fell asleep at the gate.',
    'When I was a kid, I got lost in a shopping mall for over an hour.',
    'I won a ballroom dancing competition in middle school with my cousin.',
    'I accidentally ended up in a wedding photo with people I didn\'t know at all.',
    'I worked as a waiter for a week and was fired right away.',
    'I cooked for twenty people without ever having turned on a stove before.',
    'I appeared on television for three seconds during a news segment.',
    'I ran into a very famous actor in the frozen food section of the supermarket.',
    'I hitchhiked fifty kilometers in a foreign country.',
    'I slept in my car during a very severe storm in the mountains.',
    'I took the wrong train and ended up on the other side of Italy.',
    'I spent the entire New Year\'s Eve in the hospital to be with a friend.',
    'When I was a child, I fell from a very tall tree without getting a scratch.',
    'I broke my arm while playing hide-and-seek inside the house.',
    'I got a tattoo on a whim and regretted it the very next day.',
    'I cut my own hair and had to shave it all off.',
    'I dyed my hair neon green to honor a lost bet.',
    'I sang karaoke in front of a hundred people who were booing me.',
    'I played guitar in a metal band for less than two months.',
    'I wrote a love song that I\'ve never let anyone hear.',
    'I kept a secret diary for five years straight without missing a single day.',
    'I read a 600-page book in its entirety in a single night.',
    'I saw the same movie at the theater three times in the same week.',
    'I memorized an entire three-minute monologue from a movie.',
    'I acted in a school play, and I made up all the lines.',
    'I sang in a polyphonic choir for a whole year.',
    'I learned a foreign language just by watching TV shows in their original language.',
    'I took a college exam without studying and got a perfect score.',
    'I cheated on an important test, and the teacher caught me.',
    'I skipped an entire week of school without my parents knowing.',
    'I was the last to find out about some huge news involving my family.',
    'I found out I have a second cousin who lives in the United States.',
    'I\'ve lived in three different cities over the course of just two years.',
    'I moved all my belongings by myself using a very small car.',
    'I spent an entire month in a house without a TV or the internet.',
    'I spent an entire summer without using social media.',
    'I deleted all my social media accounts for three consecutive months.',
    'I lost my new phone in the ocean while I was filming a video.',
    'I left my wallet, full of money, on a train, and someone returned it to me.',
    'I found fifty euros on the street and turned it in to the police.',
    'I won twenty euros with a scratch-off ticket I bought by chance.',
    'I bought a lottery ticket and lost it before the drawing.',
    'I ended up paying for dinner for a table of strangers because of a waiter\'s mistake.',
    'I ordered the exact same dish every day for a month.',
    'I ate nothing but pizza for lunch and dinner for seven days in a row.',
    'I tried going vegan, but I only lasted two weeks.',
    'I baked a cake that turned out so hard it was inedible.',
    'I completely burned a pot by leaving it on the stove while the burner was on.',
    'I set off the hotel\'s fire alarm while cooking in my room.',
    'My oven broke right before an important dinner.',
    'I put together a huge piece of furniture, and in the end I had ten pieces left over.',
    'I painted my room a color that I immediately began to hate.',
    'I slept on an air mattress on the floor for six months.',
    'I lived with a roommate whom I never spoke to for a year.',
    'I adopted a dog on a whim while I was on vacation abroad.',
    'I\'ve given each and every plant in my house its own name.',
    'I\'ve killed every succulent I\'ve been given over the years.',
    'I rescued a kitten that was stuck on a very high branch.',
    'I was absolutely terrified of a dog that was as big as a cat.',
    'I ran a half marathon without having trained even a single day.',
    'I joined an expensive gym and only went there three times.',
    'I played soccer on an official team for just one game.',
    'I tried skiing for the first time when I was thirty, and I fell right away.',
    'I tried skydiving once and swore I\'d never do it again.',
    'I went scuba diving and panicked at a depth of ten meters.',
    'I climbed a small mountain wearing the wrong shoes.',
    'I slept in a tent during a very heavy thunderstorm for two nights in a row.',
    'I took a trip abroad by myself without telling anyone.',
    'I booked a flight for the wrong day and didn\'t end up leaving.',
    'I spent the whole night at the station waiting for the next available train.',
    'I met my best friend while we were standing in line at the supermarket.',
    'I ran into an old classmate by chance while I was in London.',
    'I\'ve maintained an important friendship for years by communicating only through chat.',
    'I wrote a very long love letter that I never sent.',
    'I received an anonymous letter that completely changed my day.',
    'I dialed the wrong number and ended up talking for ten minutes.',
    'I answered an important work call while I was naked on the beach.',
    'I worked nonstop throughout the entire Christmas break.',
    'I quit my old job without having a Plan B.',
    'I turned down a job offer that paid a much higher salary.',
    'I had a job interview in a language I spoke very poorly.',
    'I made a life-changing decision by flipping a coin.',
    'I slept soundly during a very important business meeting.',
    'I sent a confidential email to the entire company due to a technical error.',
    'I accidentally called my new boss by my ex\'s name.',
    'I worked with a colleague for months without ever knowing his last name.',
    'I pretended to know someone very well who said hello to me on the street.',
    'I enthusiastically greeted a stranger, thinking he was a close friend of mine.',
    'I recognized someone just by their voice, even though I hadn\'t heard it in ten years.',
    'I forgot my mother\'s birthday and didn\'t remember it until a week later.',
    'I organized a surprise party, but the surprise was discovered the day before.',
    'I\'ve kept a very important secret for more than five years in a row.',
    'I told my parents a lie that lasted a whole year.',
    'I confessed to a wrongdoing of mine simply because I could no longer sleep at night because of it.',
    'I cried my eyes out while watching a commercial for puppies on TV.',
    'I laughed my head off at a funeral and couldn\'t stop.',
    'I fell asleep at the movie theater during the trailer for a movie I loved.',
    'I clapped enthusiastically all by myself at the end of a movie at the theater.',
    'I sang at the top of my lungs in the car, thinking I was completely alone.',
    'I danced in the elevator with a stranger who was watching me.',
    'It wasn\'t until we\'d been living there for three years that I became friends with my neighbor.',
    'I lost all my house keys on the very day I moved.',
    'I got locked out of my house on the landing while I was still in my pajamas.',
    'I was stuck in an old elevator for more than twenty minutes.',
    'I accidentally got on a very long escalator going in the wrong direction.',
    'I went to the wrong restroom at a fancy restaurant and ended up in the one across the hall.',
    'I walked into a work meeting by mistake and stayed there for ten minutes.',
    'I was talking loudly on the phone on a train without realizing how loud I was.',
    'I sent a loving message to the very person I had been speaking ill of.',
    'I took a screenshot of a chat and accidentally sent it to the recipient.',
    'I accidentally "liked" a photo from ten years ago of one of my exes.',
    'I wrote a really mean comment and deleted it a second later.',
    'I created a fake social media profile that I never had the courage to use.',
    'I watched an entire TV series—three seasons—in just one weekend.',
    'I finished a really hard video game in just one night.',
    'I played the same online game obsessively for five years.',
    'I won a family card tournament by cheating shamelessly.',
    'I lost a ridiculous bet and had to dye my hair blue.',
    'I made a stupid bet that cost me a dinner for eight people.',
    'I ate a super-hot chili just to win a challenge.',
    'I drank three double espressos in an hour and didn\'t get a wink of sleep all night.',
    'I stayed awake all night because of anxiety that turned out to be unfounded.',
    'I had a dream that was so realistic that I firmly believed it was real as soon as I woke up.',
    'I talked in my sleep and revealed a secret that was supposed to remain secret.',
    'I used to sleepwalk all over the house when I was a kid.',
    'I woke up in a different part of the house than where I had fallen asleep.',
    'I slept soundly on a bench in a public park that afternoon.',
    'I spent an entire day without speaking to anyone.',
    'I had a long conversation with a stranger for two hours during a train ride.',
    'I returned a wallet full of money that I had found on the street.',
    'I won a prize in a charity raffle, but I never claimed it.',
    'I ate the exact same thing for lunch for thirty consecutive days.',
    'I pretended to speak a foreign language so no one would recognize me while I was on vacation.',
    'I had to ask my neighbors for help because I couldn\'t find my cat.',
    'I pretended there was a problem with the line to end a boring work call.',
    'I walked out of the movie theater halfway through the film because I was bored to death.',
    'I walked a neighbor\'s dog for ten minutes, thinking it was mine.',
    'I greeted someone I didn\'t know at all with great enthusiasm.',
    'I took a sightseeing tour of my city while pretending to be a foreign tourist.',
    'I\'ve sent birthday wishes to the wrong person two years in a row.',
    'I won a heated argument by citing a completely made-up statistic.',
    'I kept the umbrella open for ten minutes after the sun had already come out.',
    'I made a total fool of myself at a job interview, and they hired me anyway.',
    'I\'ve had a fake plant in my living room for years and have been watering it regularly.',
    'I lost my car keys and found them a month later in the freezer.',
    'I said "Enjoy your meal" to the waiter who was bringing me my dish.',
    'I ran after a bus for two hundred meters and managed to catch it.',
    'I forgot where I had parked my car, so I drove around in circles for an hour.',
  ];
}
