class ContentFrBluff {
  const ContentFrBluff._();

  static const List<String> bluffFakes = [
    'J\'ai dormi douze heures d\'affilée dans un aéroport en attendant une correspondance.',
    'Je n\'ai appris à nager qu\'à dix-huit ans, car j\'avais peur de l\'eau.',
    'J\'ai raté un vol intercontinental parce que je me suis endormi à la porte d\'embarquement.',
    'Quand j\'étais petit, je me suis perdu dans un centre commercial pendant plus d\'une heure.',
    'Au collège, j\'ai remporté un concours de danse de salon avec ma cousine.',
    'Je me suis retrouvé par erreur sur une photo de mariage de parfaits inconnus.',
    'J\'ai travaillé une semaine comme serveur et j\'ai été licencié tout de suite.',
    'J\'ai cuisiné pour vingt personnes sans avoir jamais allumé de cuisinière auparavant.',
    'Je suis apparu à la télévision pendant trois secondes au cours d\'un reportage du journal télévisé.',
    'J\'ai croisé un acteur très célèbre au rayon surgelés du supermarché.',
    'J\'ai fait du stop pendant cinquante kilomètres dans un pays étranger.',
    'J\'ai dormi dans ma voiture pendant un orage très violent en montagne.',
    'J\'ai pris le mauvais train et je me suis retrouvé à l\'autre bout de l\'Italie.',
    'J\'ai passé tout le réveillon du Nouvel An à l\'hôpital pour accompagner un ami.',
    'Quand j\'étais enfant, je suis tombé d\'un très grand arbre sans m\'écorcher.',
    'Je me suis cassé le bras en jouant à cache-cache à la maison.',
    'Je me suis fait faire un tatouage sur un coup de tête et je l\'ai regretté dès le lendemain.',
    'Je me suis coupé les cheveux tout seul et j\'ai dû me raser la tête à zéro.',
    'Je me suis teint les cheveux en vert fluo pour honorer un pari perdu.',
    'J\'ai chanté au karaoké devant une centaine de personnes qui me sifflaient.',
    'J\'ai joué de la guitare dans un groupe de metal pendant moins de deux mois.',
    'J\'ai écrit une chanson d\'amour que je n\'ai jamais fait écouter à personne.',
    'J\'ai tenu un journal intime pendant cinq ans d\'affilée, sans manquer un seul jour.',
    'J\'ai lu un livre de six cents pages d\'une seule traite, en une seule nuit.',
    'J\'ai vu le même film au cinéma trois fois dans la même semaine.',
    'J\'ai appris par cœur tout un monologue de trois minutes tiré d\'un film.',
    'J\'ai joué dans une pièce de théâtre à l\'école et j\'ai inventé toutes les répliques.',
    'J\'ai chanté dans une chorale polyphonique pendant une année entière.',
    'J\'ai appris une langue étrangère simplement en regardant des séries télévisées en version originale.',
    'J\'ai passé un examen à l\'université sans avoir révisé et j\'ai eu 30.',
    'J\'ai triché lors d\'un devoir important et le professeur m\'a pris sur le fait.',
    'J\'ai séché l\'école pendant une semaine entière sans que mes parents s\'en rendent compte.',
    'J\'ai été le dernier à découvrir une nouvelle énorme qui concernait ma famille.',
    'J\'ai découvert que j\'avais un cousin au deuxième degré qui vit aux États-Unis.',
    'J\'ai vécu dans trois villes différentes en l\'espace de deux ans seulement.',
    'J\'ai effectué tout un déménagement tout seul à l\'aide d\'une toute petite voiture.',
    'J\'ai passé un mois entier dans une maison sans télévision ni Internet.',
    'J\'ai passé tout un été sans utiliser les réseaux sociaux.',
    'J\'ai supprimé tous mes comptes sur les réseaux sociaux pendant trois mois d\'affilée.',
    'J\'ai perdu mon nouveau téléphone dans la mer alors que je tournais une vidéo.',
    'J\'ai oublié mon portefeuille bien rempli dans un train et on me l\'a rendu.',
    'J\'ai trouvé cinquante euros dans la rue et je les ai remis à la police.',
    'J\'ai gagné vingt euros grâce à un ticket à gratter acheté par hasard.',
    'J\'ai acheté un billet de loterie et je l\'ai perdu avant le tirage.',
    'J\'ai payé le dîner d\'une table d\'inconnus à cause d\'une erreur du serveur.',
    'J\'ai commandé exactement le même plat tous les jours pendant un mois.',
    'J\'ai mangé uniquement de la pizza au déjeuner et au dîner pendant sept jours d\'affilée.',
    'J\'ai essayé de devenir végétalien, mais je n\'ai tenu que deux semaines.',
    'J\'ai préparé un gâteau qui s\'est avéré si dur qu\'il était immangeable.',
    'J\'ai complètement brûlé une casserole en l\'oubliant sur le feu allumé.',
    'J\'ai déclenché l\'alarme incendie de l\'hôtel en cuisinant dans ma chambre.',
    'J\'ai cassé le four de la maison juste la veille d\'un dîner important.',
    'J\'ai monté un meuble énorme et il m\'est resté dix pièces à la fin.',
    'J\'ai peint ma chambre dans une couleur que j\'ai tout de suite commencé à détester.',
    'J\'ai dormi sur un matelas gonflable posé à même le sol pendant six mois.',
    'J\'ai vécu avec un colocataire à qui je n\'ai jamais adressé la parole en un an.',
    'J\'ai adopté un chien sur un coup de tête alors que j\'étais en vacances à l\'étranger.',
    'J\'ai donné un prénom à chacune des plantes que j\'ai chez moi.',
    'J\'ai fait mourir toutes les plantes grasses qu\'on m\'a offertes au fil des ans.',
    'J\'ai sauvé un chaton qui était coincé sur une branche très haute.',
    'J\'ai eu une peur bleue d\'un chien aussi petit qu\'un chat.',
    'J\'ai couru un semi-marathon sans m\'être entraîné ne serait-ce qu\'une seule journée.',
    'Je me suis inscrit dans une salle de sport hors de prix et je n\'y suis allé que trois fois.',
    'Je n\'ai joué au football dans une équipe officielle que lors d\'un seul match.',
    'J\'ai essayé de skier pour la première fois à trente ans et je suis tout de suite tombé.',
    'J\'ai essayé le parachutisme une fois et je me suis juré de ne plus jamais le refaire.',
    'J\'ai fait une plongée sous-marine et j\'ai paniqué à dix mètres de profondeur.',
    'J\'ai gravi une petite montagne avec des chaussures inadaptées.',
    'J\'ai dormi sous la tente pendant deux nuits d\'affilée, sous un orage très violent.',
    'Je suis parti seul à l\'étranger sans en parler à personne.',
    'J\'ai réservé un vol pour le mauvais jour et je ne suis pas parti.',
    'J\'ai passé toute une nuit à la gare à attendre le premier train disponible.',
    'J\'ai rencontré mon meilleur ami alors que nous faisions la queue au supermarché.',
    'J\'ai retrouvé par hasard un ancien camarade de classe alors que j\'étais à Londres.',
    'J\'ai entretenu une amitié importante pendant des années en communiquant uniquement par chat.',
    'J\'ai écrit une très longue lettre d\'amour que je n\'ai jamais envoyée.',
    'J\'ai reçu une lettre anonyme qui a complètement bouleversé ma journée.',
    'J\'ai composé le mauvais numéro et je suis resté au téléphone pendant dix minutes.',
    'J\'ai répondu à un appel professionnel important alors que j\'étais nu sur la plage.',
    'J\'ai travaillé sans interruption pendant toutes les vacances de Noël.',
    'J\'ai démissionné de mon ancien emploi sans avoir de plan B.',
    'J\'ai refusé une offre d\'emploi qui proposait un salaire bien plus élevé.',
    'J\'ai passé un entretien d\'embauche dans une langue que je maîtrisais très mal.',
    'J\'ai pris une décision cruciale pour ma vie en tirant à pile ou face.',
    'Je me suis endormi profondément pendant une réunion de travail très importante.',
    'J\'ai envoyé un e-mail confidentiel à l\'ensemble de l\'entreprise à la suite d\'une erreur technique.',
    'J\'ai appelé par erreur mon nouveau patron par le prénom de mon ex.',
    'J\'ai travaillé avec un collègue pendant des mois sans jamais connaître son nom de famille.',
    'J\'ai fait semblant de bien connaître une personne qui m\'a salué dans la rue.',
    'J\'ai salué avec enthousiasme un inconnu en le prenant pour un de mes amis proches.',
    'J\'ai reconnu quelqu\'un rien qu\'à sa voix, alors que je ne l\'avais pas entendu depuis dix ans.',
    'J\'ai oublié l\'anniversaire de ma mère et je m\'en suis souvenu une semaine plus tard.',
    'J\'ai organisé une fête surprise qui a été découverte la veille.',
    'J\'ai gardé un secret très important pendant plus de cinq ans d\'affilée.',
    'J\'ai raconté à mes parents un mensonge qui a duré une année entière.',
    'J\'ai avoué ma faute simplement parce que je n\'arrivais plus à dormir la nuit.',
    'J\'ai pleuré à chaudes larmes en regardant une publicité pour des chiots à la télévision.',
    'J\'ai ri aux larmes pendant un enterrement et je n\'arrivais plus à m\'arrêter.',
    'Je me suis endormi au cinéma pendant l\'avant-première d\'un film que j\'adorais.',
    'J\'ai applaudi tout seul et avec enthousiasme à la fin d\'un film au cinéma.',
    'J\'ai chanté à tue-tête dans la voiture, pensant être complètement seul.',
    'J\'ai dansé dans l\'ascenseur avec un inconnu qui me regardait.',
    'Ce n\'est qu\'après trois ans de voisinage que je me suis lié d\'amitié avec mon voisin.',
    'J\'ai perdu toutes les clés de chez moi le jour même de mon déménagement.',
    'Je me suis retrouvé enfermé dehors, sur le palier, alors que j\'étais en pyjama.',
    'Je suis resté coincé dans un vieil ascenseur pendant plus de vingt minutes.',
    'J\'ai pris par erreur un escalier roulant très long dans le mauvais sens.',
    'Je me suis trompé de toilettes dans un restaurant chic et je suis entré dans celles d\'en face.',
    'Je suis entré par erreur dans une réunion de travail et j\'y suis resté dix minutes.',
    'J\'ai parlé fort au téléphone dans un train sans faire attention au volume.',
    'J\'ai envoyé un message d\'amour justement à la personne dont je disais du mal.',
    'J\'ai fait une capture d\'écran d\'une conversation et je l\'ai envoyée par erreur au destinataire.',
    'J\'ai « aimé » par erreur une photo datant d\'il y a dix ans d\'un de mes ex.',
    'J\'ai écrit un commentaire très méchant et je l\'ai supprimé au bout d\'une seconde.',
    'J\'ai créé un faux profil sur les réseaux sociaux que je n\'ai jamais osé utiliser.',
    'J\'ai regardé une série télévisée complète de trois saisons en un seul week-end.',
    'J\'ai terminé un jeu vidéo extrêmement difficile en une seule nuit.',
    'J\'ai joué de manière obsessionnelle au même jeu en ligne pendant cinq ans.',
    'J\'ai remporté un tournoi de cartes en famille en trichant sans vergogne.',
    'J\'ai perdu un pari absurde et j\'ai dû me teindre les cheveux en bleu.',
    'J\'ai fait un pari idiot qui m\'a coûté un dîner pour huit personnes.',
    'J\'ai mangé un piment très fort juste pour relever un défi.',
    'J\'ai bu trois doubles cafés en une heure et je n\'ai pas fermé l\'œil de toute la nuit.',
    'J\'ai passé toute la nuit sans fermer l\'œil à cause d\'une angoisse qui s\'est finalement avérée infondée.',
    'J\'ai fait un rêve tellement réaliste que j\'y croyais fermement dès mon réveil.',
    'J\'ai parlé dans mon sommeil, révélant ainsi un secret qui aurait dû rester secret.',
    'Quand j\'étais enfant, je faisais du somnambulisme et je parcourais toute la maison.',
    'Je me suis réveillé dans une autre pièce de la maison que celle où je m\'étais endormi.',
    'J\'ai dormi profondément sur un banc dans un parc public un après-midi.',
    'J\'ai passé toute une journée sans adresser la parole à personne.',
    'J\'ai discuté longuement avec un inconnu pendant deux heures lors d\'un trajet en train.',
    'J\'ai rendu un portefeuille rempli d\'argent que j\'avais trouvé dans la rue.',
    'J\'ai gagné un lot lors d\'une tombola caritative et je ne l\'ai jamais réclamé.',
    'J\'ai mangé exactement la même chose au déjeuner pendant trente jours d\'affilée.',
    'J\'ai fait semblant de parler une langue étrangère pour ne pas être reconnu pendant mes vacances.',
    'J\'ai dû demander de l\'aide à mes voisins parce que je ne trouvais plus mon chat.',
    'J\'ai fait semblant d\'avoir des problèmes de ligne pour mettre fin à un appel professionnel ennuyeux.',
    'Je suis sorti du cinéma au milieu du film parce que je m\'ennuyais à mourir.',
    'J\'ai promené le chien d\'un voisin pendant dix minutes en croyant que c\'était le mien.',
    'J\'ai salué avec beaucoup d\'enthousiasme une personne que je ne connaissais absolument pas.',
    'J\'ai participé à une visite guidée de ma ville en me faisant passer pour un touriste étranger.',
    'J\'ai envoyé mes vœux d\'anniversaire à la mauvaise personne deux années de suite.',
    'J\'ai remporté une discussion animée en citant une statistique totalement inventée.',
    'J\'ai gardé mon parapluie ouvert pendant dix minutes alors que le soleil était déjà sorti.',
    'J\'ai fait une gaffe monumentale lors d\'un entretien d\'embauche, mais on m\'a quand même embauché.',
    'J\'ai gardé une plante artificielle dans le salon pendant des années, en l\'arrosant régulièrement.',
    'J\'ai perdu les clés de ma voiture et je les ai retrouvées un mois plus tard dans le congélateur.',
    'J\'ai dit « bon appétit » au serveur qui m\'apportait mon plat.',
    'J\'ai couru derrière un bus pendant deux cents mètres et j\'ai réussi à le rattraper.',
    'J\'ai oublié où j\'avais garé ma voiture et j\'ai tourné en rond pendant une heure.',
  ];
}
