/// Generato da tool/generate_content.dart (traduzione DeepL dai
/// pool italiani). Stesse posizioni e stesso tono degli originali IT.
class ContentFrImpostore {
  const ContentFrImpostore._();

  static const List<String> impostoreWords = [
    'Plage',
    'Montagne',
    'Aéroport',
    'Gare',
    'Métro',
    'Hôpital',
    'Pharmacie',
    'Supermarché',
    'Boulangerie',
    'Pizzeria',
    'Restaurant',
    'Bar',
    'Discothèque',
    'Salle de sport',
    'Piscine',
    'Bibliothèque',
    'Musée',
    'Cinéma',
    'Théâtre',
    'Stade',
    'École',
    'Université',
    'Bureau',
    'Usine',
    'Chantier',
    'Coiffeur',
    'Dentiste',
    'Banque',
    'Courrier',
    'Hôtel',
    'Camping',
    'Zoo',
    'Verseau',
    'Parc',
    'Jardin',
    'Forêt',
    'Désert',
    'Île',
    'Volcan',
    'Cascade',
    'Ascenseur',
    'Escalier roulant',
    'Feu de signalisation',
    'Autoroute',
    'Ferry',
    'Avion',
    'Train',
    'Vélo',
    'Trottinette',
    'Scooter',
    'Parapluie',
    'Lunettes',
    'Montre',
    'Sac à dos',
    'Valise',
    'Portefeuille',
    'Clés',
    'Téléphone',
    'Chargeur de batterie',
    'Casques audio',
    'Télévision',
    'Réfrigérateur',
    'Lave-linge',
    'Aspirateur',
    'Four',
    'Matelas',
    'Oreiller',
    'Couverture',
    'Canapé',
    'Fauteuil',
    'Miroir',
    'Douche',
    'Serviette',
    'Brosse à dents',
    'Savon',
    'Café',
    'Cornetto',
    'Glace',
    'Pizza',
    'Lasagnes',
    'Sandwich',
    'Salade',
    'Pâtes',
    'Risotto',
    'Soupe',
    'Chocolat',
    'Pop-corn',
    'Chips',
    'Pastèque',
    'Ananas',
    'Limone',
    'Piment',
    'Fromage',
    'Miel',
    'Salles',
    'Chien',
    'Chat',
    'Cheval',
    'Pingouin',
    'Dauphin',
    'Requin',
    'Abeille',
    'Fourmi',
    'Araignée',
    'Serpent',
    'Ballon',
    'Raquette',
    'Panier',
    'Patins',
    'Ski',
    'Guitare',
    'Piano',
    'Batterie',
    'Microphone',
    'Karaoké',
    'Mariage',
    'Anniversaire',
    'Nouvel An',
    'Vacances',
    'Déménagement',
    'Faro',
    'Croisière',
    'Ferme',
    'Cirque',
    'Vignoble',
    'Manège',
    'Planétarium',
    'Moulin',
    'Pompiste',
    'Station de lavage',
    'Blanchisserie',
    'Marché',
    'Marchand de glaces',
    'Sushi',
    'Barbecue',
    'Pique-nique',
    'Mine',
    'Bowling',
    'Parc d\'attractions',
    'Glacier',
    'Sauna',
    'Thermes',
    'Luge',
    'Surf',
    'Tente',
    'Feu de joie',
    'Karaté',
    'Marathon',
    'Tatouage',
    'Château',
  ];
}
