class ContentFrApp {
  const ContentFrApp._();

  static const Map<String, String> ui = {
    'app.tagline': 'Le jeu de soirée où\ntout le monde est connecté.',
    'common.retry': 'RÉESSAYER',
    'common.cancel': 'ANNULER',
    'common.continue': 'CONTINUER',
    'common.back_home': 'RETOUR À L’ACCUEIL',
    'common.loading': 'Un instant…',
    'common.you': 'toi',
    'onboarding.slide1.title': 'La soirée va bientôt\nchanger de rythme',
    'onboarding.slide1.body':
        'Chacun joue sur son propre téléphone, mais vous jouez tous ensemble. Joyo rassemble tout le monde, à vous de jouer.',
    'onboarding.slide2.title': 'Un code et\nvous êtes dedans',
    'onboarding.slide2.body':
        'Crée une salle, partage le code et fais entrer tes amis. En quelques secondes, vous êtes prêts à jouer.',
    'onboarding.slide3.title': 'Six jeux.\nDes possibilités infinies.',
    'onboarding.slide3.body':
        'Tu préfères, Je n’ai jamais, Qui pourrait le faire ?, Action ou vérité, Bluff Story et Imposteur. Choisissez votre jeu et c’est parti.',
    'onboarding.slide4.title': 'C’est toi qui choisis\njusqu’où aller',
    'onboarding.slide4.body':
        'Normal pour commencer, Mix pour changer de rythme, Hot quand vous voulez passer à la vitesse supérieure.',
    'onboarding.language': 'Dans quelle langue jouez-vous ?',
    'onboarding.start': 'COMMENCER',
    'onboarding.skip': 'PASSER',
    'home.create': 'CRÉER UNE SALLE',
    'home.join': 'REJOINDRE AVEC UN CODE',
    'home.games': 'Les jeux',
    'home.connection_failed': 'Impossible de se connecter à Joyo.',
    'home.language': 'Langue',
    'join.title_create': 'Créer une salle',
    'join.title_join': 'Rejoindre la salle',
    'join.name_question': 'Comment tu t’appelles ?',
    'join.name_hint': 'Entre ton prénom',
    'join.color': 'Choisis ta couleur',
    'join.avatar': 'Choisis ton avatar',
    'join.error_avatar': 'Choisis un avatar.',
    'join.code': 'Code de la salle',
    'join.cta_create': 'CRÉER LA SALLE',
    'join.cta_join': 'REJOINDRE',
    'join.error_name': 'Entre ton prénom.',
    'join.error_code': 'Le code doit contenir 6 caractères.',
    'error.room_not_found': 'Impossible de trouver une salle avec ce code.',
    'error.room_full': 'La salle est pleine. 10 joueurs maximum.',
    'error.room_finished': 'Cette partie est déjà terminée.',
    'error.connection': 'Connexion perdue. Vérifie ta connexion et réessaie.',
    'lobby.title': 'Salle d’attente',
    'lobby.code_label': 'CODE DE LA SALLE',
    'lobby.code_hint': 'Partage-le avec tes amis · appuie pour le copier',
    'lobby.code_copied': 'Code copié',
    'lobby.players': 'Joueurs',
    'lobby.you': 'toi',
    'lobby.host_badge': 'HÔTE',
    'lobby.pick_game': 'CHOISIS LE JEU',
    'lobby.waiting_host': 'L’hôte choisit le jeu…',
    'lobby.which_game': 'On joue à quoi ?',
    'lobby.remove_player': 'Retirer {name} ?',
    'lobby.remove_player_body':
        'Utilise cette option si quelqu’un a fermé l’application sans quitter la salle. Il pourra revenir avec le même code.',
    'lobby.remove': 'RETIRER',
    'lobby.exit_host_title': 'Fermer la salle ?',
    'lobby.exit_host_body':
        'La salle sera fermée pour tout le monde et les autres joueurs retourneront à l’accueil.',
    'lobby.exit_title': 'Quitter la salle ?',
    'lobby.exit_body':
        'Tu es sur le point de quitter la salle. Les autres joueurs le verront.',
    'lobby.stay': 'RESTER',
    'lobby.close': 'FERMER',
    'lobby.leave': 'QUITTER',
    'lobby.exit_failed': 'Impossible de quitter la salle : {detail}',
    'lobby.room_closed': 'L’hôte a fermé la salle.',
    'lobby.reconnecting': 'Reconnexion…',
    'lobby.entering': 'Connexion à la salle…',
    'mode.title': 'Modes',
    'mode.normale': 'Normal',
    'mode.mix': 'Mix',
    'mode.hot': 'Hot',
    'mode.normale.desc':
        'Les règles de base. Le moyen le plus simple de commencer.',
    'mode.mix.desc':
        'Plus de variété, plus de rythme et quelques surprises en plus.',
    'mode.hot.desc':
        'Plus direct, plus personnel. Seulement si vous êtes prêts.',
    'settings.rounds': 'Manches par partie',
    'game.round_of': 'Manche {n} sur {total}',
    'game.preparing': 'Préparation de la manche…',
    'game.create_failed': 'Impossible de créer la manche : {detail}',
    'game.close_failed': 'Impossible de terminer la manche : {detail}',
    'game.vote_failed': 'Réponse non enregistrée : {detail}',
    'game.next_round': 'MANCHE SUIVANTE',
    'game.see_podium': 'VOIR LE PODIUM',
    'game.waiting_next': 'L’hôte va bientôt lancer la prochaine manche…',
    'game.finished': 'Partie terminée',
    'game.answered': '{n} sur {total} ont répondu',
    'game.back_to_lobby': 'RETOUR À LA SALLE',
    'game.lobby_short': 'SALLE',
    'game.host_only': 'Seul l’hôte peut relancer le jeu depuis la salle.',
    'game.coming_soon': 'BIENTÔT DISPONIBLE',
    'podium.title': 'Fin de la partie',
    'podium.winner': '{name} gagne',
    'podium.no_scores':
        'Ce jeu ne rapporte pas de points. Ici, l’important, c’est de jouer.',
    'podium.points': '{n} points',
    'podium.points_one': '{n} point',
    'preferisci.name': 'Tu préfères',
    'preferisci.tagline': 'Deux choix. Une réponse. Tu choisis quoi ?',
    'preferisci.prompt': 'Tu préfères…',
    'preferisci.or': 'ou',
    'preferisci.split': 'Voici le choix du groupe',
    'preferisci.no_votes': 'Personne n’a répondu',
    'non_ho_mai.name': 'Je n’ai jamais',
    'non_ho_mai.tagline': 'C’est arrivé ou pas ? On va le découvrir.',
    'non_ho_mai.prompt': 'Je n’ai jamais…',
    'non_ho_mai.done': 'JE L’AI FAIT',
    'non_ho_mai.never': 'JAMAIS',
    'non_ho_mai.anonymous':
        'Les réponses sont anonymes. Seul le total est affiché.',
    'non_ho_mai.nobody': 'Personne ne l’a fait',
    'non_ho_mai.count': '{n} sur {total}',
    'non_ho_mai.guess_who': 'À vous de deviner maintenant qui l’a fait',
    'chi.name': 'Qui pourrait le faire',
    'chi.tagline': 'Une question. Un nom. À vous de décider.',
    'chi.decided': 'Le groupe a décidé',
    'chi.tie': 'Égalité',
    'chi.no_votes': 'Aucun vote',
    'obbligo.name': 'Action ou vérité',
    'obbligo.tagline': 'Cette fois, ce n’est plus toi qui décides.',
    'obbligo.spinning': 'La bouteille tourne…',
    'obbligo.your_turn': 'À toi de jouer',
    'obbligo.turn_of': 'Au tour de {name}',
    'obbligo.choosing': 'Choix en cours…',
    'obbligo.dare': 'ACTION',
    'obbligo.truth': 'VÉRITÉ',
    'obbligo.no_choice': '{name} n’a pas choisi à temps',
    'obbligo.when_done':
        'Une fois terminé, l’hôte peut lancer la prochaine manche',
    'bluff.name': 'Bluff Story',
    'bluff.tagline': 'Une vérité. Deux mensonges. Sauras-tu bluffer ?',
    'bluff.writing': '{name} écrit\nune vérité à son sujet',
    'bluff.your_turn_body':
        'Écris une vérité sur toi. Nous ajouterons deux mensonges. Les autres devront trouver laquelle est vraie.',
    'bluff.hint': 'Écris ta vérité…',
    'bluff.send': 'ENVOYER TA VÉRITÉ',
    'bluff.too_short': 'Écris au moins 30 caractères.',
    'bluff.which_true': 'Quelle est la vérité sur {name} ?',
    'bluff.in_play': 'Ton histoire est en jeu',
    'bluff.dont_tell': 'Ne laisse pas les autres deviner laquelle est vraie.',
    'bluff.your_truth': 'ta vérité',
    'bluff.true_label': 'vraie',
    'bluff.truth_of': 'La vérité sur {name}',
    'bluff.nobody_guessed': 'Personne n’a trouvé. {name} vous a tous bluffés.',
    'bluff.guessed': '{n} ont trouvé',
    'bluff.guessed_one': '{n} a trouvé',
    'bluff.scoring':
        '+2 à chaque bonne réponse · +1 à {name} pour chaque bluff réussi',
    'bluff.multilang_title': 'Des langues différentes à table',
    'bluff.multilang_body':
        'Votre groupe joue dans des langues différentes : les mensonges '
        'sortent traduits, mais la phrase vraie reste dans la langue de la '
        'personne qui l\'écrit et peut se faire repérer aussitôt.',
    'bluff.ai_working': 'Je prépare deux mensonges…',
    'bluff.ai_working_sub': 'pensés pour l’histoire de {name}',
    'impostore.name': 'Imposteur',
    'impostore.tagline': 'L’un de vous joue avec des informations différentes.',
    'impostore.only_you': 'Toi seul peux voir ça',
    'impostore.you_are': 'Tu es l’imposteur',
    'impostore.you_are_body':
        'Tu ne connais pas le mot. Écoute les autres, improvise et ne te fais pas repérer. Si tu es démasqué mais que tu trouves le mot, tu récupères des points.',
    'impostore.the_word': 'Le mot secret est',
    'impostore.one_doesnt': 'L’un de vous ne connaît pas le mot.',
    'impostore.round_of_words': 'Tour de mots',
    'impostore.round_of_words_body':
        'À tour de rôle, chacun dit un seul mot lié au secret.\nTrop précis et tu aides l’imposteur. Trop vague et c’est toi qui risques de passer pour l’imposteur.',
    'impostore.your_word': 'Ton mot : {word}',
    'impostore.to_vote': 'PASSER AU VOTE',
    'impostore.who': 'Qui est l’imposteur ?',
    'impostore.guess_hint': 'Le mot secret était…',
    'impostore.guess_body':
        'Tu es l’imposteur. Essaie de trouver le mot : si les autres te démasquent mais que tu trouves la bonne réponse, tu récupères des points.',
    'impostore.confirm': 'CONFIRMER',
    'impostore.vote_registered': 'Vote enregistré',
    'impostore.caught': 'Imposteur découvert',
    'impostore.escaped': 'L’imposteur s’est échappé',
    'impostore.word_was': 'Le mot était',
    'impostore.guessed_it': 'Bonne réponse : « {guess} » · +3 points',
    'impostore.said': 'Réponse donnée : « {guess} »',
    'impostore.points_caught': '+2 à ceux qui ont voté pour l’imposteur',
    'impostore.points_escaped': '+5 pour l’imposteur',
    'impostore.votes': '{n} votes',
    'impostore.votes_one': '{n} vote',
    'premium.title': 'Contenus personnalisés',
    'premium.body':
        'Dans « Qui pourrait le faire » et « Bluff Story », l’IA crée des contenus pensés pour votre groupe au lieu d’utiliser des phrases prédéfinies.',
    'premium.active': 'IA active dans cette salle',
    'premium.active_body': 'Contenus générés pour votre groupe',
    'premium.unlock': 'DÉBLOQUER',
    'premium.watch_ad': 'REGARDER LA PUB',
    'premium.host_only': 'Seul l’hôte peut la débloquer.',
    'premium.credits': '{n} crédits',
    'premium.unlocked': 'IA débloquée pour cette salle',
    'premium.ad_reward': 'Tu as obtenu un contenu généré par l’IA',
    'premium.ad_incomplete': 'Publicité non terminée.',
    'premium.no_store':
        'Les achats ne sont pas disponibles ici. Utilise Google Play ou l’App Store.',
    'premium.ads_mobile_only':
        'Les publicités sont disponibles uniquement sur mobile.',

    'shop.badge': 'Premium',
    'shop.title': 'Débloque Mix et Hot',
    'shop.body':
        'Mix et Hot sont des modes premium. Regarde 3 publicités pour les débloquer le temps d’une partie.',
    'shop.progress': '{n}/3 publicités',
    'shop.watch': 'REGARDER UNE PUB',
    'shop.unlocked': 'Mix et Hot débloqués pour une partie',
    'shop.host_only': 'Seul l’hôte peut les débloquer.',
    'shop.go_premium': 'Ou passe à Premium',
    'shop.page_title': 'Boutique',
    'shop.free_title': 'Débloque avec des pubs',
    'shop.in_room_only': 'Disponible dans un salon, en tant qu’hôte.',
    'shop.games': '{n} parties premium prêtes',
    'endgame.promo': 'Envie de plus d’étincelles et moins de pubs ?',
    'endgame.shop_cta': 'DÉCOUVRIR PREMIUM',

    'paywall.title': 'Passe à Premium',
    'paywall.no_ads_name': 'Sans publicité',
    'paywall.no_ads_desc': 'Joue sans publicité.',
    'paywall.premium_name': 'Premium',
    'paywall.premium_desc': 'Mix, Hot, parties plus longues et sans publicité.',
    'paywall.per_month': '/mois',
    'paywall.active': 'Actif',
    'paywall.subscribe': 'S’ABONNER',
    'paywall.restore': 'Restaurer les achats',
    'paywall.restored': 'Abonnement restauré',
    'paywall.nothing_restored': 'Aucun abonnement à restaurer',
  };
}
