/// Generato da tool/generate_content.dart (traduzione DeepL dai
/// pool italiani). Stesse posizioni e stesso tono degli originali IT.
class ContentFrApp {
  const ContentFrApp._();

  static const Map<String, String> ui = {
    'app.tagline':
        'Le jeu festif pour ceux qui ont\nchacun leur propre téléphone.',
    'common.retry': 'Réessayez',
    'common.cancel': 'Annuler',
    'common.continue': 'SUIVANT',
    'common.back_home': 'RETOUR À LA PAGE D\'ACCUEIL',
    'common.loading': 'Attends un instant…',
    'common.you': 'toi',
    'onboarding.slide1.title': 'La soirée prend\nune tournure inattendue',
    'onboarding.slide1.body':
        'Chacun avec son téléphone, tous dans la même pièce. Joyo relie les écrans, à vous de semer le chaos.',
    'onboarding.slide2.title':
        'Le code en main,\non entre dans le vif du sujet',
    'onboarding.slide2.body':
        'Ouvre la pièce, crie le code et regarde tes amis s\'y précipiter en quelques secondes.',
    'onboarding.slide3.title': 'Six jeux pour\nne jamais s\'ennuyer',
    'onboarding.slide3.body':
        'Vote pour tes amis, invente des mensonges colossaux ou tente ta chance avec la bouteille. À fond !',
    'onboarding.slide4.title':
        'C\'est toi qui décides\njusqu\'où tu veux aller',
    'onboarding.slide4.body':
        'Mode « Normal » pour se mettre dans l\'ambiance, « Mix » pour animer la soirée, « Hot » pour quand les masques tombent.',
    'onboarding.language': 'Dans quelle langue jouez-vous ?',
    'onboarding.start': 'COMMENCER',
    'onboarding.skip': 'Passer',
    'home.create': 'CRÉER UNE PIÈCE',
    'home.join': 'INSCRIVEZ-VOUS AVEC UN CODE',
    'home.games': 'Les jeux',
    'home.connection_failed': 'Échec de la connexion à Joyo.',
    'home.language': 'Langue',
    'join.title_create': 'Créer une salle',
    'join.title_join': 'Rejoignez-nous',
    'join.name_question': 'Comment tu t\'appelles ?',
    'join.name_hint': 'Ton nom',
    'join.color': 'Ta couleur',
    'join.code': 'Code de la chambre',
    'join.cta_create': 'CRÉEZ LA PIÈCE',
    'join.cta_join': 'ENTRER',
    'join.error_name': 'Écris ton nom.',
    'join.error_code': 'Le code comporte 6 caractères.',
    'error.room_not_found': 'Aucune chambre ne correspond à ce code.',
    'error.room_full': 'La salle est pleine : 10 joueurs maximum.',
    'error.room_finished': 'Ce match est déjà terminé.',
    'error.connection':
        'Connexion perdue. Rouvrez l\'application et réessayez.',
    'lobby.title': 'Hall d\'entrée',
    'lobby.code_label': 'CODE DE LA SALLE',
    'lobby.code_hint': 'Dis-le à voix haute · appuie pour copier',
    'lobby.code_copied': 'Code copié',
    'lobby.players': 'Joueurs',
    'lobby.you': 'toi',
    'lobby.host_badge': 'HÔTE',
    'lobby.pick_game': 'CHOISIS LE JEU',
    'lobby.waiting_host': 'L\'animateur est en train de choisir le jeu…',
    'lobby.which_game': 'À quoi on joue ?',
    'lobby.remove_player': 'Supprimer {name} ?',
    'lobby.remove_player_body':
        'Utilisez-le si quelqu\'un a fermé l\'application sans se déconnecter. Il pourra toujours se reconnecter grâce à ce code.',
    'lobby.remove': 'Supprimer',
    'lobby.exit_host_title': 'Fermer la pièce ?',
    'lobby.exit_host_body':
        'La salle se ferme pour tout le monde : les autres joueurs retournent à la page d\'accueil.',
    'lobby.exit_title': 'Sortir de la pièce ?',
    'lobby.exit_body': 'Les autres joueurs te verront sortir.',
    'lobby.stay': 'Reste',
    'lobby.close': 'Fermer',
    'lobby.leave': 'Quitter',
    'lobby.exit_failed': 'Échec de la sortie : {detail}',
    'lobby.room_closed': 'La salle a été fermée par l\'hôte.',
    'lobby.reconnecting': 'Reconnexion…',
    'lobby.entering': 'J\'entre dans la pièce…',
    'mode.title': 'Modalités',
    'mode.normale': 'Normal',
    'mode.mix': 'Mix',
    'mode.hot': 'Tendance',
    'mode.normale.desc':
        'Idéale pour briser la glace sans trop de difficultés.',
    'mode.mix.desc':
        'Les jeux s\'enchaînent et le rythme s\'accélère. Accrochez-vous bien.',
    'mode.hot.desc': 'Sans limites. À ne jouer que si vous êtes prêts à tout.',
    'settings.rounds': 'Nombre de manches par match',
    'game.round_of': 'Round {n} sur {total}',
    'game.preparing': 'Je prépare le round…',
    'game.create_failed': 'Je n\'arrive pas à créer le tour : {detail}',
    'game.close_failed': 'Je n\'arrive pas à terminer le round : {detail}',
    'game.vote_failed': 'Réponse non enregistrée : {detail}',
    'game.next_round': 'PROCHAIN TOUR',
    'game.see_podium': 'VOIR LE PODIUM',
    'game.waiting_next':
        'Le présentateur s\'apprête à lancer la prochaine manche…',
    'game.finished': 'Le match est terminé',
    'game.answered': '{n} personnes sur {total} ont répondu',
    'game.back_to_lobby': 'RETOUR À LA PAGE D\'ACCUEIL',
    'game.lobby_short': 'LOBBY',
    'game.host_only': 'L\'hôte peut relancer la partie depuis le hall.',
    'game.coming_soon': 'À venir',
    'podium.title': 'Fin du match',
    'podium.winner': '{name} remporte la victoire',
    'podium.no_scores':
        'Ce jeu n\'attribue pas de points : pas de classement, juste la partie.',
    'podium.points': '{n} points',
    'podium.points_one': '{n} point',
    'preferisci.name': 'Tu préfères',
    'preferisci.tagline': 'Des choix atroces : qui partage ton avis ?',
    'preferisci.prompt': 'Tu préfères…',
    'preferisci.or': 'ou bien',
    'preferisci.split': 'Le groupe s\'est réparti comme suit',
    'preferisci.no_votes': 'Personne n\'a répondu',
    'non_ho_mai.name': 'Je n\'ai jamais',
    'non_ho_mai.tagline':
        'Le confessionnal est ouvert. Confesse-toi et tu survivras.',
    'non_ho_mai.prompt': 'Je n\'ai jamais…',
    'non_ho_mai.done': 'JE L\'AI FAIT',
    'non_ho_mai.never': 'JAMAIS',
    'non_ho_mai.anonymous':
        'Personne ne verra ce que tu as répondu : on ne voit que le décompte.',
    'non_ho_mai.nobody': 'Personne ne l\'a fait',
    'non_ho_mai.count': '{n} sur {total}',
    'non_ho_mai.guess_who': 'À vous maintenant de deviner qui c\'est',
    'chi.name': 'Qui pourrait le faire ?',
    'chi.tagline': 'Le jeu où l\'on pointe du doigt (littéralement).',
    'chi.decided': 'Le groupe a décidé',
    'chi.tie': 'Égalité de mérite',
    'chi.no_votes': 'Aucune note',
    'obbligo.name': 'Action ou vérité',
    'obbligo.tagline':
        'C\'est la bouteille qui décide, toi tu transpires. Pas d\'excuses.',
    'obbligo.spinning': 'La bouteille tourne…',
    'obbligo.your_turn': 'À toi de jouer',
    'obbligo.turn_of': 'C\'est au tour de {name}',
    'obbligo.choosing': 'Il est en train de choisir…',
    'obbligo.dare': 'OBLIGATION',
    'obbligo.truth': 'VÉRITÉ',
    'obbligo.no_choice': '{name} n\'a pas fait son choix à temps',
    'obbligo.when_done':
        'Une fois qu\'il a terminé, l\'animateur lance la prochaine manche',
    'bluff.name': 'L\'histoire d\'un bluff',
    'bluff.tagline':
        'Mentir, c\'est tout un art. Arrives-tu à ne pas te faire prendre ?',
    'bluff.writing':
        '{name} est en train d\'écrire\nune anecdote vraie à son sujet',
    'bluff.your_turn_body':
        'Écris un fait vrai te concernant. Le jeu va glisser deux mensonges parmi ceux-ci : les autres devront deviner lequel est le tien.',
    'bluff.hint': 'Écris ici…',
    'bluff.send': 'ENVOIE TA VÉRITÉ',
    'bluff.too_short': 'Écris quelque chose d\'un peu plus long.',
    'bluff.which_true': 'Quelle est la vérité sur {name} ?',
    'bluff.in_play': 'Ton histoire est en jeu',
    'bluff.dont_tell': 'Ne passe pas à côté de la vraie.',
    'bluff.your_truth': 'ta vérité',
    'bluff.true_label': 'vraie',
    'bluff.truth_of': 'La vérité sur {name}',
    'bluff.nobody_guessed': 'Personne n\'a deviné : {name} vous a tous bernés',
    'bluff.guessed': '{n} ont trouvé la bonne réponse',
    'bluff.guessed_one': '{n} a trouvé la bonne réponse',
    'bluff.scoring':
        '+2 à celui qui a deviné · +1 à {name} pour chaque bluff réussi',
    'bluff.ai_working': 'Je suis en train d\'inventer deux mensonges…',
    'bluff.ai_working_sub': 'conçu sur mesure pour l\'histoire de {name}',
    'impostore.name': 'Imposteur',
    'impostore.tagline':
        'Un intrus parmi nous. Trouve-le avant qu\'il ne soit trop tard.',
    'impostore.only_you': 'Tu es le seul à voir ça',
    'impostore.you_are': 'C\'est toi l\'imposteur',
    'impostore.you_are_body':
        'Tu ne connais pas ce mot. Écoute, improvise et ne te fais pas démasquer : si tu devines le mot à la fin, tu récupères des points.',
    'impostore.the_word': 'Le mot est',
    'impostore.one_doesnt': 'L\'un d\'entre vous ne la connaît pas.',
    'impostore.round_of_words': 'Jeu de mots',
    'impostore.round_of_words_body':
        'À tour de rôle, chacun dit un seul mot en rapport avec le secret.\nSi c\'est trop précis, l\'imposteur comprendra ; si c\'est trop vague, c\'est vous qui passerez pour l\'imposteur.',
    'impostore.your_word': 'Ton mot : {word}',
    'impostore.to_vote': 'PASSER AU VOTE',
    'impostore.who': 'Qui est l\'imposteur ?',
    'impostore.guess_hint': 'Le mot secret était…',
    'impostore.guess_body':
        'C\'est toi l\'imposteur : essaie de deviner le mot. Si tu te fais démasquer mais que tu trouves la bonne réponse, tu regagnes des points.',
    'impostore.confirm': 'CONFIRMATION',
    'impostore.vote_registered': 'Vote enregistré',
    'impostore.caught': 'Un imposteur démasqué',
    'impostore.escaped': 'L\'imposteur s\'en est tiré à bon compte',
    'impostore.word_was': 'Le mot était',
    'impostore.guessed_it':
        'Vous avez trouvé la bonne réponse : « {guess} » · +3 points',
    'impostore.said': 'Il avait dit : « {guess} »',
    'impostore.points_caught': '+2 à ceux qui ont voté pour l\'imposteur',
    'impostore.points_escaped': '+5 pour l\'imposteur',
    'impostore.votes': '{n} votes',
    'impostore.votes_one': '{n} vote',
    'premium.title': 'Contenus sur mesure',
    'premium.body':
        'Dans « Qui pourrait le faire ? » et « Bluff Story », les phrases sont écrites par votre groupe plutôt que tirées d\'une liste.',
    'premium.active': 'IA active dans cette pièce',
    'premium.active_body':
        'Questions et fausses informations diffusées au sein de votre groupe',
    'premium.unlock': 'DÉVERROUILLER',
    'premium.watch_ad': 'ANNONCE',
    'premium.host_only': 'C\'est l\'hébergeur qui peut la débloquer.',
    'premium.credits': '{n} crédits',
    'premium.unlocked': 'IA débloquée pour cette pièce',
    'premium.ad_reward': 'Tu as débloqué un contenu généré par l\'IA',
    'premium.ad_incomplete': 'Annonce non finalisée.',
    'premium.no_store':
        'Ces achats ne sont pas disponibles ici : vous devez passer par Google Play ou l\'App Store.',
    'premium.ads_mobile_only':
        'Les annonces ne fonctionnent que sur téléphone.',
  };
}
