class ContentFrImpostore {
  const ContentFrImpostore._();

  static const List<String> impostoreWords = [
    'Plage',
    'Montagne',
    'Aéroport',
    'Gare',
    'Métro',
    'Hôpital',
    'Pharmacie',
    'Supermarché',
    'Boulangerie',
    'Pizzeria',
    'Restaurant',
    'Bar',
    'Discothèque',
    'Salle de sport',
    'Piscine',
    'Bibliothèque',
    'Musée',
    'Cinéma',
    'Théâtre',
    'Stade',
    'École',
    'Université',
    'Bureau',
    'Usine',
    'Chantier',
    'Coiffeur',
    'Dentiste',
    'Banque',
    'Poste',
    'Hôtel',
    'Camping',
    'Zoo',
    'Aquarium',
    'Parc',
    'Jardin',
    'Forêt',
    'Désert',
    'Île',
    'Volcan',
    'Cascade',
    'Ascenseur',
    'Escalier mécanique',
    'Feu de signalisation',
    'Autoroute',
    'Ferry',
    'Avion',
    'Train',
    'Vélo',
    'Trottinette',
    'Scooter',
    'Parapluie',
    'Lunettes',
    'Montre',
    'Sac à dos',
    'Valise',
    'Portefeuille',
    'Clés',
    'Téléphone',
    'Chargeur de batterie',
    'Casques audio',
    'Télévision',
    'Réfrigérateur',
    'Lave-linge',
    'Aspirateur',
    'Four',
    'Matelas',
    'Oreiller',
    'Couverture',
    'Canapé',
    'Fauteuil',
    'Miroir',
    'Douche',
    'Serviette',
    'Brosse à dents',
    'Savon',
    'Café',
    'Croissant',
    'Glace',
    'Pizza',
    'Lasagnes',
    'Sandwich',
    'Salade',
    'Pâtes',
    'Risotto',
    'Soupe',
    'Chocolat',
    'Pop-corn',
    'Chips',
    'Pastèque',
    'Ananas',
    'Citron',
    'Piment',
    'Fromage',
    'Miel',
    'Sel',
    'Chien',
    'Chat',
    'Cheval',
    'Pingouin',
    'Dauphin',
    'Requin',
    'Abeille',
    'Fourmi',
    'Araignée',
    'Serpent',
    'Ballon',
    'Raquette',
    'Panier',
    'Patins',
    'Ski',
    'Guitare',
    'Piano',
    'Batterie',
    'Microphone',
    'Karaoké',
    'Mariage',
    'Anniversaire',
    'Nouvel An',
    'Vacances',
    'Déménagement',
    'Phare',
    'Croisière',
    'Ferme',
    'Cirque',
    'Vignoble',
    'Manège',
    'Planétarium',
    'Moulin',
    'Station-service',
    'Station de lavage',
    'Blanchisserie',
    'Marché',
    'Glacier',
    'Sushi',
    'Barbecue',
    'Pique-nique',
    'Mine',
    'Bowling',
    'Parc d\'attractions',
    'Glacier (montagne)',
    'Sauna',
    'Thermes',
    'Luge',
    'Surf',
    'Tente',
    'Feu de camp',
    'Karaté',
    'Marathon',
    'Tatouage',
    'Château',
  ];
}
