import '../content_tone.dart';

/// Generato da tool/generate_content.dart (traduzione DeepL dai
/// pool italiani). Stesse posizioni e stesso tono degli originali IT.
class ContentFrObbligoOVerita {
  const ContentFrObbligoOVerita._();

  static const Map<String, List<String>> obblighi = {
    ContentTone.normal: [
      'Imité la façon de marcher de la personne à ta droite.',
      'Chante le refrain de la dernière chanson que tu as écoutée.',
      'Parle en rimes jusqu\'à ton prochain tour.',
      'Imité le cri de trois animaux et fais-les deviner.',
      'Danse pendant dix secondes sans musique.',
      'Raconte une blague : si personne ne rit, répète-la plus fort.',
      'Imité ton personnage préféré d\'une série.',
      'Prends la pose d\'une statue et reste immobile pendant trente secondes.',
      'Parle comme un commentateur sportif pendant une minute.',
      'Affiche la dernière photo que tu as prise.',
      'Affichez votre écran d\'accueil sans rien ouvrir.',
      'Montre-nous l\'émoji que tu utilises le plus souvent et explique-nous pourquoi tu as choisi celui-là.',
      'Montre-nous combien d\'alarmes tu as programmées.',
      'Pose une question absurde, choisie par le groupe, à l\'assistant vocal de ton téléphone.',
      'Envoie un message vocal chanté à l\'un de tes contacts, au hasard.',
      'Appelle un ami et chante-lui « Joyeux anniversaire », même si ce n\'est pas son anniversaire.',
      'Fais un compliment sincère à chaque personne présente.',
      'Décris la personne à ta gauche en utilisant seulement trois mots.',
      'Invente un rap de vingt secondes sur la personne à ta gauche.',
      'Imité le professeur dont tu te souviens le moins bien.',
      'Fais comme si tu étais un vendeur et vends-nous cette table.',
      'Présente la météo de demain comme à la télévision.',
      'Parle avec un accent étranger jusqu\'au prochain tour.',
      'Racontez l\'intrigue d\'un film sans en donner le titre ; les autres doivent le deviner.',
      'Fais un discours de remerciement comme si tu avais remporté un prix.',
      'Créez une publicité à la volée pour l\'objet le plus proche de vous.',
      'Montre-nous comment tu danses quand tu es seul à la maison.',
      'Chante au lieu de parler pendant les deux prochaines minutes.',
      'Il marche avec un livre en équilibre sur la tête.',
      'Enfile tes vêtements à l\'envers pendant deux tours.',
      'Demande à la personne à ta droite de te faire une nouvelle coiffure.',
      'Fais un dessin du groupe en trente secondes.',
      'Écris ton nom avec la main qui n\'est pas la tienne et montre-le.',
      'Dessine le portrait d\'un présent les yeux fermés, puis offre-le-lui.',
      'Récite l\'alphabet à l\'envers aussi vite que possible.',
      'Compte jusqu\'à vingt en sautant les multiples de trois.',
      'Dis trois mots à l\'envers, en commençant par le dernier.',
      'Raconte une histoire inventée de trente secondes qui commence par « Hier soir… ».',
      'Raconte ta journée comme si c\'était un film d\'horreur.',
      'Décris ton travail ou ta journée type comme le ferait un enfant.',
      'Fais comme si tu étais un robot pendant une minute.',
      'Réponds uniquement par des questions jusqu\'au prochain tour.',
      'Tu ne peux pas dire « oui » ni « non » avant ton prochain tour.',
      'Parle de toi à la troisième personne jusqu\'à ton prochain tour.',
      'Ris aussi fort que possible, sans raison.',
      'Reste très sérieux pendant trente secondes pendant que les autres essaient de te faire rire.',
      'Fais vingt secondes de planche pendant que les autres comptent.',
      'Fais cinq pompes, au rythme indiqué par le groupe.',
      'Cours sur place jusqu\'à la fin de ton service.',
      'Fais dix squats en prononçant le nom d\'un objet présent à chaque flexion.',
      'Mange quelque chose choisi par la personne à ta gauche.',
      'Goûte deux choses ensemble qui ne vont pas bien ensemble.',
      'Rédige une critique digne d\'un critique étoilé sur le dernier plat que tu as mangé aujourd\'hui.',
      'Prépare une boisson sans alcool et fais-la goûter à quelqu\'un.',
      'Lève ton verre de manière spontanée en l\'honneur du groupe.',
      'Raconte ton plus beau souvenir avec une personne présente.',
      'Raconte comment tu as fait la connaissance de la personne qui se trouve en face de toi.',
      'Dis ce que tu envies (dans le bon sens du terme) à chaque personne présente.',
      'Fais une prédiction sur l\'avenir d\'une personne présente.',
      'Donne un surnom à chacun et explique-le.',
      'Réponds uniquement sous le nouveau surnom choisi par le groupe jusqu\'à la fin du match.',
      'Choisissez qui, parmi ce groupe, vous emmèneriez sur une île déserte et expliquez pourquoi.',
      'Raconte-nous l\'achat le plus cher que tu aies fait sans raison.',
      'Avoue-nous une de tes habitudes bizarres.',
      'Raconte-nous une de tes peurs ridicules.',
      'Fais semblant d\'avoir peur d\'un objet qui se trouve dans la pièce.',
      'Parle-nous d\'un de tes talents inutiles et montre-nous ce dont tu es capable.',
      'Montre-nous ton meilleur « tour de magie » improvisé.',
      'Fais un origami avec ce que tu trouves en une minute.',
      'Construis une tour avec trois objets de la pièce.',
      'Trouve trois objets jaunes dans la maison en trente secondes.',
      'Échange un vêtement que tu portes avec la personne à ta droite.',
      'Prends un selfie en faisant la plus grosse grimace possible.',
      'Prends une photo en imitant la pose de la personne qui se trouve à ta gauche.',
      'Réalise une vidéo de dix secondes comme si tu étais un influenceur.',
      'Enregistre un message de motivation pour le groupe.',
      'Lis l\'horoscope du jour d\'une voix théâtrale.',
      'Invente un horoscope pour la personne assise à ta droite.',
      'Décris comment sera ta vie dans dix ans, sans trop y réfléchir.',
      'Déclare ton amour éternel à un objet de la pièce : le canapé compte.',
      'Joue une scène d\'adieu déchirante avec un oreiller.',
      'Dis-moi quelle chanson tu connais par cœur et chante-en un extrait.',
      'Chante au karaoké pendant dix secondes sans musique.',
      'Siffle une chanson et fais-la deviner.',
      'Fais un beatbox de cinq secondes.',
      'Il imite le son de trois instruments différents.',
      'Fais semblant de jouer de la guitare comme lors d\'un concert.',
      'Danse comme si tu étais tout seul en boîte.',
      'Apprends un pas de danse au groupe.',
      'Prends une photo de groupe en donnant toi-même les instructions.',
      'Choisis la bande originale de la soirée et explique pourquoi.',
      'Raconte-nous la plus belle chose qui t\'est arrivée cette semaine.',
      'Dis-moi une chose que tu aimerais apprendre et pourquoi tu ne t\'y es pas encore mis.',
      'Fais une liste de trois choses pour lesquelles tu es reconnaissant en ce moment.',
      'Envoie un petit message sympa à quelqu\'un à qui tu n\'as pas écrit depuis longtemps.',
      'Appelle ta mère ou un membre de ta famille et dis-lui que tu l\'aimes.',
      'Envoie « Bonjour ! » accompagné de trois emojis choisis au hasard dans le chat familial.',
      'Laisse le groupe choisir ta prochaine action pour le tour suivant.',
      'Il défile comme un mannequin d\'un bout à l\'autre de la pièce, pirouette comprise.',
      'Comporte-toi comme un T-Rex aux bras courts jusqu\'à ton prochain tour.',
      'Utilise une télécommande ou une brosse comme micro chaque fois que tu parles, pendant un tour.',
      'Joue au serveur : prends très au sérieux les commandes imaginaires de tout le monde.',
      'Mime un film sans parler jusqu\'à ce que le groupe devine de quel film il s\'agit.',
      'Imitez un personnage célèbre choisi par le groupe jusqu\'à ce que quelqu\'un devine de qui il s\'agit.',
      'Fais un compliment à chaque personne présente en sautillant sur une jambe.',
      'Essaie de te lécher le coude de toutes tes forces pendant dix secondes.',
      'Raconte une histoire pour s\'endormir en trente secondes en imitant toutes les voix.',
      'Parle pendant une minute d\'un sujet choisi par le groupe, comme si tu étais le plus grand expert en la matière.',
      'Répète trois fois de suite un virelangue choisi par le groupe sans faire d\'erreur.',
      'Décris ce que fait la personne en face de toi comme si tu réalisais un documentaire sur la nature.',
      'Fais cinq mimiques à la demande : heureux, en colère, surpris, amoureux, méfiant.',
      'Danse un slow romantique avec un balai ou un oreiller.',
      'Présente un journal télévisé avec trois informations absurdes sur les personnes présentes.',
      'Fais écho : répète le dernier mot de la personne qui parle jusqu\'à ce que ce soit à nouveau ton tour de parler.',
      'Parle à voix basse jusqu\'à ton prochain tour, quoi qu\'il arrive.',
      'Garde un immense sourire sur le visage pendant trois minutes, quoi qu\'il arrive.',
      'Compose un hymne pour le groupe sur l\'air d\'une chanson célèbre et chante-le.',
      'Demande au groupe de te faire prendre la pose comme une statue et reste ainsi le temps d\'une photo.',
      'Tu fais une scène dramatique digne d\'un feuilleton parce qu\'il ne reste plus qu\'un biscuit.',
      'Essaie de faire rire la personne la plus sérieuse du groupe en trente secondes, sans la toucher.',
      'Empile autant d\'oreillers que possible sur toi et reste en équilibre pendant dix secondes.',
      'Invente une langue et « traduis » ce que dit la personne à ta droite.',
      'Fais comme si tu étais coincé dans une boîte invisible jusqu\'à ce que quelqu\'un te « libère ».',
      'Racontez comment ce groupe s\'est formé, à la manière d\'un documentaire historique.',
      'Veuillez vous adresser à tout le monde en utilisant le « vous » jusqu\'à votre prochain tour, avec une extrême formalité.',
      'Réalise un tutoriel de cuisine imaginaire avec les objets que tu as sous les yeux.',
      'Avance au ralenti jusqu\'à la fin du tour, rediffusions comprises.',
      'Dis bonjour en cinq langues différentes, en inventant celles que tu ne connais pas.',
      'Imité un animal jusqu’à ce que quelqu’un devine lequel.',
      'Réponds en chantant à tout ce qu’on te dit jusqu’à ce que ce soit ton tour.',
      'Fais dix petits sauts sur place en criant ton nom.',
      'Invente une devise pour le groupe et répète-la à voix haute.',
      'Joue le rôle de commentateur de la pièce pendant trente secondes.',
      'Imagine une publicité pour l\'objet situé à ta droite.',
      'Ne parle qu’à voix basse jusqu’à ce que ce soit à nouveau ton tour.',
      'Tu restes immobile comme une statue pendant que les autres essaient de te faire rire.',
      'Fais du play-back sur une chanson de ton choix du groupe pendant quinze secondes.',
      'Imite un personnage célèbre choisi par le groupe.',
      'Résume l\'intrigue d\'un film célèbre en exactement dix mots.',
      'Récite les jours de la semaine à l\'envers aussi vite que possible.',
      'Fais comme si tu remportais un Oscar et remercie les personnes présentes une par une.',
      'Marche comme un robot jusqu\'à la porte, puis reviens.',
      'Trouve un surnom sympa pour chacune des personnes présentes.',
      'Chante « Tanti auguri » comme s\'il s\'agissait d\'une chanson de rock.',
      'Fais cinq expressions différentes en cinq secondes.',
      'Garde un oreiller en équilibre sur ta tête pendant un tour complet.',
      'Décris ta journée en utilisant uniquement des sons.',
      'Fais une prévision météo inventée de toutes pièces, en prenant cela très au sérieux.',
      'Commande une pizza imaginaire de manière épique et spectaculaire.',
      'Applaudis chaque phrase prononcée par les autres jusqu’à ce que ce soit ton tour.',
    ],
    ContentTone.mix: [
      'Fais un massage sensuel à l\'intérieur de la cuisse d\'une personne consentante pendant trente secondes.',
      'Chuchote à l\'oreille de la personne à ta droite ton fantasme le plus coquin.',
      'Embrasse le cou d\'une personne consentante et souffle délicatement sur sa peau.',
      'Demande à une personne consentante de choisir un vêtement que tu devras retirer.',
      'Simule un orgasme pendant quinze secondes, avec des sons et des gestes, devant tout le monde.',
      'Enlève trois vêtements (accessoires non compris) et reste ainsi jusqu\'à la fin du match.',
      'Lèche le lobe de l\'oreille de la personne à ta gauche (si elle est d\'accord).',
      'Enlève un accessoire ou une couche de vêtements de la manière la plus provocante et la plus lente possible.',
      'Fais-toi bander les yeux et devine qui sont trois personnes du groupe en ne leur embrassant que la main ou le bras.',
      'Recréez votre position préférée avec un coussin de manière extrêmement réaliste.',
      'Pose ta tête sur les genoux d\'une personne consentante et reste-y pendant trois rounds.',
      'Envoie une photo de toi nu(e) (ou une photo très provocante) à la personne de ton choix et montre la notification d\'envoi au groupe.',
      'Fais un lap dance de trente secondes à une personne consentante choisie par le groupe.',
      'Dansez un slow sensuel, corps contre corps, avec une personne consentante, pendant une minute.',
      'Suivez avec la langue le contour du cou de la personne à votre gauche (si elle est d\'accord).',
      'Tiens la main de la personne la plus séduisante de la pièce en la glissant sous son t-shirt (si elle est d\'accord).',
      'Regarde dans les yeux la personne que tu trouves la plus attirante pendant trente secondes tout en te mordant la lèvre.',
      'Montre au groupe l\'expression que tu as au moment de l\'orgasme : reste ainsi pendant cinq secondes.',
      'Embrasse lentement la poitrine ou l\'épaule d\'une personne consentante de ton choix.',
      'Imité le son que tu fais quand on te fait une fellation, avec le son.',
      'Récite ton répertoire de sexting à voix haute, d\'un ton extrêmement sérieux.',
      'Dis au groupe quel serait le message de séduction le plus osé que tu enverrais à la personne qui te plaît en ce moment.',
      'Décris à voix haute comment tu emmènerais au lit la personne assise à ta gauche, étape par étape.',
      'Apprends au groupe ton astuce préférée pour exciter quelqu\'un en moins d\'une minute.',
      'Décris étape par étape ta nuit idéale : des préliminaires au petit-déjeuner.',
      'Réalise une publicité de trente secondes dans laquelle tu te présentes en tant qu\'amant, en mettant en avant tes meilleurs atouts.',
      'Raconte ta meilleure nuit en donnant des détails sur les positions et les sensations.',
      'Décris ton baiser idéal et offre-le tout de suite à une personne consentante (si elle est d\'accord).',
      'Dis à voix haute la phrase la plus osée qu’on t’ait jamais chuchotée au lit.',
      'Chuchote « j\'ai envie de toi maintenant » de ta voix la plus sensuelle à l\'oreille de trois personnes différentes.',
      'Envoie un message coquin à la dernière personne avec qui tu as passé du temps et montre sa réponse.',
      'Imite la façon dont tu dragues quand tu es ivre et que tu ne cherches qu\'à conclure.',
      'Montre au ralenti comment tu utilises ta langue pendant un baiser : le groupe note ta technique.',
      'Envoie « Je pense à nous deux au lit » à un contact de ton choix dans le groupe.',
      'Lis à haute voix la conversation la plus osée que tu as sur ton téléphone, sans rien censurer.',
      'Montre la photo la plus osée que tu as prise ou reçue ces derniers mois.',
      'Montre au groupe ton historique de navigation en mode incognito des deux derniers jours.',
      'Écris « J\'ai envie de le faire avec toi » à la personne qui te plaît et montre-lui la capture d\'écran.',
      'Envoie un message vocal de séduction de dix secondes à un ex choisi par le groupe.',
      'Raconte-nous jusqu’où tu es allé dans l’endroit le plus fréquenté où tu aies jamais mis les pieds.',
      'Décris les trois choses qui t\'excitent le plus au lit, sans tourner autour du pot.',
      'Raconte-nous ton réveil le plus gênant après une nuit de sexe endiablé.',
      'Avoue-nous quel fétichisme tu n\'as pas encore osé essayer.',
      'Dis le nom de la personne présente ici avec laquelle tu aurais le plus de chances de finir au lit ce soir.',
      'Classe les personnes présentes en fonction uniquement de leurs capacités potentielles au lit.',
      'Attribuez à chaque personne présente une « note d\'attirance » comprise entre 1 et 10, en la regardant dans les yeux.',
      'Dis-nous quel couple de cette pièce ferait des étincelles au lit et pourquoi.',
      'Choisis la personne du groupe que tu aimerais voir nue en ce moment.',
      'Fais à une personne du groupe le compliment le plus osé qui te vienne à l\'esprit sur son physique.',
      'Propose un « jeu de rôle » rapide à la personne à ta droite et dis la première réplique.',
      'Traverse la pièce comme si tu étais dans un club de strip-tease, arrête-toi devant quelqu\'un et fais-lui signe.',
      'Laisse le groupe rédiger un message audacieux depuis ton téléphone et l\'envoyer à qui il veut.',
      'Enlève deux vêtements ou accessoires de ton choix, aussi lentement que possible, pendant que le groupe chante une chanson sexy.',
      'Donne une fessée bien sentie, avec son accord, à la personne choisie par le groupe.',
      'Reproduis pendant dix secondes les sons que tu émets au lit au moment du plaisir maximal.',
      'Embrasse lentement le cou d\'une personne consentante, en commençant par l\'oreille et en descendant.',
      'Mima, sans te déshabiller, imite ta position préférée pendant dix secondes, en y mettant tout ton cœur.',
      'Dis à voix haute le nom de la personne présente dans cette pièce que tu embrasserais tout de suite.',
      'Fais un massage d\'une minute dans le dos d\'une personne consentante, en glissant tes mains sous ses vêtements (si elle est d\'accord).',
      'Chuchote à l\'oreille de celle qui est à ta droite ce que tu lui ferais si vous étiez seules dans cette pièce.',
      'Échange trois regards intenses avec la personne que tu trouves la plus sexy, sans jamais rire.',
      'Décris dans les moindres détails les sous-vêtements que tu portes ce soir.',
      'Danse le reggaeton pendant une demi-minute en te frottant (avec son consentement) contre une personne du groupe.',
      'Fais-toi glisser un glaçon dans ton pantalon et tiens le coup une minute sans crier.',
      'Chuchote le nom de ton sextoy préféré à l\'oreille de quelqu\'un, comme s\'il s\'agissait d\'une prière.',
      'Décris comment tu te caresses quand tu es seul et que tu veux jouir rapidement.',
      'Explique la différence entre un baiser normal et un baiser « de lit », à l\'aide d\'exemples théoriques.',
      'Mime « Je suis en train d\'écrire à la fille qui me plaît pour l\'inviter chez moi », en passant par toutes les étapes de la panique et de la réussite.',
      'Montre-nous ta meilleure pose « j\'ai envie de baiser » et explique-nous ta stratégie.',
      'Raconte-nous le compliment le plus coquin que tu aies jamais reçu et qui te l\'a fait.',
      'Répète « j\'en veux plus » avec cinq intentions différentes : le groupe doit deviner la bonne.',
      'Fais le geste le plus érotique possible en n\'utilisant qu\'un glaçon.',
      'Apprends au groupe comment faire un suçon parfait sans laisser trop de traces.',
      'Découvre quel parfum te donne envie de déshabiller quelqu\'un sur-le-champ.',
      'Danse un slow de vingt secondes avec quelqu\'un de présent, en lui murmurant des mots coquins.',
      'Fais la même grimace que quand tu jouis : le groupe vote pour l\'intensité.',
      'Rédige un message de « bonjour après l\'amour » qui ferait craquer n\'importe qui.',
      'Choisis parmi les membres du groupe celui que tu aimerais avoir comme « partenaire de lit » pendant un mois entier.',
      'Mords délicatement l\'épaule d\'une personne consentante et laisse-la en redemander.',
      'Caressez du doigt le dos nu d\'une personne consentante, de la nuque jusqu\'à la taille.',
      'Fais glisser un glaçon le long du cou d\'une personne consentante avec ta bouche.',
      'Détache tes cheveux et laisse-les retomber sur une personne consentante tout en lui chuchotant quelque chose à l\'oreille.',
      'Elle mordille les doigts d\'une personne consentante, un par un, en la regardant dans les yeux.',
      'Danse en t\'accroupissant lentement devant une personne consentante choisie par le groupe.',
      'Effleure les lèvres de la personne la plus séduisante avec les tiennes, sans jamais l\'embrasser, pendant dix secondes.',
      'Demande à une personne consentante d\'écrire sur ton corps, avec un doigt, un mot grivois, puis devine de quel mot il s\'agit.',
      'Appuie ton front contre celui de la personne que tu trouves la plus sexy et respirez ensemble pendant vingt secondes.',
      'Caresse la nuque d\'une personne consentante tout en lui murmurant la phrase la plus sensuelle que tu connaisses.',
      'Embrasse le poignet de trois personnes différentes qui y consentent, en feignant à chaque fois de plus en plus de désir.',
      'Masse doucement les épaules de la personne à ta droite en lui chuchotant à quel point tu aimes sa peau.',
      'Passe ta langue sur le bord d\'un verre d\'un air provocateur tout en fixant la personne qui te plaît.',
      'Mords-toi la lèvre inférieure et garde le regard fixé sur la personne la plus séduisante pendant tout un round.',
      'Retirez lentement votre ceinture ou un lacet et utilisez-le pour attacher (avec le consentement de la personne) les poignets de quelqu\'un pendant une minute.',
      'Laissez une personne consentante vous guider la main où elle le souhaite, par-dessus vos vêtements, pendant dix secondes.',
      'Récite une réplique tirée d\'un film érotique avec la voix la plus rauque possible, devant tout le monde.',
      'Simule un baiser passionné avec le dos de ta main, de la manière la plus réaliste possible.',
      'Décris au groupe, en regardant une personne consentante, ce que tu ferais à ses lèvres si tu le pouvais.',
      'Chuchote un compte à rebours de cinq à un à l\'oreille de quelqu\'un, comme si quelque chose allait se passer.',
      'Elle frotte lentement sa joue contre celle d\'une personne consentante, comme le ferait un chat en chaleur.',
      'Mords l\'air près du cou d\'une personne consentante sans la toucher, pour lui donner des frissons.',
      'Dessinez un cœur avec la langue sur la paume ouverte d\'une personne consentante.',
      'Danse une demi-minute en ne bougeant que les hanches, de la manière la plus sensuelle possible, devant le groupe.',
      'Poser tes mains sur les hanches d\'une personne consentante et la guider dans un mouvement lent pendant vingt secondes.',
      'Demande à quelqu\'un qui est d\'accord de souffler sur ta nuque et réagis comme si ça te rendait fou.',
      'Chuchote « ferme les yeux » à une personne consentante et laisse-la deviner où tu vas l\'effleurer.',
      'Décris à voix haute ton réveil idéal aux côtés de la personne à ta droite.',
      'Fais semblant de déshabiller du regard la personne la plus séduisante de la pièce, en silence, pendant dix secondes.',
      'Il embrasse sur la joue une personne consentante, en s\'approchant dangereusement des lèvres.',
      'Montre comment tu embrasserais quelqu’un sous la pluie en utilisant le groupe comme public et un oreiller comme partenaire.',
      'Raconte-nous la fois où tu as le plus désiré quelqu’un sans pouvoir l’avoir.',
      'Passe une fraise (ou un doigt) sur les lèvres d\'une personne consentante et fais-lui goûter.',
      'Demandez à une personne consentante de tracer avec son doigt une ligne allant de votre cou à votre main, puis retenez votre souffle.',
      'Répète « viens ici » avec trois intonations différentes jusqu\'à ce que le groupe décide laquelle est la plus séduisante.',
      'Passe une audition pour le rôle principal d\'un film pour adultes en jouant la scène d\'ouverture, tout en restant habillé.',
      'Décris l\'endroit précis où tu aimerais être embrassé(e) en ce moment et laisse quelqu\'un essayer (avec ton consentement).',
      'Imitez avec vos mains la silhouette de la personne que vous trouvez la plus sexy tout en la regardant dans les yeux.',
      'Chuchote à l\'oreille de la personne à ta gauche à quel moment de la journée tu penses le plus au sexe.',
      'Demande gentiment à quelqu\'un qui est d\'accord de te mordre l\'oreille et ne ris pas pendant dix secondes.',
      'Dansez en vous appuyant de dos contre une personne consentante, en guidant ses mouvements avec vos hanches.',
      'Raconte-moi, en la regardant, ce qui t\'attire physiquement chez la personne à ta droite, détail par détail.',
      'Regarde dans les yeux une personne consentante tout en embrassant lentement le dos de sa main, en remontant vers son poignet.',
      'Fais mine d\'enlever ton maillot aussi lentement que possible, en t\'arrêtant à mi-chemin au milieu des protestations du groupe.',
      'Chuchote une promesse coquine à l\'oreille de la personne qui te plaît, comme s\'il s\'agissait d\'un secret d\'État.',
      'Décris la scène de séduction parfaite et attribue le rôle principal à un présent.',
      'Embrasse passionnément ton avant-bras en montrant au groupe exactement comment tu embrasses d\'habitude.',
      'Demande-lui de te verser (ou verse-toi) quelques gouttes d\'eau sur la nuque et laisse-les couler sans les essuyer pendant un round.',
      'Regarde une personne consentante et mime-lui avec tes lèvres, sans parler, les trois mots que tu aimerais lui dire au lit.',
      'Défile comme un mannequin sur un podium imaginaire en t\'arrêtant pour envoyer un baiser à la personne qui te plaît.',
      'Caresse doucement le bras de la personne à tes côtés tout en lui racontant ton dernier rêve érotique.',
      'Mets une chanson lente et invite à danser la personne qui te plaît le plus, corps contre corps.',
      'Demande-leur de fermer les yeux et identifie trois personnes consentantes uniquement à l\'odeur de leur peau.',
      'Chuchote « tu es tout ce que je veux ce soir » à la personne à ta droite, comme si tu le pensais vraiment.',
      'Décris ce que tu ferais à une personne consentante si vous n’aviez que cinq minutes dans une pièce fermée.',
      'Mords délicatement l\'épaule d\'un oreiller, comme si tu faisais un suçon à ton partenaire.',
      'Tiens le menton d\'une personne consentante et approche ton visage du sien, à un souffle de ses lèvres.',
      'Récite, à genoux, une déclaration pleine de désir à la personne la plus sexy de la pièce.',
      'Fais glisser lentement tes mains le long de tes hanches tout en regardant fixement la personne qui te plaît, comme dans un clip vidéo.',
      'Chuchotez à l\'oreille d\'une personne consentante votre moment préféré des préliminaires.',
      'Demande à une personne consentante de choisir une partie de son corps et fais-lui un compliment torride à ce sujet.',
      'Danse un tango improvisé avec une personne consentante, pour finir dans une posture à quelques centimètres de son visage.',
      'Décris comment tu séduirais quelqu\'un en utilisant uniquement ta voix, puis montre-le en parlant pendant dix secondes.',
      'Demande à quelqu\'un d\'écrire sur ta nuque, avec le doigt, le nom de la personne qui t\'attire, puis demande au groupe de deviner de qui il s\'agit.',
      'Raconte le rêve que tu aimerais réaliser avec l\'une des personnes présentes dans cette pièce.',
      'Montre au groupe comment tu te déplaces au-dessus d\'un partenaire, à l\'aide d\'un oreiller, pendant dix secondes.',
      'Chuchote à la personne la plus séduisante ce que tu remarques en premier chez elle chaque fois qu\'elle entre dans une pièce.',
      'Passe lentement un doigt sur tes lèvres tout en soutenant le regard de la personne que tu désires.',
      'Demande au groupe de te dicter trois mots coquins et utilise-les dans une phrase séduisante adressée à la personne qui te plaît.',
      'Embrasse lentement les jointures des doigts d\'une personne consentante, tout en levant les yeux vers elle.',
      'Décris l\'odeur corporelle que tu préfères chez un partenaire et sens (avec son accord) le cou de quelqu\'un pour vérifier.',
      'Demande à une personne consentante de te murmurer son fantasme à l\'oreille et réagis uniquement par le regard.',
    ],
    ContentTone.hot: [
      'Embrasse avec la langue la personne à ta droite, si elle est d\'accord.',
      'Demandez à une personne consentante de vous retirer un vêtement avec les dents.',
      'Imité ta position préférée sur une personne consentante pendant trente secondes.',
      'Décris à voix haute comment tu emmènerais au lit la personne qui se trouve en face de toi.',
      'Montre l\'expression que tu as quand tu atteins l\'orgasme.',
      'Lèche le cou de la personne à ta gauche jusqu\'à ce qu\'elle frissonne, si elle est d\'accord.',
      'Fais un suçon bien visible sur l\'épaule d\'une personne consentante.',
      'Assieds-toi à califourchon sur une personne consentante et reste dans cette position pendant tout un round.',
      'Simule un orgasme bruyant et réaliste pendant vingt secondes devant tout le monde.',
      'Chuchote à l\'oreille de la personne qui se trouve en face de toi la chose la plus coquine que tu lui ferais.',
      'Fais un lap dance d\'une minute à une personne consentante choisie par le groupe.',
      'Mordille le lobe de l\'oreille de la personne à ta droite, si elle est d\'accord.',
      'Fais passer un glaçon de ta bouche à celle d\'une personne consentante.',
      'Montre au groupe comment tu bouges tes hanches pendant l\'acte sexuel, en position debout.',
      'Il lèche une goutte de boisson sur le cou d\'une personne consentante.',
      'Enlève un vêtement et garde-le pendant les trois prochains rounds.',
      'Montre dans quelle position tu dors en t\'allongeant par terre.',
      'Embrasse la partie du corps de ton choix sur une personne consentante.',
      'Simule une fellation sur une banane ou un autre objet pendant quinze secondes.',
      'Dansez un slow en étreinte avec une personne consentante, les mains libres.',
      'Décris en détail la dernière fois où tu t\'es masturbé.',
      'Montre par des gestes à quel point ton ex le plus mémorable est doué ou douée.',
      'Pose ta main sur la cuisse d\'une personne consentante et laisse-la là pendant un round.',
      'Imite les sons que tu fais au lit quand tu es sur le point de jouir.',
      'Lèche le doigt d\'une personne consentante de la manière la plus provocante possible.',
      'Déshabille-toi jusqu\'à ne garder que tes sous-vêtements et échange ta place avec la personne en face de toi.',
      'Montre à quel point tu peux être sensuelle en retirant lentement tes chaussettes ou tes chaussures.',
      'Mords délicatement le cou d\'une personne consentante en y laissant une marque de dents.',
      'Montre, avec une main, le mouvement de la langue que tu ferais lors d\'un baiser à la française.',
      'Donne une fessée à une personne consentante, puis laisse-toi donner une fessée à ton tour.',
      'Décris le fantasme sexuel qui t\'excite le plus, sans aucune censure.',
      'Fais semblant de chevaucher quelqu\'un en restant assis sur une chaise pendant vingt secondes.',
      'Fais un massage sensuel du dos d\'une personne consentante pendant une minute.',
      'Montre comment embrasser passionnément en utilisant le dos de ta main.',
      'Dénude ton épaule et laisse une personne consentante t\'embrasser à cet endroit.',
      'Raconte à voix haute le rêve érotique le plus osé dont tu te souviennes.',
      'Imité la position du missionnaire dans les airs pendant dix secondes, en y mettant toute ton expression.',
      'Chuchote un gémissement à l\'oreille de la personne à ta droite, si elle y consent.',
      'Demandez à une personne consentante de vous attacher les poignets avec un foulard pendant un round.',
      'Décris ce qui t\'excite le plus dans le corps de la personne qui se trouve en face de toi.',
      'Montre-nous comment tu enlèverais ton soutien-gorge d\'une seule main, les yeux fermés.',
      'Lèche la crème ou le sucre sur le doigt d\'une personne consentante.',
      'Montrez votre plus beau gros plan d\'un regard séduisant, en le maintenant pendant dix secondes.',
      'Fais semblant de faire une fellation à un concombre avec le plus grand sérieux pendant quinze secondes.',
      'Laisse une personne consentante te souffler dans la nuque et réagis comme tu le ferais au lit.',
      'Décris-nous la fois où tu as eu l\'orgasme le plus intense de ta vie.',
      'Danse à la pole en utilisant une chaise comme barre pendant trente secondes.',
      'Approche tes lèvres à un centimètre de celles de la personne en face de toi, sans l\'embrasser, pendant dix secondes.',
      'Lance un gémissement qui va crescendo et se termine par un cri, comme un véritable point culminant.',
      'Passe ta langue sur ta lèvre supérieure en fixant du regard la personne qui t\'attire le plus ici.',
      'Enlève tes sous-vêtements par-dessous tes vêtements et montre-les au groupe.',
      'Laisse une personne consentante te mordre le cou pendant cinq secondes.',
      'Décris ton sextoy préféré et explique comment tu l\'utilises.',
      'Elle fait semblant de dévêtir du regard chaque personne présente, une par une.',
      'Exécute une danse du ventre lente et provocante pendant vingt secondes.',
      'Lèche lentement un doigt et mets-le dans ta bouche, tout en regardant la personne en face de toi.',
      'Chuchote à une personne consentante dans quelle position tu aimerais la voir.',
      'Pose ta tête sur les genoux d\'une personne consentante pendant tout un round.',
      'Montre comment tu bouges ta langue quand tu fais une fellation, sur un glaçon ou sur une cuillère.',
      'Demandez à une personne consentante de vous masser les cuisses pendant trente secondes.',
      'Décris la partie de ton corps qui te rend fou quand on la touche.',
      'Simulez un étreinte passionnée avec un oreiller pendant vingt secondes.',
      'Embrasse la main d\'une personne consentante en remontant jusqu\'au coude.',
      'Montre à quel point tu sais être effronté en mimant un strip-tease de dix secondes.',
      'Chuchote à l\'oreille des membres du groupe, l\'un après l\'autre, à quel point tu les trouves excitants.',
      'Demande-leur de te bander les yeux et devine qui, parmi les personnes consentantes, t\'embrasse sur la joue.',
      'Décris comment tu aimes qu\'on te touche pendant les préliminaires.',
      'Imité la position de la « pecorina » dans les airs pendant dix secondes, avec conviction.',
      'Il lèche le bord du verre d\'une manière obscène sous les regards de tout le monde.',
      'Fais un twerk endiablé de trente secondes devant le groupe.',
      'Pose la main d\'une personne consentante sur ta hanche et guide-la pendant que tu danses.',
      'Raconte la chose la plus audacieuse que tu aies faite au lit pour faire forte impression.',
      'Fais semblant d\'enrouler tes jambes autour de quelqu\'un en utilisant l\'air, tout en restant debout.',
      'Laisse une personne de ton choix te caresser la nuque et montre comment tu réagis.',
      'Décris en détail la relation sexuelle que tu aimerais avoir ce soir.',
      'Fais le regard le plus sensuel que tu puisses en regardant dans les yeux la personne qui t’attire.',
      'Embrasse le poignet d\'une personne consentante et remonte lentement avec tes lèvres.',
      'Montre comment tu cambrerais le dos au summum du plaisir.',
      'Chuchote trois mots coquins à l\'oreille de la personne à ta gauche, si elle est d\'accord.',
      'Laisse une personne consentante te mordre un doigt de manière provocante.',
      'Décris la partie du corps d\'une personne présente ici qui t\'impressionne le plus.',
      'Simule un orgasme progressif en effleurant uniquement ton cou et ton visage.',
      'Lance un regard séducteur et fais une moue aux lèvres à celui ou celle qui te plaît le plus.',
      'Enlève ton t-shirt ou défais les boutons, et reste comme ça pendant deux rounds, si tu te sens d\'attaque.',
      'Lèche le sel sur la main d\'une personne consentante avant de boire un « cicchetto ».',
      'Pose tes mains sur les hanches d\'une personne consentante et fais-la danser avec toi.',
      'Décris la chose la plus cochonne qu\'on t\'ait jamais chuchotée au lit.',
      'Fais semblant de lécher une partie très intime d\'un fruit pendant dix secondes.',
      'Laisse-toi enlacer par derrière par une personne consentante et reste ainsi pendant un round.',
      'Montre-nous comment tu bouges quand tu es au-dessus pendant l\'amour, sur une chaise.',
      'Chuchote à l\'oreille de la personne qui se trouve devant toi ton désir le plus interdit.',
      'Embrasse lentement le cou d\'une personne consentante en comptant jusqu\'à dix.',
      'Montre-nous ta gamme de gémissements à trois niveaux d\'intensité différents.',
      'Demande à une personne consentante de souffler doucement dans ton oreille et réagis.',
      'Décris comment tu t\'y prendrais avec la personne qui se trouve en face de toi, si tu le pouvais.',
      'Simule une danse de séduction en retirant lentement une ceinture ou un accessoire.',
      'Lèche le sucre sur les lèvres d\'une personne consentante, si elle est d\'accord.',
      'Fais ta meilleure imitation de la façon dont tu appelles quelqu\'un par son prénom au lit.',
      'Appuie ton front contre celui de la personne en face de toi et respire profondément pendant dix secondes.',
      'Décris le fantasme à trois que tu aimerais vivre et avec qui tu le vivrais.',
      'Imite un strip-tease complet sans te déshabiller, en trente secondes.',
      'Faites-vous gratter doucement le dos par une personne consentante, par-dessus vos vêtements.',
      'Déhanche-toi en entrant dans une pièce pour faire tourner la tête à tout le monde.',
      'Chuchote à l\'oreille d\'une personne consentante ce que tu lui ferais si nous étions seuls.',
      'Embrasse l\'intérieur du poignet de la personne en face de toi tout en la regardant droit dans les yeux.',
      'Décris le bruit qui t\'excite le plus pendant les rapports sexuels.',
      'Simule un rapport sexuel debout en t\'appuyant contre le mur pendant quinze secondes.',
      'Montre avec tes mains la taille du plus gros pénis que tu aies jamais vu.',
      'Lèche ton index et effleure tes lèvres en regardant la personne qui t\'attire le plus.',
      'Demande à quelqu\'un qui y consent de te tirer doucement les cheveux et montre comment tu réagis.',
      'Décris l\'endroit le plus farfelu où tu aimerais faire l\'amour.',
      'Imité la position du 69 avec un oreiller pendant dix secondes.',
      'Caresse sensuellement le visage d\'une personne consentante en descendant vers son cou.',
      'Chuchote une liste de trois choses que tu ferais à la personne qui se trouve devant toi ce soir.',
      'Montre comment tu danses collé à quelqu\'un en boîte de nuit, avec une personne consentante.',
      'Demande à une personne consentante de te faire un baiser en forme d\'empreinte dans le cou.',
      'Décris la chose la plus passionnante qui t\'ait arrivé dans un lieu public.',
      'Fais semblant de murmurer le nom de la personne la plus sexy de la pièce.',
      'Lèche lentement le dos de la main de la personne qui se trouve en face de toi.',
      'Montre-nous comment tu te déshabilles quand tu veux séduire quelqu\'un, tranquillement.',
      'Passe une main dans les cheveux d\'une personne consentante et approche ton visage.',
      'Décris ce que tu ferais avec tes lèvres à la personne qui t\'attire le plus dans cette pièce.',
      'Fais semblant d\'être menotté au lit pendant dix secondes, en prenant un air convaincant.',
      'Laisse une personne consentante te caresser le dos dénudé, si elle est d\'accord.',
      'Lâche un gémissement étouffé, comme si tu te retenais dans un lieu public.',
      'Chuchote à l\'oreille de la personne à ta droite quel est ton fétiche, si elle y consent.',
      'Embrasse le cou d\'un oreiller comme s\'il s\'agissait de la personne que tu désires le plus.',
      'Décris la chose la plus folle que tu aimerais faire au moins une fois.',
      'Fais semblant de recevoir une fessée en réagissant par un gémissement, pendant dix secondes.',
      'Lèche lentement une sucette ou une glace sur bâtonnet en regardant fixement la personne qui te plaît.',
      'Montre-nous comment tu te cambres quand quelqu\'un t\'embrasse au bon endroit.',
      'Pose tes lèvres sur l\'épaule d\'une personne consentante et remonte jusqu\'à son oreille.',
      'Décris les préliminaires qui ne te lassent jamais et te font planer.',
      'Simule un rapport passionné contre une porte pendant quinze secondes.',
      'Laisse une personne consentante te mordre doucement la lèvre inférieure.',
      'Prends un air des plus provocants tout en passant tes mains sur ton corps.',
      'Chuchote à la personne en face de toi à quel point tu la désires, en utilisant des mots explicites.',
      'Embrasse sensuellement, un par un, les doigts d\'une personne consentante.',
      'Décris la position dans laquelle tu atteins le plus facilement l\'orgasme.',
      'Simule une danse érotique en te frottant lentement contre une chaise.',
      'Lèche une goutte imaginaire sur la poitrine ou le cou de la personne en face de toi, si elle est d\'accord.',
      'Montre-moi comment tu te déhanches sous les draps quand tu fais l\'amour.',
      'Pose ta main sur le cœur d\'une personne consentante et descends doucement vers son abdomen.',
      'Décris l\'orgasme le plus long que tu aies jamais eu et comment cela s\'est passé.',
      'Fais semblant de sucer un doigt de manière obscène pendant dix secondes en regardant le groupe.',
      'Laisse-toi serrer fort par une personne consentante et laisse-lui échapper un gémissement.',
      'Prends un air de « moment fort » tout en cambrant le dos, pendant cinq secondes.',
      'Chuchote à l\'oreille de chacun ce que tu aimerais lui faire, tout au long du parcours.',
      'Montre-nous comment tu réagis quand on te mordille le cou, avec ta voix et tes frissons.',
      'Imitez votre moment de plaisir le plus intense, avec votre voix et vos mouvements, pendant dix secondes.',
    ],
  };

  static const Map<String, List<String>> verita = {
    ContentTone.normal: [
      'Quelle est la chose la plus gênante que tu aies faite en public ?',
      'Quel est le plus gros mensonge que tu aies raconté quand tu étais enfant ?',
      'Quel est ton « plaisir coupable » musical ?',
      'Quel film t\'a le plus fait pleurer ?',
      'Quelle est la chose la plus stupide pour laquelle tu t\'es disputé ?',
      'Selon toi, quel est ton pire défaut ?',
      'Quel défaut tes amis te reprochent-ils et que tu ne reconnais absolument pas ?',
      'Quelle est la chose la plus chère que tu aies cassée ?',
      'T\'es-tu déjà fait passer pour malade pour éviter quelque chose ?',
      'Quelle est l\'excuse que tu utilises le plus souvent ?',
      'Que fais-tu quand tu es seul et que personne ne te voit ?',
      'Quelle est ta manie la plus bizarre ?',
      'Combien de temps passes-tu réellement sur ton téléphone chaque jour ?',
      'Quelle est l\'application que tu ouvres le plus souvent sans raison particulière ?',
      'Quelle a été ta dernière recherche sur Internet, la vraie ?',
      'Quelle est la plus vieille photo que tu as dans ton téléphone ?',
      'Qui est la dernière personne à qui tu as écrit ?',
      'Quel est le message le plus gênant que tu aies envoyé ?',
      'T\'est-il déjà arrivé d\'envoyer un message à la mauvaise personne ? Que disait-il ?',
      'Quelle est la plus belle chose que quelqu\'un t\'ait dite ?',
      'Quel est le compliment le plus étrange que tu aies jamais reçu ?',
      'Qui est la personne la plus importante dans ta vie ?',
      'Qui appellerais-tu si tu avais un gros problème à trois heures du matin ?',
      'Qu\'est-ce que tu apprécies le plus chez un ami ?',
      'Quel a été le plus beau moment de cette année ?',
      'Quel a été le moment le plus difficile de cette année ?',
      'Qu\'est-ce qui t\'inquiète le plus pour l\'avenir ?',
      'Quel est ton rêve que tu n\'as encore révélé à personne ?',
      'Que ferais-tu si, demain, tu ne devais plus travailler ?',
      'Si tu pouvais changer une décision, laquelle serait-ce ?',
      'De quoi es-tu le plus fier ?',
      'Quel compliment aimerais-tu recevoir ?',
      'Qu\'est-ce qui te met de bonne humeur en cinq minutes ?',
      'Qu\'est-ce qui te met le plus vite en colère ?',
      'Quelle est cette manie dont tu n\'arrives pas à te débarrasser ?',
      'Es-tu plus ordonné ou plus désordonné que tu ne veux bien l\'admettre ?',
      'À quand remonte la dernière fois où tu as ri aux larmes ?',
      'Quelle est la chose la plus courageuse que tu aies faite ?',
      'Qu\'est-ce que tu ne ferais jamais pour de l\'argent ?',
      'Pour quelle somme serais-tu prêt à te faire raser la tête ?',
      'Quel est ton talent caché ?',
      'Quelle est la chose que tout le monde sait faire, sauf toi ?',
      'Quelle est la chose la plus difficile que tu aies apprise ?',
      'Sur une échelle de 1 à 10, quelle note donnerais-tu à ta vie en ce moment ?',
      'Que te manque-t-il pour obtenir un 10 sur 10 ?',
      'Quel est le plus bel endroit où tu sois allé ?',
      'Où aimerais-tu vivre si tu avais le choix ?',
      'Quel voyage referais-tu dès demain ?',
      'Quelles sont les pires vacances que tu aies jamais passées ?',
      'As-tu déjà raté un avion ou un train ? Comment ça s\'est terminé ?',
      'Quelle est la chose la plus bizarre que tu aies mangée ?',
      'Quel est le plat que tu sais le mieux cuisiner ?',
      'Quel est ton plat réconfortant ?',
      'Serais-tu prêt à manger le même plat pendant un mois pour mille euros ?',
      'Quelle est la chose la plus inutile que tu aies achetée ?',
      'Combien de temps te faut-il vraiment pour te préparer ?',
      'Quelle est la robe que tu ne jettes pas, même si tu devrais ?',
      'Quelle tendance as-tu suivie et que tu rejettes aujourd\'hui ?',
      'Quelle coupe de cheveux regrettes-tu ?',
      'Tu te ferais tatouer ? Où et quoi ?',
      'Quelle est la chose que tu as faite uniquement pour faire plaisir à quelqu’un d’autre ?',
      'T\'es-tu déjà fait passer pour quelqu\'un qui avait compris quelque chose pour ne pas te ridiculiser ?',
      'Sur quel sujet bluffes-tu le plus ?',
      'Quel est le livre que tu dis avoir lu mais que tu n\'as pas terminé ?',
      'Quelle série as-tu abandonnée en cours de route ?',
      'Quel personnage te ressemble le plus ?',
      'Si tu étais un animal, lequel serais-tu et pourquoi ?',
      'Si tu devais changer de nom, lequel choisirais-tu ?',
      'Quel est le surnom que tu détestais quand tu étais petit ?',
      'Quelle est la chose la plus ennuyeuse que tu aies jamais faite dans le cadre de ton travail ?',
      'Quel est le collègue ou le camarade de classe que tu ne supportais pas, et pourquoi ?',
      'Quelle est la chose que tu repousses depuis le plus longtemps ?',
      'À quelle heure vas-tu vraiment te coucher ?',
      'Combien de fois éteins-tu ton réveil avant de te lever ?',
      'Quel est ton endroit préféré chez toi ?',
      'Que prendrais-tu avec toi si tu devais fuir de chez toi en une minute ?',
      'Quel est l\'objet auquel tu es le plus attaché ?',
      'Quel est le plus beau cadeau que tu aies reçu ?',
      'Quel est le pire cadeau que tu aies jamais reçu ?',
      'As-tu déjà recyclé un cadeau ?',
      'Quelle est la bonne résolution de début d\'année que tu n\'as jamais tenue ?',
      'Quelle habitude aimerais-tu abandonner ?',
      'Quelle habitude aimerais-tu prendre ?',
      'Qui, parmi le groupe, appellerais-tu pour demander un conseil sérieux ?',
      'Qui, dans le groupe, te fait le plus rire ?',
      'Qu\'as-tu appris des personnes présentes ce soir ?',
      'Qu\'aimerais-tu que le groupe sache à ton sujet ?',
      'Quelle est la question que tu espérais ne pas entendre ce soir ?',
      'Y a-t-il quelque chose que tu as toujours voulu demander à quelqu\'un ici ?',
      'Si je devais décrire cette soirée en un mot, lequel choisirais-tu ?',
      'Quelle est la situation la plus gênante que tu aies vécue à l\'école ?',
      'Quel est le rêve le plus absurde dont tu te souviennes ?',
      'Quel est le petit mensonge que tu dis le plus souvent ?',
      'Quel plat fais-tu semblant d\'apprécier par simple politesse ?',
      'Si tu avais un super-pouvoir pendant une journée, que ferais-tu en premier ?',
      'Quelle personnalité aimerais-tu inviter à dîner et que lui demanderais-tu ?',
      'Quelle est la chose la plus drôle qui se soit produite lors d\'une de tes réunions de famille ?',
      'Si tu pouvais échanger ta vie avec celle de quelqu\'un d\'autre pendant une journée, qui choisirais-tu ?',
      'Quelle est la chanson dont tu chantes toujours les paroles de travers ?',
      'Quelle est la chose la plus bizarre que tu aies faite par ennui ?',
      'T\'est-il déjà arrivé de ne pas pouvoir t\'empêcher de rire à un moment où c\'était strictement interdit ? Raconte-nous.',
      'Quelle est la gaffe qui te fait rire aujourd\'hui, mais qui t\'a anéanti sur le moment ?',
      'Quel est l\'objet le plus étrange que tu gardes dans ta chambre ?',
      'Quelle est la chose la plus enfantine que tu fais encore aujourd\'hui ?',
      'Si ta vie était un film, quel acteur jouerait ton rôle ?',
      'Quelle a été ta pire « idée géniale » ?',
      'T\'es-tu déjà mis à chanter devant le miroir en utilisant ta brosse à cheveux comme micro ?',
      'Quel est le mot que tu as toujours du mal à prononcer ?',
      'Quel est ton record le plus fou, peu importe ce qui compte comme record ?',
      'Que ferais-tu en premier si tu gagnais un million demain matin ?',
      'Quelle est l\'application la plus inutile que tu aies téléchargée et que tu n\'aies jamais utilisée ?',
      'T\'es-tu déjà endormi dans un endroit bizarre ? Où ça ?',
      'Quelle est la chose que tu cherches sur Internet parce que tu as honte de ne pas la savoir ?',
      'Quel est le plat que tu as le plus spectaculairement raté ?',
      'Quelle est la règle chez toi que tu trouvais normale, mais qui était en fait très bizarre ?',
      'Quel personnage de dessin animé te faisait peur quand tu étais enfant ?',
      'Quelle est la chose la plus absurde à laquelle tu croyais quand tu étais enfant ?',
      'T\'est-il déjà arrivé de répondre au salut de quelqu\'un qui saluait une autre personne ?',
      'Quelle est la notification qui te stresse le plus ?',
      'Quelle est la chanson qui te rappelle toujours des souvenirs ?',
      'Si tu pouvais te téléporter n\'importe où pendant une journée, où irais-tu ?',
      'Quel métier rêvais-tu d\'exercer quand tu étais enfant ?',
      'Qu\'est-ce que tout le monde adore et que tu n\'aimes vraiment pas ?',
      'Quelle émission trash regardes-tu et défendrais-tu bec et ongles ?',
      'T\'est-il déjà arrivé de parler à ton animal ou à tes plantes comme s\'ils comprenaient tout ?',
      'Quelle est la chose que tu sais le moins bien faire, mais que tu continues à faire avec enthousiasme ?',
      'Quel est le plus beau message que tu gardes dans ton téléphone ?',
      'Quelle est cette théorie farfelue à laquelle tu crois un peu, même si tu sais qu\'elle est absurde ?',
      'Quel est ton plan de survie en cas d\'apocalypse zombie ?',
      'Préférerais-tu pouvoir voler ou lire dans les pensées, et pourquoi ?',
      'Quelle est l\'excuse la plus originale que tu aies jamais utilisée pour justifier un retard ?',
      'Qu\'est-ce que tu faisais quand tu étais enfant et que tu aimerais que ce soit socialement acceptable aujourd\'hui encore ?',
      'À ton avis, qui, parmi les membres du groupe, survivrait le plus longtemps sur une île déserte ?',
      'Quel est le mot italien que tu trouves le plus drôle ?',
      'Quel est le son ou le bruit que tu ne supportes vraiment pas ?',
      'Quelle est la chose la plus gentille que tu aies faite en secret pour quelqu\'un ?',
      'As-tu déjà gagné quelque chose lors d\'un concours ou d\'une tombola ? Quoi ?',
      'Selon toi, quel parfum de glace devrait être interdit par la loi ?',
      'Quel est le film que tout le monde adore et que tu n\'as jamais réussi à regarder jusqu\'au bout ?',
      'Quel est l\'aliment que tu fais semblant de ne pas aimer, mais que tu mangerais en cachette ?',
      'Quelle est la chanson que tu chantes uniquement quand tu es sûr que personne ne t\'entend ?',
      'Quelle est la chose la plus absurde que tu fais quand tu es sûr que personne ne te regarde ?',
      'Quel est ton talent le plus inutile ?',
      'Quelle est la peur la plus irrationnelle que tu aies ?',
      'Quel est le pire cadeau que tu aies jamais réutilisé ?',
      'Qu\'y a-t-il de plus gênant dans ton historique YouTube ?',
      'Quelle est l\'excuse que tu utilises le plus souvent pour quitter une fête ?',
      'Quel dessin animé regarderais-tu encore aujourd\'hui sans honte ?',
      'Si tu pouvais échanger ton travail contre celui de l\'une des personnes présentes pendant une journée, qui choisirais-tu ?',
      'Quel est le compliment qui te fait le plus plaisir ?',
    ],
    ContentTone.mix: [
      'Comment s\'est passée ta première fois ? Âge, lieu, position et note de 1 à 10.',
      'Avec combien de personnes as-tu couché ? Donne le nombre exact, sans arrondir.',
      'Quel est l\'endroit le plus absurde ou le plus risqué où tu l\'as fait ?',
      'As-tu déjà pratiqué le sexe anal ? Ça t\'a plu ? Sois honnête.',
      'As-tu déjà couché avec quelqu\'un le jour même où tu l\'as rencontré ? Combien de fois ?',
      'Quelle a été ta aventure d\'un soir la plus folle et où ça s\'est passé ?',
      'Tu as déjà couché avec un ami et fait comme si de rien n\'était ? C\'était qui ?',
      'As-tu déjà pratiqué le sexting avec plus de trois personnes en même temps ?',
      'Quel est le message le plus vulgaire que tu aies jamais envoyé ou reçu ? Cite-le.',
      'As-tu déjà envoyé ou reçu une vidéo à caractère sexuel de toi-même ? Le referais-tu ?',
      'As-tu déjà reçu une photo osée sans l\'avoir demandée ? Quelle a été ta véritable réaction ?',
      'Quel est ton fantasme érotique le plus extrême que tu n\'as jamais révélé à personne ?',
      'As-tu déjà participé à un plan à trois ? Si ce n\'est pas le cas, avec qui, parmi ce groupe, aimerais-tu le faire ?',
      'Y a-t-il une personne dans cette pièce avec laquelle tu passerais volontiers la nuit ? Un nom.',
      'Préférerais-tu un orgasme incroyable de trois minutes ou une heure de câlins parfaits ?',
      'Qui a été le meilleur amant de ta vie et pourquoi ? Qu\'est-ce qu\'il avait de spécial ?',
      'As-tu déjà embrassé deux personnes différentes au cours de la même heure ? Où étiez-vous ?',
      'T\'est-il déjà arrivé de regretter amèrement d\'avoir couché avec quelqu\'un au moment même où tu le faisais ?',
      'T\'es-tu déjà réveillé à côté de quelqu\'un et t\'es-tu enfui par la fenêtre ou en cachette ?',
      'Qu\'est-ce qui compte le plus au lit : la technique, la taille ou la complicité mentale ?',
      'Au lit, es-tu plutôt dominant ou soumis ? Donne un exemple de ce que tu aimes faire.',
      'Lumières allumées, miroirs et vidéos, ou obscurité totale ? Justifie ton choix.',
      'Quel est le compliment le plus excitant qu\'on t\'ait fait pendant un rapport sexuel ?',
      'As-tu déjà simulé un orgasme pour que le rapport se termine plus vite ? Combien de fois ?',
      'Quelle est la situation la plus gênante qui t\'ait jamais arrivée pendant que tu le faisais ?',
      'T\'es-tu déjà fait surprendre par tes parents ou par un inconnu alors que tu étais en pleine action ?',
      'As-tu déjà fait semblant de dormir pour éviter de le faire ? Parce que tu n\'en avais pas envie ?',
      'As-tu déjà menti sur tes performances pour impressionner tes amis ?',
      'Quelle a été ta plus longue séance de sexe ? Combien de fois par jour ?',
      'Y a-t-il quelqu’un dans ce groupe qui t’ait déjà excité rien qu’en parlant ?',
      'Qu\'est-ce qui t\'attire en premier chez une personne et qui te fait te dire « j\'ai envie de coucher avec elle » ?',
      'Quel est le vêtement que tu trouves le plus sexy de tous ? Et celui qui te rebute le plus ?',
      'Tu te considères comme doué au lit ? Quel est ton atout incontournable ?',
      'Qu\'est-ce que tu aimerais apprendre à mieux faire au lit ? As-tu déjà regardé des tutoriels ?',
      'Quelle est la phrase de drague la plus effrontée que tu aies utilisée et qui a marché ?',
      'As-tu déjà flirté avec le partenaire d\'un ami proche ? Jusqu\'où es-tu allé ?',
      'As-tu déjà donné un faux numéro à quelqu\'un après l\'avoir embrassé ? Pourquoi ?',
      'Quelle est la chose la plus audacieuse que tu aies faite dans un lieu public bondé ?',
      'As-tu déjà eu une aventure estivale qui s\'est terminée par une vidéo ou une photo osée ?',
      'Quelle a été la plus grande différence d\'âge que tu aies eue dans une relation sexuelle ?',
      'As-tu déjà embrassé quelqu\'un dans cette pièce à l\'insu des autres ?',
      'Lequel d\'entre nous embrasserais-tu tout de suite si la lumière s\'éteignait pendant une minute ?',
      'À ton avis, lequel d\'entre nous est le plus « sauvage » au lit, en le regardant comme ça ?',
      'As-tu déjà utilisé une appli de rencontres uniquement pour des relations sexuelles sans lendemain ? Combien de matchs ont abouti à un coup d\'un soir ?',
      'Quelle est la conversation la plus compromettante que tu as actuellement sur ton téléphone ?',
      'T\'est-il déjà arrivé d\'écrire à un ex à trois heures du matin juste parce que t\'en avais envie ?',
      'Qu\'est-ce qui te manque le plus au lit de ton dernier partenaire ?',
      'As-tu déjà eu une liaison secrète avec une personne en couple ? Comment ça s\'est terminé ?',
      'As-tu déjà été « l\'autre » en toute conscience ? T\'es-tu senti coupable ?',
      'Quel est ton « kink » le plus bizarre ou le plus inavouable ?',
      'Au-dessus ou en dessous ? Devant ou derrière ? Réponds vite, sans réfléchir.',
      'As-tu déjà ressenti de la douleur au lit et découvert que ça te plaisait ?',
      'As-tu déjà eu des relations sexuelles dans un bureau ou sur ton lieu de travail ?',
      'T\'es-tu déjà caressé en pensant à quelqu\'un qui se trouve dans cette pièce ?',
      'Quelle partie de ton corps reçoit le plus de compliments au lit ?',
      'As-tu déjà fait un strip-tease pour quelqu\'un ? Comment ça s\'est passé ?',
      'Quelle est la phrase la plus cochonne que tu aies jamais dite à quelqu\'un pendant que vous le faisiez ?',
      'Si tu pouvais choisir une personne célèbre pour une nuit de sexe sans lendemain, qui serait-ce ?',
      'As-tu déjà fait l\'amour dans la mer, dans une piscine ou dans un jacuzzi public ?',
      'À quel moment de la journée te sens-tu généralement le plus excité ?',
      'Que portes-tu généralement pour dormir quand tu es avec quelqu’un que tu veux taquiner ?',
      'As-tu déjà fait l\'amour en gardant tes chaussettes ? Le groupe te jugera si tu réponds oui.',
      'Quelle est la position que tu trouves la plus fatigante, mais qui te procure le plus de plaisir ?',
      'As-tu déjà essayé le sexe tantrique ou des séances très longues ? Raconte-nous.',
      'As-tu déjà utilisé de la nourriture ou de la glace pendant les préliminaires ? Comment ça s\'est passé ?',
      'Quel est le signe qui ne laisse aucun doute lorsque tu veux le faire tout de suite ?',
      'Si tu le pouvais, qui d\'entre nous emmènerais-tu dans une pièce à l\'écart en ce moment ?',
      'Quelle est la première chose qui te fait comprendre qu\'une personne t\'aime vraiment ?',
      'As-tu déjà embrassé quelqu\'un du même sexe que toi ? Ça t\'a plu ou ça t\'a simplement intrigué ?',
      'Quel est le geste en apparence anodin qui t\'excite plus que tout autre ?',
      'Préfères-tu séduire ou te faire séduire ? Donne un exemple concret de ta dernière conquête.',
      'Quelle est la chose la plus audacieuse que tu aies demandée au lit, et comment cela a-t-il été accueilli ?',
      'As-tu déjà fait un rêve érotique mettant en scène une personne présente dans cette pièce ?',
      'Quelle partie du corps de ton partenaire te fait complètement perdre la tête ?',
      'À tes yeux, combien de temps dure une nuit parfaite et combien de fois aimerais-tu vivre ça ?',
      'As-tu déjà utilisé un sextoy en couple ? Si ce n\'est pas le cas, ça te dirait d\'essayer ?',
      'Quel est le plus gros mensonge que tu aies jamais raconté pour coucher avec quelqu\'un ?',
      'As-tu déjà eu le béguin en secret pour un ami de ton partenaire ?',
      'Quel est l\'endroit de ta maison où tu préfères le faire, à part dans ton lit ?',
      'As-tu déjà couché avec quelqu\'un dès le premier rendez-vous ? L\'as-tu regretté ou l\'as-tu refait ?',
      'Quelle est la phrase qui te fait tomber sous le charme de quelqu\'un en un clin d\'œil ?',
      'Tu préfères un massage érotique très lent ou passer directement aux choses sérieuses ?',
      'Quelle est la tenue la plus osée que tu aies portée pour faire craquer quelqu’un ?',
      'T\'est-il déjà arrivé d\'espionner ou d\'entendre par hasard deux personnes en train de le faire ? Raconte-nous.',
      'Quelle est la durée record de tes préliminaires, et aimerais-tu qu\'ils durent plus ou moins longtemps ?',
      'Si tu devais décrire ton style au lit en un seul mot, quel serait-il ?',
      'As-tu déjà eu un rendez-vous secret dans des toilettes publiques ou dans une voiture ?',
      'À quelle occasion as-tu désiré quelqu’un que tu ne pouvais pas avoir ?',
      'T\'es-tu déjà tombé amoureux de quelqu\'un simplement à cause de sa façon d\'embrasser ?',
      'Quelle est la chose que personne n\'imaginerait jamais à ton sujet au lit ?',
      'T\'es-tu déjà trompé de destinataire en envoyant un message coquin ? Comment ça s\'est terminé ?',
      'Selon toi, qui, dans cette pièce, est le plus doué pour flirter sans se faire remarquer ?',
      'Quelle est ta limite absolue au lit, la chose que tu ne ferais jamais ?',
      'As-tu déjà embrassé quelqu\'un juste pour rendre une autre personne jalouse ?',
      'Quelle partie de ton corps aimerais-tu que quelqu\'un embrasse plus souvent ?',
      'As-tu déjà eu une relation basée uniquement sur le sexe ? Combien de temps a-t-elle duré ?',
      'Quel fantasme partages-tu avec ton partenaire mais que tu n\'as jamais réalisé ?',
      'Qu\'est-ce qui t\'excite le plus : la voix, le regard ou les mains d\'une personne ?',
      'T\'es-tu déjà fait passer pour quelqu\'un qui n\'était pas intéressé par une personne qui te plaisait pourtant énormément ?',
      'Quelle a été la plus longue histoire d\'amour avant de finir enfin au lit avec quelqu\'un ?',
      'As-tu déjà fait l\'amour en écoutant une chanson en particulier ? Laquelle ?',
      'Quel est le compliment physique qui te fait te sentir immédiatement désirable ?',
      'As-tu déjà eu un coup de foudre purement physique ? Avec qui et comment ça s\'est passé ?',
      'Préfères-tu les baisers lents et profonds ou les baisers fougueux et frénétiques ?',
      'Quelle est la chose la plus osée qu\'on t\'ait chuchotée pendant que vous le faisiez ?',
      'T\'est-il déjà arrivé d\'avoir des sentiments pour deux personnes en même temps ? Comment as-tu géré cette situation ?',
      'Quel est le parfum, le tien ou celui de quelqu’un d’autre, que tu associes à la meilleure relation sexuelle que tu aies eue ?',
      'As-tu déjà flirté sans vergogne avec quelqu\'un devant ton partenaire ?',
      'Quelle est la position que tu aimerais essayer mais que tu n\'as jamais osé proposer ?',
      'As-tu déjà vécu une expérience à plus de deux ? Si ce n\'est pas le cas, le ferais-tu, et avec qui ici ?',
      'Qu\'est-ce qui te fait passer l\'envie d\'un coup alors que tu es sur le point de le faire ?',
      'Quelle est la chose la plus sexy qu\'une personne puisse faire tout habillée ?',
      'As-tu déjà eu une aventure avec quelqu\'un de beaucoup plus âgé ou plus jeune que toi ?',
      'Quel est ton signal secret pour faire comprendre à quelqu\'un que tu as envie de lui, ce soir ?',
      'T\'est-il déjà arrivé d\'être excité à un moment totalement inapproprié ? Où étais-tu ?',
      'Selon ceux qui ont été avec toi, qu\'est-ce qui fait de toi un amant inoubliable ?',
      'T\'est-il déjà arrivé de continuer à penser à un ex alors que tu étais au lit avec quelqu\'un d\'autre ?',
      'Quel est le mot le plus coquin que tu aimes qu\'on te murmure à l\'oreille ?',
      'As-tu déjà embrassé quelqu\'un sous l\'effet de l\'adrénaline, par exemple après avoir frôlé le danger ?',
      'Préfères-tu les rapports sexuels planifiés et soignés ou ceux qui sont spontanés et passionnés ?',
      'À quelle occasion as-tu le plus risqué d’être pris sur le fait ?',
      'As-tu déjà écrit ou reçu une lettre ou un message érotique que tu conserves encore aujourd\'hui ?',
      'Qui, dans cette pièce, embrasserais-tu, qui emmènerais-tu au lit et qui éviterais-tu ? Sois honnête.',
      'Quelle est ta pensée la plus coquine quand tu vois quelqu’un qui te plaît énormément ?',
      'As-tu déjà vécu une aventure pendant tes vacances dont tu n\'as jamais parlé à personne ?',
      'Quel jeu de rôle aimerais-tu essayer au moins une fois dans ta vie ?',
      'T\'es-tu déjà réveillé excité à côté d\'un ami ? Qu\'as-tu fait ?',
      'Quelle est la chose la plus gênante que tu aies recherchée sur Internet à propos du sexe ?',
      'As-tu déjà eu peur de décevoir quelqu’un au lit ? Comment ça s’est passé, au final ?',
      'À quel moment t\'es-tu senti le plus désiré de toute ta vie ?',
      'Préfères-tu faire l\'amour dans le noir ou regarder ton partenaire droit dans les yeux ?',
      'As-tu déjà embrassé plus d\'une personne au cours d\'une même soirée ? Combien ?',
      'Quelle est la chose la plus folle que tu ferais pour passer une nuit avec la personne que tu désires ?',
      'T\'est-il déjà arrivé de devoir retenir tes gémissements pour ne pas te faire entendre ? Où ça ?',
      'Quelle est ta zone érogène secrète que peu de gens ont découverte ?',
      'T\'est-il déjà arrivé de faire le premier pas, sans hésiter, avec quelqu\'un que tu venais tout juste de rencontrer ?',
      'Qu\'est-ce qui te donne le plus confiance en toi quand tu es nu ?',
      'As-tu déjà vécu une relation à distance qui ne reposait que sur des appels vidéo coquins ?',
      'Quel est le souvenir érotique qui te revient le plus souvent à l\'esprit quand tu es seul ?',
      'Si le partenaire de tes rêves ne te demandait qu\'une seule chose au lit, qu\'est-ce que tu aimerais que ce soit ?',
      'As-tu déjà eu des rapports sexuels pour faire la paix après une dispute violente ? Était-ce mieux ?',
      'Avec quelle personne as-tu eu la plus grande complicité au lit, et pourquoi ?',
      'As-tu déjà essayé de résister à une tentation avant de céder lamentablement ? Avec qui ?',
      'Quelle est la partie du corps de ton partenaire idéal que tu regardes en premier ?',
      'Qu\'est-ce qui t\'excite le plus : être regardé ou regarder pendant que tu le fais ?',
      'As-tu déjà conclu un accord de « amis avec avantages » qui a mal tourné ? Raconte-nous.',
      'Quelle est la chose la plus romantique et la plus coquine que tu aimerais faire au cours d\'une même nuit ?',
      'Selon toi, qui, dans cette pièce, essaie de te draguer en ce moment ?',
      'Quelle est la question la plus intime que tu aimerais poser à une personne présente ce soir ?',
      'Quelle est la chose qui te donnerait le plus envie de faire en ce moment même, si le jeu le permettait ?',
    ],
    ContentTone.hot: [
      'As-tu déjà attaché quelqu\'un ou t\'es-tu déjà laissé attacher pendant un rapport sexuel ?',
      'As-tu déjà goûté le sperme ou l\'éjaculation de ton partenaire ?',
      'Ça te dirait de faire un plan à trois ? Avec qui parmi les personnes présentes ?',
      'Quel est l\'endroit le plus risqué où tu l\'as fait ?',
      'En moyenne, combien de fois par jour te masturbes-tu ?',
      'Quelle est la position sexuelle qui te permet d\'atteindre l\'orgasme le plus rapidement ?',
      'As-tu déjà simulé un orgasme ? Avec combien de personnes ?',
      'Quelle est la chose la plus coquine qu\'on t\'ait chuchotée au lit ?',
      'As-tu déjà pratiqué le sexe oral dans un lieu public ?',
      'Avec qui, parmi les personnes présentes, coucherais-tu sans hésiter ?',
      'Quel est ton sextoy préféré et à quelle fréquence l\'utilises-tu ?',
      'As-tu déjà eu un orgasme uniquement grâce au sexe oral ?',
      'Qu\'est-ce qui t\'excite le plus : pratiquer ou recevoir une fellation ?',
      'As-tu déjà envoyé une vidéo intime à quelqu\'un ?',
      'Quel est le fantasme sexuel que tu n\'as jamais avoué à personne ?',
      'As-tu déjà eu des relations sexuelles avec plusieurs personnes au cours d\'une même nuit ?',
      'Quelle partie de ton corps te fait perdre la tête quand on la touche ?',
      'As-tu déjà essayé le bondage ou est-ce que cette idée t\'excite ?',
      'Combien de temps a duré ton rapport sexuel le plus long ?',
      'As-tu déjà couché avec quelqu\'un dès le premier rendez-vous ?',
      'Quelle est la chose la plus coquine que tu aies faite au lit ?',
      'As-tu déjà embrassé une personne du même sexe que toi ?',
      'T\'es-tu déjà masturbé en pensant à l\'une des personnes présentes ?',
      'Combien de partenaires as-tu eus jusqu\'à présent ?',
      'As-tu déjà eu un rapport anal ? Ça t\'a plu ?',
      'Quelle est ta zone érogène la plus secrète ?',
      'As-tu déjà utilisé des menottes ou des moyens de contrainte pendant tes rapports sexuels ?',
      'Combien de temps te faut-il généralement pour atteindre l\'orgasme ?',
      'As-tu déjà fait l\'amour dans une voiture ? Où étiez-vous garés ?',
      'Qui, parmi les personnes présentes, est le meilleur au lit ?',
      'As-tu déjà essayé la fessée, que ce soit en la donnant ou en la recevant ?',
      'Quelle est la chose la plus audacieuse que tu aies faite pour exciter un partenaire ?',
      'As-tu déjà fait l\'amour alors que d\'autres personnes se trouvaient dans la pièce d\'à côté ?',
      'Tu préfères faire l\'amour dans le noir ou avec la lumière allumée ?',
      'As-tu déjà eu une relation avec quelqu\'un de beaucoup plus âgé ou plus jeune que toi ?',
      'Quel est ton fétiche le plus original ?',
      'As-tu déjà fait l\'amour dans l\'eau, à la piscine ou à la mer ?',
      'Combien de fois par semaine aimerais-tu avoir des relations sexuelles, dans l\'idéal ?',
      'As-tu déjà essayé le sexe les yeux bandés ?',
      'Avec lequel de tes ex serais-tu prêt(e) à recoucher, ne serait-ce que pour une nuit ?',
      'Quelle est la position que tu ne supportes pas au lit ?',
      'As-tu déjà eu un orgasme multiple ?',
      'As-tu déjà léché ou embrassé une partie du corps peu conventionnelle de ton partenaire ?',
      'Quelle est la pensée la plus cochonne que tu aies eue aujourd’hui ?',
      'As-tu déjà couché avec quelqu\'un dont tu ne te souvenais plus du nom ?',
      'L\'idée d\'être regardé pendant que tu fais l\'amour t\'excite-t-elle ?',
      'As-tu déjà utilisé de la nourriture pendant les préliminaires ? Quoi ?',
      'Quel fantasme aimerais-tu réaliser avec l\'une des personnes présentes ?',
      'As-tu déjà fait l\'amour chez les parents de quelqu\'un ?',
      'Sur une échelle de un à dix, quelle importance accordes-tu à l\'apparence physique d\'un partenaire ?',
      'As-tu déjà ressenti de la douleur consensuelle pendant un rapport sexuel et cela t\'a-t-il plu ?',
      'Quelle est la chose la plus bizarre qui t\'ait excité ?',
      'As-tu déjà eu une relation avec deux personnes en même temps ?',
      'Tu te masturbes davantage le matin ou le soir ?',
      'As-tu déjà eu des relations sexuelles par téléphone ou par visioconférence ?',
      'À quel endroit de ton corps aimerais-tu qu\'on t\'embrasse le plus souvent ?',
      'As-tu déjà simulé une scène porno avec un partenaire ?',
      'Avec qui, parmi les personnes présentes, aimerais-tu échanger un baiser avec la langue ?',
      'As-tu déjà eu une relation uniquement pour le sexe ?',
      'Quel a été ton orgasme le plus gênant à expliquer ?',
      'As-tu déjà porté de la lingerie ou des sous-vêtements particuliers pour séduire quelqu\'un ?',
      'Tu aimes dire des mots cochons pendant l\'amour ou ça te met mal à l\'aise ?',
      'As-tu déjà eu des relations sexuelles dans des toilettes publiques ?',
      'Combien de minutes durent généralement tes préliminaires ?',
      'As-tu déjà essayé le sexe tantrique, c\'est-à-dire lent et prolongé ?',
      'Quelle est la chose la plus osée que tu aies jamais demandée au lit ?',
      'As-tu déjà eu des relations sexuelles avec un collègue ou un supérieur hiérarchique ?',
      'Qu\'est-ce qui t\'excite le plus : le sexe fougueux ou le sexe tendre ?',
      'As-tu déjà eu un rendez-vous organisé uniquement en ligne dans le but d\'avoir des relations sexuelles ?',
      'Quelle est la partie de ton corps dont tu es le plus fier au lit ?',
      'As-tu déjà fait l\'amour en plein air, dans une forêt ou dans un parc ?',
      'Si tu étais célibataire ce soir, avec qui parmi les personnes présentes flirterais-tu ?',
      'As-tu déjà eu plusieurs orgasmes au cours d\'un même rapport ?',
      'Quelle est la chose la plus interdite que tu aimerais essayer au moins une fois ?',
      'As-tu déjà eu des relations sexuelles avec quelqu\'un qui avait beaucoup plus d\'expérience que toi ?',
      'Tu aimes être dominé ou tu préfères avoir le contrôle ?',
      'As-tu déjà eu un rapport sexuel sous la douche ou dans une baignoire ?',
      'Quel est ton record de rapports sexuels en une seule journée ?',
      'As-tu déjà embrassé deux personnes au cours d\'une même soirée ?',
      'Dans quelle position te sens-tu le plus sexy ?',
      'As-tu déjà eu des relations sexuelles tout en parlant au téléphone avec quelqu\'un d\'autre ?',
      'T\'est-il déjà arrivé d\'avoir une érection à un moment complètement inopportun ?',
      'As-tu déjà couché avec la mauvaise personne et l\'as-tu regretté ?',
      'Quelle est la chose la plus intime que tu aies confiée uniquement à un partenaire ?',
      'As-tu déjà essayé d\'avoir des relations sexuelles avec un vibromasseur partagé ?',
      'Parmi les personnes présentes, avec laquelle penses-tu avoir le plus d’affinités sexuelles ?',
      'As-tu déjà fait l\'amour sur une table ou une étagère de cuisine ?',
      'Tu aimes regarder des vidéos osées, tout seul ou à deux ?',
      'As-tu déjà eu un rapport sexuel dans un ascenseur ou dans un endroit insolite ?',
      'Quel est le compliment le plus excitant qu\'on t\'ait fait sur ton corps ?',
      'As-tu déjà essayé les jeux de rôle au lit ? Quel scénario ?',
      'Combien de positions différentes arrives-tu à faire au cours d\'un seul rapport ?',
      'As-tu déjà eu un orgasme rien qu\'en te faisant caresser le cou ou les oreilles ?',
      'Qu\'est-ce qui te donne envie de faire l\'amour sur-le-champ ?',
      'As-tu déjà fait l\'amour sous une tente ou en camping ?',
      'T\'es-tu déjà épris de quelqu\'un uniquement pour ses performances au lit ?',
      'As-tu déjà utilisé des huiles ou des crèmes pendant les rapports sexuels ou lors de massages ?',
      'Quelle est la personne présente ici avec laquelle tu n\'as jamais flirté, mais à laquelle tu as pensé ?',
      'As-tu déjà fait l\'amour sans dire un mot de tout le temps ?',
      'Qu\'est-ce qui t\'excite le plus : embrasser le cou ou les lèvres ?',
      'As-tu déjà fait l\'amour dans un hôtel à l\'heure ?',
      'Quelle est la chose la plus déjantée qu\'un partenaire t\'ait proposée ?',
      'As-tu déjà essayé d\'être ligoté, les mains et les pieds ?',
      'Avec qui, parmi les personnes présentes, aimerais-tu passer une nuit passionnée ?',
      'T\'est-il déjà arrivé qu\'un rapport soit interrompu au moment le plus intense ? Par qui ?',
      'Tu préfères faire l\'amour en musique ou dans le silence le plus total ?',
      'As-tu déjà léché de la nourriture sur le corps de ton partenaire ?',
      'Quelle est la fantaisie qui te fait atteindre l\'orgasme le plus rapidement ?',
      'As-tu déjà couché avec quelqu\'un que tu venais de rencontrer en vacances ?',
      'Sur une échelle de un à dix, à quel point fais-tu du bruit au lit ?',
      'As-tu déjà essayé les fessées dans le cadre d\'un jeu érotique ?',
      'Qu\'est-ce qui te rend fou pendant les préliminaires ?',
      'As-tu déjà fait l\'amour dans un endroit où vous risquiez de vous faire surprendre ?',
      'T\'es-tu déjà masturbé dans un lieu public ?',
      'T\'es-tu déjà souhaité que le partenaire actuel ou l\'ex d\'un ami soit là ?',
      'Quel est le moment le plus passionnant dont tu te souviennes avec un partenaire ?',
      'As-tu déjà essayé de faire l\'amour les yeux bandés et les mains liées ?',
      'Avec quelle personnalité célèbre coucherais-tu sans hésiter ?',
      'As-tu déjà fait l\'amour plus de trois fois en une nuit ?',
      'Tu préfères le sexe le matin ou la nuit ?',
      'T\'est-il déjà arrivé d\'embrasser quelqu\'un juste pour un pari et d\'avoir fini par apprécier ça ?',
      'Quelle est la chose la plus érotique que tu aies jamais écrite dans un message ?',
      'As-tu déjà eu des relations sexuelles chez des amis pendant une fête ?',
      'Quel est ton point faible quand quelqu\'un essaie de te séduire ?',
      'As-tu déjà essayé d\'avoir des relations sexuelles avec un accessoire ou un nouveau jouet ?',
      'Avec qui, parmi les personnes présentes, t\'imagines-tu passer une nuit inoubliable ?',
      'As-tu déjà eu des relations sexuelles sur ton lieu de travail ?',
      'Qu\'est-ce qui t\'excite le plus pendant l\'amour : le contact visuel ou les mots ?',
      'As-tu déjà vécu une relation si intense que tu en es resté sans forces ?',
      'Quelle est la chose la plus cochonne que tu aies faite pour satisfaire un partenaire ?',
      'As-tu déjà fait l\'amour sur une plage la nuit ?',
      'Tu aimes qu\'on te morde pendant les rapports sexuels ?',
      'As-tu déjà eu un orgasme si intense que tu en as presque eu honte ?',
      'Quelle est la première partie du corps de votre partenaire que vous embrassez ?',
      'As-tu déjà essayé de faire l\'amour devant un miroir ?',
      'Avec qui, parmi les personnes présentes, partagerais-tu ton secret le plus érotique ?',
      'As-tu déjà couché avec quelqu’un que tu t’étais juré d’éviter ?',
      'Tu préfères prendre l\'initiative ou te laisser séduire ?',
      'As-tu déjà eu un fantasme sur quelqu\'un avec qui tu ne devrais pas en avoir ?',
      'Quelle est la tenue la plus audacieuse que tu porterais pour une soirée spéciale ?',
      'As-tu déjà fait l\'amour sous la pluie, dehors ou près d\'une fenêtre ouverte ?',
      'T\'es-tu déjà excité en regardant quelqu\'un se déshabiller à son insu ?',
      'As-tu déjà eu plusieurs partenaires au cours de la même semaine ?',
      'Quel est le geste qui te fait comprendre d’emblée que tu as envie de quelqu’un au lit ?',
      'T\'est-il déjà arrivé de faire l\'amour et de rire à cause d\'un incident gênant ?',
      'Avec qui, parmi les personnes présentes, aimerais-tu te livrer à un jeu de séduction ?',
      'T\'est-il déjà arrivé d\'avoir des relations sexuelles en pensant à quelqu\'un d\'autre que la personne avec qui tu étais ?',
      'Quelle est la chose la plus excitante que quelqu\'un t\'ait dit vouloir te faire ?',
      'As-tu déjà eu un rapport si silencieux que tu as dû retenir chaque gémissement ?',
      'Quel est le désir sexuel le plus secret que tu n\'as jamais confié à personne ici ?',
    ],
  };
}
