import '../content_tone.dart';

/// Pool gratuito di "Non ho mai": 160 frasi, divise per tono.
/// Ogni frase completa "Non ho mai…".
class NonHoMaiPool {
  const NonHoMaiPool._();

  static const List<({String text, String tone})> entries =
      <({String text, String tone})>[
        // ---------------------------------------------------------- soft
        (text: 'saltato il lavoro o la scuola fingendomi malato', tone: ContentTone.soft),
        (text: 'dormito fino a mezzogiorno passato', tone: ContentTone.soft),
        (text: 'mangiato qualcosa caduto per terra', tone: ContentTone.soft),
        (text: 'cantato sotto la doccia a squarciagola', tone: ContentTone.soft),
        (text: 'finto di conoscere una canzone per non fare brutta figura', tone: ContentTone.soft),
        (text: 'dimenticato il compleanno di un amico stretto', tone: ContentTone.soft),
        (text: 'perso un treno o un aereo', tone: ContentTone.soft),
        (text: 'viaggiato da solo', tone: ContentTone.soft),
        (text: 'rotto un osso', tone: ContentTone.soft),
        (text: 'fatto un tatuaggio', tone: ContentTone.soft),
        (text: 'tinto i capelli di un colore assurdo', tone: ContentTone.soft),
        (text: 'mandato un messaggio alla persona sbagliata', tone: ContentTone.soft),
        (text: 'finto di ridere a una battuta che non avevo capito', tone: ContentTone.soft),
        (text: 'parlato da solo ad alta voce', tone: ContentTone.soft),
        (text: 'pianto guardando un film', tone: ContentTone.soft),
        (text: 'guardato una stagione intera in un giorno', tone: ContentTone.soft),
        (text: 'mangiato la pizza con le posate', tone: ContentTone.soft),
        (text: 'messo l\'ananas sulla pizza', tone: ContentTone.soft),
        (text: 'cucinato qualcosa di immangiabile', tone: ContentTone.soft),
        (text: 'bruciato la cena', tone: ContentTone.soft),
        (text: 'dimenticato il fornello acceso', tone: ContentTone.soft),
        (text: 'chiuso le chiavi dentro casa', tone: ContentTone.soft),
        (text: 'dimenticato dove avevo parcheggiato', tone: ContentTone.soft),
        (text: 'preso una multa', tone: ContentTone.soft),
        (text: 'fatto finta di non vedere un conoscente per strada', tone: ContentTone.soft),
        (text: 'inventato una scusa per non uscire', tone: ContentTone.soft),
        (text: 'cancellato un piano all\'ultimo minuto', tone: ContentTone.soft),
        (text: 'detto "arrivo tra cinque minuti" mentre ero ancora a casa', tone: ContentTone.soft),
        (text: 'fatto la spesa affamato', tone: ContentTone.soft),
        (text: 'comprato qualcosa che non ho mai usato', tone: ContentTone.soft),
        (text: 'speso troppo per una cosa inutile', tone: ContentTone.soft),
        (text: 'venduto qualcosa online', tone: ContentTone.soft),
        (text: 'partecipato a una gara', tone: ContentTone.soft),
        (text: 'vinto un premio', tone: ContentTone.soft),
        (text: 'cantato al karaoke', tone: ContentTone.soft),
        (text: 'ballato senza musica', tone: ContentTone.soft),
        (text: 'suonato uno strumento davanti a qualcuno', tone: ContentTone.soft),
        (text: 'scritto una poesia', tone: ContentTone.soft),
        (text: 'tenuto un diario', tone: ContentTone.soft),
        (text: 'dormito in aeroporto', tone: ContentTone.soft),
        (text: 'dormito in macchina', tone: ContentTone.soft),
        (text: 'dormito in tenda', tone: ContentTone.soft),
        (text: 'fatto il bagno di notte al mare', tone: ContentTone.soft),
        (text: 'nuotato in un lago', tone: ContentTone.soft),
        (text: 'avuto paura del buio da grande', tone: ContentTone.soft),
        (text: 'dormito con la luce accesa', tone: ContentTone.soft),
        (text: 'urlato per un incubo', tone: ContentTone.soft),
        (text: 'camminato nel sonno', tone: ContentTone.soft),
        (text: 'russato tanto da svegliare qualcuno', tone: ContentTone.soft),
        (text: 'mangiato a letto', tone: ContentTone.soft),
        (text: 'saltato la colazione per una settimana intera', tone: ContentTone.soft),
        (text: 'bevuto un caffè dimenticato e ormai freddo', tone: ContentTone.soft),
        (text: 'rovesciato qualcosa addosso a qualcuno', tone: ContentTone.soft),
        (text: 'rotto qualcosa di prezioso senza dirlo', tone: ContentTone.soft),
        (text: 'incolpato qualcun altro per una cosa mia', tone: ContentTone.soft),
        (text: 'copiato a un compito in classe', tone: ContentTone.soft),
        (text: 'finito un lavoro all\'ultima notte utile', tone: ContentTone.soft),
        (text: 'mandato una mail senza l\'allegato', tone: ContentTone.soft),
        (text: 'sbagliato il nome di una persona in faccia', tone: ContentTone.soft),
        (text: 'dimenticato una password importante', tone: ContentTone.soft),
        (text: 'cercato il mio nome su internet', tone: ContentTone.soft),
        (text: 'bloccato qualcuno sui social', tone: ContentTone.soft),
        (text: 'pubblicato qualcosa e cancellato dopo cinque minuti', tone: ContentTone.soft),
        (text: 'finto che il telefono fosse scarico per non rispondere', tone: ContentTone.soft),
        (text: 'risposto dopo giorni fingendo di non aver visto', tone: ContentTone.soft),
        (text: 'usato il Wi-Fi di qualcun altro senza chiedere', tone: ContentTone.soft),
        (text: 'cantato in macchina fissando gli altri automobilisti', tone: ContentTone.soft),
        (text: 'ballato da solo in ascensore', tone: ContentTone.soft),
        (text: 'parlato con un animale come se capisse tutto', tone: ContentTone.soft),
        (text: 'dato un nome alla mia macchina', tone: ContentTone.soft),
        (text: 'fatto una promessa che sapevo di non mantenere', tone: ContentTone.soft),
        (text: 'mentito sulla mia età', tone: ContentTone.soft),
        (text: 'esagerato quanto mi era piaciuto un regalo', tone: ContentTone.soft),
        (text: 'ridato a qualcun altro un regalo ricevuto', tone: ContentTone.soft),
        (text: 'tenuto per anni una cosa prestata', tone: ContentTone.soft),
        (text: 'prestato dei soldi senza rivederli', tone: ContentTone.soft),
        (text: 'chiesto un aumento', tone: ContentTone.soft),
        (text: 'cambiato lavoro di punto in bianco', tone: ContentTone.soft),
        (text: 'lavorato durante una vacanza', tone: ContentTone.soft),
        (text: 'fatto un colloquio per un posto che non volevo', tone: ContentTone.soft),
        (text: 'mangiato al fast food due volte nello stesso giorno', tone: ContentTone.soft),
        (text: 'mangiato il gelato a colazione', tone: ContentTone.soft),
        (text: 'fatto ore di fila per qualcosa', tone: ContentTone.soft),
        (text: 'dimenticato un appuntamento importante', tone: ContentTone.soft),
        (text: 'litigato per il telecomando', tone: ContentTone.soft),
        (text: 'guardato lo stesso film più di cinque volte', tone: ContentTone.soft),
        (text: 'imparato a memoria una scena di un film', tone: ContentTone.soft),
        (text: 'perso una scommessa stupida', tone: ContentTone.soft),
        (text: 'vinto a carte barando', tone: ContentTone.soft),
        (text: 'rotto uno schermo del telefono', tone: ContentTone.soft),
        (text: 'lasciato il telefono in un locale', tone: ContentTone.soft),
        // ------------------------------------------------------ piccante
        (text: 'baciato qualcuno la prima sera', tone: ContentTone.piccante),
        (text: 'avuto una cotta per qualcuno di questo gruppo', tone: ContentTone.piccante),
        (text: 'avuto una cotta per il partner di un amico', tone: ContentTone.piccante),
        (text: 'scritto a un ex nel cuore della notte', tone: ContentTone.piccante),
        (text: 'risposto a un ex dopo mesi di silenzio', tone: ContentTone.piccante),
        (text: 'finto di dormire per evitare una conversazione', tone: ContentTone.piccante),
        (text: 'mentito a chi stavo frequentando', tone: ContentTone.piccante),
        (text: 'controllato il telefono di un partner', tone: ContentTone.piccante),
        (text: 'avuto due appuntamenti nello stesso giorno', tone: ContentTone.piccante),
        (text: 'baciato due persone nella stessa serata', tone: ContentTone.piccante),
        (text: 'detto "ti amo" senza pensarlo davvero', tone: ContentTone.piccante),
        (text: 'chiuso una storia con un messaggio', tone: ContentTone.piccante),
        (text: 'rimesso insieme i pezzi con un ex', tone: ContentTone.piccante),
        (text: 'avuto una storia a distanza', tone: ContentTone.piccante),
        (text: 'tenuto nascosta una relazione', tone: ContentTone.piccante),
        (text: 'flirtato per ottenere qualcosa', tone: ContentTone.piccante),
        (text: 'usato un\'app di incontri', tone: ContentTone.piccante),
        (text: 'usato una foto profilo di dieci anni fa', tone: ContentTone.piccante),
        (text: 'incontrato dal vivo qualcuno conosciuto online', tone: ContentTone.piccante),
        (text: 'dedicato una canzone a qualcuno presente in questa stanza', tone: ContentTone.piccante),
        (text: 'scritto una lettera d\'amore', tone: ContentTone.piccante),
        (text: 'ballato lentamente con uno sconosciuto', tone: ContentTone.piccante),
        (text: 'dormito a casa di qualcuno appena conosciuto', tone: ContentTone.piccante),
        (text: 'perso il conto di quanto avevo bevuto', tone: ContentTone.piccante),
        (text: 'fatto qualcosa di imbarazzante da ubriaco', tone: ContentTone.piccante),
        (text: 'rimpianto la mattina dopo i messaggi della sera prima', tone: ContentTone.piccante),
        (text: 'dimenticato pezzi di una serata intera', tone: ContentTone.piccante),
        (text: 'cantato per strada alle quattro di notte', tone: ContentTone.piccante),
        (text: 'fatto il bagno senza costume', tone: ContentTone.piccante),
        (text: 'girato per casa senza vestiti con qualcuno in visita', tone: ContentTone.piccante),
        (text: 'dimenticato di chiudere la porta del bagno', tone: ContentTone.piccante),
        (text: 'avuto un appuntamento al buio', tone: ContentTone.piccante),
        (text: 'detto una bugia enorme a un primo appuntamento', tone: ContentTone.piccante),
        (text: 'finto di essere single', tone: ContentTone.piccante),
        (text: 'spiato il profilo del nuovo partner del mio ex', tone: ContentTone.piccante),
        (text: 'litigato in pubblico con un partner', tone: ContentTone.piccante),
        (text: 'fatto pace con un bacio senza chiarire niente', tone: ContentTone.piccante),
        (text: 'baciato qualcuno per una scommessa', tone: ContentTone.piccante),
        (text: 'rimpianto una risposta data a Obbligo o Verità', tone: ContentTone.piccante),
        (text: 'rivelato il segreto di un amico', tone: ContentTone.piccante),
        (text: 'origliato una conversazione privata', tone: ContentTone.piccante),
        (text: 'finto di non sapere una cosa che sapevo benissimo', tone: ContentTone.piccante),
        (text: 'avuto un flirt sul posto di lavoro', tone: ContentTone.piccante),
        (text: 'scritto al capo cose che non avrei dovuto', tone: ContentTone.piccante),
        (text: 'portato via una penna dall\'ufficio', tone: ContentTone.piccante),
        (text: 'mangiato il pranzo di un collega', tone: ContentTone.piccante),
        (text: 'dato buca a un appuntamento senza avvisare', tone: ContentTone.piccante),
        (text: 'finto di stare male per evitare un invito', tone: ContentTone.piccante),
        (text: 'saltato un matrimonio all\'ultimo momento', tone: ContentTone.piccante),
        (text: 'pianto in bagno durante una festa', tone: ContentTone.piccante),
        (text: 'dormito al cinema durante un appuntamento', tone: ContentTone.piccante),
        (text: 'conservato una foto imbarazzante di un amico', tone: ContentTone.piccante),
        (text: 'condiviso lo screenshot di una chat privata', tone: ContentTone.piccante),
        (text: 'creato un profilo falso', tone: ContentTone.piccante),
        (text: 'scrollato il profilo di qualcuno fino a tre anni fa', tone: ContentTone.piccante),
        (text: 'risposto a una storia solo per farmi notare', tone: ContentTone.piccante),
        (text: 'mentito su dove stavo passando la serata', tone: ContentTone.piccante),
        (text: 'detto di essere a casa mentre ero fuori', tone: ContentTone.piccante),
        (text: 'nascosto una relazione alla mia famiglia', tone: ContentTone.piccante),
        (text: 'presentato qualcuno ai miei troppo presto', tone: ContentTone.piccante),
        (text: 'baciato qualcuno di cui non ricordavo il nome', tone: ContentTone.piccante),
        (text: 'chiesto a un amico di chiamarmi per scappare da un appuntamento', tone: ContentTone.piccante),
        (text: 'lasciato un locale di nascosto per non salutare', tone: ContentTone.piccante),
        (text: 'finito la serata in un posto che non ricordo', tone: ContentTone.piccante),
        (text: 'dormito vestito e con le scarpe addosso', tone: ContentTone.piccante),
        (text: 'finto un compleanno per avere il dolce gratis', tone: ContentTone.piccante),
        (text: 'detto una bugia durante questa partita', tone: ContentTone.piccante),
        (text: 'giudicato qualcuno solo dalla foto profilo', tone: ContentTone.piccante),
        (text: 'ghostato qualcuno senza spiegazioni', tone: ContentTone.piccante),
        (text: 'riletto una vecchia chat per nostalgia', tone: ContentTone.piccante),
      ];

  static int get length => entries.length;
}
